### ISSUE TITLE
Improve external repository integration

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_go#1]
See [this mailing list thread](https://groups.google.com/forum/#!searchin/bazel-discuss/santiago/bazel-discuss/qeeQEQCQlo8/A3DYgQlwCgAJ) and https://github.com/bazelbuild/bazel/issues/997.

Right now, go rules are very inconvenient to use with external repositories.

**Comment by yugui** [comment]
Fixed in #30.
