### ISSUE TITLE
go_embed_data generates file in bazel-bin/ instead of bazel-genfiles/

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1006]
Hi, 

I found that `go_embed_data`  throws output to `bazel-bin` instead of `bazel-genfiles`, which seems a bug to me.  Could you take a look?

BUILD.bazel

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_embed_data")

go_embed_data(
    name = "file_embed",
    srcs = ["main.go"],
    package = "main",
    out = "main_embed.go",
)

go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
        "main_embed.go",
    ],
    importpath = "test",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "test",
    importpath = "test",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```

main.go

```
package main

import "fmt"

func main() {
	fmt.Println("Hello world")
}
```

```shell
$ l bazel-genfiles/
$ l bazel-bin/
total 2808
-r-xr-xr-x  1 xiaoyi  wheel      244 Nov  9 17:51 main_embed.go*
-r-xr-xr-x  1 xiaoyi  wheel  1429392 Nov  9 17:51 test*
drwxr-xr-x  4 xiaoyi  wheel      136 Nov  9 17:50 test.runfiles/
-r-xr-xr-x  1 xiaoyi  wheel      131 Nov  9 17:50 test.runfiles_manifest*
drwxr-xr-x  3 xiaoyi  wheel      102 Nov  9 17:51 ~stripped~go_default_library~/
drwxr-xr-x  3 xiaoyi  wheel      102 Nov  9 17:51 ~stripped~test~/
```

**Comment by ianthehat** [comment]
bazel-genfiles is deprecated, nothing should use it any more.

From the documentation

>    output_to_genfiles:
>    If true, the files will be generated in the genfiles directory instead of the bin directory. 
>    Unless you need it for compatibility with existing rules (e.g. when generating header files for C++),
>    do not set this flag.

**Comment by jayconrod** [comment]
+1 to what Ian said. I'm unsure of the history of genfiles. I think it has to do with generated, platform-specific C/C++ header files. Other than that specific case, it's preferred that all output files  go in a single tree under bazel-bin.

**Comment by ashi009** [comment]
Thanks for the quick response. 

I'm asking this mainly due to https://groups.google.com/d/topic/bazel-discuss/OVN0t4bYWMQ, as I'm using [unionfs](https://github.com/hanwen/go-fuse/blob/master/example/unionfs/main.go) to join workspace and `bazel-genfiles/` to `${GOPATH}/src/${PREFIX}`. So the standard go tools can find generated photo libraries source.

To make embedded files work, I'll have to join `bazel-bin/` as well.  Which will also add `go_default_test_*.go` file to the `$GOPATH`, and go standard tool will start to complaint that `import "test/pkg1" is a program, not an importable package`. Though it won't break the toolchain for now, it's definitely annoying. 

pkg1/lib1.go

```
package pkg1

func A() {}
```

lib1_test.go
```
package pkg1

import "testing"

func TestA(t *testing.T) {}
```

BUILD.bazel
```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["lib1.go"],
    importpath = "test/pkg1",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["lib1_test.go"],
    importpath = "test/pkg1",
    library = ":go_default_library",
)
```

```shell
$ ls ~/go/src/test/pkg1/
BUILD.bazel                         go_default_test_main_test.go        ~stripped~go_default_library~
go_default_test.runfiles            lib1.go                             ~stripped~go_default_test~library~~
go_default_test.runfiles_manifest   lib1_test.go
```

**Comment by jayconrod** [comment]
I won't claim to have a good story for this. Our long-term plan is to get the Go tools to work with Bazel and other build tools. People on the Go team are actively working on this.

Have you looked at the `go_path` rule? I'm not sure whether it would be useful in this case, but it might be worth taking a look. See [BUILD.bazel](https://github.com/bazelbuild/rules_go/blob/master/BUILD.bazel#L33) for an example.

**Comment by ashi009** [comment]
Yeah, I saw that.  It's an option, but manually putting `go_path` across all libraries just doesn't scale.

I'll go ahead with a patched `unionfs` to filter out all `*_main_test.go` for now.

**Comment by ashi009** [comment]
Yeah, I saw that.  It's an option, but manually putting `go_path` across all libraries just doesn't scale.

I'll go ahead with a patched `unionfs` to filter out all `*_main_test.go` for now. (Which I believe is also godoc server friendly.)

Thanks!
