### ISSUE TITLE
Error: "Archive mode does not match [target] is race_stripped expected stripped"

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#1008]
I tried updating `kubernetes/test-infra` to the latest version of `rules_go` (9556bc88d7d240d3bcbf07d24282953eb1687ef3) and re-ran gazelle. Now when I run tests, I'm getting a weird error:

```
ERROR: .../code/kubernetes/src/k8s.io/test-infra/mungegithub/mungers/BUILD:9:1: in go_test rule //mungegithub/mungers:go_default_test: 
Traceback (most recent call last):
        File ".../code/kubernetes/src/k8s.io/test-infra/mungegithub/mungers/BUILD", line 9
                go_test(name = 'go_default_test')
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/rules/test.bzl", line 90, in _go_test_impl
                go_toolchain.actions.binary(ctx, go_toolchain, name = ctx.label...., <6 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 36, in go_toolchain.actions.binary
                go_toolchain.actions.library(ctx, go_toolchain = go_toolchain, mo..., <6 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/library.bzl", line 120, in go_toolchain.actions.library
                go_toolchain.actions.archive(ctx, go_toolchain = go_toolchain, mo..., <4 more arguments>)
        File ".../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 96, in go_toolchain.actions.archive
                fail("Archive mode does not match {} ...)))
Archive mode does not match //vendor/gopkg.in/yaml.v2:go_default_library is race_stripped expected stripped
ERROR: Analysis of target '//mungegithub/mungers:go_default_test' failed; build aborted: Analysis of target '//mungegithub/mungers:go_default_test' failed; build aborted
```

Our `.bazelrc` contains `test --features=race`; if I remove `--features=race` it builds properly.

**Comment by ixdy** [comment]
Clone https://github.com/ixdy/kubernetes-test-infra/tree/cc7fe3b9ea493f159f7b9c940d889de75d44aad5 if you want to repro.

**Comment by ianthehat** [comment]
Took me all day to find this but...

https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/BUILD#L28

don't do that :)

**Comment by ixdy** [comment]
Ah, well, that used to work. :)

Is there a better way to enable race detection on all tests by default but exclude some tests?

**Comment by ianthehat** [comment]
It might have done, but it would not have done what you think (only that library would have had race turned off, not all the ones it depended on).
I did not bother because it did not seem useful, I could add a race=on/off (like the pure and static ones), it's easy and it would work, if you need it (is race just too expensive on that target?)
The problem is, there is no way to override it once you set it on a test, you will only be able to run that test with race turned on by modifying the build file (which is why I did not bother)

**Comment by ixdy** [comment]
In our case, this particular package is known to be racy (or at least the tests are), but because we're deprecating that code, it isn't worth fixing.

**Comment by ixdy** [comment]
It seems like the fix in #1010 isn't working properly, or I'm misunderstanding how to use it.

I removed `features = ["-race"]` from the go_test rule and added `race = "off"`, but now it complains about missing dependencies:
```
ERROR: .../code/kubernetes/src/k8s.io/test-infra/mungegithub/mungers/BUILD:9:1: Couldn't build file mungegithub/mungers/~stripped~go_default_test~library~~/k8s.io/test-infra/mungegithub/mungers.a: GoCompile mungegithub/mungers/~stripped~go_default_test~library~~/k8s.io/test-infra/mungegithub/mungers.a failed (Exit 1)
2017/11/13 12:48:40 missing strict dependencies:
        mungegithub/mungers/approval-handler.go: import of k8s.io/test-infra/mungegithub/mungers/approvers, which is not a direct dependency
        mungegithub/mungers/approval-handler.go: import of k8s.io/test-infra/mungegithub/mungers/matchers/event, which is not a direct dependency
        mungegithub/mungers/block_paths.go: import of k8s.io/kubernetes/pkg/util/yaml, which is not a direct dependency
        mungegithub/mungers/check-labels.go: import of k8s.io/kubernetes/pkg/util/yaml, which is not a direct dependency
        mungegithub/mungers/inactive-review-handler.go: import of k8s.io/test-infra/mungegithub/mungers/matchers, which is not a direct dependency
        mungegithub/mungers/milestone-maintainer.go: import of k8s.io/test-infra/mungegithub/mungers/approvers, which is not a direct dependency
        mungegithub/mungers/milestone-maintainer.go: import of k8s.io/test-infra/mungegithub/mungers/matchers/event, which is not a direct dependency
        mungegithub/mungers/submit-queue.go: import of k8s.io/test-infra/mungegithub/mungers/shield, which is not a direct dependency
        mungegithub/mungers/submit-queue.go: import of github.com/NYTimes/gziphandler, which is not a direct dependency
        mungegithub/mungers/submit-queue.go: import of github.com/prometheus/client_golang/prometheus, which is not a direct dependency
```

https://github.com/ixdy/kubernetes-test-infra/tree/ce9b0e86825253227fade74d35a6b90ce584a225 is the git tree I'm using to repro.

**Comment by ianthehat** [comment]
You are still using the legacy `library = ":go_default_library", `form instead of the correct `embed = [":go_default_library"], ` form.
Sorry, I forgot to mention you also need to fix that.
I tested 1010 on test-infra as I was writing it, and it did the right thing...
Except for the fact that you can't build //... because there is a bunch of stuff in vendor that does not build.

**Comment by ixdy** [comment]
I think gazelle needs to be updated - it keeps adding `library =` attribute back. (I also would've expected gazelle to rewrite the library attributes into embed.)

**Comment by jayconrod** [comment]
Sorry, I should have fixed this a long time ago. #1017 will update Gazelle to generate embed instead of library.
