### ISSUE TITLE
go_grpc_library output not created

### ISSUE THREAD

**Issue by spikecurtis** [bazelbuild/rules_go#1012]
I'm having trouble getting `go_grpc_library` rule working.  When I build I get

```
bazel build //... 
INFO: Found 51 targets...
ERROR: /home/spike/go/src/tigera.io/dikastes/proto/BUILD:3:1: output 'proto/go_default_library/tigera.io/dikastes/proto/authz.pb.go' was not created.
ERROR: /home/spike/go/src/tigera.io/dikastes/proto/BUILD:3:1: not all outputs were created or valid.
```
What does this mean?  How can I get more info?

I'm pulling into `WORKSPACE` with

```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.7.0/rules_go-0.7.0.tar.gz",
    sha256 = "91fca9cf860a1476abdc185a5f675b641b60d3acf0596679a27b580af60bf19c",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains", "go_repository")
go_rules_dependencies()
go_register_toolchains()

load("@io_bazel_rules_go//proto:def.bzl", "proto_register_toolchains")
proto_register_toolchains()
```

and my build file looks like

```
load("@io_bazel_rules_go//proto:def.bzl", "go_grpc_library")

go_grpc_library(
    name = "go_default_library",
    proto = ":authz_proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "authz_proto",
    srcs = ["authz.proto"],
)
```

**Comment by jayconrod** [comment]
Do you have an `option go_package` statement in your .proto file? Make sure that matches whatever you expect the import path to be. You may also want to specify the `importpath` attribute on the `go_grpc_library` rule.

**Comment by spikecurtis** [comment]
@jayconrod that worked.  Happy to have this closed, unless you want to keep open to track unhelpful error message as a bug.  Cheers!

**Comment by jayconrod** [comment]
Glad to hear it worked. I'll close this now. We'll most likely make `importpath` mandatory in the future as part of removing `go_prefix`, which should reduce the chance of error.
