### ISSUE TITLE
Significant slow down in build time

### ISSUE THREAD

**Issue by ivyxyz** [bazelbuild/rules_go#1013]
Using commit 9556bc88d7d240d3bcbf07d24282953eb1687ef3, the build slows down significantly with heavy disk io. Looks like the stdlib code is copying the entire go toolchain on every target.

https://github.com/bazelbuild/rules_go/commit/7c664db6ddf82a24bcc4c49a62e08b7bbbf18e01#diff-b1e7c11591fbac0890652d29a78d6222R93

Running `inotifywait -mr .` at `~/.cache/bazel/_bazel_user/sha` along with `bazel build ...`, there are lots of outputs:

```
./bazel-sandbox/different_number/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/

./bazel-sandbox/3175211375642440610/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/src/cmd/go/testdata/importcom/src/wrongplace/ DELETE_SELF 
./bazel-sandbox/7145389296667911019/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/src/runtime/ CREATE timestub.go
./bazel-sandbox/8657867472004421131/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/src/cmd/go/testdata/src/vend/vendor/vend/dir1/ DELETE_SELF 
./bazel-sandbox/3175211375642440610/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/src/cmd/go/testdata/importcom/src/ DELETE,ISDIR wrongplace
./bazel-sandbox/3144955954922670518/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/src/sync/atomic/ CREATE asm_nacl_arm.s

./bazel-sandbox/3144955954922670518/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/pkg/linux_amd64/math/ DELETE big.a
./bazel-sandbox/3144955954922670518/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/pkg/linux_amd64/math/ DELETE cmplx.a
./bazel-sandbox/3144955954922670518/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/pkg/linux_amd64/math/ DELETE rand.a
./bazel-sandbox/3144955954922670518/execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/pkg/linux_amd64/math/ DELETE_SELF 
```

**Comment by jayconrod** [comment]
@ianthehat This is likely a consequence of cross-compiling the standard library. Is there any way we can speed this up in common cases, e.g., for non-cross builds and local toolchains?

**Comment by ianthehat** [comment]
I was expecting a small but not noticeable slowdown, on my test builds it was not a relevant difference.
We do have to map the entire standard library into the sandbox now where we used to use an absolute non sandboxed path, but it should just be building soft links not copying, and it's not that many files (compared to mapping all the includes in c++ rules for instance) so I am surprised it is noticeable.
What kind of speed difference are you seeing, on what kind of machine, an building what kind of code?

There are things we can do to make it faster in the future, the biggest of which is precise standard library dependancies, which means we only have to map the bits that are actually used. I am also hoping that when sandboxfs arrives it means we get to just pass a map to it, not have to replicate the mapping on an actual file system.

I would be interested to know if your build is back to the same speed as before if you run without th sandbox.

**Comment by ixdy** [comment]
The `kubernetes/test-infra` build has also gotten noticeably slower after updating our rules_go dependency.

For a `bazel build -- //... -//vendor/...`,

Using rules_go @ c72631a220406c4fae276861ee286aaec82c5af2: `INFO: Elapsed time: 28.117s, Critical Path: 6.87s`

Using rules_go @ 6d900bc95ae678bec5c91031b8e987957d2a7f93: `INFO: Elapsed time: 80.493s, Critical Path: 22.86s`


`bazel test -- //... -//vendor/...` is similarly bad.
Using rules_go @ c72631a220406c4fae276861ee286aaec82c5af2: `INFO: Elapsed time: 62.435s, Critical Path: 25.51s`

Using rules_go @ 6d900bc95ae678bec5c91031b8e987957d2a7f93: `INFO: Elapsed time: 121.286s, Critical Path: 45.26s`

**Comment by ianthehat** [comment]
If that's a clean build, I would expect it to be much longer than before, you are building the entire standard library in two modes (pure and not) from source where before you were just using the installed version. But building the standard library will only happen once for most people, so I did not optimize for that case.
Even for build machines, when we get the distributed cache building the standard library will *always* be a cache hit, so the cost should be small.

**Comment by ixdy** [comment]
It might be self-inflicted pain, but since we set `test --features=race` on our repo bazelrc, it seems like everything gets rebuilt when we switch between `bazel build` and `bazel test`, which didn't seem to be the case before. (Or maybe it was, but it didn't take nearly as long as it does now.)

**Comment by ianthehat** [comment]
normal and race builds of libraries are now fully independent, which they need to be.
Binaries however need to build their output executable in the mode they have been asked to build, so they will get re-linked (not compiled, just linked) every time you switch. 

There is an issue though that if you compile tools then they will also be built in race mode, and then if you use those tools in the build their outputs will be invalidated because they have been re-linked.
I have already filed a bug against bazel because I cannot detect cfg=host in order to override the race decision, which would prevent this.

In the mean time, it would probably be better to just set race=True on all the tests (we can add an option to gazelle for this) and then not use --featues=race. Then everything will be stable (and also your builds will be faster because you won't be running tools with race detection enabled....)

**Comment by ivyxyz** [comment]
The go_stdlib_linux_amd64_cgo directory is about 35M. I'm using a rotating disk, 4 cores with `bazel build -j 10`. This means it will try to copy >350M instantly when I start the build, and my system seems to freeze. Even Ctrl-C takes a while to stop bazel. The only way to proceed without heavy disk io is using `-j 1`.

**Comment by ianthehat** [comment]
It should not be copying those files, just making links, so the size does not matter just the count.

**Comment by ixdy** [comment]
Similarly, I updated kubernetes/kubernetes to latest rules_go and tried a clean build of `//build/release-tars`.

With rules_go @ c72631a220406c4fae276861ee286aaec82c5af2: `INFO: Elapsed time: 147.930s, Critical Path: 77.39s`
With rules_go @ 6d900bc95ae678bec5c91031b8e987957d2a7f93: `INFO: Elapsed time: 332.336s, Critical Path: 108.21s`

I haven't yet examined what is exactly causing this slowdown, but this feels like a pretty worrying regression.

**Comment by jayconrod** [comment]
I understand why #1023 fixes this issue now. Mini-postmortem time:

The key change was wrapping the `direct` argument to `emit_archive` in a `depset`. Semantically, it seems like this shouldn't do anything other than deduplicating elements, but it's significant for performance.

When you build a `depset`, Bazel de-duplicates the direct elements (`GoArchive` structs) and the transitive elements (`SkylarkNestedSet`s). De-duplication is performed something resembling a Java  `HashSet`. So Bazel will call `equals` and `hashCode` for all of these. `NestedSet` does not override `equals` or `hashCode`, so it has referential equality as far as deduplication is concerned. `SkylarkList` has structural equality, so calling these methods can be very expensive. This is why the stack shows Bazel getting bogged down computing the hash code of alternating structs and lists.

We should make sure we're never storing transitive information in a list or tuple in a struct that ends up in  a depset.

Note that the referential equality of depsets affects the equality of providers. We should be careful not to rely on providers being de-duplicated in depsets.

**Comment by ivyxyz** [comment]
Thanks, I will have a try once the #1023 fix is in. I'm not sure if that fixes heavy io, because I see very low cpu usage and high iowait for writing in bazel-sandbox.

**Comment by ivyxyz** [comment]
I tested 534cc6c1f0ce3b1ed6297cbc665c4c23af9143cc, and the heavy io still exists.

**Comment by ixdy** [comment]
I think @ivyxyz might be onto something regarding io.

We've noticed a pretty significant slowdown in build times in kubernetes/test-infra.

Trying to understand what's happening, I tried building the kubetest binary with rules_go at c72631a220406c4fae276861ee286aaec82c5af2 ("old") and at 95b702c5331b5d01445fe485c25fc80f3f9e0dcf ("new").

At "old":
```
=== EXECUTION PHASE INFORMATION ===

Total preparation time                   2.69 ms
Total execution phase time               2.725 s
Total time finalizing build              5.08 ms

Action dependency map creation           0.00 ms
Actual execution time                    2.725 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.11%       27     0.55 ms
    ACTION_EXECUTE   37.55%       27      192 ms
   ACTION_COMPLETE    0.01%       27     0.06 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    0.13%     3799     0.00 ms
           VFS_DIR    0.07%      729     0.01 ms
      VFS_READLINK    0.00%       24     0.00 ms
           VFS_MD5    1.51%       28     7.45 ms
        VFS_DELETE    0.12%     1059     0.02 ms
          VFS_OPEN    0.00%        4     0.04 ms
         VFS_WRITE    0.00%        3     0.01 ms
              WAIT    0.53%       19     3.88 ms
     SKYFRAME_EVAL   19.73%        1     2.723 s
       SKYFUNCTION   40.21%      677     8.20 ms

Critical path (2.659 s):
    Id        Time Percentage   Description
 28071      526 ms   19.77%   action 'GoLink kubetest/kubetest'
 28070      651 ms   24.48%   action 'GoCompile kubetest/~normal~kubetest~/k8s.io/test-infra/kubetest.a'
 28069      710 ms   26.71%   action 'GoCompile vendor/golang.org/x/crypto/ssh/~normal~go_default_library~/golang.org/x/crypto/ssh.a'
 28068     95.3 ms    3.59%   action 'GoCompile vendor/golang.org/x/crypto/ed25519/~normal~go_default_library~/golang.org/x/crypto/ed25519.a'
 28067      165 ms    6.20%   action 'GoCompile vendor/golang.org/x/crypto/ed25519/internal/edwards25519/~normal~go_default_library~/golang.org/x/crypto/ed25519/internal/edwards25519.a'
 28066      312 ms   11.75%   action 'GoCompile external/io_bazel_rules_go/go/tools/builders/compile [for host]'
 28065      199 ms    7.50%   action 'GoCompile external/io_bazel_rules_go/go/tools/builders/~normal~compile~/github.com/bazelbuild/rules_go/go/tools/builders/compile.a [for host]'
```

At "new":
```
=== EXECUTION PHASE INFORMATION ===

Total preparation time                   2.53 ms
Total execution phase time              14.569 s
Total time finalizing build              4.42 ms

Action dependency map creation           0.00 ms
Actual execution time                   14.569 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.03%       29     0.62 ms
    ACTION_EXECUTE   29.78%       29      685 ms
   ACTION_COMPLETE    0.32%       29     7.38 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    3.61%   565618     0.00 ms
           VFS_DIR    0.62%    17479     0.02 ms
      VFS_READLINK    0.13%    18065     0.00 ms
           VFS_MD5    0.61%      209     1.95 ms
        VFS_DELETE    3.71%   133978     0.02 ms
          VFS_OPEN    0.00%        5     0.04 ms
         VFS_WRITE    0.00%        3     0.01 ms
              WAIT    0.05%      190     0.19 ms
     SKYFRAME_EVAL   21.83%        1    14.567 s
       SKYFUNCTION   39.31%    32276     0.81 ms
   SKYLARK_USER_FN    0.00%       32     0.01 ms

Critical path (14.168 s):
    Id        Time Percentage   Description
146146      894 ms    6.31%   action 'GoLink kubetest/kubetest'
146145      968 ms    6.83%   action 'GoCompile kubetest/~stripped~kubetest~/k8s.io/test-infra/kubetest.a'
146144     1.190 s    8.40%   action 'GoCompile vendor/golang.org/x/crypto/ssh/~stripped~go_default_library~/golang.org/x/crypto/ssh.a'
146143      514 ms    3.63%   action 'GoPack vendor/golang.org/x/crypto/curve25519/~stripped~go_default_library~/golang.org/x/crypto/curve25519.a'
146142      837 ms    5.91%   action 'GoAsmCompile vendor/golang.org/x/crypto/curve25519/~stripped~go_default_library~/ladderstep_amd64.o'
146141      731 ms    5.16%   action 'GoCompile external/io_bazel_rules_go/go/tools/builders/asm [for host]'
146140      578 ms    4.08%   action 'GoCompile external/io_bazel_rules_go/go/tools/builders/~stripped~asm~/github.com/bazelbuild/rules_go/go/tools/builders/asm.a [for host]'
146139     8.454 s   59.67%   action 'SkylarkAction external/go_stdlib_linux_amd64_cgo/bin/go [for host]'
146138     1.49 ms    0.01%   action 'Writing file external/go_stdlib_linux_amd64_cgo/ROOT [for host]'
```

Comparing those two, the amount of VFS operations is much higher with the newer version of the rules. I'm not sure how much of that is attributable to building the go stdlib, though.

**Comment by ixdy** [comment]
Trying to isolate out the go stdlib, I built kubetest, then updated `kubetest/main.go` to change the value of a variable and rebuilt (with cache).

At "old":
```
=== EXECUTION PHASE INFORMATION ===

Total preparation time                   6.58 ms
Total execution phase time               1.133 s
Total time finalizing build              4.89 ms

Action dependency map creation           0.00 ms
Actual execution time                    1.133 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.17%        3     2.04 ms
      ACTION_CHECK    0.04%        3     0.49 ms
    ACTION_EXECUTE   30.84%        3      373 ms
   ACTION_COMPLETE    0.02%        3     0.27 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    0.12%      566     0.01 ms
           VFS_DIR    0.06%      109     0.02 ms
      VFS_READLINK    0.00%        2     0.01 ms
           VFS_MD5    2.91%        4     26.4 ms
        VFS_DELETE    0.19%      160     0.04 ms
          VFS_OPEN    0.01%        4     0.06 ms
          VFS_READ    0.00%        2     0.01 ms
         VFS_WRITE    0.00%        3     0.02 ms
              WAIT    0.00%        2     0.00 ms
     SKYFRAME_EVAL   30.99%        1     1.126 s
       SKYFUNCTION   34.44%       12      104 ms

Critical path (1.122 s):
    Id        Time Percentage   Description
    44      611 ms   54.49%   action 'GoLink kubetest/kubetest'
    43      510 ms   45.51%   action 'GoCompile kubetest/~normal~kubetest~/k8s.io/test-infra/kubetest.a'
```

At "new":
```
=== EXECUTION PHASE INFORMATION ===

Total preparation time                   8.93 ms
Total execution phase time               2.655 s
Total time finalizing build              3.39 ms

Action dependency map creation           0.00 ms
Actual execution time                    2.655 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.04%        3     0.77 ms
      ACTION_CHECK    0.01%        3     0.26 ms
    ACTION_EXECUTE   23.45%        3      511 ms
   ACTION_COMPLETE    0.01%        3     0.17 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    2.03%    24228     0.01 ms
           VFS_DIR    0.50%     1342     0.02 ms
      VFS_READLINK    0.00%        2     0.00 ms
           VFS_MD5    0.94%        4     15.4 ms
        VFS_DELETE    2.70%    10758     0.02 ms
          VFS_OPEN    0.00%        4     0.03 ms
          VFS_READ    0.00%        2     0.00 ms
         VFS_WRITE    0.00%        3     0.01 ms
              WAIT    0.00%        2     0.00 ms
     SKYFRAME_EVAL   28.56%        1     1.867 s
       SKYFUNCTION   29.73%       12      162 ms
   SKYLARK_USER_FN    0.00%        2     0.01 ms

Critical path (1.861 s):
    Id        Time Percentage   Description
    45      860 ms   46.19%   action 'GoLink kubetest/kubetest'
    44     1.001 s   53.81%   action 'GoCompile kubetest/~stripped~kubetest~/k8s.io/test-infra/kubetest.a'
```

**Comment by ianthehat** [comment]
All the speed improvements I have done so far were in the analysis phase, which I hope is much better (you cut it from those reports, so I assume it was).
For the execution phase, my theory is that it's cause by mapping the stdlib into the sandbox, which is bad, but should at least be a constant cost per go target.
#1049 should improve it a bit (it only maps the .a files and tools not the entire stdlib)
If that is the main cause, the only way to improve it further will be to go with fine grained stdlib dependancies, rather than pulling in the entire stdlib I think (although the next step is to verify that there are not still lots of unneeded files being pulled in to the sandbox)

**Comment by ixdy** [comment]
#1049 seems to restore us roughly to the "old" build times, yes.

**Comment by ianthehat** [comment]
#1049 is now in, @ivyxyz can you test again?
If it's not better, can you produce a profile for me?

**Comment by ash2k** [comment]
I've just noticed a build time regression too. Specifically `bazel test` for the project takes 30-40 seconds when it was instantaneous before when there are no changes. This is with 95b702c5331b5d01445fe485c25fc80f3f9e0dcf and updating to the latest master 473ed9b2bf3279bfb52cc85dd3a9d22a2f99d9a6 did not help. If the version is reverted even further - bcc7a4ff5a21ff2640f86cb302a7d976e33d89f1 - it is "fast", takes just 1 second. This is not the last "fast" version, just a version that I used a while ago. 

How to reproduce:
1. Clone https://github.com/atlassian/smith
2. `make setup`
3. Run `make test` several times.

**Comment by ianthehat** [comment]
That sounds like a very different issue, re-running test should mean it needs to do no work at all, no speed multiplier would affect that.
I tried to reproduce, but I could not get it to build at all (possibly related to differing versions of tools on my machine).
If you can try to build with --explain and/or -s, and see what it thinks it is doing, we might be able to explain it. If you find something, please open a new issue with the reports.

**Comment by ivyxyz** [comment]
I tested #1049 and there was no more high io. Thanks.
