### ISSUE TITLE
"pure" and "race" modes are incompatible

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#1016]
In our `.bazelrc` we set `test --features=race` to enable the race detector for all tests.

If I add `pure = "on"` to a `go_binary` rule, `bazel test` then fails with a Go compiler error:

```
ERROR: .../.cache/bazel/_bazel_jgrafton/0eecda305d958f4f4dc699a78d676923/external/go_stdlib_linux_amd64_pure_race/BUILD.bazel:4:1: error executing shell command: 'export GOROOT=$(pwd)/bazel-out/host/bin/external/go_stdlib_linux_amd64_pure_race GOOS=linux GOARCH=amd64 CGO_ENABLED=0 CC=/usr/bin/gcc CXX=/usr/bin/gcc COMPILER_PATH=/usr/bin && mkdir -p bazel-out/...' failed (Exit 2)
go install: -race requires cgo; enable cgo by setting CGO_ENABLED=1
ERROR: .../code/kubernetes/src/k8s.io/test-infra/prow/cmd/hook/BUILD:10:1 error executing shell command: 'export GOROOT=$(pwd)/bazel-out/host/bin/external/go_stdlib_linux_amd64_pure_race GOOS=linux GOARCH=amd64 CGO_ENABLED=0 CC=/usr/bin/gcc CXX=/usr/bin/gcc COMPILER_PATH=/usr/bin && mkdir -p bazel-out/...' failed (Exit 2)
```

Setting `race = "off"` explicitly on the `go_binary` rule solves the issue, but I'm wondering whether this should be necessary. At the very least it should probably be documented.

**Comment by ianthehat** [comment]
It's a limitation of `go build`, which we use to build the SDK. I have no idea why this limitation exists, it does not seem to be documented anywhere, and I am hoping that when we switch to find grained stdlib dependancies it will no longer be a relevant limitation.
