### ISSUE TITLE
crosstool_top is not working

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#1019]
`crosstool_top` is behaving weirdly with rules_go and cross compilation. While I know that cgo cross compilation is not yet supported, I figure I'd put an issue to track it.

How to reproduce:
```
$ bazel build --crosstool_top=@androidndk//:toolchain-libcpp --cpu=arm64-v8a --experimental_platforms=@io_bazel_rules_go//go/toolchain:android_arm64 //:lldbtest_cmd
.................
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 16. The major revisions supported by Bazel are [10, 11, 12, 13, 14]. Defaulting to revision 14.
ERROR: No toolchain found for cpu 'darwin'. Valid cpus are: [
  armeabi,
  armeabi-v7a,
  arm64-v8a,
  mips,
  mips64,
  x86,
  x86_64,
].
$
```

WORKSPACE
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.7.0/rules_go-0.7.0.tar.gz",
    sha256 = "91fca9cf860a1476abdc185a5f675b641b60d3acf0596679a27b580af60bf19c",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains(go_version="host")

android_sdk_repository(
    name="androidsdk",
    api_level=21,
)

android_ndk_repository(
    name="androidndk",
    path = "/Users/steeve/Library/Android/sdk/ndk-bundle/",
    api_level=14,
)
```

**Comment by steeve** [comment]
On a side note, perhaps relying on `crosstool_top` should be all it takes to have cgo cross compilation?

**Comment by ianthehat** [comment]
despite it's name, crosstool does not imply cross compilation, it just describes a compiler... I have a custom crosstool just to build with special clang options.

I think that c++ will soon move to the same platform selection mechanism that go already uses, and --experimental_platforms will cease to be experimental.

I am going to close this bug in favour of #1020 as I will be confused every time I read this issues title :)

**Comment by steeve** [comment]
Awesome, thanks for the quick answer.

For the record I'm in the process of porting golang/mobile to Bazel and this is the biggest road block (as I'm generating `.frameworks` and `.aar` with golang code).
