### ISSUE TITLE
Gazelle fails when multiple proto packages are declared in one directory

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/rules_go#1035]
I have created an example in https://github.com/Xjs/protoTest .

As far as I see it, it might work to have packages.buildPackage return a slice of packages in the proto case, and call the WalkFunc on each of them. The packages are already known in the packageMap, and selectPackage could differentiate between go and proto packages, returning one go package or a MultiplePackageError in the go case, and multiple packages in the proto case.

I am happy to modify gazelle to support this, and send a pull request, but since I'm not very experienced with protobuf handling yet, I would appreciate to get some feedback on this proposal first.

**Comment by jayconrod** [comment]
At the moment, Gazelle only supports one package per directory. Long term, I'd like Gazelle to support multiple packages (Go or proto). There are a few other architecture changes in progress right now (indexed import paths, external dependency management, better empty rule deletion), so I'd prefer to wait until those are in before working on multiple packages.

To work around this, I'd suggest disabling proto rule generation in the directories with multiple proto packages (you can add a `# gazelle:proto disable` comment in the build file), and then writing those rules by hand. Gazelle will continue to update other Go rules in the directory automatically, though you may need `# keep` comments in a few places to preserve dependencies.

**Comment by jayconrod** [comment]
Closing old Gazelle issues. Support for multiple packages is bazelbuild/bazel-gazelle#7. Please file a new issue at bazelbuild/bazel-gazelle if that doesn't cover this though.
