### ISSUE TITLE
Test failure: non-number in go version

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1036]
In [generate_test_main.go](https://github.com/bazelbuild/rules_go/blob/525d7ee547f7554a3d76692bb2f89db6fe502f45/go/tools/builders/generate_test_main.go#L324), we check the Go version number for 1.7 compatibility.

Go version numbers aren't always numbers and dots. For example, development branches may contain other characters.

**Comment by achew22** [comment]
In related pull requests https://github.com/bazelbuild/rules_nodejs/pull/56

Is this a more generalizable pattern?

**Comment by jayconrod** [comment]
@achew22 I don't think there is a generalizable pattern unless a project is really strict about semver. For Go, dev branches and RC numbers can get baked into the version string (which I didn't anticipate when I updated this).

From internal discussion, we decided to drop 1.7 since it's no longer officially supported, and we planned to do so soon anyway. This means that we won't parse version strings in this tool at all.

**Comment by achew22** [comment]
I think the generalization to any project is too much. To me, it appears that many rules_* projects are attempting to validate that they aren't loaded in Bazel < 0.x.y and verifying that the Bazel that's running the current rules_ repo I think is a tractable problem.
