### ISSUE TITLE
Warning with bazel 0.3.1

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_go#104]
When using `rules_go` with bazel 0.3.1 I receive the following WARNING. This isn't a large issue for now, but it will cause an error in future versions.

`WARNING: /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/io_bazel_rules_go_toolchain/WORKSPACE:1: Workspace name in /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/io_bazel_rules_go_toolchain/WORKSPACE (@golang_linux_amd64) does not match the name given in the repository's definition (@io_bazel_rules_go_toolchain); this will cause a build error in future versions.
`

**Comment by hochhaus** [comment]
Thanks!

**Comment by hochhaus** [comment]
I'm still getting this error with bazel 0.3.2 and 2e6cbd84edeedaeb4eb05187230a1b12913b217e.

```
WARNING: /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/golang_linux_amd64/WORKSPACE:1: Workspace name in /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/golang_linux_amd64/WORKSPACE (@io_bazel_rules_go_toolchain) does not match the name given in the repository's definition (@golang_linux_amd64); this will cause a build error in future versions.
```

Can this issue be reopened?

**Comment by pmbethe09** [comment]
Hmm.
I also get this error.
But if instead I put "golang_linux_amd64" in the written WORKSPACE file I
get:

WARNING:
/home/pbethe/.cache/bazel/_bazel_pbethe/cfa212590cbbbf7eafed3d7d9a8d4855/external/golang_linux_amd64/WORKSPACE:1:
Workspace name in
/home/pbethe/.cache/bazel/_bazel_pbethe/cfa212590cbbbf7eafed3d7d9a8d4855/external/golang_linux_amd64/WORKSPACE
(@io_bazel_rules_go_toolchain) does not match the name given in the
repository's definition (@golang_linux_amd64); this will cause a build
error in future versions.

Apparently a better solution is needed.
