### ISSUE TITLE
shard_count is ignored in go_test

### ISSUE THREAD

**Issue by yasushi-saito** [bazelbuild/rules_go#1040]
Specifying shard_count=N in a go_test rule simply results in the test run N times without any sharding. 

Maybe I'm misreading, but I can't find a logic that reads TEST_SHARD_INDEX and TEST_TOTAL_SHARDS environment variables and selects a subset of tests that match the sharding predicate. 

It looks like we would easily add this feature to go/tools/builders/generate_test_main.go

**Comment by jayconrod** [comment]
We haven't implemented sharing yet. You're right, generate_test_main.go would be the place to add it.

**Comment by ianthehat** [comment]
This was fixed in #1259
