### ISSUE TITLE
Gazelle: Idea: Add a mode to use Go import paths as labels for Go library targets

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/rules_go#1058]
I suggest implementing a mode (I presume it would boil down to a Labeler) that labels Go and Proto targets by their Go import paths, such as e. g.

```
go_library(
    name = "github.com/Xjs/example/foo",
    importpath = "github.com/Xjs/example/foo",
    srcs = ["foo/a.go", "foo/b.go"],
    visibility = ["//visbibility:public"],
    deps = ["@com_github_golang_protobuf//:github.com/golang/protobuf/proto"],
)
```

I believe the changes proposed in #1046 (and those which are going to follow up) lay a good ground for making this work solidly for all sorts of go and proto packages.

I have already implemented it (doesn't fully support proto package names yet) in a somewhat hackish façon in an internal fork (not on Github) and successfully built a medium-sized project with some dependencies with it, all with gazelle-generated flat build files, so there seems no obvious issue with Bazel and label names of this kind.

Do you think this is a sensible suggestion? Do you see any reasons why import paths as target labels wouldn't be a good idea?

**Comment by Xjs** [comment]
This is related to #859.

**Comment by jayconrod** [comment]
I'm not sure if you've seen Gazelle's flat mode (enable with the `-experimental_flat` flag on the command line), but this sounds very similar. The difference is that rule names in flat mode are based on directory names, not import path. In most repositories, they're similar though (minus the prefix).

I'd prefer not to change naming too much on top of this, since it makes testing more complicated.

**Comment by Xjs** [comment]
@jayconrod I have seen and used flat mode, but I'm referring specifically to changing the names to *exactly* match the importpaths.

**Comment by ianthehat** [comment]
I'm not sure what the benefit is, but the downside is a seriously painful command line to build a single library
for instance
```
bazel build //Xjs/example/foo:github.com/Xjs/example/foo
```
where if the library were just named foo (which is where we want to get to, not the go_default_library it would be today) you would use
```
bazel build //Xjs/example/foo
```

**Comment by jayconrod** [comment]
I've given this some more thought. I'm now convinced that even flat mode is a bad idea.

Rule names are part of a repository's public interface. When names change, it breaks dependent repositories and forces them to migrate to use the new names.

This is a particularly big issue with repo rules like `new_git_repository`, `new_http_archive`, and `go_repository`, which provide build files for a repository that doesn't have them. These rules effectively imposing a new public interface on another repository. If there are multiple dependent repositories that provide build files that follow different naming conventions for a shared repository (a diamond dependency), that can cause serious issues that may be difficult or impossible to resolve downstream. This conflict is unnecessary and can be avoided by following strict naming conventions.

Flat mode was intended to be a workaround for the fact that `new_git_repository` and `new_http_archive` only accept a single build file. There are enough problems with this, that I think we should abandon flat mode develop repo rules that accept multiple build files instead.

The one change I might consider is getting rid of the `go_default_library` and `go_default_test` names. If we do that, we'll migrate to a single new naming scheme (which would be what @ianthehat said). The naming scheme would not be configurable. We'll have to weigh the cost of the migration against the benefits though; it may already not be viable.
