### ISSUE TITLE
new_go_repository() binary naming

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_go#106]
When using a repository which only contains a binary (eg: [samegoal/teerun](https://github.com/samegoal/teerun)) the binary is named after the full repository (eg `com_github_samegoal_teerun`) instead of just the parent directory (eg: `teerun`).

For example:

```
new_go_repository(
    name = "com_github_samegoal_teerun",
    commit = "515e055985d243cb7f5384b86fa884ebcc0e27df",
    importpath = "github.com/samegoal/teerun",
)
```

Results in the binary `bazel-bin/external/com_github_samegoal_teerun/com_github_samegoal_teerun` when I would expect `bazel-bin/external/com_github_samegoal_teerun/teerun` which is more in line with the default go toolset.

**Comment by hochhaus** [comment]
If I change the name to `teerun` then the binary name is also `teerun`. However, then the naming scheme of my repositories is inconsistent.

Should I just rename the repository or is this something `new_go_repository()` will consider working around?

**Comment by ianthehat** [comment]
You now have full control over both the rule name (from which the binary name is inferred) or explicit setting of the binary name.
