### ISSUE TITLE
Bazel cache getting confused by case-sensitive repository name differences

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_go#1064]
In my workspace I have some docker libs that use the older github.com/Sirupsen/logrus library path, and more modern code that use github.com/sirupsen/logrus (note the difference between Sirupsen and sirupsen).

The Sirupsen one just gets directed to the new one. AFAIK there's no easy way to create an aliased importpath, so I tried pulling in the repositories twice with the two different paths.

That works. I can build the code.

Except that when I try to build the code again, it fails:

```
yves@MacBook-Air:~/src/github.com/nictuku/microclusters/bababot$ bazel build :bababot
WARNING: /private/var/tmp/_bazel_yves/9d2b55ff2a90c4314d8256aee539277a/external/com_github_sirupsen_logrus/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_yves/9d2b55ff2a90c4314d8256aee539277a/external/com_github_sirupsen_logrus/WORKSPACE (@com_github_Sirupsen_logrus) does not match the name given in the repository's definition (@com_github_sirupsen_logrus); this will cause a build error in future versions.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_yves/9d2b55ff2a90c4314d8256aee539277a/external/com_github_bshuster_repo_logruzio/BUILD.bazel:3:1: GoCompile external/com_github_bshuster_repo_logruzio/~stripped~go_default_library~/github.com/bshuster-repo/logruzio.a failed (Exit 1).
2017/11/25 01:05:29 missing strict dependencies:
	external/com_github_bshuster_repo_logruzio/formatter.go: import of github.com/sirupsen/logrus, which is not a direct dependency
	external/com_github_bshuster_repo_logruzio/logruzio.go: import of github.com/sirupsen/logrus, which is not a direct dependency
Target //bababot:bababot failed to build
```
Note that the error here is the strict dependencies thing, not the warning above.

Why is this happening only after the second build? Is the bazel cache case insentitive?

Note that this isn't important to me - I can workaround it by fixing the docker library upstream - but I thought I'd mention it for the record.

**Comment by ianthehat** [comment]
This is not really a rules_go thing, more a fundamental bazel thing.

I don't really know but my guess would be that bazel cache/buildoutput/etc is exactly as sensitive as the underlying file system, but that the target graph analysis is fully case sensitive, which probably means that things that vary only by case will cause horrendous issues where the trees/files are effectively overlaid on each other, the consequences of which would be somewhere between unpredictable and disastrous, and any build errors you get will be spurious lies cause by incorrect file contents.

I'm going to close this bug on the assumption that this is something we (the go team) have no control over, please re-open if you think that's not correct, or if you find more evidence/facts of interest.
