### ISSUE TITLE
Supporting TestMain(m *testing.M)

### ISSUE THREAD

**Issue by fangkyo** [bazelbuild/rules_go#11]
Seems go_test rule doesn't allow a test which has [TestMain(m *testing.M)](https://golang.org/pkg/testing/) function.
It reports an error similar to the message below:
github.com/bazelbuild/rules_go/bazel-out/local_linux-fastbuild/bin/examples/lib/a_test_main_test.go:16: cannot use lib.TestMain (type func(*testing.M)) as type func(*testing.T) in field value.

A straightforward solution is to update [generate_test_main.go:76](https://github.com/bazelbuild/rules_go/blob/master/go/tools/generate_test_main.go#L76) like below (but I'm not sure if it's enough):
`if !strings.HasPrefix(fn.Name.Name, "Test") || fn.Name.Name == "TestMain" {
	continue
}
`

**Comment by yugui** [comment]
Fixed with #68
