### ISSUE TITLE
Please support excluding certain paths from vendor/ in Gazelle

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/rules_go#1103]
This is probably easiest to solve as part of https://github.com/bazelbuild/rules_go/issues/859

https://github.com/kubernetes/client-go has unusual dependency handling. It vendors _most_ of its dependencies, but leaves some deps un-vendored. This prevents Gazelle from generating BUILD files, because some externals need to use `//vendor/foo.com/bar` and others need `@com_foo_bar//`.

It would be nice if Gazelle (via `go_repository`) could be told that certain external dependencies should be resolved as Bazel deps, even if the overall repository is having BUILD files generated with vendored deps.

**Comment by jayconrod** [comment]
I think #859 will fix this if Gazelle is run in external mode. Dependencies that can be resolved using the vendor directory will be, anything unresolved will go to an external dependency.

I'll leave this open to be sure to verify this case when that issue is closed.

**Comment by jayconrod** [comment]
Closing old Gazelle issues. This should be working now. If not, please file a new issue at bazelbuild/bazel-gazelle.
