### ISSUE TITLE
Cross compiling filegroups

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#1104]
Is it possible to use `filegroup`s `output_group` attribute to get a cross-compiled binary now that the preferred way of cross-compiling is not done through output groups?

**Comment by ianthehat** [comment]
cross compiling was never done through output groups, only race/pure was done that way.
At the moment cross compiling can only be triggered by changing the toolchain, which means either using ---experimental_platforms or --cpu on the command line, and only one can be built at a time.
What changed is that the files generated will not overwrite each other, so it's build cache friendly, and also  you can build a couple of platforms in sequence and then collect all the results when you are done if you like.
The changes to propagate the target goos and goarch through the mode in theory mean we could now build multiple pure go target architectures in a single bazel invocation, but cgo will not be possible until dynamic platform transitions arrives (no idea when the Bazel team will have time for that, but it's definitely planned)

**Comment by achew22** [comment]
The specific case I'm trying to deal with is trying to package up a project that has binary is compile for multiple operating system to distribute on NPM. Right now I have a [shell script](https://github.com/bazelbuild/bazel-watcher/blob/master/npm/publish.sh) that does a bunch of gross stuff compiling it twice and making temp directories. I would like to move it over to bring all in build files. Do you have any theories on how I could do that?

**Comment by ianthehat** [comment]
Persuade the Bazel team to implement toolchain transitions so we can have rules that state what toolchain they compile with....
Seriously, right now running bazel twice with the two toolchains is the best you are going to manage.
We could try adding goos and goarch controls to go_binary, it's probably not that hard, then you could declare separate go_binary rules for each target architecture, and collect up the results of all those rules, but it will break if you have any cgo anywhere in the system.
