### ISSUE TITLE
Error "Unsupported architecture: unknown" when `uname -p` returns "unknown"

### ISSUE THREAD

**Issue by nlacasse** [bazelbuild/rules_go#1111]
Happens on master, when building any go library on Linux.

Error is coming from this line:
https://github.com/bazelbuild/rules_go/blob/master/go/private/toolchain.bzl#L41

My `uname -p` returns `unknown`.  Every linux machine I have tried this on also returns `unknown`.  As a result all builds fail with "Unsupported architecture: unknown"

The behavior was introduced in https://github.com/bazelbuild/rules_go/pull/1070.

**Comment by jayconrod** [comment]
Discussed in chat. It sounds like `uname -m` might be a better option here, and we probably shouldn't fail for `unknown`.
