### ISSUE TITLE
rules_go 0.8.0 not working at all under Linux

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/rules_go#1122]
I just tried to give the recently published 0.8.0 release of `rules_go` a try. I first tried under Windows to see there is finally progress regarding #736, but when I noticed failure, I tried under Linux as well. I cannot even build the simplest package. It works (I checked) with 0.7.0, but I didn't have the time so far to go back in the commit history to see what the last working version was.

Example to reproduce:

`empty.go`:

```package main

func main() {}
```

`BUILD.bazel`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "empty",
    srcs = ["empty.go"],
    importpath = "empty",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "empty_cmd",
    importpath = "empty",
    library = ":empty",
    visibility = ["//visibility:public"],
)
```

`WORKSPACE`:
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go",
    tag = "0.8.0",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()

```

Output of `bazel build empty_cmd`:

```
ERROR: /home/jannis/.cache/bazel/_bazel_jannis/3dead889dfeadfbce32d4cea0bf66d14/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:9:1: every rule of type _go_toolchain implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Unsupported architecture: unknown
ERROR: Analysis of target '//:empty_cmd' failed; build aborted: no such package '@go_sdk//': Unsupported architecture: unknown
INFO: Elapsed time: 4.738s
FAILED: Build did NOT complete successfully (8 packages loaded)
    currently loading: @io_bazel_rules_go//go/private
```

I'm using Bazel 0.8.1 on Debian 9.2 on an x86_64 kernel in a Hyper-V virtual machine.

**Comment by jayconrod** [comment]
This was fixed yesterday in #1113. Sorry for the break. We were being overly strict about the result of `uname -p`, which returns `unknown` on some newer versions of Linux.

We'll tag a point release with this and a few other bug fixes early next week. In the mean time, use tip (which has the fix merged) or 02d2c56 (before the break).
