### ISSUE TITLE
go_test execution/report problem (probably gazelle problem)

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_go#1124]
Hello,

Before migrate to bazel I used https://github.com/tebeka/go2xunit
It is tool, which transform go test log to junit report.

In jenkins report I saw the every single "TestXXX" function as separate test, now I have single report for all TestXXX from single file.

I would like to see some solution for:
1. Separate test result in report for every single TestXXX
2. Parallel test execution of TestXXX (function parallelisation) instead of parallel binary execution

With best regards, Oleg

**Comment by jayconrod** [comment]
This sounds similar to #236. I'm not sure whether it's an exact duplicate though. Either way, we should do it.

**Comment by excavador** [comment]
It similar, but #236 about test report only, while I am asking about parallel test execution also.
It up to your, mark it as duplicate or just extend the #236 by words about parallel test execution of separate test functions

**Comment by jayconrod** [comment]
For parallel execution of tests, have you tried [`T.Parallel`](https://godoc.org/testing#T.Parallel)? It should work the same in Bazel as in "go test".

**Comment by excavador** [comment]
No.

Consider the single my_test.go file

```
func TestA(*testing.T) {
}

func TestB(*testing.T) {
}
```

Actual bazel/rules_go solution run these two functions as single test (single binary) with single report.

I want to see TWO separate tests, where every test has it own report (1) and executed independ, parallely (by bazel parallel execution) (2)

**Comment by jayconrod** [comment]
(Re-triaging old issues)

Closing as infeasible. Each test in Bazel's test reporting is a single rule (a `go_test` rule), written by the developer, not split up by rule set authors. Tests may contain many test cases, but they can't be split up into separate targets without manual work by the test author.

I think the main case where this usually matters is where you want to run and debug an individual test case. That can be done with `--test_filter=TestA`. That lets you specify a regular expression matching the test case to run. It works the same way the `-test.run` flag works in `go test`.
