### ISSUE TITLE
Supports bazel 0.3.0?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#113]
I'm curious if rules_go is being tested against 0.3.0 in a CI matrix.  On [travis](https://travis-ci.org/pubref/rules_protobuf/jobs/161725410), I'm now getting:

```sh
/home/travis/.cache/bazel/external/io_bazel_rules_go/go/def.bzl:500:18: expected ConfigurationTransition or NoneType for 'cfg' while calling label but got string instead: host.
```

Which seems related to changing the cfg attributes from `HOST_CFG` to `"host"`.  So, I'm thinking of dropping 0.3.0 from my build matrix and requiring 0.3.1 instead.  

Perhaps I've missed something so I thought I'd bring it up here.

**Comment by pmbethe09** [comment]
I typically build @ HEAD, so I was not aware of that.  I made the change to
"host" to eliminate the 'deprecated' message we were getting.

**Comment by pcj** [comment]
Looks like @jart brought this up a few days ago in https://github.com/bazelbuild/bazel/issues/1788.

**Comment by yugui** [comment]
I didn't intentionally dropped support of 0.3.0. But it would be reasonable to say that rules_go doesn't support 0.3.0 because 0.3.1 was released two months ago.
