### ISSUE TITLE
Error "object of type 'cpp' has no field 'ld_executable'" 

### ISSUE THREAD

**Issue by Quramy** [bazelbuild/rules_go#1132]
Hi. 

I've attempted [alexeagle/angular-bazel-example](https://github.com/alexeagle/angular-bazel-example#try-it) and encountered the following error:

```
ERROR: /private/var/tmp/_bazel_wacul_kurami/2991e1354d246f89e78432d3232620c3/external/go_stdlib_darwin_amd64_pure_race/BUILD.bazel:4:1: in stdlib rule @go_stdlib_darwin_amd64_pure_race//:go_stdlib_darwin_amd64_pure_race:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wacul_kurami/2991e1354d246f89e78432d3232620c3/external/go_stdlib_darwin_amd64_pure_race/BUILD.bazel", line 4
		stdlib(name = 'go_stdlib_darwin_amd64_pure_race')
	File "/private/var/tmp/_bazel_wacul_kurami/2991e1354d246f89e78432d3232620c3/external/io_bazel_rules_go/go/private/rules/stdlib.bzl", line 52, in _stdlib_impl
		cpp.ld_executable
object of type 'cpp' has no field 'ld_executable'.
ERROR: Analysis of target '//src:devserver' failed; build aborted.
```

Do you have some workadound for this?(the words `cpp` or `ld_executable`, it seems that my C/C++ linker settings has some mistake...? 🤔  )

I think the above error is thrown from a .bzl source code in this repository. I'm poor at golang and Bazel. I am sorry if I am mistaken

**Comment by jayconrod** [comment]
This seems like a problem with your C++ toolchain.

* What version of Bazel are you using?
* What OS and architecture are you running on and targeting?
* Anything unusual about the C/C++ toolchain on your system?

**Comment by Quramy** [comment]
- Bazel: bazel release 0.5.4
- OS: macOS Sierra 10.12.6

I've installed `Apple LLVM version 8.1.0 (clang-802.0.42)` as C/C++ compiler.

I'm using macports so the following configure in my .zshrc : 

```sh
# /opt/local/lib is used by mac ports
export LD_LIBRARY_PATH=/opt/local/lib
```

**Comment by jayconrod** [comment]
You'll need a newer version of Bazel to use the latest version of rules_go. We currently require at least Bazel 0.8.0.

I'm not sure whether Bazel's autoconfiguration works with Macports clang. Are you able to build regular `cc_binary` / `cc_library` rules?
