### ISSUE TITLE
Failure building with --features=race

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#1133]
```console
bazel build --features=race //cmd/bla
INFO: Analysed 4 targets (292 packages loaded).
INFO: Found 4 targets...
ERROR: /private/var/tmp/_bazel_mmazurskiy/b34360f02dd290fea1de7cb4ffb49b60/external/io_bazel_rules_go/go/tools/builders/BUILD.bazel:79:1: error executing shell command: 'export GOROOT=$(pwd)/bazel-out/host/bin/external/go_stdlib_darwin_amd64_cgo_race && bazel-out/host/bin/external/go_stdlib_darwin_amd64_cgo_race/bin/go tool compile -o bazel-out/host/bin/external/io...' failed (Exit 1)
external/io_bazel_rules_go/go/tools/builders/env.go:18:2: can't find import: "flag"
INFO: Elapsed time: 1.358s, Critical Path: 0.37s
FAILED: Build did NOT complete successfully
```
If I build the same package without `--features=race` - it works.

OS: macOS 10.12.6
Bazel: 0.8.1 
Rules_go: latest as of today dfcdede243e986a0dd1e4c3e2f1005051ab5b15e

p.s. another thing I have noticed: `race` parameter to `go_test`/`go_binary` is not documented anywhere. Or I cannot find it? Is using it for binaries is the recommended way (like for `go_test`)?

**Comment by jayconrod** [comment]
Thanks for reporting this. I reproduced this and bisected it down to 7b0091d45c355faf9110a1ad939752512acd0910 - "Allow pure go cross compilation within a single build (#1114)".

It looks like we're compiling our tool binaries in race mode, but they're given the non-race standard library as input. We shouldn't be compiling anything in the host configuration in race mode, but we can't detect if something is for the host configuration or not, so we should at least ignore the race feature for `go_tool_binary`.
