### ISSUE TITLE
go_proto_library plugin implicitly depends on proctoc-gen-go

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1139]
`go_proto_library` uses `tools/builders/go-protoc` to generate pb files.  Which adds `import_path` flag to the proto gen request.  Which is not a standard protoc plugin option, and leads to other plugins to complaint on this.  So the current status with `go_proto_library` is that it only support protoc-gen-go sub-plugins, more specifically, only grpc is supported atm.

Shall we make it part of the `go_proto_complier` options to avoid this?

**Comment by ianthehat** [comment]
I have working prototypes using mwitkow/go-proto-validators and I made gogo work for the weaveworks project already.
If you have any more plugins you want me to add natural support for, please list them and I will look into it.
The plan is for the proto/ folder to have a .bzl file for all the reasonably common go plugins, and enough examples to make sure they keep working, the most recent commits in #1131 were related to fixing issues with these (notably allowing individual proto plugins to supply extra deps correctly)

**Comment by ashi009** [comment]
Thanks for the quick reply. The one thing I’d love to see work is
protoc-gen-grpc-gateway. It has been a problem since day one, and I don’t
want to rely on pubref for gateway code generation any longer — it has
always been a blocker for me switching to the latest stable buildenv.

protoc-gen-grpc-gateway is a protoc plug-in that generates files that are
depend on go_libraries. The funny part of this generator is that, it’s
incapable of generating a fully functional go file, but instead it needs to
combine the pb.go file generated by protoc-gen-go in grpc mode.

I haven’t tried out the latest cl yet. Will take a look in the morning.
Ian Cottrell <notifications@github.com>于2017年12月15日 周五上午12:31写道：

**Comment by achew22** [comment]
@ianthehat, FYI I'm a maintainer on grpc-gateway and would be more than happy to help adding support for it to rules_go

**Comment by ianthehat** [comment]
If you want to look at what I did for the validator and put up a PR (with a test), it would be welcome, I was going to do the gogo ones next and then get to the gateway one sometime after that.
If you want to put the rules in the grpc-gateway repository, that's fine too, and should work just as well

**Comment by ashi009** [comment]
@achew22 @ianthehat PTL.

**Comment by tkellen** [comment]
Any chance someone subscribed to this issue could point me in the direction of an example implementation using these functionality?

**Comment by jayconrod** [comment]
Fixed in #1165
