### ISSUE TITLE
Gazelle uses the wrong naming convention for go_grpc_library

### ISSUE THREAD

**Issue by nclinger** [bazelbuild/rules_go#1147]
For a grpc proto files gazel generates the following build target:
```
go_grpc_library(
    name = "helloworld_go_proto",
    importpath = "builds/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)
```

However, I believe the standard for naming is \<proto file name\>_\<lang\>_grpc, thus this should be:
```
go_grpc_library(
    name = "helloworld_go_grpc",
    importpath = "builds/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)
```

Fyi, this seems to correctly work when the file only contains a grpc service definition without any messages definitions.

**Comment by nclinger** [comment]
Ops missed that Gazelle moved to a new repo.  Will repost this there.

**Comment by ianthehat** [comment]
Going to close this as you are moving the issue, but note that there is not really a standard naming for grpc libraries, and there is no more go_grpc_library rule anyway, you just change the compiler on a go_proto_library rule, so keeping the package_lang_proto name probably makes sense.
