### ISSUE TITLE
Protolibrary access *.go files 

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_go#1176]
Is it possible for a rule to have access to the .go files instead of depending directly on the library .a? I know this behaviour maybe shouldn't be supported.

**Comment by jayconrod** [comment]
Could you tell us more about your use case? If you're building a library that includes both generated .go file and handwritten .go files, you can do that with `embed`.

```
go_proto_library(
    name = "foo_go_proto",
    proto = ":foo_proto",
    ...
)

go_library(
    name = "go_default_library",
    srcs = ["extra.go"],
    embed = [":foo_go_proto"],
    ...
)
```

If you need the actual .go file as a result, we could add something to the `go_source` rule that would make it easier to get them. We haven't seen a use case yet for this though.

**Comment by afking** [comment]
It was to export the files locally to the $GOPATH so developers IDEs can find the definitions. Bit of a hack but worked for helping developers understanding, while builds always used the protobuf generated libraries.

**Comment by ianthehat** [comment]
We have plans around that kind of thing, see the issues linked from the [Go source tools](/bazelbuild/rules_go/projects/1) project
If you look at the go_path rule you can see how we collect up sources and transform them into a GOPATH copy, it's much more complicated though. 
If you really want just the files, we can easily give you a way to get them, or you could write some custom skylark yourself that just digs them out of the GoSource provider.
