### ISSUE TITLE
go_rules fails to properly detect ppc64le

### ISSUE THREAD

**Issue by jbedorf** [bazelbuild/rules_go#1186]
My problem seems to be similar to #854  but as that one is closed and it is slightly different in the output I'm opening a new issue.

**Environment info**
```
$ uname -a
Linux host 3.10.0-693.11.1.el7.ppc64le #1 SMP Fri Oct 27 05:42:02 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux
```
Bazel information
```
$ bazel version
build label: 0.9.0- (@non-git)
```

When running a simple test problem (same as given in the last comment of #854 ) with modifications to WORKSPACE to take the latest master version of `the rules_go` repository

WORKSPACE
````
 git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go",
    commit = "bd1753da4c06bdd10c8bbe0086da18fcea055eea",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
```` 

BUILD.bazel
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "hello",
    srcs = ["hello.go"],
    importpath = "example.com/hello",
)
```

hello.go
```
package main

func main() {
}
```

When running `bazel build //:hello` it will attempt to download the linux_amd64 rules, this can be fixed by changing:
https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L32
into:
` elif res.stdout.strip() == 'ppc64le':`
For some reason the stdout output contains a new line which causes the comparison to fail. 

Fixing that it will download the proper-sdk, but then during the building step it fails because it builds the sdk for `ppc64` instead of `ppc64le`: 

```
$ bazel build //:hello
INFO: Analysed target //:hello (163 packages loaded).
INFO: Found 1 target...
[5 / 13] 2 actions running
    GoStdlib external/go_stdlib_linux_ppc64_cgo/bin/go [for host]; 2s processwrapper-sandbox
    GoStdlib external/go_stdlib_linux_ppc64_cgo/bin/go; 2s processwrapper-sandbox
```

Which causes the build/compilation steps later on to fail:
```
$ external/io_bazel_rules_go/go/tools/builders/BUILD.bazel:22:1: 
error executing shell command: 'export GOROOT=$(pwd)/bazel-out/host/bin/external/go_stdlib_linux_ppc64_cgo &&
 bazel-out/host/bin/external/go_stdlib_linux_ppc64_cgo/bin/go tool compile -o bazel-out/host/bin/external/io_bazel_rules...' failed (Exit 1)
external/io_bazel_rules_go/go/tools/builders/asm.go:20:2: can't find import: "flag"
```

The problem here is that it takes libraries that just have been compiled for `ppc64` instead of  `ppc64le`. I'm not sure if this is a problem with bazel or that the go_rules pick up the wrong OS.  If I manually execute that line set `GOROOT`  to point to a custom build go-sdk targeted for `ppc64le` then the compilation of that file succeeds. However, that change does not get picked up and rerunning `bazel build` while setting `GOROOT` globally does not affect the build.

Is there a way to point the build system to a local sdk in order to prevent that it download/compiles the sdk itself for the wrong target? (Both host and target in this case are ppc64le).

**Comment by jayconrod** [comment]
I created #1187 to strip the result of `uname -p` before checking for known processors. With that, you should get the correct SDK automatically.

> Fixing that it will download the proper-sdk, but then during the building step it fails because it builds the sdk for ppc64 instead of ppc64le

Not really sure why that's happening. @ianthehat will know.

> Is there a way to point the build system to a local sdk in order to prevent that it download/compiles the sdk itself for the wrong target? (Both host and target in this case are ppc64le).

Yes, in your WORKSPACE, you change `go_register_toolchains` to the call below. This will use the SDK at `$GOROOT`.

```
go_register_toolchains(go_version = "host")
```

**Comment by jbedorf** [comment]
Thanks the fix seems to work. 

I could not get it to work with ` go_register_toolchains(go_version = "host") `  it kept building the ppc64 version.  I did some more digging, maybe it helps in tracing what / where the detection fails. I stripped most of the items in the `GOOS` and `GOARCH` lists defined in `go/platform/list.bzl` and then ran the build with ` --toolchain_resolution_debug=true`  . This gave:
```
INFO: ToolchainResolution: Looking for toolchain of type @io_bazel_rules_go//go:toolchain...
INFO: ToolchainResolution:   Considering toolchain @io_bazel_rules_go//go/toolchain:go_linux_amd64-impl...
INFO: ToolchainResolution:     Toolchain constraint @bazel_tools//platforms:cpu has value @bazel_tools//platforms:x86_64, which does not match value @bazel_tools//platforms:ppc from the execution platform @bazel_tools//platforms:host_platform
INFO: ToolchainResolution:   Rejected toolchain @io_bazel_rules_go//go/toolchain:go_linux_amd64-impl, because of execution platform mismatch
INFO: ToolchainResolution:   Considering toolchain @io_bazel_rules_go//go/toolchain:go_linux_amd64_cross_linux_ppc64le-impl...
INFO: ToolchainResolution:     Toolchain constraint @bazel_tools//platforms:cpu has value @bazel_tools//platforms:x86_64, which does not match value @bazel_tools//platforms:ppc from the execution platform @bazel_tools//platforms:host_platform
INFO: ToolchainResolution:   Rejected toolchain @io_bazel_rules_go//go/toolchain:go_linux_amd64_cross_linux_ppc64le-impl, because of execution platform mismatch
INFO: ToolchainResolution:   Considering toolchain @io_bazel_rules_go//go/toolchain:go_linux_ppc64le_cross_linux_amd64-impl...
INFO: ToolchainResolution:     Toolchain constraint @bazel_tools//platforms:cpu has value @io_bazel_rules_go//go/toolchain:ppc64le, which does not match value @bazel_tools//platforms:ppc from the execution platform @bazel_tools//platforms:host_platform
INFO: ToolchainResolution:   Rejected toolchain @io_bazel_rules_go//go/toolchain:go_linux_ppc64le_cross_linux_amd64-impl, because of execution platform mismatch
INFO: ToolchainResolution:   Considering toolchain @io_bazel_rules_go//go/toolchain:go_linux_ppc64le-impl...
INFO: ToolchainResolution:     Toolchain constraint @bazel_tools//platforms:cpu has value @io_bazel_rules_go//go/toolchain:ppc64le, which does not match value @bazel_tools//platforms:ppc from the execution platform @bazel_tools//platforms:host_platform
INFO: ToolchainResolution:   Rejected toolchain @io_bazel_rules_go//go/toolchain:go_linux_ppc64le-impl, because of execution platform mismatch
INFO: ToolchainResolution:   No toolchain found
ERROR: While resolving toolchains for target //:hello: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//:hello' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```
After that I modified the bazel source file `ToolchainResolutionFunction.java` in order to force it to accept this toolchain: `@io_bazel_rules_go//go/toolchain:ppc64le`. Recompiled bazel and with that change in it builds the `ppc64le`  version of the SDK and correctly compiles the example program.

**Comment by jayconrod** [comment]
With #1197 merged, are you running into any other issues with the ppc64le build? If not, I'll close this issue.

**Comment by jbedorf** [comment]
This can be closed. I'm now able to build the examples out of the box.
