### ISSUE TITLE
Gazelle generates incorrect dependencies for gopkg.in/src-d/go-git.v4

### ISSUE THREAD

**Issue by jeremyje** [bazelbuild/rules_go#1188]
If you have a golang project that depends on gopkg.in/src-d/go-git.v4 then gazelle generates deps with @in_gopkg_src_d//go-git.v4:go_default_library instead.

This is especially problematic when the deps of deps use gopkg.in since those rules are autogenerated.

Lastly, it's kinda weird why these commits are pinned why gazelle can't just infer the go_repositories altogether.

**Comment by jayconrod** [comment]
> If you have a golang project that depends on gopkg.in/src-d/go-git.v4 then gazelle generates deps with @in_gopkg_src_d//go-git.v4:go_default_library instead.

I remember this being an issue some time ago, but I believe it's been fixed. What commit are you using for Gazelle? When I use Gazelle at tip, that path resolves to `@in_gopkg_src_d_go_git_v4//:go_default_library`.

> Lastly, it's kinda weird why these commits are pinned why gazelle can't just infer the go_repositories altogether.

bazelbuild/bazel-gazelle#56 is the general issue tracking this. It will take some time though.

**Comment by jeremyje** [comment]
Closing. I upgraded gazelle and the problem went away. Thanks.
