### ISSUE TITLE
go_source not exposing GoLibrary provider

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_go#1189]
I am currently trying to implement swagger support.
For that, I tried the following:

    go_source(
        name = "srcs",
        srcs = ["main.go"],
        deps = ["bar"],
    )

    swagger_spec(
        name = "spec",
        srcs = srcs,
    )

with (_swagger_spec_) `srcs` being defined as:

    "srcs": attr.label(mandatory = True, providers=[GoLibrary]),

The error I get is:

    in srcs attribute of swagger_spec rule //golang/src/foo:spec: '//golang/src/foo:srcs' does not have mandatory providers: 'GoLibrary'

Looking at the code of `go_source` IMO this should work.
Anyone any idea what I am doing wrong?

**Comment by abergmeier** [comment]
Seems to be a bug in 0.8.1. Is working fine in f3c2604571f64a401283bbfe92c45234205f5cca.

**Comment by ianthehat** [comment]
Given that #1190 is merged, I am going to presume we can close this. Let me know if that was not the case.

**Comment by abergmeier** [comment]
> Given that #1190 is merged, I am going to presume we can close this. Let me know if that was not the case.

It is fixed in master. IMO it would be ok to close it once you released a fixed version (as of today 0.8.1. is still the lastest). Assuming you release a version soonish, I'll leave it closed, though.
