### ISSUE TITLE
cgo_library doesn't pass copts down to cgo

### ISSUE THREAD

**Issue by ecaraszi** [bazelbuild/rules_go#119]
Hello,

Thanks for making rules_go!   Here's a small bug report & potential fix:  

Bug: cgo_binary doesn't pass copts down to the compiler flags in the cgo invocation.

Fix:  github.com/ecaraszi/rules_go on branch cflags 

I used this patch to successfully build the github.com/go-gl libraries (glfw 3.2, gl 4.1-core, and mathgl) and link a working example.

**Comment by pmbethe09** [comment]
We welcome contributions, so please make a PR

**Comment by jmhodges** [comment]
(Sorry, just poking around in other cgo tickets. This maybe can be closed again now?)

**Comment by jayconrod** [comment]
Closing old issues. Seems like this one is fixed.
