### ISSUE TITLE
Remove importpath from go_test and go_binary

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#1207]
We have deprecated them, we should remove them for the next version.

**Comment by abergmeier** [comment]
Why do you want to remove `importpath` on `go_binary`? I actually use it to change path for consumption in `GoArchive`.

**Comment by ianthehat** [comment]
Could you explain what you mean? There should have been no useful way to consume the importpath on a go_binary or go_test, if you have a use case I need to understand it so I can support it.
It was only really there for the benefit of the go_path rules, and because both rules build a library underneath that they nominally need an importpath for (although they don't care what the import path is as the library is not imported by normal code)

**Comment by abergmeier** [comment]
Well we e.g. have the following:

    /golang/src/ourproject/main.go
    /golang/src/ourproject/BUILD

with:

    go_binary(
        name = "ourproject",
        srcs = ["main.go"],
        importpath = "ourproject",
    )

    my_rule(
        lib = "ourproject",

`my_rule.lib` accepts `GoLibrary` providers and internally Skylark uses the `importpath` to look for files. If you remove importpath, you IMO then also need to at least remove `GoLibrary` provider let alone all implicit functionality that comes with that.

**Comment by ianthehat** [comment]
It's a valid GoLIbrary, it's just not an importable one...
What is it you are looking in the GoLibrary of a go_binary for? There are plenty of use cases, but none of them should be dependant on an explicitly set importpath.
If you are just looking for files, you resolve it to a GoSource object, and then pick the source files out of that.

**Comment by jayconrod** [comment]
After further discussion, we decided not to remove `importpath`, since it's useful in `go_path`. It's a bit of a misnomer, but it seems better to keep it than to introduce a new attribute (e.g., `exportpath`).

I've removed the deprecation notice for that attribute. Some work still needs to be done within the providers to make it clear whether an archive is importable. I'll fix that when we remove `go_prefix` (soon!).

**Comment by junghoahnsc** [comment]
What `importpath` should I set for `go_binary` and `go_test`?

For example, I saw https://github.com/bazelbuild/rules_go/blob/master/tests/core/go_path/cmd/bin/BUILD.bazel#L7, which sets `importpath` to `"example.com/repo/cmd/bin"` while `bin.go` has `package main`.

Is this a right way to set `importpath` both for `go_binary` and `go_test` to work correctly with `go_path`

**Comment by junghoahnsc** [comment]
Thanks for the clafification! 
It looks like that `importpath` just affects Go source path in `src/...` regardless of the actual package name in the source code.
