### ISSUE TITLE
Gazelle doesn't chroot proto_library references

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_go#1219]
Try to run Gazelle on [this](https://github.com/kubernetes/sample-controller).

I am getting a bunch of errors that are tantamount to Gazelle not rewriting `//k8s.io/...` to `//vendor/k8s.io/....`.

**Comment by mattmoor** [comment]
Actually, it's worse than I thought, it seems to be generating the `proto_library` rules...

e.g. in `vendor/k8s.io/api/admissionregistration/v1alpha1/BUILD` I see (among other things):
```
+
+proto_library(
+    name = "v1alpha1_proto",
+    srcs = ["generated.proto"],
+    deps = [
+        "//k8s.io/apimachinery/pkg/apis/meta/v1:v1_proto",       <-- OOPS!
+        "//k8s.io/apimachinery/pkg/runtime:runtime_proto",
+        "//k8s.io/apimachinery/pkg/runtime/schema:schema_proto",
+        "//k8s.io/apimachinery/pkg/util/intstr:intstr_proto",
+    ],
+)
+
+go_proto_library(
+    name = "v1alpha1_go_proto",
+    importpath = "k8s.io/api/admissionregistration/v1alpha1",
+    proto = ":v1alpha1_proto",
+    deps = [
+        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/runtime:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/runtime/schema:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/util/intstr:go_default_library",
+    ],
+)
```

**Comment by mattmoor** [comment]
FYI I'm using this in `BUILD`:
```

load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_binary", "go_library", "go_prefix")

go_prefix("k8s.io/sample-controller")

gazelle(
    name = "gazelle",
    external = "vendored",
)
```

... and running `bazel run //:gazelle` per documentation.

**Comment by mattmoor** [comment]
This looks like the same thing I hit [here](https://github.com/bazelbuild/rules_go/issues/1022), but in terms of `vendor/` based deps.

**Comment by mattmoor** [comment]
This got me past this:
```shell
bazel run //:gazelle -- -proto=disable
```

**Comment by mattmoor** [comment]
I'm going to leave this open, it's silly to create these bad references.

**Comment by jayconrod** [comment]
Discussed offline. We decided to disable proto rule generation by default in vendor.

Migrated to bazelbuild/bazel-gazelle#77
