### ISSUE TITLE
Using new_go_repository to import external repos that use vendoring

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/rules_go#122]
Does it work at all?

I tried this
```
new_go_repository(
  name = "com_github_prometheus_prometheus",
  importpath = "github.com/prometheus/prometheus",
  tag = "v1.1.3"
)
```
This is the BUILD generated for cmd/promtool:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "promtool",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_prometheus_common//version:go_default_library",
        "//config:go_default_library",
        "//promql:go_default_library",
        "//util/cli:go_default_library",
    ],
)
```
Then I did
```
bazel build @com_github_prometheus_prometheus//cmd/promtool
```
and I got
```
ERROR: /private/var/tmp/_bazel_shimin/3a4c5c5e79ba6f8a3fd88b3eacc43127/external/com_github_prometheus_prometheus/cmd/promtool/BUILD:3:1: no such package '@com_github_prometheus_common//version': error loading package 'external': The repository named 'com_github_prometheus_common' could not be resolved and referenced by '@com_github_prometheus_prometheus//cmd/promtool:promtool'.
ERROR: Analysis of target '@com_github_prometheus_prometheus//cmd/promtool:promtool' failed; build aborted.
```
The prometheus repo uses vendoring for external dependencies. There is a vendors/ directory under which dependencies like github.com/prometheus/common/version are stored. Can new_go_repository be used for repos like that?

**Comment by hochhaus** [comment]
My understanding is that (per #114) `new_go_repository()` does not utilize the  packages located under the `vendor/` directory. Instead, bazel expects that you explicitly add all of your (recursive) dependencies to your `WORKSPACE` file. This is very explicit and predictable.

That said, personally, I hope this plan is revisited in order to make it easier to interoperate with the go ecosystem.

**Comment by pmbethe09** [comment]
Right, the current rules && gazelle work the bazel-way which means remote
vendoring.
And bazel currently requires flattening of transitive dependencies

So to get this to work, you would add to your WORKSPACE

new_go_repository(
  name = "com_github_prometheus_common",
  importpath = "github.com/prometheus/c
<http://github.com/prometheus/prometheus>ommon",
  commit = "e35a2e33a50a7d756c7afdfaf609f93905a0c111"
)

I used the latest commit, as I don't see any tag matching "v1.1.3"

And yes, this does mean that building with bazel will ignore the vendor
directory which would have been used by 'go build'.

This is a shortcoming that Andy has already pointed out, but we don't have
a solution proposed yet.

**Comment by guoshimin** [comment]
Thanks y'all for the information. Looks like I will need to do this for all the transitive dependencies. It's not realistic in many cases. I hope there will be a better solution in the future.

**Comment by pmbethe09** [comment]
I have a proposal in another thread to @yugui to have gazelle auto populate
your WORKSPACE file, including transitive dependencies, which should make
this a lot easier.

**Comment by hochhaus** [comment]
@pmbethe09 Excellent, thanks. Is that thread public? If so, can you provide a pointer?

**Comment by pmbethe09** [comment]
It was in a PR or issues thread here somewhere, but essentially it is auto-updating of your WORKSPACE file by gazelle.  I have a PR in progress.

**Comment by pmbethe09** [comment]
I mentioned it here:
https://github.com/bazelbuild/rules_go/pull/116

**Comment by hochhaus** [comment]
Thanks @pmbethe09.
