### ISSUE TITLE
Shorten generated file names

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#1224]
```
tests/cgo_pure/cgo.go
```
becomes
```
bazel-bin/tests/cgo_pure/linux_amd64_stripped/cgo_pure.cgo_codegen~/tests_cgo_pure_cgo.cgo1.go
```
which is too long a name, and makes compiler errors very hard to read/process

**Comment by ivyxyz** [comment]
The "file name too long" error occurred on eCryptFS that does not allow long file names (143 chars max).
https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash

CGoCodeGen failed (Exit 1).
open bazel-out/k8-dbg/bin/external/com_github_miekg_dns/vendor/golang.org/x/net/ipv6/linux_amd64_stripped/go_default_library.cgo_codegen~/bazel-out_k8-dbg_bin_external_com_github_miekg_dns_vendor_golang.org_x_net_ipv6_linux_amd64_stripped_go_default_library.cgo_codegen~__cgo_empty.cgo1.go: file name too long

There are also file names like "external_com_github_miekg_dns_vendor_golang.org_x_net_ipv6_batch.cgo1.go"

Is it possible to shorten the names to be "__cgo_empty.cgo1.go" and "batch.cgo1.go"?

**Comment by ivyxyz** [comment]
Friendly ping @ianthehat and @jayconrod  for the build failure above.

**Comment by ianthehat** [comment]
It's on my list of things to do, but it's not right at the top...
The crazy long filenames were originally neccesary because there were collisions between different rules and modes, and this was the only fully reliable solution at the time.
With the massive changes to the way we compile things and the switch to the aspect based builds, it is probably much easier to generate a non colliding but still short name now.
