### ISSUE TITLE
Depending on a C library which is built by make

### ISSUE THREAD

**Issue by gshimansky** [bazelbuild/rules_go#1233]
This is a question, not a bug.

I am trying to write bazel build for a Go project https://github.com/intel-go/yanff currently built with `make`. We use `make` because we have a dependency from [DPDK C library](http://dpdk.org/) and it is a traditional C library that is built with `make`.

I tried to write a `genrule` named `build-dpdk` to call `make` in DPDK web archive, but if I add it to dependencies of go_library it requires this genrule to be either `GoLibrary` or `cc` depending on whether I add it to `deps` or `cdeps`, e.g. `cdeps = [ "@dpdk//:build-dpdk", ]`. I am unsure how to continue now.

I tried to search issues and rules_go sources, but the only possible solution it seems is to convert DPDK build into `cc_library` bazel build which requires too much effort, requires continuous support and doesn't guarantee correctness. In short, converting DPDK build to bazel is not an option.

Are we the first Go project which depends on a complex C library dependency?

**Comment by ianthehat** [comment]
This is really a general bazel question rather than a rules_go one, but I will try to answer anyway.
I believe you can add the output of your genrule (that runs make) to the scrs of a cc_library rule, and then use that as normal, but I have never actually tried it.

**Comment by gshimansky** [comment]
Thank you for a recommendation. I didn't realize that `cc_library` allows library binaries `.a` and `.so` into `srcs`. I will try to implement this approach and write here about the results.
I think the question still relates to `rules_go` since `go_library` provider restrictions are the problem that I am trying to overcome.

**Comment by ianthehat** [comment]
Hope it works and do let us know.
The reason I say it's not rules_go is that the restriction on cdeps is because we delegate to the cc rules underneath, the type restrictions come from them not us.
If we really had to we could try to work out how to do it without the c rules being involved, but it would not be simple (we would have to force the use of the external linker in cases where we did not have cgo for instance)

**Comment by gshimansky** [comment]
Thank you. I managed to build DPDK as a cc_library and genrule inside of it. Leaving this code for reference if someone else searches for a problem like this

```
filegroup(
    name = "dpdk-binaries",
    srcs = [
        "x86_64-native-linuxapp-gcc-install/lib/librte_eal.a",
        "x86_64-native-linuxapp-gcc-install/include/dpdk/rte_eal.h",
    ],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "dpdk-build",
    srcs = [
        ":dpdk-binaries",
    ],
    visibility = ["//visibility:public"],
)

genrule(
    name = "dpdk-run-make",
    srcs = [ ":dpdk-17.08" ],
    outs = [
        "x86_64-native-linuxapp-gcc-install/lib/librte_eal.a",
        "x86_64-native-linuxapp-gcc-install/include/dpdk/rte_eal.h",
    ],
    local = 1,
    cmd = """
make -C $(location :dpdk-17.08) config T=x86_64-native-linuxapp-gcc
make -C $(location :dpdk-17.08) install T=x86_64-native-linuxapp-gcc DESTDIR=x86_64-native-linuxapp-gcc-install
cp -rv $(location :dpdk-17.08)/x86_64-native-linuxapp-gcc-install $(@D)/
""",
    visibility = ["//visibility:private"],
)
```
