### ISSUE TITLE
inability to handle multiple different versions of vendored packages

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/rules_go#1237]
EDIT: please see https://github.com/bazelbuild/rules_go/issues/1237#issuecomment-357418520 instead.

Example repo: https://github.com/guoshimin/rules_go_test

Inside the example/ folder, there are two sets of go_{library,binary}, where the only difference is the order of deps in the respective go_library.

`//example:example` builds successfully, whereas `//example:example2` fails to build:
```
$ bazel build //example:example2
Loading: 
Loading: 0 packages loaded
INFO: Analysed target //example:example2 (0 packages loaded).
INFO: Found 1 target...
bazel: Entering directory `/home/shimin/.cache/bazel/_bazel_shimin/aa160757cc427c3c02795
fdc1f75cf88/execroot/__main__/'                                                        
[0 / 2] BazelWorkspaceStatusAction stable-status.txt
ERROR: /home/shimin/rules_go_test/example/BUILD.bazel:31:1: GoLink example/linux_amd64_s
tripped/example2 failed (Exit 1)                                                       
google.golang.org/grpc/transport.newFramer: relocation target type.golang.org/x/net/http
2.frameCache not defined                                                               
type.**golang.org/x/net/http2.frameCache: relocation target type.*golang.org/x/net/http2
.frameCache not defined                                                                
google.golang.org/grpc/transport.newFramer: undefined: "type.golang.org/x/net/http2.fram
eCache"                                                                                
type.**golang.org/x/net/http2.frameCache: undefined: "type.*golang.org/x/net/http2.frame
Cache"                                                                                 
2018/01/13 00:07:38 error running linker: exit status 1
bazel: Leaving directory `/home/shimin/.cache/bazel/_bazel_shimin/aa160757cc427c3c02795f
dc1f75cf88/execroot/__main__/'                                                         
Target //example:example2 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.926s, Critical Path: 1.27s
FAILED: Build did NOT complete successfully
```

What's at play here?

Here's my bazel version:
```
$ bazel version
Build label: 0.8.1
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/baz
el/BazelServer_deploy.jar                                                              
Build time: Tue Dec 5 14:29:45 2017 (1512484185)
Build timestamp: 1512484185
Build timestamp as int: 1512484185
```

I'm using rules_go v0.9.0.

**Comment by guoshimin** [comment]
The problem seems to have to do with the fact that there are two versions of golang.org/x/net/http2 in the dependency closure, one that's vendored directly, and one vendored indirectly via k8s.io/client-go. When invoking the go linker, it works when the directly vendored version appears first, and fails otherwise.

**Comment by guoshimin** [comment]
Actually, in the general case, no order will build successfully. I now have a smaller example at https://github.com/guoshimin/rules_go_test, in the versions/ folder.

The dependencies are as follows:

![graph](https://user-images.githubusercontent.com/11787293/34904282-a91e85fc-f7f7-11e7-890d-137830b8e270.png)

Basically, there are two versions of foo.com/x:
- one in versions/vendor, used by baz.com/z, 
- the other in versions/vendor/bar.com/vendor, used by bar.com/y

'go build' has no problem with it, but bazel fails with
```
$ bazel build //versions
INFO: Analysed target //versions:versions (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/shimin/rules_go_test/versions/BUILD.bazel:14:1: GoLink versions/linux_amd64_stripped/versions failed (Exit 1)
foo.com/x.Foo1: call to external function
baz.com/z.Baz: relocation target foo.com/x.Foo1 not defined
baz.com/z.Baz: undefined: "foo.com/x.Foo1"
2018/01/13 08:23:59 error running linker: exit status 1
Target //versions:versions failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.756s, Critical Path: 0.13s
FAILED: Build did NOT complete successfully
```

It seems the problem lies with rules_go's inability to deal with different versions of vendored packages.

**Comment by guoshimin** [comment]
I have a sketch for the fix in https://github.com/bazelbuild/rules_go/compare/master...guoshimin:importmap?expand=1

**Comment by jayconrod** [comment]
Thanks for reporting this and for the detailed analysis.

The issue is that we compile libraries according to their import path. If multiple libraries with the same import path are visible to the linker, it just picks the first one.

"go build" uses `-importmap` to change the effective import path of vendored libraries when compiling dependent libraries. We should probably do this for all dependencies -- use `-importmap` to map import paths to directories or labels.

I think the reason we weren't doing this originally was that we were supporting Go 1.7, which didn't have `-importmap`. We dropped support for 1.7 a few months ago though, so we should be able to fix this now.

**Comment by guoshimin** [comment]
How do you think of my sketch for the fix? It uses importmap. Is it sound?

**Comment by jayconrod** [comment]
I think your fix is a step in the right direction, but not complete. I haven't had a chance to really examine how it impacts the command lines (sorry, really swamped today).

One concern: naming files based on Bazel package name is not enough. There will likely be more than one Go rule in the same package, and they may be part of the same build (especially with tests). The package name may also be empty in the workspace root.

We might want to make a more sweeping change here though. I think the reason we make library output file names based on import path is to avoid using `-importmap`. We might be able to simplify this considerably.

There's also golang/go#20579 (`-importcfg` flag) which we might want to use instead. That's in Go 1.9+, but we'll be able to drop 1.10 support soon.

cc @ianthehat

**Comment by ianthehat** [comment]
I had a patch similar to this (but with a safer and shorter .a name). 
It turned out to be a non viable change, because the way it works is to modify the import path early, rather than late map the import path to the .a file. This causes things that acquire the package name at run time to change behavior, things like stack traces or reflection, so it can't be the default behavior.

I am planning to use `-importcfg` as soon as we can so that we don't need the crazy .a file names and we don't need the huge library search paths we have right now, but I was not thinking about using it to map the same import paths to multiple binaries.

It's a deeply wrong thing to do (as the two copies of the package are now both being linked, and if they have any global state then good luck making anything work), so I think if we support it, it ought to be very explicit.

A library can already control it's own import path, we could add a transitive importmap to the library so that you get importmap directives propagate from your dependancies, then the vendored version could control it.
Something like 

```
go_library(
  name = "x",
  importpath = "baz/foo.com/x",
  importmap = "foo.com/x",
)
```

would cause anything importing it to get `-importmap foo.com/x=baz/foo.com/x` added to it's command lines

As a separate thing, we probably ought to complain much more visibly if the same import path is presented to the link step more than once.

**Comment by guoshimin** [comment]
@jayconrod @ianthehat Thank you both for you insight. Do you guys have suggestions on what we should do in the meantime? I fully agree that it's a broken situation, and would like to do the right thing. One of the libraries we use vendors an older version of another library, but we also use the newer version of that library directly. We can't just pick one version because each contains functions that aren't present in the other version. I wonder how the community at large solves this problem?

**Comment by ianthehat** [comment]
I am happy to implement my suggested importmap argument if we agree it's going to solve the problem.
I am not sure if gazelle can or should do anything automatically to use it, but it would at least be possible to modifiy the build files in the vendor folders to change the importpath and add the importmap lines.
It's not a big change, would probably take me a day or so to do it, maybe slightly more to add some tests.

**Comment by guoshimin** [comment]
Yeah, I think that will unblock us from using Bazel for our go builds. Thanks!

**Comment by guoshimin** [comment]
Actually, I misunderstood how this solution works and this solution does not solve the problem, at least not nicely.  When I do
```
go_library(
  name = "x",
  importpath = "baz/foo.com/x",
  importmap = "foo.com/x",
)
```
I also need to change "foo.com/x" to "baz/foo.com/x" in all the code that depends on this library. And if I do this, "go build" will stop working, as it doesn't know what "baz/foo.com/x" is.

Do we have a solution that doesn't require modifying any existing go code?

**Comment by jayconrod** [comment]
@guoshimin Just to give you a heads up, I'm planning on reversing the sense of `importpath` and `importmap`. `importpath` will be the *source* import path (the path that other packages write in the import declarations in source files). `importmap` will be the *actual* import path (not really visible except in stack traces). So you'd write a rule like this:

```
go_library(
    name = "go_default_library",
    srcs = ...
    importpath = "example.com/repo",
    importmap = "vendor/example.com/repo",
)
```

I think this is more in line with what people expect. The source import path will always be specified, and the actual import path only needs to be specified in cases where disambiguation is needed. Tools like Gazelle can read a single attribute to find the source import path.

Gazelle will generate `importmap` attributes for rules in vendor directories automatically.

This should resolve the issue you mentioned above.

**Comment by guoshimin** [comment]
There appears to be a regression in rules_go for go1.10. 

In https://github.com/guoshimin/rules_go_test/tree/cb84404f0d9e638ed518f1ab4ec794154fe8a926, I'm using the latest rules_go, and I set go_version to 1.9.4. `bazel build //versions/...:all` works fine.

Then, I change go_version to 1.10 in https://github.com/guoshimin/rules_go_test/commit/ca697b5ac30679d439fa2be1f100e936cceccf36. Now `bazel build //versions/...:all` fails with

```
INFO: Analysed 6 targets (8 packages loaded).
INFO: Found 6 targets...
ERROR: /home/shimin/rules_go_test/versions/BUILD.bazel:14:1: GoLink versions/linux_amd64_stripped/versions failed (Exit 1)
2018/02/22 07:29:29 duplicate symbol go.constinfo.foo.com/x (types 44 and 44) in bar.com/vendor/foo.com/x and bazel-out/k8-fastbuild/bin/versions/vendor/foo.com/x/linux_amd64_stripped/go_default_library~/foo.com/x.a(_go_.o)
2018/02/22 07:29:29 error running linker: exit status 1
INFO: Elapsed time: 21.869s, Critical Path: 9.22s
FAILED: Build did NOT complete successfully
```
It seems it doesn't like the fact that both vendor/foo.com/x/x.go and vendor/bar.com/vendor/foo.com/x/x.go define a const named foo. The code does compile using the go tool though.

**Comment by jayconrod** [comment]
@guoshimin You'll need to resolve this by adding `importmap = "bar.com/vendor/foo.com/x"` to the vendored `go_library` rule.

A binary may depend on multiple libraries with the same *source* import paths, but the *actual* import paths must be unique. By default, the actual import path is the same as the source import path, but it can be changed with the `importmap` attribute.

To be honest, this should have always been an error, and we should have caught it earlier in rules_go. It looks like the Go linker is now reporting the error, which is good. I plan to make Gazelle set `importmap` automatically for vendored libraries (bazelbuild/bazel-gazelle#131) so you won't have to do this by hand. Once that's done, the rules will report an error.

**Comment by guoshimin** [comment]
I did set importmap: https://github.com/guoshimin/rules_go_test/blob/ca697b5ac30679d439fa2be1f100e936cceccf36/versions/vendor/bar.com/vendor/foo.com/x/BUILD.bazel#L6. Had I not, go 1.9.4 would not have worked either. The only change that made it to go from working to not working was changing go_version from 1.9.4 to 1.10.

**Comment by jayconrod** [comment]
Ah, sorry, you had everything correct.

I spent some time staring at the command lines we're emitting and poking at the Go 1.10 toolchain. It appears that we should be passing `-p` the actual import path (i.e., `importmap`). We were passing the source import path. I'll send a PR shortly.
