### ISSUE TITLE
sha256 not checked on go_repository

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_go#1244]
I would like to enforce `sha256` checksums for all our third party dependencies but adding an incorrect sha256 to a `go_repository` rule does not seem to do anything, it just seems to be ignored (e.g. on running `bazel build :library` and that library depends on that go_repository). Is this as expected?

**Comment by jayconrod** [comment]
I can't reproduce this. Could you show a `go_repository` rule where you're using this?

Internally, `go_repository` has two methods of fetching a repo: it can clone a repository using a VCS tool (git, hg, etc) or it can download an HTTP archive. I'm guessing you're doing the former. `sha256` is only used to verify downloaded HTTP archives. For VCS downloads, we assume the VCS tool will verify the revision id that gets checked out.

We should fail with a more reasonable error message if VCS-only or HTTP-only attributes are used in the wrong mode.

**Comment by Globegitter** [comment]
@jayconrod ah that makes sense. Yes `go_repository` rules generally are like:
```
go_repository(
        name = "org_golang_x_text",
        commit = "e19ae1496984b1c655b8044a65c0300a3c878dd3",
        importpath = "golang.org/x/text",
    )
```

Thanks for the quick PR to improve error messages.
