### ISSUE TITLE
rules_go ignores vendor inside vendor dependency

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_go#1245]
Verified on latest bazel (0.9.0) and latest rules_go (commit hash 93fbdfae183f24c1bea4dc6f776188523ba3a2be)

Please take a look to repo
https://github.com/excavador/bazel_vendor_inside_vendor

**Comment by jayconrod** [comment]
Closing in favor of bazelbuild/bazel-gazelle#91.
