### ISSUE TITLE
rules_go fails on ci.bazel.io 

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_go#125]
After PR #116. See http://ci.bazel.io/job/rules_go/355/

**Comment by pmbethe09** [comment]
@pcj do you have a fix for this?

**Comment by pcj** [comment]
@pmbethe09 Happy to help, but looks like @yugui working on it?  Don't want to duplicate work.  Pls instruct further if needed.

**Comment by yugui** [comment]
There looks to be another test failure on darwin.
http://ci.bazel.io/job/PR-rules_go/121/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/testReport/junit/(root)/go_tools_gazelle_wspace_go_default_test/go_tools_gazelle_wspace_go_default_test/

**Comment by pcj** [comment]
Would it be desirable to have a travis CI build as well to triage issues before they go to ci.bazel.io?  Would be happy to contribute this.

**Comment by pcj** [comment]
That may be silly idea.  Jenkins enough is probably fine.

**Comment by damienmg** [comment]
If you call the jenkins voting before submitting every PR you should be
safe.
