### ISSUE TITLE
gogo proto: `no such attribute 'compilers' in 'go_proto_library' rule`

### ISSUE THREAD

**Issue by dwsilver** [bazelbuild/rules_go#1271]
I'm investigating adopting Bazel for our Go codebase, and I'm currently stuck on the getting the proto files to compile correctly with gogo. The Gazelle auto-generated rules compile them correctly using the default compiler, but I'm not sure how to activate the gogo support in 0.9.0. 

I've seen [the example](https://github.com/bazelbuild/rules_go/blob/985b08a07c3fe8c3a305bae8204da4e8c13fe17d/tests/legacy/examples/proto/gogo/BUILD.bazel), but it's not clear exactly what changes I need to make. 

Here is my attempt at a build file. This is the Gazelle-generated file after attempting to follow the example:
```load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "cheese_proto",
    srcs = ["cheese.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "cheese_go_proto",
    importpath = "example.com/stuff/cheese",
    proto = ":cheese_proto",
    visibility = ["//visibility:public"],
    compilers = ["@io_bazel_rules_go//proto:gogo"],
)
```

This produces an error:
`no such attribute 'compilers' in 'go_proto_library' rule`

I'm on latest released version (0.9.0). 

What changes do I have to make to build the proto files using gogo? Do I update the build file like I was trying? Is there a global setting to use it for everything? Is there a way to get Gazelle to generate these for me?

**Comment by ianthehat** [comment]
The example is a test that should pass, the only reason I can see for the error you are seeing is if you are on a version of rules_go from before the compilers attribute was added.

you should be able to do
`bazel test @io_bazel_rules_go//tests/legacy/examples/proto/gogo/... `
and get something like
```
$bazel test @io_bazel_rules_go//tests/legacy/examples/proto/gogo/...
INFO: Analysed 3 targets (167 packages loaded).
INFO: Found 2 targets and 1 test target...
INFO: Elapsed time: 31.876s, Critical Path: 7.43s
INFO: Build completed successfully, 50 total actions
@io_bazel_rules_go//tests/legacy/examples/proto/gogo:gogo_test           PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
```

**Comment by dwsilver** [comment]
Yes, that was the problem. I was using an old branch that had an old go_rules specified. I updated to the latest set of go rules now it's working. 

Thanks!
