### ISSUE TITLE
Need clear way to use private github repos with go_repository

### ISSUE THREAD

**Issue by 1mentat** [bazelbuild/rules_go#1280]
Having spent the last couple hours Googling and looking at github issues to try and make this work, at least from a documentation perspective, there needs to be a clear way to include private github repositories with go_repository(). The answer is probably really simple but I'm not finding it.

**Comment by 1mentat** [comment]
It appears that the answer is:

```
    vcs = "git",
    remote = "git@github.com:<org>/<project>.git",
```

**Comment by ianthehat** [comment]
What would be the best way to make this clear in the documentation?

**Comment by 1mentat** [comment]
Probably just something in the overview for go_repository that just says the above. Though from some of the stuff I read it'll be going away soon?

**Comment by ianthehat** [comment]
It is, but not soon enough that it's not worth documenting properly.

**Comment by 1mentat** [comment]
Thank you!
