### ISSUE TITLE
go_context docs need a mention of _go_context_data

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1281]
The go_context docs in https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst don't mention that your rule also needs

```
"_go_context_data": attr.label(default=Label("@io_bazel_rules_go//:go_context_data"))
```

in its arguments.

**Comment by ianthehat** [comment]
It's not supposed to be documented, it's supposed to be totally hidden from you so I can change it. You are supposed to declare the rule with `go_rule` instead (as documented [here](/bazelbuild/rules_go/blob/master/go/toolchains.rst#the-context)
Given that this was not clear the documentation is probably needs some fixing, what do I need to change?

**Comment by jmhodges** [comment]
Psssh, I dunno. I might be a special case of someone who came in with too much out-of-date knowledge.

I'll close this since you've answered me and I have no good ideas about what to do about the docs

**Comment by jmhodges** [comment]
Thank you!
