### ISSUE TITLE
Support analysis tools

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#1292]
We need to be able to support vet like tools that allow library compilation to fail if the tests fail.
Ideally this should happen in parallel with the compile, and be configurable such that new checks can be added globally, for specific targets, and for all dependencies of specific targets.

We may want lint like tools to be able to run with the same mechanism, but that is not a fundamental requirement.

**Comment by jayconrod** [comment]
(Re-triaging old issues)

[nogo](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) implements this functionality.
