### ISSUE TITLE
Allow specifying args to containers in the BUILD file

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_go#1296]
Currently, if you define something like:

```
  go_image(
    name = "something_image",
    importpath = "unused",
    embed = embed,
    args = ["--port=8080"],
  )
```

then you are able to run: `bazel run :something_image.binary` and bazel will add the `--port=8080` to the binary and run it for you.

This behavior is defined for `*_binary`. The documentation says "Most binary rules permit an args attribute, but where this attribute is not allowed, this fact is documented under the specific rule.".

Unfortunately, this doesn't seem to work when the container itself is built and run: the CMD and/or Entrypoint in the container specification are not updated with the specified args.

Would it be acceptable for rules_docker to respect the `args` parameter add it to the container arguments' in the container image?

**Comment by jayconrod** [comment]
Could you file this issue at bazelbuild/rules_docker instead? `go_image` is defined there. Seems like a reasonable feature to have though.
