### ISSUE TITLE
go/tools/wtool failed to compile

### ISSUE THREAD

**Issue by kaoet** [bazelbuild/rules_go#1298]
With `rules_go-0.9.0` and `bazel-gazelle-0.9` in my WORKSPACE file.

```
$ bazel run @io_bazel_rules_go//go/tools/wtool
ERROR: /private/var/tmp/_bazel_kaoet/36fa48d35610c3df93350ffe6ac2b55e/external/io_bazel_rules_go/go/tools/wtool/BUILD.bazel:3:1: no such package '@bazel_gazelle//resolve': BUILD file not found on package path and referenced by '@io_bazel_rules_go//go/tools/wtool:wtool'
ERROR: Analysis of target '@io_bazel_rules_go//go/tools/wtool:wtool' failed; build aborted: no such package '@bazel_gazelle//resolve': BUILD file not found on package path
INFO: Elapsed time: 0.336s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

It seems that `@bazel_gazelle//resolve` is moved to `@bazel_gazelle//internal/resolve`.

Workaround:
1. `go get -v -u github.com/bazelbuild/rules_go/go/tools/wtool`
2. `cd $GOPATH/src/github.com/bazelbuild/bazel-gazelle`
3. `git checkout 4fdd1313eca9d262ca3cf607b5befc1577a120fe`
4. `go install -v github.com/bazelbuild/rules_go/go/tools/wtool` to get the `wtool` binary.

**Comment by ianthehat** [comment]
As mentioned in [this post](https://groups.google.com/forum/#!topic/bazel-go-discuss/HVkeMs-TnmI) wtool is being deleted in the very near future, gazelle does everything it does but better now.
