### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_go#1301]
```
every rule of type go_context_data implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Unsupported operating system: freebsd
```

**Comment by jayconrod** [comment]
We use `ctx.os.name` and `uname -p` to detect the host operating system before downloading an SDK. The logic is in `_go_download_sdk_impl` in [go/private/sdk.bzl](https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl).

We don't have a way to verify changes on FreeBSD. However, if you send us a PR that correctly detects FreeBSD, we will merge it.

**Comment by rescrv** [comment]
I'm hoping the invitation to submit a PR is still welcome:  https://github.com/bazelbuild/rules_go/pull/1497

**Comment by jayconrod** [comment]
#1497 was merged, so this should be closed. Thanks!
