### ISSUE TITLE
Build failure with cross compiled stdlib

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1304]
Suppose we have a minimal program that imports a standard library package via a library.

lib.go

```
package lib

import _ "syscall"
```

main.go

```
package main

import _ "example.com/lib"
```

BUILD.bazel

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "lib",
    srcs = ["lib.go"],
    importpath = "example.com/lib",
)

go_binary(
    name = "main",
    srcs = ["main.go"],
    deps = [":lib"],
)
```

If we cross compile this using a toolchain explicitly specified on the command line, we're unable to import the standard package:

```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //:main
...
ERROR: /usr/local/google/home/jayconrod/go/src/example.com/repo/BUILD.bazel:3:1: GoCompile darwin_amd64_pure_stripped/lib~/example.com/lib.a failed (Exit 1).
lib.go:3:8: can't find import: "syscall"
```

**Comment by jayconrod** [comment]
This worked in rules_go 0.8.0. It was broken with a different message in 0.9.0. The actual stdlib missing changes every time. nacl seems particularly silly.

```
ERROR: While resolving toolchains for target @go_stdlib_nacl_arm_cgo_race//:go_stdlib_nacl_arm_cgo_race: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain.
ERROR: Analysis of target '//:main' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain.
```

**Comment by jayconrod** [comment]
The cause of this seems to be as follows:

* `go_library` depends on `@io_bazel_rules_go//:stdlib` through the implicit `_stdlib` attribute added by `go_rule`. Since `go_library` does not have mode attributes, this is a regular dependency, not through an aspect.
* `stdlib` calls `go_context`, which retrieves the toolchain. `stdlib` uses `@io_bazel_rules_go//go/toolchain:bootstrap_toolchain`.
* There are no cross-compiling bootstrap toolchains; the bootstrap toolchain is intended to build host-mode binaries. So the host toolchain is selected.
* Everything goes wrong after this. We get `goos` and `goarch` from the toolchain, and we get the host values instead of the target values.

We *can* build a binary that depends directly on stdlib packages. The `_stdlib` attribute on `go_binary` is an aspect, which uses the regular toolchain, not the bootstrap toolchain.

We can also build a binary that cross-compiles using `goos` / `goarch` attributes. Again, this builds the stdlib via the aspect.

**Comment by steeve** [comment]
This seems related to my issue at https://github.com/bazelbuild/rules_go/issues/1264#issuecomment-362717819
