### ISSUE TITLE
go_embed_data tool and rule

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/rules_go#1313]
This would be quite useful.

see https://github.com/kubernetes/kubernetes/issues/59491

**Comment by jayconrod** [comment]
I have a couple things that might work for you already.

[`go_embed_data`](https://github.com/bazelbuild/rules_go/blob/master/go/extras.rst#go-embed-data) is similar to the Blaze macro of the same name, both in its interface and the file that it generates.

We also have [extras/bindata.bzl](https://github.com/bazelbuild/rules_go/blob/master/extras/bindata.bzl) which uses go-bindata (now a fork of the original). That one is undocumented. It's mostly an example of how to write a rule with the Go toolchain.

**Comment by mikedanese** [comment]
Awesome! Thanks for the pointer.
