### ISSUE TITLE
gopath returns a relative path

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1318]
So, in my code that uses the gopath API stuff, I found I needed 

```
gopath = "$(pwd)/" + ctx.var["BINDIR"] + "/" + ctx.attr.gopath_dep[GoPath].gopath
```

in my skylark when I'm going to set that `gopath` variable to `GOPATH`.

If I use just `ctx.attr.gopath_dep[GoPath].gopath` as `GOPATH`, the Go tooling yells at me with errors about relative paths:

```
go: GOPATH entry is relative; must be absolute path: "go/svc/fe/darwin_amd64_stripped/mock_sess_gomock_gopath~".
```

Is there some way we can make this better or is there some other way of doing this that is already better?

**Comment by jmhodges** [comment]
You can see this in use at https://github.com/jmhodges/bazel_gomock/blob/2b50dd4dd44829d0cf347f58011cacde1c395b7e/gomock.bzl#L9

**Comment by jmhodges** [comment]
(I should note that `"$(pwd)/" + ctx.attr.gopath_dep[GoPath].gopath` doesn't work and the go tooling will not be able to find the Go libraries requested.)

**Comment by jmhodges** [comment]
(Also, looking at how `gopath` is defined, maybe this is working by happenstance? I don't really understand the `_tag` function.)

**Comment by jayconrod** [comment]
cc @ianthehat Why does `go_path` return `short_path` here? Could we use `declare_directory` and return that `File` instead?

**Comment by ianthehat** [comment]
Directory file targets were broken when I wrote this rule (and I think still are for remote execution) but this could probably use them now.
go_path is very neglected, and hopefully in the future redundant, but if there are simple changes that make it work better right now I would be happy to accept them.

**Comment by jayconrod** [comment]
Closing some old issues.

I rewrote `go_path` some time after this issue was filed, so I'm not sure if it's still applicable. `GoPath.gopath` should be the short path to the file (useful for executables and tests), and `GoPath.gopath_file` is the long path (useful for actions). Both paths are relative, but the `$(pwd)/` trick should work, depending on the situation.

Please re-open if you're still having issues.
