### ISSUE TITLE
Cross compile windows on linux

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_go#1319]
How do you cross compile to windows from linux? When setting `--cpu=x64_windows` I'm getting 

```sh
ERROR: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for CPU 'x64_windows' and compiler 'msvc-cl'
```

Pure builds with `--features=pure` work. Other targets seem to fail. `armeabi-v7a` compiles if I set `--features=pure` before `--cpu`. Is this a problem with my environment or an issue with the binary?

**Comment by jayconrod** [comment]
Does your build include any cgo code or C++ dependencies? It's difficult to cross-compile those, and that may not fully work.

If you are building a pure Go binary, you can cross compile with `--platforms=@io_bazel_rules_go//go/toolchains:windows_x64` on the command line.

You can also set the `goos` and `goarch` attributes in `go_binary`. Be careful though: `select` expressions are not aware of these, so if you have any platform-specific dependencies, you may have problems.

**Comment by afking** [comment]
@jayconrod thanks, getting closer but still having issues. Building with `--platforms` returns:

```sh
bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //installer
..
ERROR: While resolving toolchains for target @go_stdlib_windows_386_pure_race//:go_stdlib_windows_386_pure_race: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//installer:installer' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
```

If I set `goos = "windows", pure = "on"` I then get a select issue but build starts to compile. Anyway to get around the selects or do you need to alter the BUILD file to remove them?

**Comment by afking** [comment]
@jayconrod sorry to bug you, any updates on this? Is there a setting for `gazelle` to remove all the file selections?

**Comment by jayconrod** [comment]
@afking Sorry, not yet. I'm planning to tag releases of rules_go and Gazelle this week (probably today actually), then I'll make several changes to Gazelle rule generation shortly after that. This will be the first of those changes.

**Comment by afking** [comment]
Closing, removed `goos` and `goarch` attributes in favor of `bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64` which works!
