### ISSUE TITLE
Conflicts with google.golang.org/grpc/status

### ISSUE THREAD

**Issue by astratto** [bazelbuild/rules_go#1332]
Hi! This is more of a request for info/help than a bug report, so please correct me if I'm completely wrong here.

I'm currently seeing a failure with an application that imports and uses `google.golang.org/grpc/status`.

The code is something like

```
import (
...
	grpccodes "google.golang.org/grpc/codes"
	grpcstatus "google.golang.org/grpc/status"
)
...

switch grpcstatus.Code(err) {
...
```
And here's the failure:

```
$ bazel test myapp/lib.go:132:10: undefined: "google.golang.org/grpc/status".Code
myapp/lib.go:235:51: undefined: "google.golang.org/grpc/status".Code
2018/02/15 16:03:00 error running compiler: exit status 1
(16:03:00) INFO: Elapsed time: 22.320s, Critical Path: 2.02s
(16:03:00) FAILED: Build did NOT complete successfully
```

---

The `Gopkg.toml` file contains: 
```
[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.9.1"
```

The `Gopkg.lock` file contains: 
```
[[projects]]
  name = "google.golang.org/grpc"
  packages = ...
  revision = "6b51017f791ae1cfbec89c52efdf444b13b550ef"
  version = "v1.9.2"
```

The `Gopkg.bzl` file contains: 
```
go_repository(
    name = "org_golang_google_grpc",
    importpath = "google.golang.org/grpc",
    urls = ["https://github.com/grpc/grpc-go/archive/6b51017f791ae1cfbec89c52efdf444b13b550ef.tar.gz"],
    ...
)
```
---

For some reason it looks like it’s picking up an old version that doesn’t have Code() on status:

```
$ cat /home/vagrant/.cache/bazel/_bazel_vagrant/67aba0381bcebf737397fb417afebbd8/external/org_golang_google_grpc/rpc_util.go
...
// Version is the current grpc version.
const Version = "1.6.0"
```

Searching for the commit hash for _1.6.0_ (`f92cdcd7dcd`), the only reference is in `rules_go/go/private/repositories.bzl`:
```
_maybe(git_repository,
    name = "org_golang_google_grpc",
    remote = "https://github.com/grpc/grpc-go",
    commit = "f92cdcd7dcdc69e81b2d7b338479a19a8723cfa3",  # v1.6.0, latest as of 2017-10-10
    overlay = manifest["org_golang_google_grpc"],
)
```

Ideas?

**Comment by jayconrod** [comment]
We declare `@org_golang_google_grpc` inside `go_rules_dependencies`. I'll update the dependency today to avoid this problem.

It's possible to work around this by declaring your own version of `org_golang_google_grpc` before calling `go_rules_dependencies` in WORKSPACE. However, that's going to be difficult because `go_repository` probably won't work at that point. So you'll either need to update `io_bazel_rules_go` to tip after the dependency is updated, or just copy the rule and the overlaid build files after the update.

**Comment by astratto** [comment]
Thanks again Jay! I wasn't sure that's what is causing the conflict, so thanks for confirming that! 😄 

I'm already working off of `master` because of the patch for `1.9.4`, so it's not a big deal.

**Comment by astratto** [comment]
@jayconrod one question about this: is there a way/plan to prevent this in future?

I noticed that there are several dependencies that are quite commonly used in other projects (i.e., `github.com/gogo/protobuf`) and I guess this overlap means that `rules_go` forces them to use a specific version.

**Comment by jayconrod** [comment]
@astratto Not sure what we can do, other than update these dependencies in rules_go more regularly.

All rules_go dependencies can be overridden by declaring them before calling `go_rules_dependencies()`. You should be able to do this with `go_repository` for anything that doesn't already have build files. The overlay rules may be useful as well once we have a better workflow for using them with Gazelle.

There is some work going on in Bazel with recursive workspace evaluation. Once that's complete, you won't need to call `go_rules_dependencies()` anymore, but you may still want to override repositories with alternate versions, which presents the same challenges as now. At least the overriding will be more intuitive (it shouldn't matter where in WORKSPACE you override).
