### ISSUE TITLE
Discussion: rules_go should not depend on gRPC (and other repos) if it doesn't use them

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/rules_go#1335]
Motivation: I spent an hour cursing at the Go compiler for `undefined: "google.golang.org/grpc/status".Code`. The reason was that rules_go binds gRPC v1.6, and I status.Code() only appeared in a later version. I of course forgot that I didn't bind it myself.

I argue that rules_go shouldn't bind gRPC, because
1. it's almost immediately out of date
2. it can't be safely updated, in case a user of rules_go used the default version and the new gRPC version isn't backwards safe. (I'm surprised this hasn't happened before, so my analysis might be wrong).

Related - how do I bind my own version? I ended up copy-pasting to my `WORKSPACE` from https://github.com/bazelbuild/rules_go/commit/0cd983e2c6f6665fcae3e93eb303a00e54dc6fc5:

```
load("@io_bazel_rules_go//go/private:go_repository.bzl", "go_repository")

go_repository(
    name = "org_golang_google_grpc",
    build_file_proto_mode = "disable",  # use existing generated code
    commit = "8e4536a86ab602859c20df5ebfd0bd4228d08655",  # v1.10.0
    importpath = "google.golang.org/grpc",
)
```

Looks like I'm using a private API, and not sure if I can use simple `http_archive` because of lack of `BUILD.bazel` files.

**Comment by jayconrod** [comment]
In principle, I completely agree: rules_go should have a really minimal set of dependencies. I would actually prefer the proto rules to be in a separate repository with separate dependencies.

The reasons for not changing this are mainly practical: I want to minimize API churn. Removing these dependencies from `go_rules_dependencies()` by default would break everyone depending on them. I expect we'll need to change the WORKSPACE API when the Bazel recursive workspace work is finished. Maybe we can do this at the same time.

About overriding the version, what you're doing is correct. Just declare another repository rule with the same name before `go_rules_dependencies` is called. It's ugly, but without recursive workspaces, any abstraction in WORKSPACE will be very leaky.

**Comment by cgrushko** [comment]
My argument is that the built-in version is ~never correct, so everyone is going to bind their own version anyway, so might as well remove the confusion. Same argument for all of the repositories that `rules_go` brings in as a convenience.

Re binding my own version - if people are expected to use `//go/private:go_repository.bzl` then it should be moved out of `private`.

**Comment by jayconrod** [comment]
`rules_go` doesn't declare repositories as a convenience -- `go_proto_library` will not work at all without proto dependencies. Of course, if you're not using gRPC, you don't need the gRPC dependency, but then it doesn't matter.

But what's the alternative? We could make a list of repositories and ask people to include the ones they need in their WORKSPACE, perhaps with some function that declares a default if none is specified. But that's `go_rules_dependencies`.

> Re binding my own version - if people are expected to use //go/private:go_repository.bzl then it should be moved out of private.

Sorry I missed the `private` from you're earlier comment. The canonical place to load `go_repository` is `@io_bazel_rules_go//go:def.bzl`. All our public symbols are there. I'm working on moving `go_repository` to `@bazel_gazelle` so we can drop Gazelle's dependencies, but the transition isn't complete yet.

**Comment by cgrushko** [comment]
> `go_proto_library` will not work at all without proto dependencies

Correct, and by providing a protobuf binding without the user's direct action, you make it more convenient for them. Or so it seems - I argue that the user is better off with setting their own dependencies themselves (because the version you give them is wrong, etc.).

**Comment by jayconrod** [comment]
I don't think I agree -- users already have the power to override versions of these repositories in WORKSPACE when they need to. Forcing them to declare dependencies on everything that they need transitively through rules_go means a lot of boilerplate to paste in for new projects. It also means that upgrading rules_go is more difficult: if we depend on a new protobuf feature in our implementation, and users have declared an old version because they pasted boilerplate from our documentation a few months ago, things will break without an apparent reason.

I expect the current situation will improve in a couple ways. First, I'm planning to do more regular releases in rules_go. We will update our dependencies to newer versions every major release, roughly every month. Second, I'm really hoping recursive Bazel recursive workspaces arrives soon and we have a better way to specify and resolve conflicts in transitive dependencies.
