### ISSUE TITLE
go_test does not run (or build) testable examples

### ISSUE THREAD

**Issue by bobcatfish** [bazelbuild/rules_go#1341]
When running tests with `go test`, [testable examples](https://blog.golang.org/examples) will be run as well. However when using the bazel rule `go_test` with a testable example included in the `srcs`, the testable example is not run.

For example, if I modify the  [testable examples](https://blog.golang.org/examples) example to panic:
```
package stringutil_test

import (
        "errors"
        "fmt"

        "github.com/golang/example/stringutil"
)

func ExampleReverse() {
        fmt.Println(stringutil.Reverse("hello"))
        // Output: olleh
        panic(errors.New("ERMAGHERD!"))
}
```
And I run this with `go test`, I get:

```
$ go test -v                                 
=== RUN   ExampleReverse
--- FAIL: ExampleReverse (0.00s)
panic: ERMAGHERD! [recovered]
	panic: ERMAGHERD!
...
```

But if I put the same func into the src of a test file in a `go_test` rule, and I run it with `bazel test`, instead any tests in the file (i.e. funcs starting with `Test`) are run, but the example is not.

**Comment by mattmoor** [comment]
@ixdy FYI (not sure if K8s uses these)
