### ISSUE TITLE
go_local_sdk() - symlink-to-symlink results in broken SDK

### ISSUE THREAD

**Issue by teeler** [bazelbuild/rules_go#1345]
`go_local_sdk()` symlinks the provided SDK, but during calls to the `stdlib` builder, but the helper used to replicate paths doesn't follow symlinks:

https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/replicate.go#L108

At first, i thought that there was just a check missing to see if the symlink was actually a directory, but then, from https://golang.org/pkg/path/filepath/#Walk:

> "Walk does not follow symbolic links."

So, even though I have a directory structure from local_sdk:
```
(¬‿¬) ls -alh
total 24K
drwxr-x--- 2 rtp eng 4.0K Feb 22 00:25 .
drwxr-x--- 9 rtp eng 4.0K Feb 22 11:45 ..
lrwxrwxrwx 1 rtp eng   28 Feb 22 00:25 bin -> /tmp/go/bin
-rw-r----- 1 rtp eng  363 Feb 22 00:25 BUILD.bazel
-rwxr-x--x 1 rtp eng 4.1K Feb 22 00:25 packages.txt
lrwxrwxrwx 1 rtp eng   28 Feb 22 00:25 pkg -> /tmp/go/pkg
-rwxr-x--x 1 rtp eng    0 Feb 22 00:25 ROOT
lrwxrwxrwx 1 rtp eng   28 Feb 22 00:25 src -> /tmp/go/src
-rw-r----- 1 rtp eng  103 Feb 22 00:25 WORKSPACE
```

`replicateTree()` fails to actually copy anything 😢 
This results in the call to `go install` (https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/stdlib.go#L68) failing because:

> can't load package: package runtime/cgo: cannot find package "runtime/cgo" in any of:

I thought a simple solution would be just to copy the files directly instead of symlinking, but the only conceivable way to do that with the `repository_ctx` is by manually executing `cp` (which might not be super platform independent)?

**Comment by jayconrod** [comment]
I'm having trouble reproducing this. Could you post the output of `ls -l` in the directory referenced by `local_sdk`? Also, what operating system are you on? Symlinks may work a little differently on Windows.

The `@go_sdk` repository *may* contain symlinks to the top-level directories inside the GOROOT. `replicateTree` dereferences those here: https://github.com/bazelbuild/rules_go/blob/d4b304b8f2173837791da28c66683a5fe5e5c56e/go/tools/builders/replicate.go#L132

It only dereferences one symlink though. I don't think it will work if it's a symlink to a symlink. Could that be what's happening here?

**Comment by teeler** [comment]
Just to confirm - it was a symlink to a symlink, and swapping os.Readlink for filepath.EvalSymlinks resolves the issue.

**Comment by teeler** [comment]
Thanks for all the help Jay!
