### ISSUE TITLE
go_binary: support build constraints via build_setting

### ISSUE THREAD

**Issue by justinsb** [bazelbuild/rules_go#1351]
I have a library which requires custom build tags to build it (because there are two modes of operation, and we switch between them using build tags).

Specifically, if building from make I need to do this:

` go build -o $@ -tags 'peer_name_alternative peer_name_hash' k8s.io/kops/protokube/cmd/protokube`

When I try what I believe to be the equivalent syntax with bazel the tags appear to be ignored - they aren't visible on the command line with `bazel build -s` for example, and I get a compilation error that suggests the code was ignored.

I'm adding this to go_library: `tags = [  "peer_name_alternative", "peer_name_hash"  ],  # keep`.  Actual code is here: https://github.com/kubernetes/kops/pull/4514/files 

Is there a different place / way I should be passing the tags?

**Comment by jayconrod** [comment]
Build tags aren't actually supported yet. Our compiler wrapper filters source files using tags, but it doesn't have any way to turn on custom tags. #1340 should add some support for this, plus several other changes. You'll pass `--define=gotags=foo,bar,baz` on the command line when building.

This assumes that tags pull in alternate files that aren't normally required, e.g., extra debug or profiling code. If you have a library that *requires* tags to build, maybe we can add a `go_tags` attribute or something like that.

Note that the `tags` attribute is common to all Bazel rules. rules_go doesn't interpret that attribute directly. It makes it easier to identify specific rules using `bazel query`, and some tags like `manual` have special meaning to Bazel.

**Comment by jayconrod** [comment]
#2219 will provide a framework for supporting this.
