### ISSUE TITLE
go_path: support vendoring

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1372]
go_path should write packages into a vendor directory if they were originally defined in a vendor directory.

This should be controlled with a new attribute like `vendor = True`. Probably off by default.

rules_go generally doesn't recognize vendoring at all. Gazelle knows about vendor directories in order to set `importpath` and resolve dependencies, but directory names aren't communicated directly to `go_path`. Maybe examining package names in labels will be good enough though.

**Comment by ianthehat** [comment]
The vendored ones should have the importmap set, gopath should obey that (which it needs to anyway to disambiguate things with identical import paths)
