### ISSUE TITLE
resolve the import org_golang_x_oauth2 

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#1399]
I meet a error when i build grpc with rules_go

```
ERROR: /private/var/tmp/_bazel_bilibili/bd4bb69cb618928c1f3c0616978ab91f/external/org_golang_google_grpc/interop/BUILD.bazel:3:1: no such package '@org_golang_x_oauth2//google': The repository could not be resolved and referenced by '@org_golang_google_grpc//interop:go_default_library'
```
then i find the [repositories.bzl
](https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl) that have not information about org_golang_x_oauth2.

so is it a problem?

**Comment by hawkingrei** [comment]
I find the solution.

I add some configure in the WORKSPACE to solve this problem

```

go_repository(
    name = "com_google_cloud_go",
    commit = "7808a7bf89ab1b3b840e00435c5404af438ec24d",
    importpath = "cloud.google.com/go",
    remote = "git@github.com:GoogleCloudPlatform/google-cloud-go.git",
    vcs = "git",
)

go_repository(
    name = "org_golang_x_oauth2",
    remote = "git@github.com:golang/oauth2.git",
    vcs = "git",
    commit = "fdc9e635145ae97e6c2cb777c48305600cf515cb",
    importpath = "golang.org/x/oauth2",
)
```

but if adding this configure to repositories .bzl, it is more friendly

**Comment by jayconrod** [comment]
I'm glad you were able to resolve the error.

repositories.bzl declares repositories that rules_go itself depends on. Ideally, this list of repositories is as short as possible. We don't use oauth2 directly, so it's better for developers to declare it in their own projects.
