### ISSUE TITLE
Cannot compile a simple example app

### ISSUE THREAD

**Issue by denesalmasi** [bazelbuild/rules_go#14]
Dear Bazel Go folks,

I have tried to create a simple example workspace loosely based on what's here in the repo and I am unable to import my sample library to a binary. I fail to see what problem could I have with the contents of the files and I see a suspicious line in the error message.

I have attached example.tar.gz, an archive that contains this simple example workspace.

Attempting to build //example/samplebin:my_bin_target, I see the following error:

```
[denes@rudanium example]$ bazel build example/samplebin:my_bin_target
INFO: Found 1 target...
ERROR: /home/denes/goexp/example/example/samplebin/BUILD:3:1: error executing shell command: 'rm -rf bazel-out/local-fastbuild/bin/example/samplebin/my_bin_target.a.dir && mkdir -p bazel-out/local-fastbuild/bin/example/samplebin/my_bin_target.a.dir && mkdir -p bazel-out/local-fastbuild/bin/...' failed: namespace-sandbox failed: error executing command /home/denes/.cache/bazel/_bazel_denes/533fb7a800c9d3f6af2a311f02e299bb/example/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
github.com/bazelbuild/rules_go/example/samplebin/samplebin.go:5: can't find import: "example.org/repo/example/samplelib"
Target //example/samplebin:my_bin_target failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.683s, Critical Path: 0.76s
```

This line: `github.com/bazelbuild/rules_go/example/samplebin/samplebin.go:5: can't find import: "example.org/repo/example/samplelib"` is strange. Is it normal that it copies my go file into such directory structure that starts with github.com/bazelbuild/rules_go? Why not "example.org/repo" instead? (The string I specified as go_prefix) I suspect that this may be a bug but I admit I don't know much about the internals of these rules yet.

Will also look into the bzl file myself...

Bazel version 0.2.1, go version go1.6.1 linux/amd64, running this on Arch Linux.
**Workspace: [go-example.tar.gz](https://github.com/bazelbuild/rules_go/files/232954/go-example.tar.gz)**

Thanks for your help,
Dénes

**Comment by yugui** [comment]
It is a bug of rules_go, which was fixed in 3dc43724d4d914294d9021a6a809fe74410d28e8.

Unfortunately rules_go v0.0.1 does not contain the commit.  So you need to replace the `git_repository` in your `WORKSPACE` with something like:
```bzl
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "3dc43724d4d914294d9021a6a809fe74410d28e8",
)
```

**Comment by jdanekrh** [comment]
I've encountered this issue in the current master branch:

    git clone https://github.com/bazelbuild/rules_go.git
    cd rules_go
    ~/bin/bazel build //examples/bin:all

Output from the last command is

    INFO: Found 1 target...
    ERROR: /home/vagrant/rules_go/examples/lib/BUILD:7:1: error executing shell command: 'rm -rf bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/...' failed: namespace-sandbox failed: error executing command /home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
    Target //examples/bin:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.168s, Critical Path: 0.04s

When running the last command with debugging options, the result is

    $ ~/bin/bazel build //examples/bin:all --verbose_failures --sandbox_debug 
    INFO: Found 1 target...
    ERROR: /home/vagrant/rules_go/examples/lib/BUILD:7:1: error executing shell command: 'rm -rf bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/...' failed: 

    Sandboxed execution failed, which may be legitimate (e.g. a compiler error), or due to missing dependencies. To enter the sandbox environment for easier debugging, run the following command in parentheses. On command failure, a bash shell running inside the sandbox will then automatically be spawned:

    namespace-sandbox failed: error executing command 
    (cd /home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go && \
    exec env - \
        GOARCH=amd64 \
        GOOS=linux \
    /home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go/_bin/namespace-sandbox @/home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go/bazel-sandbox/2ec34737-4e2e-4f03-ba19-b7166a01bc00-0.params -- /bin/bash -c 'rm -rf bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && mkdir -p bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir/github.com/bazelbuild/rules_go/examples/lib && ln -s ../../../../../../../../../../../examples/lib/lib.go bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir/github.com/bazelbuild/rules_go/examples/lib/lib.go && export GOROOT=$(pwd)/external/golang_linux_amd64/go/bin/.. && cd  bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a.dir && ../../../../../../external/golang_linux_amd64/go/bin/go tool compile -o ../../../../../../bazel-out/local-fastbuild/bin/examples/lib/go_default_library.a -pack -I . github.com/bazelbuild/rules_go/examples/lib/lib.go').
    src/main/tools/namespace-sandbox.c:761: sandbox root is /home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go/bazel-sandbox/2ec34737-4e2e-4f03-ba19-b7166a01bc00-0
    src/main/tools/namespace-sandbox.c:763: working dir is /home/vagrant/.cache/bazel/_bazel_vagrant/dfcbd34cf5cd1f666bcaf1073daa9d3f/rules_go
    src/main/tools/namespace-sandbox.c:392: unshare succeeded after 1 tries
    Target //examples/bin:bin failed to build
    INFO: Elapsed time: 0.147s, Critical Path: 0.03s

When I switch sandbox off, the build succeeds

    $ ~/bin/bazel build //examples/bin:all --spawn_strategy=standalone
    INFO: Found 1 target...
    Target //examples/bin:bin up-to-date:
      bazel-bin/examples/bin/bin.a
      bazel-bin/examples/bin/bin
    INFO: Elapsed time: 0.405s, Critical Path: 0.28s

I am using `Red Hat Enterprise Linux Server release 7.2 (Maipo)`  running inside Docker with kernel `Linux 58896ba9515a 4.4.8 #1-NixOS SMP Wed Apr 20 06:44:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pnasrat** [comment]
Looking at the sandbox code I think maybe is a known issue (also it's in bazel not go_rules themselves)

https://github.com/bazelbuild/bazel/blob/master/src/main/tools/namespace-sandbox.c#L381

  // This weird workaround is necessary due to unshare seldomly failing with
  // EINVAL due to a race condition in the Linux kernel (see
  // https://lkml.org/lkml/2015/7/28/833). An alternative would be to use
  // clone/waitpid instead.

The original mail link to lkml.org seems broken but can be found at other archives http://lkml.iu.edu/hypermail/linux/kernel/1507.3/03207.html

Although that thread talks about considering that patch it doesn't look merged I do see a later change that my be related

https://git.kernel.org/cgit/linux/kernel/git/ebiederm/user-namespace.git/commit/kernel/user_namespace.c?h=for-linus&id=faf00da544045fdc1454f3b9e6d7f65c841de302

Can you test this outside of Docker? Are you using userns in docker - if so can you test with that disabled 

https://docs.docker.com/engine/reference/commandline/daemon/#daemon-user-namespace-options

**Comment by jdanekrh** [comment]
Apologies for conflating issues.

When running Bazel without docker in a plain RHEL72, sandbox is not supported (CONFIG_USER_NS is disabled). The build works fine and I get the usual warning message about sandboxing:

    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.

Running Bazel in plain NixOS is tricky, that's why I am running it in docker, so I haven't tried that.

I am probably not using userns. The command line of docker is

    docker-1.10.3/libexec/docker/docker daemon --group=docker --storage-driver=devicemapper --host=fd://

as you can see, there is no userns in it.
