### ISSUE TITLE
Unable to cross compile go for linux in Mac OS

### ISSUE THREAD

**Issue by kramasamy** [bazelbuild/rules_go#1401]
Getting the following errors - any help is appreciated. I am using bazel 0.11.1 and go rules version 0.10.0

```
bazel build --cpu k8 build/packages/...
ERROR: No default_toolchain found for cpu 'k8'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]
INFO: Elapsed time: 0.154s
FAILED: Build did NOT complete successfully (0 packages loaded)
Karthikz-MacBook-Pro:streamlio karthikz$ bazel version
Build label: 0.11.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 18:46:16 +50148 (1520362464376)
Build timestamp: 1520362464376
Build timestamp as int: 1520362464376
```

**Comment by jayconrod** [comment]
If you're building a pure Go project (no cgo, C/C++ dependencies, or external linking), you can cross-compile with `--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64`.

If part of your build requires a cross C/C++ compiler or linker, in addition to setting `--platforms`, you'll need to [write a CROSSTOOL](https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial) that describes your toolchain (unfortunately this is not an easy process), then set `--cpu` to the name of your toolchain.

**Comment by kramasamy** [comment]
Thanks @jayconrod - that works. Wondering if this can be simplified so that it is easy to remember.

**Comment by jayconrod** [comment]
@kramasamy We've been talking with the Bazel team about improvements to cross-compilation, mostly in the context of multi-configuration builds. I think we'll have more capabilities in the future, but I don't expect the command line interface to change too much.

For now, I added a [FAQ](https://github.com/bazelbuild/rules_go#how-do-i-cross-compile) so it's easier to find out how to do this.

**Comment by prestonvanloon** [comment]
Sorry to necro-post, is there any example of a CROSS tool from linux to compile to Mac with cgo deps?
