### ISSUE TITLE
Generating coverage profile

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1406]
Is it possible to generate a coverage profile? It seems like the most recently submitted method doesn't work and I was wondering if anyone has found a good way of doing this.

**Comment by jeb2239** [comment]
So the data file is always empty even though it is present.

**Comment by jayconrod** [comment]
Could you post a small repro case? Is it always empty after #1407 landed?

Here's a [small example](https://gist.github.com/jayconrod/f89c849ed80421a8e4b0fabb633e15e8) that works for me. Run with `bazel coverage //:go_default_test`.

**Comment by jeb2239** [comment]
https://github.com/jeb2239/turbo-octo-waddle

This is a repro^

Yeah it produces nothing when I run coverage maybe something is wrong with my example.

**Comment by jeb2239** [comment]
The command line I used was `bazel coverage -s //src/...`

**Comment by jayconrod** [comment]
This doesn't make sense to me. I ran the same command and got coverage data. What Bazel version are you using? What platform? I tried with Bazel 0.11.1 and 0.12.0rc2 on Linux and macOS. Is there anything in an rc file that might affect which packages are covered?

```
$ bazel coverage //src/...
...
//src:go_default_test                                                    PASSED in 0.2s
  /usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/5d3ad6b76520af284d310967c9146a20/execroot/__main__/bazel-out/k8-fastbuild/testlogs/src/go_default_test/coverage.dat

Executed 1 out of 1 test: 1 test passes.

$ cat /usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/5d3ad6b76520af284d310967c9146a20/execroot/__main__/bazel-out/k8-fastbuild/testlogs/src/go_default_test/coverage.dat
mode: set
coverage/src/src/main.go:7.12,9.2 1 1
coverage/src/src/main.go:11.13,14.2 1 1
coverage/src/src/main.go:16.13,20.2 2 0
```

**Comment by jeb2239** [comment]
So I get nothing and no bazelrc is being loaded. Did you use the same rules version as me? Is mine too old?

**Comment by jeb2239** [comment]
Also is there away to find the coverage.dat from the symlinked directories?

**Comment by jeb2239** [comment]
Here is my output 

https://gist.github.com/jeb2239/31988256ee4958e5d591bd821d9f0c7b

**Comment by jeb2239** [comment]
I also tried it with your example and it doesn't work either. Here is the test.log from running with your example.
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ [[ -z '' ]]
+ echo --
--
+ echo 'Coverage collection running in legacy mode.'
Coverage collection running in legacy mode.
+ echo 'Legacy mode only supports C++ and even then, it'\''s very brittle.'
Legacy mode only supports C++ and even then, it's very brittle.
+ COVERAGE_LEGACY_MODE=1
+ [[ -z bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files ]]
+ ROOT=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__
+ [[ bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files != /* ]]
+ export COVERAGE_MANIFEST=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files
+ COVERAGE_MANIFEST=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files
+ export COVERAGE_DIR=_coverage/go_default_test/test
+ COVERAGE_DIR=_coverage/go_default_test/test
+ [[ _coverage/go_default_test/test == /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__* ]]
+ COVERAGE_DIR=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test
+ mkdir -p /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test
+ COVERAGE_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat
+ [[ bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat == /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__* ]]
+ COVERAGE_OUTPUT_FILE=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat
+ export JAVA_COVERAGE_FILE=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test/jvcov.dat
+ JAVA_COVERAGE_FILE=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test/jvcov.dat
+ export COVERAGE=1
+ COVERAGE=1
+ export BULK_COVERAGE_RUN=1
+ BULK_COVERAGE_RUN=1
+ [[ ! -n 1 ]]
+ [[ -n 1 ]]
+ export GCOV_PREFIX_STRIP=3
+ GCOV_PREFIX_STRIP=3
+ export GCOV_PREFIX=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test
+ GCOV_PREFIX=/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test
+ cd /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/linux_amd64_stripped/go_default_test.runfiles/__main__
+ /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/linux_amd64_stripped/go_default_test.runfiles/__main__/linux_amd64_stripped/go_default_test
PASS
+ TEST_STATUS=0
+ touch /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat
+ [[ 0 -ne 0 ]]
+ cd /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__
+ [[ -n 1 ]]
+ cat /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files
+ grep '.gcno$'
+ read path
+ cat /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/bin/go_default_test.instrumented_files
+ egrep '.(cc|h)$'
+ read path
+ /usr/bin/lcov -c --no-external -d /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test -o /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat
Capturing coverage data from /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test
Found gcov version: 7.2.0
Scanning /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test for .gcda files ...
geninfo: WARNING: no .gcda files found in /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test - skipping!
Finished .info-file creation
+ sed -i -e 's*/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/_coverage/go_default_test/test*/home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__*g' /home/barriosj/.cache/bazel/_bazel_barriosj/b790a967df273339965ace6e27b0005e/bazel-sandbox/2588218491952539266/execroot/__main__/bazel-out/k8-fastbuild/testlogs/go_default_test/coverage.dat
+ exit 0
```

**Comment by jayconrod** [comment]
Uggghh... Bazel is doing something crazy and I have no idea why.

I compared your test log with mine. I don't have lcov installed on my system. When I installed lcov, running `bazel coverage` gives me an empty file. When I remove /usr/bin/lcov, it gives me data again.

**Comment by jeb2239** [comment]
so is the solution for me to remove lcov?

**Comment by jayconrod** [comment]
I wouldn't call it a solution; it's hardly even a workaround.

Another workaround is to take the binary produced with "bazel coverage" and run it directly (but this is not very satisfying either):

```
$ bazel-bin/src/linux_amd64_stripped/go_default_test -test.coverprofile=cover.dat
hey
hey
PASS
coverage: 50.0% of statements
$ cat cover.dat
mode: set
coverage/src/src/main.go:7.12,9.2 1 1
coverage/src/src/main.go:11.13,14.2 1 1
coverage/src/src/main.go:16.13,20.2 2 0
```

I need to spend some time understanding what Bazel is doing with coverage information, what pieces are missing, and what pieces are buggy.

**Comment by jeb2239** [comment]
now is there a way to have the go path reconstructed in its entirety without having to list every single go target?

**Comment by jayconrod** [comment]
[`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) may be helpful. I merged a rewrite for it earlier this week.

**Comment by jeb2239** [comment]
yeah I know about that but it requires me to maintain a list of go targets so everytime someone adds a new binary I need to update the call of go_path?

**Comment by jayconrod** [comment]
Yes, you'll need a full list of `go_binary` targets. I don't think there's any way around that. But it will catch all the transitive `go_library` dependencies.

It may also leave out packages that don't have known import paths, which covers a number of `go_binary`. Definitely not a perfect tool. Will probably have a solution to that after the next release.

**Comment by jeb2239** [comment]
Also is there away to call repo rules like git_repository and local_repository from a .bzl ?

**Comment by jayconrod** [comment]
You can call them inside a .bzl function by prepending `native.`. This is only necessary for built-in repo rules. For Skylark rules like `go_repository`, you can call them normally.

Of course, functions that declare repository rules can only safely be called from WORKSPACE.

**Comment by jeb2239** [comment]
so I have been testing out the suggested method of generating a coverage profile.
and got this result by running `./bazel-bin/cow/linux_amd64_stripped/go_default_test -test.coverprofile=cover.dat`
```
mode: set
coverage/cow/cow/main.go:7.12,9.2 1 1
coverage/cow/cow/main.go:11.13,14.2 1 1
coverage/cow/cow/main.go:16.13,20.2 2 0
```
which looks wrong to me as there should be one less `cow` in the path

I attempt to make a coverage report by doing

```
export GOPATH=/home/barriosj/go_bazel_project/bazel-bin/linux_amd64_stripped/all_srcs\~/
go tool cover --html=cover.dat -o cover.html
```
and I get an error:
```
cover: can't find "main.go": cannot find package "coverage/cow/cow/" in any of:
	/home/barriosj/go/src/coverage/cow/cow (from $GOROOT)
	/home/barriosj/go_bazel_project/bazel-bin/linux_amd64_stripped/all_srcs~/src/coverage/cow/cow (from $GOPATH)
```
but if I delete the extra `cow` it works well.

**Comment by jeb2239** [comment]
Another strange thing:
```
bazel coverage -s //:go_default_test --test_output=all  --keep_going
./bazel-bin/linux_amd64_stripped/go_default_test -test.coverprofile=cover.dat
```
works fine but if I do this
```
bazel coverage -s //... --test_output=all  --keep_going
./bazel-bin/linux_amd64_stripped/go_default_test -test.coverprofile=cover.dat
```
I get this error
```
testing: cannot use -test.coverprofile because test binary was not built with coverage enabled
```
this seems like pretty random behavior but maybe expected.

**Comment by jayconrod** [comment]
> Is there a rule regarding how bazel deletes things

I don't think this is really documented. In this case, Bazel tells the test binary to write to `COVERAGE_OUTPUT_FILE`, and it deletes that file after running the test. If the test is run outside Bazel, it can write the coverage file somewhere else. Within the generated test main, we copy that environment variable to the `-test.coverprofile` flag.

> is there a standard way to instrument go code at a high level?

We use `go tool cover` to instrument code. It transforms source files, and we pass the transformed source files to the compiler (which has no support for coverage on its own). This writes data files in a Go-specific format.

Bazel tests us which targets to instrument through a Skylark API. That can be controlled with `--instrumentation_filter` and `--instrument_test_targets`.

Bazel is supposed to collect and present coverage instrumentation from all test targets it runs, regardless of language. Within Google, Blaze requires coverage data to be in lcov format. That part is not working yet (see bazelbuild/bazel#1118). When it does work, we'll convert the Go coverage data into whatever format Bazel wants.

**Comment by jeb2239** [comment]
is there away to have go tool cover generate html pages ?
```
 -> % go tool cover --html=cover.dat -o cover.html
```
This is something I am trying to figure out for my team so we can keep using bazel so any suggestions would help.
the `go tool cover`  expects everything to be in go path format 

Also how is it possible to even generate a coverage report if it is deleted immediately by the build tool.

**Comment by jeb2239** [comment]
why is the top level folder name repeated?  this makes it impossible for the output file to work with go tool cover. I am just manually deleting the extra cow so it works but think this is a bug.

```
mode: set
coverage/cow/cow/main.go:7.12,9.2 1 1
coverage/cow/cow/main.go:11.13,14.2 1 1
coverage/cow/cow/main.go:16.13,20.2 2 0
```

**Comment by jeb2239** [comment]
Just wondering if I am the only one seeing this issue.

**Comment by jayconrod** [comment]
Sorry for the slow response. Was out of town for the last week.

> is there away to have go tool cover generate html pages ?

As you said, `go tool cover` expects a `GOPATH`-like layout. We can't support this directly, but `go_path` may be useful for hacking around this. Again, it has several limitations.

The long term plan is to have the workspace (whether it's Bazel, go build, vgo, or something else) abstracted away from tools like cover.

> why is the top level folder name repeated?

That is a bug. Sorry about that. #1443 should fix it.
