### ISSUE TITLE
HEAD breaking on missing proto lib with no changes

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1422]
I've when to upgrade rules_go to get the new gopath stuff, etc., but am getting a build break with:

```
$  bazel build //proto/...
INFO: Analysed 12 targets (41 packages loaded).
INFO: Found 12 targets...
ERROR: /Users/jmhodges/founding/src/founding/proto/sessions/sessproto/BUILD.bazel:11:1: GoCompile proto/sessions/sessproto/darwin_amd64_stripped/sessproto_go_proto~/founding/proto/sessions/sessproto.a failed (Exit 1)
2018/03/30 18:07:38 missing strict dependencies:
	/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/bazel-sandbox/7460772703440129978/execroot/founding/bazel-out/darwin-fastbuild/bin/proto/sessions/sessproto/darwin_amd64_stripped/sessproto_go_proto~/founding/proto/sessions/sessproto/sess.pb.go: import of proto/time, which is not a direct dependency
```

The sessproto proto file I have has

```
import "proto/time/time.proto";
```

in it and the gazelle generated sessproto BUILD looks like:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "sessproto_proto",
    srcs = ["sess.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//proto/time:timeproto_proto"
    ],
)

go_proto_library(
    name = "sessproto_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "founding/proto/sessions/sessproto",
    proto = ":sessproto_proto",
    visibility = ["//visibility:public"],
    deps = ["//proto/time:go_default_library"],
)

go_library(
    name = "go_default_library",
    embed = [":sessproto_go_proto"],
    importpath = "founding/proto/sessions/sessproto",
    visibility = ["//visibility:public"],
)
```

while the timeproto bazel file (also generated by gazelle but with one visibility setting edited) looks like:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "timeproto_proto",
    srcs = ["time.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "timeproto_go_proto",
    importpath = "founding/proto/time",
    proto = ":timeproto_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    embed = [":timeproto_go_proto"],
    importpath = "founding/proto/time",
    visibility = [
        # some things I changed
        "//go/pkg/sessions:__subpackages__",
        "//go/svc/fe:__subpackages__",
        "//go/svc/sessions:__subpackages__",
        "//proto/sessions:__subpackages__",
    ],
)
```

I haven't attempted to generate these BUILD files but they were made with gazelle 0.9 and then had gazelle 0.10.1 run against them, as well.

I don't understand what went wrong here.

**Comment by jmhodges** [comment]
I maybe should also note that in //proto/timeproto/time.proto the package is written as `package timeproto;`

**Comment by jmhodges** [comment]
(btw deleting those BUILD.bazels and letting them be recreated by gazelle doesn't change their contents, other than the visibility stuff on time.proto's go_default_library)

**Comment by jayconrod** [comment]
@jmhodges The error comes from a mismatch between the import in the generated .pb.go files (`proto/time`) and the `importpath` attribute of the dependency (`founding/proto/time`).

You said nothing changed in the build files after upgrading to a newer Gazelle, so I guess we can rule out `importpath` changing. That means the import in the generated .pb.go files must have changed.

What version of rules_go were you using earlier? There have been a few changes to the proto rules in the last month, but I can't think of anything that would cause this. If you have a small test case that reproduces this, that would be very helpful.

**Comment by jmhodges** [comment]
Here's a repro: http://github.com/jmhodges/bazel_bugs/tree/rules_go_1422

I was at 3e6e9bbf8f9ed35f5956fba80dde9283e121a66c and it broke when I moved it to c003e0ccbe743017c87025917d6b8c42b1cc1442

**Comment by jayconrod** [comment]
Thanks for posting a repro. That helped a lot. The issue was caused by #1388.

We use an aspect `go_proto_aspect` to build a map of proto sources to Go import paths in the transitive dependency graph. In #1388, I stopped the aspect from propagating on `embed` edges; it was causing problems earlier. However, we need those edges to generate .pb.go files with correct imports.

#1422 should fix this. Sorry about the break.

**Comment by jmhodges** [comment]
Oh, great! Thanks for the fix.

(Also, for those playing along at home, Jay meant to link to the https://github.com/bazelbuild/rules_go/pull/1431 PR)
