### ISSUE TITLE
Problems with .dylib files on macOS

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_go#1435]
It looks like rules_go doesn't account for .dylib files:

https://github.com/bazelbuild/rules_go/blob/7a6f32812eaf167c03ba50fcf75a2750efda1fb3/go/private/actions/link.bzl#L85

Additionally, I believe macOS will need further adjustment when Bazel 0.12 is released, due to this change: https://github.com/bazelbuild/bazel/commit/f98a7a2fedb3e714cef1038dcb85f83731150246

**Comment by jayconrod** [comment]
@sayrer Could you tell me a bit more about the situation where you're having a problem with this? What errors are you seeing? When does it happen? Do you have a reproducible test case?

Bazel `cc_library` typically generates both .a and .so files (not .dylib, even on macOS). I'm not claiming the code that handles this is correct or complete, but it's been there for a while and seems to be working. If there's a case we're not handling though, please let me know.

**Comment by sayrer** [comment]
I have a build of libphonenumber (CMake invoked via genrule) that relies on Bazel-provided libraries such as protobuf (which are .so files on macOS, as you note). Then, I use cgo to make use of libphonenumber. It works fine on Linux, but I get "image not found" errors at runtime on mac, where libphonenumber.dylib can't locate libprotobuf.so.

I think this link line in link.bzl should cover anything supported by cc_import: https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import.shared_library

**Comment by jayconrod** [comment]
Ok, I think I get the issue. To recap, if you have a .dylib built with something other than `cc_library`, provided as a `cc_import` rule in `cdeps`, it isn't found at the loader at run-time because:

* In link.bzl, we don't add libraries to the rpath unless they end with .so. We should extend this to include .dylib and .dll.
* On macOS, we should set the rpath with `@loader_path` instead of `$ORIGIN`.

Is that correct?

**Comment by sayrer** [comment]
I think that is correct as of Bazel 0.12

**Comment by jayconrod** [comment]
Ok, I have a draft PR fixing this at https://github.com/jayconrod/rules_go/commit/4a2b829db2d2525c7e3b005f584e8f5b3db72dbc.

Could you take a look at the build file for the test and check if it matches your situation? https://github.com/jayconrod/rules_go/blob/4a2b829db2d2525c7e3b005f584e8f5b3db72dbc/tests/core/cgo/BUILD.bazel

At least at the moment, you'll need to make sure your .dylib is build with `-install_name @rpath/libmylibrary.dylib`, which allows it to be discovered using rpaths at load time. Bazel has a wrapper script that fixes this up on macOS when linking `cc_binary` rules, but it's not clear we can do that in Go.
