### ISSUE TITLE
fail to build because of _empty.go

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#1438]
it fails when i run the building with rules_go.Error message is that

```
/root/.cache/bazel/_bazel_root/9fb8753853fa4f06dcf18e6226b8e4f5/execroot/__main__/_empty.go:1:1: syntax error: package statement must be first
```
my environment version is that
rules_go: 0.10.3
bazel:  0.11.0
golang: 1.10.1

i think there is relationship with [#1428](https://github.com/bazelbuild/rules_go/pull/1428)

so i downgrade the rules_go to 0.10.2. It runs successfully

**Comment by jayconrod** [comment]
Sorry for the slow response. Was out of the office for the last week.

When exactly does this happen? Do you have a small test case I can look at?

After #1428, when all of the .go files in a package have been filtered out with build constraints (e.g., `// +build ignore`), the compile builder will write a file named `_empty.go` that just contains a package declaration, then it will compile that. This creates a valid .a file that can be used in the rest of the build. The contents of that file are fixed, and there should never be a syntax error in there.
