### ISSUE TITLE
tests not rebuilding on changed external

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1442]
Hey, I just noticed that my tests weren't rebuilding after I'd bumped the version of golang.org/x/net (specifically for the golang.org/x/net/publicsuffix lib). This is with the HEAD of rules_go.

The dep was actually in the go_library  of a go_binary that I was running a go_test on. Latest gazelle release doesn't change any of the deps or anything. The dep was on `@org_golang_x_net//publicsuffix:go_default_library` and the change from commit 3da985ce5951d99de868be4385f21ea6c2b22f24 to 61147c48b25b599e5b561d2e9c4f3e1ef489ca41 did have changes to the publicsuffix dep.

But the tests were still saying they were "cached". Not sure why.

**Comment by jayconrod** [comment]
Closing old issues. Please reopen if you're still seeing this.
