### ISSUE TITLE
Using Something like go-oracle that relies on C driver

### ISSUE THREAD

**Issue by marct83** [bazelbuild/rules_go#1464]
Hi. We are getting a little hung up on using Oracle in our go apps with bazel/gazelle. We use go-oracle in our app and it uses ODPI-C driver that is written in C and needs to be compiled with the app. 

Any guidance on how we would setup our Build files to make this work would be great.

**Comment by jayconrod** [comment]
Can you build the C library with the [`cc_library`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library) rule? If so, you can add it as a dependency of a Go library and access it with cgo.

```
go_library(
    name = "go_default_library",
    srcs = ...,
    cgo = True,
    cdeps = [":go_oracle"],
)

cc_library(
    name = "go_oracle",
    srcs = ...,
    hdrs = ...,
)
```

If you have a prebuilt static or dynamic library, or if you build the library through an external build system (e.g., via `genrule`), you can import it with [`cc_import`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import), then link that through `cdeps` (though there are a lot of complications around dynamic libraries and rpaths, so I'd recommend static if it's an option).

**Comment by marct83** [comment]
That Helps.

Next issue with this is getting the Oracle Client libraries into the bazel build environment. These libraries come directly from Oracle and are stored locally. Here's a bit of info https://oracle.github.io/odpi/doc/installation.html

**Comment by jayconrod** [comment]
The Makefile for the client library looks relatively simple, so you may be able to just build it with `cc_library`. If you run into issues with building C/C++, the best channels for support are StackOverflow (we keep an eye on the `[bazel]` tag) or the [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) mailing list.
