### ISSUE TITLE
Files in external tests have wrong names in coverage data

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1466]
From [this comment](https://github.com/bazelbuild/rules_go/pull/1462#issuecomment-384782057)

> I'm also seeing some filenames that don't exist, for example a client/service_test.go is getting mapped to client/service_test/service.go. I think this is an effect of #1256.

**Comment by jmillikin-stripe** [comment]
To clarify, that test was an internal test (not an external dep).
