### ISSUE TITLE
How to use a binary only package?

### ISSUE THREAD

**Issue by kalbasit** [bazelbuild/rules_go#1469]
Our project depends on WURFL and they provided us with a binary-only-package split into a `.go` file, a `.a` and a C library to install on the host. The Go file goes something like this:

```go
//go:binary-only-package

package wurfl

// Cache Provider possible values
const (
	WurflCacheProviderNone      = C.WURFL_CACHE_PROVIDER_NONE
)
```

Where should these files go? and how to use them with Bazel?

List of relevant files provided:

```
/usr/include/wurfl/wurfl.hpp
/usr/include/wurfl/wurfl.h
/usr/lib/libwurfl.so.0.1.5
/usr/lib/libwurfl.so
/usr/lib/libwurfl.so.0
$GOPATH/pkg/linux_amd64/scientiamobile/wurfl.a
$GOPATH/scientiamobile/wurfl/wurfl.go
```

**Comment by kalbasit** [comment]
@jayconrod has there been any work on this? Any plans to work on it?

**Comment by jayconrod** [comment]
Sorry, no update on this at the moment.

**Comment by jayconrod** [comment]
(Re-triaging old issues).

Closing as obsolete. Since Go 1.13, the Go toolchain no longer supports binary-only packages.
