### ISSUE TITLE
buildifier repo error on `query deps(//external:*)`

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#148]
When running `bazel query deps(//external:*)` on a repo with 

    git_repository(
        name = "io_bazel_rules_go",
        remote = "https://github.com/bazelbuild/rules_go.git",
        tag = "0.2.0",
    )

    load("@io_bazel_rules_go//go:def.bzl", "go_repositories")

    go_repositories()

in the WORKPLACE, this error is seen: 

/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/def.bzl:1245:3: every rule of type _go_repository_tools implicitly depends upon the target '@io_bazel_buildifier//:BUILD', but this target could not be found because of: no such package '@io_bazel_buildifier//': error loading package 'external': The repository named 'io_bazel_buildifier' could not be resolved.

I *think* I just have to explicitly add that repo to the WORKSPACE. If so, it might be nice to add that to the README.

**Comment by jmhodges** [comment]
Hrm, except I can't find that repo anywhere on the net. It might be github.com/bazelbuild/buildifier's but that has a dep on @io_bazel_rules_go, so that probably isn't right.

Anyway, lmk. Would be nice to figure this one out.

**Comment by yugui** [comment]
It is caused by unused reference to undefined external repositories I introduced by mistake in trial and error.

**Comment by jmhodges** [comment]
Oh, that's straightforward! Thanks!

**Comment by jmhodges** [comment]
Hm, I've updated to HEAD, but I'm stilling getting similar errors.

**Comment by jmhodges** [comment]
ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/tools/gazelle/gazelle/BUILD:3:1: no such package '@io_bazel_buildifier//differ': error loading package 'external': The repository named 'io_bazel_buildifier' could not be resolved and referenced by '@io_bazel_rules_go//go/tools/gazelle/gazelle:go_default_library'.

**Comment by jmhodges** [comment]
Oh, that's from `bazel build '@io_bazel_rules_go//go/tools/gazelle/gazelle`

**Comment by jmhodges** [comment]
Weirdly, it works in the rules_repo. bazel seems to download the repo at the new commit, but maybe it has the old target graph loaded when it goes to fix itself and errors? Doing a `bazel clean` doesn't fix the problem, though.

**Comment by jmhodges** [comment]
Ahh, I have to call go_internal_deps in order to make those work from my repo. Okay!

**Comment by jmhodges** [comment]
Oh, right, it's private. I guess it's fine for now to build outside. I'm only planning on using gazelle explicitly as a migration tool for this repo, and don't have reason to call it from inside the repo's CI or whatever right now.
