### ISSUE TITLE
Add support for grpc_gateway as a native grpc compiler

### ISSUE THREAD

**Issue by Mistobaan** [bazelbuild/rules_go#1494]
The final goal is to be able to use gazelle to generate rules for proto buffers that use:

- gogo proto (faster serialization than go proto)
- grpc_gateway to generate HTTP endpoints using `google/api/annotations` extension
- gazelle for bazel build autogeneration 

I have a working prototype on my machine but requires edits in different repositories 
- grpc_gateway grpc-ecosystem/grpc-gateway#647
- bazel-gazelle bazelbuild/bazel-gazelle#197
- rules_go #1495 

and probably need the collaboration of few of these mantainers to review/merge everything 

@jayconrod 
@ianthehat 
@achew22

**Comment by jayconrod** [comment]
Closing per discussion in #1495
