### ISSUE TITLE
Desire -test.short in go_test

### ISSUE THREAD

**Issue by bimargulies-google** [bazelbuild/rules_go#1500]
I wish I could specify -test.short as part of a go_test rule. Is that a reasonable desire?

**Comment by bimargulies-google** [comment]
I'd really like a command-line override. I guess I could put the test in twice, once with the args, once with not, and set up the one without test.short to be manual-only. I wonder how confused gazelle would get?

The problem here is that, essentially, I want to treat the 'long' version of the tests as something run by particular build jobs but not by individuals doing a 'bazel test "...".

**Comment by bimargulies-google** [comment]
Oh, and I can't pass in -test.short with a bazel cli, because then the python tests in the same project fail.

**Comment by jayconrod** [comment]
> I'd really like a command-line override. I guess I could put the test in twice, once with the args, once with not, and set up the one without test.short to be manual-only. I wonder how confused gazelle would get?

This might be your best option. Gazelle will update the `go_test` named `go_default_test` and will ignore the other one.
