### ISSUE TITLE
Generate gopkg toml using resolved bazel go dependencies 

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1502]
Is there away to get all the resolved dependencies resolved by bazel and iterate through them to make a Gopkg.toml?

**Comment by jayconrod** [comment]
There's no way to do this at present. I'm not sure there's a really good way to do this either. WORKSPACE is more analogous to Gopkg.lock than Gopkg.toml.

The closest thing I can recommend is use `github.com/bazelbuild/buildtools/build` to parse WORKSPACE, then match top-level `go_repository` rules. It won't catch repositories declared in macros though, and some work may be needed to identify repositories declared with something other than `go_repository`.
