### ISSUE TITLE
Build/Test is failing on Mac with github.com/coreos/etcd dependency

### ISSUE THREAD

**Issue by kalbasit** [bazelbuild/rules_go#1504]
Hello,

My project has a dependency on `github.com/coreos/etcd` and it works fine on Linux, but it's not working on Mac. I've created a reproducible test at https://github.com/kalbasit/bazel-reproducible/tree/master/coreos_etcd_client

I'm suspecting that it's related to #456, but I've added `extra_args = ["-build_file_name", "BUILD.bazel"],` to the `gazelle` rule but it did not help.

Linux:

```shell
$ bazel test //...
WARNING: ignoring _JAVA_OPTIONS in environment.
INFO: Analysed 2 targets (26 packages loaded).
INFO: Found 1 target and 1 test target...
INFO: Elapsed time: 1.720s, Critical Path: 0.05s
INFO: 1 process, processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
//helper:go_default_test                                                 PASSED in 0.0s

Executed 1 out of 1 test: 1 test passes.
```

Mac:

```shell
$ bazel test //...
ERROR: /Users/kalbasit/code/src/github.com/kalbasit/bazel-reproducible/coreos_etcd_client/helper/BUILD.bazel:3:1: no such package '@com_github_coreos_etcd//client': BUILD file not found on package path and referenced by '//helper:go_default_library'
ERROR: Analysis of target '//helper:go_default_library' failed; build aborted: no such package '@com_github_coreos_etcd//client': BUILD file not found on package path
INFO: Elapsed time: 0.246s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by kalbasit** [comment]
I found another ticket reporting a similar issue #234, @jayconrod you marked #234 as resolved but I'm not sure that it is.

**Comment by jayconrod** [comment]
Gazelle only sets a few attributes in `go_repository`. There's no way to set `build_file_generation` using Gazelle on the command-line, but it will leave manual edits in place when it updates rules.

Note that `gazelle update-repos -from_file=Gopkg.lock` will update existing rules if they're present, rather than adding new, redundant rules. So you may not need to remove existing `go_repository` rules before running `gazelle update-repos`, unless there's another reason.

**Comment by kalbasit** [comment]
@jayconrod here's the relevant extract of my script:

```bash
#!/bin/bash
set -e

function go_vendor() {
        if [[ "${1}" = "-update" ]]; then
                dep ensure -update
        else
                dep ensure
        fi

        # this package contains a broken symlink and it seems to be killing Bazel
        rm -rf vendor/github.com/coreos/etcd/cmd

        # clear the WORKSPACE of all generated go_repository in preparation of
        # running gazelle update-repos
        sed '/^# gazelle:autogenerated$/q' WORKSPACE > /tmp/WORKSPACE
        mv /tmp/WORKSPACE WORKSPACE

        # update the WORKSPACE
        bazel run --noshow_progress //:gazelle -- update-repos -from_file=Gopkg.lock
}

go_vendor
```

relevant WORKSPACE section:

```python
####
# NOTE: do not remove or change the line below, `platform vendor` uses this to
# clean the workspace before updating the externals.
#
# gazelle:autogenerated

go_repository(
    name = "com_github_coreos_etcd",
    commit = "70c8726202dd91e482fb4029fd14af1d4ed1d5af",
    importpath = "github.com/coreos/etcd",
    build_file_generation = "on",
)
```

and of course, when I run it, the flag gets removed

```diff
$ git diff WORKSPACE
diff --git a/src/WORKSPACE b/src/WORKSPACE
index 24626637..5cc109ff 100644
--- a/src/WORKSPACE
+++ b/src/WORKSPACE
@@ -166,7 +166,6 @@ go_repository(
     name = "com_github_coreos_etcd",
     commit = "70c8726202dd91e482fb4029fd14af1d4ed1d5af",
     importpath = "github.com/coreos/etcd",
-    build_file_generation = "on",
 )

 go_repository(
```

The goal of the above script it to keep the `WORKSPACE` in sync with `Gopkg.lock`, so whenever we remove a dependency from the lock file, it will also be removed from the `WORKSPACE`; but this of course breaks when you account for manual changes. Is there a better way to sync them?

**Comment by jayconrod** [comment]
It seems like the main problem is removing repository rules that are no longer needed. I don't have a better way to do that right now, but I've filed bazelbuild/bazel-gazelle#213 for that. When that's implemented, you could run `gazelle update-repos -prune` or something similar, and it would remove repository rules that aren't needed anymore.
