### ISSUE TITLE
cgo support not quite working

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_go#1505]
The following does not work with _rules_go 0.12_ and _bazel 0.13_:

```
go_repository(
    name = "foo",
    importpath = "github.com/keroserene/go-webrtc",
    commit = "a1272c08ab1d5ca154c6794ddc5f73d2e576fe1b",
)
```

First off - I am quite impressed that it works as far as it does.
It seems to not find `_cgo_export.h`.

**Comment by abergmeier** [comment]
Filed rather with Gazelle directly https://github.com/bazelbuild/bazel-gazelle/issues/203

**Comment by jayconrod** [comment]
Closing in favor of bazelbuild/bazel-gazelle#203 being the canonical issue.
