### ISSUE TITLE
Using a single @go_sdk for prebuilt binaries prevents remote builds if platform != host_platform

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/rules_go#1507]
When Bazel remote workers are doing a build, they receive the content of `repository_rule` directories directly from the Bazel client. The "platforms" and "toolchains" features are used to invoke binaries usable by the host system, so in theory the correct externals could be selected when the remote build platform is different from the local client.

rules_go's use of `ctx.os.name` and `uname` in `_go_download_sdk_impl` to select the downloaded toolchain breaks the toolchain selection logic, because the repo rules are run locally but the content of them is run remotely. And since the `@go_sdk` repo name doesn't have any sort of platform component, the toolchain selection always ends up trying to run binaries that match the client (not host) platform.

I think the correct way to implement this is to define many `go_sdk` externals, one per supported platform name, and have each toolchain entry be configured to use the correct go_sdk.

**Comment by hchauvin** [comment]
Hi, switching the logic to the toolchains is something I need as well.  @jmillikin-stripe have you worked on this?

**Comment by jmillikin-stripe** [comment]
I've made a quick-n-dirty patch to rules_go to verify basic builds work when `@go_sdk` is renamed to have platform-specific names. I also wrote up some notes on toolchains at <http://john-millikin.com/bazel-toolchains>. Other than that, I've done no work on this -- and I won't have time to do so in the immediate future.

**Comment by jayconrod** [comment]
I've been thinking about how to handle this, and I have a rough plan. Basically, I'd like to turn `go_download_sdk` into a macro which:

* Declares a repository rule that downloads the SDK and declares `go_toolchain` and `toolchain` rules for all host and target platforms supported by that SDK.
* Calls `register_toolchains` for all of those toolchains.

Everything in rules_go that references files from `@go_sdk` should get those files from the current toolchain instead. This means the `@go_sdk` name will no longer be special. Any number of SDKs could be declared, and Bazel will pick the right toolchain.

I need to confirm some details with Bazel and remote execution folks. It may be a little tricky to make this work without changing the API or unnecessarily downloading SDK archives, but I think it can be done.

**Comment by jayconrod** [comment]
@excavador I think this might work now, but I haven't verified it. As described above, the SDK rules are now macros that declare a repository, then register the toolchains in that repository. As long as toolchains are registered for the execution platform, you should be good. Note that you'll need to set `goos` and `goarch` explicitly on repository rules if they're different from your host platform.

**Comment by excavador** [comment]
@jayconrod checked last commit (0.17.0), does not work

Or I am not able to build on host, or I am not able to build on remote.

> Note that you'll need to set goos and goarch explicitly on repository rules if they're different from your host platform.

Yes, I did it for go_sdk_download.

The problem is so simple: @gosdk is global and can be only host or remote golang version

We need some why to use at the same time host and target golang version - like @gosdk_local and @gosdk_remote

**Comment by jayconrod** [comment]
Most of the references to `@go_sdk` have been cut, but I guess there are still a few that are causing problems.

I'm trying to pull more things into the toolchain for 0.18.0 so that dependencies are selected dynamically. That should help with this.

**Comment by jmillikin-stripe** [comment]
Thanks!

**Comment by excavador** [comment]
Thank you!

**Comment by steeve** [comment]
@excavador @jmillikin-stripe hey guys, did you manage to make it work ? darwin to linux remote?

**Comment by jmillikin-stripe** [comment]
I got cross-platform builds working, but it needed some heavy hacking in a local rules_go branch to convince the toolchain it doesn't really need cgo or a C compiler.

**Comment by jayconrod** [comment]
@jmillikin-stripe Were you working on a 0.18.x release or `master`? This should be a lot easier with 0.19.0.

**Comment by jmillikin-stripe** [comment]
I was using v0.18.6, will try again when the v0.19 series is cut.
