### ISSUE TITLE
Support building binary only packages

### ISSUE THREAD

**Issue by zaycev** [bazelbuild/rules_go#1523]
Is there a way to produce .a files compatible with Go binary-only-package mechanism using existing go rules?

I tried to write a simple rule which takes output paths from `GoArchive.libs` and `GoArchive.cgo_deps` and packages them into a zip archive with a Go binary package structure. I found that `.a` files produced by `go_library` have a format different from what `go build -i -o mypackage.a` will produce. For example, I'm seeing the following problem when I'm trying to import `.a` produced by `go_library`:

```
# command-line-arguments
cannot find package fmt.a (using -importcfg)
cannot find package sync.a (using -importcfg)
cannot find package runtime/cgo.a (using -importcfg)
cannot find package syscall.a (using -importcfg)
/Users/zaytsev/.gvm/gos/go1.10.2/pkg/tool/darwin_amd64/link: cannot open file : open : no such file or directory
```

`main.go` (outside of bazel workspace):
```
package main

import (
	"fmt"
	"mypackage"
)

func main() {
	fmt.Println(mypackage.Example)
}
```

**Comment by robfig** [comment]
cmd/go has dropped support for binary-only packages. Closing
https://github.com/golang/go/issues/28152
