### ISSUE TITLE
benchmarking go code

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1532]
Is there a way to benchmark go tests similar to  go test -bench=.

I tried doing some thing like
./bazel-bin/mylib/linux_amd64_stripped/go_default_test -test.bench=TestWkt

but nothing happens , I get no timings or anything.

**Comment by jayconrod** [comment]
Hmm, this works for me:

```
$ bazel-bin/linux_amd64_stripped/go_default_test -test.bench=.
goos: linux
goarch: amd64
BenchmarkFib10-12    	 3000000	       382 ns/op
PASS
```

Also these:

```
$ bazel run :go_default_test -- -test.bench=.
$ bazel test :go_default_test --test_arg=-test.bench=.
```
