### ISSUE TITLE
Best practice for updating a rules_go dependency that uses overlay

### ISSUE THREAD

**Issue by jwahlin** [bazelbuild/rules_go#1533]
I need to update the commit ID for com_github_golang_protobuf. They fixed a bug in the last couple of weeks that affects my team's product. I would like to know what the best practice is for loading a dependency in my WORKSPACE if it has an overlay set when loaded by go_rules_dependencies().

At the moment, I have added this to my WORKSPACE:
```
load("@io_bazel_rules_go//third_party:manifest.bzl", "manifest")
load("@io_bazel_rules_go//go/private:tools/overlay_repository.bzl", "git_repository")

git_repository(
    name = "com_github_golang_protobuf",
    commit = "3a3da3a4e26776cc22a79ef46d5d58477532dede",  # master, as of 2018-05-22
    overlay = manifest["com_github_golang_protobuf"],
    remote = "https://github.com/golang/protobuf",
)
```

Is this good practice or is there a different, recommended approach?

**Comment by jayconrod** [comment]
That will work as long as there were no changes in `@com_github_golang_protobuf` that requires changes in build files. It may be safer to use [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) instead for this.

```
go_repository(
    name = "com_github_golang_protobuf",
    importpath = "github.com/golang/protobuf",
    commit = "3a3da3a4e26776cc22a79ef46d5d58477532dede",  # master, as of 2018-05-22
    build_file_proto_mode = "disable",
)
```

FYI, it may be a few weeks before the proto repositories are updated again in rules_go. I need to make some fixes around proto dependency management, and Gazelle will need some changes to support that. This repo should be fine to override, but I have concerns about gRPC.

**Comment by jwahlin** [comment]
Thanks for your feedback. I initially tried go_repository, but that gave me cycle dependency errors:
```
ERROR: /private/var/tmp/_bazel_jamie/87267ef3ad0e627014f10dd44d8fdb61/external/com_github_golang_protobuf/protoc-gen-go/BUILD.bazel:18:1: in go_binary rule @com_github_
golang_protobuf//protoc-gen-go:protoc-gen-go: cycle in dependency graph:
    //internal/auth:go_default_library
    @neo//protos/go/matrix/org:go_default_library
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
    @io_bazel_rules_go//proto:go_proto_bootstrap
.-> @com_github_golang_protobuf//protoc-gen-go:protoc-gen-go (host)
|   @com_github_golang_protobuf//protoc-gen-go:go_default_library (host)
|   @com_github_golang_protobuf//protoc-gen-go/generator:go_default_library (host)
|   @io_bazel_rules_go//proto/wkt:compiler_plugin_go_proto (host)
|   @io_bazel_rules_go//proto/wkt:descriptor_go_proto (host)
|   @io_bazel_rules_go//proto:go_proto_bootstrap (host)
`-- @com_github_golang_protobuf//protoc-gen-go:protoc-gen-go (host)
This cycle occurred because of a configuration option
```
This cycle error made me wonder if the overlay is required for golang/protobuf. If go_repository should work correctly for golang/protobuf, I can create a ticket in the gazelle repo.

**Comment by jayconrod** [comment]
I forgot that repository had some manual changes a while ago to make it work (#1498). So `go_repository` won't work there, at least for now.

Ok, so if you're able to use the overlay build files in rules_go, that's probably the easiest thing. This is some temporary ugliness that I hope to resolve soon. If that doesn't work, you'll need to create a new overlay by checking out that repo, running Gazelle, and applying the patch from #1498.

**Comment by jwahlin** [comment]
Thanks for the insider information. That's very helpful.

You mentioned this is temporary ugliness. Do you know how will this change going forward?

**Comment by jayconrod** [comment]
I'm still putting together a plan, but here's a sketch:

* We'll have a standard set of `proto_library` and `go_proto_library` rules for Well Known Types, gRPC, and Google APIs. Some of these are already defined in `@com_google_protobuf`, `@org_golang_google_genproto`, and `@io_bazel_rules_go//proto/wkt`. The rules that are already defined won't move.
* For Go programs that should not or cannot run protoc through Bazel (for example, because their protos have import prefixes that Bazel doesn't understand), we'll provide `go_library` rules, built from .pb.go files for these dependencies. In general, these `go_libraries` should not be mixed with the `go_proto_libraries` above.
* Gazelle will know how to resolve imports of these known types to the standard dependencies. It will ignore vendored or local versions of these libraries.
* For Go projects that should not or cannot run protoc through Bazel, there will be a way to disable this special dependency resolution in Gazelle and use the regular .pb.go libraries.

I hope this will land in a rules_go major release in a month or so. If everything goes smoothly. The specific timeframe and plan may shift.

**Comment by Globegitter** [comment]
@jayconrod I also just tried to update `com_github_golang_protobuf` to `c823c79ea1570fb5ff454033735a8e68575d1d0f` and getting the same issue:

```
(17:52:50) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/com_github_golang_protobuf/protoc-gen-go/BUILD.bazel:18:1: in go_binary rule @com_github_golang_protobuf//protoc-gen-go:protoc-gen-go: cycle in dependency graph:
    //search-pipeline:search-pipeline
    //search-pipeline/server:search-pipeline
    //search-pipeline/server:search-pipeline.binary
    //search-pipeline/server:go_default_library
    @org_golang_google_grpc//:go_default_library
    @org_golang_google_grpc//status:go_default_library
    @go_googleapis//google/rpc:status_go_proto
    @io_bazel_rules_go//proto:go_proto
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
    @io_bazel_rules_go//proto:go_proto_bootstrap
.-> @com_github_golang_protobuf//protoc-gen-go:protoc-gen-go (host)
|   @com_github_golang_protobuf//protoc-gen-go:go_default_library (host)
|   @com_github_golang_protobuf//protoc-gen-go/grpc:go_default_library (host)
|   @io_bazel_rules_go//proto/wkt:descriptor_go_proto (host)
|   @io_bazel_rules_go//proto:go_proto_bootstrap (host)
`-- @com_github_golang_protobuf//protoc-gen-go:protoc-gen-go (host)
This cycle occurred because of a configuration option
```

So the "temporary ugliness" still exists? And manual steps are needed to fix?

**Comment by Globegitter** [comment]
Actually what seemed to work just copying the patches like so:

```
git_repository(
    name = "com_github_golang_protobuf",
    remote = "https://github.com/golang/protobuf",
    commit = "c823c79ea1570fb5ff454033735a8e68575d1d0f",
    patches = [
        "@io_bazel_rules_go//third_party:com_github_golang_protobuf-gazelle.patch",
        "@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch",
    ],
    patch_args = ["-p1"],
    # gazelle args: -go_prefix github.com/golang/protobuf -proto disable_global
)
```
