### ISSUE TITLE
Build error involving wrong importmap passed to vendored external tests

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1538]
Originally reported by @ixdy. To reproduce, checkout https://github.com/ixdy/kubernetes at 8704a68a3712d35e778043d6e4109913449677e9 and run this command:

```
$ bazel build staging/src/k8s.io/apimachinery/pkg/runtime:go_default_test
...
/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/4a2bdc82526db3ea358ea56d8f9e540e/sandbox/linux-sandbox/107/execroot/__main__/staging/src/k8s.io/apimachinery/pkg/runtime/conversion_test.go:34:94: cannot use "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/testing".InternalComplex literal (type *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/testing".InternalComplex) as type "k8s.io/apimachinery/pkg/runtime".Object in argument to scheme.AddKnownTypeWithName:
	*"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/testing".InternalComplex does not implement "k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
...
```

**Comment by ixdy** [comment]
In particular, this package (`staging/s8s.io/apimachinery/pkg/runtime`) has a `go_library` which overrides `importmap`:

```python
go_library(
    name = "go_default_library",
    importmap = "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime",
    importpath = "k8s.io/apimachinery/pkg/runtime",
...
)
```
and several go tests which depend on the library.

It looks like when building the external go tests, the go rules are passing `-importmap 'k8s.io/apimachinery/pkg/runtime=k8s.io/apimachinery/pkg/runtime'`, rather than `-importmap 'k8s.io/apimachinery/pkg/runtime=k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime'`.

**Comment by jayconrod** [comment]
Thanks again for reporting this. The issue was that `importpath` was being inherited from the `go_library` by the `go_test`, but `importmap` was not. `importmap` will now be inherited. This interacted with internal / external tests in a weird way: external tests are compiled against the internal test archive (which is what gets linked into the binary) while everything else is compiled against the library under test.

**Comment by jayconrod** [comment]
When this is merged, I'll cherry-pick this along with a few other fixes back to older branches. I'll tag point releases for those.
