### ISSUE TITLE
Spaces are not supported in test fixtures

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#1540]
I'm getting the following error when I have a file with a space in the name in the `testdata` directory:
```console
ERROR: /gopath/src/bla/bla/bla/bla/bla/bla/BUILD.bazel:25:1: Creating runfiles tree bazel-out/darwin-fastbuild/bin/bla/bla/bla/darwin_amd64_race_stripped/go_default_test.runfiles failed (Exit 1)
_bin/build-runfiles (args bazel-out/darwin-fastbuild/bin/bla/bla/bla/darwin_amd64_race_stripped/go_default_test.runfiles_manifest bazel-out/darwin-fastbuild/bin/bla/bla/wiring/darwin_amd64_race_stripped/go_default_test.runfiles): link or target filename contains space on line 12: '__main__/bla/bla/bla/testdata/k8s deployment with dependency.bundle.yaml /gopath/src/bla/bla/bla/bla/bla/bla/testdata/k8s deployment with dependency.bundle.yaml'
```

Snippet from `BUILD.bazel`:
```bzl
go_test(
    name = "go_default_test",
    size = "small",
    srcs = ["some_test.go"],
    data = glob(["testdata/**"]),
    embed = [":go_default_library"],
    race = "on",
    deps = [
       ....
    ],
)
```
rules_go version 0.12.0, bazel 0.14.1, macOS

Does it mean I cannot use such names? Is it a bug or expected behavior?

p.s. tried to use the latest commit of rules_go but ran into https://github.com/bazelbuild/buildtools/issues/327.

**Comment by ash2k** [comment]
Looks like this is Bazel's limitation/design. Accidentally stumbled upon the explanation here https://docs.bazel.build/versions/master/build-ref.html#label_directory

> Unfortunately, there are some scenarios where directory labels must be used. For example, if the testdata directory **contains files whose names do not conform to the strict label syntax** (e.g. they contain certain punctuation symbols), then explicit enumeration of files, or use of the glob() function will produce an invalid labels error.

**Comment by jayconrod** [comment]
It's unfortunate this doesn't work. I was going to file an issue on Bazel, but I think bazelbuild/bazel#374 already covers this. That has been open for... quite a while. :(
