### ISSUE TITLE
Xcode is mandatory after objc support

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#1554]
Posting here so that others facing this issue are able to find a solution easily. Please feel free to close this issue if you decide that this is WAI.

https://github.com/bazelbuild/rules_go/pull/1437 made an Xcode install mandatory on macOS if the user does not specify `--macos_sdk_version` command line flag. Before this change, merely having the Xcode command line tools installed was sufficient.

It appears that the `apple_ensure_options` function adds the following two environment variables:
https://github.com/bazelbuild/rules_go/blob/bd1c095bdf04385a412a57c2feb9cd6e8fbe89c0/go/private/context.bzl#L308

```
APPLE_SDK_PLATFORM=MacOSX
APPLE_SDK_VERSION_OVERRIDE=10.10
```

When these environment variables are present, bazel ([XcodeLocalEnvProvider](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/exec/apple/XcodeLocalEnvProvider.java)) will use xcrun to determine the location of Apple SDK when sandboxing the build. The SDK at this specific version is available only when Xcode (app) is installed, but not when Xcode Command Line tools are installed. For the latter, only the SDK for the current OS version will be available, e.g. 10.13 is available on High Sierra.

In such a case, every rules_go action will fail with this error:
```
ERROR: /.../external/io_bazel_rules_go/BUILD.bazel:8:1: GoStdlib external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/pkg failed: I/O exception during sandboxed execution: xcrun failed with code 1.
This most likely indicates that SDK version [10.10] for platform [MacOSX] is unsupported for the target version of xcode.
Process exited with status 1
stdout: stderr: xcrun: error: SDK "macosx10.10" cannot be located
xcrun: error: SDK "macosx10.10" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'macosx10.10'
```

A quick solution to this is for users to specify `build --macos_sdk_version=10.13` for High Sierra, and similar for other OS versions in their bazelrc.

A desired solution at rules_go level would be to introduce these environment variables only when objc files are present in sources, as people not writing Apple specific code are not familiar with these bazel command line flags.

**Comment by jayconrod** [comment]
So what exactly is broken and when? I tried uninstalling Xcode and reinstalling Xcode command line tools. After doing that, objc code no longer builds. cgo code and C/C++ targets still build all right though.

**Comment by siddharthab** [comment]
So with Xcode uninstalled, and only Command Line Tools with 10.13 SDK present. I.e.

```
$ xcode-select -p
/Library/Developer/CommandLineTools

$ ls $(xcode-select -p)/SDKs
MacOSX.sdk	MacOSX10.13.sdk
```

I get the error:
```
$ bazel build -s @io_bazel_rules_go//tests/core/stdlib:stdlib_files
INFO: Analysed target @io_bazel_rules_go//tests/core/stdlib:stdlib_files (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # @io_bazel_rules_go//:stdlib [action 'GoStdlib external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/pkg']
(cd /private/var/tmp/_bazel_sbagaria/cbc65c0599a628f6b259751382f9efc3/execroot/grail && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.10 \
    ...
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/stdlib -sdk external/go_sdk -out 'bazel-out/darwin-opt/bin/external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~' -filter_buildid bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/filter_buildid)
ERROR: /private/var/tmp/_bazel_sbagaria/cbc65c0599a628f6b259751382f9efc3/external/io_bazel_rules_go/BUILD.bazel:8:1: GoStdlib external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/pkg failed: I/O exception during sandboxed execution: xcrun failed with code 1.
This most likely indicates that SDK version [10.10] for platform [MacOSX] is unsupported for the target version of xcode.
Process exited with status 1
stdout: stderr: xcrun: error: SDK "macosx10.10" cannot be located
xcrun: error: SDK "macosx10.10" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'macosx10.10'
Target @io_bazel_rules_go//tests/core/stdlib:stdlib_files failed to build
```

**NOTE** The value of the environment variable `APPLE_SDK_VERSION_OVERRIDE` will ask bazel to look for 10.10 but users with new macOS installs won't have that version.

If you specify the SDK version yourself to the version you have, then everything works great.
```
$ bazel build --macos_sdk_version=10.13 @io_bazel_rules_go//tests/core/stdlib:stdlib_files
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target @io_bazel_rules_go//tests/core/stdlib:stdlib_files (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # @io_bazel_rules_go//:stdlib [action 'GoStdlib external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/pkg']
(cd /private/var/tmp/_bazel_sbagaria/cbc65c0599a628f6b259751382f9efc3/execroot/grail && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.13 \
    ...
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/stdlib -sdk external/go_sdk -out 'bazel-out/darwin-opt/bin/external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~' -filter_buildid bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/filter_buildid)
Target @io_bazel_rules_go//tests/core/stdlib:stdlib_files up-to-date:
  bazel-bin/external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/ROOT
  bazel-bin/external/io_bazel_rules_go/darwin_amd64_stripped/stdlib~/pkg
```

I think ObjC code needs Xcode app to be present. There I get this probably expected error:
```
ERROR: .../external/io_bazel_rules_go/tests/core/cgo/objc/BUILD.bazel:28:1: in objc_library rule @io_bazel_rules_go//tests/core/cgo/objc:sub: Expected action_config for 'objc-compile' to be configured
```

Am I still not being clear?

**Comment by jayconrod** [comment]
That is clear, but I wasn't seeing the same issue yesterday after installing Xcode. Not really sure what the difference is between our setups, but your change seems to work, so it's probably not worth digging into.
