### ISSUE TITLE
force cgo in new_go_repository?

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#156]
First up, thanks so much for all this work. It's been a real joy to use.

Okay, so when I use `new_go_repository` on a project requiring cgo, it seems to miss that there are c files it needs.

A relatively common example of this is

    new_go_repository(
        name = "com_github_mattn_go_sqlite3",
        importpath = "github.com/mattn/go-sqlite3",
        commit = "7204887cf3a42df1cfaa5505dc3a3427f6dded8b",
    )

and running a build command on its targets.

I'm not quite sure what would be the best way to solve it. Looking for cgo code every time that bazel hits this repo seems like a likely non-starter. A param to specify a list of cgo packages inside that repo that we pass into new_go_repository? Or maybe the long term solution is to just not work on cgo repositories and have people specify them by hand?

**Comment by jmhodges** [comment]
(I'd maybe just make a cgo_library target on top of the code in the remote and use that, but I actually have other `new_go_repository`-made repositories that depend on the cgo repository directly.)

**Comment by jmhodges** [comment]
Oh! This is just using gazelle under the hood, so we *could* just look at pkg.CGoFiles. I've spent a little too much time shaving yaks today, but maybe I could take a pass at it.

**Comment by pmbethe09** [comment]
@wlynch will take a pass at extending gazelle for this

**Comment by pmbethe09** [comment]
One problem I see here is: where does sqlite3*.h come from?

In order for the cgo_library to work, sqllite would need to be accessible somehow from cdeps, as bazel requires a hermetic dependency defined in the WORKSPACE and BUILD rules.

Short of pushing BUILD files into github.com/mattn/go-sqlite3 and just using go_repository,
the only idea I see is maybe adding a 'cdeps' attribute to new_go_repository, passed down to gazelle and maybe used in cdeps for all cgo_library that are detected.  This will over-depend if there are multiple cgo_library, but maybe it is easiest, where trying to do more is much harder.
Then in your top-level WORKSPACE, you define sqllite or equivalent, etc.

**Comment by jmhodges** [comment]
For go-sqlite3 specifically, passing the sqlite*.h around is unnecessary. It keeps all of the C bindings behind the Go API and the static binaries created work just fine in libs or commands that depend on them. At least at the sha I use: https://github.com/mattn/go-sqlite3/tree/7204887cf3a42df1cfaa5505dc3a3427f6dded8b

That seems to be true of most cgo packages, too, so there's maybe value in simpler patch that can have the cdeps stuff built into after?

I did have to do a bunch of manual build tag for it but we all know about the build tag support stuff. I've posted [a gist with it](https://gist.github.com/jmhodges/772daecb03ebeeba671d255ed27ddb41) just in case someone else wants it.

**Comment by jmhodges** [comment]
I needed this this weekend so I wrote it. https://github.com/bazelbuild/rules_go/pull/166

Thanks again for being patient with me stealing work. Just got stuff I had to unblock.

**Comment by pmbethe09** [comment]
Right, gazelle does not yet know how to create cgo_library.  It also does
not know how to create the 'main test' pattern which is needed as the rules
don't allow a go_test to depend on a go_binary.  (see
https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/gazelle/BUILD
for the example of what it should create).
