### ISSUE TITLE
no such package '@com_github_cespare_xxhash//': The repository could not be resolved

### ISSUE THREAD

**Issue by senior7515** [bazelbuild/rules_go#1569]
Running latest 0.12.1 and gazelle 0.12.

# Build file: 

```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "CompressionFlags.go",
        "DynamicHeader.go",
        "Header.go",
        "HeaderBitFlags.go",
        "PayloadHeaders.go",
        "client.go",
        "connection.go",
        "handle.go",
        "header_utils.go",
        "server.go",
        "service.go",
    ],
    importpath = "github.com/senior7515/smf/src/go/smf",
    visibility = ["//visibility:public"],
    deps = [
        "//src/third_party/flatbuffers/go",
        "@com_github_cespare_xxhash//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["dispatch_test.go"],
    embed = [":go_default_library"],
)

```

# Error: 

```
ERROR: /home/agallego/workspace/smf/src/go/smf/BUILD.bazel:3:1: no such package '@com_github_cespare_xxhash//': The repository could not be resolved and referenced by '//src/go/smf:go_default_library'
ERROR: Analysis of target '//src/go/smf:go_default_test' failed; build aborted: no such package '@com_github_cespare_xxhash//': The repository could not be resolved

```

# Things I've done to Resolve

* I've tried 12.0 and 11 versions  with no luck
* manually generated the BUILD.bazel file 
* looked through all the issues related to this and couldn't find / understand a fix that would work

Here is a link to the open source project build file:

https://github.com/senior7515/smf/blob/master/src/go/smf/BUILD.bazel

**Comment by senior7515** [comment]
This works great thanks! 

Is there a way to avoid `bazel run //:gazelle ...` ignore some repos

I have some manual deps for c++ cmake (that also happen to have go) in 

src/thirdparty/*

when I run bazel run //:gazelle it creates BUILD.bazel files in all transitive projects. 

how do i set the default to ignore say all in //src/thirdparty/*

**Comment by jayconrod** [comment]
Gazelle can be configured using [special comments in build files](https://github.com/bazelbuild/bazel-gazelle#directives). In this case, `# gazelle:exclude` is probably what you need. In your top-level build file, you could write the comment below, and Gazelle won't recurse into that directory:

```
# gazelle:exclude src/thirdparty
```

At the moment, there's no way to give it a whitelist of directories, though that would probably be a useful feature.

**Comment by senior7515** [comment]
Awesome thank you! it all works.
