### ISSUE TITLE
Teach gazelle the "main sandwich"

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#157]
e.g. https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/gazelle/BUILD

gazelle should be able to generate this BUILD file, but it doesn't know how to make the go_library for testing, and then use 'library =' to create the go_binary rule.

**Comment by jmhodges** [comment]
Sorry to steal work from others, but I had need for this today. So, I pushed up #164 to get it done.

**Comment by pmbethe09** [comment]
Fix was not quite right, reopening
