### ISSUE TITLE
Use google/protobuf v3.6.0

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1576]
The current version of protobuf includes invalid doc string which is unacceptable by Google Cloud Endpoints config manager:
> 'ERROR: google/protobuf/timestamp.proto:121:1: (at document line 76) Unexpected end tag '--)' with missing begin tag.'

v3.6.0 provides the [fix](https://github.com/google/protobuf/commit/92a7e778e7394386f413cec28d67a07630f784b1).

**Comment by jayconrod** [comment]
I'll upgrade the proto dependencies soon after #1548 is fixed (which should be in the next couple days). Ideally, I'd like to get a major release out with the fix and upgraded dependencies early next week.

**Comment by jayconrod** [comment]
`master` now has v3.6.0.1. That will be in rules_go 0.13.0, which should be released in a day or two.
