### ISSUE TITLE
run a script before go_test 

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#1588]
Now I get a demand that  run a script when to run go_test. if this go_test has been run, this script. have not to be run. Is it possible to make go_test to do this? or have i to write a rule to  complete this？

if i write a rule to complete , how to wrap go_test to Incrementally run this script？

**Comment by jayconrod** [comment]
I'm not sure I understand what you're asking. Are you trying to run a script (what kind of script?) from a `go_test`? Or do you want to run a `go_test` from a script? Is the script part of another test or is it outside Bazel?

**Comment by hawkingrei** [comment]
this script is to start up some infra for finishing the unit test. this script may be writed by golang.

our reposity is a monorepo. it includes many project. so we want to incrumentally start up this infra before running some unit test by this script.

**Comment by jayconrod** [comment]
I expect you may want to write a Bazel rule to build the script and manage its dependencies.

From the `go_test` side, you'll want to make sure the script is built and available when your test runs. Referencing the script through the `data` attribute is probably the best way to do that. You'll also need to know the location of the script. For that, you can expand the location in the test `args`, then you can access those arguments with `os.Args`.

```
sh_binary(
    name = "start_service",
    srcs = ["start_service.sh"],
)

go_test(
    name = "go_default_test",
    ...
    data = [":start_service"],
    args = ["$(location :start_service)"],
)
```

**Comment by jefersonla** [comment]
Sorry for reopening this very old question, but is it possible to define pre and post-routines for the go_test rule?
I want to do something very similar to what @hawkingrei wants.

The idea is that I have some integration tests that require another application running in the background to work. Using one sh_binary I can start and stop this application, but now I want to do this without having to call these scripts manually.

My plan was to use the genrule routine and create a small rule that runs a script before and other after the tests, but according to genrule docs (see https://bazel.build/reference/be/general#genrule):

> Do not use a genrule for running tests. 

So I don't know what I should do in this case.

**Comment by achew22** [comment]
I have to say that I agree with Jay's strategy here. Go has a notion of a [TestMain](https://pkg.go.dev/testing#hdr-Main) function where you can put arbitrary setup and tear down information. The best way to do this is probably to either run your script as a part of `TestMain` before invoking your tests, or to implement what the `sh_binary` would do in go and run that before invoking your tests.

Closing since I don't think we will ever support something more than that in the rule definition.
