### ISSUE TITLE
Building unstripped binaries on MacOS fails

### ISSUE THREAD

**Issue by pmuetschard** [bazelbuild/rules_go#1591]
`link.go` fails when building an unstripped binary (e.g. by passing `--strip never` to bazel) on MacOs.

In non-stripping mode, `link.go` is invoked without passing the `-w` flag as part of the `go link` tool options. On MacOS, this causes `go link` to attempt to create a temp file with the same name as the output executable, but with a `~` appended (i.e. `<executable>~`). See [golang/src/cmd/link/internal/ld/lib.go line 1344](https://github.com/golang/go/blob/ad4e6370fe801c7d7b97e893b87c7f3d5b05f955/src/cmd/link/internal/ld/lib.go#L1344.)

However, rules_go has already created a *directory* by that name to store the `main.a` library, causing `go link` to fail with:
`external/go_sdk/pkg/tool/darwin_amd64/link: combining dwarf failed: open bazel-out/darwin-opt/bin/<executable>~: is a directory`

For example:

Bazel invoking `link.go`:
```
env - CGO_ENABLED=1
  GOARCH=amd64
  GOOS=darwin
  GOROOT='bazel-out/darwin-opt/bin/external/io_bazel_rules_go/darwin_amd64/stdlib~'
  GOROOT_FINAL=GOROOT
  PATH=/usr/bin

bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/link
  -sdk external/go_sdk
  -dep [...]
  -o bazel-out/darwin-opt/bin/bar/darwin_amd64/foo
  -main 'bazel-out/darwin-opt/bin/bar/darwin_amd64/foo~/example.com/bar/foo.a
  --
  -extld external/local_config_cc/cc_wrapper.sh
  -extldflags '-headerpad_max_install_names -lc++ -no-canonical-prefixes'
```
Which then invokes `go link`, thusly:
```
external/go_sdk/pkg/tool/darwin_amd64/link
  -L [...]
  -o bazel-out/darwin-opt/bin/bar/darwin_amd64/foo
  -extld external/local_config_cc/cc_wrapper.sh
  -extldflags '-headerpad_max_install_names -lc++ -no-canonical-prefixes'
  bazel-out/darwin-opt/bin/bar/darwin_amd64/foo~/example.com/bar/foo.a
```

Notice the output file and main library archive:
```
bazel-out/darwin-opt/bin/bar/darwin_amd64/foo
bazel-out/darwin-opt/bin/bar/darwin_amd64/foo~/example.com/bar/foo.a
```

**Comment by jayconrod** [comment]
Thank you for reporting this, and thank you especially for analyzing the problem.

I'm changing the internal filename suffix to '%'. Hopefully there aren't any tools that unexpectedly create '%' files. :)
