### ISSUE TITLE
go_proto_library generates different package name from protoc

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1596]
(Originally bazelbuild/bazel-gazelle#271)

In [`github.com/googleapis/gnostic/extensions`](https://github.com/googleapis/gnostic/tree/master/extensions), when we build with `go_proto_library`, we generate a .pb.go file with the package name `extensions`. When we manually generate .pb.go files with protoc, we generate a .pb.go file with the package name `openapiextension_v1` (which matches the other .go file in the directory).

There is no `option go_package` in this proto. Gazelle sets the `importpath` to `github.com/googleapis/gnostic/extensions`, which is correct, but I think we're passing that path to `protoc-gen-go` in a way that sets the package name to the last element, `extensions`.

**Comment by tarekbecker** [comment]
I have the same issue when I try to build something using `https://github.com/hashicorp/go-plugin`. @jayconrod did you find a solution?

**Comment by jayconrod** [comment]
@tarekbecker Sorry, I haven't had time to look into this yet.
