### ISSUE TITLE
cross compiling for darwin

### ISSUE THREAD

**Issue by Godley** [bazelbuild/rules_go#1597]
Hi there, I'm attempting to cross compile a go binary using the instructions in the readme but with `darwin` selected. I seem to get an error I don't quite understand:
```
ERROR: While resolving toolchains for target //cmd/dm:dm: Target @bazel_tools//platforms:osx was referenced as a platform, but does not provide PlatformInfo
ERROR: Analysis of target '//cmd/dm:dm' failed; build aborted: Target @bazel_tools//platforms:osx was referenced as a platform, but does not provide PlatformInfo
...
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Am I missing some dependency?  I'm attempting cross compilation for darwin from a mac so that I can run the same build inside a container on a linux machine. Building locally and building in a container both fail with the same error though the build passes when I don't include the `--platform` argument.

## Version
I am on 0.13.0 of `rules_go` and `Build label: 0.15.1-homebrew` of bazel
## Workspace
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.13.0/rules_go-0.13.0.tar.gz"],
    sha256 = "ba79c532ac400cefd1859cbc8a9829346aa69e3b99482cd5a54432092cbc3933",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.13.0/bazel-gazelle-0.13.0.tar.gz"],
    sha256 = "bc653d3e058964a5a26dcad02b6c72d7d63e6bb88d94704990b908a1445b8758",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()
```
...plus a long list of go_repositories for the project.

**Comment by jayconrod** [comment]
Could you post the command line you're using? It should look something like this:

```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //cmd/dm
```

**Comment by Godley** [comment]
Ah, my bad, I was missing `_amd64` (`bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin //cmd/dm). Typical! Thanks :)
