### ISSUE TITLE
support fully static binaries

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/rules_go#161]
Users should be able to produce fully static binaries from go source, especially exclusively go source.

**Comment by pmbethe09** [comment]
The current binaries presumably have a shared dependency on libpthread and libc?

I get the same result on linux if I say 'go install github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle as when I 
bazel build //go/tools/gazelle/gazelle:gazelle

What is the magic flag to 'go build' to make it fully static?

**Comment by mikedanese** [comment]
```
CGO_ENABLED=0 go install github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
```
Should produce a static binary.

**Comment by powelljo** [comment]
I was just looking at this issue myself and see it's been discussed here already.  Has there been any progress made on passing along values of environment variables that Go builds can depend on?  I see there is limited support, specifically for `GOOS` and `GOARCH`, already [https://github.com/bazelbuild/rules_go/blob/c7e02c851a8faf803f260800e7387248ccd47683/go/def.bzl#L83].

**Comment by GinFungYJF** [comment]
Any update about this? If no, are there any workarounds?

**Comment by pmbethe09** [comment]
@jayconrod may look into this

**Comment by jayconrod** [comment]
I'm definitely planning to improve this. Cross compilation is a slightly higher priority in the short term though.

**Comment by mikedanese** [comment]
Also related: https://github.com/bazelbuild/rules_go/issues/217

Specifically, this would partially solve (although I believe this uses libc rather than the go libc implementation):

```python
go_binary(
    name = "foo",
    srcs = ["foo.go"],
    gc_linkopts = [
        "-linkmode external",
        "-extldflags -static",
    ],
)
```

**Comment by GinFungYJF** [comment]
@mikedanese The gc_linkopts attribute seems to has not been implemented.

**Comment by mikedanese** [comment]
@GinFungYJF It is not implemented in the opensource rules but it does exist in the internal rules (which are completely different). #217 proposes we implement similar feature in opensource.

**Comment by jayconrod** [comment]
`gc_linkopts` has been merged for a little while now. So static builds should work even with cgo present.

```bzl
go_binary(
    name = "main",
    srcs = ["main.go"],
    go_linkopts = [
      "-extldflags",
      "-static",
    ],
    library = ":cgo_lib",
)

cgo_library(
    name = "cgo_lib",
    srcs = ["cgo_lib.go"],
    cdeps = [":foo"],
)

cc_library(
    name = "foo",
    srcs = ["foo.c"],
)
```

Couple things to note:

* Linking without cgo is static by default. `-linkmode external` is not necessary.
* `-extldflags` must be a separate string from the actual flags, which must all be one string. 
* Static linking with cgo [does not work](https://developer.apple.com/library/content/qa/qa1118/_index.html) on macOS.

@mikedanese, is anything missing? Should anything work differently?

**Comment by jayconrod** [comment]
I'm closing this because `go_linkopts` gives control over static linking, but please re-open if anything more needs to be done.

**Comment by mikedanese** [comment]
@jayconrod I can't think of anything (other than mac support :) ). Thanks!

**Comment by gsf** [comment]
The correct attribute is `gc_linkopts`, not `go_linkopts`, correct?

**Comment by jayconrod** [comment]
Yes, `gc_linkopts` is the correct option.

**Comment by achew22** [comment]
Are there more flags that need to be passed in to statically link pthread?

My rule looks like this

```go
  go_binary(
      name = "bin",
      library = ":go_default_library",
      gc_linkopts = [
        "-extldflags",
        "-static",
      ],
  )
```

when I compile it 

```
$ ldd bazel-bin/my/path/bin
        linux-vdso.so.1 =>  (0x00007ffc97130000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f021b5e6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f021b21d000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556425e6d000)
```

Following the dependencies, pthread is coming in from a dependency on sqlite

**Comment by mikedanese** [comment]
@achew22 does this work for you:

https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.4/cmd/kubeadm/BUILD#L11-L22

**Comment by achew22** [comment]
Woo! That fixed it. Thanks for the help!
