### ISSUE TITLE
chdir in go_test to allow open source tests to run successfully

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#162]
This is just making a [TODO in the code](https://github.com/bazelbuild/rules_go/blob/9d29b3c40cd30007155eeb502e12899b9a53ec3b/go/def.bzl#L467-L469) into a ticket since I ran into this last night.

It would be nice for the Go tests to do a chdir to the directory holding the data files, so open-source go tests continue to work without code changes.

**Comment by pmbethe09** [comment]
Hmm, interesting idea.  bazel always runs your test from the 'root',
although it is a sandbox with only the files you declare available.  This
would be a deviation from that, but I suppose is inline with how Go runs
its tests.

**Comment by kerinin** [comment]
Being able to switch back and forth between `go test` and `bazel test` would make it much easier to transition my teams to bazel, as it allows people to  opt-in to the new hotness as they have time to learn new tools.

**Comment by pmbethe09** [comment]
We have existing bazel-style repos that expect things from the WORKSPACE
root, but
presumably in all gazelle-generated go_test, the Go-style behavior is
expected.

My suggestion: a 'go_test.run_in_root' attribute, which defaults to False,
but can be set to True if you want to do things bazel-styel (and therefore
not 'go build' compatible.)

Will look into it soon.

**Comment by kerinin** [comment]
FWIW, I'm hacking around this currently by running tests with `--run_under=wrap.sh` with

```sh
# wrap.sh
#!/bin/bash
cd $(dirname $1)
exec $(basename $1)
```

**Comment by jmhodges** [comment]
I think this got fixed?

**Comment by jayconrod** [comment]
Yes, this should work now.
