### ISSUE TITLE
means to pass run=Foobar down to a test?

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#163]
I can't seem pass any combination `-run=Foobar`, `run=Foobar` or `-test.run=Foobar` in a way that will get the test binary to run only tests matching "Foobar" with `--test_arg`.

Not sure what the deal is here. It definitely errors when you pass `-run`, but passing `test.run` (that it claims it supports) doesn't change the default behavior of running all tests.

I tested this with `bazel test --test_output=errors -s --test_arg=-test.run=GoPrefix //go/tools/gazelle/rules:go_default_xtest` and the TestGenerator test was also run instead of just TestGeneratorGoPrefix.

**Comment by jmhodges** [comment]
(Also, usually `-run` is supported by the test binaries in go, so maybe that's related?)

**Comment by jmhodges** [comment]
Fixed a typo in the summary. I meant to write `bazel test --test_output=errors -s --test_arg=-test.run=GoPrefix  //go/tools/gazelle/rules:go_default_xtest`.

**Comment by jmhodges** [comment]
Anyone know how to make this one work? Not sure what I'm missing here.

**Comment by pmbethe09** [comment]
No idea, never tried it.  @yugui ?

**Comment by jmhodges** [comment]
Ping @yugui

**Comment by jayconrod** [comment]
Closing some old issues. This should be fixed in #278. You should be able to filter tests now with `--test_filter=pattern` or with `--test_arg=-test.run=pattern`.
