### ISSUE TITLE
Conflicting resolutions for WKT dependencies

### ISSUE THREAD

**Issue by eduardoramirez** [bazelbuild/rules_go#1646]
I updated to `go_rules` 0.13.0 and I went through the process of running gazelle to update existing WKT proto dependencies to use the ones provided by `go_rules`, i.e.

```
"@com_github_golang_protobuf//descriptor:go_default_library_gen",
"@com_github_golang_protobuf//jsonpb:go_default_library_gen",
"@com_github_golang_protobuf//proto:go_default_library",
"@io_bazel_rules_go//proto/wkt:descriptor_go_proto",
```

Once I did that I rebuilt the app and got a lot of warnings of the form:

```
GoLink: warning: package "github.com/golang/protobuf/ptypes/timestamp" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/timestamp:go_default_library
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
```

The app still compiled and ran. However, I get a fatal error along the same lines when I build the `go_path` rule:

```
src/github.com/golang/protobuf/ptypes/struct/struct.pb.go: references multiple files (bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/proto/wkt/darwin_amd64_stripped/struct_go_proto~/github.com/golang/protobuf/ptypes/struct/struct.pb.go and external/com_github_golang_protobuf/ptypes/struct/struct.pb.go)
```

A snippet of my `WORKSPACE` file

```
# other stuff 

http_archive(
    name = "com_google_protobuf",
    urls = ["https://codeload.github.com/google/protobuf/zip/ab8edf1dbe2237b4717869eaab11a2998541ad8d"],
    strip_prefix = "protobuf-ab8edf1dbe2237b4717869eaab11a2998541ad8d",
    type = "zip",
)

new_http_archive(
    name = "com_github_googleapis",
    url = "https://github.com/googleapis/googleapis/archive/common-protos-1_3_1.zip",
    strip_prefix = "googleapis-common-protos-1_3_1/",
    build_file = "proto/googleapis.bzl",
)

http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.13.0/rules_go-0.13.0.tar.gz"],
    sha256 = "ba79c532ac400cefd1859cbc8a9829346aa69e3b99482cd5a54432092cbc3933",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.13.0/bazel-gazelle-0.13.0.tar.gz"],
    sha256 = "bc653d3e058964a5a26dcad02b6c72d7d63e6bb88d94704990b908a1445b8758",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

go_repository(
    name = "org_golang_google_genproto",
    commit = "81158efcc9f219c511e4d3c0d61a0e6e49c01a24",
    importpath = "google.golang.org/genproto",
)

go_repository(
    name = "com_github_golang_protobuf",
    commit = "b4deda0973fb4c70b50d226b1af49f3da59f5265",
    importpath = "github.com/golang/protobuf",
)

# more go_repository definitions.... 
```

I've spent quite a bit trying to understand what's going on here with no luck. Any ideas what might be happening here?

I saw this https://github.com/bazelbuild/bazel-gazelle/issues/159 which seemed like the same issue but was unsure of the resolution.

Thanks in advanced for any help!

**Comment by jayconrod** [comment]
Sorry for the conflicts, and thanks for reaching out. You may want to read through [Avoiding conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) in the Gazelle documentation for some background on what's happening. To summarize, you're getting two copies of `github.com/golang/protobuf/ptypes/timestamp` linked into your build: one is generated from .proto files during the build, and the other is built from pre-generated .pb.go files.

Gazelle *should* resolve import paths for the Well Known Types to one set of rules or the other. That's fairly new functionality though, and I'm not 100% confident it's working perfectly. It's possible that more special cases are needed.

One thing to start with: how is `@com_github_golang_protobuf//ptypes/timestamp:go_default_library` getting pulled into your build? That one is built from .pb.go files, and Gazelle shouldn't resolve imports to that unless proto rule generation is enabled. You can find the dependency chain with this command:

```
bazel query 'somepath(//:my_binary, @com_github_golang_protobuf//ptypes/timestamp:go_default_library)'`
```

**Comment by eduardoramirez** [comment]
Thanks for the prompt response. That command gave me more insight. It seems that [grpc gateway](https://github.com/grpc-ecosystem/grpc-gateway) is bringing those imports.
 
`bazel query` points to this rule (modified to show it) as the problematic one. In particular the gateway compiler.
```
go_proto_library(
    name = "model_go_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_grpc",
        "@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway:go_gen_grpc_gateway",
    ],
    importpath = "github.com/path/to/project",
    proto = ":model",
    deps = [
        "@go_googleapis//google/api:annotations_go_proto",
    ],
)
```

 the relevant snippet from `bazel query`

```
$ bazel query 'allpaths(//project/..., com_github_golang_protobuf//ptypes/timestamp:go_default_library)'
....
//proto:model_go_proto
@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway:go_gen_grpc_gateway
@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library
@com_github_golang_protobuf//ptypes:go_default_library
@com_github_golang_protobuf//ptypes/timestamp:go_default_library
```

The runtime package does indeed declare these dependencies in their [BUILD file](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/BUILD.bazel#L33).

I depend on this package through `go_repository`. Is there a way to force gazelle to modify those dependencies when it brings it into workspace?

**Comment by jayconrod** [comment]
Ok, it looks like grpc-gateway got those dependencies before Gazelle had a special case for `ptypes.` Re-running Gazelle in that repo *might* be enough to fix the problem, but I can't say for sure.

You can try adding `build_file_generation = "on"` in the `go_repository` rule. Normally, `go_repository` won't run Gazelle if there already a build file present in the root directory, but setting this to `on` forces Gazelle to run.

**Comment by eduardoramirez** [comment]
gotcha. Will give that a try. Thanks again.

**Comment by jayconrod** [comment]
@achew22 Could you take a look at this issue and let me know your thoughts?

To summarize, since 0.13.0, rules_go provides two different versions of several popular proto libraries (ptypes and the WKTs). One version generates code from .proto files at build time, and the other uses pre-generated .pb.go files. Mixing the two versions (e.g., by depending on each through different libraries linked into the same binary) may cause conflicts at compile-, link-, and run-time.

grpc-gateway depends on rules_go 0.12.1, so it doesn't have these new definitions. `//runtime:go_default_library` and other targets depend on `github.com/golang/protobuf/ptypes`, which depends on libraries built from .pb.go files, so those will conflict with `go_proto_library` rules for the equivalent libraries.

Have you run into this yet? I think it may be resolved by updating to a newer rules_go and Gazelle. Re-running Gazelle should update `deps` to point to the proto-generated targets by default (there are special cases for `github.com/golang/protobuf/ptypes` and a few others).

**Comment by eduardoramirez** [comment]
newer versions of grpc-gateway fixed this.
