### ISSUE TITLE
Cannot download go1.10.1.linux-amd64.tar.gz from China

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_go#1660]
Using `rules_go` tag `0.14.0`.

The initialization failed `go_download_sdk` with url `https://dl.google.com/go1.10.1.linux-amd64.tar.gz`.

The download failed because of the GFW.

I know I can tweak the `urls` attribute in the `go_download_sdk` rule to switch to another source. But it would be better for Chinese mainlanders to have DIRECT access to a china based mirror.

**Comment by jayconrod** [comment]
Unfortunately, I cannot provide another source for these archives.
