### ISSUE TITLE
Android should also match Linux config_setting

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#1672]
The Go compiler matches the Linux tag when building for Android. Selecting on `@io_bazel_rules_go//go/platform:linux` should also work when building with `@io_bazel_rules_go//go/platform:android`, if possible.

Or perhaps Gazelle should generate the two select clauses?

**Comment by jayconrod** [comment]
Closing old issues. I think this one has been fixed for a while. Please comment if not.
