### ISSUE TITLE
build tags in cgo directive support

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#168]
Build tag support is, in general, ongoing, and we'd like to extend it to include cgo's CFLAGS, LDFLAGS, etc., directives.

This seems like a side-issue to the main thrust of getting build tags going, and I could easily imagine myself forgetting it in the excitement of having build tags. Nice to track it separately.

**Comment by jmhodges** [comment]
This maybe got handled in https://github.com/bazelbuild/rules_go/commit/ff444c3e587d4073266f3f680598408e228ef6af ?

**Comment by 1-z** [comment]
We now have support for GOOS/GOARCH build tags in cgo (e.g. "linux", "amd64", etc), but not arbitrary tags (e.g. "example" or "openssl"). I may poke at this. Is there already a design in place for what this ought to look like?

**Comment by 1-z** [comment]
I create a pull request with some progress for arbitrary flags. I am taking as implicit that go_library and go_binary are covered in local workspaces by their maintainers running Gazelle to generate the BUILD files with appropriate flags. Thoughts?

This allows setting desired build_tags with Gazelle as well as new_go_repository:
https://github.com/bazelbuild/rules_go/pull/224

**Comment by ianthehat** [comment]
I believe all cgo tag handling is now correct with the new filtering happening in the cgo tool wrapper.
