### ISSUE TITLE
Fail to build kythe with "GoCompile: missing strict dependencies:" issue

### ISSUE THREAD

**Issue by liangti** [bazelbuild/rules_go#1694]
Hi,

I just start using bazel to build kythe, which is another opensource project of google. And I end up with the following issue, which I totally have no idea about.

```
{home_dir}/.cache/bazel/_bazel_{username}/98d38803a60823c92ebfddc03cf95f21/external/org_golang_google_api/transport/http/BUILD.bazel:3:1: GoCompile external/org_golang_google_api/transport/http/linux_amd64_stripped/go_default_library~/google.golang.org/api/transport/http.a failed (Exit 1)
GoCompile: missing strict dependencies:
	{home_dir}/.cache/bazel/_bazel_{username}/98d38803a60823c92ebfddc03cf95f21/sandbox/processwrapper-sandbox/17/execroot/io_kythe/external/org_golang_google_api/transport/http/go18.go: import of "go.opencensus.io/exporter/stackdriver/propagation"
	{home_dir}/.cache/bazel/_bazel_{username}/98d38803a60823c92ebfddc03cf95f21/sandbox/processwrapper-sandbox/17/execroot/io_kythe/external/org_golang_google_api/transport/http/go18.go: import of "go.opencensus.io/plugin/ochttp"
Known dependencies are:
	google.golang.org/api/googleapi/transport
	google.golang.org/api/internal
	google.golang.org/api/option
	golang.org/x/net/context
	golang.org/x/oauth2
Check that imports in Go sources match importpath attributes in deps.
```

Please forgive me for hiding home path and username.

The `BUILD.bazel` is following:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "dial.go",
        "go18.go",
        "not_go18.go",
    ],
    importpath = "google.golang.org/api/transport/http",
    visibility = ["//visibility:public"],
    deps = [
        "//googleapi/transport:go_default_library",
        "//internal:go_default_library",
        "//option:go_default_library",
        "@org_golang_x_net//context:go_default_library",
        "@org_golang_x_oauth2//:go_default_library",
    ],
)
```

It seems the `go` file is create temporarily so that there is no way to check the file. And I don't think I am suppose to change bazel setting or kythe source code? It should be some global environment issue I guess. Can somebody take a look at that and give me some ideas about that? 

Thanks a lot~

**Comment by jayconrod** [comment]
Sorry for the slow response time. I'm still catching up on issues after GopherCon.

I wasn't able to reproduce this failure with kythe on master. Are you building a different target or configuration? Did you report this in google/kythe?

```
$ bazel build @org_golang_google_api//transport/http:go_default_library
...
bazel: Leaving directory `/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/8b47ceb8acae79b729d207679095a22d/execroot/io_kythe/'
Target @org_golang_google_api//transport/http:go_default_library up-to-date:
  bazel-bin/external/org_golang_google_api/transport/http/linux_amd64_stripped/go_default_library%/google.golang.org/api/transport/http.a
```

**Comment by liangti** [comment]
Thank you for replying. I try 
`bazel build @org_golang_google_api//transport/http:go_default_library` 
and it reports same issue, that is missing two dependencies. 

So I manually add 
```
"@io_opencensus_go//exporter/stackdriver/propagation:go_default_library",
"@io_opencensus_go//plugin/ochttp:go_default_library",
```
into the `{home_dir}/.cache/bazel/_bazel_{username}/98d38803a60823c92ebfddc03cf95f21/external/org_golang_google_api/transport/http/BUILD.bazel` and it pass and build successfully.

I guess it may be some environment setting issue? So that some machine can build successfully and some fail?

**Comment by jayconrod** [comment]
When I build from master (`b36c955`), the generated build file has those dependencies already.

> I guess it may be some environment setting issues? So that some machine can build successfully and some fail?

Could be. Could you tell me more about your environment? I was trying this on linux/amd64.

**Comment by liangti** [comment]
Same operating system and same architecture, also same commit. 

Several things are different in my environment. Not sure are relevant to this issue., but I do want to learn more about bazel.

So one is that the bin, lib and include are not /usr/bin, /usr/lib, and /usr/include, but different path. So when I use bazel to build kythe, it reports `bison` command not found in a bzl file `tools/build_rules/lexyacc.bzl`, because seems bazel tends to search binary file in default path. Is there any method to specify environment path such as lib, bin, include in bazel? Seems flag `LDFLAGS` is not working. Please notice that the `PATH` environment variable already set .

**Comment by liangti** [comment]
Thank you for your help. I got the following information:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="{home_dir}/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="{home_dir}/go"
GORACE=""
GOROOT="{my_own_path}/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="{my_own_path}/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build853997774=/tmp/go-build -gno-record-gcc-switches"
```

Again the lib is in different directory, not in /usr/lib. And one more thing that is my machine is in an internal environment so that it may not be able to fetch some external source sometimes, due to proxy, certificate issues. I specify the certificates and proxy for bazel. Would that be an issue for gazelle too?

**Comment by jayconrod** [comment]
Thanks for posting the environment info. I don't see anything unusual in there.

It's possible an internal proxy would interfere with Gazelle. When Gazelle encounters an external import path (one outside of the current prefix), it will try to determine what part of the import path corresponds to the repository and what part is the path within the repository. This is how `go.opencensus.io/plugin/ochttp` gets transformed to `@io_opencensus_go//plugin/ochttp:go_default_library`.

There are some special cases for major sites like github.com and golang.org. Both the missing imports are from go.opencensus.io, which is not special-cased, so that's likely the problem.

Gazelle supports a `-known_import` flag which is meant to work around this problem. So something like this *might* work:

```
go_repository(
    name = "org_golang_google_api",
    build_extra_args = ["-known_import=go.opencensus.io"],
    commit = "3097bf831ede4a24e08a3316254e29ca726383e3",
    custom = "google_api",
    custom_git = "https://github.com/google/google-api-go-client.git",
    importpath = "google.golang.org/api",
)
```

**Comment by liangti** [comment]
Oh, really helpful. Thanks for helping me. I will study about it later.
