### ISSUE TITLE
Please update bazel-toolchains pin.

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/rules_go#1698]
Please update the [@bazel-toolchains](https://github.com/bazelbuild/bazel-toolchains) pin to the latest as described here: https://releases.bazel.build/bazel-toolchains.html.

The Buildkite configuration for RBE builds/tests has been [modified](https://github.com/bazelbuild/continuous-integration/pull/314/files) to use the latest configs from @bazel-toolchains which are only available at the latest release of the repo. You might have already got the following error in the RBE Ubuntu1604 Buildkite builds/tests:

```
ERROR: no such package '@bazel_toolchains//configs/ubuntu16_04_clang/1.0/bazel_0.16.1/default': BUILD file not found on package path
```

Update the @bazel-toolchains pin to [latest](https://releases.bazel.build/bazel-toolchains.html) will resolve the above issue.

In the future, if you see a similar error like the above, it might be your @bazel-toolchains pin is out-of-date again.

**Comment by jayconrod** [comment]
@xingao267 Is there a better way to keep this up to date automatically?

**Comment by nlopezgi** [comment]
@jayconrod, sorry for this issue. This is the first Bazel release since we started enabling rule repos to run CI on remote execution. We are improving how this process works for the next Bazel release.

**Comment by jayconrod** [comment]
@nlopezgi Sounds good. I'm glad to have the additional platform test coverage!
