### ISSUE TITLE
Re-evaluate go_path's mode = "copy"

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1699]
When Bazel makes a directory artifact visible to an action, it may create a symbolic link to the directory *or* it may create symbolic links for individual files in the tree. This is new behavior in Bazel 0.17. Previously, `go_path` relied on Bazel linking to the directory in order to create a `copy` mode artifact with `go_path`.

`//tests/core/go_path:go_path_test` has been disabled until this issue is resolved, since it is failing in Bazel CI at HEAD.

Related issues:

* bazelbuild/bazel#5682 - original report of test breakage.
* #1669 - report of test breakage in rules_go.
* bazelbuild/bazel#5971 - report of change in Bazel behavior.

**Comment by buchgr** [comment]
Hey Jay, could you please explain to me what the user facing (i.e. as a user of rules_go) impact of this issue is? Thanks!

**Comment by jayconrod** [comment]
@buchgr This issue causes an observable change in the behavior of `go_path` with `mode = "copy"`: the contents of the directory may be symbolic links instead of files.

I don't know of any consumer of `go_path` that would be broken because of that. So this may be a very low impact change. It's possible that if someone is running `tar` directly on the output without dereferencing links, that would break, but there's already a `mode = "archive"`, so hopefully people use that instead.

In any case though, if there's no effective difference between `mode = "copy"` and `mode = "link", there's no need to have both.
