### ISSUE TITLE
Request for bumping version

### ISSUE THREAD

**Issue by yugui** [bazelbuild/rules_go#17]
As reported in #14, the only available tag v0.0.1 does not work fine with real applications.
So it would be better to dump the version to v0.0.2 with a commit after 3dc43724d4d914294d9021a6a809fe74410d28e8.

Also [`README.md`](https://github.com/bazelbuild/rules_go#setup) needs to be updated so that it points the new version.

**Comment by kchodorow** [comment]
What do you mean? I can change the README and tag that commit as 0.0.2.

**Comment by damienmg** [comment]
I just mean we do not have any real owner for the go rules right now so nobody to maintain those tag and decide to create new tag. We can continue by going best effort from us or maybe we should put that in the sheriff bucket or any other good solution.

**Comment by kchodorow** [comment]
Sounds reasonable for now.

**Comment by pnasrat** [comment]
Is there a process for external folks to become maintainers - I'm just starting to look at issues in the ruleset here, and potentially given time can contribute more fully here.

**Comment by damienmg** [comment]
Not really a process, for the scala rules we just gave the support to the people actually developing them. 

With the go rules, because of glaze, we still need a good owner on the Google side but we would be happy to have external maintainers too.

**Comment by kchodorow** [comment]
Bumped: https://github.com/bazelbuild/rules_go/releases/tag/0.0.2.
