### ISSUE TITLE
Where are the bazel go tool chains hosted? 

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1705]
I would like host them locally and modify the url go rules uses.

**Comment by jayconrod** [comment]
For anyone finding this later, rules_go downloads the standard toolchains from golang.org.

[go/toolchains.rst](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst) has information about customizing the toolchains. In particular, [`go_download_sdk`](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go-download-sdk) is probably what you'd want.
