### ISSUE TITLE
Cross Compiling to armv5

### ISSUE THREAD

**Issue by pweaver** [bazelbuild/rules_go#1719]
How do I set GOARM=5 when cross compiling go code? Should this be a separate platform?

**Comment by wuhanstudio** [comment]
> rules_go doesn't provide direct support for `GOARM`, but I expect setting `--action_env=GOARM=5` on the command line should work.

I tried to build an armv6 executable with:
```
bazel build --action_env=GOARM=6  --platforms=@io_bazel_rules_go//go/toolchain:linux_arm //:target
```
But an executable file armv5 was generated.
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```

**Comment by jayconrod** [comment]
Closing old issues. Sorry, this won't be supported.

**Comment by fmeum** [comment]
We added support for AMD64 microarchitecture levels in https://github.com/bazelbuild/rules_go/commit/eb03b81312c3d459fb1ffdb18da9aa122e649905.

We would accept contributions that add support for `GOARM` along these lines.
