### ISSUE TITLE
go_test fails on windows if package is inside folder

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_go#1720]
When using Windows, If I have the exact same empty test inside and outside a folder inside my workspace, the test outside the folder will succeed and the one inside will fail.

Reproduction:
- `git clone https://github.com/filipesilva/bazel_go_windows`
- `cd bazel_go_windows`
- `bazel test ...`
```
$ bazel test ...
INFO: Analysed 4 targets (0 packages loaded).
INFO: Found 2 targets and 2 test targets...
FAIL: //foo:go_default_test (see C:/users/kamik/_bazel_kamik/5xrk7syg/execroot/__main__/bazel-out/x64_windows-fastbuild/testlogs/foo/go_default_test/test.log)
INFO: Elapsed time: 1.415s, Critical Path: 0.55s
INFO: 1 process: 1 local.
INFO: Build completed, 1 test FAILED, 2 total actions
//:go_default_test                                              (cached) PASSED in 0.7s
//foo:go_default_test                                                    FAILED in 0.5s
  C:/users/kamik/_bazel_kamik/5xrk7syg/execroot/__main__/bazel-out/x64_windows-fastbuild/testlogs/foo/go_default_test/test.log

Executed 1 out of 2 tests: 1 test passes and 1 fails locally.
INFO: Build completed, 1 test FAILED, 2 total actions
```
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //foo:go_default_test
-----------------------------------------------------------------------------
2018/09/17 15:19:58 could not change to test directory: chdir C:\users\kamik\_bazel_kamik\5xrk7syg\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\foo\windows_amd64_stripped\go_default_test.exe.runfiles\__main__\foo: The system cannot find the file specified.
```

If I had to best, it's related to looking up runfiles on Windows. `rules_go` has some helpers (https://github.com/bazelbuild/rules_go/tree/master/go/tools/bazel) that maybe can address this. Unsure why it doesn't happen on the root package though.

I'm using Windows 10, Bazel 0.17.1, and `rules_go` at https://github.com/bazelbuild/rules_go/commit/1bad20854a59785f4896d8b8847bdb57bfccf2ba.

**Comment by jayconrod** [comment]
By default, `go_test` tries to change to the package directory when it starts. That assumes that the runfiles symlink tree has been constructed, but Bazel doesn't construct runfile symlink trees on Windows because Windows only lets admin users create symlinks.
