### ISSUE TITLE
Error extracting buildifier

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#174]
When I use bazel to build the "//examples/external:record_log" int the examples, bazel downloads the buildifier. But the *.zip it not correct, it's just a web page. So it can't be extracted.How to solve it?

**Comment by pmbethe09** [comment]
Can you give more detailed reproduction instructions?  Running against
rules_go HEAD, which is cae6f4bb955034a0a9940715fbc743af7dc02709
and bazel HEAD which is b3610d54c87938e89e81d83810c0d16a41115a11

'bazel build //examples/external:record_log'

Works fine for me.

**Comment by pmbethe09** [comment]
and I was running on ubuntu linux, but have also confirmed it works fine on
OSX
