### ISSUE TITLE
Make cgo use standard C/C++ toolchain actions

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1742]
Currently, when `cgo = True` on `go_library`, `go_binary`, or `go_test`, we create a large graph of *rules*.

* There is an internal `_cgo_codegen` rule that generates pure C and pure Go code.
* Go code is built with `go_library`.
* The C code is compiled with `cc_library` and `cc_binary`. Objects are extracted out of the static library and packed into the .a file produced by `go_library`.
* Lots of other details.

This graph is repeated for every configuration that could affect the evaluation of build tags, so it has a significant overhead in analysis time. It's also hostile to `bazel query`, since there are a lot of targets that are less in the *what to build* category and more in the *how to build it*.

Recently, Bazel exposed a lot more information about the C/C++ toolchain to Starlark rules. We should be able to incorporate cgo directly into the analysis code that implements `go_library`, `go_binary`, and `go_test`. We should not need separate rules for code generation or C/C++ compilation.

It may still be necessary to use `objc_library` to compile Objective C code, since the Objective C toolchain is not exposed.

**Comment by jmhodges** [comment]
I'm not sure what's left on this ticket. I think maybe the code that needed this was finally deleted in https://github.com/bazelbuild/rules_go/commit/d31ac798d17a307a305a585c1be60b729acb6a09 ?

**Comment by jayconrod** [comment]
Yeah, this can be closed.
