### ISSUE TITLE
rules_go query breaks on github.com/cloudflare/cfssl/ on macOS

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#175]
When using cloudflare/cfssl in new_go_repository, rules_go sees the [script/build](https://github.com/cloudflare/cfssl/blob/master/script/build) bash shell script and breaks. This happens only on case-insensitive file systems like macOS's.

Interestingly, there is no Go code in that package, so if rules_go was able to figure out that it wasn't a real BUILD file, or delay processing the BUILD file until after it found all the go packages in the repo, the problem might be fixable without also having to way for the bazel `BUILD.bazel` change to happen.

**Comment by jmhodges** [comment]
Ah, now that I think about it, this is maybe a bazel problem? It only occurs when querying for all of the targets in that external repo.

    $  bazel query @com_github_cloudflare_cfssl//...
    ERROR: package contains errors: script.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:4:11: invalid character: '$'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:13:22: invalid character: '$'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:19:18: invalid character: '$'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:29:63: invalid character: '$'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:40:20: invalid character: '`'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:40:24: invalid character: '`'.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:4:16: syntax error at '"$(dirname $0)"': expected ).
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:6:11: syntax error at '{': expected newline.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:10:1: syntax error at 'if': This is not supported in BUILD files. Move the block to a .bzl file and load it.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:2:6: name 'e' is not defined.
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:4:12: contains syntax error(s).
    ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/com_github_cloudflare_cfssl/script/BUILD:6:1: name 'relabel' is not defined.

**Comment by katre** [comment]
There's an open bug for this in the master bazel repo, see https://github.com/bazelbuild/bazel/issues/552.

**Comment by pmbethe09** [comment]
bazel gets tripped up by files or directories named 'build' on
case-insensitive file systems.  There is work in progress to solve this.
