### ISSUE TITLE
No actual toolchain_type for @io_bazel_rules_go//go:toolchain

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_go#1752]
With the fixes for https://github.com/bazelbuild/bazel/issues/6015, there will be an actual dependency from toolchains back to the respective toolchain_type target. rules_go currently does not actually define the toolchain_type, and so builds fail (see https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/480#5b3d386c-f1d5-412d-adf0-522dd5856b2c for a sample).

Error:
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ef9bf13ce4d6a32f18a051c5f9234a8d/external/go_sdk/BUILD.bazel:52:1: no such target '@io_bazel_rules_go//go:toolchain': target 'toolchain' not declared in package 'go'; however, a source directory of this name exists.  (Perhaps add 'exports_files(["toolchain"])' to go/BUILD, or define a filegroup?) defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ef9bf13ce4d6a32f18a051c5f9234a8d/external/io_bazel_rules_go/go/BUILD.bazel and referenced by '@go_sdk//:go_windows_amd64'
```

**Comment by katre** [comment]
The fix is to define the toolchain_type target, which I will send a PR for shortly.

@jayconrod,  how difficult will it be to get this into a released rules_go before Bazel 0.20.0 is cut (early November)?

**Comment by jayconrod** [comment]
@katre Not hard hard all. I expect to tag a major release on Monday, and possibly another release by the end of October with updated C/C++ toolchain calls (major or minor release depending on how big the change is).

**Comment by katre** [comment]
Okay, good. I've identified the following downstream projects that are failing in CI due to this error:
* bazel-toolchains
* buildtools
* Gerrit
* rules_docker
* rules_nodejs
* rules_sass
* rules_typescript
