### ISSUE TITLE
Conflicting package heights error with go_library and go_proto_library

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#1772]
it has not any problem when I use rules_go 0.14.3,  but when it is upgraded to 0.15.x, it will be reported
```
ERROR: /Users/bilibili/go/src/go-common/app/service/main/assist/model/assist/BUILD:8:1: GoCompile app/service/main/assist/model/assist/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/assist/model/assist.a failed (Exit 1): compile failed: error executing command
  (cd /private/var/tmp/_bazel_bilibili/bd4bb69cb618928c1f3c0616978ab91f/execroot/__main__ && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/compile -sdk external/go_sdk -installsuffix darwin_amd64 -src app/service/main/assist/model/assist/assist.go -src app/service/main/assist/model/assist/rpc.go -arc 'go-common/app/service/main/account/model=go-common/app/service/main/account/model=bazel-out/darwin-fastbuild/bin/app/service/main/account/model/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/account/model.a' -arc 'go-common/app/service/main/member/model=go-common/app/service/main/member/model=bazel-out/darwin-fastbuild/bin/app/service/main/member/model/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/member/model.a' -arc 'go-common/library/ecode=go-common/library/ecode=bazel-out/darwin-fastbuild/bin/library/ecode/darwin_amd64_stripped/go_default_library%/go-common/library/ecode.a' -arc 'go-common/library/time=go-common/library/time=bazel-out/darwin-fastbuild/bin/library/time/darwin_amd64_stripped/go_default_library%/go-common/library/time.a' -o bazel-out/darwin-fastbuild/bin/app/service/main/assist/model/assist/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/assist/model/assist.a -package_list bazel-out/host/bin/external/go_sdk/packages.txt -- -trimpath . -p go-common/app/service/main/assist/model/assist)

Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: error running subcommand: exit status 2
/private/var/tmp/_bazel_bilibili/bd4bb69cb618928c1f3c0616978ab91f/sandbox/darwin-sandbox/109/execroot/__main__/app/service/main/assist/model/assist/assist.go:5:2: internal compiler error: conflicting package heights 13 and 20 for path "go-common/app/service/main/member/model"

```

in the 0.14.3. using `--subcommonds` : 
```
SUBCOMMAND: # //app/service/main/assist/model/assist:go_default_library [action 'GoCompile app/service/main/assist/model/assist/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/assist/model/assist.a']
(cd /private/var/tmp/_bazel_bilibili/bd4bb69cb618928c1f3c0616978ab91f/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM='' \
    APPLE_SDK_VERSION_OVERRIDE='' \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    XCODE_VERSION_OVERRIDE=10.0.0 \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/compile -sdk external/go_sdk -src app/service/main/assist/model/assist/assist.go -src app/service/main/assist/model/assist/rpc.go -dep go-common/app/service/main/account/model -dep go-common/app/service/main/member/model -dep go-common/library/ecode -dep go-common/library/time -importmap 'go-common/app/service/main/account/model=go-common/app/service/main/account/model' -importmap 'go-common/app/service/main/member/model=go-common/app/service/main/member/model' -importmap 'go-common/library/ecode=go-common/library/ecode' -importmap 'go-common/library/time=go-common/library/time' -o bazel-out/darwin-fastbuild/bin/app/service/main/assist/model/assist/darwin_amd64_stripped/go_default_library%/go-common/app/service/main/assist/model/assist.a -package_list bazel-out/host/bin/external/go_sdk/packages.txt -- -I bazel-out/darwin-fastbuild/bin/app/service/main/account/model/darwin_amd64_stripped/go_default_library%/ -I bazel-out/darwin-fastbuild/bin/app/service/main/member/model/darwin_amd64_stripped/go_default_library%/ -I bazel-out/darwin-fastbuild/bin/library/ecode/darwin_amd64_stripped/go_default_library%/ -I bazel-out/darwin-fastbuild/bin/library/time/darwin_amd64_stripped/go_default_library%/ -trimpath . -I . -p go-common/app/service/main/assist/model/assist)
```  

bazel.build Looks like this：
```
go_library(
    name = "go_default_library",
    srcs = [
        "assist.go",
        "rpc.go",
    ],
    importpath = "go-common/app/service/main/assist/model/assist",
    tags = ["automanaged"],
    visibility = ["//visibility:public"],
    deps = [
        "//app/service/main/account/model:go_default_library",
        "//app/service/main/member/model:go_default_library",
        "//library/ecode:go_default_library",
        "//library/time:go_default_library",
    ],
)
```
go version 1.11.1
bazel 0.18.0

so what clues you have about this？thank you. look forward to your reply.

**Comment by jayconrod** [comment]
"Conflicting package heights" is a new error in Go 1.11. Each .a file has a *package height* written into its export data which is the maximum of its imports' package heights plus one. If you're getting this error, it means you're importing a package which one of your imports also imported, but the .a file your import was compiled with was different than the .a file you're compiling against (it had a different package height written in).

We saw this error occasionally during the development of Go 1.11 when .a files from cgo and pure configurations were mixed together. Some libraries would depend on `runtime/cgo` in cgo mode but would have no dependencies in pure mode (which caused their package height to be different). 13 and 20 is a dramatic difference though.

I'm not sure how this error would come up with Bazel and rules_go though. Is there anything strange happening in your build with multiple configurations? Any possible you're depending on multiple `go_library` targets with the same `importpath` and `importmap`? Would you be willing to put together a minimal example that reproduces this so I can investigate further?

**Comment by hawkingrei** [comment]
I have made a minimal example at https://github.com/hawkingrei/bad-example

run command
```
bazel build //app/...
```

then you will see.

```
ERROR: /Users/bilibili/myresearch/bad-example/app/interface/main/account/model/BUILD:9:1: GoCompile app/interface/main/account/model/darwin_amd64_stripped/go_default_library%/go-common/app/interface/main/account/model.a failed (Exit 1)
GoCompile: error running subcommand: exit status 2
/private/var/tmp/_bazel_bilibili/4cde5f2b70453070070ed920a866809d/sandbox/darwin-sandbox/339/execroot/__main__/app/interface/main/account/model/relation.go:7:2: internal compiler error: conflicting package heights 13 and 20 for path "go-common/app/service/main/member/model"

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
INFO: Elapsed time: 157.595s, Critical Path: 25.87s
INFO: 338 processes: 338 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

i run it at macos 10.13.6 (17G65)

**Comment by jayconrod** [comment]
@hawkingrei Thanks for posting that repo, that's really helpful. I've started to look into this, and I *think* I know what's happening.

The problem that's causing the error is more than one library with the package path `go-common/app/service/main/member/model` is in the dependency graph of `//app/interface/main/account/model:go_default_library`. The are two targets with this `importpath`: `//app/service/main/account/model:model_go_proto` and `//app/service/main/account/model:go_default_library`. The `go_library` has additional .go files that introduce additional dependencies (so the archives produced by these targets will have different package heights).

`//app/interface/main/account/model:go_default_library` depends directly on `//app/service/main/account/model:go_default_library`, but it also depends on `//app/service/main/member/model:go_default_library`, which embeds `//app/service/main/member/model:model_go_proto`, which depends on `//app/interface/main/account/model:model_go_proto`. So I think that's how multiple archives with the same package path end up in the graph.

I'm not sure what the solution to this should be yet. Perhaps we should be more strict about checking duplicate package paths. But this way of generating dependencies for `go_library` and `go_proto_library` is intended to work. So maybe when we're processing embeds, if an embedded target (a `go_proto_library` has a dependency with the same package path as a dependency of the embedding target (a `go_library` rule), the embedding target should be able to override and replace the dependency. I think that would fix this case.

**Comment by hawkingrei** [comment]
Thank you! Do you have the plan to fix this problem?
