### ISSUE TITLE
Gazelle fails on Windows

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_go#1775]
Error:
```
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_tools//go/analysis': Traceback (most recent call last):
  | File "C:/users/b/_bazel_b/vdpycznq/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
  | patch(ctx)
  | File "C:/users/b/_bazel_b/vdpycznq/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 80, in patch
  | fail(("Error applying patch %s:\n%s%s...)))
  | Error applying patch @io_bazel_rules_go//third_party:org_golang_x_tools-gazelle.patch:
  | /usr/bin/bash: patch: command not found
```

This is on Bazel CI (https://buildkite.com/bazel/rules-typescript-typescript/builds/749#928243ad-1996-4d93-972a-f8f5600100be), trying to test https://github.com/bazelbuild/rules_typescript/pull/308 (in order to update rules_typescript to rules_go 0.16.0).

**Comment by jayconrod** [comment]
@katre `patch` must be installed on the host system in `PATH` in order for `git_repository` and `http_archive` to work. It's available in MSYS2 by running `pacman -S patch`. MSYS2 is a Bazel dependency, but you don't get `patch` by default. I wonder if that should be added to the Bazel Windows setup instructions?

It may be possible to bundle a `patch` executable or compile a small program in Go that can apply patches, but that's a lot of extra complication. Any ideas? What are other rule sets doing?

**Comment by katre** [comment]
Paging @philwo: can we install patch on the BazelCI windows images?

**Comment by philwo** [comment]
It should already be installed: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-windows.ps1#L108

We don't currently put the MSYS2 stuff on the PATH though. Maybe we didn't do so to discourage Windows builds from using these tools unless absolutely and explicitly required, but I don't remember.

@meteorcloudy WDYT?

**Comment by katre** [comment]
That's odd that it wasn't found, then.

**Comment by katre** [comment]
If we can fix this without a Bazel update, I'd prefer that.

**Comment by meteorcloudy** [comment]
Another solution is that we can install patch through `choco` the Windows package manager
https://chocolatey.org/packages/patch

FYI @aehlig @dslomov I'll leave the external dependency team to decide how to make `patch` command work on Windows.

**Comment by jayconrod** [comment]
@meteorcloudy I tried choco's patch earlier, but I wasn't able to make it work. It pops up a UAC screen asking for administrative privilege. I don't think patch should need to run as admin.

**Comment by meteorcloudy** [comment]
Oh, indeed. @philwo Can we set environment variable for a specific project on CI?
Looks like the only workaround before a new Bazel release is adding bash bin tools path into `PATH` env var.

**Comment by philwo** [comment]
I don't think we can currently do that, but I'll prepare Windows images with MSYS2 on the PATH. Let's see how that goes.

**Comment by katre** [comment]
Thanks, let me know if you need me to help test.

**Comment by philwo** [comment]
New images with Msys2 on the PATH have been rolled out to Buildkite. In theory it should now just work where it failed before the change. If not, I think we might have to actually change Bazel.

Could you please test this by rerunning the jobs you were looking at? :)

**Comment by meteorcloudy** [comment]
Thanks, Philipp! 
@katre Now it's failing with a different error:
```
java.io.IOException: Error downloading [https://dl.google.com/go/go1.11.1.windows-amd64.zip] to C:/users/b/_bazel_b/hbkjbo3d/external/go_sdk/go1.11.1.windows-amd64.zip: Checksum was 604c75fbf909b4fcdbb39116edb7d1ef200d57b6e5e3b3aef58857c79f7745a1 but wanted 230a08d4260ded9d769f072512a49bffe8bfaff8323e839c2db7cf7c9c788130
```
https://buildkite.com/bazel/rules-typescript-typescript/builds/752#61996da6-9870-4cdf-9b49-364171b311b9

**Comment by philwo** [comment]
Interesting. Looks like the hash mentioned in the WORKSPACE should be correct:

```
philwo@philwo-imacpro ~/Downloads curl -sSLO https://dl.google.com/go/go1.11.1.windows-amd64.zip
philwo@philwo-imacpro ~/Downloads shasum -a256 go1.11.1.windows-amd64.zip 
230a08d4260ded9d769f072512a49bffe8bfaff8323e839c2db7cf7c9c788130  go1.11.1.windows-amd64.zip
```

Not sure why it failed and gave a wrong hash. Maybe the download was interrupted?

**Comment by philwo** [comment]
Looks like that was a flake, now it's failing with `/usr/bin/bash: patch: command not found` again. :|

**Comment by meteorcloudy** [comment]
Hmm,, I logged into a CI Windows machine, the MSYS bin tools path doesn't seem to be added.
```
C:\Users\pcloudy>echo %PATH%
C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;c:\openjdk\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;c:\ninja;c:\bazel;c:\buildkite;C:\Users\pcloudy\AppData\Local\Microsoft\WindowsApps;

C:\Users\pcloudy>patch
'patch' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\pcloudy>
```

**Comment by philwo** [comment]
Mhm... maybe the Chocolatey package doesn't add that folder to the PATH. :|

I guess we could add it manually. @meteorcloudy could you send me the full path to the bin folder?

**Comment by meteorcloudy** [comment]
I guess so, it should be `C:\tools\msys64\usr\bin`

**Comment by katre** [comment]
Have there been any further work to deal with this? It's currently at the end of a long trail of blocking work that's stopping me from rolling forward several Bazel changes.

**Comment by meteorcloudy** [comment]
Sorry for that, I tried to log into the machines and manually change the `PATH` environment variable. But that doesn't affect the CI. We'll have to wait for the Windows slaves to be recreated with `C:\tools\msys64\usr\bin`

**Comment by philwo** [comment]
The good news: The "rm not found" error no longer seems to happen with the new images! 🎉
The bad news: Now your build crashes Bazel with an internal error and a stack trace referring to a checkState preconditions failure in com.google.devtools.build.lib.rules.cpp. 😭

@meteorcloudy might have some ideas about this.

Log: https://buildkite.com/bazel/rules-go-golang/builds/774#9f499b09-e235-482c-93e1-82f50a64425f

**Comment by meteorcloudy** [comment]
@philwo Thanks for the new images!
The new issue is due to https://github.com/bazelbuild/bazel/issues/6292, we'll have to upgrade bazel to 0.18.1 or 0.19.0 after they come out.

**Comment by meteorcloudy** [comment]
@katre The PR for rules_typescript seems to be passing on Windows now:
https://buildkite.com/bazel/rules-typescript-typescript/builds/749#_

**Comment by katre** [comment]
Thank you!
