### ISSUE TITLE
bazel coverage fails for go_test rules with attribute race="on"

### ISSUE THREAD

**Issue by dan-compton** [bazelbuild/rules_go#1801]
For rules `bazel query attr(race, "on", kind(go_test, //...))` `bazel coverage` will fail due to (I assume) lack of CGO support.   

```
 && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOROOT=bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_race_stripped/stdlib% \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \

...

-- -extld /usr/bin/gcc -race '-buildid=redacted' -w -extldflags '-fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -lm --coverage --coverage')

runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.text): relocation target __gcov_init not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.data.rel): relocation target __gcov_merge_add not defined
runtime/cgo(.text): undefined: "__gcov_init"
runtime/cgo(.text): undefined: "__gcov_init"
runtime/cgo(.text): undefined: "__gcov_init"
runtime/cgo(.text): undefined: "__gcov_init"
runtime/cgo(.text): undefined: "__gcov_init"
```

As a workaround I'm currently using `bazel query 'kind(go_test, //...) - attr(race, "on", kind(go_test, //...))`, but am considering using buildozer to re-write the test tags at build time.  It would be useful if rules_go either skipped and logged or covered without without race detection enabled, though I assume the later would be less desirable in general.

**Comment by jayconrod** [comment]
Marking as a bug, but I couldn't actually reproduce this. What version of Bazel are you using? What version of rules_go? Anything unusual about your C/C++ toolchain? If you can put together a small example that reproduces this as a gist or a repo, that would be helpful.

About `race = "on"`, I'd recommend using `--features=race` instead if possible. However, it's not clear that would work around this problem.

**Comment by dan-compton** [comment]
https://github.com/dan-compton/repro_rules_go_issue_1801


```
Linux _ 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
Build label: 0.18.0
Build time: Mon Oct 15 08:33:18 2018 (1539592398)
Build timestamp: 1539592398
Build timestamp as int: 1539592398
```

```
rules_go_release = "0.16.0"
rules_go_sha = "ee5fe78fe417c685ecb77a0a725dc9f6040ae5beb44a0ba4ddb55453aad23a8a"
```

```
g++                                           4:5.3.1-1ubuntu
g++-5                                         5.4.0-6ubuntu1~16.04.11
gcc                                           4:5.3.1-1ubuntu1
gcc-5                                         5.4.0-6ubuntu1~16.04.11
gdc                                           4:5.3.1-1ubuntu1
gdc-5                                         5.4.0-6ubuntu1~16.04.11
hardening-includes                            2.7ubuntu2
libantlr-java                                 2.7.7+dfsg-6ubuntu1
libecj-java                                   3.10.1-2ubuntu1
libllvm3.8:amd64                              1:3.8-2ubuntu4
libllvm6.0:amd64                              1:6.0-1ubuntu2~16.04.1
libllvm6.0:i386                               1:6.0-1ubuntu2~16.04.1
libluajit-5.1-2:amd64                         2.0.4+dfsg-1
libluajit-5.1-common                          2.0.4+dfsg-1
libplexus-archiver-java                       2.2-1
libprotoc-dev:amd64                           3.1.0-0ubuntu1~maarten0
libprotoc10:amd64                             3.1.0-0ubuntu1~maarten0
libxkbcommon-dev                              0.5.0-1ubuntu2.1
libxkbcommon0:amd64                           0.5.0-1ubuntu2.1
nuitka                                        0.6.0.6+ds-1
protobuf-compiler                             3.1.0-0ubuntu1~maarten0
```

# The following works (addition of -linkshared)
`bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/link -sdk external/go_sdk -installsuffix linux_amd64_race -tags race -arc '@io_bazel_rules_go//go/tools/coverdata:coverdata=github.com/bazelbuild/rules_go/go/tools/coverdata=bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/go/tools/coverdata/linux_amd64_race_stripped/coverdata%/github.com/bazelbuild/rules_go/go/tools/coverdata.a' -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/k8-fastbuild/bin/1801/linux_amd64_race_stripped/1801 -main bazel-out/k8-fastbuild/bin/1801/linux_amd64_race_stripped/1801%/github.com/dan-compton/repro_rules_go_1801/1801.a -- -extld /usr/bin/gcc -race '-buildid=redacted' -w -extldflags '-fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -lm --coverage --coverage' --linkshared`

**Comment by dan-compton** [comment]
Adding cgo=true in the `go_test` rule fixes this.

**Comment by dan-compton** [comment]
I can reproduce this in our monorepo, but haven't been able to repro it outside of the monorepo.  I'll reopen this if I can repro.

**Comment by jayconrod** [comment]
I was able to reproduce this with the example you provided, so reopening. Thank you for putting that together.

Some folks in the Kubernetes slack mentioned a very similar error, so this may be more widespread.

From an initial look, it seems we're pulling in `runtime/cgo`, and something in there is referencing gcov functions, but we're not doing an external link with gcov libraries. There are several things that don't seem right about that.

Investigating further...

**Comment by dan-compton** [comment]
> I was able to reproduce this with the example you provided, so reopening. Thank you for putting that together.


Glad to hear it.  Strange thing is that I was able to repro it initially, but couldn't later so I decided that the example was probably flawed.  Thanks for the fix!
