### ISSUE TITLE
How to "replace the string after prefix with the prefix you chose for your project" in BUILD.bazel?

### ISSUE THREAD

**Issue by zwl1619** [bazelbuild/rules_go#1806]
the docs says:  https://github.com/bazelbuild/rules_go#generating-build-files

> Add the code below to the BUILD or BUILD.bazel file in the root directory of your repository. Replace the string after prefix with the prefix you chose for your project earlier.
> 
> load("@bazel_gazelle//:def.bzl", "gazelle")
> 
> \# gazelle:prefix github.com/example/project
> gazelle(name = "gazelle")

My project is `D:\workspace\www\go_work\go_learning`,how to replace the string after prefix?

**Comment by jayconrod** [comment]
You can change the prefix just by editing the build file.

When you run Gazelle, it joins this prefix with a subdirectory path to generate `importpath` attributes for `go_library` rules. For example, if your top-level build file is `D:\workspace\www\go_work\go_learning\BUILD.bazel`, and you set the prefix to `example.com/go_learning`, and you have a subdirectory with .go files, `D:\workspace\www\go_work\go_learning\experimental\server`, when you run `bazel run //:gazelle`, it will generate the file `D:\workspace\www\go_work\go_learning\experimental\server\BUILD.bazel` that looks something like this:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["server.go"],
    importpath = "example.com/go_learning/experimental/server",
    visibility = ["//visibility:public"],
)
```

Other libraries can import that library using the `importpath` string.

```
package main

import "example.com/go_learning/experimental/server"
```
