### ISSUE TITLE
Expand coverage of new_go_repository to include other repo types

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#181]
Because of restrictions on internet access on some of my org's build agents, it's harder to build go packages with Bazel than I would like.

Can we get support for downloading new_go_repositories as:

- http_archive()
- local_repository()
- git_repository() from git location not matching importpath.

Thanks!

**Comment by ianthehat** [comment]
As of #446 new_go_repository has been deprecated, go_repository now covers all these use cases directly.
Please feel free to reopen this issue and let me know if it does not do what you need.
