### ISSUE TITLE
Bazel tries to build cgo targets for *all* architectures when using rules_go + cgo + action listeners

### ISSUE THREAD

**Issue by justbuchanan** [bazelbuild/rules_go#1821]
We initially ran into this issue with the [kythe](https://github.com/kythe/kythe) project where we use bazel's extra actions feature for extracting compilation info. I've narrowed it down to a minimal example in this gist: https://gist.github.com/justbuchanan/29d611e4a3cf46b3624a4d6a3ea2832c.

From what I understand, when dealing with a cgo-enabled target, rules_go adds a dependency for each supported architecture and later selects only one of those to actually be built. However, when using extra actions, bazel attempts to build *all* of these architecture-specific targets. The result is that a `bazel build` works correctly, but a `bazel build --experimental_action_listener=//:my_action_listener` fails when it attempts to build targets for arm, mips, etc on my amd64 machine.

I'm not sure if this is a bug in rules_go or bazel aspects or if we should be forcing the action listener to be more specific about which targets it applies to. Any thoughts?

cc @schroederc

**Comment by jayconrod** [comment]
I'm not familiar with `--experimental_action_listener`, but this seems like a bug in that feature, not rules_go. Have you brought this up with the Bazel folks?

Unfortunately, rules_go is working as intended here. When cgo is turned on, we use a macro to stitch together a graph of `cc_library`, `go_library` and various internal rules. We support cross-compilation using an aspect, and the aspect needs to propagate through that graph. We don't actually build targets for platforms other than the target platform (there isn't a chain of dependencies in the action graph). If the action listener is causing additional actions to be executed, that seems like a bug.

At some point after the Starlark Build Configuration proposal is implemented, I intend to rewrite both cgo and cross-compilation support. Hopefully that will avoid this problem.

**Comment by justbuchanan** [comment]
Thanks for the pointers. I think you're right that this is a bug in `--experimental_action_listener` - I'll open a bug on the bazel repo.

In the meantime, we're able to work around this by adding the
` --experimental_extra_action_top_level_only` flag.
