### ISSUE TITLE
Runfile dependency on go-protoc-gen causes linking conflict

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1824]
We are using 0.16.0 ATM, in a go_binary rule, we use `@com_github_golang_protobuf//protoc-gen-go` as runfile.

```
go_binary(
    name = "protoc-gen-youzan",
    data = ["@com_github_golang_protobuf//protoc-gen-go"],
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

However, this causes linking warning:

> GoLink: warning: package "github.com/golang/protobuf/protoc-gen-go/descriptor" is provided by more than one rule:
>     @com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library
>     @io_bazel_rules_go//proto/wkt:descriptor_go_proto
> Set "importmap" to different paths in each library.
> This will be an error in the future.
> GoLink: warning: package "github.com/golang/protobuf/protoc-gen-go/plugin" is provided by more than one rule:
>     @com_github_golang_protobuf//protoc-gen-go/plugin:go_default_library
>     @io_bazel_rules_go//proto/wkt:compiler_plugin_go_proto
> Set "importmap" to different paths in each library.
> This will be an error in the future.

**Comment by jayconrod** [comment]
I don't have enough information to reproduce this. In particular, I'd need to know what that `go_default_library` rule looks like. Would you mind posting a minimal gist or test repo that demonstrates this?

I don't think `data = ["@com_github_golang_protobuf//protoc-gen-go"]` should cause this. The conflict may be coming from somewhere else. You should probably not have `@io_bazel_rules_go//proto/wkt:descriptor_go_proto` in your dependency graph (or any other `go_proto_library`). Note that Gazelle will resolve imports of known proto libraries to `go_proto_library` targets automatically. You'll probably want to add `# gazelle:proto disable` to the build file for this package to prevent that.

**Comment by ashi009** [comment]
Sorry for the noise. After digging into this, it turned out that, this was due to grpc-gateway dependency, as they have BUILD files in the repo and they are referring to the wrong ones.

Closing as WAI.
