### ISSUE TITLE
name '_go_repository_attrs' is not defined

### ISSUE THREAD

**Issue by rmgogogo** [bazelbuild/rules_go#184]
go_repository.bzl", line 106, in repository_rule
		_go_repository_attrs
name '_go_repository_attrs' is not defined.

**Comment by pcj** [comment]
Can you clarify the problem you're having?  It's defined at line 55.

https://github.com/bazelbuild/rules_go/blob/master/go/private/go_repository.bzl#L55-L67

**Comment by pmbethe09** [comment]
We can't help you without precise reproduction instructions.
