### ISSUE TITLE
Depending on two go_proto_library's with same import path not working

### ISSUE THREAD

**Issue by draffensperger** [bazelbuild/rules_go#1841]
I'm running into an issue where I have two `go_proto_library` rules that share the same `importpath`, but come from different `.proto` files. Then when I try to use both of them in a third `go_proto_library`, I get a compiler error saying one of the two dependent messages is undefined in the import path.

For more context, see https://github.com/census-instrumentation/opencensus-proto/pull/154#discussion_r238816282

**Comment by jayconrod** [comment]
Could you try referencing the other `go_proto_library` targets with `embed = [...]` instead of `deps = [...]`? `embed` will combine the generated sources into an archive that is compiled with one compile action. `deps` requires targets to be separate archives with distinct package paths.

**Comment by draffensperger** [comment]
So in my case, I have `trace_proto_go` and `trace_config_proto_go` that are both `go_proto_library` rules and have the same import path. However, the `go_proto_library` that depends on them both (`trace_service_proto_go`) is in a different import path. When I tried using only `embed` in its build rule I get an error for missing dependencies. When I specify them in `deps` and also use `embed`, I get a [compile error](https://travis-ci.org/census-instrumentation/opencensus-proto/jobs/464032876) for trying to import the package that has `trace_proto_go` and `trace_config_proto_go`.

A workaround for me is to create a combined `proto_library` for both protos called say `trace_and_config_protos` that includes both protos in `srcs` and then a combined `go_proto_library` that depends on it. Then I can depend on that single combined `go_proto_library` that has both protos. That does work, but I wanted to confirm that is needed before I do that since it feels like it ideally wouldn't be needed.

**Comment by jayconrod** [comment]
The workaround you suggest is probably what I'd recommend, given the current state of `go_proto_library`. Usually, there's a clearer relationship between proto packages, Go packages, `proto_library` targets, and `go_proto_library` targets.

I don't know whether this would work, but you might be able to define a `go_library` that embeds both `go_proto_library` target, and then depend on the `go_library` from `trace_service_proto_go`. It's possible some metadata will get lost in translation there, but maybe worth a try.

**Comment by draffensperger** [comment]
Thanks, that works! I was able to create a `go_library` with `srcs = []` and `embed = ["trace_proto_go", "trace_config_proto_go"]` and successfully depend on it from the `trace_service_proto_go` with no errors. That feels slightly cleaner than creating extra `proto_library` and `go_proto_library` rules.

**Comment by strican** [comment]
As far as I can tell, this renders [gazelle's instructions](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#option-1-use-go-proto-library-exclusively) useless.

Here's an [example repo](https://github.com/strican/test-protos) I set up with gazelle rules. It clearly auto-generates multiple `go_proto_library` definitions with the same `importpath` ([seen here](https://github.com/strican/test-protos/blob/master/api/common/BUILD)). However, it gives the error described in this thread.

So is there a fix for this in the works, or should this issue be raised in the gazelle repo for them to adopt this workaround as standard?

**Comment by jayconrod** [comment]
The protos in your example don't have `option go_package` set, so the package name will be inferred automatically. When run from the repo root, protoc infers the package names to be `api_common_foo`, `api_common_bar`, and `api_common_baz`. These can't be compiled together into the same package.

Gazelle can't generate correct rules for these without using distinct `importpaths`. I don't think it should do that without explicit input from the user. However, generating rules that don't work isn't desirable either. It should probably print an error instead and not generate anything. I've opened bazelbuild/bazel-gazelle#504 for this.

**Comment by strican** [comment]
Thanks. Question though - importpath seems to have the same effect and can be set without setting the go_package option. Are both necessary? Can one override the other?

**Comment by jayconrod** [comment]
`importpath` is the string by which a library is imported by other Go libraries. When we compile or link a Go package, we generate a file that maps these strings to filenames. Gazelle generates the `importpath` by concatenating a prefix and a directory path.

`option go_package` can be used to set the Go package name (the `package` declaration at the top of .pb.go files) or the import path (as written in other generated .pb.go files that import the containing .proto) or both.

If `importpath` and `option go_package` don't match, I think it may break other `go_proto_libraries` that depend on the conflicting `go_proto_library`. We should have better diagnostics for this. There already be an override for that somewhere though.
