### ISSUE TITLE
nogo: .x file is not written when cgo is enabled

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_go#1846]
I just updated rules_go to the currently latest commit `e56822c37c2f3d4e6aff7937b570e9db9ab753ff` and now building `autogazelle` is broken:

```
(09:34:18) INFO: Analysed target @bazel_gazelle//cmd/autogazelle:autogazelle (29 packages loaded, 6820 targets configured).
(09:34:18) INFO: Found 1 target...
(09:34:18) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/bazel_gazelle/vendor/golang.org/x/sys/unix/BUILD.bazel:3:1: output 'external/bazel_gazelle/vendor/golang.org/x/sys/unix/linux_amd64_stripped/go_default_library%/github.com/bazelbuild/bazel-gazelle/vendor/golang.org/x/sys/unix.x' was not created
(09:34:18) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/bazel_gazelle/vendor/golang.org/x/sys/unix/BUILD.bazel:3:1: not all outputs were created or valid
Target @bazel_gazelle//cmd/autogazelle:autogazelle failed to build
```

I also tried the latest official `rules_go` release (`0.16.3`) and I also tried updating the gazelle repo to the latest commit. In fact it seems commit https://github.com/bazelbuild/rules_go/commit/c751b20374e4d762a902ffc3a7c99d44dbf22e4b breaks the build of autogazelle.

**Comment by jayconrod** [comment]
#1848 should fix this. Sorry for the break.

I expect to push this out with a bugfix release before the end of the year.

**Comment by Globegitter** [comment]
Thanks for the quick fix.
