### ISSUE TITLE
go_proto_library: support multiple proto dependencies

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1856]
`go_proto_library` currently generates .pb.go files from a single `proto_library` target, referenced with the `proto` attribute. This does not work well when there are multiple `proto_library` targets for the same package (e.g., one `proto_library` per .proto file).

The `proto` attribute should be replaced with a `protos` attribute that accepts a list of labels.

A wrapper macro may be used to migrate users of the old `proto` attribute until it is deprecated and removed.

**Comment by vam-google** [comment]
@jayconrod can you please assign this to me?

**Comment by jayconrod** [comment]
GitHub won't let me assign to anyone outside the bazelbuild org. But let's proceed as if you're assigned. :)
