### ISSUE TITLE
docker sandbox failure

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_go#1863]
I am just experimenting with docker sandboxing and getting the following error on running some of our integration tests:

```
...
(14:55:22) INFO: Docker sandboxing is supported
(14:55:26) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/com_github_ory_dockertest/docker/pkg/mount/BUILD.bazel:3:1: undeclared inclusion(s) in rule '@com_github_ory_dockertest//docker/pkg/mount:go_default_library%linux_amd64%cgo_c_lib':
this rule is missing dependency declarations for the following files included by 'external/com_github_ory_dockertest/docker/pkg/mount/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_export.c':
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h'
Target //app/db:go_default_test failed to build
```

I am using the following config:
```
build:docker --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=0
build:docker --experimental_docker_image=golang:latest
build:docker --spawn_strategy=docker
build:docker --strategy=Javac=docker
build:docker --strategy=Closure=docker
build:docker --genrule_strategy=docker
build:docker --define=EXECUTOR=remote
build:docker --experimental_docker_verbose
build:docker --experimental_enable_docker_sandbox
```

The dependency I am getting the error about is: https://github.com/ory/dockertest and we are using the following version:

```
go_repository(
    name = "com_github_ory_dockertest",
    importpath = "github.com/ory/dockertest",
    tag = "v3.3.2",
)
```

If that is not enough I am happy to provide a repro.

Edit: Also just getting another one

```
(15:24:00) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/org_golang_x_sys/unix/BUILD.bazel:3:1: undeclared inclusion(s) in rule '@org_golang_x_sys//unix:go_default_library%linux_amd64%cgo_c_lib':
this rule is missing dependency declarations for the following files included by 'external/org_golang_x_sys/unix/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_export.c':
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h'
Target //heimdall/client-go:go_default_test failed to build
```

and that dep is

```
go_repository(
    name = "org_golang_x_sys",
    commit = "73d4af5aa059",
    importpath = "golang.org/x/sys",
)
```

**Comment by jayconrod** [comment]
This sounds like a problem with CROSSTOOL. Something generated by cgo expects `/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h` to be available in the sandbox as an input. 

Is this build supposed to be without a C compiler? If yes, I think you'll need to add `--features=pure` to your configuration, which will disable cgo. If no, your CROSSTOOL will need something like `cxx_builtin_include_directory: "/usr/lib/gcc/x86_64-linux-gnu/6"` to make that directory available.

**Comment by Globegitter** [comment]
Ahh, so that could be an issue with the dockerfile used not having gcc then? Tbh I am not entirely sure what the docker image has to contain and what will be provided "hermetically". But adding `--features=pure` does indeed fix the issue. I have also not been able to find much documentation on this (which I suppose would then also be true for remote build execution.) 

In any case thanks for that fix here at hand.
