### ISSUE TITLE
Go rule to install binary

### ISSUE THREAD

**Issue by PranavSathy** [bazelbuild/rules_go#187]
It would be awesome if there was "install" attribute or something on the go_binary rule, which will install the compiled binary if it was successfully compiled. That way after compiling my binary, I can use it in the command line directly.

**Comment by pmbethe09** [comment]
Reasonable idea, but the problem is: bazel runs using its own downloaded
Go, and its actions intentionally run in a sandbox to enforce hermeticity.
So by design bazel has no way to "install" the built software.  Instead it
is left up to some sort of wrapping process to complete the installation.

**Comment by PranavSathy** [comment]
@pmbethe09 Ah I see, is there any way to have a genrule then that executes a go_binary (and triggers a build if it has not already been built?).

**Comment by pmbethe09** [comment]
Sure, add the go_binary target path in the tools section of the genrule
(that ensures that it is built for "host" configuration).
Then use it via $(location ...)
https://bazel.build/versions/master/docs/be/general.html#genrule

go_binary(name="something", ....)

genrule(name="other", srcs = ..., outs = ...,
tools = [":something"], cmd = "$(location :something) ...")

**Comment by PranavSathy** [comment]
Awesome, thanks @pmbethe09
