### ISSUE TITLE
go_library fails to link shared library created by cc_binary

### ISSUE THREAD

**Issue by robin-thomas** [bazelbuild/rules_go#1871]
### Description
Currently, if any of the dependencies of `go_library` in `cgo` mode are not cc_library, objc_library, cc_proto_library or cc_import, it fails the build.

But in the case of external dependencies which are unable to use `cc_library` to bundle all its transitive dependencies (because of https://github.com/bazelbuild/bazel/issues/492), they need to use `cc_binary` to create a *.so shared library.

### Expected outcome
`go_library` should support linking shared libraries even if they are created by `cc_binary`.

### Bazel version
> 0.20.0

### OS version
> Ubuntu 16.04

**Comment by jayconrod** [comment]
Are you able to use `cc_import` for this? I think that's supposed to be the tool to solve this problem.

For example, this works for me (but I'm not sure it's suitable for anything more than this trivial case):

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

cc_binary(
    name = "libhello.so",
    srcs = ["hello.c"],
    linkshared = True,
)

cc_import(
    name = "hello",
    shared_library = ":libhello.so",
)

go_binary(
    name = "gello",
    srcs = ["gello.go"],
    cdeps = [":hello"],
    cgo = True,
)
```
