### ISSUE TITLE
Support subpackages in `new_go_repository`

### ISSUE THREAD

**Issue by kerinin** [bazelbuild/rules_go#188]
In many cases the import path and the source repository is not the same, for instance 

* `github.com/golang/protobuf/proto`
* `golang.org/x/net/context`
* `golang.org/x/net/http2`
* `golang.org/x/text/encoding`
* `google.golang.org/grpc/credentials`

Adding one of these with `new_go_repository` currently causes an error:

```
ERROR: .../BUILD:3:1: no such package '@x_net_context//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_rmichael/c50984a7f41b3a8568653b89ff33eb26/external/io_bazel_rules_go/go/private/go_repository.bzl", line 40
		_go_repository_impl(ctx)
	File "/private/var/tmp/_bazel_rmichael/c50984a7f41b3a8568653b89ff33eb26/external/io_bazel_rules_go/go/private/go_repository.bzl", line 36, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx....))
failed to fetch golang.org/x/net/context: 2016/11/04 14:54:35 get "golang.org/x/net/context": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
2016/11/04 14:54:35 get "golang.org/x/net/context": verifying non-authoritative meta tag
2016/11/04 14:54:35 not a root of a repository: golang.org/x/net/context
 and referenced by '//lib/cntx:go_default_library'.
ERROR: Analysis of target '//lib/cntx:go_default_library' failed; build aborted.
INFO: Elapsed time: 1.620s
```

**Comment by pmbethe09** [comment]
This already works, maybe the documentation needs to be better?

The key here, is the new_go_repository needs to reference the import path for the repository, not the complete import path.

So for 
import "golang.org/x/net/context"

gazelle will generate a dependency on
"@org_golang_x_net//context:go_default_library"

and finally you need a WORKSPACE entry for the org_golang_x_net repo which might look like:

new_go_repository(
    name = "org_golang_x_net",
    commit = "55a3084c9119aeb9ba2437d595b0a7e9cb635da9",
    importpath = "golang.org/x/net",
)

**Comment by kerinin** [comment]
Thank you!  I think the part that was unclear was the subpackage import syntax (`..//context:go_default_library`)

**Comment by pmbethe09** [comment]
If you use gazelle to generate your BUILD files, the break between repository and path should become clearer.
