### ISSUE TITLE
--features=norace doesn't override --features=race in .bazelrc

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_go#1881]
The documentation for bazel indicates that the negative feature flag should always override the positive flag, yet this doesn't seem to be the case with rules_go.

**Comment by prestonvanloon** [comment]
It looks like `--features=norace` doesn't work at all with bazel coverage. It still use the `race = "on"` attribute rather than respecting the `norace` feature.

**Comment by jayconrod** [comment]
Closing old issues. Sorry I never responded to this. `--features=race` is no longer supported. `--@io_bazel_rules_go//go/config:race` is the new way to set that.
