### ISSUE TITLE
workspace names in go_rules_dependencies

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#1886]
Should rules_go be using different workspace names for the repositories it defines in `go_rules_dependencies`?

gazelle generates the same names for external repositories, and so there can only be one version of the external dependency. We would like to keep ours, but are forced to use the ones coded in rules_go.

**Comment by jayconrod** [comment]
It's best to avoid depending on the same repository with multiple names. This can cause conflicts if multiple copies of a library with the same `importpath` are included in a build.

You can safely override the dependencies declared by `go_rules_dependencies` by declaring them in WORKSPACE. See [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies). 

I think `gazelle update-repos` will add `go_repository` rules to your WORKSPACE, even if they're declared by default in `go_rules_dependencies`. That behavior could probably be improved, but it's probably better than not adding the repositories at all (if the user wants to update to a specific version or just wants to be explicit about the dependency).

**Comment by siddharthab** [comment]
The problem is with additional patches that rules_go has for org_golang_x_tools, and com_github_golang_protobuf. These patches are required, and they may not apply on our versions.

My thought was that we could enforce that the users don't depend on any go_library within rules_go using visibility. And that way, the user's build is isolated from the libraries used by rules_go. The only way multiple copies will exist in the same build is if the user explicitly depends on a workspace that rules_go has named as its internal dependency.

**Comment by jayconrod** [comment]
I think it would be much, much easier to resolve any differences with the patches. Most of the content of those patches is just the result of running Gazelle (the `-gazelle.patch` files are there to avoid rules_go depending on Gazelle). The additional changes are pretty minor. You may even be able to use `go_repository` (running Gazelle automatically) and apply the non-Gazelle patch files in third_party (`go_repository` supports the same patch functionality as `http_archive`).

The one exception is `@go_googleapis`; the owners of `github.com/googleapis/googleapis` are working on Bazelifying that, so we'll migrate to that eventually.

**Comment by siddharthab** [comment]
That is what I ended up doing. I was just a little bit nervous applying a patch to a different base, but it works for now. I think I can close this now. Thank you so much for always replying so quickly and being so reliable. 👍
