### ISSUE TITLE
gazelle: handle case of go_proto_library and also checked in generated files

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#189]
Some projects might try and stay "Go-compatible", and check-in the .pb.go files, but for bazel use a go_proto_library (whether from here or pubref).

When merging the new and old, gazelle should drop the new go_library and filegroup if it detects a go_proto_library(name="go_default_library")

**Comment by jayconrod** [comment]
Closing old Gazelle issues. If Gazelle isn't doing something you want, please open a new issue at https://github.com/bazelbuild/bazel-gazelle.

We now use a `-proto` argument or directive to decide what rules to generate. The `fix` command can convert old rules to the new scheme.
