### ISSUE TITLE
Unable to fetch/use Go 1.12b1 due to missing env

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#1892]
It fails with the following error:
```
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@<CENSORED>//go': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined
```

**Comment by jayconrod** [comment]
Thanks for reporting this! I hadn't expected 1.12 to be such a big upgrade, but a lot of changes are necessary.

I'm closing this issue as fixed, since bazelbuild/bazel-gazelle#419 fixed this specific problem. #1896 will be the catch-all issue for all the other problems I found.
