### ISSUE TITLE
Support Go 1.12 symabis

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1893]
Go 1.12 now requires the build system to pass `-gensymabis` to the assembler to generate a symabis file, then pass that file to the compiler with `-symabis`.

Not doing this causes failures like this:

```
github.com/bazelbuild/rules_go/tests/build_constraints.TestAsm: relocation target github.com/bazelbuild/rules_go/tests/build_constraints.asm not defined for ABIInternal (but is defined for ABI0)
GoLink: error running subcommand: exit status 2
```

For reference:

* [CL 146999](https://go-review.googlesource.com/c/go/+/146999)
* [CL 149818](https://go-review.googlesource.com/c/149818)

**Comment by robfig** [comment]
@jayconrod is this issue still relevant?

**Comment by jayconrod** [comment]
It looks like we're passing those flags, so I think this is fixed.

(Thanks for going through these old issues by the way!)
