### ISSUE TITLE
Define GOOS_<goos> and GOARCH_<goarch> for assembly

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1894]
`go build` does this. We should, too.

Example:

```
/opt/go1.12beta1/pkg/tool/linux_amd64/asm -trimpath $WORK/b001 -I $WORK/b001/ -I /opt/go1.12beta1/pkg/include -D GOOS_linux -D GOARCH_amd64 -o $WORK/b001/foo.o ./foo.s
```

**Comment by eugene-dounar** [comment]
Cannot build https://github.com/thrift-iterator/go due to this limitation. On of it's dependencies (https://github.com/v2pro/plz) relies on GOARCH_<goarch>
