### ISSUE TITLE
Build changes needed to support Go 1.12

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1896]
This is a catch-all issue for 1.12 related changes.

* [ ] Deprecate `go_vet_test` and direct usage of `vet` in `nogo` because `go tool vet` no longer works. `nogo(vet = True)` should use the analysis framework instead of invoking vet.
* [x] Generate symabis files for packages with assembly. The assembler now requires this.
* [x] Ensure cgo .o files in archives don't have their extensions truncated. The linker will no longer blindly link files.
* [x] Create a cache directory and set `GOCACHE` when building the standard library.
* [ ] Update to a newer Gazelle that can build `fetch_repo` and `gazelle` correctly (needed for tests).
* [x] Fix or disable tests that rely on removed features.

**Comment by robfig** [comment]
@jayconrod good to close this out?

**Comment by jayconrod** [comment]
Yep this can be closed.
