### ISSUE TITLE
Include info from @io_bazel_rules_go//:go_info in workspace status

### ISSUE THREAD

**Issue by gebn** [bazelbuild/rules_go#1907]
I'd like to stamp my binaries with the version of Go used to build them. I'm already using `x_defs` (a really handy feature!), however I can't see a sane way to run `bazel build @io_bazel_rules_go//:go_info` in my `--workspace_status_command` (I set this flag in `.bazelrc`, so presumably there would be infinite recursion). Is there a recommended way of getting info from `go_info_report` into the workspace status so variables can be substituted as normal?

**Comment by jayconrod** [comment]
Could you use [`runtime.Version()`](https://godoc.org/runtime#Version) instead?

The most practical way to get the Go version into `x_defs` would probably be for `go_sdk` to declare a version and for the linker action to make that available to `x_defs`. `runtime.Version` seems a lot more straightforward to me though.

**Comment by gebn** [comment]
Ah of course - it didn't occur to me that these would be equivalent! Thanks.

Moving the goalposts slightly, how about other information in `go_info_report`, like the compiler used, which isn't available from `runtime`?

**Comment by jayconrod** [comment]
At the moment, the only compiler we support is `gc`, the Go compiler that ships with the SDK. We may support others in the future, but that would be done through toolchains, and it would be up to toolchains whether / how they want to expose identifying information when linking.

For the rest of the information in `go_info`, this is mostly just the result of running `go env`. There's a lot of stuff in here that would break reproducibility (i.e., you might see a different sandbox directory in `GOROOT` every time you link).

Could you say more about the problem you're trying to solve? Much of the information in `go_info` isn't actually relevant to how rules_go builds things, so I want to check if there's a better way to get the information you need.

**Comment by gebn** [comment]
Besides the Go version, it was really just out of curiosity - I noticed `kubectl` displays this kind of info, and wondered if there was an equivalent:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:17:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

I've actually *just* realised this is [nothing special](https://github.com/kubernetes/kubernetes/blob/9c48ca48998ac0070990667259594b529facf4ca/pkg/version/version.go#L39) - I was wrong about the compiler not being available in `runtime`. `kubectl` [uses `x_defs`](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/cmd/kubectl/BUILD#L13) for [the other](https://github.com/kubernetes/kubernetes/blob/master/pkg/version/def.bzl) fields.

I'll close this issue. Thanks for your help!
