### ISSUE TITLE
wtool: check for existence of a repo, allow custom tags

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#191]
The almost submitted logic is:
 for a repo named 'com_github_golang_glog' 
determine the import path and add an entry 
new_go_repository(name="com_github_golang_glog", importpath="github.com/golang/glog", commit = ...)
where commit equals the current HEAD by doing essentially 
'git ls-remote https://github.com/golang/glog HEAD'

Future work: if com_github_golang_glog:some_tag is used, ensure that is a valid tag and then use it instead of HEAD.
Future work: check for the existence of this repo, and either skip, or update the commit/tag as driven by flags.

**Comment by ianthehat** [comment]
This is now deprecated, in favour of gazelle editing the workspace with full merging logic.
See bazelbuild/bazel-gazelle#47 for the new update-repos command
