### ISSUE TITLE
security releases 1.11.5 and 1.10.8 on Weds Jan 23rd

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1911]
The Go team has announced a security release coming out on Weds January 23rd around 8 PM UTC/12 PM PT/3 PM ET. See https://groups.google.com/forum/#!topic/golang-announce/yzoslEVBvIs

New versions will be 1.11.5 and 1.10.8

**Comment by jayconrod** [comment]
I'll put out a new rules_go point release with support for these soon after they're published.

**Comment by jmhodges** [comment]
Done long ago!
