### ISSUE TITLE
Unexpected file collision when generating go_path

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/rules_go#1916]
While writing some rules for myself on top of rules_go I came across, what I suspect is, a bug in the implementation of `_go_path_impl` in [`path.bzl`](https://github.com/bazelbuild/rules_go/blob/72dff4e33d24aac4953ee794815dc569af0d8093/go/private/tools/path.bzl#L32).

It appears that further down in the function we have [a code-block](https://github.com/bazelbuild/rules_go/blob/72dff4e33d24aac4953ee794815dc569af0d8093/go/private/tools/path.bzl#L67-L104) that creates the map of all files to link and which at the same time checks for the uniqueness of the providers for each individual file in the resulting directory tree. More specifically for data sections [we use](https://github.com/bazelbuild/rules_go/blob/72dff4e33d24aac4953ee794815dc569af0d8093/go/private/tools/path.bzl#L82-L91):
```python
# [...]
    if ctx.attr.include_data:
        for pkg in pkg_map.values():
            for f in pkg.data:
                parts = f.path.split("/")
                if "testdata" in parts:
                    i = parts.index("testdata")
                    dst = pkg.dir + "/" + "/".join(parts[i:])
                else:
                    dst = pkg.dir + "/" + f.basename
                _add_manifest_entry(manifest_entries, manifest_entry_map, inputs, f, dst)
# [...]
```
As far as my reading goes this works in all usual cases where people use `testdata`. However if one were to depend on a (non-`testdata`) `filegroup` rule that uses a glob of type `glob(['foo/**']` then this will break if the underlying globbed sub-directories contain two files with the same name.

Will be creating a PR with a proposed fix but am not entirely sure what style of fix would be preferred in-line with the rest of the rules' implementation style.

**Comment by robfig** [comment]
I was just about to file this same issue! I put together a minimal reproduction here:
https://github.com/robfig/gopath_example

The concrete use case I have is sets of translation files, where I have e.g.

```
country-data/de.po  # translations into german of country & region names, from CLDR
go-data/de.po  # translations into german of messages extracted from the application
```

A `go_path` that depends on any `go_library` that depends on these files fails.

**Comment by Helcaraxan** [comment]
Nice coincidence @robfig. 🤣 

Will be putting in the PR proposal in the next hour or so.

**Comment by Helcaraxan** [comment]
Ok. This is going to be somewhat more complicated than I though initially. At the level of `_go_path_impl` we are dealing with `GoArchive` and `GoArchiveData` providers. These do not, unfortunately, remember for a specific data (or source) file whether it was provided directly or via another rule (and the associated label in this case).

There are only `File` objects available which means I need to think a bit more in order to architect a workable solution to this issue. The intermediary fix (which does not pass the tests for indirect `data` dependencies) is available here: Helcaraxan/rules_go@74301f5e68f9522a55f6d2887ab5322002c9d83c.

**Comment by robfig** [comment]
Thanks for sharing! My workaround for the time being is to set `include_data=False`, which happens to work for my usages of `go_path`

**Comment by Helcaraxan** [comment]
Just a quick update: am still working / experimenting from time to time on this but have not been able to find a nice solution to this issue.

**Comment by jayconrod** [comment]
I'm closing most old issues. It sounds like this might still be a problem, but it's not clear that a solution is feasible and you've found a workaround. If this is still causing a problem, please comment, and we can reopen.

**Comment by SpencerC** [comment]
@jayconrod this is still an issue
