### ISSUE TITLE
go_proto_library: does not work for genfile inputs

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#193]
go_proto_library gets tripped up by files in bazel-out/local-*/genfiles

Take any of the proto examples, for example examples/proto/gostyle/BUILD
add 
genrule(name="copy", srcs=["gostyle.proto"], outs=["gostyle.gen.proto"], cmd="cp $< $@")
and change the go_proto_library srcs to be ["gostyle.gen.proto"]

Should work, but doesn't -- protoc generates the file in a different place than the rule expects.

**Comment by douglas-reid** [comment]
I've run into similar issues when trying to deal with things like munging `import "google/rpc/status.proto";` to the genproto path and then compile.

**Comment by pmbethe09** [comment]
Actually this issue was fixed in PR
https://github.com/bazelbuild/rules_go/pull/204

However there is a persistent problem where protos in Go-land appear in different paths than the "normal" one that other languages use.
Just like your example, which is `import "google/rpc/status.proto";` for everyone else, but for some reason
 `import "googleapis/rpc/status.proto";` in Go.
https://godoc.org/google.golang.org/genproto/googleapis/rpc/status

You could do an ugly workaround by running 'sed' in a genrule before feeding to go_proto_library.

I believe the pubref/protobuf go_proto_library has a way to make this work with some manual lifting.

**Comment by douglas-reid** [comment]
Awesome. I look forward to updating to a newer commit and trying out the genrule + sed approach. I had previously switched to using the pubref library you mentioned.
