### ISSUE TITLE
nogo panic

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#1932]
I'm trying (again) to enable nogo but it panics:
```console
 bazel test //... -- -//vendor/...
INFO: Invocation ID: b3f0a5c8-76f5-4f8e-a138-1d1ad566a993
DEBUG: /private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
DEBUG: Rule 'org_golang_x_tools' modified arguments {"sha256": "11629171a39a1cb4d426760005be6f7cb9b4182e4cb2756b7f1c5c2b6ae869fe"}
INFO: Analysed 44 targets (1332 packages loaded, 2972 targets configured).
INFO: Found 35 targets and 9 test targets...
ERROR: /Users/ash2k/go/src/github.com/atlassian/smith/vendor/k8s.io/klog/BUILD.bazel:3:1: GoCompile vendor/k8s.io/klog/darwin_amd64_stripped/go_default_library%/github.com/atlassian/smith/vendor/k8s.io/klog.a failed (Exit 1) compile failed: error executing command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/compile -sdk external/go_sdk -installsuffix darwin_amd64 -src vendor/k8s.io/klog/klog.go -src ... (remaining 14 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: nogo: internal error: gob encoding of analysis fact printWrapper failed: gob: type not registered for interface: printf.isWrapper; please report a bug against fact *printf.isWrapper in package "golang.org/x/tools/go/analysis/passes/printf"
panic: internal error: gob encoding of analysis fact printWrapper failed: gob: type not registered for interface: printf.isWrapper; please report a bug against fact *printf.isWrapper in package "golang.org/x/tools/go/analysis/passes/printf"

goroutine 1 [running]:
log.Panicf(0x12a6b1d, 0x6e, 0xc00018bc78, 0x4, 0x4)
        GOROOT/src/log/log.go:333 +0xda
golang.org/x/tools/go/analysis/internal/facts.(*Set).Encode(0xc0001db7e0, 0x5, 0x8, 0xc000147b30)
        external/org_golang_x_tools/go/analysis/internal/facts/facts.go:266 +0x7ad
main.checkPackage(0x147c380, 0x5, 0x5, 0x7ffeefbff88c, 0x2d, 0xc00006f4a0, 0xc00006f4d0, 0xc00006f530, 0xc00000e6d0, 0x2, ...)
        external/io_bazel_rules_go/go/tools/builders/nogo_main.go:177 +0x308
main.run(0xc00000e390, 0x36, 0x37, 0x0, 0x0)
        external/io_bazel_rules_go/go/tools/builders/nogo_main.go:80 +0x3cc
main.main()
        external/io_bazel_rules_go/go/tools/builders/nogo_main.go:54 +0x8d
INFO: Elapsed time: 1.870s, Critical Path: 0.70s
```

Reproducer is here https://github.com/atlassian/smith/compare/nogo-panic. Clone, `dep ensure`, `make update-bazel` and then `bazel test //... -- -//vendor/...`

**Comment by jmhodges** [comment]
Just hit this error, too, after doing nothing but upgrading from 0.16.5 to 0.17.0.

**Comment by jayconrod** [comment]
Thanks for reporting, and sorry for letting this bug slip through. I thought we had unit test coverage for fact serialization just by running the `printf` checker on a library, but need one library that defines a `printf` function and one library that calls in to verify fact serialization and deserialization both work.

We should really have better test coverage on this. I'll turn on nogo in Gazelle when this lands. That should help a little bit.

**Comment by jayconrod** [comment]
Reopening, since this is still panicking when building SSA for one of the more advanced checks. The basic checks enabled with `vet = True` should work though.

**Comment by jayconrod** [comment]
@ash2k If I'm remembering correctly, fact serialization was added between 0.16 and 0.17, so you would have seen a similar panic for analyzers that require it, such as `printf`. Fact serialization was added to the framework in `golang.org/x/tools/go/analysis` around the same time as 0.16 cut, and I didn't have support for it until recently.

Background: fact serialization allows an analyzer to save information about a package to a file. The same analyzer can load that information when it processes a dependent package. The `printf` analyzer is one use case: it has a root set of functions, including `fmt.Printf`, and it records facts about other functions that have format string and list parameter and call `printf` functions. So you can call `fmt.Printf` through wrappers across packages and still get warnings about having the wrong arguments.

**Comment by jayconrod** [comment]
Debugging notes for future self and anyone else who runs across this issue.

I'm seeing a panic like this:

<details>
<pre>
goroutine 1 [running]:
golang.org/x/tools/go/ssa.(*Function).lookup(0xc0003172c0, 0x74fb20, 0xc0002d8e60, 0x0, 0x0, 0xc0002d60c0)
	external/org_golang_x_tools/go/ssa/func.go:428 +0x492
golang.org/x/tools/go/ssa.(*builder).addr(0xc000233658, 0xc0003172c0, 0x74bdc0, 0xc00000b200, 0xc000000300, 0x70a4b0, 0xc000124b00)
	external/org_golang_x_tools/go/ssa/builder.go:346 +0x20c
golang.org/x/tools/go/ssa.(*builder).addr(0xc000233658, 0xc0003172c0, 0x74c100, 0xc00000b220, 0xc000232c00, 0x40b42f, 0xc0002d2dc0)
	external/org_golang_x_tools/go/ssa/builder.go:371 +0x11f4
golang.org/x/tools/go/ssa.(*builder).expr(0xc000233658, 0xc0003172c0, 0x74c100, 0xc00000b220, 0xc0002d2da0, 0x1)
	external/org_golang_x_tools/go/ssa/builder.go:528 +0x168
golang.org/x/tools/go/ssa.(*builder).addr(0xc000233658, 0xc0003172c0, 0x74c1c0, 0xc00000b240, 0x0, 0x1, 0x74b100)
	external/org_golang_x_tools/go/ssa/builder.go:417 +0xee5
golang.org/x/tools/go/ssa.(*builder).assignStmt(0xc000233658, 0xc0003172c0, 0xc00005d720, 0x1, 0x1, 0xc00005d740, 0x1, 0x1, 0x924f00)
	external/org_golang_x_tools/go/ssa/builder.go:1037 +0x4c6
golang.org/x/tools/go/ssa.(*builder).stmt(0xc000233658, 0xc0003172c0, 0x74b7c0, 0xc000067e80)
	external/org_golang_x_tools/go/ssa/builder.go:2006 +0x208e
golang.org/x/tools/go/ssa.(*builder).stmtList(0xc000233658, 0xc0003172c0, 0xc00000b380, 0x2, 0x2)
	external/org_golang_x_tools/go/ssa/builder.go:790 +0x72
golang.org/x/tools/go/ssa.(*builder).stmt(0xc000233658, 0xc0003172c0, 0x74b940, 0xc000122000)
	external/org_golang_x_tools/go/ssa/builder.go:2102 +0x2292
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xc000233658, 0xc0003172c0)
	external/org_golang_x_tools/go/ssa/builder.go:2195 +0x2cf
golang.org/x/tools/go/ssa.(*builder).buildFuncDecl(0xc000233658, 0xc00006bda0, 0xc000122030)
	external/org_golang_x_tools/go/ssa/builder.go:2225 +0xec
golang.org/x/tools/go/ssa.(*Package).build(0xc00006bda0)
	external/org_golang_x_tools/go/ssa/builder.go:2341 +0x7ee
golang.org/x/tools/go/ssa.(*Package).build-fm()
	external/org_golang_x_tools/go/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc00006bdcc, 0xc0002338d8)
	GOROOT/src/sync/once.go:44 +0xb3
golang.org/x/tools/go/ssa.(*Package).Build(0xc00006bda0)
	external/org_golang_x_tools/go/ssa/builder.go:2260 +0x54
golang.org/x/tools/go/analysis/passes/buildssa.run(0xc000016f80, 0xc0002d6310, 0x6fb48a, 0xd, 0xc000233bd0)
	external/org_golang_x_tools/go/analysis/passes/buildssa/buildssa.go:72 +0x28b
main.(*action).execOnce(0xc0000ca090)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:283 +0x59d
main.(*action).execOnce-fm()
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:233 +0x2a
sync.(*Once).Do(0xc0000ca090, 0xc000233c88)
	GOROOT/src/sync/once.go:44 +0xb3
main.(*action).exec(0xc0000ca090)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:233 +0x50
main.execAll(0xc00005d5d0, 0x2, 0x2)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:220 +0x38
main.checkPackage(0x928bf0, 0x2, 0x2, 0x7ffcd5825d05, 0x28, 0xc000077c80, 0xc000077cb0, 0xc000077d10, 0xc00000e170, 0x1, ...)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:189 +0x387
main.run(0xc00000e0d0, 0xb, 0xb, 0x0, 0x0)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:81 +0x3cc
main.main()
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:55 +0x8d
</pre>
</details>


* This is coming from the `buildssa` analyzer. `buildssa` produces SSA information as its result. It doesn't produce any findings on its own. `buildssa` does not record facts.
* The panic happens on `//flag:go_default_library` in Gazelle. Probably other packages, but this is a simple leaf package.
* `nilness` depends on `buildssa`.
* `vet -nilness ./flag` does not panic.

**Comment by ash2k** [comment]
I can confirm the issue is fixed. Thanks a lot. I think the cause of my previous issues might have been an older version of the x/tools repo that I used. I have now updated to the commit rules_go uses and everything works fine.
