### ISSUE TITLE
Rules_go don't not work with development build of Bazel

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/rules_go#1935]
Bazel CI is red (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/790#53603a07-db68-4013-9f36-45e9e09afd24), because version check returns empty string for development builds of Bazel. Would it be an option to show a warning saying we're using development version Bazel in our own risk? :)

Thanks!

**Comment by jayconrod** [comment]
Oops, I should have tested this against a development version. Will fix today.

No need to show a warning -- I think we can assume a development version is new and should use the latest version of this file.

FYI, I'm implementing your suggestion to define a repository which picks a different set of compatibility definitions based on the Bazel version. This was an attempt at that.

**Comment by hlopko** [comment]
Yup I assumed so, I hit the same thing when I implemented this for rules_rust :) Nice demonstration of how a bad API costs time over and over.
