### ISSUE TITLE
compatibility layer

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1937]
I get this error from the compatability layer. I was wondering how to fix this?

ERROR: ErrorInfo{exception=null, rootCauses={}, cycles=[[] -> [[/home/barriosj/go-aqrcommon]/[WORKSPACE], 2, @io_bazel_rules_go//go:def.bzl (in workspace), @io_bazel_rules_go//go/private:rules/wrappers.bzl (in workspace), @io_bazel_rules_go//go/private:rules/cgo.bzl (in workspace), @io_bazel_rules_go_compat//:compat.bzl (in workspace), AST_FILE_LOOKUP:@io_bazel_rules_go_compat//:compat.bzl, PACKAGE_LOOKUP:@io_bazel_rules_go_compat//, REPOSITORY:@io_bazel_rules_go_compat, REPOSITORY_DIRECTORY:@io_bazel_rules_go_compat]], isCatastrophic=false, rootCauseOfException=null, isDirectlyTransient=false, isTransitivelyTransient=false}

**Comment by jayconrod** [comment]
Hmm, it looks like a cyclic dependency error, but it's not in a format I've seen before (usually they are much more vague). What version of Bazel is this? What rules_go commit? What's the command line?

Also, could you confirm in WORKSPACE you're loading symbols from `@io_bazel_rules_go//go:deps.bzl` and not `def.bzl`?

**Comment by jeb2239** [comment]
yes they are coming from io_bazel_rules_go//go:def.bzl

**Comment by jeb2239** [comment]
the bazel version is 0.22.0

**Comment by jayconrod** [comment]
Ok, that explains it. Starting in rules_go 0.17.0, WORKSPACE definitions need to be loaded from `@io_bazel_rules_go//go:deps.bzl` instead of `def.bzl`. This change was necessary to add the compatibility repository. `compat.bzl` needs to be loaded from files loaded by `def.bzl`, but it needs to be declared first in `go_rules_dependencies`. So `go_rules_dependencies` and other definitions were moved to the new file.

**Comment by jeb2239** [comment]
so how can I fix this?

**Comment by jayconrod** [comment]
In WORKSPACE, replace this line:

```
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
```

with this line:

```
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
```
