### ISSUE TITLE
new_go_repository: vendored code interfering with non-vendored

### ISSUE THREAD

**Issue by benley** [bazelbuild/rules_go#194]
I'm trying to build https://github.com/golang/gddo using new_go_repository, and I used [wtool](https://github.com/bazelbuild/rules_go/tree/master/go/tools/wtool) to generate the various new_go_repository [WORKSPACE entries](https://gist.github.com/benley/f2aeb9de8eedffda0e9cbc2a219ac0dd) for it.

It appears that gddo has all its dependencies vendored into the gddo repo, which isn't too uncommon.  Unfortunately it looks like gazelle is building the vendored-in copy of various things, but translating those libraries' internal dependencies to point at the non-vendored copy of the same library, which may not even be at the same version.  The result is some strange `visibility` errors:

```
$ bazel build @com_github_golang_gddo//...
ERROR: /private/var/tmp/_bazel_bstaffin/26abb02a80899f40a981f66c2d82ca06/external/com_github_golang_gddo/vendor/golang.org/x/net/trace/BUILD:3:1: Target '@org_golang_x_net//internal/timeseries:go_default_library' is not visible from target '@com_github_golang_gddo//vendor/golang.org/x/net/trace:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: Analysis of target '@com_github_golang_gddo//vendor/golang.org/x/net/trace:go_default_library' failed; build aborted.
INFO: Elapsed time: 0.089s
```

Is there a known workaround for this?

**Comment by pmbethe09** [comment]
I think you have hit a feature of gazelle, directories called "internal"
get a more restrictive visibility:

https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/rules/generator.go#L258

Probably this feature should be turned off for gazelle running under
new_go_repository

**Comment by GinFungYJF** [comment]
Has this feature been turned off for gazelle running under new_go_repository now?

**Comment by jayconrod** [comment]
This should be working now. Gazelle now resolves import paths using all libraries in a repository, including in vendor directories (subject to vendoring visibility). external / vendored mode only applies to libraries that can't be resolved this way.
