### ISSUE TITLE
Question - Package a go_binary with data files

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_go#1942]
Hi,
I want to build a deployable artifact that includes all required data files. The native `java_binary` rule includes a `_deploy` target that produces a jar containing the compiled class files along with the data files that each included library depends upon. I don't see anything analogous for `go_binary`, and I can see two options for implementing it:

1. Update `go_binary` to also provide a `_deploy` suffixed target which tars up things into some standard archive layout. It might be self-executing, or it could include a runner script inside the archive, or it could require the user to know how to un-tar and run it. Are you open to such a pull request?

2. Add a `my_go_binary` macro that does the above. This comes with the extra work of making Gazelle generate `my_go_binary` rules instead of `go_binary`, which does not seem to be a provided knob. Therefore, forking Gazelle or implementing a knob + submitting a PR would be the only options. 

I was hoping you could provide some input:

- This seems like a common use case, so I was wondering if there's a more straightforward solution that I'm missing. 
- Thoughts on each of the above implementation options

Thank you very much,
Rob

**Comment by jayconrod** [comment]
Instead of adding this functionality to `go_binary`, there should be a generic rule that handles packaging. There are some generic [packaging rules](https://docs.bazel.build/versions/master/be/pkg.html) for Bazel. `pkg_tar` might suit your needs. It should be pretty straightforward to write a custom rule if that doesn't work for you.

One other question: is it just the executable that needs to access the data files, or do they need to be visible to other programs? [`go_embed_data`](https://github.com/bazelbuild/rules_go/blob/master/go/extras.rst#go-embed-data) can build data files into the executable itself. There's also [`bindata`](https://github.com/bazelbuild/rules_go/blob/master/extras/bindata.bzl).

**Comment by robfig** [comment]
Thanks for the response!

`pkg_tar` should do the trick. I do think it would be helpful if it were provided by `go_binary` by default for the same reason `java_binary` provides it, but it's easy enough to make it myself. 

Instead of having a developer add a custom `pkg_tar` rule for each `go_binary` they want to deploy, I'd like to encapsulate that using a macro, e.g.  `go_deployable` which creates a `go_binary` and `pkg_tar`. Today we use gazelle to generate the `go_binary` rules.. would you be open to a pull request adding a parameter to it, e.g. `gazelle --rule_name=go_deployable`?  Alternatively, I could have `bazel run :gazelle` invoke both gazelle and then buildozer with the appropriate modifications. Perhaps that's better.

The data only needs to be accessible to the binary, but I was not keen to find and update all of the code that assumes filesystem access via `os.Open`. I've also anecdotally heard that embedding data blobs can trigger pathologically long compile times depending on what's being embedded, but that information might be outdated or only apply to very large data files. But thanks for the link, I will try it out for a few cases and see how it works & how many places I would have to update.

**Comment by jayconrod** [comment]
I think the problem with having this be a feature of `go_binary` is that there would be too many options. With Java, providing a jar is obvious, but with Go, it could be tar, zip, deb, rpm, Docker image and more with various compression, signing, or formatting options and various bits of data to include. It's better to have separate rules for packaging that compose well with `go_binary` and other rules.

And macros are fine for composing these.

Gazelle isn't able to handle macros like this now, but it may be a valuable feature to have. Is this something you'd want to apply globally throughout a repository, or only to specific targets? In any case, please open an issue in bazelbuild/bazel-gazelle, and we can decide what it should look like.
