### ISSUE TITLE
Allow direct access to the go tool

### ISSUE THREAD

**Issue by stephenmw** [bazelbuild/rules_go#195]
I am using rules_go how they are meant to be used for new code that is directly in my repo. However, I have some code from the non-bazel world that I need to compile. I want to compile that code how it was meant to be compiled (with the go tool) and not bazel.

Here is the code I have right now:

```
gopath="$(mktemp -d /tmp/build-gddo-server.XXXXXXXXXX)"
trap "rm -rf $gopath" EXIT

mkdir -p "$gopath/src/github.com/golang"
ln -s "$PWD/external/gddo" "$gopath/src/github.com/golang"

GOPATH="$gopath" GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GO_CMD" build \
    -installsuffix gddo-nocgo \
    -o "$OUT" \
    github.com/golang/gddo/gddo-server

```

If possible, I want to be able to directly access the go tool downloaded from rules_go. I could build my own, but since I use rules_go anyways, it would be nice if I didn't need multiple copies in my workspace.

For the record:

- I understand I will lose cross platform building
- I understand I will increase compilation time
- I would love a better way to implement this than using /tmp

**Comment by pmbethe09** [comment]
On Mon, Nov 14, 2016 at 11:30 AM, Stephen Weinberg <notifications@github.com
> wrote:

> I am using rules_go how they are meant to be used for new code that is
> directly in my repo. However, I have some code from the non-bazel world
> that I need to compile. I want to compile that code how it was meant to be
> compiled (with the go tool) and not bazel.
>

I don't understand this statement, since bazel does use 'go tool' under the
hood.
What goes wrong when using bazel with this code?

**Comment by stephenmw** [comment]
Well, the biggest problem is I can't figure out how to get gddo to compile by normal means. This is the code I am using:

```
new_go_repository(
    name = "gddo_go_repo",
    importpath = "github.com/golang/gddo",
    commit = "806603679dee755c926f72ac76673ee4594dcd32",
)
```

The result is that I enter dependency hell. At the same time my code in my original post works but is using an external Go installation so I know everything I need is there. As for me being afraid of using bazel... I didn't know what magic it was using and had a perfectly good system of compiling that gave me static binaries and I knew worked.

**Comment by pmbethe09** [comment]
What library in gddo are you linking against?

You probably want to use the standard name that gazelle would give you of
'com_github_golang_gddo'

**Comment by stephenmw** [comment]
After using com_github_golang_gddo:

$ bazel build @com_github_golang_gddo//gddo-server:gddo-server
ERROR: /private/var/tmp/_bazel_stephenmw/92657461b7173c04bba61ab8c1d4c966/external/com_github_golang_gddo/gddo-server/BUILD:3:1: no such package '@org_golang_x_net//context': error loading package 'external': The repository named 'org_golang_x_net' could not be resolved and referenced by '@com_github_golang_gddo//gddo-server:gddo-server'.
ERROR: Analysis of target '@com_github_golang_gddo//gddo-server:gddo-server' failed; build aborted.
INFO: Elapsed time: 2.118s

This is probably a bug in the Go rules.

**Comment by pmbethe09** [comment]
This message indicates that there is no
new_go_repository(name='org_golang_x_net',...) in your WORKSPACE
You have to add all of the transitive dependencies into a flattened
WORKSPACE file.

basically:
$ bazel build -k @com_github_golang_gddo//gddo-server:gddo-server
$ wtool org_golang_x_net ...

the '-k' has bazel keep going, so it will detect all repos directly
referenced by com_github_golang_gddo
find all of the messages like
"The repository named 'org_golang_x_net' could not be resolved"
and call wtool with them, repeat until it builds.

**Comment by pmbethe09** [comment]
go install github.com/bazelbuild/rules_go/go/tools/wtool

gazelle assumes you want to follow the bazel way of remote vendoring.  To
do otherwise, you have to write your BUILD files by hand.

**Comment by jayconrod** [comment]
Closing some old issues. Please reopen if something specific should be changed.
