### ISSUE TITLE
Excluding external repository from nogo

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1950]
Is it possible to exclude external repos from nogo?

**Comment by jayconrod** [comment]
You can provide a configuration file that excludes files using regular expressions applied to their paths (as they would appear in error messages). I think you could probably match the external repo name using that.

[Configuring analyzers](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst#configuring-analyzers) has the details.

**Comment by jeb2239** [comment]
I did this and tried several paths. I want to silence a specific file 

/apps/tmp/bazel/sandbox/processwrapper-sandbox/358/execroot/aqrcommon/bazel-out/k8-fastbuild/bin/external/com_github_alexbrainman_odbc/linux_amd64_stripped/api%linux_amd64%cgo_codegen%/zapi_unix.go:59:406: possible misuse of unsafe.Pointer

```
{
    
    "unsafeptr":{
        "exclude_files":{
            "github.com/alexbrainman/odbc/zapi_unix.go": " possible misuse of unsafe.Pointer"
        }
    }
  }
```

This doesn't work. I am not sure how to match things in external dependencies.

**Comment by jeb2239** [comment]
Just wondering if there is any info available on this issue.

**Comment by jayconrod** [comment]
The regex is applied to the path as it appears in error messages. This works:

```
{
  "unsafeptr": {
    "exclude_files": {
      "/com_github_alexbrainman_odbc/": "buggy repo"
    }
  }
}
```

**Comment by jeb2239** [comment]
It seems like that method works for unsafe pointer but not shadow.

**Comment by hochhaus** [comment]
@jeb2239 Some of the analysis passes are named a bit inconsistently. For example, [composites](https://github.com/golang/tools/blob/master/go/analysis/passes/composite/composite.go#L36) vs `composite`. I've enabled nearly all of the [passes](https://github.com/golang/tools/tree/master/go/analysis/passes) and as best I can tell the corresponding `config.json` options do apply correctly so long as you verify them again the `analysis.Analyzer.Name` value.

It would be helpful for nogo to fail when `config.json` names a phase which does not exist to help identify these issues easily.

**Comment by fmeum** [comment]
Nogo can now be configured on a per-package basis: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#configuring-nogo
