### ISSUE TITLE
Make `--platforms` support cross-compiling for multiple binaries in one invocation

### ISSUE THREAD

**Issue by viswajithiii** [bazelbuild/rules_go#1952]
I want to be able to compile a `test_binary` for multiple target platforms in one invocation.

Currently, the compilation is run like this, with three separate invocations:
```
	bazel build $(BAZEL_FLAGS) --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 -- //test_binary
	bazel build $(BAZEL_FLAGS) --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 -- //test_binary
	bazel build $(BAZEL_FLAGS) --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 -- //test_binary
```
I would like to be able to run something like:
```
	bazel build $(BAZEL_FLAGS) \
		--platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 \
		--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 \
		--platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 \
		-- //test_binary
```
However, if I try this, it only builds the binary for whatever platform was passed last.
I also tried passing a comma-separated list to a single `--platforms` argument, but there, it only builds the binary for the first element of the list.

I've tried using `goos` and `goarch` to achieve this, but it doesn't work because of the limitations outlined here (it picks some incorrect transitive dependencies): https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#note-on-goos-and-goarch-attributes

Is there a way to make this work in one invocation? The hope is to be able to get slightly faster builds this way. Thanks!

**Comment by jayconrod** [comment]
`--platforms` is a language-agnostic Bazel flag, so this feature would definitely need to be handled on the Bazel side, not in rules_go.

I did a quick search of issues in bazelbuild/bazel. I didn't find a feature request for this specifically, but I think it's something that's planned. You might take a look at [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html) for more detail.

**Comment by katre** [comment]
This is the "Flagless multiplatform builds" feature from the roadmap @jayconrod linked.

**Comment by viswajithiii** [comment]
Thanks for the quick answer, @jayconrod! From my read of the `bazelbuild/bazel` code, it looks like they already support passing multiple values to the `--platforms`; their parser treats it as a comma-separated list. 

However, from my experiments yesterday, passing a comma-separated list doesn't work in practice. Does this mean it's probably a bug in `bazelbuild/bazel`? (I'm not sure exactly how responsibility is divided between the `bazelbuild/bazel` and `rules_go`.) 

(For reference, the code I was looking at was https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/PlatformOptions.java#L83, which uses their `LabelListConverter` parser, defined at https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/config/BuildConfiguration.java#L180.)

**Comment by viswajithiii** [comment]
@katre Thanks for your response! I don't really want flagless multiplatform builds -- I'm fine with passing all the platforms as arguments to `bazel build`. I just want multiplatform builds. 🙂

**Comment by xiaoguomin** [comment]
Has the problem been solved yet？

**Comment by katre** [comment]
@xiaoguomin: We aren't prioritizing this work, because of the potential memory implications for Bazel. We won't realistically pick it up until we are much further along with other projects to reduce Bazel's memory usage.
