### ISSUE TITLE
Failed to fetch package - not a root of a repository error

### ISSUE THREAD

**Issue by FilipNikolovski** [bazelbuild/rules_go#1953]
We recently switched a project to use Go modules, and currently hit an issue when importing a package which include versioned path.

In my code I have this import:

`import  "github.com/mailgun/mailgun-go/v3"`

I updated the go.mod file with the command:

`go get github.com/mailgun/mailgun-go/v3`

In my WORKSPACE file i have this go repository defined:

```
go_repository(
    name = "com_github_mailgun_mailgun_go_v3",
    importpath = "github.com/mailgun/mailgun-go/v3",
    tag = "v3.3.0",
)
```

The error that shows when i run `bazel build //...` is the following:

```
ERROR: Analysis of target '//mailer/pkg/validators:go_default_library' failed; build aborted: 
no such package '@com_github_mailgun_mailgun_go_v3//': failed to fetch com_github_mailgun_mailgun_go_v3: 
2019/02/15 16:36:19 not a root of a repository: github.com/mailgun/mailgun-go/v3
```

Any help is appreciated, thanks!

**Comment by jayconrod** [comment]
You should be able to work around this by setting `remote` and `vcs` explicitly.

```
go_repository(
    name = "com_github_mailgun_mailgun_go_v3",
    importpath = "github.com/mailgun/mailgun-go/v3",
    remote = "https://github.com/mailgun/mailgun-go",
    tag = "v3.3.0",
    vcs = "git",
)
```

We really just need to support this in `go_repository` though. I'll close this as a dup of bazelbuild/bazel-gazelle#400.
