### ISSUE TITLE
fetch_repo SSH Authentication

### ISSUE THREAD

**Issue by PranavSathy** [bazelbuild/rules_go#196]
Would it be possible to modify `fetch_repo` in order to support SSH authentication (or Authentication of any sort for that matter)? It would assist in having private remote repositories linked together (without the need for a monorepo).

**Comment by PranavSathy** [comment]
git config --global url."git@github.com:".insteadOf "https://github.com/"

^ I noticed that doing that makes the golang VCS package utilize the SSH authentication I wanted, which works. Perhaps this behavior can be baked into the BUILD rule as an attribute (use_ssh) or something?

**Comment by ianthehat** [comment]
We are proceeding with the plan to kill the fetch_repo tool completely, and are not likely to make any changes to it in the mean time, so I am going to close this issue.
