### ISSUE TITLE
Overriding dependencies documentation is outdated

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/rules_go#1966]
https://github.com/bazelbuild/rules_go/blob/0.17.1/go/workspace.rst#overriding-dependencies

Based on the latest release, the instructions will no longer work because:

> Starting in this version, def.bzl now references a compatibility repository declared in go_rules_dependencies, so loading def.bzl before calling go_rules_dependencies will result in an error. This is necessary to support older and newer versions of Bazel across breaking Bazel API changes.

**Comment by jayconrod** [comment]
Thanks for reporting!
