### ISSUE TITLE
new_go_repository does not support build tags

### ISSUE THREAD

**Issue by 1-z** [bazelbuild/rules_go#197]
Attempting to port an existing project into bazel is failing.
The project depends on github.com/docker/docker, but attempting to import this into bazel is failing due to extensive use of build tags in some of its dependencies (also imported with new_go_repository). This leads to a variety of build errors. Is there currently a method to avoid this in new_go_repository using something like new_git_repository and a genrule?

**Comment by pmbethe09** [comment]
This is a known deficiency in gazelle.

**Comment by 1-z** [comment]
pr/200 (ff444c3e587d4073266f3f680598408e228ef6af) resolved this issue for me, closing.
