### ISSUE TITLE
New deps.bzl/def.bzl split prevents overriding versions in go_rules_dependencies()

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_go#1976]
We have been calling `go_rules_dependencies` after all other `go_repository` definitions in our WORKSPACE. There are a couple of reasons for this:

- to use newer versions compatible with our source code (in particular, those in `Gopkg.lock` - see also https://github.com/bazelbuild/bazel/issues/3908)
- to use `http_archive`, which can mirror the repo and avoids build warnings from the repository rules

However, this appears to be impossible since #1933, as `go_repository` can't be loaded until `go_rules_dependencies` has been invoked.

Would it make sense to add an official way of invoking `go_rules_compat(name = "io_bazel_rules_go_compat")` so that it `go_repository` can be used before `go_rules_dependencies`?

**Comment by jayconrod** [comment]
You should be able to load and call `go_repository` before calling `go_rules_dependencies`. Neither `gazelle_dependencies` nor `go_repository` depend on `go_rules_dependencies` being called first. There's a brief example in [overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies).

If this is not working, let me know so I can reproduce / fix it. That's how it's supposed to work though.

**Comment by drigz** [comment]
After upgrading to 0.17.1 I got an error:

```
ERROR: Failed to load Starlark extension '@io_bazel_rules_go_compat//:compat.bzl'.                                                                                                                                 
It usually happens when the repository is not defined prior to being used.                                    
Maybe repository 'io_bazel_rules_go_compat' was defined later in your WORKSPACE file?
```

It's not clear exactly what the culprit is. However, if I place `go_rules_dependencies()` before `load("@bazel_gazelle//:def.bzl", "go_repository")` the build works. If I swap the two lines, the build fails with the error above.

**Comment by jayconrod** [comment]
Hmm, could you try loading `go_repository` from `@bazel_gazelle//:deps.bzl` instead? I think `go_repository` is defined in both places because the distinction wasn't really important before. I should remove it from `def.bzl` though.

**Comment by drigz** [comment]
That indeed fixes it. Thanks for the quick support!

**Comment by nelhage** [comment]
I can reproduce this in livegrep/livegrep:

https://github.com/livegrep/livegrep/compare/rules_go-1976

[fails with the same error.](https://circleci.com/gh/livegrep/livegrep/256)

I am [pulling in `go_repository`](https://github.com/livegrep/livegrep/blob/5db20d77226766ea302d9efa9eb4511428c7a7d8/tools/build_defs/go_externals.bzl#L1-L4) from `deps.bzl`

I haven't tried to minimize; I can take a stab but I have a pretty big `WORKSPACE` so it'd be nontrivial. Let me know if I should open a new issue instead.

**Comment by nelhage** [comment]
Ah, I was pulling in my `WORKSPACE` definitions from `def.bzl` still. Fixing that seems to have fixed the problem.

**Comment by ChankiWu** [comment]
I encounter this error again when I want to migrate code from Bazel 0.22 to 0.25:
ERROR: Failed to load Starlark extension '@io_bazel_rules_go_compat//:compat.bzl'.
It usually happens when the repository is not defined prior to being used.
This could either mean you have to add the 'io_bazel_rules_go_compat' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or the repository 'io_bazel_rules_go_compat'

I don't use go so I don't download gazelle. Could anyone please provide some solutions for this?

**Comment by jayconrod** [comment]
@ChankiWu That error usually comes up if you're loading symbols from `@io_bazel_rules_go//go:def.bzl` in WORKSPACE. They should be loaded from `@io_bazel_rules_go//go:deps.bzl` instead.
