### ISSUE TITLE
release notes don't mention that a gazelle version bump is needed

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1982]
Looks like there's a required upgrade to gazelle 0.17 but I didn't see that mentioned in the release notes. Details below.

Upgrading to rules_go 0.18 and started getting failed Travis CI builds. Logged in and saw messages like 

```
(09:16:35) ERROR: Skipping '@com_github_jmhodges_goose//cmd/goose': no such package '@com_github_jmhodges_goose//cmd/goose': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
```

Some GitHub searching found [a PR to rules_go](https://github.com/bazelbuild/rules_go/pull/1903) mentioning a newer version of gazelle was needed for the GOCACHE stuff, but I hadn't bumped it myself. It'd be cool if the release docs could let us know of required upgrades for gazelle like that.

(Oddly, this all worked fine on my macOS machine but failed in TravisCI)

**Comment by jayconrod** [comment]
Thanks for pointing that out that omission. I've edited that in to the release notes for 0.17.1 and 0.18.0.
