### ISSUE TITLE
Cache collision across linux distributions

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_go#1988]
We just started using rules_go widely at my company, and I'm hearing that developers on Linux workstations are getting build errors. The build errors are not reproducible with the remote cache disabled, and the error suggests that a cgo-generated file produced by and specific to our CI system is attempted to be built on a developer workstation. 

Our CI system runs CentOS 7 and is the only thing that populates the build cache.  This particular developer runs Ubuntu 16.04.4 LTS. My guess is that both qualify as linux_amd64 which is the resolution of the cache key (I could be totally wrong on that though). 

Here's the example error message:

```
(19:06:26) ERROR: /home/jsharps/.cache/bazel/_bazel_jsharps/8c279106a568f928c3ee245a89be553d/external/org_golang_x_sys/unix/BUILD.bazel:3:1: undeclared inclusion(s) in rule '@org_golang_x_sys//unix:go_default_library%linux_amd64%cgo_c_lib':
this rule is missing dependency declarations for the following files included by 'external/org_golang_x_sys/unix/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_export.c':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
Target //gocode/src/corp/lmp/apigateway:go_default_library failed to build
```

This error resolves when disabling the cache, and it also resolves when passing --features=pure to disable cgo. 

Do you have any advice on how to manage a cache that services multiple linux distributions? The only short-term fix I can think of is to disable cache population for Linux Go artifacts.

Thank you!
Rob

**Comment by jayconrod** [comment]
This error sounds like a system include file isn't correctly included in the C/C++ toolchain. rules_go just adds dependencies on whatever the C/C++ toolchain says we need, so there's not much I can do here.

Are you configuring the toolchain explicitly with a CROSSTOOL file, or are you relying on Bazel's auto-configuration? If you're using your own CROSSTOOL, make sure system header directories are declared in `cxx_builtin_include_directory`. If you're relying on the autoconfiguration, you'll probably need to open an issue on bazelbuild/bazel or the bazel-discuss mailing list.

**Comment by robfig** [comment]
We are using auto-configuration (which should be host configuration). Will do, thanks!
