### ISSUE TITLE
How to integrate nogo with other tools

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_go#1998]
We are using https://github.com/haya14busa/reviewdog and I wonder how I would integrate that with nogo. Is there a way to let nogo run without stopping on errors to catch the output?

**Comment by jayconrod** [comment]
Closing old issues -- sorry I never responded to this one.

nogo errors are like compiler errors: they're just printed to stdout by `GoCompilePkg` actions. I suppose you could take the binary produced by `nogo` and run it separately, but that's likely difficult and not all that useful.
