### ISSUE TITLE
Bazel wrongly returns cached test results with ginkgo under some circumstances

### ISSUE THREAD

**Issue by rmohr** [bazelbuild/rules_go#1999]
### What version of rules_go are you using?

0.18.0

### What version of gazelle are you using?

0.16.0
### What version of Bazel are you using?

0.22.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux, Fedora

### What did you do?

Create a test suite:

```go
package virt_api_test

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestVirtApi(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Virt_Api Suite")
}
```

which is in the _test package, so `virt_api_test`. 

Then create actual tests in a separate file in the same directory

```go
package virt_api

import (
	. "github.com/onsi/ginkgo"
)

var _ = Describe("Filesystem", func() {

	It("should succeed", func() {

	})
})
```
Note that here package `virt_api` is used. Gazelle sets both files as sources for `go_test`:

```
go_test(
    name = "go_default_test",
    srcs = [
        "api_test.go",
        "virt-api_suite_test.go",
    ],
```

The first test run executs the tests. When you then add more tests into the the test file bazel still returns the cached results.

When I set `package` in both files to the same name, does not matter if `virt_api` or `virt_api_test`, bazel detects all changes properly.

It is probably fair to say that the package setup is not right in my example, but `go test` just works like expected, so it is hard to track that your tests are actually not run by bazel.

### What did you expect to see?

I would have expected that bazel checks if _test files change and runs all tests again, no matter in which package they are.

### What did you see instead?

Bazel thought that there are no changes in the tests and only returns cached results.

**Comment by jayconrod** [comment]
It looks like the issue here is that the generated testmain package only imports test packages if they contain tests, examples, or benchmarks (following the conventions of the `testing` package). Since `virt_api` doesn't contain tests, it doesn't get imported and may not be included in the output executable.

This is not what `go test` does: the generated testmain package should import test packages if they have one or more files after build constraints are evaluated. We should fix this.

**Comment by alexeldeib** [comment]
I hit the exact scenario described here. Is there a proper arrangement of code/test files that solves this issue? What's the impact of naming them the same (test code gets pulled in as business logic, bloated binaries)?

Any other solution to running tests with Bazel?

**Comment by rmohr** [comment]
It should be enough to use the same package name for all test files in a package.

**Comment by rmohr** [comment]
@jayconrod could you point me to the general locations where this should be fixed? I can give it a try, since we would really need this fixed.

**Comment by jayconrod** [comment]
@rmohr The source for the test `main` package is generated by `go/tools/builders/generate_test_main.go`. I think the test packages are built, they're just not imported or linked into the test binary.
