### ISSUE TITLE
go_tool_binary fails due to missing GOROOT env variable

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/rules_go#2005]
**Versions:** Bazel 0.22.0, rules_go 0.18.0, gazelle version 0.17.0

When using remote execution, some Go targets fail early in the build process with an error about missing `GOROOT`:

```
22:26:32   (cd /mnt/tmpfs/BAZEL_OUTPUT/execroot/remotebuild_testing && \
22:26:32   exec env - \
22:26:32   /bin/bash -c ''\''external/go_sdk/bin/go'\'' tool compile -o '\''bazel-out/host/bin/external/go_sdk/builder'\''.a -I '\''external/go_sdk'\'' $@ && '\''external/go_sdk/bin/go'\'' tool link -o '\''bazel-out/host/bin/external/go_sdk/builder'\'' -L '\''external/go_sdk'\'' '\''bazel-out/host/bin/external/go_sdk/builder'\''.a && rm '\''bazel-out/host/bin/external/go_sdk/builder'\''.a' '' external/io_bazel_rules_go/go/tools/builders/ar.go external/io_bazel_rules_go/go/tools/builders/asm.go external/io_bazel_rules_go/go/tools/builders/builder.go external/io_bazel_rules_go/go/tools/builders/cgo.go external/io_bazel_rules_go/go/tools/builders/compile.go external/io_bazel_rules_go/go/tools/builders/cover.go external/io_bazel_rules_go/go/tools/builders/env.go external/io_bazel_rules_go/go/tools/builders/extract.go external/io_bazel_rules_go/go/tools/builders/filter.go external/io_bazel_rules_go/go/tools/builders/filter_buildid.go external/io_bazel_rules_go/go/tools/builders/flags.go external/io_bazel_rules_go/go/tools/builders/generate_nogo_main.go external/io_bazel_rules_go/go/tools/builders/generate_test_main.go external/io_bazel_rules_go/go/tools/builders/importcfg.go external/io_bazel_rules_go/go/tools/builders/link.go external/io_bazel_rules_go/go/tools/builders/pack.go external/io_bazel_rules_go/go/tools/builders/replicate.go external/io_bazel_rules_go/go/tools/builders/stdlib.go external/io_bazel_rules_go/go/tools/builders/path.go)
22:26:32 Execution platform: @bazel_tools//platforms:host_platform
22:26:32 go: cannot find GOROOT directory: /usr/local/go
22:26:32 Target //the_target failed to build
```

I believe this is because `_go_tool_binary_impl()` isn't setting `GOROOT` in its environment, and since `/usr/local` is outside the execroot it doesn't get pulled in to the remote build environment.

**Comment by jayconrod** [comment]
Could you say more about your remote setup? Is this on RBE or something else? Do you have a custom builder image?

It shouldn't be necessary to set `GOROOT`, since it should be inferred from the location of the `go` binary. I wonder if there's another `go` binary that's leaking in somehow?

**Comment by jmillikin-stripe** [comment]
We have a custom image (which does not include Go), and a custom remote executor based on gVisor. The executor constructs a filesystem that looks like this:

```
$ ls /build/sandbox.1234/blobs
77d6a18522029c2299b7463721c3bb9f92c1d1cb7805b2316693556a8652fdad/data-0755

$ ls /build/sandbox.1234/execroot
external/bazel_tools/tools/genrule/genrule-setup.sh -> /build/sandbox.1234/blobs/77d6a18522029c2299b7463721c3bb9f92c1d1cb7805b2316693556a8652fdad/data-0755
```

Code that assumes it can `realpath()` out of the sandbox and then inspect the filesystem structure will not work in this environment.

**Comment by jayconrod** [comment]
I tried reproducing this by running Bazel locally inside a Docker image that does not include Go. I couldn't reproduce the error, but it's obviously not the same environment.

You're probably in a much better position to figure out what's going on here. `go_tool_binary` is defined in `go/private/rules/binary.bzl`. It just runs a shell script that executes `go tool compile` and `go tool link`. The target that's failing here is `@go_sdk//:builder`, which is a toolchain dependency.

**Comment by jayconrod** [comment]
Does the executor itself have `GOROOT` in its environment? Might be interesting to print `env` as part of that script.

**Comment by jmillikin-stripe** [comment]
The executor doesn't have GOROOT set. I believe that the `go` binary itself is doing some sort of filesystem inspection based on `realpath(argv[0])`.

If I edit `GoToolchainBinary` to set `GOROOT` explicitly, then the build succeeds. The current code we have in WORKSPACE is:

```python
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz"],
    patch_cmds = [ 
        # Workaround for https://github.com/bazelbuild/rules_go/issues/2005: If GOROOT
        # isn't set, builds in the hermetic remote execution sandbox will go looking
        # for a '/usr/local/go' that doesn't exist.
        """sed -i.bak 's/mnemonic = "GoToolchainBinary",/mnemonic = "GoToolchainBinary", env = {"GOROOT": sdk.root_file.dirname},/' go/private/rules/binary.bzl"""
    ],  
)
```
