### ISSUE TITLE
Assembly files not classified correctly, based on cgo mode

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2006]
### What version of rules_go are you using?

0.18.1

### What version of Bazel are you using?

0.23.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What did you do?

`//tests/legacy/build_constraints:go_default_test` is incorrect. It includes Go assembly files in a package with cgo.

### What did you expect to see?

Go assembly sources should be rejected with a message like `package using cgo has Go assembly file asm_linux.s`. Both .s and .S files should be included in the build and should be assembled with the C compiler. This should only happen for packages with `cgo = True` when cgo is enabled.

### What did you see instead?

Go assembly sources are assembled with the Go assembler. .S files should not be included in the build unless `cgo = True` and cgo is enabled.

**Comment by jsharpe** [comment]
This happens for datadog/zstd - I hit this when using gazelle to generate deps for ethereum-go : this is the workaround in that case: https://github.com/aspect-build/rules_sol/pull/8/files#diff-1f2c31b701f066691b4a4024644f86e092ab731eb81cc5d6282017fe485082ae

**Comment by fmeum** [comment]
If we can't fix the issue in Gazelle, we could add the affected Go repos to the BCR with the fixing patches applied, as we did for [circl](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/circl).
