### ISSUE TITLE
@net_zlib: java.io.IOException when trying to build protos

### ISSUE THREAD

**Issue by polds** [bazelbuild/rules_go#2017]
### What version of rules_go are you using?

0.18.1

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.23.2-homebrew

### What operating system and processor architecture are you using?

macOS 10.14.2 

### What did you do?

Attempted to run `bazel build //proto:all`

proto/service.proto
```
syntax = "proto3";
package foo.bar;

message Message {
    string msg = 1;
}
```

proto/BUILD
```
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "foo",
    srcs = ["service.proto"],
)

go_proto_library(
    name = "foo_go_proto",
    importpath = "example.com/foo/bar",
    proto = ":foo",
)
```

### What did you expect to see?

No error, outputted pb.go files.

### What did you see instead?

ERROR: /private/var/tmp/_bazel_peter/e52ee941616e71d08aacc980b70e10b0/external/io_bazel_rules_go/go/private/repositories.bzl:90:9: no such package '@net_zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_peter/e52ee941616e71d08aacc980b70e10b0/external/net_zlib/zlib-1.2.11.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//external:zlib'

I have verified it's not transient networking issues `wget https://zlib.net/zlib-1.2.11.tar.gz` works just fine.

**Comment by jayconrod** [comment]
Could you report this in `bazelbuild/bazel`? Any Java exceptions are emitted by Bazel itself, not rules_go.

It sounds like Bazel was unable to establish a connection, due to an internal certificate error. The URL is working outside of Bazel.

**Comment by polds** [comment]
For Future Readers: You pointing out this is Bazel and not rules_go caused me to stumble on https://github.com/bazelbuild/bazel/issues/3915 . Specifically, and sadly, update your [JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). This now works.
