### ISSUE TITLE
How to access the go toolchain from tests

### ISSUE THREAD

**Issue by blico** [bazelbuild/rules_go#2036]
We have several tests that are trying to call go tools such as `go list` and `gofmt`. This is problematic because in Bazel's test environment the go context isn't set up, and runfiles are symlinks so tools reliant on `GOPATH` won't follow the symlinks.

I am curious if there is any recommended way for accessing the go toolchain from tests?

The most related issue I can find is #511

**Comment by jayconrod** [comment]
There's not an automatic way to do this through `go_test`, but the toolchain files are normally available, depending on how you have your WORKSPACE set up.

By default, the toolchain is downloaded into an external repo called `go_sdk`. You can examine it in the directory `$(bazel info output_base)/external/go_sdk`. There are some `filegroups` which provide various subsets of the toolchain. `@go_sdk//:files` contains basically everything.

Be aware that `go list` may have side effects, depending on how it's invoked, especially in module mode. You may need to define a temporary `GOPATH` or `GOCACHE` to use it.

**Comment by blico** [comment]
Thank you Jay!
