### ISSUE TITLE
[Feature Request] Setting TMPDIR to TEST_TMPDIR

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2046]
Tests in Go often use [os.TempDir()](https://golang.org/pkg/os/#TempDir) to create temporary directory to write to. This method uses environment variable `TMPDIR`, or use `/tmp` if it is not set. However, `TMPDIR` or `/tmp` may not be writable on some machines. It would be great if `go_test` rule can set `TMPDIR` to the value of `TEST_TMPDIR` provided by Bazel test.

### What version of rules_go are you using?

0.18.3

### What version of gazelle are you using?

a6448000532153e49f7e0f401428e9c42337c6e1

### What version of Bazel are you using?

0.24.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux, amd64

**Comment by linzhp** [comment]
The path of TEST_TMPDIR is too long in current Bazel's implementation to create UNIX domain sockets in most POSIX systems (https://github.com/bazelbuild/bazel/issues/11089). I am thinking about reverting #2401 so people can create sockets using `ioutil.TempFile("", "unix-socket")` under system's TMPDIR instead of TEST_TMPDIR. Otherwise people will have to explicitly call `ioutil.TempFile("/tmp", "unix-socket")` to create sockets.

@jayconrod what do you think?

**Comment by jayconrod** [comment]
I don't think #2401 should be reverted. Tests should probably use `TEST_TMPDIR` most of the time. It's possible it's a faster file system (tmpfs or something) in some configurations.

UNIX sockets are a fairly narrow use case, so using a shorter directory name just for them seems okay.

**Comment by linzhp** [comment]
Under what circumstance does `TEST_TMPDIR` use tmpfs? Using `--sandbox_tmpfs_path=/tmp` and `--test_tmpdir=/tmp` at the same time would lead to errors like this in Linux:

```
src/main/tools/linux-sandbox-pid1.cc:198: "mount(/tmp/_tmp/8bb6ba865df4a598ed907399eb71ce52, /tmp/_tmp/8bb6ba865df4a598ed907399eb71ce52, nullptr, MS_BIND | MS_REC, nullptr)": No such file or directory
```

So it would be faster if we set `--sandbox_tmpfs_path=/tmp` and unset `TMPDIR`, which defaults to `/tmp` in tmpfs

**Comment by jayconrod** [comment]
I just threw out tmpfs as an example. Not sure if that's used in practice.

In truth, I'm not really sure why both `TMPDIR` and `TEST_TMPDIR` are needed. They seem redundant. Maybe it's useful for tests to use temporary directory separate from the code being tested? I suppose if that's the case, then perhaps #2401 should be reverted.

I don't have a strong opinion here, so if you want to roll back #2401, I'm happy to merge a PR.
