### ISSUE TITLE
new_go_repository chokes on packages that import "."

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#205]
My project includes a dependency on [github.com/tmc/dot](https://github.com/tmc/dot) that, in its tests, includes [the line](https://github.com/tmc/dot/blob/master/dot_test.go#L4):
```go
import (
    dot "."
)
```
This causes Bazel to fail with the message "unrecognized import path "."":
```
$ bazel build :all
...........
ERROR: /Users/tom.payne/go/src/github.com/twpayne/dot-blaze/BUILD:5:1: no such package '@com_github_tmc_dot//': failed to generate BUILD files for github.com/tmc/dot: 2016/11/24 14:58:02 unrecognized import path "."
 and referenced by '//:go_default_library'.
ERROR: Analysis of target '//:go_default_library' failed; build aborted.
INFO: Elapsed time: 77.242s
```
I've attached a sample minimal package (containing just `WORKSPACE`, `BUILD`, and `main.go`) to reproduce the problem. You might need to change the `go_prefix` line in `BUILD` depending on where you install them. Download the zip file: [github.com_twpayne_dot-blaze.zip](https://github.com/bazelbuild/rules_go/files/611499/github.com_twpayne_dot-blaze.zip)

**Comment by jayconrod** [comment]
Closing old issues. The repository has been updated since this issue was filed, and they no longer have this import.

I'm not sure this is actually valid Go code. If the SDK compiles it, it may be a bug there.
