### ISSUE TITLE
[Feature Request] allow statically linking libstdc++ and libgcc in cgo

### ISSUE THREAD

**Issue by gengyl08** [bazelbuild/rules_go#2051]
### What version of rules_go are you using?

0.18.1

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.23.0

### Does this issue reproduce with the latest releases of all the above?

YES

### What operating system and processor architecture are you using?

Ubuntu 18.04 x86_64

### What did you do?

We're trying to build a cgo application using the cdeps attribute. Our goal is to have a binary with libstdc++ and libgcc statically linked. However, in the current go_library target, the default cc toolchain is used and -lstdc++ is always used if cdeps is non-empty. Removing -lstdc++ from CROSSTOOL does not work because other dependencies of our application, for example protobuf, won't build. To solve this problem, a flag in the go_library and go_binary rules that explicitly disables -lstdc++ would be very helpful. Another option is to remove -lstdc++ if -static-libstdc++ is detected in the link options.

**Comment by gengyl08** [comment]
The problem with removing -lstdc++ using CROSSTOOL is: our application has both cgo dependencies and protobuf dependencies. If we remove -lstdc++ using CROSSTOOL, our cgo dependencies link fine. But protobuf cannot be build complaining it cannot find the c++ references (sample of error messages below). So we have to only remove -lstdc++ for cgo but not for protobuf.

In short, some existing go libraries are built with the default CROSSTOOL. Removing -lstdc++ would prevent those libraries from building.

**Comment by gengyl08** [comment]
Sample protobuf error messages with -lstdc++ removed from CROSSTOOL:

.cache/bazel/_bazel_gengyl08/6495583e75166e0f09c0e631e2b1282f/external/com_google_protobuf/BUILD:354:1: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -o bazel-out/host/bin/external/com_google_protobuf/protoc '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) [clone .isra.17]: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function _GLOBAL__sub_I_main: error: undefined reference to 'std::ios_base::Init::Init()'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function _GLOBAL__sub_I_main: error: undefined reference to 'std::ios_base::Init::~Init()'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function main: error: undefined reference to 'operator delete(void*)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function main: error: undefined reference to 'operator delete(void*)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function main: error: undefined reference to 'operator delete(void*)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:function main: error: undefined reference to 'operator delete(void*)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o:main.cc:DW.ref.__gxx_personality_v0: error: undefined reference to '__gxx_personality_v0'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/code_generator.o:code_generator.cc:function void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.42]: error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/code_generator.o:code_generator.cc:function void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.42]: error: undefined reference to 'std::__throw_logic_error(char const*)'

**Comment by jayconrod** [comment]
Closing old issues. I don't think there's anything for rules_go to do here.
