### ISSUE TITLE
Feature request: Workspace-relative file paths in compilation errors

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_go#2061]
I wanted to propose a quality-of-life improvement. Currently, compile errors are passed back to the user verbatim, which on MacOS results in very wide messages due to the sandbox directory.

On the build I just ran, the workspace directory in the sandbox is 104 characters:
```
/private/var/tmp/_bazel_robfig/008081e55e53b945b85110f778538398/sandbox/darwin-sandbox/6/execroot/brain/
```

This adds friction to development:
- Messages often wrap to the next line of my terminal, making them harder to scan / read
- I can not jump directly to the file by copying the path. (Normally I precisely copy the workspace-relative portion of the path). 
- Relatedly, unless you pass --sandbox_debug, those files are already deleted, so you can't even review them (e.g. if they are a third party dependency or generated code).

I propose trimming the paths reported to be workspace relative. That would address the main use case, although figuring out something better for 3rd party deps and generated code would be good too. Maybe a gold plated solution would recognize that case and provide paths in bazel-out (generated) or bazel-WORKSPACE/external (3rd party)

I'm not sure how hard this would be or how to accomplish it. Perhaps the rules could pipe the output through a new Go program that does the filtering?

Any thoughts?

**Comment by whilp** [comment]
This has been a repeated point of friction for our (internal) users. I can't think of a good approach to solve it beyond running a wrapper that unmangles the paths in output. Presumably, this is a problem for other bazel rules beyond rules_go. Does anyone know of a working solution elsewhere that might serve as inspiration?

**Comment by whilp** [comment]
Ah, perhaps —run_under is the right direction:

https://docs.bazel.build/versions/master/user-manual.html#flag--run_under
