### ISSUE TITLE
Lack of documentation go_test -> size

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_go#2098]
We are missing documentation about the option "size" in the bazel rule "go_test".

The page I am referring to is here: https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go_test

Thanks!

**Comment by jayconrod** [comment]
`size` is an [attribute common to all Bazel test rules](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests). I'd rather not document common attributes, since there are a lot of them. Some, like `visibility`, require a lot of explanation.
