### ISSUE TITLE
Coverage tests are broken in Bazel 0.27.0

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2100]
Example: https://buildkite.com/bazel/rules-go-golang/builds/1197#7fba7969-7a88-4201-b0a4-8982d9ebf8d0

* //tests/core/coverage:coverage_test_test
* //tests/core/nogo/coverage:coverage_test
* //tests/core/race:race_feature_test

**Comment by robfig** [comment]
The latest build looks like all these tests are passing, e.g.
https://buildkite.com/bazel/rules-go-golang/builds/3263#ad864e99-1e32-4dfd-a83b-951fa4fad57c

```
//tests/core/coverage:coverage_test                                      PASSED in 16.8s
//tests/core/nogo/coverage:coverage_test                                 PASSED in 5.5s
//tests/core/race:race_test                                              PASSED in 57.3s
```

Closing, but please reopen if I've missed something
