### ISSUE TITLE
Cannot build cgo package on OS that it has no source files for

### ISSUE THREAD

**Issue by zbarahal** [bazelbuild/rules_go#2104]
### What version of rules_go are you using?
github.com/bazelbuild/rules_go/releases/download/0.18.6/rules_go-0.18.6.tar.gz

### What version of gazelle are you using?
github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz

### What version of Bazel are you using?
0.27.0

### Does this issue reproduce with the latest releases of all the above?
I believe these are all the latest

### What operating system and processor architecture are you using?
Linux AMD64

### Any other potentially useful information about your toolchain?

Local development on a Mac, CI on an Ubuntu box

### What did you do?
Building a project that includes a vendored cgo package that only has build files for non Linux OSes.

### What did you expect to see?
I expect the package to successfully build on Darwin (using the CGO files) and on Linux (using no files)

### What did you see instead?
Bazel errors due to no source files.

This is similar to https://github.com/bazelbuild/rules_go/issues/678 and https://github.com/bazelbuild/rules_go/issues/453.

I was able to get the build to work by creating a select statement for `srcs` and passing the full build list in for default and an empty go file for the Linux case. However I would expect Gazelle to be able to generate the dummy file or successfully build with no source files on a platform that doesn't need cgo. @jayconrod suggested the dummy file solution on issue #453.

**Comment by jayconrod** [comment]
It looks like this failure happens on 0.18.6 but not on `master`. The new `GoCompilePkg` can build empty cgo libraries. That will be included in 0.19.0 when it's ready.

Note that although Bazel will be able to build these libraries with the next version of rules_go, the Go command cannot build them. It's better to exclude dependencies on such a library using `select` in `deps`. Gazelle generates these automatically.

**Comment by zbarahal** [comment]
Thanks @jayconrod
