### ISSUE TITLE
How to map coverage files to file locations on disk

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#2108]
Do you have any recomended hacks for mapping coverage information written in standard go path form to their actual locations on disk?

**Comment by jayconrod** [comment]
Sorry, I don't have any specific advice for this. Go tests will write coverage data to the path in the environment variable `COVERAGE_OUTPUT_FILE`. Bazel sets that to a path derived from the test's label, but I don't think there are any stability promises there. You may be able to get the location programmatically by using `--build_event_binary_file` or `--build_event_json_file`, but I haven't tried.

FYI, Go coverage output is currently in the format that `go test` uses, but it will need to be converted to the lcov format in the future so coverage can work across languages.

**Comment by yuany4oujia** [comment]
你们在搞什么啊
