### ISSUE TITLE
Compile actions should include the intended import path

### ISSUE THREAD

**Issue by creachadair** [bazelbuild/rules_go#211]
The [Kythe](http://kythe.io/) tools need to keep track of the (putative) import path of each library being built. It would thus be very helpful if the `go tool compile` invocation included the `-p` flag. I believe the patch below is sufficient to add this.

Absent this, we have to recover that information by various disgusting string hackery, which is further complicated by `go_prefix`, and thus very brittle.

Better still would be if the `-o` output path already had the correct layout for the import mechanism to recognize it—I think that would permit most of the noise in the response file to be removed (the symlink forest is especially pernicious).

```diff --git a/go/def.bzl b/go/def.bzl
index baf535a..fdf6344 100644
--- a/go/def.bzl
+++ b/go/def.bzl
@@ -200,7 +200,8 @@ def emit_go_compile_action(ctx, sources, deps, out_lib, extra_objects=[]):
       ('../' * out_depth) + ctx.file.go_tool.path,
       "tool", "compile",
       "-o", ('../' * out_depth) + out_lib.path, "-pack",
-      "-I", "."
+      "-I", ".",
+      "-p", _go_importpath(ctx),
   ]
 
   # Set -p to the import path of the library, ie.
```

**Comment by pmbethe09** [comment]
SGTM, do you want to send out a PR and assign to me?

**Comment by creachadair** [comment]
Sure, will do, thanks. I'll start with the smaller part. I'd also like to see if we can eliminate the symlink forest, but I'll need to do more extensive testing for that. :)
