### ISSUE TITLE
org_golang_x_tools is almost 4 months old

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2113]
Is it time to upgrade? Since `go_rules_dependencies()` is called very early, it forces all repos to use the old version of `org_golang_x_tools`

**Comment by jayconrod** [comment]
I'll upgrade before the next release, which will be after minimal module compatibility is implemented.

In the mean time, see [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies) for instructions on using a newer version. Note that `org_golang_x_tools` should be declared *before* calling `go_rules_dependencies`, and you'll need to apply the patches in `//third_party` (except the Gazelle patch).

**Comment by Yunji-Leo** [comment]
Able to run gazelle on latest org_golang_x_tools to create the org_golang_x_tools-gazelle.patch. Any guidance on how to create the org_golang_x_tools-extra.patch ?
