### ISSUE TITLE
[Feature Request] mutation testing in go_test_library

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_go#2114]
I'm looking to add mutation testing via the library [go-mutesting](https://github.com/zimmski/go-mutesting). The main blocker I see here is that this library probably depends on standard go pathing.

I haven't investigated it yet, but I wanted to put in a feature request to see what you think.

Thanks

**Comment by jayconrod** [comment]
Seems useful, though I'd like to keep `rules_go` small and focused. I also have very limited bandwidth for new feature work these days.

Is this something that could be implemented with [Go toolchains](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst) and supported in a separate repo?

**Comment by prestonvanloon** [comment]
It could be! I'll give it a try when I have a few free cycles.
