### ISSUE TITLE
go proto import path resolves as package name

### ISSUE THREAD

**Issue by steventangx** [bazelbuild/rules_go#2117]
### What version of rules_go are you using?

io_bazel_rules_go: 0.18.6
bazel_gazelle: 0.16.0
bazel: 0.27.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Centos7, x86_64

### What did you do?

I was in the process of upgrading bazel from 0.21.0 -> 0.27.0, and in doing so, upgraded io_bazel_rules_go to resolve some other downstream dependencies.

Then, I tried running `bazel build //...`, which results in a failure to build due to unexpected import aliasing.

Build file:
```
proto_library(
    name = "myproject_processor_proto",
    srcs = [
        "processor.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:empty_proto",
        "@com_google_protobuf//:struct_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "myproject_processor_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "github.com/myproject/api/processor",
    proto = ":myproject_processor_proto",
    visibility = ["//visibility:private"],
)

go_library(
    name = "go_default_library",
    embed = [":myproject_processor_go_proto"],
    importpath = "github.com/myproject/api/processor",
    visibility = ["//visibility:public"],
)
```

processor.proto file (imports):
```
syntax = "proto3";
package myproject.processor;

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
```

client.go:
```
import (
       "fmt"
       
       "github.com/myproject/api/processor"
)
```

### What did you expect to see?

In our go code we import the proto as `import "github.com/myproject/api/processor"`.
I didn't expect that the import name would alias to `myproject_projector` (the mangled package name).   
This wasn't an issue before using `bazel 0.21.0` and `rules_go 0.16.5`.

### What did you see instead?

```
/bazel_output/sandbox/processwrapper-sandbox/14642/execroot/myproject/internal/app/processor/client.go:9:2
: imported and not used: "github.com/myproject/api/processor" as myproject_processor
```

The imports seemed to be aliased to include what is specified as the package name of the proto, rather than the string of the go_proto_library import path, which is what I expected before upgrading the rules_go version.

**Comment by jayconrod** [comment]
It looks like `myproject_processor` is the package name that protoc-gen-go generates outside of Bazel / rules_go. If it was generating something different before, it's likely due to a bug that has been fixed.

```
$ cat >processor.proto <<EOF
syntax = "proto3";
package myproject.processor;

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
EOF

$ protoc --go_out=. processor.proto
processor.proto: warning: Import google/protobuf/struct.proto but not used.
processor.proto: warning: Import google/protobuf/timestamp.proto but not used.
processor.proto: warning: Import google/protobuf/empty.proto but not used.

$ head processor.pb.go 
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor.proto

package myproject_processor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/struct"
```

I'd strongly recommend using `option go_package` in each .proto file to specify the package name and import path.

```
option go_package = "github.com/myproject/api/processor";
```
