### ISSUE TITLE
go_binary does not build with `bazel coverage`

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#2127]
### What version of rules_go are you using?

master (6b3f7611dd21da0f7b35164ae2acb592009832f2)

### What version of gazelle are you using?

None

### What version of Bazel are you using?

0.27.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS, Ubuntu, amd64

### Any other potentially useful information about your toolchain?

None

### What did you do?

```
bazel coverage //tests/core/go_binary:hello
```

### What did you expect to see?

Build complete successfully.

### What did you see instead?

```
$ bazel coverage //tests/core/go_binary:hello
INFO: Invocation ID: adff400f-5ec7-4b80-863d-af473bbba498
INFO: Analyzed target //tests/core/go_binary:hello (26 packages loaded, 6562 targets configured).
INFO: Found 1 target and 0 test targets...
ERROR: /Users/sbagaria/Workspace/rules_go/tests/core/go_binary/BUILD.bazel:6:1: GoLink tests/core/go_binary/darwin_amd64_stripped/hello failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder link -sdk external/go_sdk -installsuffix darwin_amd64 -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o ... (remaining 12 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/darwin_amd64/link: cannot open file : open : no such file or directory
link: error running subcommand: exit status 2
cannot find package github.com/bazelbuild/rules_go/go/tools/coverdata (using -importcfg)
Target //tests/core/go_binary:hello failed to build
```

I played a `git bisect`, and found the culprit to be 528f6faf83f85c23da367d61f784893d1b3bd72b. The commit immediately before this builds just fine, and so does rules_go 0.18.7 (latest release).

**Comment by siddharthab** [comment]
I can work on this with a little bit of guidance, if you want.

**Comment by jayconrod** [comment]
Fixed the link error in #2129, but this coverage doesn't really work on binaries. The code that writes out cover data is in the generated test main package, and that's not included in binaries. So an instrumented binary will collect data but never write it.

We don't really have a clear story for coverage. At some point in the future, we should make tests write coverage data in lcov format as Bazel expects instead of the Go format. I don't think there's clear guidance on what should be done for binaries.

**Comment by siddharthab** [comment]
Thank you!

Also, good to know that coverage information from binaries is not written out. I was trying to find the coverage data from a test running a binary.

From a user perspective, I will expect any instrumented executable to write out the collected coverage information, not just a test executable.

**Comment by jayconrod** [comment]
> From a user perspective, I will expect any instrumented executable to write out the collected coverage information, not just a test executable.

Agreed, but there are a lot of questions I don't know the answers to. We'd need to inject some code that writes out coverage data after `main` returns. That's difficult in Go. There needs to be a way to specify where the file should be written. It should probably written in lcov format, same as Bazel expects. Anything we do should be similar to other binaries generated by Bazel.

**Comment by siddharthab** [comment]
Ah! Looks like Go [decided against](https://groups.google.com/forum/#!topic/golang-nuts/qBQ0bK2zvQA/discussion) having an atexit like mechanism common in other languages.

The coverage format is also not clear. Last year, there was [talk](https://docs.google.com/document/d/1-ZWHF-Q-qCKf19ik-t33ie58BkNurrYYzKR4OLtcilY/edit#heading=h.9bhixz6dz310) about moving away from lcov and toward Cobertura. So I made rules_r output Cobertura format instead of lcov.

Anyway, all this is off-topic. This issue can be closed.

**Comment by siddharthab** [comment]
My main issue was that we use `bazel coverage //...` to generate coverage for all our tests, but this issue was preventing that workflow. Same issue when you have a go_test that uses a go_binary as a data dependency. Both these use cases are satisfied by the link error fix you made.

**Comment by jayconrod** [comment]
Yeah, I remember the plan was to use Cobertura. Not sure what happened with that. It seems like they're planning to use lcov now.

Will close when #2129 is merged. That should fix errors in `bazel coverage //...` at least.
