### ISSUE TITLE
Debug build broken when assembler is used

### ISSUE THREAD

**Issue by eikemeier** [bazelbuild/rules_go#2144]
Commit https://github.com/bazelbuild/rules_go/commit/528f6faf83f85c23da367d61f784893d1b3bd72b#diff-1d4a1e5e3da947a074e13dee5c205ea5R99 introduced flags that are not understood by the [asm](https://golang.org/cmd/asm/) command.

See also issue #2143.

### What version of rules_go are you using?

0.19.0

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.28.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS (darwin) amd64

### Any other potentially useful information about your toolchain?

Assembly code must be used

### What did you do?

Run https://github.com/eikemeier/hello-go with

```bash
bazel run --sandbox_debug --compilation_mode=dbg //:hello-go
```

### What did you expect to see?

```
Hello, World!
```

### What did you see instead?

```
ERROR: .../external/com_github_golang_snappy/BUILD.bazel:3:1: GoCompilePkg external/com_github_golang_snappy/darwin_amd64_debug/go_default_library%/github.com/golang/snappy.a failed (Exit 1) sandbox-exec failed:
...
    -o bazel-out/darwin-dbg/bin/external/com_github_golang_snappy/darwin_amd64_debug/go_default_library%/github.com/golang/snappy.a -gcflags '-N -l' -asmflags '-N -l')
flag provided but not defined: -N
usage: asm [options] file.s ...
...
compilepkg: error running subcommand: exit status 2
Target //:hello-go failed to build
```

**Comment by prestonvanloon** [comment]
Maybe related: https://github.com/bazelbuild/rules_go/issues/2143 

I think the same PR broke both use cases.

**Comment by dentiny** [comment]
Do you resolved this issue? How to compile with debug mode?
