### ISSUE TITLE
Latest rules_go instructions require unreleased gazelle features

### ISSUE THREAD

**Issue by rickypai** [bazelbuild/rules_go#2145]
### What version of rules_go are you using?

`0.19.0`

```bzl
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "9fb16af4d4836c8222142e54c9efa0bb5fc562ffc893ce2abeac3e25daead144",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.19.0/rules_go-0.19.0.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/0.19.0/rules_go-0.19.0.tar.gz",
    ],
)
```

### What version of gazelle are you using?

`0.17.0`

```bzl
http_archive(
    name = "bazel_gazelle",
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
)
```

### What version of Bazel are you using?

`0.28.0` (unlikely relevant)

```plaintext
$ bazel version
Build label: 0.28.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jul 10 16:17:44 2019 (1562775464)
Build timestamp: 1562775464
Build timestamp as int: 1562775464
```

### Does this issue reproduce with the latest releases of all the above?

Yes (latest releases)

No (using gazelle on HEAD)

### What operating system and processor architecture are you using?

Darwin amd64 (unlikely relevant)

### Any other potentially useful information about your toolchain?

(Unlikely relevant)

### What did you do?

Imported `org_golang_google_grpc` according to instructions in https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#grpc-dependencies

### What did you expect to see?

build succeeds, at least without repository import issues.

### What did you see instead?

```plaintext
$ bazel build //...
INFO: Invocation ID: 6691c325-0d97-4336-8f66-21bdb5c12a34
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:91:1: //external:org_golang_google_grpc: no such attribute 'sum' in 'go_repository' rule
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:91:1: //external:org_golang_google_grpc: no such attribute 'version' in 'go_repository' rule
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:99:1: //external:org_golang_x_net: no such attribute 'sum' in 'go_repository' rule
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:99:1: //external:org_golang_x_net: no such attribute 'version' in 'go_repository' rule
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:106:1: //external:org_golang_x_text: no such attribute 'sum' in 'go_repository' rule
ERROR: /Users/ricky/vsco/src/github.com/rickypai/golang-boilerplate/WORKSPACE:106:1: //external:org_golang_x_text: no such attribute 'version' in 'go_repository' rule
ERROR: error loading package 'external': Package 'external' contains errors
ERROR: Skipping '//...': no targets found beneath ''
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.257s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Particularly,

```plaintext
no such attribute 'sum' in 'go_repository' rule
```

and

```plaintext
no such attribute 'version' in 'go_repository' rule
```

This seems to be due to the instructions requiring go mod support, which was added in https://github.com/bazelbuild/bazel-gazelle/pull/450 into master but has yet been made as a release. Using gazelle on HEAD will get pass this issue.

It seems like either the instructions should be fixed to not depend on go modules, or cut a gazelle release and make the dependency explicit in documentation.

See sample repo (random plug i have a boilerplate repo for golang + bazel):

- rules_go 0.18.x + gazelle 0.17.0 works: https://github.com/rickypai/golang-boilerplate/tree/06f76a30e30a7488a830ec031b98cfe0aab9575e
- rules_go 0.19.0 + gazelle 0.17.0 does not work: https://github.com/rickypai/golang-boilerplate/tree/rpai/rules_go_0_19_0
- rules_go 0.19.0 + gazelle HEAD works (at least gets pass this issue): https://github.com/rickypai/golang-boilerplate/tree/rpai/rules_go_0_19_0_gazelle_master

(There seems to be a separate issue with cross-compilation and `org_golang_x_sys` but I'll file that separately)

Thanks a lot for your work on rules_go and gazelle!

**Comment by eikemeier** [comment]
The instructions say “[you can generate these rules with `bazel run //:gazelle -- update-repos -from_file=go.mod`](https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#grpc-dependencies)”.

The mentioned imported versions are only an example, the current gazelle version doesn't generate them.

So, I assume it's a potentially confusing documentation bug.
