### ISSUE TITLE
Cannot build go_library with bazel_skylib 0.9.0

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_go#2157]
### What version of rules_go are you using?

0.19.1

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.28.1

### Does this issue reproduce with the latest releases of all the above?

Yes. Updated gazelle to 0.18.1 and faced same issue.

### What operating system and processor architecture are you using?

ubuntu 18. linux_amd64

### Any other potentially useful information about your toolchain?

The only thing that changed was that I updated bazel-skylib from 0.8.0 to 0.9.0.

https://github.com/bazelbuild/bazel-skylib/releases/tag/0.9.0

### What did you do?

bazel build //:go_default_library

### What did you expect to see?

Successful build

### What did you see instead?

```
ERROR: /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel:3:1: in go_tool_library rule @io_bazel_rules_go//go/tools/coverdata:coverdata:
Traceback (most recent call last):
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel", line 3
                go_tool_library(name = 'coverdata')
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/rules/library.bzl", line 42, in _go_library_impl
                go.archive(go, source)
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 218, in go.archive
                sets.union(cgo_exports, *[a.cgo_exports for a...])
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/bazel_skylib/lib/new_sets.bzl", line 184, in sets.union
                struct(_values = dicts.add(*[s._values ...]))
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/bazel_skylib/lib/new_sets.bzl", line 184, in struct
                dicts.add(*[s._values for s in args])
        File "/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/bazel_skylib/lib/new_sets.bzl", line 184, in dicts.add
                s._values
object of type 'list' has no field '_values'
```

**Comment by prestonvanloon** [comment]
Looks like others have reported similar issue in bazel-skylib. https://github.com/bazelbuild/bazel-skylib/issues/163#issuecomment-511408099

**Comment by crazyStrongboy** [comment]
> Looks like others have reported similar issue in bazel-skylib. [bazelbuild/bazel-skylib#163 (comment)](https://github.com/bazelbuild/bazel-skylib/issues/163#issuecomment-511408099)

Have you solved this problem？

**Comment by jayconrod** [comment]
Skylib made a breaking change in 0.9.0.

rules_go should stop using the `sets` module, which previously worked on depsets, but is now a separate hash set implementation.

**Comment by GabrielGhe** [comment]
We've run into this issue too. Is there a solution except downgrading to bazel_skylib `0.8.0`?

**Comment by jmhodges** [comment]
I believe this can be closed because of https://github.com/bazelbuild/rules_go/pull/2208 (and, soon, https://github.com/bazelbuild/rules_go/pull/2220)

**Comment by marcus-sa** [comment]
Seems like it's not resolved.

Trying to use Gazelle in Bazel and it throws that error.

```

**Comment by jayconrod** [comment]
@marcus-sa #2220 is not released yet. If new need to use a newer version of Skylib, you'll need to user a newer commit of `rules_go` with `git_repository`.

**Comment by marcus-sa** [comment]
@jayconrod oh cool, thanks.
Any specific commit or just the one you linked to?

**Comment by jayconrod** [comment]
@marcus-sa Tip of `master` should be good. That will make sure you have access to the latest Go security releases.

**Comment by marcus-sa** [comment]
@jayconrod cheers, I'll try it out!
