### ISSUE TITLE
pure=off cannot be passed down to dependencies in go_test

### ISSUE THREAD

**Issue by tanjianfeng** [bazelbuild/rules_go#2167]
### What version of rules_go are you using?

0.18.7/0.19.1

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.26.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux

### What did you do?

After supersede go_binary with go_test, we cannot pass down pure=off:
https://github.com/google/gvisor/blob/master/runsc/container/BUILD#L30.

We'd like to pass down CGO_ENABLED=true when compiling its dependencies.
We've tried setting pure = "off" and static = "on"; but after compile, we still see CGO_ENABLED=false is set in the compile command.

### What did you expect to see?

We'd like to the dependency library is compiled in CGO_ENABLED=true.

**Comment by jayconrod** [comment]
Pure mode is not used by default (that is, cgo is enabled by default). Do you know how it's getting turned on? Are you cross-compiling or targeting a platform where cgo is not enabled? If you're cross-compiling, are you using `--platforms` on the command line or setting the `goos` and `goarch` attributes?

The logic for deciding how a package should be built is in [`get_mode`](https://github.com/bazelbuild/rules_go/blob/d63ad405c5b75d9e8fc50bcd0680e301a50df484/go/private/mode.bzl#L80). Pure mode is forced on if there's no configured C/C++ toolchain or if the `goos` / `goarch` attributes are set (which usually means the C/C++ toolchain targets the wrong platform).

**Comment by tanjianfeng** [comment]
From the compile command, we indeed set the goos and goarch, but it's not cross-compiling:

    CGO_ENABLED=0 \
    GOARCH=amd64 \
    GOOS=linux \
    GOROOT=bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib% \
    GOROOT_FINAL=GOROOT ...

**Comment by jayconrod** [comment]
Closing most old issues. Sorry for now following up on this. Please comment if you're still seeing this issue.

**Comment by mikberg** [comment]
I'm seeing this issue when trying to use [github.com/uber/h3-go](https://github.com/uber/h3-go). Tests importing this library (or libraries which in turn imports it) fail with:

```
exec env - \
    CGO_ENABLED=0 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
(...)
myfile.go:20:20: undefined: empty.FromGeo
myfile.go:20:31: undefined: empty.GeoCoord
```
