### ISSUE TITLE
gazelle can not recognize import path "gopkg.in/yaml.v2"

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#218]
I use the binary of gazelle as a command line tool to generate BUILD files of the third repositories. And it works in most cases. However, when I use gazelle on the third repositories which import "gopkg.in/yaml.v2", it complains `2016/12/07 12:13:34 unrecognized import path "gopkg.in/yaml.v2"`, is it a bug?

**Comment by pmbethe09** [comment]
That does seem like a bug, yes.

**Comment by GinFungYJF** [comment]
Finally I found that it is a network problem:
https://github.com/golang/tools/blob/master/go/vcs/vcs.go#L491
after I set the environment variables of proxy, the gazelle works well.
