### ISSUE TITLE
bazel_testing: more flexibility for running commands

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2189]
The `bazel_testing` package should provide more functions for running `bazel` commands:

* `BazelCmd(args ...string) *exec.Command` - analogous to `exec.Command`, but sets up the environment as `RunBazel` does now.
* `BazelOutput(args ...string) (string, error)` - convenience function for getting stdout. Useful for `bazel info` and `bazel query` commands.

`RunBazel` should be implemented in terms of `BazelCmd`.

**Comment by achew22** [comment]
Would this work?

https://godoc.org/github.com/bazelbuild/bazel-watcher/bazel
https://github.com/bazelbuild/bazel-watcher/blob/master/bazel/bazel.go

I would be happy to upstream it if you're interested.

**Comment by jayconrod** [comment]
@achew22 That does what I need, but I'd prefer a much more minimal API.

I filed this issue because `RunBazel` was not general enough, which caused a Gazelle contributor to duplicate it.

**Comment by achew22** [comment]
Can you help me understand how that API could be made more minimal?

**Comment by jayconrod** [comment]
> Can you help me understand how that API could be made more minimal?

I'd be happy with just a function `BazelCmd(args ...string) *exec.Command`. That's enough for my purposes.

**Comment by jayconrod** [comment]
There are a few things I want to abstract here:

* The location and name of the `bazel` command. In past iterations of Bazel's CI, this has moved around a lot, and it's not always in `PATH`. Currently it is, but I'd like to fix this in one place if it breaks in the future.
* Any required modification to the environment. `RunBazel` currently removes some variable's from the caller's environment.
* Any options required by all commands (resource usage, remote configuration, etc.).

Aside from the mechanics of running a `bazel` command in the test environment, I think just providing an `*exec.Command` gives the most flexibility with a familiar interface.
