### ISSUE TITLE
Weirdly different behavior between darwin and linux when downloading go sdk

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#2191]
### What version of rules_go are you using?

Issue found in 0.19.3, wasn't present in 0.18.6

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.28.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

linux/amd64

### Any other potentially useful information about your toolchain?

Totally bog standard, AFAIK. No remote execution, remote caching, any fanciness like that, except we do use `--distdir` as described below.

### What did you do?

Our repo uses `--distdir` to avoid having to download anything from the internet. Therefore, I have `go1.12.9.linux-amd64.tar.gz` checked into our git LFS server so that it appears in the `.distdir` directory in our repo. I then have `.bazelrc` in the repo point to that directory with the `--distdir` argument.

Upgraded rules_go from 0.18.6 -> 0.19.3, *and* go to 1.12.9

### What did you expect to see?

Everything to basically work just fine

### What did you see instead?

On *only* linux (our CI system -- most devs are using mac os x), we see download failures for the go SDK (we actually configure bazel with a non-standard set of x509 trust roots, which eliminates ~all the ones on the public internet, so this is expected if it's reaching out). This is fixed only when I move `.distdir/go1.12.9.linux-amd64.tar.gz` to `.distdir/go_sdk.tar.gz`. This is super unexpected, but I believe is the result of https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L152, and our build was succeeding under 0.18.6 because we had previously ensured (via `go_download_sdk`) that the go sdk(s) were available on an internal server. That is no longer tenable, so we started using `.distdir`, and the fact that our old go sdk existed on the internal server may have masked this issue.

**Comment by jayconrod** [comment]
This is the first time I've heard of `--distdir`. How does that interact with `ctx.download`? Does it just match out the output file name? If so, that seems extremely brittle; I expect the output filename is very much an implementation detail of the code using `ctx.download` as is the case here.

Why not use an HTTP proxy instead? I'd expect that would cover far more cases. I imagine `--distdir` doesn't cover Git repository fetches for example.

**Comment by swsnider** [comment]
Because using an HTTP proxy requires all developers to set something up locally, and --distdir works across both the CI and local dev environments without extra setup. I hear you though -- distdir seems like a giant hack IMHO

**Comment by swsnider** [comment]
And yeah, it doesn't cover git repo fetches, that's for sure.

**Comment by swsnider** [comment]
Filed https://github.com/bazelbuild/bazel/issues/9227 to report the distdir issue. This can probably be closed because it's probably not a rules_go specific issue.

**Comment by swsnider** [comment]
Actually, it would be *amazing* if in the meantime you could switch it up to use the OS in the outs name, so that I can at least discriminate on that. I get it if that's not really a thing you want to do though.

**Comment by jayconrod** [comment]
PRs welcome 😁 I'd rather not make a blind fix here though.

The output filename doesn't matter for this implementation; it could be set to the last path component of the URL. We just download it, extract it, and delete it. `ctx.download_and_extract` bugs out on some of the file names (something about invalid UTF-8 not making the round trip through Java's UTF-16 representation?), so we need to use the external tar.

**Comment by swsnider** [comment]
Yeah, thanks for your help -- I was able to solve this internally by using the `patches` directive to http_archive with rules_go. I doubt you'll want the patch upstream, but here's what I came up with:

```
diff --git a/go/private/sdk.bzl b/go/private/sdk.bzl
index c72791be..184ec2f9 100644
--- a/go/private/sdk.bzl
+++ b/go/private/sdk.bzl
@@ -137,6 +137,15 @@ def _register_toolchains(repo):
     ]
     native.register_toolchains(*labels)
 
+def _canonicalize_os(name):
+    name = name.lower()
+    if "win" in name:
+        return "windows"
+    elif "mac" in name:
+        return "darwin"
+    elif "nix" in name:
+        return "linux"
+
 def _remote_sdk(ctx, urls, strip_prefix, sha256):
     # TODO(bazelbuild/bazel#7055): download_and_extract fails to extract
     # archives containing files with non-ASCII names. Go 1.12b1 has a test
@@ -146,15 +155,16 @@ def _remote_sdk(ctx, urls, strip_prefix, sha256):
     if urls[0].endswith(".tar.gz"):
         if strip_prefix != "go":
             fail("strip_prefix not supported")
+        sdk_output_name = "go_sdk-{}.tar.gz".format(_canonicalize_os(ctx.os.name))
         ctx.download(
             url = urls,
             sha256 = sha256,
-            output = "go_sdk.tar.gz",
+            output = sdk_output_name,
         )
-        res = ctx.execute(["tar", "-xf", "go_sdk.tar.gz", "--strip-components=1"])
+        res = ctx.execute(["tar", "-xf", sdk_output_name, "--strip-components=1"])
         if res.return_code:
             fail("error extracting Go SDK:\n" + res.stdout + res.stderr)
-        ctx.execute(["rm", "go_sdk.tar.gz"])
+        ctx.execute(["rm", sdk_output_name])
     else:
         ctx.download_and_extract(
             url = urls,
```

**Comment by swsnider** [comment]
Closing because I solved my own problem and this isn't really the repo with the bug.
