### ISSUE TITLE
Create rules_go's equivalent to ijar/compile_jars

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#2193]
Perhaps `rules_go` could have an `ijar`/`compile_jars` equivalent.

Such tool would:
- take a compiled package, say `mypkg.a`
- get its public symbols (via `x/packages`)
- generate Go source that would only contain shim methods/symbols without body
- compile that shim package into another file (say `mypkg.h.a`)
- when compiling modules that depend on `mypkg`, pass `mypkg.h.a` instead of `mypkg.a`
- pass `mypkg.a` at link time

The idea would be that only public api changes would trigger recompilation of downstream packages, and most of the time only linking would happen.

**Comment by jayconrod** [comment]
This is such a good idea that I'm going to de-dup it against #1803. :)

By default, the Go compiler produces archives that contain two files: machine code consumed by the linker, and type information consumed by the compiler for dependent packages.

We could split these into separate output files. Blaze does this within Google. We should do it, too.

**Comment by steeve** [comment]
Nice!!
