### ISSUE TITLE
Why is the size of binary generated by bazel smaller than that generated by go tool ?

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#220]
```
-rwxr-xr-x 1 root root 7885664 Dec  8 15:41 gurl    (by go build)
-rwxr-xr-x 1 root root 5600320 Dec  8 15:35 gurl.bazel  (by bazel build)
```

And both the go version is 1.6.2
bazel version:0.4.0
rules_go tag:0.3.0

**Comment by pmbethe09** [comment]
No idea.
Try running 'go build -x' and then 'bazel build -s' and look at the sizes
of each of the intermediate products?

**Comment by GinFungYJF** [comment]
I run 'go build -x' and 'bazel build -s', and then compare their flags. I found that it is because of the flag '-s' in the link phase. The flag '-s' means omitting the symbol table and debug information, but I need them. So     how to remove the '-s' ?

**Comment by GinFungYJF** [comment]
I run 'go build -x' and 'bazel build -s', and then compared their flags. I found that it is because of the flag '-s' in the 'io_bazel_rules_go_toolchain/bin/go tool link' command during the link phase of 'bazel build'. The flag '-s' means omitting the symbol table and debug information, but I need them. So  how to remove the '-s' ?

**Comment by pmbethe09** [comment]
Presumably we should tie in the use of '-s' to the bazel flag '-c' {opt,
fastbuild, dbg} and only use '-s' for "opt" mode.
