### ISSUE TITLE
Duplicate proto rule providers

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_go#2200]
```console
INFO: From GoLink testgrid/resultstore/linux_amd64_race_stripped/go_default_test:
link: warning: package "github.com/golang/protobuf/ptypes/duration" is provided by more than one rule:
    @io_bazel_rules_go//proto/wkt:duration_go_proto
    @com_github_golang_protobuf//ptypes/duration:go_default_library
```

What is the best way for me to resolve this? Any pointers?

**Comment by jayconrod** [comment]
[Avoiding conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) describes this issue and what to do about it. Does that answer your question?

(Sorry for the slow response, just got back from vacation).
