### ISSUE TITLE
Toolchain Resolution for go_linux_amd64-impl fails on macOS

### ISSUE THREAD

**Issue by Development-Ocktopi** [bazelbuild/rules_go#2215]
### What version of rules_go are you using?

0.19.3

### What version of gazelle are you using?
0.18.1

### What version of Bazel are you using?
0.29.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Developer's Host: Darwin Kernel Version 19.0.0 x86_64 (osx)
Remote Worker: Linux 5010568880c9 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux(Docker container)  (l.gcr.io/google/bazel:latest)
```bash
# worker go version
root@5b7a78b1c745:/# go version
go version go1.12.8 linux/amd64
```

### Any other potentially useful information about your toolchain?

Remote execution

### What did you do?
Defined a platform 
```python
platform(
    name = "linux_x86_64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)
```
Used this for remote build as:

```bash
bazel build --config=ubuntu16-04 --platforms=//platforms:linux_x86_64 --host_cpu=k8 --host_platform=//platforms:linux_x86_64 --toolchain_resolution_debug //:target
```

### What did you expect to see?

Expected the constraints in the platform to match `@go_sdk//:go_linux_amd64_cgo-impl`

### What did you see instead?

```
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_amd64-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//os:os has value @platforms//os:osx, which does not match value @platforms//os:linux from the execution platform @bazel_toolchains//configs/ubuntu16_04_clang/1.2:rbe_ubuntu1604_r352865

INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_amd64_cgo-impl...
INFO: ToolchainResolution:     Toolchain constraint @io_bazel_rules_go//go/toolchain:cgo_constraint has value @io_bazel_rules_go//go/toolchain:cgo_on, which does not match value <missing> from the target platform //platforms:linux_x86_64
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_amd64_cgo-impl, because of target platform mismatch

INFO: ToolchainResolution:   No toolchains found
ERROR: While resolving toolchains for target //:target: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//:target' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```

I expect either of `@go_sdk//:go_linux_amd64-impl` or `@go_sdk//:go_linux_amd64_cgo-impl` to match, however I'm perplexed by the log lines suggesting that `@go_sdk//:go_linux_amd64-impl`'s toolchain constraint:`@platforms//os:os has value @platforms//os:osx`.

Ideally I would have only require `--host-platform` and `--host_cpu`, but even with only those flags, I'm getting similar toolchain resolution failure.

**Comment by amarshat** [comment]
Are you downloading the linux sdk in order for bazel to recognise and use that toolchain?

```
# download the linux sdk for arm64 in your WORKSPACE 
load("@io_bazel_rules_go//go:deps.bzl",  "go_download_sdk")

go_download_sdk(
    name = "go_sdk_linux",
    goos = "linux",
    goarch = "amd64",
    version = "1.12.9”,
)
```

Then you should add the `platforms`, `host_platforms`, `host_cpu` parameters with build.

**Comment by Development-Ocktopi** [comment]
Thank you! That worked, although I'm wondering why a separate download was not required for usual java projects for remote building.
