### ISSUE TITLE
pure+static cgo does not link symbols from "runtime/cgo"

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#2216]
### What version of rules_go are you using?

0.19.4 and HEAD (c44823f9d83597fd22cfed75f063aefc5de429eb).

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

0.28.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux, x86_64

### Any other potentially useful information about your toolchain?

Issue present with both gcc and llvm with lld linker.

### What did you do?

```
bazel build --features=static //tests/core/cgo:pure
```

### What did you expect to see?

A successful build.

### What did you see instead?

```
external/go_sdk/pkg/tool/linux_amd64/link: running /usr/bin/gcc failed: exit status 1
/tmp/go-link-689103257/go.o:go.go:_cgo_callers: error: undefined reference to 'x_cgo_callers'
/tmp/go-link-689103257/go.o:go.go:_cgo_init: error: undefined reference to 'x_cgo_init'
/tmp/go-link-689103257/go.o:go.go:_cgo_mmap: error: undefined reference to 'x_cgo_mmap'
/tmp/go-link-689103257/go.o:go.go:_cgo_munmap: error: undefined reference to 'x_cgo_munmap'
/tmp/go-link-689103257/go.o:go.go:_cgo_notify_runtime_init_done: error: undefined reference to 'x_cgo_notify_runtime_init_done'
/tmp/go-link-689103257/go.o:go.go:_cgo_sigaction: error: undefined reference to 'x_cgo_sigaction'
/tmp/go-link-689103257/go.o:go.go:_cgo_thread_start: error: undefined reference to 'x_cgo_thread_start'
/tmp/go-link-689103257/go.o:go.go:runtime._cgo_setenv: error: undefined reference to 'x_cgo_setenv'
/tmp/go-link-689103257/go.o:go.go:runtime._cgo_unsetenv: error: undefined reference to 'x_cgo_unsetenv'
/tmp/go-link-689103257/go.o:go.go:runtime.cgo_yield: error: undefined reference to '_cgo_yield'
```

**Comment by hectorgimenez** [comment]
Same error with rules version 0.18.10 and Bazel 0.24.1 and 0.29. Using latest gazelle 0.18.2.

**Comment by gebn** [comment]
This appears to be a regression in 0.19.4 - reverting to 0.19.3 fixes it for me.
