### ISSUE TITLE
'@local_config_cc_toolchains//:osx_archs.bzl': file doesn't exist'

### ISSUE THREAD

**Issue by brooksgx** [bazelbuild/rules_go#2221]
### What version of rules_go are you using?

Tried both latest and latest stable versions:
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "0c1081b3618a2c6ca1220f7f7ffb644a2955ddf8",
)

http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.19.4/rules_go-0.19.4.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/0.19.4/rules_go-0.19.4.tar.gz",
    ],
    sha256 = "ae8c36ff6e565f674c7a3692d6a9ea1096e4c1ade497272c2108a810fb39acd2",
)

### What version of gazelle are you using?

0.18.2

### What version of Bazel are you using?

0.29.1-homebrew 

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS

### What did you do?

After updating the toolchain started receiving the following error:

Target '@io_bazel_rules_go//:cgo_context_data' depends on toolchain '@local_config_cc//:cc-compiler-darwin', which cannot be found: error loading package '@local_config_cc//': Unable to load file '@local_config_cc_toolchains//:osx_archs.bzl': file doesn't exist'

**Comment by jayconrod** [comment]
This seems like an issue with your C/C++ toolchain. Do you have Xcode command line tools installed? If not, what toolchain are you using? Are you able to build `cc_binary` targets?

If you want to disable cgo (and the dependency on the C/C++ toolchain), you should be able to do so by passing `--platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64` on the command line.

**Comment by brooksgx** [comment]
I wondered about that - the tool chain was working a couple of days ago and the only system update I recall was a bazel update through homebrew.

`/usr/bin/xcodebuild -version
Xcode 10.3
Build version 10G8`

**Comment by brooksgx** [comment]
I missed your request to rerun with the platform parameter.

`bazel test //... --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64`

gave the same error

**Comment by jayconrod** [comment]
Are you able to build cc_binary targets?

**Comment by brooksgx** [comment]
Yes that seems to work. Cloned git clone https://github.com/bazelbuild/examples/

And ran the stage 3 example

```
> bazel build //...
INFO: Analyzed 3 targets (15 packages loaded, 129 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 2.311s, Critical Path: 0.73s
INFO: 8 processes: 8 darwin-sandbox.
INFO: Build completed successfully, 11 total actions

```

**Comment by jayconrod** [comment]
You mentioned earlier you started seeing this error after updating a toolchain. What toolchain was that? Xcode? Bazel? rules_go?

Some things to try:

* `bazel clean --expunge` is sometimes necessary to purge Bazel's C/C++ autoconfigured toolchains after updating system tools.
* Try building in the example workspace and a Go workspace with `--toolchain_resolution_debug`. Does it pick the same C/C++ toolchain?
* What happens if you set `BAZEL_USE_XCODE_TOOLCHAIN=1` in your environment?
* Any other flags or environment variables that would affect C/C++ toolchain selection and generation?

The `osx_archs.bzl` file is generated by Bazel's C/C++ toolchain automatic configuration in [cc_configure.bzl](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl;l=73?q=cc_configure.bzl). It looks like that file is created as long as Xcode is detected.

**Comment by brooksgx** [comment]
I think this one can be closed. Having built a C++ project I saw some strange behavior when changing back to the other project where bazel build //... tried to build the example but when I changed the build target the build completed without error.

I had already tried `bazel clean --expunge` and ran that again - not clear if it resolved the issue that time around

All very strange and will try to re-create the failure if I can

**Comment by jayconrod** [comment]
Ok, I'll go ahead and close since it doesn't seem like anything can be done from the rules_go side.

If you manage to isolate this further as a C/C++ toolchain issue, the bazel-discuss mailing list may be able to give more useful answers.
