### ISSUE TITLE
Documentation implies that building plugins is not supported when it is

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#2225]
On https://github.com/bazelbuild/rules_go/blob/master/go/modes.rst#link, it says that none of these modes are supported yet, including `plugin`, but #539 says that it's implemented (though potentially with a different value for the flag?). Which is correct? Are there other places in that doc that need to be updated?

**Comment by jayconrod** [comment]
Closing old issues. Sorry for not responding earlier. This seems to be fixed now.
