### ISSUE TITLE
allow selecting go version in go_repositories()

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#223]
It looks like `go_repositories()` roughly follows the latest released go version, without any option for projects to choose an explicit version.

Because there are frequently incompatible changes between go releases, we explicitly choose when to upgrade to a new version, and continue to build patches releases for old releases at the old go version.

As such, it'd be helpful if we could choose which version to use for builds, even if just the minor version (e.g. 1.6, 1.7, 1.8), which would track to the latest patch release (e.g. 1.7.4).

**Comment by hochhaus** [comment]
If you speicy `go_repositories(omit_go=True)` you can supply your own `golang_{darwin,linux}_amd64` http archives. This should let you track the exact version of go that you prefer.

The `rules_closure` docs have some more details and are structured similarly.

https://github.com/bazelbuild/rules_closure#overriding-dependency-versions

Does this meet your needs?

**Comment by gbrail** [comment]
I ran in to this as well -- I wasn't ready for go 1.8 but when I tried to build a project with Bazel it build with 1.8 (and didn't work).

The technique here works fine for a single project. For the record I added the stuff below to WORKSPACE.

One question -- if I have different projects on my box, and each has a different value for that repository below, will Bazel always use the right one for each project? Or will other projects pick up the value? Given that Bazel is trying to produce repeatable builds, I hope that by specifying a Go version in the WORKSPACE we can guarantee that.

```
go_repositories(omit_go=True)
new_http_archive(
  name = "golang_darwin_amd64",
  url = "https://storage.googleapis.com/golang/go1.7.5.darwin-amd64.tar.gz",
  strip_prefix = "go",
)
```

**Comment by jayconrod** [comment]
@gbrail, yes, Bazel will use the right repository for the right project. The target defined in the WORKSPACE here will apply to everything built out of that workspace.

Note however, that only one WORKSPACE file is recognized for a given build. If you import a dependency using, e.g., git_repository or go_repository, the dependency's WORKSPACE file will not be read.

**Comment by treaster** [comment]
Note that rules_go has internal dependencies on specific Go versions as well. e.g. tests in Go 1.8 need to be generated in different ways from Go <1.8.
https://github.com/bazelbuild/rules_go/commit/90342f8401c0ab8e6b9c10b9f819e1ce5e6f0de5

While I definitely like the idea of specifying the Go version in the WORKSPACE, I'm not sure how to make it work unless the rules_go folks want to support a bunch of legacy versions of Go simultaneously. (Of course, if they're willing to take that on, that'd be awesome. :-) )
