### ISSUE TITLE
go_bazel_test not handling data entries now

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#2233]
This is because of 6683d0614ed4170efe596a4d110178ca3a91b243. With it reverted, `go_bazel_test` works correctly.

If you add an entry to the `data` arg of a `go_bazel_test` (say `//go/tools/gopackagesdriver:gopackagesdriver`) , your test will fail with:

```
INFO: From Testing //tests/core/gopackages:gopackages_test:
==================== Test output for //tests/core/gopackages:gopackages_test:
error: unexpected file: go/tools/gopackagesdriver/darwin_amd64_stripped/gopackagesdriver
panic: runtime error: invalid memory address or nil pointer dereference
================================================================================
```

**Comment by jmhodges** [comment]
(Really, I had a `data` and an `args` to add a CLI argument to the `data` file with `$(location)`)

**Comment by jmhodges** [comment]
The panic seems to be because of https://github.com/bazelbuild/rules_go/blob/6683d0614ed4170efe596a4d110178ca3a91b243/go/tools/bazel_testing/bazel_testing.go#L213

That line `nil`s the `cleanup` func that's immediately unconditionally deferred at https://github.com/bazelbuild/rules_go/blob/6683d0614ed4170efe596a4d110178ca3a91b243/go/tools/bazel_testing/bazel_testing.go#L114-L115

There's two similarly named errors and quick change to them shows that the one that triggers is because there's no `external/` at the start of the file path for the `gopackagesdriver` binary I'm passing in. https://github.com/bazelbuild/rules_go/blob/6683d0614ed4170efe596a4d110178ca3a91b243/go/tools/bazel_testing/bazel_testing.go#L273

Unfortunately, I'm not quite able to figure out why this code wants an `external/` prefix from context. The code first showed up in the initial commit bazel_testing (fabf03c1cd31bcf15fb945d932cef322b242be3a). 

So, the `flag.Args` is what was used to be the source in that `external/` checking loop before  https://github.com/bazelbuild/rules_go/commit/6683d0614ed4170efe596a4d110178ca3a91b243 was committed to fix the passing of flags in. And now we use the `files` variable.

I've put what was in `flag.Args` previously and what's in `files` now in a gist: https://gist.github.com/jmhodges/06c3b8c71cd89a760044f8b934819b60

Here's the diff between the two:

```diff
--- pre	2019-09-27 00:45:47.000000000 -0700
+++ post	2019-09-27 00:46:48.000000000 -0700
@@ -1,4 +1,4 @@
-[external/io_bazel_rules_go/BUILD.bazel
+[go/tools/gopackagesdriver/darwin_amd64_stripped/gopackagesdriver
 external/io_bazel_rules_go/WORKSPACE
 external/io_bazel_rules_go/extras/BUILD.bazel
 external/io_bazel_rules_go/extras/bindata.bzl
@@ -121,5 +121,4 @@
 external/io_bazel_rules_go/third_party/go_googleapis-gazelle.patch
 external/io_bazel_rules_go/third_party/org_golang_google_genproto-gazelle.patch
 external/io_bazel_rules_go/third_party/org_golang_x_tools-extras.patch
-external/io_bazel_rules_go/third_party/org_golang_x_tools-gazelle.patch
-external/io_bazel_rules_go/third_party/sanitize_patch_dates.go]
+external/io_bazel_rules_go/third_party/org_golang_x_tools-gazelle.patch]
```

So, an initial BUILD.bazel goes missing, the gopackagesdriver binary gets added, and the sanitize_patch_dates.go file disappears from the list, too.

It's late here, so I'm going to hop off to bed.

**Comment by jmhodges** [comment]
Btw, it looks the data file I passed in does exists at that path. I'm not sure what to make of that.

**Comment by jmhodges** [comment]
Not sure what to do about this one but happy to help with some direction!

I've had to revert it to keep working in my gopackagesdriver branch.

**Comment by jayconrod** [comment]
Looked into this a bit, but I wasn't able to reproduce it. #2237 will at least fix the panic when calling `cleanup`.

`setupWorkspace` needs to know the workspace name and the path within the workspace for each file. That's needed to locate files on Windows (using `bazel.ListRunfiles`) and to place files in the test directory. My expectation was that each path generated with `$(locations ...)` would be of the form `external/workspace_name/path_within_workspace`. That doesn't seem to be the case here. What does the path actually look like? Where is the target with respect to the test?

**Comment by jmhodges** [comment]
I pushed a reproduction to [jmhodges/go_bazel_test_data_repro](https://github.com/jmhodges/rules_go/tree/go_bazel_test_data_repro)

Run:
  
```
bazel test //tests/core/dataargtest:dataargtest_test  --test_output=errors
```

Hopefully, that reproduces on your side, too. (I'm on bazel 0.29.1)

**Comment by jmhodges** [comment]
And it seems to be the `args` setting that causes the problem. If you delete it, the problem resolves (but your flag in the test will not be set, of course)

**Comment by jmhodges** [comment]
Small ping! (A ping asking if that repros for you, not for a solution)

**Comment by jayconrod** [comment]
Yes! That example was very helpful. I was able to reproduce it last night but didn't have time to send a PR.

#2239 should fix it. Turns out I forgot how slices work.

**Comment by jmhodges** [comment]
Who amongst us hasn't forgotten how slices work? Thanks much!

**Comment by jmhodges** [comment]
Hey, so I tested this fix, and now it's saying the test's `os.Open` can't find the binary file at the path that was passed in (`go/tools/builders/darwin_amd64_stripped/md5sum`).

I'm not sure how to fix this up.

**Comment by jmhodges** [comment]
(That's the repro's test, I mean.)

**Comment by jmhodges** [comment]
Interestingly, it looks like the `md5sum` label in `data` isn't getting the `md5sum` file added to arguments passed in the `os.Args` that `bazel_testing.TestMain` is seeing.

This is with bazel 1.0.0. 

Unfortunately, I upgraded bazel and it's been hard for me to downgrade to test previous behavior.

**Comment by jmhodges** [comment]
Patching in `bazel_testing/def.bzl` to `["$(locations {})".format(t) for t in kwargs["data"]]` to the `kwargs["args"]` array gets us back to the `external/` "unexpected file" error.

**Comment by jayconrod** [comment]
Are you running `bazel.RunFile`, `bazel.FindBinary` or a similar function after the call to `bazel_testing.TestMain`? As part of the workspace construction, `bazel_testing.TestMain` changes the working directory to be the root directory of the workspace. That means relative paths passed to `bazel.RunFile` will no longer be meaningful. The best approach here is to resolve runfiles before calling `bazel_testing.TestMain` or capture the working directory at that point and resolve them manually later with `bazel.ListRunfiles`.

**Comment by jmhodges** [comment]
Ahh, I thought that bazel_testing.TestMain was handling some of the problems that might crop up with  `$(location ..)` calls using symlinks or some such. My b. Thanks!

I was calling `os.Open` on the path passed in by `$(location //go/tools/builders:md5sum)` at https://github.com/jmhodges/rules_go/blob/20c5414a7f764276bc94aa7cc5fb40d68abf4f0c/tests/core/dataargtest/dataargtest_test.go#L49

Doing some pwd work and plopping it does get the test to pass: https://github.com/jmhodges/rules_go/blob/20c5414a7f764276bc94aa7cc5fb40d68abf4f0c/tests/core/dataargtest/dataargtest_test.go#L19-L23
