### ISSUE TITLE
Can't use rules_go toolchain as `toolchains` attribute in genrule

### ISSUE THREAD

**Issue by gkousik** [bazelbuild/rules_go#2255]
### What version of rules_go are you using?
0.20.1

### What version of gazelle are you using?
0.17.0

### What version of Bazel are you using?
1.1.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
`Linux x86_64`

### Any other potentially useful information about your toolchain?
None

### What did you do?
I have a genrule like:

```
genrule(
    name = "foo",
    srcs = [],
    outs = ["foo.txt"],
    cmd = "touch foo.txt > $@",
    toolchains = [
        "@io_bazel_rules_go//go:toolchain",
    ],
)
```

### What did you expect to see?
That this toolchain is successfully provided to the execution of the genrule.

### What did you see instead?
```
'@io_bazel_rules_go//go:toolchain' does not have mandatory providers: 'TemplateVariableInfo'
ERROR: Analysis of target '//foo:bar' failed; build aborted: Analysis of target '//foo:bar' failed; build aborted
INFO: Elapsed time: 0.662s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 9 targets configured)
```

**Comment by jayconrod** [comment]
Could you explain more about the problem you're trying to solve? The example you gave reproduces the error, but I don't understand why you'd want to use a Go toolchain in a `genrule`.

This is the first time I've heard of the `toolchains` attribute of `genrule`. The documentation says this:

```
The set of toolchains that supply "Make variables" that this target can use in some of its attributes. Some rules have toolchains whose Make variables they can use by default.
```

The Go toolchain does not provide any variables like this. I guess `TemplateVariableInfo` is how they would be provided. What variables do you need? Why not consume the toolchain in a regular rule instead of a `genrule`?

**Comment by gkousik** [comment]
Sure, I'm trying to build a go-plugin based on some C++ libraries (using SWIG). I also build some C++ libraries as part of that, and after the C++ libraries are built, I want to use the same `go_sdk` used by bazel to call `go build -buildmode=plugin <sourcefiles>`.

I need to use the same `go_sdk`, so that the plugin can be built with the same version of go-compiler that all of our other go-tooling uses.

**Comment by gkousik** [comment]
The actual genrule looks something like this:

```
genrule(
name = "buildwithswig",
cmd = "run-build.sh > $@",
srcs = ["foo.go"],
toolchains = [ "@io_bazel_rules_go//go:toolchain", ],
outputs = ["someplugin.so"],
```

and in the `run-build.sh` file:

```
#!/bin/bash

<...
code to clone and build C++ libraries
...>

go build -buildmode=plugin foo.go
```

**Comment by jayconrod** [comment]
I can't speak for building C/C++, but running `go build` in a `genrule` is not supported.

For building a plugin, your best option is likely [`go_binary`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-binary) with `linkmode = "plugin"`. You can set `cgo = True`, and pull in any C/C++ files to build directly in `srcs` and C/C++ libraries to link against in `cdeps`.

Writing a custom rule that uses the [toolchain API](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst) directly is also an option.

I'd still advise against using `go build` in either situation though. The go command is an entirely separate build system with its own cache and dependency system which both will need to be set up in the sandbox and which tend to change from release to release. Use the toolchain functions like `go.archive`, `go.link`, or use the compiler and linker directly.

**Comment by gkousik** [comment]
I'm using swig to make go talk to C++ classes, and unfortunately `go_binary` does not support swig currently (based on caveats here https://github.com/bazelbuild/rules_go#overview). 

I'll try writing a custom rule and using the toolchain API.
