### ISSUE TITLE
Support supplying test arguments through rule

### ISSUE THREAD

**Issue by tommyknows** [bazelbuild/rules_go#2256]
rules_go allows supplying `--test-arg` on the command line.
This is nice, but we have more than one test that we'd like to run, and they may need different arguments.

Would it be possible to instead support passing additional arguments through the rule-specification?

Example:
```bzl
go_test(
    name = "my_test",
    srcs = ["bla_test.go"],
    arguments = [
        "-my-test-arg=\"Hello World\"",
        "-my-other-arg=\"Goodbye\""
    ],
)
```

Reason is that I would like to write a wrapper around the `go_test`, that supports resolving stamps for some arguments, or supply the path / directory of a target that the test depends on.

Thanks

**Comment by jayconrod** [comment]
`go_test` already supports an `args` attribute. It's one of the [built-in test attributes](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests) that all tests support like `name`, `timeout`, `size`, `visibility`. Does that work for you?

**Comment by tommyknows** [comment]
ah alright! 
Yes, that works.
Sorry for wasting your time & thanks for the quick help!🙂
