### ISSUE TITLE
Investigate proto_library deprecation and rules_proto toolchains

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2266]
The native [`proto_library`](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library) rule is deprecated. The official replacement is [rules_proto](https://github.com/bazelbuild/rules_proto), which is implemented in Starlark.

rules_proto has its own toolchains. `go_proto_library` should support this. We may need to support both the native and Starlark `proto_library` implementations for a while.

**Comment by prestonvanloon** [comment]
Is there any migration path or design doc for how to create a rules_proto_toolchain?

**Comment by jayconrod** [comment]
@prestonvanloon https://github.com/bazelbuild/rules_proto is probably the right place to ask. They don't currently define any toolchains or toolchain types though.

**Comment by prestonvanloon** [comment]
Thanks!

**Comment by drigz** [comment]
Was this fixed by #2333?

**Comment by jayconrod** [comment]
Yes this can be closed now.
