### ISSUE TITLE
Switching between multiple Go toolchain from build CLI options

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2267]
We have a custom Go toolchain to be enabled for a small number of builds, but not for all builds in the repo. I know we can use [go_download_sdk](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go-download-sdk) from a custom location and register the custom Go toolchain. So one solution is to patch the WORKSPACE file whenever we want to build with the custom Go toolchain.

For other languages, people are able to switch compilers, SDKs and toolchains with `--android_sdk`, `--proto_compiler`, `--java_toolchain`, `--apple_sdk`, etc. Can we do something similar with Go?

**Comment by jayconrod** [comment]
The flags you mentioned are used by the native Bazel rules. Rules implemented in Starlark cannot define flags like this.

`--extra_toolchains` may be what you need though. It lets you provide a comma-separated list of toolchain labels, and they'll be registered as if passed to `register_toolchains` in WORKSPACE.
