### ISSUE TITLE
doc how to bump x/tools for gopackagesdriver

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#2272]
There's been a bunch of improvements to x/tools and specifically around the lsp stuff that'll make it easier for #512 to get done. Stuff like adding the GOPACKAGESPRINTDRIVERERRORS env var so we don't have to set up weird log file tail'ing to get the output from gopackagesdriver. https://github.com/golang/tools/commit/5e247c9ad0a0a5f0032a0bfb2d1eb6e0dca10318

I'd like to propose a bump, but I'm not completely sure how the patches were generated in `//third_party` so I can update them. Maybe I've just missed where those scripts are stored?

**Comment by jayconrod** [comment]
There's some documentation on updating dependencies in general on the [Updating dependencies](https://github.com/bazelbuild/rules_go/wiki/Updating-dependencies) wiki page. It doesn't say much about x/tools specifically. I think the only extra step for x/tools is to add a `go_tool_library` for any new packages in `go/analysis/passes` and anything those packages transitively depend on.

I don't typically accept PRs to update dependencies, though if it helps you with gopackagesdriver development I'm happy to do so. 

My normal process is to update all dependencies at once before a new minor release, which happens about once a quarter. Dependency updates can't be backported to old release branches, so there's not usually much point in updating them more often than that.
