### ISSUE TITLE
linkmode=plugin does not work with multiple plugins per binary

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#2277]
### What version of rules_go are you using?

0.19.5

### What version of gazelle are you using?

0.18.2

### What version of Bazel are you using?

1.1.0-homebrew

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

darwin/amd64

### Any other potentially useful information about your toolchain?

Bog standard

### What did you do?

Built two different go_binary(linkmode="plugin") targets, load them in the same program.

### What did you expect to see?

Both plugins load, and execute

### What did you see instead?

Program calls the first plugin twice.

This is probably https://go-review.googlesource.com/c/go/+/60910/

**Comment by jayconrod** [comment]
I tried this out but it seemed to work. Could you post an example gist or repo that reproduces this?
