### ISSUE TITLE
release-0.20 release with (#2269)

### ISSUE THREAD

**Issue by r-hang** [bazelbuild/rules_go#2278]
Hey rules_go team!

I saw that (#2269) was recently merged to the release-0.20 branch. I was wondering when there would be an official release containing that commit!

**Comment by jayconrod** [comment]
#2269 was already released as part of [v0.20.2](https://github.com/bazelbuild/rules_go/releases/tag/v0.20.2), but that wasn't reflected in the release notes. I've updated the release notes. Thanks for calling that out.

**Comment by r-hang** [comment]
Thanks for the update!
