### ISSUE TITLE
bazel_testing doesn't allow you to set `chmod +x` on files

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#2281]
### What version of rules_go are you using?

HEAD

### What version of gazelle are you using?

HEAD

### What version of Bazel are you using?

Build label: 1.0.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux AMD64

### What did you do?

```
const mainFiles = `
-- simple/test.sh --
printf "Started!"
-- environment/BUILD.bazel --
sh_binary(
 name = "test",
 srcs = ["test.sh"],
)               

func TestMain(m *testing.M) {                                                               
  bazel_testing.TestMain(m, bazel_testing.Args{
   Main: mainFiles,
 })                                                                                        
}

func TestBazel(t *testing.T) {
  if _, err := bazel_testing.BazelOutput("build", ":test"); err != nil {
    t.Fatalf("Error building: %v", err)
  }
}
```

### What did you expect to see?

I expect this to succeed.

### What did you see instead?

```
failed to create symbolic link 'test': file 'test.sh' is not executable
```

Is there a correct way to set executable bit on the test data with this setup? I have a bunch of tests that depend on the target being set. I can definitely move everything into a `setUp` method, but I would prefer to do it either in `TestMain` or in `init`. Do you have any theories on how to do this? Could I add a "SetUp" method to the Args that go into `bazel_testing.TestMain` for example?

**Comment by jayconrod** [comment]
> Do you have any theories on how to do this? Could I add a "SetUp" method to the Args that go into bazel_testing.TestMain for example?

That seems like a good way to handle this.
