### ISSUE TITLE
`rules_go` does not support identifying `@io_bazel_rules_go` with `@`

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_go#2285]
### What version of rules_go are you using?

HEAD, i.e.,  b8db84a2f3fd7fac1801ddef376a549c2d83b682
### What version of gazelle are you using?

n/a

### What version of Bazel are you using?

HEAD (after https://github.com/bazelbuild/bazel/commit/81b57d605de823f8e6f846a06d8e50d9a00041e3)

### Does this issue reproduce with the latest releases of all the above?

n/a

### What operating system and processor architecture are you using?

not OS specfic

### Any other potentially useful information about your toolchain?

see https://github.com/bazelbuild/continuous-integration

### What did you do?

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281

### What did you expect to see?

passing test

### What did you see instead?

- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281#ffbfcb90-d83a-4c54-a0dd-48b6f9b74680
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281#4c4875ad-e973-4af1-ac72-3ae3cfb6318f
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281#e81a9d4e-21e7-408b-9ec8-58483cbd6f0d
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281#e81a9d4e-21e7-408b-9ec8-58483cbd6f0d

### Futher information

`rules_go` assumes at various places that bazel-generated artifacts have a path starting with `external`. This is wrong if `rules_go` is the main repository. Examples include https://github.com/bazelbuild/rules_go/blob/b8db84a2f3fd7fac1801ddef376a549c2d83b682/go/tools/bazel_testing/bazel_testing.go#L297

Tracking issue is https://github.com/bazelbuild/bazel/issues/10246

Background on the change https://github.com/bazelbuild/bazel/issues/7130

**Comment by jayconrod** [comment]
#2285 should fix this for newer integration tests (using `go_bazel_test`).

There are still a number of failing integration tests using the old `bazel_test` framework. It will take a few days to migrate those tests to the new `bazel_test` framework (#1959).

**Comment by jayconrod** [comment]
As of #2303, all the rules_go tests have been upgraded to use the new test framework, which is fixed with respect to this flag. I'll delete the old test framework shortly.

I'll wait to make sure the next run of https://buildkite.com/bazel/bazel-at-head-plus-downstream is fixed before closing this.
