### ISSUE TITLE
Typo in v0.20.2 release notes

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_go#2292]
The [release notes](https://github.com/bazelbuild/rules_go/releases/tag/v0.20.2) for v0.20.2 are rather confusing, stating that "Go 1.13.4 and 1.12.13 are **not** supported." Looking at previous release notes and commit messages, it would seem that they are indeed supported in this pre-release.

![bWEdBcYvsdi](https://user-images.githubusercontent.com/196617/69466479-7cde2980-0d84-11ea-88b0-2e552f355d19.png)

**Comment by jayconrod** [comment]
Fixed, thanks for pointing that out.
