### ISSUE TITLE
go_test for internal functions

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#231]
Hello,

I'm trying to test internal function in the same package.
Should I put all sources in go_test for this?

```
a.go():
package a

func aa() string {}

a_test.go():
package a

func TestAa(...) {
   a := aa()
}

BUILD:
go_library(
    name = "go_default_library",
    srcs = [ "a.go"],
)
go_test(
    name = "a_test",
    srcs = [ "a_test.go"],
    deps = [":go_default_library"],
)
```
In this case, a_test.go can't resolve `func aa()`.
Is this expected?

**Comment by junghoahnsc** [comment]
It seems to work when I used `library` instead of `deps`.
I couldn't find a doc on `library` attributes. Is this a supported attribute?

**Comment by pmbethe09** [comment]
Yes, library = ":go_default_library".
The documentation is probably a bit light, but if you use the gazelle tool,
it would just do that for you

**Comment by jayconrod** [comment]
Closing some old issues. The `library` attribute is documented now.
