### ISSUE TITLE
rules_go failing with Bazel@HEAD+Downstream on Windows

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_go#2310]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1305#f0bc62a0-28fe-40e8-84fc-7485878c6189

Most tests fail with:
```
error: could not load default workspace name: open WORKSPACE: The system cannot find the file specified.
```

**Comment by jayconrod** [comment]
Thanks for reporting. This is most likely coming from the rules_go integration test framework. I'll take a look soon.

**Comment by jayconrod** [comment]
Looks like the issue was resolved. rules_go is now green in Bazel@Head + Downstream.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1310
