### ISSUE TITLE
Wrong hash of `go1.13.3.linux-amd64.tar.gz`

### ISSUE THREAD

**Issue by emranbm** [bazelbuild/rules_go#2312]
I noticed that there is a wrong hash of the file `go1.13.3.linux-amd64.tar.gz` here!!
https://github.com/bazelbuild/rules_go/blob/3762b89ad8b1d71007a4a07b194a48d505613c15/go/private/sdk_list.bzl#L51
The true (sha256sum) hash is: `8cdd475462b5cce485b377ba22321e942fc35b458d821ddf7c5fbce12e1d9ccb`.  
It causes Bazel to re-download the file, even if it's present in the `--distdir`.

**Comment by jayconrod** [comment]
The current hash seems correct. The hash `0804bf02020dceaa8a7d7275ee79f7a142f1996bfd0c39216ccb405f93f994c0` in `sdk_list.bzl` is what's listed on https://golang.org/dl/, and it's also what I'm seeing when downloading.

```
$ curl https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  114M  100  114M    0     0  22.3M      0  0:00:05  0:00:05 --:--:-- 23.2M
0804bf02020dceaa8a7d7275ee79f7a142f1996bfd0c39216ccb405f93f994c0  -
```
