### ISSUE TITLE
v0.20.x external dependency break with 'missing strict dependencies'

### ISSUE THREAD

**Issue by dayfine** [bazelbuild/rules_go#2313]
### What version of rules_go are you using?

0.20.3

### What version of gazelle are you using?

0.19.1

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac OS Catalina 2.9GHz Dual Core

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

I updated my rules_go from 0.19.0 to 0.20.3 and bazel from 0.18.1 to 0.19.1 and then saw this *regression*.
I have an external repository (built with Bazel) that I included in workspace  and use it as dependency in go build targets.

```python
# WORKSPACE
go_repository(
    name = "com_github_dayfine_base-go",
    commit = "3aeebe3e6e13fea583050bca3d64edf5a526c795",
    importpath = "github.com/dayfine/base-go",
)

# BUILD
go_test(
    name = "go_default_test",
    srcs = ["xxx_test.go"],
    embed = [":go_default_library"],
    deps = [
        "@com_github_dayfine_base-go//base/testing:go_default_library",
    ],
)

# xxx_test.go
import (
  "testing"

  . "github.com/dayfine/base-go/base/testing"
)

```

See actual code at https://github.com/dayfine/black_sholes/pull/3/files

### What did you expect to see?

Targets build, as they were before I updated rules_go from 0.19.x to 0.20.x.

### What did you see instead?

```
compilepkg: missing strict dependencies:
	/private/var/tmp/_bazel_$username/$hash/sandbox/darwin-sandbox/9/execroot/black_sholes/option/model_test.go: import of "github.com/dayfine/base-go/base/testing"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
```

**Comment by jayconrod** [comment]
The library `@com_github_dayfine_base-go//base/testing:go_default_library` is imported as `github.com/dayfine/base-go/base/testing`, but its `importpath` in [`@com_github_dayfine_base-go//base/testing:BUILD.bazel`](https://github.com/dayfine/base-go/blob/master/base/testing/BUILD.bazel) is `github.com/dayfine/base/base/testing`. They have to match.
