### ISSUE TITLE
allow to specify GOROOT directly, instead of `root_file`

### ISSUE THREAD

**Issue by flokli** [bazelbuild/rules_go#2314]
### What version of rules_go are you using?
v0.20.3

### What version of gazelle are you using?
v0.19.1

### What version of Bazel are you using?
0.29.0

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
NixOS 19.09, x86_64-linux

### What did you do?
```
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(go_version = "host")

gazelle_dependencies(go_sdk = "go_sdk")

# gazelle:repository_macro go_repositories.bzl%go_repositories
load("//:go_repositories.bzl", "go_repositories")

go_repositories()
```

We do use the host go, which is provided via a nix-shell.
We don't use `go_wrap_sdk` to pass it in.

### What did you expect to see?
`rules_go` using the provided go sdk successfully

### What did you see instead?
Bazel stumbles over the fact that `${pkgs.go}/share/go` doesn't contain a `README.md` file:

```
ERROR: error loading package '': Encountered error while reading extension file 'buildifier/deps.bzl': no such package '@com_github_bazelbuild_buildtools//buildifier': no such package '@bazel_gazelle_go_repository_cache//': no such package '@go_sdk//': Traceback (most recent call last):
	File "/home/usercache/bazel/_bazel_user/9923957c70cd7b59bec21e32af97c8be/external/io_bazel_rules_go/go/private/sdk.bzl", line 114
		str(ctx.path(ctx.attr.root_file).dir...)
	File "/home/user/.cache/bazel/_bazel_user/9923957c70cd7b59bec21e32af97c8be/external/io_bazel_rules_go/go/private/sdk.bzl", line 114, in str
		ctx.path(ctx.attr.root_file)
Not a regular file: /home/user/.cache/bazel/_bazel_user/9923957c70cd7b59bec21e32af97c8be/external/go/share/go/README.md
```

It's a bit more complicated, as `${pkgs.go}/share/go` only contains directories:
```
⇒  ls -la /nix/store/sz7mgf91bxd3xpxgqjzgr2avl9cshlz8-go-1.13.5/share/go/                                                                                      
dr-xr-xr-x - root  1 Jan  1970 .
dr-xr-xr-x - root  1 Jan  1970 ..
dr-xr-xr-x - root  1 Jan  1970 api
dr-xr-xr-x - root  1 Jan  1970 bin
dr-xr-xr-x - root  1 Jan  1970 doc
dr-xr-xr-x - root  1 Jan  1970 lib
dr-xr-xr-x - root  1 Jan  1970 misc
dr-xr-xr-x - root  1 Jan  1970 pkg
dr-xr-xr-x - root  1 Jan  1970 src
```

Why do we rely on that `README.md` in first place? It seems `rules_go` determines the `GOROOT` successfully, so can't we just be happy with only that?

In most places, we just use `root_file.dirname` anyways…

**Comment by jayconrod** [comment]
How is `go_wrap_sdk` getting called? I don't think anything in the WORKSPACE snippet you posted would call it, and I can't think of anything in rules_go or Gazelle that would call it with `README.md`.

**Comment by flokli** [comment]
There is no call to `go_wrap_sdk` in my `WORKSPACE` at all.

I tried building it again, after disabling `--remote_http_cache` and purging my local cache, and it seems to work now - so I suspect some of the intermediate cache results not getting properly invalidated.

I don't think it's an issue with `rules_bazel` or gazelle - sorry for the noise.
