### ISSUE TITLE
Support godefs generation

### ISSUE THREAD

**Issue by ajguerrer** [bazelbuild/rules_go#2324]
I would like to submit this issue as a feature request to track support for a Bazel rule for  `go tool cgo -godefs` code generation.

Given a set of definitions in a C header file, I would like to generate an equivalent set of definitions in pure go for use in a `go_library` or `go_binary` without requiring cgo. Running `go tool cgo -godefs` can do exactly that, but it looks like there isn't any Bazel support for it yet. 

Note, the command takes a cgo-style file as input and outputs pure go to standard out. Once generated, I would like the output to serve as a replacement for the input file. In other words, I have no need to specify a custom output path.

**Comment by ajguerrer** [comment]
Perhaps instead of writing a new rule, a new boolean attribute, `godefs = False (default)` could be added to `go_library`, `go_binary`, etc. If `True`,This attribute would run each of the `srcs` through `go tool cgo -godefs` before compiling. That might work too.

**Comment by ajguerrer** [comment]
After learning more about Cgo and Bazel, I do not think I have a use case for this anymore. Looks like `go_library` with `cgo = True` works just fine for me. 

I realize now that my main concern was what happens when a unused contant/struct is added to a C header provided in the `srcs` of a `go_library`. It turns out that Bazel and rules_go is smart enough to notice when the `go_library` has actually changed. 

For example,

```python
go_binary(
    name = "my_binary",
    srcs = ["main.go"],
    embed = [":my_library"],
)

go_library(
    name = "my_library",
    srcs = [
        "foo.go",
        "foo.h",
    ],
    cgo = True,
    importpath = "github.com/bazelbuild/rules_go/my_library",
    visibility = ["//visibility:public"],
)
```
```c
// foo.h
#define MY_FOO 1
```

```go
// foo.go
package main

// #include "foo.h"
import "C"
import "fmt"

const MyFoo int32 = C.MY_FOO

func main() {
	fmt.Println(MyFoo)
}
```
Bazel will not build a new  `my_binary` if I add `#define MY_BAR 2` to `foo.h`. That's exactly what I want, so I'm closing this issue.

**Comment by jayconrod** [comment]
@ajguerrer Glad you got this sorted out.

Sorry for the slow response btw. I just got back from the holidays and am working through a long backlog of issues and reviews.
