### ISSUE TITLE
Set -test.v only for go_test targets

### ISSUE THREAD

**Issue by robbertvanginkel** [bazelbuild/rules_go#2344]
We're using `--test_arg=-test.v` in our `.bazelrc` to make sure all tests run in verbose mode to later use `github.com/jstemmer/go-junit-report` for creating a junit testreport.

Now that we're adding some non-go test targets to our repo, using `bazel test --test_arg=-test.v` on a mix of test target types fails as some of the testrunners understandably don't know what to do with `-test.v`.

Is there a recommended way in Bazel to pass flags to only to a specific set of test targets? So far we've had the following ideas to deal deal with this:
- Wrap `go_test` from `@io_bazel_rules_go//go:def.bzl` in our own macro that adds `-test.v` to the target's `args` if its not present.
- Maintain a small patch on rules_go that sets `test.v` from `generate_test_main.go` based on an environment variable being set.

As we try to stay as close to upstream rules_go as possible, neither the patch or wrap approach seems ideal. Any suggestions on a maintainable way we could run all go test targets with `-test.v`?

**Comment by robbertvanginkel** [comment]
Is this a case where user defined build settings (from  https://docs.bazel.build/versions/master/skylark/config.html#user-defined-build-settings) might be useful.

I could imagine something like the following could do the trick:
```
bazel test --define=@io_bazel_rules_go//flags:go_test=-test.v
```

**Comment by jayconrod** [comment]
This sounds like #236.

Either of the solutions you suggested should work as temporary measures. If you want to upstream a change to rules_go though, I'd rather fix #236 properly though. I think that means `-test.v` unconditionally in generated test executables and translating the JSON output to XML.

Bazel seems to have a generic mechanism for this (there's an `XML_OUTPUT_FILE` environment variable passed to tests), but I don't know much about it.

**Comment by robbertvanginkel** [comment]
Fixing https://github.com/bazelbuild/rules_go/issues/236 in general would indeed remove the need for us to need to set flags specifically for go test targets. That seems like the better approach, closing this out.

**Comment by mimfgg** [comment]
Hi @robbertvanginkel,

just stumbling on the same problem, did you find as clean way to fix this?

Cheers

**Comment by mimfgg** [comment]
for anyone finding this, adding `test --test_env=GO_TEST_WRAP_TESTV=1` to your `.bazelrc` is a solution :)
