### ISSUE TITLE
`--test_arg=-test.list` does not show output

### ISSUE THREAD

**Issue by Yunji-Leo** [bazelbuild/rules_go#2346]
### What version of rules_go are you using?

"0.20.2"

### What version of gazelle are you using?

0.18.0

### What version of Bazel are you using?

1.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

dawin, amd64

### What did you do?

bazel test --test_arg=-test.list=".*" //...

### What did you expect to see?

All the test cases names get listed

According to:
-test.list regexp
    	list tests, examples, and benchmarks matching regexp then exit

### What did you see instead?

Tests PASSED, no test cases name returned.

**Comment by jayconrod** [comment]
Are you setting `--test_output=all` or `--test_output=streamed`?

By default (`--test_output=summary`), Bazel does not show any output from test executables that exit with status 0.

**Comment by Yunji-Leo** [comment]
> Are you setting `--test_output=all` or `--test_output=streamed`?
> 
> By default (`--test_output=summary`), Bazel does not show any output from test executables that exit with status 0.

Thanks, `--test_output=all` works.
