### ISSUE TITLE
README recommends using `--features=race` but that invalidates build cache

### ISSUE THREAD

**Issue by v3n** [bazelbuild/rules_go#2347]
What is the preferred approach?

**Comment by jayconrod** [comment]
`--features=race` should not invalidate the build cache.

Please fill out the issue template and describe what's happening.

**Comment by v3n** [comment]
Roger, let me repro again and post some info:

I also noticed that this has conflicting information 
 with the README: https://github.com/bazelbuild/rules_go/blob/master/go/modes.rst#using-the-race-detector
