### ISSUE TITLE
Expose test cases in test XML

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#236]
Over on the Kubernetes project, we're currently running `go test -v` piped into [go-junit-report](https://github.com/jstemmer/go-junit-report), which gives nice JUnit XML down to test case level, e.g. for the test added in https://github.com/kubernetes/kubernetes/pull/39161:
```xml
<testsuite tests="104" failures="1" time="7.000" name="k8s.io/kubernetes/pkg/kubelet">
  <properties>
    <property name="go.version" value="go1.7.4"/>
  </properties>
  ...
  <testcase classname="kubelet" name="TestAlwaysFail" time="0.000">
    <failure message="Failed" type="">kubelet_pods_test.go:1491: this should always fail</failure>
  </testcase>
</testsuite>
```

When I run this same test under bazel, the `test.xml` only notes that the overall test failed, with no details about the failing test case.
```xml
<testsuite name="pkg/kubelet/go_default_test" tests="1" failures="0" errors="1">
  <testcase name="pkg/kubelet/go_default_test" status="run"><error message="exited with error code 1"></error></testcase>
</testsuite>                                                                                                                             
```

If look at `test.log`, I can eventually find the failing test case, though it's not as straightforward as the `go-junit-report`-produced XML. (It looks like this log is just `go test -v` output.)

I'm guessing the Bazel `go_test` output can't be improved until https://github.com/golang/go/issues/2981 is resolved, but if you have any suggestions/workarounds, those would be welcome, too.

**Comment by nelhage-stripe** [comment]
@ixdy fwiw I'm currently working around in CI by running `bazel test` with `--test_arg=-test.v` and then generating my own XML using `go-junit-report` on the log files in `bazel-out/local-fastbuild/testlogs/`. It's  a hack, but it gets me full reports in my CI.

Would also love to see this upstreamed somehow.

**Comment by ashi009** [comment]
@ianthehat any pointer on this?  I'd love to improve test report feature as well.  I'll have some time to work on this next week (probably).

**Comment by brendandouglas** [comment]
This is also important for IDE integration -- the Bazel IntelliJ plugin relies on test xml to show passing/failing test cases.

**Comment by tristanz** [comment]
Any public workarounds for this issue?   I'm assuming other folks have already solved this in various ways.

**Comment by robbertvanginkel** [comment]
I looked at this today but couldn't really find a satisfactory way of implementing this. Unfortunately the `pkg/testing` pacakge always outputs to [`os.Stdout` ](https://github.com/golang/go/blob/9e2299207a4ed4de49eae173903ae88ee8da6065/src/testing/testing.go#L1200), and the code that wires in the `test2json` package for structured test output lives in the `go test` command and wraps the execution of the compiled go test binary (which rules_go generates in `generate_test_main.go`). The standard go toolchain gets structured test output by wrapping golang test binaries, but bazel expects these binaries to write structured test output files themselves. I couldn't find any wrapper layer in bazel/rules_go that'd allow for some setup/wrapping of go test binaries.

@jayconrod any suggestions on how one could approach this?

**Comment by jayconrod** [comment]
We should probably add a test wrapper at some point. It would also be useful for changing directories before the test binary is exec'd. Sorry I don't have bandwidth to work on this right now though.

**Comment by robbertvanginkel** [comment]
A possible downside to a wrapper approach would be complicating something like attaching a debugger to the test target. A change to the execution directory seems like something the starlark [`testing.Environment`](https://docs.bazel.build/versions/2.0.0/skylark/lib/testing.html#TestEnvironment) provider could be used for (not supported today though, only supports environment variables).

For this specific issue, it seems ideal if we change the upstream go implementation to accept a writer instead of defaulting to `os.Stdout`. Short of that being done done and released I can imagine we could:
- Replace `os.Stdout` with a `os.Pipe` before invoking `testing.MainStart`, spawn a goroutine to copy (wouldn't catch cgo prints).
- Use `syscall.Dup2` to duplicate the filedescriptor to one for a file (but would be unix only).

Do any of those suggestions seem viable to you or do you have other approaches in mind?

**Comment by jayconrod** [comment]
A wrapper seems like the best approach to me, and it might be necessary anyway for #1955. Bazel has at least one layer of test wrapper, too. And test executables are generally intended to be run via `go test`, which acts as a wrapper. So it seems like that should at least be possible.

Do you use debuggers today? If so do you run the test executable directly or attach to the test after it's running?

Getting `testing` to accept a writer would be more difficult than other options. It would have to go through the proposal process and be carefully justified. I think we'd need to capture test output printed on stdout and stderr anyway (from tests themselves, not the `testing` package).

One thing to watch out for: the `-test.v` flag is visible to tests through `testing.Verbose`. So setting `-test.v` unconditionally might not be a good idea, but I don't known of a way to tell whether Bazel expects verbose test output.

**Comment by robbertvanginkel** [comment]
Personally I usually do something like:
```
bazel run -c dbg --run_under="@com_github_go_delve_delve//cmd/dlv exec " -- //target
```
sometimes using `--listen` for a remote debugging session to attach to. Always using `exec` on the binary build by bazel though.

As far as I understand the only way to indicate a starlark rule is a test is by using `rule(..., test = True)`, where the `DefaultInfo(executable = ...)` points to the binary to run with `bazel test`. Without any other other way of specifying a separate wrapper, it seems to me that the binary returned here needs to include the wrapper functionality. If this wrapper would execute the real tests as a subprocess, that makes it tricky to attach a debugger.

Maybe if we write the wrapper logic in go and embed it in the testrunner, we could use an indication that the tests were started  by bazel to conditionally trigger the wrapping logic instead of executing the tests as usual? I'm thinking of something similar of how the `os/exec` tests in the stdlib work with `GO_WANT_HELPER_PROCESS=1`.

**Comment by jayconrod** [comment]
@robbertvanginkel Wow, that's cool. I haven't seen a one-liner to start delve on a Go binary built with Bazel.

You're right though, having a wrapper would break that. And as you point out, we don't get to provide a separate executable for the test action.

So replacing `stdout` either by setting `os.Stdout` or using system calls sounds good, but that should definitely be controlled by an environment variable; folks who build test binaries and run directly should not notice any difference. Bazel sets a bunch of environment variables for tests, so I imagine there's something in there to use.

**Comment by robbertvanginkel** [comment]
I was looking at implementing with either overwriting  `os.Stdout` or the syscall, however I ran into the following in code that's part of the testmain:

https://github.com/bazelbuild/rules_go/blob/b2c7df325cf96bf8daa9c5d329baf85df4b405eb/go/tools/builders/generate_test_main.go#L154-L158

Even after capturing what `testing` has written to stdout, without a wrapper it isn't easily possible to run some code that would process it. If a user implements their own `TestMain`, they're expected to call `os.Exit()` with the exitcode from `m.Run()`. As far as I know, there is no way to reliably run the processing code if the user code needs to cal `os.Exit()`.

It seems like that means we might need a wrapper after all. What do you think of the approach of having the test binary itself be the wrapper, where based on being ran from `bazel test` (detected with some environment variable) it would execute a subprocess with itself?

**Comment by jayconrod** [comment]
> What do you think of the approach of having the test binary itself be the wrapper, where based on being ran from bazel test (detected with some environment variable) it would execute a subprocess with itself?

That's a good idea. That handles output from cgo and subprocesses started by tests, too, so it seems like a cleaner approach.

**Comment by robbertvanginkel** [comment]
I've opened https://github.com/bazelbuild/rules_go/pull/2348 with a scaffold for how I imagine what  the wrapper would look like.

For the xml generation, I think there's two approaches we can take:
1) Use the go toolchain's test2json, then manually transform the line delimited json events into a single xml file. The test2json code lives under `cmd/internal/test2json/` and isn't public, so either all test packages would need to be able to run `go tool test2json` or we vendor a copy of the code with rules_go.
2) Use https://github.com/jstemmer/go-junit-report, which is MIT licensed. Either by taking on an extra dependency from rules_go and supplying the packages as dependencies in testmain, or by vending a copy (possibly taking the significant bits and adding them to the testwrapper package to  simplify the integration code and avoid linking extra libraries).

Just to validate the idea of using a testwrapper I have tried 2) in https://github.com/bazelbuild/rules_go/commit/342e07d3613ac9445710ac9425609aeed59a3a9d. It works, but as I'm not sure what you prefer for dependencies/vendoring for rules_go I'll hold off on making a PR with that for now.

**Comment by jayconrod** [comment]
I don't know if this will work, but let's try importing `cmd/internal/test2json` directly from the test main. I don't think there's anything in the builder that prevents importing internal `cmd` packages.

It's a little bit sketchy, but I think it's better than using the go toolchain (may not be compatible with target platform), vendoring or embedding the library (may not be compatible if the output format changes), or adding a dependency (same problems, plus dependency management).

**Comment by robbertvanginkel** [comment]
I tried importing `cmd/internal/test2json`, but it results in the following error:
```
compilepkg: error running subcommand: exit status 2
.../execroot/io_bazel_rules_go/bazel-out/darwin-fastbuild/bin/tests/legacy/transitive_data/darwin_amd64_stripped/go_default_test%/testmain.go:12:2: can't open import: "cmd/internal/test2json": open .../execroot/io_bazel_rules_go/external/go_sdk/pkg/darwin_amd64/cmd/internal/test2json.a: no such file or directory
```
It seems like there is no prebuilt `cmd/internal/test2json.a` in the standard go distributions from https://golang.org/dl/:
```
$ tar -tvf /Users/robbert/Downloads/go1.13.6.darwin-amd64.tar.gz | grep test2json | grep -v testdata
drwxr-xr-x  0 kbuilder wheel       0 Jan  9 11:09 go/src/cmd/test2json/
-rw-r--r--  0 kbuilder wheel    4450 Jan  9 11:09 go/src/cmd/test2json/main.go
drwxr-xr-x  0 kbuilder wheel       0 Jan  9 11:09 go/src/cmd/internal/test2json/
-rw-r--r--  0 kbuilder wheel   12097 Jan  9 11:09 go/src/cmd/internal/test2json/test2json.go
-rw-r--r--  0 kbuilder wheel    7062 Jan  9 11:09 go/src/cmd/internal/test2json/test2json_test.go
-rwxr-xr-x  0 kbuilder wheel  2819728 Jan  9 11:35 go/pkg/tool/darwin_amd64/test2json
```

**Comment by robbertvanginkel** [comment]
I have pushed some updates to https://github.com/bazelbuild/rules_go/pull/2348 so that it contains the testwrapper, xml conversion and a few tests.

Currently it copies in `test2json.go` from upstream go. I was thinking we might be able to depend on `@go_sdk//:src/cmd/internal/test2json/test2json.go` (and rewrite `package test2json` to `package main` with a genrule), but this still feels a little fragile. Open to suggestions.

**Comment by jayconrod** [comment]
Huh, I'm surprised `cmd/internal/test2json.a` isn't prebuilt. Sorry to mislead you with that suggestion.

Copying `test2json.go` is probably the next best option for now. Adding some custom code to the rules or to the builder to pull copy it out of the standard library and change the package name would be viable, but it's complicated, and there wouldn't be too much benefit. If there's an incompatible change to the JSON format in the future though, we'd need to do that, but that seems unlikely.

**Comment by asv** [comment]
`bazel test` output with `--test_output=errors` now also contains successfully passed tests, i.e. became too verbose...
