### ISSUE TITLE
Concurrent packages.Load at build time

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2366]
When there are several Bazel actions calling `golang.org/x/tools/go/packages.Load`, the build time of each of those action increase as the number of such concurrent actions increases. One example of such action is in the source mode of [gomock rule](https://github.com/jmhodges/bazel_gomock/blob/6f3bc610237ab39f288738d338a2d3ef6bf68bba/gomock.bzl#L31), which calls `packages.Load` through [mockgen](https://github.com/golang/mock/blob/3dcdcb6994c4de42a73bd2e4790178be3ed4554b/mockgen/parse.go#L52).

We observed similar slow down in a Bazel rule that calls Mockery, which also [calls](https://github.com/vektra/mockery/blob/master/mockery/parse.go#L75) `packages.Load`.

I understand that `packages.Load` is generally slow because it needs to fill `GOCACHE` every time, which is not persist across Bazel builds. However, that doesn't explain why different actions slow each other down.

This issue may not be related to rules_go, but is more related to Bazel's action environment and the behavior of `golang.org/x/tools/go/packages.Load` and the underlying `go list` package driver. I put it here just because it is related to @jayconrod and @jmhodges's work. Feel free to refer to other venues.

### What version of rules_go are you using?

v0.21.2

### What version of gazelle are you using?

v0.20.0

### What version of Bazel are you using?

2.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS 10.15.3, amd64, 6-Core Intel Core i7

### What did you do?

```
git clone git@github.com:linzhp/bazel_examples.git
cd bazel_examples
git checkout f1dbf19487a2822df0aa049509f40f6bb6be66be
bazel build --experimental_generate_json_trace_profile //sqlite:mocks
bazel build --experimental_generate_json_trace_profile //sqlite:mocks //sqlite2:mocks //sqlite3:mocks 
bazel build --experimental_generate_json_trace_profile //sqlite:mocks //sqlite2:mocks //sqlite3:mocks //sqlite4:mocks //sqlite5:mocks
bazel build --experimental_generate_json_trace_profile //sqlite:mocks //sqlite2:mocks //sqlite3:mocks //sqlite4:mocks //sqlite5:mocks //sqlite6:mocks //sqlite7:mocks
```

### What did you expect to see?

`Action sqlite/mocks.go` should finish in about the same time in all builds (maybe except the last one as I only have 6 cores).

### What did you see instead?
Wall duration for `Action sqlite/mocks.go`
1 action: 35s
3 concurrent actions: 38s
5 concurrent actions: 47s
7 concurrent actions: 58s

Also the CPU usage is very low even when 7 concurrent `Action sqlite/mocks.go` actions are running.

<img width="1083" alt="Screen Shot 2020-02-10 at 1 14 45 PM" src="https://user-images.githubusercontent.com/98395/74190507-54d5c800-4c07-11ea-9cbc-1db79094fe3f.png">

**Comment by jayconrod** [comment]
This depends a lot on how `packages.Load` is invoked and whether the underlying packages have cgo code. But it doesn't seem too surprising to me. `packages.Load` runs `go list` internally (assuming `GOPACKAGESDRIVER` is not set). `go list` is usually either I/O limited or memory limited, depending on whether files are in the kernel cache. `go list` has some parallelism internally, too. Adding more cores probably won't help.

**Comment by linzhp** [comment]
`go list` loads transitive dependencies of a given package and compiles them, which is why it needs `GOCACHE` . After looking at the code, it appears that mockgen only needs `Package.PkgPath` and mockery only needs `Package.Types` and `Package. Syntax`. All these fields can be populated without loading transitive deps or compilation.

Do you think it a good idea to implement a simple `GOPACKAGESDRIVER` that calls [go/parser.ParseDir](https://golang.org/pkg/go/parser/#ParseDir) to avoid calling `go list`?

**Comment by jayconrod** [comment]
If `Package.Types` is needed for a cgo package, the C code needs to be at least partly compiled, which is very slow for some packages. That may be the case for anything related to SQLite.

> Do you think it a good idea to implement a simple GOPACKAGESDRIVER that calls go/parser.ParseDir to avoid calling go list?

Adding a `GOPACKAGESDRIVER` implementation that could be run inside a Bazel action is #393. A lot of the work may be shared with #512.

The idea is that either `GoCompilePkg` or a separate action would produce a package description as JSON. A driver could then scoop those files up for relevant packages, fix up paths, then return that JSON to `packages.Load`.

**Comment by jayconrod** [comment]
Closing old issues. Not sure if there's anything for rules_go to do here.
