### ISSUE TITLE
Depend on nogo with a transition and delete go_tool_library

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2374]
Instead of having the toolchain depend on nogo, a common target like `@io_bazel_rules_go//:go_context_data` should depend on it. The dependency should transition to a configuration that doesn't depend on nogo. That would break the cyclic dependency.

With that change, we could deprecate `go_tool_library`, and we could drop a lot of the custom patching for analyses in `org_golang_x_tools`.

This would also make it possible to use an alternative nogo binary using a command-line flag.

**Comment by achew22** [comment]
I believe this would also allow specifying custom `nogo` binaries on a per `go_binary` target basis as well which would be really nifty!

**Comment by bartle-stripe** [comment]
ooc are there still plans to address this?

**Comment by jayconrod** [comment]
Unfortunately, this is blocked by bazelbuild/bazel#11291.

**Comment by tux21b** [comment]
The upstream bug that has blocked this issue seems to be resolved now: https://github.com/bazelbuild/bazel/issues/11291#issuecomment-822515694
