### ISSUE TITLE
dependency cycle in @go_googleapis//google/api:annotations_proto

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_go#2387]
### What version of rules_go are you using?
v0.22.0

### What version of gazelle are you using?
v0.20.0

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

I don't know

### What operating system and processor architecture are you using?

linux x86_64

### What did you do?

bazelisk build @go_googleapis//google/api:annotations_proto

### What did you expect to see?

It builds

### What did you see instead?
```text
ERROR: /.../external/go_googleapis/google/api/BUILD.bazel:4:1: in proto_library rule @go_googleapis//google/api:annotations_proto: cycle in dependency graph:
.-> @go_googleapis//google/api:annotations_proto [self-edge]
`--
This cycle occurred because of a configuration option
ERROR: Analysis of target '@go_googleapis//google/api:annotations_proto' failed; build aborted
```

If I look in the build file, I see that annotations_proto lists itself in its deps:

```py
proto_library(
    name = "annotations_proto",
    srcs = [
        "annotations.proto",
        "client.proto",
        "field_behavior.proto",
        "http.proto",
        "resource.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
        "@go_googleapis//google/api:annotations_proto",
    ],
)
```

**Comment by jayconrod** [comment]
Related to #2355. Because we can't patch in the name of the repository before Gazelle runs, a special case that prevents this doesn't work.

**Comment by jayconrod** [comment]
`v0.22.1` is out now with this fix. Sorry for the break.
