### ISSUE TITLE
About the uses of gazelle

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#239]
Why doesn't gazelle support auto generating BUILD files for self developed code? Is it designed to only support external dependencies? Or is it just because some features haven't been implemented? Our development team want to use rules_go as automatically as possible.

**Comment by pmbethe09** [comment]
Can you give an example of what you mean?  I don't follow your use of the term "self developed code".

**Comment by GinFungYJF** [comment]
The "self developed code" I said means the packages that are not external dependencies in a go_repository rule.

**Comment by GinFungYJF** [comment]
Finally I understood that it is related to the source folder layout. So close it.
