### ISSUE TITLE
Support protobuf APIv2 (google.golang.org/protobuf)

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2395]
As described at https://blog.golang.org/a-new-go-api-for-protocol-buffers

There is a new module for protocol buffers, `google.golang.org/protobuf`. The old version is `github.com/golang/protobuf`, which will continue to be maintained.

At least the following needs to be done:

- [ ] Add a dependency on `org_golang_google_protobuf` with any necessary patches to `go_rules_dependencies`.
- [ ] Change the default `go_proto_compiler` targets to point to the new compiler. My understanding is that code generated with the new compiler will work with the old API.
- [ ] Update implicit dependencies for the `go_proto_compiler` targets.
- [ ] Test that old generated code is compatible with the new API and new generated code is compatible with the old API.

**Comment by shahms** [comment]
It would also be nice to support v1.4.0 of the old API, which is implemented using the new API for transition purposes.  It's often impractical to switch an entire codebase in one go.

* github.com/golang/protobuf@v1.4.0 is a version of APIv1 implemented in terms of APIv2. The API is the same, but the underlying implementation is backed by the new one. This version contains functions to convert between the APIv1 and APIv2 proto.Message interfaces to ease the transition between the two.

**Comment by jayconrod** [comment]
Fixed in #2455.

I was not able to update `//proto:go_proto` to the new compiler in `google.golang.org/protobuf`, but the new version of the old compiler will generate code compatible with both APIs. The new compiler [does not support gRPC](https://github.com/protocolbuffers/protobuf-go/releases#v1.20-grpc-support), and there is no replacement gRPC compiler yet.

**Comment by ribrdb** [comment]
I'm testing this out and seeing a bunch of warnings like this:
```
2020/05/05 17:52:22 WARNING: proto: message google.protobuf.OneofDescriptorProto is already registered
        previously from: "github.com/golang/protobuf/protoc-gen-go/descriptor"
        currently from:  "google.golang.org/protobuf/types/descriptorpb"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

Does that mean I've got the wrong version of some dependency?

**Comment by jayconrod** [comment]
@ribrdb Please file a new issue with more information.
