### ISSUE TITLE
go_download_sdk: allow downloading any release

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2405]
`go_download_sdk` should be able to download any Go release after some minimum version. If the Go version is not specified, the latest version should be chosen from `https://golang.org/dl`.

`go_download_sdk` should return the version so that Bazel tells users how to make the rule deterministic, the same way `git_repository` does if you don't specify `shallow_since`. It's unclear whether it should also return the SHA-256 sums for all downloads. It might be better to return a single SHA-256 sum of the JSON blob with all the sums.

The default boilerplate would change to something like this:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.1/rules_go-v0.22.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.1/rules_go-v0.22.1.tar.gz",
    ],
    sha256 = "e6a6c016b0663e06fa5fccf1cd8152eab8aa8180c583ec20c872f4f9953a7ac5",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_download_sdk")

go_rules_dependencies()

go_download_sdk(name = "go_sdk")
```

After fetching `go_sdk` for the first time, you'd change it to:

```
go_download_sdk(
    name = "go_sdk",
    version = "1.14",
)
```

This would avoid the need to update and release rules_go after every Go release.

**Comment by jan25** [comment]
This might be useful: https://github.com/golang/go/issues/34864, it talks about golang.org JSON API to fetch golang release info.
