### ISSUE TITLE
cgo library build errors if --features=pure provided in bazelrc

### ISSUE THREAD

**Issue by shahrukh330** [bazelbuild/rules_go#2410]
### What version of rules_go are you using?

v0.20.2

### What version of gazelle are you using?

v0.19.1

### What version of Bazel are you using?
v1.2.1

### What operating system and processor architecture are you using?
macOs mojave 10.14.6
nixOs 

### What did you do?
We have a monorepo with multiple go services and these services may or may not depend on cgo enabled libraries. For packages which depend on cgo enabled libraries we provide `pure = "off", static = "off",` in BUILD.bazel to build the binaries. For everything else we provide `--feature=pure` in `bazel.rc` to keep everything pure and not link against libc.  

Running `bazel build //...` fails with error for go_library with cgo dependencies as it tries to build those libraries with `CGO_ENABLED=0`.

### What did you expect to see?
Providing `--feature=pure` in bazel.rc should not have affected `go_library ` as documentation states that 
> Only rules that link accept build mode controlling attributes (go_binary and go_test, not go_library). 

### What did you see instead?
Build failures

**Comment by jayconrod** [comment]
> Running bazel build //... fails with error for go_library with cgo dependencies as it tries to build those libraries with CGO_ENABLED=0.

`--features=pure` is analogous to `CGO_ENABLED=0`. `pure = "on"` applies to a binary and all its dependencies. You can't set `pure` on individual packages because it doesn't make sense to link a binary with some packages built `pure` and others not.

> The entire transitive set of libraries that a leaf depends on are built in the mode specified by
the binary rule.

**Comment by shahrukh330** [comment]
Thank you for the answer. Closing this.
