### ISSUE TITLE
go_embed_data is failing to embed .c / .cc source code

### ISSUE THREAD

**Issue by ccontavalli-j** [bazelbuild/rules_go#2411]
### What version of rules_go are you using?

0.19.3

### What version of gazelle are you using?

0.18.2

### What version of Bazel are you using?

2.0.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Debian GNU/Linux, intel x86_64.

### What did you do?

I have a simple:

```
go_embed_data(
    name = "input-files",
    package = "inputs",
    srcs = glob(["inputs/**"]),
    flatten = True,
)
```

in the inputs/ directory there happens to be a file with `.cc` extension. 

### What did you expect to see?

go_embed_data is for including raw files and make them available in my go code. I was expecting the ASCII characters in the .cc file to simply be made available in a golang []byte array, like any other file included with go_embed_data.

### What did you see instead?

go_embed_data is trying to compile the file?? Or thinks I should be compiling the file by enabling cgo instead??

go_embed_data should just embed supplied files as is?

```
ERROR: BUILD.bazel:3:1: in go_embed_data rule xxx:
Traceback (most recent call last):
        File "BUILD.bazel", line 3
                go_embed_data(name = 'input-files')
        File "15fc299b357cf96b2746daf48840ec72/external/io_bazel_rules_go/extras/embed_data.bzl", line 68, in _go_embed_data_impl
                go.library_to_source(go, ctx.attr, library, ctx.coverage_in...())
        File "15fc299b357cf96b2746daf48840ec72/external/io_bazel_rules_go/go/private/context.bzl", line 266, in go.library_to_source
                fail("source {} has C/C++ extension, ...))
source tester/inputs/test.cc has C/C++ extension, but cgo was not enabled (set 'cgo = True')
```

**Comment by jayconrod** [comment]
This should be fixed on `master`. Thanks for reporting!
