### ISSUE TITLE
Replace buildifier_test rule with buildifier rule

### ISSUE THREAD

**Issue by jan25** [bazelbuild/rules_go#2417]
This repo uses custom implemented rule/script around buildifier cli here https://github.com/bazelbuild/rules_go/blob/master/tests/buildifier_test.bzl which is used in CI/presubmit. We could replace `buildifier_test` rule to reuse `buildifier` rule from here https://github.com/bazelbuild/buildtools/tree/master/buildifier#setup-and-usage-via-bazel

**Comment by jayconrod** [comment]
The `buildifier` rule produces an executable intended to be invoked with `bazel run`. That's useful for manual fixing and testing, but it's not what `buildifier_test` is used for.

`buildifier_test` is meant to fail CI testing if a file has any `buildifier` issues. It runs on a specific set of files.
