### ISSUE TITLE
Runfiles library should provide environment variables for subprocesses

### ISSUE THREAD

**Issue by phst** [bazelbuild/rules_go#2423]
If a Bazel-built binary wants to launch another Bazel-built binary, it needs to tell the latter binary where to find the runfiles, because `argv[0]` for the latter binary will be different (or, in case of scripts, entirely unavailable). Other languages provide a function that returns `RUNFILES_DIR` and `RUNFILES_MANIFEST` environment variables (see https://github.com/bazelbuild/bazel/blob/master/tools/cpp/runfiles/runfiles_src.h#L159 for C++), and runfiles.go should provide the same:

```go
func EnvVars() []string
```

**Comment by jayconrod** [comment]
Please fill out the issue template and describe the specific problem you're having.

Shouldn't subprocesses already see `RUNFILES_DIR` or `RUNFILES_MANIFEST_FILE` from the parent process? Not sure why they'd need to be different.

**Comment by phst** [comment]
> Please fill out the issue template and describe the specific problem you're having.

This is essentially https://github.com/bazelbuild/rules_go/issues/2359 combined with https://docs.bazel.build/versions/master/skylark/rules.html#tools-depending-on-tools "To simplify subtool tool logic, it’s recommended that each subtool optionally accept its runfiles root as a parameter (via environment or command line argument/flag). A root tool can thus pass the correct canonical runfiles root to any of its subtools." and the reasoning given at https://github.com/bazelbuild/bazel/blob/master/tools/cpp/runfiles/runfiles_src.h#L58.
I can come up with a full example if you want, but I hope these documents clarify the problem.

> Shouldn't subprocesses already see RUNFILES_DIR or RUNFILES_MANIFEST_FILE from the parent process? Not sure why they'd need to be different.

These variables are only set when using `bazel run` or `bazel test`, but not when using a Bazel-built binary in a Bazel action or running it directly. Then the runfiles library needs to look at `os.Args[0]` as described in https://github.com/bazelbuild/rules_go/issues/2359, but subprocesses that are themselves Bazel-built binaries with runfiles can't do that because for them `os.Args[0]` is different, so the parent binary needs a way to communicate the runfiles location to the subprocesses.

**Comment by jayconrod** [comment]
Thanks, that makes more sense. Marking as a feature request.
