### ISSUE TITLE
Have go_binary emit CcInfo

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#2433]
Now that Bazel 2.2 is the minimum version for rules_go, I was thinking it would be cool for `go_library` or `go_binary` to emit `CcInfo`.

Benefits are:
- `go_library/binary` can be directly put into the deps of a `cc_library`
- `linkmode` could be automatically inferred
- remove legacy `.cc` target and associated macros targets, so pure rule

I think it would be easier to do it after #2414 lands, however.

**Comment by jayconrod** [comment]
I would *love* to get rid of those `.cc` targets and not have to deal with `cc_import`.
