### ISSUE TITLE
Question towards dependencies for a simple project structure

### ISSUE THREAD

**Issue by wanghran** [bazelbuild/rules_go#2454]
### What version of rules_go are you using?
v0.22.4

### What version of gazelle are you using?
v0.20.0

### What version of Bazel are you using?
v3.0.0

### What operating system and processor architecture are you using?
macOS Catalina 10.15.4, x86_64

### What did you do?
I have a simple starting go project with standard structure. https://github.com/wanghran/learning_golang/tree/nestedPack

├── go.mod
├── app
│   ├── httpserver
│   │   ├── server
│   │   │   ├── handlers.go
│   │   │   └── BUILD.bazel
│   │   ├── BUILD.bazel
│   │   └── main.go
│   ├── BUILD.bazel
│   └── main.go
├── WORKSPACE
├── library
│   └── wikipage
│       ├── page.go
│       └── BUILD.bazel
├── README.md
└── BUILD.bazel

I've set the `importpath` of `//app/httpserver/server` to be "github.com/wanghran/learning_golang/app/httpserver/server" and I've imported that package into `//app/httpserver/main.go`.

---
`//app/httpserver/server/BUILD.bazel`
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["handlers.go"],
    importpath = "github.com/wanghran/learning_golang/app/httpserver/server",
    visibility = ["//app/httpserver:__pkg__"],
)
```
---
`//app/httpserver/BUILD.bazel`
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library (
    name = "go_default_library",
    srcs = [
        "main.go",
    ],
    importpath = "github.com/wanghran/learning_golang/app/httpserver",
    deps = ["//app/httpserver/server:go_default_library"],
    visibility = ["//visibility:private"],
)

go_binary (
    name = "main",
    srcs = ["main.go"],
    deps = ["//app/httpserver:go_default_library"],
)
```
---
`//app/httpserver/main.go`
```
package main

import (
	"fmt"
	"log"
	"net/http"

	myserver "github.com/wanghran/learning_golang/app/httpserver/server"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Printf("Hi there, I love %s!", r.URL.Path[1:])
	myserver.PrintForFun()
}

func main() {
	http.HandleFunc("/", handler)
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

### What did you expect to see?
I expected the build to be successful when run `bazel build //app/httpserver:main`

### What did you see instead?
```
ERROR: /Users/hwang6/Documents/Workspace/learning_golang/app/httpserver/BUILD.bazel:13:1: GoCompilePkg app/httpserver/darwin_amd64_stripped/main%/app/httpserver/main.a failed (Exit 1) builder failed: 
error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src app/httpserver/main.go -arc ... (remaining 11 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /private/var/tmp/_bazel_hwang6/70934f9d8d71033315c3e345661b3f6a/sandbox/darwin-sandbox/19/execroot/learning_golang/app/httpserver/main.go: import of "github.com/wanghran/learning_golang/app/httpserver/server"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //app/httpserver:main failed to build
```

**Comment by jayconrod** [comment]
Your `go_binary` target depends on `//app/httpserver:go_default_library`, which has `importpath = "github.com/wanghran/learning_golang/app/httpserver"`:

```
go_binary (
    name = "main",
    srcs = ["main.go"],
    deps = ["//app/httpserver:go_default_library"],
)
```

However, it imports `github.com/wanghran/learning_golang/app/httpserver/server`, and it doesn't directly import any dependency that provides it. Every package that .go source files import must have corresponding targets in `deps` with the same `importpaths`. 

Are you using Gazelle? Re-running it should fix this automatically.

**Comment by wanghran** [comment]
Thanks! It works right now. Seems like I have misunderstood the meaning of deps in `go_binary`. I thought it should include the library of the source files.

**Comment by jayconrod** [comment]
It does include transitively imported packages when it comes to linking, but not compiling. All directly imported packages have to be listed in `deps` or in the `deps` list of one of the targets listed in `embed`.

I'll close this but let me know if you have more questions.
