### ISSUE TITLE
Generate testsuites for nested tests instead of individual testcases

### ISSUE THREAD

**Issue by v3n** [bazelbuild/rules_go#2457]
This would be improvement for grouping tests with the JUnit output feature (which is awesome, thanks so much for adding it).

An example of a nested test:

```
func TestCase(t *testing.T) {
    t.Run("SubTest, func(t *testing.T) {
        // ....
    })
}
```

This results in a test called: `TestCase/SubTest`. The desire here is for TestCase to be it's own suite, with SubTest as a test case.

I'm not sure if it's possible to have nested TestSuites with the JUnit schema, ([the XSD here](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) seems to indicate not), in that case, treating test `TestCase/SubTest/AnotherNestedTest` as testcase `AnotherNestedTest` in testsuite `TestCase/Subtest` would be awesome.

**Comment by jayconrod** [comment]
cc @robbertvanginkel

**Comment by robbertvanginkel** [comment]
As I read the spec, it doesn't seem to allow for nested testsuites. Other go libraries that parse go test output into xml like `github.com/jstemmer/go-junit-report` also choose to have a testcase per golang subtest https://github.com/jstemmer/go-junit-report/blob/master/testdata/12-report.xml.

I think go's subtest pattern is more flexible than what can be represented in a testsuite, as it allows fails of the parent test itself. For example:
```
func TestCase(t *testing.T) {
    if someCheck() != false {
        t.Error()
    }
    t.Run("SubTest, func(t *testing.T) {
        // ....
    })
}
```
I'm not sure how that would be represented if `TestCase` is a suite, as suites itself can't have failures. I suppose you could add an implicit meta/self testcase to every suite, but I'm not convinced thats worth it.

**Comment by v3n** [comment]
Gotcha. I'm fine to close this given that.
