### ISSUE TITLE
Should gazelle complete the rules that have been defined manually in the BUILD file?

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#246]
Should gazelle complete or update the rules that have been defined manually in BUILD?
For example, there are a_test.go, b_test.go, c_test.go in package A, then I define a go_test like:
```
go_test(
     name = "a",
     srcs = ["a_test.go"],
     deps = [""],
)
```
or
```
go_test(
     name = "a",
     srcs = ["a_test.go"],
)
```
Should gazelle automatically generate the values in the 'deps' to complete the rule ?

**Comment by jayconrod** [comment]
Sorry for the slow response.

I think this would be useful functionality. Gazelle will already merge srcs and deps for rules that it auto-generates (`go_default_library`, etc), but it currently leaves other rules alone.

Might be good to require a tag on rules that Gazelle should update.

This would probably be difficult to get working though. Gazelle uses go/build, which makes assumptions about which files are part of the package. So it might need to symlink files mentioned in srcs into a directory before getting information from go/build. srcs might include labels for generated code and filegroups. Gazelle probably couldn't support that.

**Comment by jayconrod** [comment]
(Closing old Gazelle issues. Please open a new issue at https://github.com/bazelbuild/bazel-gazelle if Gazelle isn't doing something you want).

In general, I don't want Gazelle to be too flexible about rule naming. It would make it easy to accidentally overwrite a manually defined rule with a different name. In a large repository with lots of build files, it would be easy to overlook a change like that.

We may need something like this though if we change the naming scheme. We still want to get rid of the `go_default_library` name.
