### ISSUE TITLE
it throws when using inffered importpath on go_proto_library 

### ISSUE THREAD

**Issue by Leo7654** [bazelbuild/rules_go#2469]
According to this guid, import path is optional. But when not provided it throws error.

Example:
```
go_proto_library(
    name = "foo_go_proto",
    // importpath = "example.com/repo/foo",
    proto = ":foo_proto",
    visibility = ["//visibility:public"],
    deps = ["//bar:bar_go_proto"],
)
```

Throws "importpath must be specified in this library or one of its embedded libraries"

Guide:
https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#go_proto_library
> The Go import path of this library. If unspecified, this will be inferred from the rule's location in the repository.

Source:
https://github.com/bazelbuild/rules_go/blob/1e30322052bdce23fc5d3c8f4ce804d579600fe4/proto/def.bzl#L84

**Comment by jayconrod** [comment]
Please fill out the issue template. At this point, I don't know what issue you're seeing or how to reproduce it.

**Comment by Leo7654** [comment]
> Please fill out the issue template. At this point, I don't know what issue you're seeing or how to reproduce it.

I've updated the description.

**Comment by jayconrod** [comment]
Ok, seems like the documentation needs to be updated. There may have been some cases where `importpath` could be inferred in the past, but I don't believe that's the case anymore.

**Comment by Leo7654** [comment]
@jayconrod Thank you for your answer.
