### ISSUE TITLE
nogo binary passing through .bazelrc fails "bazel info"

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2475]
### What version of rules_go are you using?

8e6cfa5ef437aca79a987ad87e093c2065d71394

### What version of Bazel are you using?

3.0.0

### Does this issue reproduce with the latest releases of all the above?

I don't know

### What operating system and processor architecture are you using?

Darwin amd64

### What did you do?

```
$ echo "build --@io_bazel_rules_go//go/config:nogo=@io_bazel_rules_go//:tools_nogo" >> .bazelrc 
$ bazel info
```

### What did you expect to see?

Some bazel information

### What did you see instead?

```
ERROR: unknown key: '--@io_bazel_rules_go//go/config:nogo=@io_bazel_rules_go//:tools_nogo'
```

**Comment by jayconrod** [comment]
Thanks for reporting. I've opened bazelbuild/bazel#11301 so this can be fixed on the Bazel side.

Fortunately, setting the default in `go_register_toolchains` still works. I was planning to deprecate that, but it looks like it will need to stick around in some form for a while.

**Comment by linzhp** [comment]
Fixed by Bazel
