### ISSUE TITLE
go_test broken with go 1.11: os.ProcessState.ExitCode does not exist

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_go#2476]
### What version of rules_go are you using?

It looks like it broke with 0.22.0
I'm currently using v0.21.3 and tests work, but i can't upgrade.

### What version of gazelle are you using?

0.22.0

### What version of Bazel are you using?
3.1.0

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
Debian Stretch, x86_64

### Any other potentially useful information about your toolchain?
Using go 1.11 because that's the last version that support all the app engine apis.

### What did you do?

Write a test using go_test and the go 1.11 sdk.
The generated testmain.go uses os.ProcessState.ExitCode, which was added in go 1.12.
Maybe it could use reflect to call this method so it can work with newer go runtimes, but just exit with 
testWrapperAbnormalExit for go1.11?

### What did you expect to see?

I can build and run the test.

### What did you see instead?
```
testmain.go:65:16: xerr.ExitCode undefined (type *exec.ExitError has no field or method ExitCode)
```

**Comment by jayconrod** [comment]
Sorry, I'm afraid I can't help with this.

The Go team only supports the current release (1.14) and the previous release (1.13). Projects maintained by the Go team may use language and standard library features available in the oldest supported release.

This policy covers not only rules_go but also projects rules_go depends on, like `golang.org/x/tools` and `github.com/golang/protobuf`. So even if `go_test` were modified not to use Go 1.12 features, other things would probably still break.

**Comment by ribrdb** [comment]
I'm not sure I believe things will probably  break.
google-cloud-go also depends on golang.org/x/tools and github.com/golang/protobuf, but they say "We support the two most recent major versions of Go. If Google App Engine uses an older version, we support that as well."
If however you're not going to support go 1.11 shouldn't you change the MIN_SUPPORTED_VERSION to something greater than 1.11?

**Comment by ribrdb** [comment]
Also, protobuf looks like they were making changes for go 1.9 last month
