### ISSUE TITLE
descriptor.proto unavailable

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_go#248]
Since https://github.com/google/go-genproto/commit/b3e7c2fb04031add52c4817f53f43757ccbf9c18, the file descriptor.proto from google.golang.org/genproto/protobuf was removed, basically re-opening #165 (aka can't import "google/protobuf/descriptor.proto")

The file is available here of course: https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto

but there are no BUILD rules for it, and certainly not any go_proto_library compatible rules in that repo.

Any chance this could be implemented, maybe in a similar way to how other well know protos were implemented in #182?

In fact, maybe everything in https://github.com/google/protobuf/blob/master/BUILD#L192:

```
RELATIVE_WELL_KNOWN_PROTOS = [
    # AUTOGEN(well_known_protos)
    "google/protobuf/any.proto",
    "google/protobuf/api.proto",
    "google/protobuf/compiler/plugin.proto",
    "google/protobuf/descriptor.proto",
    "google/protobuf/duration.proto",
    "google/protobuf/empty.proto",
    "google/protobuf/field_mask.proto",
    "google/protobuf/source_context.proto",
    "google/protobuf/struct.proto",
    "google/protobuf/timestamp.proto",
    "google/protobuf/type.proto",
    "google/protobuf/wrappers.proto",
]
```

p.s. short investigation let me to this line:
https://github.com/bazelbuild/rules_go/blob/090c82ceb82cd946b0a6e6a0d5c5211dbc1694a3/proto/go_proto_library.bzl#L261

```
_well_known_imports = ["any", "duration", "empty", "struct", "timestamp", "wrappers"]
```

But those imports are already pre-compiled, and pulled from
`_WELL_KNOWN_REPO = "@com_github_golang_protobuf//ptypes/"`, which doesn't help much.

Maybe pull from `@com_github_golang_protobuf//protoc-gen-go/descriptor` in the same fashion?

**Comment by pmbethe09** [comment]
To confirm, you need descriptor.proto to use proto2 extensions?

The problem is @com_github_golang_protobuf//protoc-gen-go/descriptor only
contains descriptor.pb.go, but not descriptor.proto

So to do this would require depending on some other repo like
github.com/google/protobuf or google.golang.org/genproto/protobuf
But doing that gets into version mismatch issues, and thus has not been
done.

If you really need this, you can hack it yourself:
* make a directory in your project //google/protobuf
* use a genrule to copy descriptor.proto from github.com/google/protobuf
* use go_proto_library on the copied file.
(this looks similar to what was done in buildifier/buildozer
https://github.com/bazelbuild/buildifier/blob/master/build_proto/BUILD)

**Comment by yohcop** [comment]
I am writing a proto compiler plugin (to generate code based on protos). The proto compiler parses the proto files and emits Descriptors (that are defined in descriptor.proto) on stdout. So I need to parse those descriptors from stdin. (Technically, they are wrapped in another proto, but same thing.)

The github.com/google/protobuf dependency is already included, in
[go_proto_library.bzl#L309](https://github.com/bazelbuild/rules_go/blob/4cb081e19399f187324d6ec6976b515e9a7aec75/proto/go_proto_library.bzl#L309)

Yes, I know I can hack it myself of course, but if it was already done in buildifier, and I'm sure in other projects as well, it seems good to not have everybody use the same hack ;)

**Comment by pmbethe09** [comment]
In that case, don't you just need a compiled library for descriptor?  (and
not the .proto file)
https://github.com/golang/protobuf/tree/master/descriptor

You should just be able to depend on
@com_github_golang_protobuf//descriptor:go_default_library

**Comment by yohcop** [comment]
Well almost :) my compiler uses annotations on protos (ServiceOptions and MethodOptions) to specify various options (e.g. endpoints for http RPCs). For that, I define proto messages that extend ServiceOptions and MethodOptions defined in descriptor.proto. Something like:

```
import "google/protobuf/descriptor.proto";

message ServiceOptions {
  string options = 1;
}

extend google.protobuf.ServiceOptions {  // This needs descriptor.proto
  ServiceOptions Service = 7791;
}
```

**Comment by pmbethe09** [comment]
Ah.  Well sadly I don't have a good answer for you (yet).

If https://github.com/golang/protobuf would add descriptor.proto to the
descriptor dir, then I could extend the hack in go_proto_library to make
that also show up in google/protobuf/

**Comment by junghoahnsc** [comment]
Is there any reasonable solution other than copying descriptor.proto to my repo?

**Comment by pmbethe09** [comment]
Unless you can convince the golang/protobuf folks to check in descriptor.proto
https://github.com/golang/protobuf/issues/222

**Comment by ianthehat** [comment]
I believe the new implementation of `go_proto_library` offers you everything you need here.
You can access a `proto_library` for `descriptor.proto` directly from `@com_google_protobuf//:descriptor_proto`

You can either use the output of that rule (a descriptor) or dig out it's sources, or use the new go_proto_library rule with a custom toolchain.

**Comment by nicolov** [comment]
For reference, you can do:

```
go_proto_library(
    name = "descriptor_go_proto",
    importpath = "github.com/golang/protobuf/protoc-gen-go/descriptor",
    proto = "@com_google_protobuf//:descriptor_proto",
)
```

to have access to the descriptor go library.
