### ISSUE TITLE
go_path does not work with go_test targets

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_go#2487]
### What version of rules_go are you using?

v0.22.4
### What version of gazelle are you using?

v0.20.0
### What version of Bazel are you using?

3.1.0
### Does this issue reproduce with the latest releases of all the above?
Yes.

### What operating system and processor architecture are you using?

Tested on both Mac and Linux

### What did you do?

Reproduction here: https://github.com/purkhusid/go-path-repro

### What did you expect to see?

Test files to be added to the GOPATH

### What did you see instead?

Error: `in go_path rule //:gopath: non-test target '//:gopath' depends on testonly target '//testing:go_default_test' and doesn't have testonly attribute set`

**Comment by jayconrod** [comment]
It looks like this is core Bazel functionality, working as designed. A target may not depend on a test target (such as a `go_test`) or a target with `testonly = True` unless it also has `testonly = True`. The [Bazel documentation](https://docs.bazel.build/versions/master/be/common-definitions.html#common.testonly) has more info.

You should be able to set `testonly = True` on the `go_path` to resolve this error. There's nothing that the `go_path` implementation can do though.

**Comment by purkhusid** [comment]
This works. Thanks!
