### ISSUE TITLE
@com_google_protobuf is not listed as one of the dependencies for rules_go

### ISSUE THREAD

**Issue by stevenwjy** [bazelbuild/rules_go#2489]
### What version of rules_go are you using?

v0.22.4

### What version of gazelle are you using?

v0.20.0

### What version of Bazel are you using?

v3.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What did you do?

Tried to build bazel without including @com_google_protobuf in the `WORKSPACE`

### What did you expect to see?

Successful build since I have loaded all the rules_go dependencies. However, it seems that `@com_google_protobuf` is not listed as one of the dependencies

### What did you see instead?

`The repository '@com_google_protobuf' could not be resolved and referenced by '@io_bazel_rules_go//proto/wkt:timestamp_go_proto`

**Comment by stevenwjy** [comment]
To resolve the issue, I had to put the following code in my `WORKSPACE`:

```
http_archive(
    name = "com_google_protobuf",
    sha256 = "a79d19dcdf9139fa4b81206e318e33d245c4c9da1ffed21c87288ed4380426f9",
    strip_prefix = "protobuf-3.11.4",
    # latest, as of 2020-02-21
    urls = [
        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

Is it possible to just load `@com_google_protobuf` as one of the dependencies for `rules_go`?

**Comment by jayconrod** [comment]
`com_google_protobuf` used to be declared in `go_rules_dependencies`, but it was removed after they started requiring that `protobuf_deps` function call. `go_rules_dependencies` cannot load and call that function. It has to be loaded and called separately in `WORKSPACE`.

There's an example of setting this up in https://github.com/bazelbuild/rules_go#protobuf-and-grpc. You're doing the right thing though.

**Comment by ethkim** [comment]
Resurrecting an old thread here. If I follow the official documentation [here](https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#proto-dependencies) with `git_repository`, it throws an error for missing zlib link

> WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> ERROR: An error occurred during the fetch of repository 'zlib':
>    Traceback (most recent call last):
>         File "/private/var/tmp/_bazel_ethan/575feae57a671313296eed2bb870ab5f/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
>                 download_info = ctx.download_and_extract(
> Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_ethan/575feae57a671313296eed2bb870ab5f/external/zlib/temp1442036611497880383/zlib-1.2.11.tar.gz: GET returned 404 Not Found

With @stevenwjy 's http_archive pointing to https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz, it works though. Maybe the git_repository instruction points to an old commit -- what would be the best way to keep that updated (not just for the instruction, but also to keep our build config up to date)? Thanks!
