### ISSUE TITLE
go_binary: setting pure = "on" should disable race mode by default

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#2499]
Interestingly, I didn't think I actually had any cgo code. I wonder if this is because of the --race flag?

### What version of rules_go are you using?

Moving io_bazel_rules_go v0.22.4 -> v0.23.0

https://github.com/bazelbuild/bazel-watcher/pull/388

### What version of gazelle are you using?

0.21.0

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

* Ubuntu 16.04
* Ubuntu 18.04
* OpenJDK Mac
* OpenJDK Windows

https://buildkite.com/bazel/bazel-watcher/builds/1169

### Any other potentially useful information about your toolchain?

They all fail with the same error

```
go install: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

### What did you do?

Any build

### What did you expect to see?

Build success

### What did you see instead?

```
go install: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

**Comment by jayconrod** [comment]
It looks like the issue here is that `//ibazel` has `pure = "on"`, which disables cgo. That should cause race mode to be disabled if the `race` attribute isn't set. If `race = "on"` is also set, that should be an error.
