### ISSUE TITLE
Protobuf well known types are registered twice

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/rules_go#2501]
### What version of rules_go are you using?

v0.23.0

### What version of gazelle are you using?

v0.21.0

### What version of Bazel are you using?

v3.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux x86_64

### Any other potentially useful information about your toolchain?

Vanilla Go

### What did you do?

Running
```sh
$ bazel test //...
```
On the grpc-gateway `v2` branch.

### What did you expect to see?

No warnings.

### What did you see instead?

Warnings about double registrations:

```
2020/05/14 17:30:43 WARNING: proto: message google.protobuf.GeneratedCodeInfo.Annotation is already registered
        previously from: "github.com/golang/protobuf/protoc-gen-go/descriptor"
        currently from:  "google.golang.org/protobuf/types/descriptorpb"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

For a build log: https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/468/workflows/b2d94c2d-bec2-475d-9342-05bcb6d013ae/jobs/9146/steps

**Comment by johanbrandhorst** [comment]
Looking a bit closer, this may be an interaction between the new `rules_go` and our `protoc-gen-swagger` `defs.bzl`: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/defs.bzl#L184-L187

**Comment by johanbrandhorst** [comment]
CC @Yannic

**Comment by jayconrod** [comment]
Reproduced with a smaller example, below.

It doesn't print the same warnings when run with `go run .`.

```
-- BUILD.bazel --
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

# gazelle:prefix example.com/hello
gazelle(name = "gazelle")

go_binary(
    name = "hello",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["use.go"],
    importpath = "example.com/hello",
    visibility = ["//visibility:public"],
    deps = [
        "@io_bazel_rules_go//proto/wkt:descriptor_go_proto",
        "@org_golang_google_protobuf//types/descriptorpb:go_default_library",
    ],
)

-- use.go --
package main

import (
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

func main() {
}
```
