### ISSUE TITLE
Not able to depend on external gogo.proto

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2512]
There seems no way to build a proto file that imports `gogoproto/gogo.proto` without copying it into the main workspace. If I set the `build_file_proto_mode = "default"`, then building `@com_github_gogo_protobuf//gogoproto:go_default_library` leads to errors like:
```
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/sandbox/darwin-sandbox/808/execroot/__main__/external/com_github_gogo_protobuf/gogoproto/helper.go:35:37: cannot use E_Embed (type *"github.com/golang/protobuf/proto".ExtensionDesc) as type *"github.com/gogo/protobuf/proto".ExtensionDesc in argument to "github.com/gogo/protobuf/proto".GetBoolExtension
```

If I have `build_file_proto_mode = "legacy"` and the following rule in the main workspace:
```
proto_library(
    name = "gogoproto_proto",
    srcs = ["@com_github_gogo_protobuf//gogoproto:go_default_library_protos"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)
```

I got:
```
in srcs attribute of proto_library rule //idl/code.uber.internal/gogoproto:gogoproto_proto: Proto source with label '@com_github_gogo_protobuf//gogoproto:go_default_library_protos' must be in same package as consuming rule.. Since this rule was created by the macro 'proto_library', the error might have been caused by the macro implementation
```

### What version of rules_go are you using?

v0.23.1

### What version of gazelle are you using?

v0.21.0

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Darwin amd64

**Comment by jayconrod** [comment]
Tentatively marking this as a bug, but I'm afraid I'm not really able to provide support for gogoproto. If there's a non-invasive fix, I'd be happy to take a PR though.

From the error message, it sounds like code generated with `github.com/golang/protobuf/proto` may not be compatible with code generated with `github.com/gogo/protobuf/proto`? I think that's the case for some of the gogoproto plugins? Not really sure.

You may also try `master` after #2511 was merged. That resolved a bug with duplicate definitions and registration between `github.com/golang/protobuf` and `google.golang.org/protobuf`. Not sure if that will help here.
