### ISSUE TITLE
Inconsistent APIv2 generated protobuf well known types behaviour

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/rules_go#2514]
### What version of rules_go are you using?

`v0.23.1`

### What version of gazelle are you using?

`v0.21.0`

### What version of Bazel are you using?

`v3.1.0`

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Imported `google.golang.org/protobuf` (AKA APIv2) generated well known types
(i.e. `"google.golang.org/protobuf/types/known/wrapperspb"`) and tried to run a test which imports
the APIv1 type and makes a comparison with `proto.Equal`. See https://play.golang.org/p/Eze1h4YnGmy for the complete setup

### What did you expect to see?

A successful test (it succeeds with `go test ./...`).

### What did you see instead?

A test failure.

### Why are you really raising this issue?

I'm working on v2 of the grpc-gateway project (https://github.com/grpc-ecosystem/grpc-gateway), and I would like to move the whole stack to v2. The first dependency on that is `protoc-gen-grpc-go` being merged (https://github.com/grpc/grpc-go/pull/3453), but the second dependency is having a `rules_go` release which wraps the APIv2 generated well known type packages. As I understand it, we currently wrap the APIv2 generated packages in the _old_ repo. I think this failure is symptomatic of this, but I could be wrong.

**Comment by jayconrod** [comment]
I think this is closely related to #2501. Could you check if this works at `master`, after #2511 landed?

I'm planning to do a patch release with that fix this week.

**Comment by johanbrandhorst** [comment]
This does indeed work fine with `740ada94dfda52f2a079f718858e8b2b8ee0fdc6`. I'll close this an re-test after the next release, thank you!
