### ISSUE TITLE
Expose go tool binary

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#2521]
Would it be possible to add support for the `go` tool? I'd like to be able to run things like:

- `bazel run @go_sdk//go -- mod tidy`
- `bazel run @go_sdk//go -- run some.package.com/bla`

Currently Go version in my project is managed via rules_go, but I also have to have a locally installed version to do things like above. This is ok, but would be nicer to have a fully hermetic build and tools too.

**Comment by jayconrod** [comment]
This is an interesting idea, and it seems useful in some cases... but I'd rather not support it in rules_go.

Currently, rules_go assumes the SDK downloaded with `go_download_sdk` is the same as what you get from `golang.org/dl`. That might not always be the case though. There are a number of optimizations we could do to take up less disk space or make cross-compilation more efficient. Some ideas:

* Only extract the `go` command and `std` sources if they're needed, for example, when cross-compiling.
* Keep compiled `std` `.a` files in a `.zip` file for simpler dependency graphs.
* Parse and type check `std` packages for editor support in the future (a `gopackagesdriver` implementation would need this).

I'd rather not close the door on these changes by committing to a directory structure where the `go` command will work.

Until that happens, you could do this on your own with a script installed as `go` somewhere in your `PATH`. It could set the appropriate environment variables, then `exec` `$(bazel info output_base)/external/go_sdk/bin/go`.
