### ISSUE TITLE
Support protoc plugin that generates yaml or text file as output instead of a go file.

### ISSUE THREAD

**Issue by sateeshpnv** [bazelbuild/rules_go#2540]
### What version of rules_go are you using?

v0.23.3

### What version of gazelle are you using?

47a2afcc7eb6e7b5dca4a791a77f459738a20483

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

MacOS

### Any other potentially useful information about your toolchain?

protoc with [go-proto-gql/protoc-gen-gqlgencfg](https://github.com/danielvladco/go-proto-gql/tree/master/protoc-gen-gqlgencfg) plugin to generate [gqlgen](https://github.com/99designs/gqlgen) yaml configuration file and graphql schema file

### What did you do?

1. Created a go_proto_compiler rule to generate .yml (yaml) file

```
go_proto_compiler(
    name = "go_gqlgencfg",
    options = ["--gqlgencfg_out="],
    plugin = "@com_github_danielvladco_go_proto_gql//go-proto-gql/protoc-gen-gqlgencfg:protoc-gen-gqlgencfg",
    suffix = ".pb.gqlgencfg.yml",
    valid_archive = False,
    visibility = ["//visibility:public"],
)
```

[go-proto-gql](https://github.com/danielvladco/go-proto-gql) protoc plugin generates yaml and graphql schema file as output from a protobuf file. Generated files are then used to run [gqlgen](https://github.com/99designs/gqlgen).

### What did you expect to see?

.yml and .graphqls files are generated.

### What did you see instead?

bazel build fails with "Unknown source type".

**Comment by jayconrod** [comment]
It sounds like it would be better to implement this as a separate Bazel rule. Why use `go_proto_library` for this?

**Comment by sateeshpnv** [comment]
Makes sense. Will try a separate Bazel rule.
