### ISSUE TITLE
I updated io_bazel_rules_go. Now the executable is not generated.  Or I hit: running gcc failed: exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by quietgopher** [bazelbuild/rules_go#2541]
### What version of rules_go are you using?
This worked using io_bazel_rules_go v0.21.3 and failed when upgrading to v0.23.3.

### What version of gazelle are you using?
v0.20.0

### What version of Bazel are you using?
```
Build label: 3.2.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 27 18:50:55 2020 (1590605455)
Build timestamp: 1590605455
Build timestamp as int: 1590605455
```

### Does this issue reproduce with the latest releases of all the above?
Bazel and rules_go are up to date.  Gazelle is not (but seems unrelated to this issue).

### What operating system and processor architecture are you using?
MacBook Pro (15-inch, 2018)
Catalina v10.15.5

### Any other potentially useful information about your toolchain?

gcc exists on $PATH.

```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What did you do?

I updated my io_bazel_rules_go.  My build stopped creating an executable in `bazel-bin/.../main/linux_amd64_pure_stripped/main`.

This seems related to a protocol buffer dependency.

```
go_binary(
    name = "main",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    visibility = ["//visibility:public"],
)
```

If I add some options for linked mode, I get the gcc error above.

```
go_binary(
    name = "main",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    cgo = 1,
    pure = "on",
    gc_linkopts = [
       "-linkmode",
       "external",
       "-extldflags",
       "-static",
    ],
    visibility = ["//visibility:public"],
 )
```

```
external/go_sdk/pkg/tool/darwin_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```

### What did you expect to see?

I expected the build to work and a linked executable in bazel-bin. 

### What did you see instead?

```
❯ bazel build main:main                             
Starting local Bazel server and connecting to it...
INFO: Analyzed target //api/main:main (154 packages loaded, 8290 targets configured).
INFO: Found 1 target...
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/io_win32.o has no symbols
[162 / 346] 12 actions, 11 running
[162 / 346] 12 actions running
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/error_listener.o has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/darwin-opt-exec-2B5CBBC6-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79/bin/external/com_google_protobuf/_objs/protobuf_lite/io_win32.o has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf.a:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/darwin-opt-exec-2B5CBBC6-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79/bin/external/com_google_protobuf/_objs/protobuf/error_listener.o has no symbols
ERROR: /Users/quietgolfer/promotedai/metrics/api/main/BUILD.bazel:30:10: GoLink api/main/main_/main failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/darwin-fastbuild-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79/bin/api/main/main_/main-0.params' -- -linkmode external ... (remaining 3 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/darwin_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH

link: error running subcommand: exit status 2
Target //api/main:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 206.883s, Critical Path: 57.86s
INFO: 533 processes: 533 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by quietgopher** [comment]
The version of my protocol buffer dependencies does not seem to make a difference.

Current:
github.com/protocolbuffers/protobuf/archive/v3.11.1.tar.gz
github.com/golang/protobuf  @ v1.3.3

I've also tried the most recent versions
github.com/protocolbuffers/protobuf/archive/v3.12.3.tar.gz
github.com/golang/protobuf  @ v1.4.2

**Comment by jayconrod** [comment]
Please edit your comment with Markdown formatting. It's very difficult to read as it is.

The error messages you posted make it sound like there's a failure building `protoc`. That should be built for your host system. Are you able to build `@com_google_protobuf//:protoc` on its own?

This target will not work by the way. `pure = "on"` implies no C toolchain should be used, but you do need a C linker if you're forcing external linking.

```
go_binary(
    name = "main",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    cgo = 1,
    pure = "on",
    gc_linkopts = [
        "-linkmode",
        "external",
        "-extldflags",
        "-static",
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by quietgopher** [comment]
Done.

`bazel build @com_google_protobuf//:protoc` works.  No additional output.

I tried a few linking options to see if I could get the executable to appear again in `bazel-bin`.  I wasn't able to find documentation on `pure` mode.  I put that in there because the default version causes different directories bazel output directories when built on mac and linux.

Did the location of executables in `bazel-...` directories change?  I now see an executable in `bazel-out/darwin-fastbuild-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79/bin/.../main/main_/main`

Got it.  That explains

**Comment by jayconrod** [comment]
> I wasn't able to find documentation on pure mode.

[`go_binary`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-binary) has the reference on this. It's not very detailed. To summarize though, `pure = "on"` is like setting `CGO_ENABLED=0` with `go build`. Additionally, it tells rules_go not to depend on the C toolchain, even if one is available.

> I put that in there because the default version causes different directories bazel output directories when built on mac and linux.

Be careful: directory names are an implementation detail and may change over time. From the command line, `bazel aquery` can tell you the paths of output files.

> Did the location of executables in bazel-... directories change?

Yes. In rules_go `v0.23.0`, we re-implemented cross-compilation using configuration transitions. That let us drop path components like `linux_amd64_race`. Bazel adds its own path component to disambiguate files built in different configurations. That's what `darwin-fastbuild-ST-05b09dfdd2e5ae92d24745e4e699444f165b36fe4c5cff40bcd8e02b7f69ac79` is.

**Comment by quietgopher** [comment]
Thanks!  This solved my issue.  

I ended up using `bazel run --run_under "echo" :main` to get the executable location.
