### ISSUE TITLE
go_binary is no longer generating artifact under bazel-bin when `goos` and `goarch` args are provided

### ISSUE THREAD

**Issue by sperretta1** [bazelbuild/rules_go#2552]
### What version of rules_go are you using? 
0.23.3

### What version of gazelle are you using?
0.21.1

### What version of Bazel are you using? 
3.2.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Mac OS

### Any other potentially useful information about your toolchain?
None

### What did you do?
I upgraded `rules_go` from `0.21.2` to `0.23.3` and noticed that bazel was no longer generating the binary artifact under `./bazel-bin`. This only happens when my `go_library` configuration includes the `goos` and `goarch` args. For example, in my project I have the following in my `BUILD.bazel` file:
```
go_binary(
    name = "engine-darwin",
    embed = ["//engine:go_default_library"],
    visibility = ["//visibility:public"],
)

go_binary(
    name = "engine-linux",
    embed = ["//engine:go_default_library"],
    visibility = ["//visibility:public"],
)
```

With this I see the following binaries:
- `bazel-bin/engine/engine-darwin_/engine-darwin`
- `bazel-bin/engine/engine-linux_/engine-linux`

However, if I add the `goos` and `goarch` arguments, these binaries are no longer generated. Here's the `BUILD.bazel` file in this case:

```
go_binary(
    name = "engine-darwin",
    embed = [":go_default_library"],
    goos = "darwin",
    goarch = "amd64",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "engine-linux",
    embed = [":go_default_library"],
    goos = "linux",
    goarch = "amd64",
    visibility = ["//visibility:public"],
)
```

Both binaries that previously were generated no longer exist.

### What did you expect to see?
I expect the binaries to be generated no differently than when the `goos` and `goarch` arguments are not passed to `go_binary`. 

### What did you see instead?
The binaries are not generated.

**Comment by jayconrod** [comment]
The output file path of `go_binary` is an implementation detail and may change over time; please don't rely on it. The [FAQ](https://github.com/bazelbuild/rules_go#how-do-i-access-go_binary-executables-from-go_test) explains some approaches for getting the path for a binary from another rule. You can also use `bazel aquery` from the command line.

This change was mentioned in the [v0.23.0 release notes](https://github.com/bazelbuild/rules_go/releases/tag/v0.23.0).

> Output file paths no longer include extra configuration data. For example, //tests/core/go_binary:hello creates the file bazel-bin/tests/core/go_binary/hello_/hello. Note that output file paths are still not stable and should not be depended on unless the "out" attribute is set explicitly (for rules that support it).

The reason for the change is that rules_go now uses transitions to target configurations to implement `goos`, `goarch` and other attributes. Bazel has a separate output tree for each target configuration, and that's where the first couple path components come from.
