### ISSUE TITLE
go_proto_library: link conflict when using go_proto_validators

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2558]
### What version of rules_go are you using?

29178b85ff03038a40e2ecb5890f3f752101b394

### What version of Bazel are you using?

3.3.1

### What did you do?

```
$ bazel test //tests/legacy/examples/proto:proto_test
```

`proto_test` depends on a `go_proto_library` that uses `//proto:go_proto_validate`. That indirectly depends on `@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library`:

* `@io_bazel_rules_go//go_proto_validate` (`go_proto_compiler`)
* `@com_github_mwitkow_go_proto_validators//:validators_golang` (`deps`)
* `@com_github_mwitkow_go_proto_validators//:_validators_golang` (`embed`)
* `@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library` (`deps`)

`@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library` should only be used for builds that don't use `go_proto_library`, i.e., those that compile pre-generated `.pb.go` files. It conflicts with `@io_bazel_rules_go//proto/wkt:descriptor_go_proto`.

Both libraries are built from the same sources, so the linker probably won't report an error because of the conflict (it can't tell the difference) but newer versions of rules_go report a warning, and in the future, it will be an error.

### What did you expect to see?

No error.

### What did you see instead?

```
package conflict error: github.com/golang/protobuf/protoc-gen-go/descriptor: multiple copies of package passed to linker:
	//proto/wkt:descriptor_go_proto
	@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library
Set "importmap" to different paths or use 'bazel cquery' to ensure only one
package with this path is linked.
This will be an error in the future.
```

**Comment by jayconrod** [comment]
Upstream issue: mwitkow/go-proto-validators#89

**Comment by Helcaraxan** [comment]
By the way the upstream has been fixed. :wink:
