### ISSUE TITLE
go_download_sdk does not support .netrc

### ISSUE THREAD

**Issue by GabrielGhe** [bazelbuild/rules_go#2560]
### What version of rules_go are you using?

v0.22.6

### What version of gazelle are you using?

Not using gazelle

### What version of Bazel are you using?

Build label: 2.0.1

### Does this issue reproduce with the latest releases of all the above?

If I want to use `go_download_sdk` with a url that requires a `.netrc`, I get `401 Unauthorized`.

### What operating system and processor architecture are you using?

ubuntu16.04 x86

### Any other potentially useful information about your toolchain?

No

### What did you do?

```
load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_register_toolchains", "go_rules_dependencies")

go_download_sdk(
    name = "go_sdk",
    urls = ["https://<internal_url>.<companyname>.com/{}"],
    sdks = {
        "linux_amd64": ("go1.14.4.linux-amd64.tar.gz", <sha256>),
        "linux_arm64": ("go1.14.4.linux-arm64.tar.gz", <sha256>),
    },
)

go_rules_dependencies()
go_register_toolchains()
```

### What did you expect to see?

That the `go_download_sdk` passes.

### What did you see instead?

`401 Unauthorized`

**Comment by jayconrod** [comment]
`go_download_sdk` uses `repository_ctx.download_and_extract` to fetch these archives. I think that method would be the right place to support `.netrc`, so please consider opening an issue at bazelbuild/bazel for this.

It may be possible to read `.netrc`, parse it in Starlark, then pass credentials to `download_and_extract` through the `auth` parameter. I'd rather not add that complexity to `go_download_sdk` though. Maybe you can implement a custom repository rule that does this, then call [`go_wrap_sdk`](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go-wrap-sdk) to configure it?

**Comment by GabrielGhe** [comment]
You're right. The approach we took was to use [`http_archive`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L109) which supports `.netrc`, and then `go_wrap_sdk`.
