### ISSUE TITLE
gazelle busted on missing differ package

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#258]
Master branch is busted. Did a `bazel clean --expunge`, even, and am still getting this:

    $  bazel build //go/tools/gazelle/...
    ERROR: /Users/jmhodges/src/github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle/BUILD:3:1: no such package '@com_github_bazelbuild_buildifier//differ': BUILD file not found on package path and referenced by '//go/tools/gazelle/gazelle:go_default_library'.
    ERROR: Analysis of target '//go/tools/gazelle/gazelle:gazelle' failed; build aborted.

**Comment by jmhodges** [comment]
Ah, looks like bazel 0.4.3 doesn't support the BUILD to BUILD.bazel file change that happened in bazelbuild/buildifer's repo.

Upgrading to 0.4.4 fixes the problem.

**Comment by pmbethe09** [comment]
That was my fault -- I incorrectly thought that 0.4.3 would work.
