### ISSUE TITLE
Can't generate Go cpuprofile/memprofile

### ISSUE THREAD

**Issue by Kazuto** [bazelbuild/rules_go#2580]
### What version of rules_go are you using?
0.21.2

### What version of gazelle are you using?
0.20.0

### What version of Bazel are you using?
2.2.0

### Does this issue reproduce with the latest releases of all the above?
Don't know, can't update because company project

### What operating system and processor architecture are you using?
darwin amd64

### Any other potentially useful information about your toolchain?
No

### What did you do?

```
bazel run --nocache_test_results :go_default_test -- -test.bench=. -- -test.cpuprofile=cpu.prof -- -test.memprofile=mem.prof
```

### What did you expect to see?
cpu.prof and mem.prof being created

### What did you see instead?
No files are created

**Comment by jayconrod** [comment]
Bazel runs tests in a temporary directory within a sandbox, so I wouldn't expect this to work. Try building the test executable first (`bazel build`) then running that binary directly (without `bazel run` or `bazel test`).

**Comment by Kazuto** [comment]
Got it, thanks. I was able to use both. The issue was my IDE which did not reload from disc fast enough to show those files.
