### ISSUE TITLE
Build failure in github.com/ulikunitz/xz under coverage

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2592]
Bazel fails to build `@com_github_ulikunitz_xz//lzma:go_default_test` under `bazel coverage`, although it succeeds in `go test -cover`:

```bash
$ go get github.com/ulikunitz/xz
$ go test -cover github.com/ulikunitz/xz/lzma
ok  	github.com/ulikunitz/xz/lzma	2.455s	coverage: 80.6% of statements
```

### What version of rules_go are you using?

0.23.7

### What version of gazelle are you using?

0.21.1

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Darwin and Linux amd 64

### What did you do?

Add the following rule to a WORKSPACE file:

```Python
go_repository(
    name = "com_github_ulikunitz_xz",
    importpath = "github.com/ulikunitz/xz",
    sum = "h1:YvTNdFzX6+W5m9msiYg/zpkSURPPtOlzbqYjrFn7Yt4=",
    version = "v0.5.7",
)
```

Run:
```bash
$ bazel coverage @com_github_ulikunitz_xz//lzma:go_default_test
```

### What did you expect to see?

Build and test succeed

### What did you see instead?

```
ERROR: /private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/external/com_github_ulikunitz_xz/lzma/BUILD.bazel:42:8: GoCompilePkg external/com_github_ulikunitz_xz/lzma/go_default_test.internal.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_ulikunitz_xz/lzma/bintree.go -src ... (remaining 151 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/sandbox/darwin-sandbox/5/execroot/__main__/external/com_github_ulikunitz_xz/lzma/bitops.go:7: syntax error: missing import path
/private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/sandbox/darwin-sandbox/5/execroot/__main__/external/com_github_ulikunitz_xz/lzma/bitops.go:9: syntax error: non-declaration statement outside function body
Target @com_github_ulikunitz_xz//lzma:go_default_test failed to build
```

**Comment by jayconrod** [comment]
Took a quick look. The original file looks like:

```
package lzma

/* Naming conventions follows the CodeReviewComments in the Go Wiki. */

// ntz32Const is used by the functions NTZ and NLZ.
const ntz32Const = 0x04d7651f
```

The file with coverage instrumentation looks like:

```
package lzma

import coverdata

/* Naming conventions follows the CodeReviewComments in the Go Wiki. */"github.com/bazelbuild/rules_go/go/tools/coverdata"

// ntz32Const is used by the functions NTZ and NLZ.
const ntz32Const = 0x04d7651f
```

[`registerCoverage`](https://github.com/bazelbuild/rules_go/blob/7ad8343a463589e43c9b8bac9aa55465f5160ddf/go/tools/builders/cover.go#L82) is the function that adds the import of `coverdata`. It basically parses the file, adds the import to the AST, then formats and writes the file back out. Looks like it needs to do something with that comment so it doesn't end up in the middle of the import declaration.
