### ISSUE TITLE
getting the wrong version of a dependency

### ISSUE THREAD

**Issue by ghasemloo** [bazelbuild/rules_go#2595]
# What version of rules_go are you using?

v0.23.7

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

2.2.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

linux

### Any other potentially useful information about your toolchain?

Here is a minimal example:
https://github.com/ghasemloo/bazel_go

### What did you do?

Using the API v2 go proto package "google.golang.org/protobuf/types/known/anypb". It works with go but not with bazel

```shell
go test ./...
```

```shell
bazel-2-2-0 test ...
```

### What did you expect to see?

should succeed without error.

### What did you see instead?

it failed with error:

> ERROR: .../golang/src/github.com/ghasemloo/bazel_go/example/BUILD.bazel:10:1: GoCompilePkg example/go_default_test.internal.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src example/example.go -src example/example_test.go -arc ... (remaining 19 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> compilepkg: error running subcommand: exit status 2
> ~/.cache/bazel/_bazel_ghasemloo/7777179a07bcc3b19260f61bcd054002/sandbox/linux-sandbox/72/execroot/__main__/example/example_test.go:13:15: undefined: anypb.New

Looking at the file

> ~/.cache/bazel/_bazel_ghasemloo/7777179a07bcc3b19260f61bcd054002/external/org_golang_google_protobuf/types/known/anypb/any.pb.go

I see that it doesn't have it, whereas the file in http://google.golang.org/protobuf/types/known/anypb does have it. It looks like it is getting it from somewhere else but not clear. 

The version specified in the WORKSPACE file is the latest (v1.25.0) but I am getting older files from somwhere (the file's timestamp is May 4th), it seems to be getting v1.21.0 
(https://pkg.go.dev/google.golang.org/protobuf@v1.21.0/types/known/anypb) instead of v1.25.0 (https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/anypb)

I have the following in WORKSPACE file:

```python
go_repository(
    name = "org_golang_google_protobuf",
    importpath = "google.golang.org/protobuf",
    sum = "h1:Ejskq+SyPohKW+1uil0JJMtmHCgJPJ/qWTxr8qp+R4c=",
    version = "v1.25.0",
)
```

**Comment by jayconrod** [comment]
Could you try moving your `go_repository` declarations above the calls to `go_rules_dependencies` and `go_register_toolchains`? `go_rules_dependencies` declares `org_golang_google_protobuf` first, and that may or may not take precedence over a later declaration. If you call `go_rules_dependencies` later, it won't override your earlier definition. [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies) has more info.

**Comment by ghasemloo** [comment]
Thanks Jay.

I updated the WORKSPACE file and played a bit around with what you suggested and instructions from the linked doc. I got it to work without moving up by reordering the top section. Not sure what was the cause though, but it is working on (I did a push).

It would be nice if there is a way to make things less surprising, e.g. would it make sense to print something when we see that a dependency definition in the WORKSPACE file is essentially ignored because of implicit previous ones? Should that be filed against the bazel?

**Comment by jayconrod** [comment]
Glad it's working.

I've opened bazel-gazelle#865, which would simply add new `go_repository` rules above calls to `go_rules_dependencies`, and `gazelle_dependencies`, so it does the right thing by default. That would remove the sharp edge here.

Bazel WORKSPACE evaluation has always been really confusing, but I don't really think it can be fixed without a major redesign which would require pretty severe incompatible changes. I'm not really confident it can be fixed at this point.

**Comment by asv** [comment]
@jayconrod But how to fix this issue if go_repository's is inside a skylark macro?

**Comment by asv** [comment]
I have a similar problem, but it doesn't fix as easily as the suggested workaround.
repro repo: https://github.com/asv/rules_go_issue2595

```shell
$ bazelisk build //...
INFO: Analyzed 2 targets (1 packages loaded, 4 targets configured).
INFO: Found 2 targets...
ERROR: /home/asmirnov/.cache/bazel/_bazel_asmirnov/14937fc9f3ef067f7f1e4b27f82fe637/external/io_bazel_rules_go/proto/wkt/BUILD.bazel:138:17: GoCompilePkg external/io_bazel_rules_go/proto/wkt/field_mask_go_proto.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 21 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/home/asmirnov/.cache/bazel/_bazel_asmirnov/14937fc9f3ef067f7f1e4b27f82fe637/sandbox/linux-sandbox/666/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/proto/wkt/field_mask_go_proto_/google.golang.org/genproto/protobuf/field_mask/field_mask.pb.go: import of "google.golang.org/protobuf/proto"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
INFO: Elapsed time: 12.683s, Critical Path: 3.60s
INFO: 53 processes: 53 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jayconrod** [comment]
> But how to fix this issue if go_repository's is inside a skylark macro?

Up to you how to manage that. Just make sure the first declaration of a repository is the version you want, and it doesn't get overridden later.

Since bazelbuild/bazel-gazelle#865 is fixed, Gazelle adds new dependencies and new macros *before* the calls to `go_rules_dependencies` and `gazelle_dependencies` if it can. I'll update the rules_go boilerplate to make that easier for new projects. I think this is a better model: direct dependencies should be declared first; indirect dependencies should be declared later and should not override direct dependency versions.

**Comment by jayconrod** [comment]
> I have a similar problem, but it doesn't fix as easily as the suggested workaround.

This looks like a new problem. I've opened #2609 to track it.

**Comment by asv** [comment]
@jayconrod thanks, I'm will follow
