### ISSUE TITLE
gopherjs support possible?

### ISSUE THREAD

**Issue by gorakhargosh** [bazelbuild/rules_go#26]
Namaste,

I'm wondering whether gopherjs support can be added to the rules set
as well.

[github.com/gopherjs/gopherjs](http://github.com/gopherjs/gopherjs)

Cheers,
Yesudeep.

**Comment by yugui** [comment]
Personally I don't think gopherjs is common enough for Go developers to support it in this repository.
It is not as common as "go build". What do you think?

But nothing prevents you from writing your own Skylark macros/rules to support gopherjs.

**Comment by gorakhargosh** [comment]
Indeed, I could write Skylark macros/rules to support gopherjs.
gopherjs doesn't come as a packaged tarball like go does. I notice
the rules fetch the go binaries before executing any build commands.
How does one do that for gopherjs?

Cheers,
Yesudeep.

**Comment by yugui** [comment]
Good point.

The (technically) easiest way is to add the skylark macros/rules in gopherjs itself.  Then you can simply import gopherjs as an external dependency. This is the way chosen in protobuf and [requested in grpc-gateway](https://github.com/gengo/grpc-gateway/issues/66).

Another way would be to import gopherjs as another external dependency. This is the way [jsonnet](https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L251) chose.
