### ISSUE TITLE
Dependency issue after v0.23.5 -> v0.23.7 upgrade

### ISSUE THREAD

**Issue by gebn** [bazelbuild/rules_go#2603]
### What version of rules_go are you using?

v0.23.7

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes, reproducible with rules_go v0.23.8.

### What operating system and processor architecture are you using?

Linux, amd64

### Any other potentially useful information about your toolchain?

No, all vanilla.

### What did you do?

Upgrade from rules_go v0.23.5 (successful build log [here](https://travis-ci.org/github/gebn/bmc_exporter/builds/709229480)) to v0.23.7 (failing build log [here](https://travis-ci.org/github/gebn/bmc_exporter/builds/715640299)). The only change was to the `http_archive` rule in `WORKSPACE` (diff of those builds [here](https://github.com/gebn/bmc_exporter/compare/33d490de3c4ed6b4cf7f7581305207a4706a2540...f2f9a41637962307f62ceda8af7a2bf008787f99)).

Build command: `bazel build --config ci --platforms "@io_bazel_rules_go//go/toolchain:windows_amd64" //:archive`

### What did you expect to see?

The build to succeed, given there were no other changes.

### What did you see instead?

The build fail due to a dependency error:

```
compilepkg: missing strict dependencies:
	/home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/sandbox/linux-sandbox/496/execroot/__main__/external/com_github_prometheus_client_golang/prometheus/process_collector_windows.go: import of "golang.org/x/sys/windows"
No dependencies were provided.
```

On v0.23.5, there were two instances of build constraints excluding Go files; they didn't affect the build so I didn't think anything of them:

```
(15:37:14) DEBUG: /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_prometheus_common: gazelle: finding module path for import golang.org/x/sys/windows/svc/eventlog: exit status 1: can't load package: package golang.org/x/sys/windows/svc/eventlog: build constraints exclude all Go files in /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200615200032-f1bc736245b1/windows/svc/eventlog
(15:37:15) DEBUG: /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_google_gopacket: gazelle: finding module path for import golang.org/x/sys/windows: exit status 1: can't load package: package golang.org/x/sys/windows: build constraints exclude all Go files in /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/windows
```

After upgrading, there were then three instances, and the build failed with an error related to `golang.org/x/sys/windows`:

```
(21:13:11) DEBUG: /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_prometheus_client_golang: gazelle: finding module path for import golang.org/x/sys/windows: exit status 1: can't load package: package golang.org/x/sys/windows: build constraints exclude all Go files in /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/windows
(21:13:18) DEBUG: /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_prometheus_common: gazelle: finding module path for import golang.org/x/sys/windows/svc/eventlog: exit status 1: can't load package: package golang.org/x/sys/windows/svc/eventlog: build constraints exclude all Go files in /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200615200032-f1bc736245b1/windows/svc/eventlog
(21:13:19) DEBUG: /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_google_gopacket: gazelle: finding module path for import golang.org/x/sys/windows: exit status 1: can't load package: package golang.org/x/sys/windows: build constraints exclude all Go files in /home/travis/.cache/bazel/_bazel_travis/9d50d981d614dd3fd344f3d990e4b19b/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/windows
```

I've been bashing my head against this, and can't figure out what's wrong - I can't see anything in the changelog between v0.23.5 and v0.23.7 that would have made this happen.

**Comment by jayconrod** [comment]
Not sure why this additional build file generation error is causing the build to fail when the first two don't. They should all be fixed.

Those messages are emitted by Gazelle, when it's run inside `go_repository` to generate build files. When Gazelle resolves an import of a package outside the module it's working on, it normally relies on information from the `WORKSPACE` file in the main repository to map between module paths and repository names. In this case, `WORKSPACE` doesn't have the information it's looking for, so it uses `go list` to look up the module name. `go list` is tied to a specific platform (by default, the host platform), so since this is a cross-compiling build, that fails too.

You should be able to fix this by declaring the missing external repositories in `WORKSPACE` like this:

```
# gazelle:repository go_repository name=org_golang_x_sys importpath=golang.org/x/sys
```

Ideally, you'll have one declaration for each `go_repository` declared outside of `WORKSPACE`. You won't need these declarations for `go_repository` dependencies inside `WORSKPACE` or for dependencies declared in a file generated with `gazelle update-repos -to_macro=file.bzl%deps`.

**Comment by gebn** [comment]
Wonderful, adding that `gazelle:repository` directive has [cleared up](https://travis-ci.org/github/gebn/bmc_exporter/builds/718781649) all the errors and let the build pass! Is creating these automatically with `update-repos` and a `go.mod` file the recommended approach, so the project would effectively build with both vanilla Go tools and Bazel?

**Comment by jayconrod** [comment]
> Is creating these automatically with update-repos and a go.mod file the recommended approach, so the project would effectively build with both vanilla Go tools and Bazel?

Yes. There are several advantages to this:

* Managing dependencies with the go tool helps ensure you're using a consistent set of dependency versions. For example, if you depend on A and B, and they depend on C at different versions, you'll get a version of C that satisfies both requirements.
* Non-Bazel projects can depend on your project more easily (mostly relevant for open source).
* There's still a lot of work to be done to make tools work well with Bazel, especially with editors (#512). If an editor can mostly pretend it's running in a Go modules project, it will deliver a better experience.

**Comment by gebn** [comment]
That's really helpful - thank you for taking the time to provide the context! I'll update my `rules_go` projects.
