### ISSUE TITLE
gazelle is erroring on unfound _test package in go_test rule

### ISSUE THREAD

**Issue by grahamjenson** [bazelbuild/rules_go#2605]
### What version of rules_go are you using?

v0.23.8

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

bazel 3.4.1

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macOS 

### What did you do?

`bazel run gazelle` causes an error because it cannot find a nonexistant package `vector2d_test`

### What did you expect to see?

Not the above error

### What did you see instead?

```$ bazel run gazelle
INFO: Analyzed target //:gazelle (27 packages loaded, 160 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  .bazel-bin/gazelle-runner.bash
  .bazel-bin/gazelle
INFO: Elapsed time: 0.524s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: finding module path for import github.com/grahamjenson/repo/shared/package/vector2d_test: exit status 1: go: finding module for package github.com/grahamjenson/repo/shared/package/vector2d_test
go: downloading github.com/grahamjenson/repo v0.0.0-20200816004058-8beb1f15691a
module github.com/grahamjenson/repo@latest found (v0.0.0-20200816004058-8beb1f15691a), but does not contain package github.com/grahamjenson/repo/shared/package/vector2d_test
```

### Cause

This PR https://github.com/bazelbuild/rules_go/pull/2331 from @jayconrod diff in file `go/tools/builders/generate_test_main.go ` :

```
for name := range importMap {		
  if !pkgs[name] {
    importMap[name].Name = "_"  // Set the names for all unused imports to "_"
  }
  cases.Imports = append(cases.Imports, importMap[name])
}
```

This causes the `_test` package to be added even though it is not used, and then gazelle cannot resolve it.

### Workaround

I think that manually setting the `go_test` rules `importpath = "github.com/grahamjenson/repo/shared/pacakge/vector2d",` seems to work. Though I have not dug into why, or if this is a real fix.

### Possible fixes

Changing the above code to:

```
for name := range importMap {		
  if pkgs[name] {
    cases.Imports = append(cases.Imports, importMap[name])
  }
}
```

Would stop adding the unused package, but as I understand from the PR, these packages might have globals that are needed even though not used. So I am unsure if this is a long-term or workable solution (this is why I reported as an issue and not a PR))

**Comment by jayconrod** [comment]
Could you post an example that reproduces this problem? Or instructions to reproduce it? The repository `github.com/grahamjenson/repo` doesn't exist or is private, so at this point, I'm not sure what the problem is and can't help you.

Your fix is not correct. The code is preparing to generate blank imports for test dependencies, which is necessary because test imports aren't directly referenced by the main package.
