### ISSUE TITLE
"fingerprint mismatch" and "multiple copies of package passed to linker"

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_go#2610]
### What version of rules_go are you using?

```
v0.23.8
```

### What version of gazelle are you using?

Latest (need gRPC 1.30 bugfix) `19b02adaffe99b5c1197f65234d8844ef5c9174532d7dd485d65401fe8547bec`

### What version of Bazel are you using?

```
3.2.0
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Attempt to build binary with gRPC and gRPC gateway.

### What did you see instead?

I need help in knowing how to debug the following error:

```
  (cd /home/bweston/.cache/bazel/_bazel_bweston/ef768c7103e8cc29b5e76fb15d2223c4/sandbox/linux-sandbox/2014/execroot/de_lwebcode_cosmic && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-fastbuild/bin/gateways/introducers/cmd/api-server/api-server_/api-server-0.params' -- -extld /usr/bin/gcc -linkmode external '-buildid=redacted' -extldflags '-fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -lm -static')
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/linux_amd64/link: fingerprint mismatch: github.com/grpc-ecosystem/grpc-gateway/runtime has b30117f80d66081b, import from main expecting efa8f74acb317603
link: error running subcommand: exit status 2
package conflict error: github.com/grpc-ecosystem/grpc-gateway/internal: multiple copies of package passed to linker:
Target //gateways/introducers/cmd/api-server:api-server failed to build
```

I see two things "fingerprint mismatch" and "multiple copies of package passed to linker" both of which I don't know how to solve.

Any help would be appreciated.

**Comment by jayconrod** [comment]
The `fingerprint mismatch` error is emitted by the Go linker. It indicates that `main` was compiled against one version of `github.com/grpc-ecosystem/grpc-gateway/runtime`, but a different version of `github.com/grpc-ecosystem/grpc-gateway/runtime` was passed to the linker, with different export data.

The `package conflict` error is emitted by the rules_go wrapper around the linker. It indicates multiple copies of the package `github.com/grpc-ecosystem/grpc-gateway/internal` were used when building a binary.

`bazel cquery` may be useful for debugging this. Use the `deps` function to print everything your binary transitively depends on and find out what the duplicate targets are. If one target is unexpected, use `somepath` to print the chain of dependencies.

**Comment by bweston92** [comment]
Ok, I thought rules_go would dedupe. Will see what I can find out using bazel cquery. Thanks

**Comment by jayconrod** [comment]
In the past, rules_go has allowed duplicates. We haven't quite switched to making it a hard error yet.

The Go 1.15 linker is stricter than 1.14 (and the fingerprint message is new in 1.15). It indicates that the duplicate really is not safe. The fingerprints are hashes of export data, so it means a package has a different set of exported definitions than the package passed to the linker.

**Comment by bweston92** [comment]
I'm not too sure how to use the `cquery` command, is the link wrapper able to say where the conflicted dependencies are? I cannot see where `github.com/grpc-ecosystem/grpc-gateway` is being used loaded in my own repos file.

**Comment by bweston92** [comment]
If I take away mine, there is an error it doesn't exist (which I would expect as `com_github_grpc_ecosystem_grpc_gateway` was unique anyway)

**Comment by bweston92** [comment]
Ok found it, if anyone sees this in future and uses `build_stack_rules_proto` then you'll need to patch this file https://github.com/stackb/rules_proto/blob/b2913e6340bcbffb46793045ecac928dcf1b34a5/deps.bzl#L217
