### ISSUE TITLE
Build error on mips64el

### ISSUE THREAD

**Issue by packyzbq** [bazelbuild/rules_go#2611]
Hi, I enconter a problem when build envoy on mips64el platform.
```
uname -a
Linux 0ee3b64e5ff9 3.10.0-862.9.1.ns7_4.37.mips64el #1 SMP PREEMPT Tue Feb 26 19:23:39 CST 2019 mips64el GNU/Linux
```
The error is as follows:
```
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//src/envoy:envoy' failed; build aborted: Analysis failed
INFO: Elapsed time: 475.089s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (195 packages loaded, 2043 targets configured)
make: *** [Makefile.core.mk:63: build_envoy] Error 1
```
[toolchain.txt](https://github.com/bazelbuild/rules_go/files/5097492/toolchain.txt)
The toolchain.txt is the output after I add `--toolchain_resolution_debug`. It is strange that the platform is `@platforms//cpu:mips64` . However my cpu platform is misp64el

BUILD file is as bellow:
```
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

gazelle(
    name = "gazelle",
    external = "vendored",
)

go_binary(
    name = "protoc-gen-validate",
    embed = [":go_default_library"],
    importpath = "github.com/envoyproxy/protoc-gen-validate",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/envoyproxy/protoc-gen-validate",
    visibility = ["//visibility:private"],
    deps = [
        "//module:go_default_library",
        "//vendor/github.com/lyft/protoc-gen-star:go_default_library",
        "//vendor/github.com/lyft/protoc-gen-star/lang/go:go_default_library",
    ],
)
```

By the way rules_go version is v0.20.3.

So how can I solve this promblem?

**Comment by jayconrod** [comment]
> By the way rules_go version is v0.20.3.

Sorry, this minor version is not supported anymore. I suspect you'll have the same issue on the latest version, but `v0.20.x` won't be updated in the future.

> It is strange that the platform is @platforms//cpu:mips64 . However my cpu platform is misp64el

How are you specifying this exactly? I'm not seeing `mips64` in [`@platforms//cpu`](https://github.com/bazelbuild/platforms/blob/master/cpu/BUILD). There is are platform constraints for mips in `@io_bazel_rules_go//go/toolchain`, but since there aren't canonical Bazel built-in constraint values, there's no built-in support for them. They might still be used by defining a custom `platform` though.

**Comment by packyzbq** [comment]
@jayconrod  Thanks for your reply! I just tried the `v0.23.8` and the error still exists. I don't know where to change and how to solve this.

> How are you specifying this exactly? I'm not seeing mips64 in @platforms//cpu. There is are platform constraints for mips in @io_bazel_rules_go//go/toolchain, but since there aren't canonical Bazel built-in constraint values, there's no built-in support for them. They might still be used by defining a custom platform though.

I get some log using `--toolchain_resolution_debug` flag. The following segment is part of whole log. You can find some mips toolchains that don't match the `@platforms//cpu:mips64`. 
```
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips, which does not match value @platforms//cpu:mips64 from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips64-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips64, which does not match value @platforms//cpu:mips64 from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips64-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips64le-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips64le, which does not match value @platforms//cpu:mips64 from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips64le-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mipsle-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mipsle, which does not match value @platforms//cpu:mips64 from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mipsle-impl, because of target platform mismatch
```

**Comment by jayconrod** [comment]
What was the value of `--platforms` passed to Bazel, if any? If you defined a custom `platform`, what constraints does it have?

Same question for `--host_platform`.

**Comment by packyzbq** [comment]
I've solved this problem and close this issue.

**Comment by orangeji11** [comment]
遇到了相同的问题，可以请教您是怎么解决的吗
