### ISSUE TITLE
rules_go provides no bzl_library targets

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/rules_go#2619]
### What version of rules_go are you using?

v0.23.8

### What version of gazelle are you using?

none

### What version of Bazel are you using?

3.3.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Ubuntu 20.04 x86_64

### Any other potentially useful information about your toolchain?

n/a

### What did you do?

I've defined a [`stardoc`](https://github.com/bazelbuild/stardoc) target for a rule set that itself uses `rules_go`. The `stardoc` rule has a `deps` attribute that expects `bzl_library` targets. The transitive closure of the `deps` attribute must cover all `*.bzl` files that are loaded directly or indirectly by the rules to be documented. `rules_go` does not expose a `bzl_library` attribute, hence I cannot specify it as a dependency on my use-case and cannot generate Stardoc documentation for my use-case.

### What did you expect to see?

That rules_go defines a `bzl_library` target for `rules_go` that includes all relevant `.bzl` files.

### What did you see instead?

That rules_go defines no `bzl_library` target.

**Comment by jayconrod** [comment]
I generally agree we should do this.

I think this is best implemented using the new `bzl` extension for Gazelle. To the extent possible, these targets should be automatically maintained and should follow conventions. For that reason, I'd prefer to go with #2621. It looks like there are still some kinks to work out in the Gazelle extension though.

Both of these PRs are significant changes right before a release, so this won't make it into `v0.24.0`.
