### ISSUE TITLE
Linker error when recompiling archives with cdeps dependency

### ISSUE THREAD

**Issue by martinxsliu** [bazelbuild/rules_go#2622]
### What version of rules_go are you using?

`0.23.8`. The issue reproduces with versions `0.23.6` and above. I've traced the issue to https://github.com/bazelbuild/rules_go/pull/2579.

### What version of gazelle are you using?

`0.21.1`

### What version of Bazel are you using?

`3.3.0`

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS 10.14.6 Mojave

### What did you do?

I have a minimal reproduction here: https://github.com/martinxsliu/testgo

I have an external test `a_test` that imports a package `b` that imports the package under test `a`. `b` also imports a cgo package `cgo` which has a `cdep` dependency on a precompiled archive.

```
a_test -> b -> a
          └--> cgo -> cgo.a (cc_import)
```

Trying to build `//a:go_default_test` fails with the linker complaining that it's not able to find the precompiled C archive (error message below).

I think this may be a regression introduced by https://github.com/bazelbuild/rules_go/pull/2579 because:
* It works on a commit of rules_go before https://github.com/bazelbuild/rules_go/pull/2579.
* It errors when registering a Go 1.14 toolchain.
* Adding a direct dependency from `a_test` to `cgo` works.
* `go build` works.

I'm also fairly certain that this is not a generic cgo issue, but rather we're failing to properly propagate the cdep since the build will pass if I replaced the archive with inline C and cleared the `cdeps` attr.

### What did you expect to see?

Build succeeds

### What did you see instead?

```
ERROR: /Users/martin/repos/testgo/a/BUILD.bazel:10:8: GoLink a/go_default_test_/go_default_test failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder link -sdk external/go_sdk -installsuffix darwin_amd64 -arc ... (remaining 21 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/darwin_amd64/link: running external/local_config_cc/cc_wrapper.sh failed: exit status 1
clang: error: no such file or directory: 'cgo/cgo.a'
clang: error: no such file or directory: 'cgo/cgo.a'
```

**Comment by jayconrod** [comment]
Thanks for reporting this. The repro repository is really helpful.

I think the problem here is the `cgo/cgo.a` file is not included as an input to the link action. The build succeed when sandboxing is disabled.

**Comment by jayconrod** [comment]
#2625 should fix this. Thanks again for a really clear bug report.
