### ISSUE TITLE
Cannot use resolve file with rules_go

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/rules_go#2634]
### What version of rules_go are you using?

Latest HEAD at bf3c5a94373cb9f080d08af98c762ab9578541c2

### What version of gazelle are you using?

Irrelevant

### What version of Bazel are you using?

```
Build label: 3.4.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 10 18:06:41 2020 (1597082801)
Build timestamp: 1597082801
Build timestamp as int: 1597082801
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS/CentOS

### Any other potentially useful information about your toolchain?

Git 2.27.0

### What did you do?

```
git clone https://github.com/bazelbuild/rules_go
cd rules_go

bazel sync --experimental_repository_resolved_file=resolved_1.bzl
bazel sync --experimental_repository_resolved_file=resolved_2.bzl

# compare first and second file
```

### What did you expect to see?

Generated resolved files to be identical

### What did you see instead?

```
--- a/resolved.bzl
+++ b/resolved.bzl
@@ -1516,7 +1516,7 @@ resolved = [
                     "importpath": "github.com/golang/glog",
                     "commit": "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
                 },
-                "output_tree_hash": "51f9e9f9fa21fd50b830caa091adc5c284b8865e762b1cc425e90a2fc6590c08"
+                "output_tree_hash": "70d51b425e9e97e14108c38c02bce38880a1d7e77f0f7e7dc78ab477aeb17147"
             }
         ]
     },
@@ -1572,7 +1572,7 @@ resolved = [
                     "importpath": "golang.org/x/mod",
                     "commit": "c0d644d00ab849f4506f17a98a5740bf0feff020"
                 },
-                "output_tree_hash": "27b04532ad172ce5d33291dbe8e712ce79648d91dec1df413321ff571a004f66"
+                "output_tree_hash": "2cb3fa4c4a8b8389bbdfb21c925f291adf27b968e2279421579307cb820d28f1"
             }
         ]
     },
@@ -1596,7 +1596,7 @@ resolved = [
                     "importpath": "golang.org/x/net",
                     "commit": "57efc9c3d9f91fb3277f8da1cff370539c4d3dc5"
                 },
-                "output_tree_hash": "21c1809d529bdd33c6f0189d019eb36a3a7e255b89c7e4f43dd5da6e7ca9ce7b"
+                "output_tree_hash": "6aef367b04e7bcbb39f8971441c1bf86dc3b5295140b373af1a5d5bf20ffda4d"
             }
         ]
     },
@@ -1620,7 +1620,7 @@ resolved = [
                     "importpath": "golang.org/x/text",
                     "commit": "a9a820217f98f7c8a207ec1e45a874e1fe12c478"
                 },
-                "output_tree_hash": "4d83b3029d0334208c78559f76c931d45a907b86f3b785412415e24cd7e47803"
+                "output_tree_hash": "56b35021fd120628edf3cfe593aa8558dea1dae400409c73588ff355b26e3256"
             }
```

**Comment by jayconrod** [comment]
rules_go doesn't use `bazel sync`, and the repositories you've listed are just used for internal testing, so I'm tempted to close this issue. What was the reason for opening it?

**Comment by sluongng** [comment]
We are trying to mirror this repo and rely on `resolved.bzl` to be consistent and ensure all the external deps have SHA256 verified.

Seems like this is not possible with `rules_go` then given the current way the patches are applied?

**Comment by jayconrod** [comment]
These repositories are declared by the `popular_repos` macro. They're used for testing `//tests/integration/popular_repos`. They're implemented using an old version of Gazelle and `go_repository`. We'll probably update to a newer version soon. I don't know what's causing these differences or how the `output_tree_hash` is specifically generated, but maybe that will fix the issue.
