### ISSUE TITLE
Linker package conflicts although proto disabled globally

### ISSUE THREAD

**Issue by tommyknows** [bazelbuild/rules_go#2640]
### What version of rules_go are you using?

v0.24.1

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

They are all the latest releases :) 

### What operating system and processor architecture are you using?

Linux / AMD64

### Any other potentially useful information about your toolchain?

Using a cache? I don't think there's anything special, we're just getting started with Bazel.

### What did you do?

I'm having a Go test that imports `"@com_google_cloud_go_pubsub//:go_default_library` (`cloud.google.com/go/pubsub`), which in turn depends on `github.com/golang/protobuf/ptypes/duration`. 

When running `bazel test //...`, I get error messages from all Go tests / build actions within that workspace:

```
INFO: From GoLink mymodule-x/integration-test/go_default_test_/go_default_test:
package conflict error: github.com/golang/protobuf/ptypes/duration: multiple copies of package passed to linker:
This will be an error in the future.
```

The build files for these tests are generated by Gazelle, apart from setting the size, timeout & a tag, there's nothing special to see there:
```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "go_default_test",
    size = "small",
    timeout = "eternal",
    srcs = ["module_test.go"],
    tags = ["integration-test"],
    deps = [
        "@com_google_cloud_go_pubsub//:go_default_library",
        "@org_golang_google_api//option:go_default_library",
    ],
)
```

The root BUILD file:
```bzl
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

# gazelle:prefix gitlab.company.com/ourproject
# gazelle:proto disable_global
gazelle(name = "gazelle")

buildifier(name = "buildifier")
```

All `go_repository` definitions in the WORKSPACE file have `build_file_proto_mode = "disable_global"` set, generated through the following command:
```
        bazel run //:gazelle -- \
                update-repos \
                -from_file=go.mod \
                -prune=true \
                -build_file_proto_mode=disable_global \
                -to_macro=build/repositories.bzl%go_repositories
```

The `go_repository` rule for `github.com/golang/protobuf`:
```bzl
    go_repository(
        name = "com_github_golang_protobuf",
        build_file_proto_mode = "disable_global",
        importpath = "github.com/golang/protobuf",
        sum = "h1:+Z5KGCizgyZCbGh1KZqA0fcLLkwbsjIzS4aV2v7wJX0=",
        version = "v1.4.2",
    )
```

### What did you expect to see?

No linker errors. As described in [Avoiding Conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts), we're using the pre-generated files everywhere. We also don't have any `go_proto_*` rules in our workspace. 

Not sure what to do or how to debug - as mentioned, we're just getting started with Bazel. I'm happy to dig into this, but need some pointers as to how & where to start.

**Comment by jayconrod** [comment]
Does `bazel cquery somepath(//..., @io_bazel_rules_go//proto/wkt:duration_go_proto)` show something useful?

**Comment by tommyknows** [comment]
Not sure:
```
//mymodule-x/integration-test:go_default_test (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@com_github_gruntwork_io_terratest//modules/k8s:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@io_k8s_client_go//kubernetes:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@io_k8s_client_go//discovery:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@com_github_googleapis_gnostic//OpenAPIv2:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@com_github_googleapis_gnostic//compiler:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@com_github_googleapis_gnostic//extensions:go_default_library (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@com_github_golang_protobuf//ptypes:go_default_library_gen (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
@io_bazel_rules_go//proto/wkt:duration_go_proto (a48bb0c187c9a31db40dce218439b5ef2b842a46c8f563d92af4fadb74c545c6)
```

What are these hashes? What should I look for?
Thanks for the quick response!

**Comment by jayconrod** [comment]
The hashes are just a hash of your current configuration, probably not important.

This output shows a chain of dependencies from a test in your repo to `@io_bazel_rules_go//proto/wkt:duration_go_proto`, which should not be passed to the linker. So you need to figure out a way to adjust your dependencies to break that chain and avoid the conflict.

How is `com_github_googleapis_gnostic` declared? It should probably be a `go_repository` with `build_file_proto_mode = "disable_global"`.

**Comment by tommyknows** [comment]
You must be a wizard! 😄 
It seems like `com_github_googleapis_gnostic` dependency was declared twice, with two different versions (one with `v0.5.0` and one with `v0.3.1`). I'm not sure how it came to that, but apparently, Gazelle didn't really prune away the imports. 

I _think_ declaring the same `go_repository` twice (e.g. with the same name) probably should result in an error? It seems to lead to weird behaviour, and I guess Gazelle doesn't (can't?) really do anything here. 

When setting up my Bazel installation, I had a look at https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent. And before running `gazelle update-repos`, they actually prune the whole `repositories.bzl` file. Now I know why :)

I removed my `repositories.bzl` file, had gazelle regenerate it and now it appears to be working. 
Thanks a lot for your help!

**Comment by jayconrod** [comment]
Glad you got it working!

Bazel has some really strange behavior for declaring and overriding external repositories multiple times. Generally, the last declaration wins unless something has already been loaded, in which case the first declaration wins. `go_repository` won't warn about this, since it is "normal" Bazel behavior, but it's best to avoid that happening if possible.

FYI The Gazelle `update-repos` command has a `-prune` flag, which can remove `go_repository` rules that aren't needed anymore. Not sure if it would help in this specific situation, but it might be useful.

I'll close this issue since it sounds like you've resolved the problem, but let me know if you have other questions.

**Comment by tommyknows** [comment]
I know about the `prune` flag and also used it (as written in the description of this issue). That's what's weird about it. 

Maybe that is flaky, which would explain why the people over at Gitlab also first clean the file & then run gazelle...?

Thanks for the explanation
