### ISSUE TITLE
go_library: compilepkg failed: mkdir The filename or extension is too long on Windows

### ISSUE THREAD

**Issue by ukai** [bazelbuild/rules_go#2641]
### What version of rules_go are you using?

0.24.1

### What version of gazelle are you using?

0.21.1

### What version of Bazel are you using?

0.3.2

### Does this issue reproduce with the latest releases of all the above?

not yet checked

### What operating system and processor architecture are you using?

Windows

### What did you do?

```
> bazelisk build //cmd/...
```

### What did you expect to see?

build succeeds

### What did you see instead?

build failed
```
ERROR: C:/src/home/ukai/_bazel_ukai/tmh4tcb4/external/org_golang_google_protobuf/internal/encoding/messageset/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_protobuf/internal/encoding/messageset/messageset.a failed (Exit 1)
compilepkg: mkdir bazel-out\x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092\bin\external\org_golang_google_protobuf\internal\encoding\messageset\x_files236711581: The filename or extension is too long.
INFO: Elapsed time: 16.540s, Critical Path: 0.89s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

messageset/BULID.bazel is
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "messageset",
    srcs = ["messageset.go"],
    importpath = "google.golang.org/protobuf/internal/encoding/messageset",
    visibility = ["//:__subpackages__"],
    deps = [
        "//encoding/protowire",
        "//internal/errors",
        "//reflect/protoreflect",
        "//reflect/protoregistry",
    ],
)
```
so it is failing in go_library.

**Comment by ukai** [comment]
can build if down version to rules_go 0.23.9

seems regression in 0.24.x

**Comment by ukai** [comment]
https://github.com/bazelbuild/rules_go/commit/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2

outExport becomes too long?
@linzhp

**Comment by linzhp** [comment]
I think it is failing here: https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compile.go#L159

It's complaining `bazel-out\x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092` being too long, not the actual temp directory.

I wonder what build configuration would put build artifacts in there. I saw it in Darwin and Linux too.

**Comment by jayconrod** [comment]
`outExport` might just need to be absolutized. Absolute paths on Windows are allowed to be longer than relative paths.

From the error message, this is probably coming from `compilepkg.go`, not `compile.go`. The latter isn't used by actions used by rules_go rules. It can still be used by other rules with the toolchain API, but I don't think that's the case here.

This is on my list to investigate, but I probably won't get to it this week.

**Comment by ukai** [comment]
ah `compilepkg.go`.
then 
https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compilepkg.go#L322

?

`outXPath` is `outFactsPath`
https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compilepkg.go#L140

so, `-x` value?
https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compilepkg.go#L66

**Comment by ukai** [comment]
```
cd C:/src/home/ukai/_bazel_ukai/tmh4tcb4/execroot/re_client
  SET CGO_ENABLED=1
    SET GOARCH=amd64
    SET GOOS=windows
    SET GOPATH=
    SET GOROOT=external/go_sdk
    SET GOROOT_FINAL=GOROOT
    SET PATH=c:/tools/msys64/mingw64/bin
  bazel-out/host/bin/external/go_sdk/builder.exe compilepkg -sdk external/go_sdk -installsuffix windows_amd64 -src external/org_golang_google_protobuf/internal/encoding/messageset/messageset.go -arc google.golang.org/protobuf/encoding/protowire=google.golang.org/protobuf/encoding/protowire=bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/encoding/protowire/protowire.x -arc google.golang.org/protobuf/internal/errors=google.golang.org/protobuf/internal/errors=bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/internal/errors/errors.x -arc google.golang.org/protobuf/reflect/protoreflect=google.golang.org/protobuf/reflect/protoreflect=bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/reflect/protoreflect/protoreflect.x -arc google.golang.org/protobuf/reflect/protoregistry=google.golang.org/protobuf/reflect/protoregistry=bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/reflect/protoregistry/protoregistry.x -importpath google.golang.org/protobuf/internal/encoding/messageset -p google.golang.org/protobuf/internal/encoding/messageset -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/internal/encoding/messageset/messageset.a -x bazel-out/x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/org_golang_google_protobuf/internal/encoding/messageset/messageset.x -gcflags  -asmflags
ERROR: C:/src/home/ukai/_bazel_ukai/tmh4tcb4/external/org_golang_google_protobuf/internal/encoding/messageset/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_protobuf/internal/encoding/messageset/messageset.a failed (Exit 1)
compilepkg: mkdir bazel-out\x64_windows-opt-exec-B51C0BA3-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092\bin\external\org_golang_google_protobuf\internal\encoding\messageset\x_files303035073: The filename or extension is too long.
```

**Comment by ukai** [comment]
confirmed that using absolute path at
https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compilepkg.go#L322
fixes the issue.

**Comment by ukai** [comment]
we need to fix compile.go as well?
https://github.com/bazelbuild/rules_go/blob/440d3abcfcd691f6a374bbbc7f3f6a6acfc6f6e2/go/tools/builders/compile.go#L159

**Comment by linzhp** [comment]
Can you test if #2648 fixes this issue?

**Comment by ukai** [comment]
yeah, #2648 fixes this issue.
