### ISSUE TITLE
go: make error output less verbose

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2661]
In PR #2585, we started printing commands run by the builder binary any time there's a failure.

This tends to be pretty chatty in most circumstances. The command lines are useful for debugging the rules and the builder, but not for diagnosing problems in programs being built. These messages should not be shown by default, but there should be some way to opt into them.

Based on discussion in #2585, setting an environment variable like `--action_env=GO_VERBOSE_FAILURES=1` seems like a good way to approach this.

**Comment by linzhp** [comment]
I am also OK with only printing the subcommand without environment variables and parameters. The original intention of #2585 is to debug build failures on CI that cannot be reproduced locally. Printing out subcommand helps to narrow down the problem. If the failure can be reproduced locally, the builder command and it's environment printed out by `--verbose_failures` is enough, but if the failure cannot be reproduced locally, printing out the full subcommand and its environment isn't going to be more helpful than the subcommand name.

So we can print out something like:

```
compilepkg: error running subcommand "external/go_sdk/pkg/tool/darwin_amd64/compile": exit status 2
```

and avoid adding another condition

**Comment by jayconrod** [comment]
@linzhp #2664 should do what you suggested.

I couldn't get `--action_env=GO_VERBOSE_FAILURES=1` to work. I forgot that Bazel ignores `--action_env` except for actions that have `use_default_shell_env=True`. Setting that would make it likely that the user's environment would interfere with some actions, so let's not do that for now.
