### ISSUE TITLE
cgo: problem including externally compiled header files

### ISSUE THREAD

**Issue by otan** [bazelbuild/rules_go#2667]
Apologies in advance if this is the wrong repo!

### What version of rules_go are you using?

v0.23.8

### What version of gazelle are you using?
The one patched with https://github.com/bazelbuild/bazel-gazelle/pull/933

### What version of Bazel are you using?
Build label: 3.5.1-homebrew

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
darwin

### Any other potentially useful information about your toolchain?
not that I know of

### What did you do?
I'm trying to link against a locally included checkout of the PROJ library.

In my `WORKSPACE`, I have:

```

new_local_repository(
  name = "proj",
  path = "./c-deps/proj",
  build_file_content = BUILD_ALL_CONTENT,
)
```

In `//c-deps/BUILD.bazel`, i have
```
load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

cmake_external(
    name = "proj",
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "BUILD_LIBPROJ_SHARED": "OFF",
    },
    lib_source = "@proj//:all",
    out_include_dir = "src",
    static_libraries = ["libproj.a"],
    visibility = ["//visibility:public"],
)
```

Which I am trying to build with this inside `//:all`:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# Lets you run `bazel run //:gazelle` to generate BUILD files. Will need to be
# re-run if any of the directives below are changed.

# gazelle:prefix github.com/cockroachdb/cockroach
# gazelle:build_file_name BUILD.bazel
# gazelle:proto disable_global
# gazelle:resolve go github.com/grpc-ecosystem/grpc-gateway/internal //vendor/github.com/grpc-ecosystem/grpc-gateway/internal

gazelle(
    name = "gazelle",
    prefix = "github.com/cockroachdb/cockroach",
)

go_library(
    name = "cockroach_lib",
    srcs = [
        "main.go",
        "proj.cc",
        "proj.h",
    ],
    cgo = True,
    clinkopts = select({
        "@io_bazel_rules_go//go/platform:aix": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:android": [
            "-lproj",
            "-lrt -lm -lpthread",
        ],
        "@io_bazel_rules_go//go/platform:darwin": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:dragonfly": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:freebsd": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:illumos": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:ios": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:js": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:linux": [
            "-lproj",
            "-lrt -lm -lpthread",
        ],
        "@io_bazel_rules_go//go/platform:nacl": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:netbsd": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:openbsd": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:plan9": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:solaris": [
            "-lproj",
        ],
        "@io_bazel_rules_go//go/platform:windows": [
            "-lproj_4_9 -lshlwapi -lrpcrt4",
        ],
        "//conditions:default": [],
    }),
    cppopts = ["-I../../../c-deps/proj/src"],
    cxxopts = ["-std=c++14"],
    importpath = "github.com/cockroachdb/cockroach",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "cockroach",
    embed = [":cockroach_lib"],
    visibility = ["//visibility:public"],
)
```

It cannot resolve the `<proj_api.h>` path, instead looking at another location (or failing if I uninstall proj):

```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from /private/var/tmp/_bazel_otan/2c69235be3e3cb8620d3c9f01728fe50/sandbox/darwin-sandbox/48/execroot/proj-repro/proj.cc:13:
/usr/local/include/proj_api.h:37:2: error: 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
#error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
```

This builds normally using `go build`, with the cgo headers:
```
// #cgo CXXFLAGS: -std=c++14
// #cgo CPPFLAGS: -Ic-deps/proj/src
// #cgo !windows LDFLAGS: -lproj
// #cgo linux LDFLAGS: -lrt -lm -lpthread
// #cgo windows LDFLAGS: -lproj_4_9 -lshlwapi -lrpcrt4
// #cgo LDFLAGS: -L/Users/otan/go/native/x86_64-apple-darwin19.6.0/proj/lib # NOTE: THIS is omitted after using bazel
//
// #include "proj.h"
```

Where there is a `proj.cc` file with:
```
#include <proj_api.h>
```

However, changing `cppopts` to `-I/full/path/to/c-deps-/proj/src` works. 

Running with `bazel build -s`, I get something that looks correct though:

```

cd /private/var/tmp/_bazel_otan/d84c8263fef9b9141e9bd680cf5147cb/execroot/cockroach && \
  exec env - \
    CC=external/local_config_cc/cc_wrapper.sh \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:external/local_config_cc:/bin \ 
  bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src pkg/geo/geoproj/geoproj.go -src pkg/geo/geoproj/geoproj_test.go -src pkg/geo/geoproj/proj.cc -src pkg/geo/geoproj/proj.h -arc 'github.com/cockroachdb/cockroach/pkg/geo/geoprojbase=github.com/cockroachdb/cockroach/pkg/geo/geoprojbase=bazel-out/darwin-fastbuild/bin/pkg/geo/geoprojbase/geoprojbase.a=' -arc 'github.com/stretchr/testify/assert=github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/assert=bazel-out/darwin-fastbuild/bin/vendor/github.com/stretchr/testify/assert/assert.a=' -arc 'github.com/stretchr/testify/require=github.com/cockroachdb/cockroach/vendor/github.com/stretchr/testify/require=bazel-out/darwin-fastbuild/bin/vendor/github.com/stretchr/testify/require/require.a=' -arc 'github.com/cockroachdb/cockroach/pkg/geo/geographiclib=github.com/cockroachdb/cockroach/pkg/geo/geographiclib=bazel-out/darwin-fastbuild/bin/pkg/geo/geographiclib/geographiclib.a=' -arc 'github.com/cockroachdb/errors=github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/errors=bazel-out/darwin-fastbuild/bin/vendor/github.com/cockroachdb/errors/errors.a=' -importpath github.com/cockroachdb/cockroach/pkg/geo/geoproj -p github.com/cockroachdb/cockroach/pkg/geo/geoproj -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/darwin-fastbuild/bin/pkg/geo/geoproj/geoproj_test.internal.a -testfilter exclude -gcflags '' -asmflags '' -cppflags '-I pkg/geo/geoproj -iquote pkg/geo/geoproj -iquote . -isystem bazel-out/darwin-fastbuild/bin/c-deps/proj/src' -cflags '-U_FORTIFY_SOURCE -fstack-protector -Wthread-safety -Wself-assign -fno-omit-frame-pointer -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -I external/c-deps/proj/src -fPIC' -cxxflags '-U_FORTIFY_SOURCE -fstack-protector -Wthread-safety -Wself-assign -fno-omit-frame-pointer -std=c++0x -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -std=c++14 -fPIC' -objcflags '-U_FORTIFY_SOURCE -fstack-protector -Wthread-safety -Wself-assign -fno-omit-frame-pointer -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -I external/c-deps/proj/src -fPIC' -objcxxflags '-U_FORTIFY_SOURCE -fstack-protector -Wthread-safety -Wself-assign -fno-omit-frame-pointer -std=c++0x -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -std=c++14 -fPIC' -ldflags 'bazel-out/darwin-fastbuild/bin/c-deps/proj/lib/libproj.a -undefined dynamic_lookup -headerpad_max_install_names -lstdc++ -lm -lproj')
```

And the directory in `/private/var/tmp/_bazel_otan/d84c8263fef9b9141e9bd680cf5147cb/execroot/cockroach` contains `c-deps/proj/src` and `external/c-deps/proj/src`, none of which I seem to be able to link against.

Wondering what I'm doing wrong here!

Minimal repro available here: https://github.com/otan-cockroach/proj-repro (note: this will not work with go build as it does not contain a built c-deps/proj anywhere)
Full environment: https://github.com/cockroachdb/cockroach/commit/3e11d5f27c8fdb97c0746c835a240fffc4045636

### What did you expect to see?
Building successfully with the correct include file if `cdeps = ["//c-deps:proj"],` is specified, without having to do `#cgo CPPFLAGS -I/full/path/to/c-deps/proj/src`  (i.e. CPPFLAGS -I relative/path)`

### What did you see instead?
See above.

**Comment by jayconrod** [comment]
It looks like you don't have a `cdeps` dependency on the library. That's should be the first thing to fix. `cdeps` should refer to `cc_library` targets or something compatible like `cc_import`.

The `cppopts` flag `-I../../../c-deps/proj/src` probably won't work, since the action will run in a tree that looks like the repository root directory. Use `-Ic-deps/proj/src` instead or include files with paths relative to the repository root.

Likewise, the `clinkopts` flag `-lproj` won't work. That's telling the toolchain to assume the library is installed in a standard system directory, which it won't be.

Note that you'll probably want to add `# keep` comments on `cppopts` and `clinkopts` to prevent Gazelle from updating them after you make manual changes. Gazelle copies those flags to `go_library`, but many flags don't make sense with both `go build` and Bazel, since they make assumptions about what's installed on the system and where tools are invoked.

**Comment by irfansharif** [comment]
yo Oliver, I tried another repro yesterday which ended up being similar to what Jay suggested just now. https://github.com/irfansharif/test-repo; I think that does the thing we want.

**Comment by otan** [comment]
> It looks like you don't have a cdeps dependency on the library. That's should be the first thing to fix. cdeps should refer to cc_library targets or something compatible like cc_import.

Ah, it got removed but I did have `cdeps = ["//c-deps:proj"],` in there.

**Comment by otan** [comment]
> The cppopts flag -I../../../c-deps/proj/src probably won't work, since the action will run in a tree that looks like the repository root directory. Use -Ic-deps/proj/src instead or include files with paths relative to the repository root.

Tried using just `c-deps/proj/src`, as well as removing `-lproj` and still doesn't work.

Maybe I should abandon the `cmake_external` route, but it does configure certain flags that seem useful.

**Comment by otan** [comment]
Dying on the `cmake_external` route, I've fixed the includes and I see them in:
```
$ ls bazel-out/darwin-fastbuild/bin/c-deps/proj/include
geodesic.h proj_api.h projects.h
```

And the `bazel build -s` gives me:
```
... -cppflags '-iquote . -isystem bazel-out/darwin-fastbuild/bin/c-deps/proj/include' ...
```

Yet I still get the proj_api.h missing error. I've updated the [repro repo](https://github.com/otan-cockroach/proj-repro) as appropriate, if anyone's willing to dig deeper.

**Comment by otan** [comment]
Ah okay, I uninstalled `PROJ` from my local system, and now it compiles!

I guess the question now is why does `/usr/include` take precedence over `-isystem bazel-out/darwin-fastbuild/bin/c-deps/proj/include`

**Comment by otan** [comment]
Ok, looks like the problem I'm running into now is https://github.com/bazelbuild/bazel/issues/8053.
