### ISSUE TITLE
certain dependency cycles misses importing correct static libraries

### ISSUE THREAD

**Issue by otan** [bazelbuild/rules_go#2668]
### What version of rules_go are you using?
v0.23.8

### What version of gazelle are you using?
The one patched with bazelbuild/bazel-gazelle#933

### What version of Bazel are you using?
Build label: 3.5.1-homebrew

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
darwin

### Any other potentially useful information about your toolchain?
no

### What did you do?
You can reproduce this by going to https://github.com/otan-cockroach/proj-repro and typing `bazel test repro:all`

I have a cc_library equivalent dependency as as `//c-deps:proj`.

This is imported by package `//proj`:
https://github.com/otan-cockroach/proj-repro/blob/4014581ebf7c5655fd60cb830b12f5de7e00234f/proj/BUILD.bazel#L3-L27

Now I have a package `//repro:repro`, which has no package dependencies. I also have `//pkgb:pkgb` which has a dependency on `//pkg:repro` and `//pkg:proj`. However, there is a `//repro:repro_test` package, which depends on `//pkgb:pkgb` (this is a go-ism for integration tests by the looks of things, where you define `package <package>_test` so that you can "integration test" certain items to avoid circular dependencies but keeping the tests within the same package).

https://github.com/otan-cockroach/proj-repro/blob/4014581ebf7c5655fd60cb830b12f5de7e00234f/pkgb/BUILD.bazel#L3-L12

https://github.com/otan-cockroach/proj-repro/blob/4014581ebf7c5655fd60cb830b12f5de7e00234f/repro/BUILD.bazel#L3-L18

When building `bazel test repro:all`, I get the following error, implying the c-dep is not imported into the environment (which I verified by checking it is not in `bazel-out/darwin-fastbuild/bin/`):

```
external/go_sdk/pkg/tool/darwin_amd64/link: running external/local_config_cc/cc_wrapper.sh failed: exit status 1
clang: error: no such file or directory: 'bazel-out/darwin-fastbuild/bin/c-deps/proj/lib/libproj.a'
```

Removing the dependency of `//pkgb` -> `//repro` makes this work fine. Similarly, adding the `//proj` dependency on `//repro:repro_test` also makes this work

### What did you expect to see?
This to work without the workarounds named above.

### What did you see instead?
Not seeing the error indicated above.

Alternatively, gazelle would separate out the `proj_test` target into a separate one to avoid the dependency madness.

----

If you can give a pointer as to where to look to resolve this, happy to try and give it a fix.

Thanks.

**Comment by jayconrod** [comment]
Sorry, I don't think I can help with this. I'm not at all familiar with `cmake_external`, and I'd guess that's the problem.

If you can reduce this to a more minimal example (just a `cc_library` and a `go_binary`) I can take a look.

**Comment by otan** [comment]
@jayconrod 

I have a repro with just `cc_library` and `go_test` -- please see the https://github.com/otan-cockroach/proj-repro.

I've used `c-deps/proj2` as a dependency instead.

**Comment by jayconrod** [comment]
I tried that example, but I'm seeing a compile error before that:

```
ERROR: /Users/jayconrod/Code/repro/rules_go2668/proj/BUILD.bazel:3:11: GoCompilePkg proj/proj.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src proj/proj.go -src proj/proj.cc -src proj/proj.h -importpath ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture x86_64:
  "func()", referenced from:
      _proj2 in _x2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
compilepkg: error running subcommand: exit status 1
```

By the way, could you try upgrading to the latest rules_go version, either `v0.23.11` or `v0.24.3`? A similar problem was fixed on both branches. Might be the same issue.

**Comment by otan** [comment]
`v0.24.3` indeed fixes it. thanks.

**Comment by otan** [comment]
Ah I thought I tested the latest version but apparently not. Thanks again for looking, appreciate your time.

**Comment by jayconrod** [comment]
Cool, glad to hear that worked!
