### ISSUE TITLE
genrule doesn't work with go_binary with gotags

### ISSUE THREAD

**Issue by bbourbie** [bazelbuild/rules_go#2676]
### What version of rules_go are you using?

v0.24.3

### What version of gazelle are you using?

No gazelle in my example

### What version of Bazel are you using?

3.6.0

### Does this issue reproduce with the latest releases of all the above?

Yes, the latest releases reproduce the problem

### What operating system and processor architecture are you using?

Darwin

### Any other potentially useful information about your toolchain?

No, I don't think so.

### What did you do?

I reproduce the error with the following workspace

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "b725e6497741d7fc2d55fcc29a276627d10e43fa5d0bb692692890ae30d98d00",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.3/rules_go-v0.24.3.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.3/rules_go-v0.24.3.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()
```

BUILD
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "gen",
    gotags = ["generate"],
    srcs = ["gen.go"],
)

genrule(
    name = "genrule",
    outs = ["copy.txt"],
    cmd = "$(location :gen) > $@",
    tools = [":gen"],
)

```

gen.go
```
// +build generate

package main

import "fmt"

func main() {
	fmt.Println("hello world")
}

```

When I run the command bazel build //:genrule, I can see a compilation issue **not package main.**  
(the error message is not a very intuitive)

If I remove the "+build generate" from the gen.go, it's now compiling as expected.

### What did you expect to see?

 bazel build //:genrule to be built fine and gen target being built with its geotags

### What did you see instead?

 bazel build //:genrule failed because gen target built failed because it is not being built with its geotags.

if it's not possible to use genrule directly, why not creating a go_genrule?

**Comment by jayconrod** [comment]
Try using `exec_tools` instead of `tools` in the `genrule`.

[`tools`](https://docs.bazel.build/versions/master/be/general.html#genrule.tools) are built for the host configuration (the machine where Bazel runs), while [`exec_tools`](https://docs.bazel.build/versions/master/be/general.html#genrule.exec_tools) are built for the the execution configuration (the machine where most actions are run).

I don't think the host configuration allows transitions to any other configuration. `gotags` is implemented using a configuration transition, so within the host configuration, `gotags` and other attributes like `goos` and `goarch` don't work.

**Comment by bbourbie** [comment]
Oh, thank you!!! Yes, indeed,  `exec_tools`  is working well. 
Thanks, it resolves my issue. 
I am closing that ticket then

**Comment by Louai-Abdelsalam** [comment]
> Try using `exec_tools` instead of `tools` in the `genrule`.
> 
> [`tools`](https://docs.bazel.build/versions/master/be/general.html#genrule.tools) are built for the host configuration (the machine where Bazel runs), while [`exec_tools`](https://docs.bazel.build/versions/master/be/general.html#genrule.exec_tools) are built for the the execution configuration (the machine where most actions are run).
> 
> I don't think the host configuration allows transitions to any other configuration. `gotags` is implemented using a configuration transition, so within the host configuration, `gotags` and other attributes like `goos` and `goarch` don't work.

@jayconrod can you elaborate on what "configuration transition" means? I've looked it up but didn't find much to have the overall statement make sense to me.

Apologies if my comment reopens the ticket; I've never actually commented on a closed ticket before.
