### ISSUE TITLE
cgo: unsure how to link against static library

### ISSUE THREAD

**Issue by irfansharif** [bazelbuild/rules_go#2681]
### What version of rules_go are you using?

v0.23.8

### What version of gazelle are you using?

v0.22.2

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

darwin

### Any other potentially useful information about your toolchain?

Nope

### What did you do?

I'm trying to link against a C++ library, and I'm unsure how to construct the right clinkopt flags to specify where to find the .a file. I've included the minimal repro here: https://github.com/irfansharif/test-repo

What I'm specifically interested in is the following [snippet](https://github.com/irfansharif/test-repo/blob/e6d4f1c962f5852545c5141506de88fa37a5459b/BUILD.bazel#L15-L30):

```
go_library(
    name = "libmain",
    srcs = ["main.go"],
    cdeps = ["//:libroach"],
    cgo = True,
    # TODO(irfansharif): How do we avoid referring to bazel-out/darwin-fastbuild
    clinkopts = [
        "-Lbazel-out/darwin-fastbuild/bin/libroach/lib",
        "-lroach",
    ],
    cppopts = [
        "-Ibazel-out/darwin-fastbuild/bin/libroach/include",
    ],
    importpath = "github.com/irfansharif/test-repo",
    visibility = ["//visibility:private"],
)
```

Where `//:libroach` generates the following [static library](https://github.com/irfansharif/test-repo/blob/e6d4f1c962f5852545c5141506de88fa37a5459b/BUILD.bazel#L63):

```
    static_libraries = ["libroach.a"],
```

How am I to get the go library to look towards the right directory where the library is placed? I see it being placed under `bazel-out/darwin-fastbuild/bin/libroach/lib`, but I assume that's unsafe to hardcode in.

### What did you expect to see?

See above.

### What did you see instead?

See above.

**Comment by jayconrod** [comment]
You shouldn't need to use `-L` or `-l` link flags or `-I` preprocessor flags for C/C++ libraries passed in through `cdeps`. `go_library` and `go_binary` should generate those automatically with the appropriate paths. The only case where you need to write those flags explicitly is if you're depending on a system library that's not part of the Bazel workspace.

**Comment by irfansharif** [comment]
Oh, doh, thanks Jay!
