### ISSUE TITLE
nogo exclude files regex doesn't match multiple repositories

### ISSUE THREAD

**Issue by jmeekhof** [bazelbuild/rules_go#2686]
### What version of rules_go are you using?
v0.24.4
```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "ac03931e56c3b229c145f1a8b2a2ad3e8d8f1af57e43ef28a26123362a1e3c7e",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.4/rules_go-v0.24.4.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.4/rules_go-v0.24.4.tar.gz",
    ],
)
```

### What version of gazelle are you using?
v0.22.2
 ```
http_archive(
    name = "bazel_gazelle",
    sha256 = "b85f48fa105c4403326e9525ad2b2cc437babaa6e15a3fc0b1dbab0ab064bc7c",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
    ],
)
```

### What version of Bazel are you using?

3.7.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Mac

### What did you do?

I'm attempting to use the `exclude_files` directive to skip the analysis of a couple of external packages. What I'm finding is that I can only exclude one but not two paths. I want to exclude both `com_github_ugorji_go_codec` and `in_gopkg_yaml_v2`.

I'm attempting to skip nilness for both of these packages. I ran across the issue with the codec first so,
```json
{
  "nilness": {
    "exclude_files": {
      "/com_github_ugorji_go_codec/": "Lots of nilness here"
    }
  }
}
```
This allows me to skip the nilness check for codec, but now I get a nilness error for my yaml package.
```json
 {
 "nilness": {
    "exclude_files": {
      "/com_github_ugorji_go_codec/": "Lots of nilness here",
      "/in_gopkg_yaml_v2/": "Some here too"
    }
  }
}
```
### What did you expect to see?
Here I was expecting to see a successful build.

### What did you see instead?
Instead I saw the `com_github_ugorji_go_codec` error come back.

**Comment by jayconrod** [comment]
The root cause of this is golang/go#31008. The nilness check doesn't include position information with its errors, so nogo doesn't know the filename and can't apply `exclude_files`.

I don't think there's anything to be done in rules_go. If that issue is fixed, this will start working.
