### ISSUE TITLE
gazelle should support updating rules that wrap go_ rules.

### ISSUE THREAD

**Issue by DrMarcII** [bazelbuild/rules_go#269]
For an example, [go_web_test_suite](https://github.com/bazelbuild/rules_webtesting/blob/master/web/go.bzl#L20) wraps go_test, and support all args allowed by go_test (plus additional arguments). If I change a generated go_test rule to go_web_test_suite, gazelle should update that rule.

**Comment by pmbethe09** [comment]
How would this work?
If gazelle is generating a 'go_xxx(name="go_default_yyy", ...' but finds a
go_extension_xxx with the same name, it should essentially merge with that
rule?

**Comment by DrMarcII** [comment]
Maybe. Although Gazelle has some other related issues in this general area. For e.g., sometimes I want multiple go_test rules to be generated for the same package (see https://github.com/bazelbuild/rules_webtesting/blob/master/go/webtest/BUILD). And I really don't like that it generates the test with name go_default_test (this is related to my dislike to #265)

In general, I want gazelle to be smarter about accepting my edits of the BUILD file and using that to guide what it does.

**Comment by pmbethe09** [comment]
Note that in 'go test' there is no concept of splitting up your tests in
the way that you have done here -- other than the internal versus external
test (via _test package).

For now, we have chosen to make gazelle compatible with the way that 'go
build' and 'go test' operate, which is not as rich as what bazel does.

**Comment by jayconrod** [comment]
Closing old issues. Migrated to bazelbuild/bazel-gazelle#18.
