### ISSUE TITLE
go_test is building binaries stripped of debug symbols

### ISSUE THREAD

**Issue by grahamjenson** [bazelbuild/rules_go#2691]
### What version of rules_go are you using?

v0.24.4

### What version of gazelle are you using?

v0.22.2

### What version of Bazel are you using?

bazel 3.5.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS

### What did you do?

1. create a go_test
1. `bazel build <path to go test>`
1. `dlv exec <path to the build binary>`

returns this error:

```
could not launch process: decoding dwarf section info at offset 0x0: too short
```

### What did you expect to see?

If you do the exact same steps with a `go_binary` it works

1. create a go_binary
1. `bazel build <path to go binary>`
1. `dlv exec <path to the build binary>`

no error, debugging works.

### What did you see instead?

Error 

```
could not launch process: decoding dwarf section info at offset 0x0: too short
```

**Comment by grahamjenson** [comment]
It looks like https://github.com/bazelbuild/rules_go/blob/master/go/private/rules/test.bzl#L124 is true (that is go.mode.debug is false) only when building a test. I am not sure why this is.

**Comment by grahamjenson** [comment]
So I have a workaround (maybe the correct way) to build. That is to put in the `.bazelrc` file the lines

```
build --@io_bazel_rules_go//go/config:debug
run --@io_bazel_rules_go//go/config:debug
test --@io_bazel_rules_go//go/config:debug
```

Or the alternative is to add `--@io_bazel_rules_go//go/config:debug` to your builds.

This will force the test to build with debug symbols.

I think it is weird to strip the tests of the debug symbols but no the `go_binary`. Also not being able to put `debug=true` on the `go_test` rule would have been nice.

**Comment by jayconrod** [comment]
This is working as intended (#2550). It significantly reduces test link time, and it's consistent with what the `go` command does.
