### ISSUE TITLE
Usage of `google.golang.org/protobuf/types/known/fieldmaskpb` panics with duplicate registration

### ISSUE THREAD

**Issue by v3n** [bazelbuild/rules_go#2692]
### What version of rules_go are you using?

`0.24.4`

### What version of gazelle are you using?

`0.22.2`

### What version of Bazel are you using?

`3.0.0`

### What operating system and processor architecture are you using?

```
Darwin 19.6.0 Darwin Kernel Version 19.6.0; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

### Any other potentially useful information about your toolchain?

Using the Protobuf & GRPC APIv2 compilers from grpc-gateway.

### What did you do?

Imported google.golang.org/protobuf/types/known/fieldmaskpb

See attached dependency graph: ![reprograph](https://user-images.githubusercontent.com/758219/97256112-6da2ff80-17cf-11eb-9054-86cad52cf9f5.png)

### What did you expect to see?

A successful build.

### What did you see instead?

```
panic: duplicate registration of "google/protobuf/field_mask.proto"

The generated definition for this file has moved:
	from: "google.golang.org/genproto/protobuf/field_mask"
	to:   "google.golang.org/protobuf/types/known/fieldmaskpb"
A dependency on the "google.golang.org/genproto" module must
be at version cb27e3aa (May 26th, 2020) or higher.

Upgrade the dependency by running:
	go get -u google.golang.org/genproto/protobuf/field_mask
```

It would seem that the problem is here: https://github.com/bazelbuild/rules_go/blob/2bada599e10349d42e369cab1ec4f4679f148598/proto/wkt/BUILD.bazel#L124

Seems like a wrapper type is needed here?

**Comment by jayconrod** [comment]
Thanks for reporting. Reproduced with:

```
-- BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "hello",
    embed = [":hello_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "hello_lib",
    srcs = ["hello.go"],
    importpath = "example.com/hello",
    visibility = ["//visibility:private"],
    deps = [
        "@io_bazel_rules_go//proto/wkt:field_mask_go_proto",
        "@org_golang_google_protobuf//types/known/fieldmaskpb:go_default_library",
    ],
)

-- hello.go --
package main

import (
	_ "google.golang.org/genproto/protobuf/field_mask"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
)

func main() {
}
```

**Comment by v3n** [comment]
Thanks @jayconrod. Do you know of any potential workarounds for this?

**Comment by jayconrod** [comment]
I don't know of a simple workaround. I need to look at it in more detail, but it's probably what you said: more wrappers are needed.

**Comment by v3n** [comment]
Cool. I've worked around this by commenting out the code that uses fieldmasks. We're in a weird transitionary state from gogo proto to proto api v2 so it would be difficult for us to go back. I _think_ we can hold out for v0.25. 

I'll also check on the status of our organizational CLA, I'd _like_ to just investigate and PR a fix, but feet are being dragged.

**Comment by rytswd** [comment]
I've been hit by this as well - has there been any update? If introducing a wrapper for fieldmask is one potential approach, should I go ahead with a PR? Or is there some other concern around it?

**Comment by jayconrod** [comment]
I've been meaning to work on this for the next release. #2737 should fix it.
