### ISSUE TITLE
Support golangci-lint via nogo

### ISSUE THREAD

**Issue by derekperkins** [bazelbuild/rules_go#2695]
At this point, `golangci-lint` has become somewhat of a standard for static analysis, and has done a lot of work unifying code linters. Coming into Bazel, there is no support for it out of the box, but seems like it should be fairly simple to support via nogo: https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst. I've created some upstream issues about providing that integration, or potentially facilitating that integration by exposing `golangci-lint` in a way that is compatible with nogo configuration.

https://github.com/golangci/golangci-lint/issues/1473
https://github.com/atlassian/bazel-tools/issues/118
_(not trying to spam with the multiple mentions, just cross-linking for visibility)_

Is there some nuance that I'm missing that would make this a bigger technical lift? Have there been prior attempts that have failed, or is there not community interest for it?

**Comment by jayconrod** [comment]
Not sure what you're specifically asking for: do you want to run `golangci-lint` with nogo, or are you asking to integrate `golangci-lint` directly into nogo by default?

Running `golangci-lint` with nogo should be easy enough if it uses `golang.org/x/tools/go/analysis`, which it sounds like it does. It would work more or less like the vet analyzers in `golang.org/x/tools/go/analysis/passes`.

Integrating `golangci-lint` directly into nogo is not feasible for at least a couple reasons: 1) rules_go should have as few dependencies as possible, and `golangci-lint` has a LOT, and 2) I have very limited maintenance bandwidth, and I can't expand the scope of rules_go at all at this time.

**Comment by derekperkins** [comment]
Mostly I'm just looking to make it easy for people to run `golangci-lint` with Bazel. Having it directly available would obviously make it the easiest, but you've reasonably ruled that out, which is helpful when deciding where things should live. I apologize if any of my questions don't make sense, I'm just trying to get myself oriented so I can determine where to start contributing.

> JSON configuration file that configures one or more of the analyzers in deps.
`config = ":config.json"`

I think what would be the most helpful at this point is understanding how to route the `golangci-lint` config. By convention, there's a yaml at the root directory ([example](https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml)) configuring all the sublinters. Should it be as simply as marshaling that into json and pointing nogo at it? The nogo example doesn't provide much context for what the config looks like or how it might be provided to the analyzers.

> I personally use golant-ci-lint at the moment because it's more convenient to configure linters to ignore certain lines of code using a comment. I think such granularity is not available via nogo, unless I'm just not seeing it in the docs. 

This was a question from @ash2k in the atlassian repo. Do you know if that sort of metadata is available in the ast passed into the nogo analyzers, or has that been lost in the original parse?

> By default, nogo analyzers will emit diagnostics for all Go source files built by Bazel. This behavior can be changed with a JSON configuration file.

Does this mean that `golangci-lint` would only need to be set up once at the root of the workspace, or would nogo need to be configured in every `BUILD` file? If in every `BUILD` target, would there be a use case for having gazelle handle some of that?

**Comment by jayconrod** [comment]
> I think what would be the most helpful at this point is understanding how to route the golangci-lint config. By convention, there's a yaml at the root directory (example) configuring all the sublinters. Should it be as simply as marshaling that into json and pointing nogo at it? The nogo example doesn't provide much context for what the config looks like or how it might be provided to the analyzers.

I don't know enough about `golangci-lint` to answer recommend anything. It should be possible at least for analyzers to read files listed in `data` attributes.

> Do you know if that sort of metadata is available in the ast passed into the nogo analyzers, or has that been lost in the original parse?

Analyzers have access to the AST. See [`analysis.Pass`](https://pkg.go.dev/golang.org/x/tools/go/analysis#Pass).

> Does this mean that golangci-lint would only need to be set up once at the root of the workspace, or would nogo need to be configured in every BUILD file? If in every BUILD target, would there be a use case for having gazelle handle some of that?

Nogo can only be configured once, globally in the workspace. Each analyzer emits all its findings without reading nogo's configuration. The main nogo package uses the configuration to filter out findings that should be ignored. That only works with file granularity though, not on individual lines.

**Comment by jayconrod** [comment]
Closing this issue. Let me know if I missed answering any question here though.

**Comment by derekperkins** [comment]
I started working on it over the weekend and didn't get very far. I found this abandoned repo that attempted to create compability. https://github.com/anuvu/bazel-nogo-lint

If you could comment on their approach and whether or not that could be used as a starting point, that would be much appreciated.

Additionally, there is upstream interest in making golangci-lint nogo compatible. Would we need to add bazel specific files to that repo in order to make it directly usable via nogo? I'm hoping that we could make it directly importable like you have made the standard analysis tools, something like:

```
deps = ["@com_github_golangci_golang_ci_lint//go/analysis:go_tool_library"],
```

**Comment by jayconrod** [comment]
You really just need a `go_tool_library` target for each analyzer package. Users can declare their `nogo` target with a list of analyzers they want and their preferred config.

Each `go_tool_library` should be declared in a build file in each package. The build files can be checked into the repository with the packages, or they can be applied through a patch, as is the case with `org_golang_x_tools`. There's no way to generate the targets automatically right now (that's bazelbuild/bazel-gazelle#578).

**Comment by sluongng** [comment]
I think what is missing here is some sane default / documentation with examples on how to achieve some of the basic static analysis jobs that is widely available in the multi-repo environments in a monorepo(or macrorepo) setup with Bazel rules_go's `nogo`.

The Passes in the golang/x/tools is rather lacking, some are just straight up anti pattern to turn on.

In the meantime, golangci-lint is a tool which aggregate different analyzers and let user pick and choose what to turn on/off with (relatively) simple config file. The experience using golangci-lint vs nogo right now is quite far apart.

I think this topic is often touched on, but if there is concrete action points needed to be taken: perhaps we can start with an example of "how to enabling the `staticcheck` for your bazel repository using `nogo`" https://staticcheck.io/. Meaning taking an existing static analyzer in the opensource ecosystem and use it in the bazel nogo setup, step-by-step.

**Comment by sluongng** [comment]
This is an example of setting up staticcheck binary in bazel recently: https://github.com/cockroachdb/cockroach-operator/pull/122/files

CockroachDB folks had to setup with a bunch of genrules and bash scripts which is tedious and poor UX/DX in general.

**Comment by sluongng** [comment]
It seems that with a simple tweak like this

```
diff --git a/hack/bin/BUILD.bazel b/hack/bin/BUILD.bazel
index eb6ae7c..aeaa69e 100644
--- a/hack/bin/BUILD.bazel
+++ b/hack/bin/BUILD.bazel
@@ -32,6 +32,7 @@ genrule(
     }),
     outs = ["staticcheck"],
     cmd = "cp $(SRCS) $@",
+    executable = True,
     visibility = ["//visibility:public"],
 )
```

You can make the `gen_rules` target in cockroach-operator to become executable to run with `bazel run`

```
master ~/work/misc/cockroach-operator> bazel run //hack/bin:co_honnef_go_tools_staticcheck -- ./pkg/update/
INFO: Analyzed target //hack/bin:co_honnef_go_tools_staticcheck (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //hack/bin:co_honnef_go_tools_staticcheck up-to-date:
  bazel-bin/hack/bin/staticcheck
INFO: Elapsed time: 0.297s, Critical Path: 0.08s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
pkg/update/update.go:35:2: const defaultPodUpdateTimeout is unused (U1000)
pkg/update/update.go:39:2: const defaultPodMaxPollingInterval is unused (U1000)
pkg/update/update.go:251:6: func makeWaitUntilAllPodsReadyFuncInAllClusters is unused (U1000)
pkg/update/update_cockroach_version.go:41:5: var validPreserveDowngradeOptionSetting is unused (U1000)
pkg/update/update_cockroach_version.go:61:6: func updateClusterCockroachVersion is unused (U1000)
pkg/update/update_cockroach_version.go:122:6: func updateClusterStatefulSets is unused (U1000)
pkg/update/update_cockroach_version.go:154:6: func makeWaitUntilAllPodsReadyFunc is unused (U1000)
pkg/update/update_cockroach_version.go:191:6: func kindAndCheckPreserveDowngradeSetting is unused (U1000)
pkg/update/update_cockroach_version.go:246:6: func preserveDowngradeSetting is unused (U1000)
pkg/update/update_cockroach_version.go:264:6: func setDowngradeOption is unused (U1000)
pkg/update/update_cockroach_version.go:279:6: type loggerKey is unused (U1000)
pkg/update/update_cockroach_version.go:287:6: func fromContext is unused (U1000)
pkg/update/update_cockroach_version.go:296:6: type roleMembership is unused (U1000)
pkg/update/update_cockroach_version.go:307:6: func listRoleGrantsForUser is unused (U1000)
pkg/update/update_cockroach_version.go:338:6: func grantRoleToUser is unused (U1000)
pkg/update/update_cockroach_version.go:350:6: func getClusterSetting is unused (U1000)
pkg/update/update_cockroach_version.go:366:6: func setClusterSetting is unused (U1000)
pkg/update/update_cockroach_version_common.go:34:6: func makeUpdateCockroachVersionFunction is unused (U1000)
pkg/update/update_cockroach_version_common.go:53:6: func makeIsCRBPodIsRunningNewVersionFunction is unused (U1000)
pkg/update/update_cockroach_version_common.go:133:6: func isPatch is unused (U1000)
pkg/update/update_cockroach_version_common.go:137:6: func isForwardOneMajorVersion is unused (U1000)
pkg/update/update_cockroach_version_common.go:145:6: func isBackOneMajorVersion is unused (U1000)
exit 1
```

**Comment by sluongng** [comment]
@derekperkins I hope the examples above could give you a path forward

@jayconrod How about we link this into a different issue / story / epic that focus on improving `nogo` experience?

**Comment by jayconrod** [comment]
> How about we link this into a different issue / story / epic that focus on improving nogo experience?

I really, really don't have bandwidth to drive that. Feel free to submit issues and feature requests for specific problems and PRs for the same. Don't expect a redesign until rules_go has a full time maintainer.

**Comment by albertocavalcante** [comment]
Hi everyone, I know it's an old issue which has already been closed but just wondering if there are further discussions regarding this happening elsewhere nowadays. Thanks.
