### ISSUE TITLE
Update rules_cc to 

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#2711]
### What version of rules_go are you using?

2bada599e10349d42e369cab1ec4f4679f148598

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

Build label: 3.7.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux

### What would you like?

Could you update rules_go's [`go/private/repositories.bzl`](https://github.com/bazelbuild/rules_go/blob/2bada599e10349d42e369cab1ec4f4679f148598/go/private/repositories.bzl#L111-L121) to point to at least https://github.com/bazelbuild/rules_cc/commit/991eb349bf648b89f7d039a2602d337c85479534?

https://github.com/bazelbuild/rules_go/blob/2bada599e10349d42e369cab1ec4f4679f148598/go/private/repositories.bzl#L111-L121

**Comment by jayconrod** [comment]
Superseded by #2726
