### ISSUE TITLE
Setting `--compilation_mode=dbg` does not enable debug mode

### ISSUE THREAD

**Issue by arjantop-cai** [bazelbuild/rules_go#2722]
### What version of rules_go are you using?
v0.24.1

### What version of gazelle are you using?
v0.22.0

### What version of Bazel are you using?
3.6

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
MacOS Catalina 10.15.7

### Any other potentially useful information about your toolchain?

```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What did you do?

Tried to debug a test in intellij with Bazel plugin, plugin sets the flag `--compilation_mode=dbg` but debug mode is not enabled by rules_go.

### What did you expect to see?

Target to be compiled with correct `gcflags` to produce a binary that can be debugged

### What did you see instead?

Delve output: `could not launch process: decoding dwarf section info at offset 0x0: too short`. Setting `--@io_bazel_rules_go//go/config:debug` manually produces a debug binary that can be debugged.

**Comment by jayconrod** [comment]
Use `--@io_bazel_rules_go//go/config:debug` instead.

I'm not sure we can even access `--compilation_mode=dbg` from Starlark. My understanding is that flag is only used to select the C/C++ toolchain.

**Comment by arjantop-cai** [comment]
@jayconrod Reading some old issues I was under the impression this should be the case. If this is the expected behavior I will close the issue.

**Comment by uhthomas** [comment]
Fixed by https://github.com/bazelbuild/rules_go/pull/3029
