### ISSUE TITLE
Bump versions of org_golang_google_genproto and go_googleapis dependencies

### ISSUE THREAD

**Issue by ahmedtd** [bazelbuild/rules_go#2724]
### What version of rules_go are you using?
0.24.7

### What version of gazelle are you using?
0.22.2

### What version of Bazel are you using?
3.7.0

### Does this issue reproduce with the latest releases of all the above?
N/A

### What operating system and processor architecture are you using?
Linux (but N/A)

### What did you do?

Attempted to refer to CertificateAuthority.PemCaCertificates from `google.golang.org/genproto/googleapis/cloud/security/privateca/v1beta1`.

### What did you expect to see?

Compilation to succeed.

### What did you see instead?

Compilation error: `unknown field 'PemCaCertificates' in struct lit
eral of type privateca.CertificateAuthority`

This should be resolved by bumping the pinned versions of org_golang_google_genproto and go_googleapis in rules_go.  I have an updated patch ready.

**Comment by jayconrod** [comment]
All dependencies will be updated as a batch before the next minor release. In the mean time, you're always free to update these in your own WORKSPACE.
