### ISSUE TITLE
go_test fails to build if a TestMain function is present

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#273]
In the code generated by `generate_test_main.go`, the function `testing.MainStart` is called if a `TestMain` function is present. The first parameter to `MainStart` is a `testing.testDeps` interface, which is not public, so we get a build error. It doesn't seem like we can call this function anymore.

**Comment by mikedanese** [comment]
Is this break due to the go 1.8 update?

**Comment by jayconrod** [comment]
Yes. It looks like `MainStart` changed its signature upstream. According to the documentation, we shouldn't be calling it directly (not sure if this is a new comment in the documentation though):

> MainStart is meant for use by tests generated by 'go test'. It is not meant to be called directly and is not subject to the Go 1 compatibility document. It may change signature from release to release.
