### ISSUE TITLE
Avoiding conflict not successful with disable_global for grpc-gateway

### ISSUE THREAD

**Issue by rytswd** [bazelbuild/rules_go#2738]
### What version of rules_go are you using?

master, following https://github.com/bazelbuild/rules_go/pull/2737

```
git_repository(
    name = "io_bazel_rules_go",
    commit = "983d48f9d2695a0a9d898bd85dde90d410629b1b",
    remote = "https://github.com/bazelbuild/rules_go",
    shallow_since = "1605912886 -0500",
)
```

### What version of gazelle are you using?

v0.22.2

### What version of Bazel are you using?

v3.7.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS Big Sur v11.0.1, x86_64

### What did you do?

Import `github.com/grpc-ecosystem/grpc-gateway/v2/runtime` and run Gazelle with disable_proto.

I have put together the repro in a repo
- [main.go](https://github.com/rytswd/simple-bazel/blob/issue/bazelbuild/rules-go/grpc-gateway-timestamp-link-dupe/main.go)
- [WORKSPACE](https://github.com/rytswd/simple-bazel/tree/issue/bazelbuild/rules-go/grpc-gateway-timestamp-link-dupe)
- [BUILD.bazel](https://github.com/rytswd/simple-bazel/blob/issue/bazelbuild/rules-go/grpc-gateway-timestamp-link-dupe/BUILD.bazel)

Essentially, this should be it

```go
package main

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

func main() {
	//
}
```

Then tried running with `bazel run simple-bazel`

### What did you expect to see?

No error

### What did you see instead?

```
link: package conflict error: github.com/golang/protobuf/ptypes/timestamp: multiple copies of package passed to linker:
        @com_github_golang_protobuf//ptypes/timestamp:timestamp
        @io_bazel_rules_go//proto/wkt:timestamp_go_proto
Set "importmap" to different paths or use 'bazel cquery' to ensure only one
```

I have tried to follow the [Avoiding Conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) documentation, but am not certain what I'm missing here. I have taken Option 2, and have `build_file_proto_mode = "disable_global",` everywhere. It seems the fact grpc-gateway has its own BUILD.bazel file is not helping. Is there anything I could do to resolve this conflict, or something that could be done for grpc-gateway repo to ensure this works for Bazel user?

The cquery on both show the following:

```
$ bazel cquery "somepath(//..., @io_bazel_rules_go//proto/wkt:timestamp_go_proto)"
//timesvc:go_default_library (63cc040)
@com_github_grpc_ecosystem_grpc_gateway_v2//runtime:go_default_library (63cc040)
@io_bazel_rules_go//proto/wkt:timestamp_go_proto (63cc040)

$ bazel cquery "somepath(//..., @com_github_golang_protobuf//ptypes/timestamp:timestamp)"
//timesvc:go_default_library (63cc040)
@org_golang_google_grpc//:go_default_library (63cc040)
@org_golang_google_grpc//:grpc (63cc040)
@org_golang_google_grpc//internal/binarylog:binarylog (63cc040)
@com_github_golang_protobuf//ptypes:ptypes (63cc040)
@com_github_golang_protobuf//ptypes/timestamp:timestamp (63cc040)
```

**Comment by jayconrod** [comment]
`github.com/grpc-ecosystem/grpc-gateway/v2` has its own build files, and as you found with `bazel cquery`, `@com_github_grpc_ecosystem_grpc_gateway_v2//runtime:go_default_library` depends on a `go_proto_library` that's generated at build time. Because of that, I don't believe grpc-gateway can be used with `build_file_proto_mode = "disable_global"`.

Can you use `go_proto_library` throughout your project (Option 1)?

If not, do the folks maintaining grpc-gateway have any advice for this situation?

**Comment by achew22** [comment]
I depend on it from a `http_archive` of the release and don't involve Gazelle at all.

**Comment by jayconrod** [comment]
@achew22 I don't think this is a Gazelle issue. Since grpc-gateway has build files already, `go_repository` would just fetch it without running Gazelle. That should be essentially the same as `http_archive`.

**Comment by jayconrod** [comment]
@rytswd 

> I believe my setup with the disable_global flag is commonly used. This link error seems to be the only blocker from using grpc-gateway, and I'd love to get this sorted out. If there is anything I could do to help, please let me know. (If this discussion should be moved to grpc-gateway repo, I'm more than happy to do so as well.)

I don't think anything can be done in rules_go. In general, you can't link the same package compiled two different ways. grpc-gateway depends on proto packages built with `go_proto_library`, so you can't link the same packages built with `go_library`.

I don't know grpc-gateway that well, so it's likely the maintainers of that project can give you better advice.

**Comment by rytswd** [comment]
@jayconrod 
Thanks for the input. I have not seen any other issues with the disable_global and overriding dependencies, and understand there isn't much rules_go can do. I have created an issue over on grpc-gateway repo to get more insights from their side.

**Comment by rytswd** [comment]
I'm closing this ticket in favour of the above grpc-gateway ticket.
