### ISSUE TITLE
Request code review for external ruleset influenced by rules_go and @jayconrod

### ISSUE THREAD

**Issue by dmayle** [bazelbuild/rules_go#2754]
Hi, I know this is probably an unusual place to file this issue, but I am open sourcing a set of rules for sqlc, the SQL to Go compiler that is heavily influenced by this repository, simple_rules_go, and the series of blog posts by @jayconrod .

The initial import can be found at https://github.com/plezentek/bazel-sqlc/pull/1

The initial import is quite large, but if you exclude the tests, it's a much more reasonable size.

I would be very grateful if you could take the time to review the code so that the quality of rules I am open sourcing is high, and so that future rules I make available benefit from any learnings there.

**Comment by jayconrod** [comment]
Sorry, I don't have bandwidth to review a large amount of code right now. Maybe check on the [bazel-discuss](https://groups.google.com/g/bazel-discuss) mailing list or on [Bazel Slack](https://slack.bazel.build/) and see if anyone's interested?

**Comment by dmayle** [comment]
I didn't end up getting any takers, so I've published the code anyway, and am working on making fixes from there.
