### ISSUE TITLE
go_library: support syso files in srcs

### ISSUE THREAD

**Issue by connyay** [bazelbuild/rules_go#2757]
### What version of rules_go are you using?

v0.24.9 

### What version of gazelle are you using?

v0.22.2

### What version of Bazel are you using?

3.7.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

darwin x86_64

### What did you do?

Attempted to include a resource.syso file with `go_binary` 

### What did you expect to see?

A successful build that includes windows version info. 

### What did you see instead?

A build failure.

```console
ERROR: rules_go_syso_demo/cmd/main/BUILD:10:10: in srcs attribute of go_transition_binary rule //cmd/main:windows: '//cmd/main:resource-syso' does not produce any go_transition_binary srcs files (expected .go, .s, .S, .h, .c, .cc, .cpp, .cxx, .h, .hh, .hpp, .hxx, .inc, .m or .mm). Since this rule was created by the macro 'go_binary_macro', the error might have been caused by the macro implementation
ERROR: Analysis of target '//cmd/main:windows' failed; build aborted: Analysis of target '//cmd/main:windows' failed
INFO: Elapsed time: 0.698s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

I put together a simple repro to demo and develop a fix against: https://github.com/connyay/rules_go_syso_demo

**Comment by connyay** [comment]
I _think_ a fix for this is a fairly small changeset https://github.com/bazelbuild/rules_go/compare/master...connyay:fixup-syso-files 

but not sure the ramifications of that change. Went with the `syso_exts` and `split.syso` to keep it fairly isolated.

Need to get approval for the CLA before I can open a PR with that - if someone beats me to this changeset please go right ahead.

**Comment by jayconrod** [comment]
Marking as an enhancement. I expect this won't be simple though. There are a lot of corner cases around linking an cross-compilation. If you're able to use `cc_library` or something compatible to build the objects to include, I'd strongly recommend that instead.
