### ISSUE TITLE
MacOS can not use the version v0.25.1 and v 0.24.0, but can use v0.24.10

### ISSUE THREAD

**Issue by nengc** [bazelbuild/rules_go#2773]
### What version of rules_go are you using?

0.24.0 or 0.25.1

### What version of gazelle are you using?

3.7.2

### What operating system and processor architecture are you using?

MacOS

### What did you see instead?

Error in download_and_extract: java.io.IOException: Error extracting /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/go_sdk/temp2048821358593620952/go1.15.5.linux-amd64.tar.gz to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/go_sdk/temp2048821358593620952: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/go_sdk/test/fixedbugs/issue27836.dir/Äfoo.go (Input/output error), rootCauses=[REPOSITORY_DIRECTORY:@go_sdk], cycles=[], isCatastrophic=false, rootCauseOfException=REPOSITORY_DIRECTORY:@go_sdk, isDirectlyTransient=false, isTransitivelyTransient=true}, ([ConfiguredTargetKey{label=//source/exe:envoy-static, config=BuildConfigurationValue.Key[a4fcd37d7280c347243684e7ac84340120209008ff4bc80de67fa625d855ab3b]}])

**Comment by jayconrod** [comment]
Can you provide any more information on your environment or how to reproduce this? I test all the releases on macOS, so I know it works for most people at least.

**Comment by jvolkman** [comment]
This is the same issue as #2771.

**Comment by jayconrod** [comment]
Closing as a duplicate then.
