### ISSUE TITLE
Invalid go:embed when building with Bazel

### ISSUE THREAD

**Issue by mkilpatrick** [bazelbuild/rules_go#2774]
### What version of rules_go are you using?
0.25.1

### What version of gazelle are you using?
0.22.3

### What version of Bazel are you using?
1.16beta1

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
OSX 10.15.7

### What did you do?
Used Go's new go:embed functionality
```
//go:embed public
var content embed.FS
```

### What did you expect to see?
Successful compilation

### What did you see instead?

> routes.go:16:7: invalid go:embed: build system did not supply embed configuration
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_amd64/compile: exit status 2

The go_library in the Bazel BUILD file has data defined like
```
go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
        "routes.go",
    ],
    data = glob([
        "public/**",
    ])],
    importpath = "...",
    deps = [
        ....    
    ],
)
```

Is something else necessary to make the embed files available through Bazel? I didn't see any new documentation after much searching.

**Comment by jayconrod** [comment]
`//go:embed` isn't supported yet. I've opened a new issue (#2775) that briefly describes what needs to be done. I'll close this one.
