### ISSUE TITLE
v0.24.10 hash mismatch?

### ISSUE THREAD

**Issue by connyay** [bazelbuild/rules_go#2779]
Hello,

Seeing some weird hash mismatches between `mirror.bazel.build` and `github.com/bazelbuild/rules_go` for [release v0.24.10](https://github.com/bazelbuild/rules_go/releases/tag/v0.24.10).

```
curl -sL https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.10/rules_go-v0.24.10.tar.gz | shasum -a 256 -
8e9434015ff8f3d6962cb8f016230ea7acc1ac402b760a8d66ff54dc11673ca6  -
curl -sL https://github.com/bazelbuild/rules_go/releases/download/v0.24.10/rules_go-v0.24.10.tar.gz | shasum -a 256 -
a515569b4903776eae90ac2696b34ee1dd45600cf9dfd7d16475e2df32867521  -
```

Did something weird happen with this release?

**Comment by jayconrod** [comment]
Thanks for identifying this. It should be fixed now.

`8e9434015ff8f3d6962cb8f016230ea7acc1ac402b760a8d66ff54dc11673ca6` is the correct SHA-256 sum. This is the one from `mirror.bazel.build`.

The file attached to the GitHub release was from an earlier iteration when the release was being prepared. There were a couple CI and test fixes I think.
