### ISSUE TITLE
Target specific test filter

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2784]
Bazel passes `--test_filter` to test frameworks as `TESTBRIDGE_TEST_ONLY`. In rules_go, it is passed down to `test.run`:

https://github.com/bazelbuild/rules_go/blob/642ff3d80c3454e8d9758c54ce6841cc089507be/go/tools/builders/generate_test_main.go#L143-L145

This is problematic when we run several targets at the same time while skipping some test cases in some targets. For example, if we want to run only `TestCase1` and `TestCase2` in `//package1:test` and all test cases in `//package2:test`:

```
bazel test --test_filter "^(TestCase1|TestCase2)$" //package1:test //package2:test
```

The such test filter would apply to all test targets, ending up running no test in `//package2:test` because there is no match.

Can we implement some scoping for the test filter regex? For example, `--test_filter="package1:^(TestCase1|TestCase2)$,package2:^TestCase3$"`. For backward compatibility, we can still support unscoped regex that applies to all test targets.

**Comment by jayconrod** [comment]
I'd prefer not to support this: I think the simple mapping to `-test.run` is valuable.

Could you say more about the use case? Is there another way it can be accomplished, like with multiple `bazel test` commands or with a build constraint or test argument?

Most of the time I've used `--test_filter` and `-test.run`, I've just wanted to fix a specific test case or group of test cases in one package. It's difficult to match all tests *except* a group of tests with a regular expression, so `-test.run` isn't useful for much more than that. There are other tools for dealing with tests of a specific size or flaky tests.

**Comment by linzhp** [comment]
It's for our CI system to dynamically decide to run or skip some unhealthy test cases scattered in many test targets. Combining with what I propose in #2785, the CI system can run all tests in one `bazel test` command while skipping some unhealthy test cases.

Multiple `bazel test` commands approach can be a workaround, but that would slow down the CI job significantly, because we have to run test targets one at a time whenever there is an unhealthy test case in it, under-utilizing the computing resources.

We have jobs running periodically to verify if the unhealthy test cases are still unhealthy, and we want to run all tests of a package (healthy or not) if the package is just changed. So we can't change the source code back and forth by adding and deleting `t.Skip` or build constraints.

What other tools available to deal with flaky tests? Can they work at test case level not just target level?

**Comment by jayconrod** [comment]
> It's for our CI system to dynamically decide to run or skip some unhealthy test cases scattered in many test targets. Combining with what I propose in #2785, the CI system can run all tests in one bazel test command while skipping some unhealthy test cases.

This seems like a really narrow case to me. I think it would be better to find another way to solve this problem outside rules_go. I think the simplicity of having `--test_filter` map to `-test.run` is valuable.

> Multiple bazel test commands approach can be a workaround, but that would slow down the CI job significantly, because we have to run test targets one at a time whenever there is an unhealthy test case in it, under-utilizing the computing resources.

Another workaround: check the XML output and ignore or special-case failures in matching tests. The top-level `bazel test` command might fail, but CI might decide that's fine based on the output.

> What other tools available to deal with flaky tests? Can they work at test case level not just target level?

I suppose there are tools that work at one level or the other, but not both. The [`flaky`](https://docs.bazel.build/versions/master/be/common-definitions.html#test.flaky) attribute was mostly what I was thinking of.

**Comment by linzhp** [comment]
We had an internal debate about whether we should skip or run and ignore unhealthy test cases. The main concern on the run and ignore approach is that we waste resources running unhealthy tests whose results are going to be ignored.

`flaky` attribute works at target level, not at test case level.

**Comment by linzhp** [comment]
No longer needed. We can set `TESTBRIDGE_TEST_ONLY` on each test target.
