### ISSUE TITLE
go_test: skipping tests with --test_filter

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2785]
We have a system that monitors the health (e.g., slow, flaky) of tests so we can dynamically skip unhealthy test cases in some environments. Using `t.Skip` is not very flexible, as it involves frequently adding and removing code snippets to a very large number of test cases. 

Can we support a minus (`-`) sign before the regex in `--test_filter` to indicate the pattern we want to skip? For example, `--test_filter=-^TestCase1$` means run all test cases except `TestCase1`.

Currently `--test_filter` is passed to `test.run`, which doesn't support the minus sign. Maybe we can filter the `allTests` slice before this line?

https://github.com/bazelbuild/rules_go/blob/642ff3d80c3454e8d9758c54ce6841cc089507be/go/tools/builders/generate_test_main.go#L141

**Comment by jayconrod** [comment]
This seems like it would be good to have. It deviates from `-test.run`, but it lines up nicely with the proposed `-skip` flag in golang/go#41583, and using a `-` prefix is similar to what Bazel's `--instrumentation_filter` uses.

**Comment by sluongng** [comment]
Having something like @linzhp proposed, i.e. filtering `allTests` slice, would be nice to have right now.

It could take a while for upstream golang to implement the `-skip` proposal.

@jayconrod are you keen on accepting a PR for a negate test filter right now? Or are you leaning toward waiting for golang proposal to land first?

**Comment by jayconrod** [comment]
Since the proposal has been accepted, I don't think there's any problem with implementing it here.

That said, it would be really nice to just translate `--instrumentation_filter` into a combination of `-test.run` and `-test.skip` instead of implementing test skipping both here and in `testing`. So it would be better to implement it upstream first.
