### ISSUE TITLE
Support Go 1.15.8 and 1.14.15

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2809]

**Comment by achew22** [comment]
Out of curiosity, is this just for older versions of `rules_go` that don't parse the releases JSON from golang.org, or is there stuff that needs to be done on the main branch?

**Comment by jayconrod** [comment]
Just for older versions, specifically the `release-0.24` branch. When the releases are ready later today, I'll send a PR that lands directly on that branch.

`master` and `release-0.25` should be able to use the new versions as soon as they're online.

**Comment by jayconrod** [comment]
Fixed by #2810
