### ISSUE TITLE
Providing support for gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [bazelbuild/rules_go#2817]
Hi.

I wanted to create a PR, for supporting https://go.googlesource.com/gollvm/. Assuming Aarch64, x86_64 builds.

**Comment by advancedwebdeveloper** [comment]
CC @thanm @cherrymui @ianlancetaylor

**Comment by advancedwebdeveloper** [comment]
Consider using Bazel as an alternative to Ninja + CMake or Make + CMake

**Comment by advancedwebdeveloper** [comment]
> Consider using Bazel as an alternative to Ninja + CMake or Make + CMake - but in case if someone is building gollvm project itself (llvm-goc compiler).

I see that there is an initiative https://github.com/google/llvm-bazel - so CC @GMNGeoffrey , @chandlerc

**Comment by advancedwebdeveloper** [comment]
https://groups.google.com/g/bazel-go-discuss/c/2AbM47CsWVk

**Comment by jayconrod** [comment]
cc @bazelbuild/go-maintainers 

At the moment, rules_go only directly supports the standard Go toolchain, `cmd/compile` and `cmd/link`. gccgo and gollvm aren't supported at this time.

It's possible to add support by declaring a `go_toolchain` that implements the toolchain API and ensuring that toolchain is selected by Bazel. [Go toolchains](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst) has a bit more information on this.

The main issue is that the builder (in go/tools/builder) is fairly tightly coupled with the Go toolchain. Features like nogo, coverage instrumentation, the upcoming `//go:embed` directive, and editor / IDE integration would need to work quite differently.

It's possible that may increase the scope and maintenance cost of rules_go significantly, on the order of 10-20%. That's fine if there's interest from other folks in building and maintaining this; personally I can't commit to that though.

**Comment by jayconrod** [comment]
@advancedwebdeveloper Could you say a bit more about your use case? (To satisfy my own curiosity more than anything).

I think you mentioned on Slack you were looking for a way to build static or shared libraries. Would `linkmode = "c-archive"` be an option for you? That would use the Go toolchain to build a library that could be linked into a C/C++ binary.

**Comment by advancedwebdeveloper** [comment]
CC @thanm

**Comment by thanm** [comment]
@advancedwebdeveloper  you've cc'd me a couple of times now on this issue... do you have a specific question for me?

As @jayconrod points out, `rules_go` is  specific to the main Go compiler + toolchain; adding gollvm/gccgo support would require fairly major surgery.

In addition, from reading your earlier posts (ex: "Consider using Bazel as an alternative to Ninja + CMake or Make + CMake") you are looking for a build system to build the gollvm compiler itself -- not to build Go applications with gollvm.  This is not really what `bazelbuild/rules_go` is about. `rules_go` is about building regular Go applications, not bootstrapping Go compilers. For example, you can't use `rules_go` to bootstrap the main Go compiler -- you have to use "make.bash" (and "go dist") for that.
