### ISSUE TITLE
Support Go 1.16

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2820]
This issue is for supporting Go 1.16 itself. Support should only be needed on the release-0.24 branch. The release-0.25 branch should be able to use 1.16 automatically (though I'll verify that before closing this issue).

Support for the `//go:embed` directive is #2775. We'll likely do a minor release soon when that's fixed (along with a few other changes).

**Comment by robfig** [comment]
@jayconrod good to close this?

**Comment by jayconrod** [comment]
Yep, embed is working now.
