### ISSUE TITLE
How to add the ldflags " -X main.BuildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'`" ?

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#284]
How to implement the same function as 

> go build -ldflags " -X main.BuildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.Version=`git rev-parse HEAD`"   ?

I add both the two arguments to the 'ldflags' in def.bzl, but it doesn't work.

**Comment by jayconrod** [comment]
You can do this with the new link stamping functionality. See the documentation for the `linkstamp` attribute for [`go_binary`](https://github.com/bazelbuild/rules_go#go_binary). Also see the example in [examples/stamped_bin](https://github.com/bazelbuild/rules_go/tree/master/examples/stamped_bin).

Basically, you will need to create a script that prints information you want to put in the link stamp. Let's call it status.sh. It will look something like this (not tested):

```bash
#!/bin/bash

echo BuildTime $(date -u '+%Y-%m-%d_%I:%M:%S%p')
echo Version $(git rev-parse HEAD)
```

Add the `linkstamp` attribute to the `go_binary` rule in your BUILD file. You'll specify the package where these values should be set.

```skylark
go_binary(
    ...
    linkstamp = "main",
)
```

Run Bazel with your status script (the "./" is important):

```
$ bazel build --workspace_status_command=./status.sh :my_binary
```

Bazel will turn the output of the status script into -X flags passed to the linker.

I plan to add support for custom link options in the future (see [#217](https://github.com/bazelbuild/rules_go/issues/217)), but that will only support static options in BUILD files.

**Comment by skyl** [comment]
`no such attribute 'linkstamp' in 'go_binary' rule`

**Comment by jayconrod** [comment]
For anyone trying to do this now, the current instructions are at https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#defines-and-stamping. The `linkstamp` attribute was deprecated and removed some time ago.
