### ISSUE TITLE
SDK versions not properly refreshed when using remote cache

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_go#2841]
### What version of rules_go are you using?

v0.26.0

### What version of gazelle are you using?

v0.23.0

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yep.

### What operating system and processor architecture are you using?

Linux/amd64

### Any other potentially useful information about your toolchain?

Using remote cache and remote fetcher (BuildBarn).

### What did you do?

Change the Go version from 1.16 to 1.16.1

### What did you expect to see?

A successful build.

### What did you see instead?

```
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/io_bazel_rules_go/go/private/sdk.bzl", line 94, column 17, in _go_download_sdk_impl
		fail("did not find version {} in https://golang.org/dl/?mode=json".format(version))
Error in fail: did not find version 1.16.1 in https://golang.org/dl/?mode=json
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/io_bazel_rules_go/go/private/sdk.bzl", line 94, column 17, in _go_download_sdk_impl
		fail("did not find version {} in https://golang.org/dl/?mode=json".format(version))
Error in fail: did not find version 1.16.1 in https://golang.org/dl/?mode=json
```

Builds ok if remote cache is disabled.

**Comment by uhthomas** [comment]
`bazel clean --expunge` does not help.

**Comment by jayconrod** [comment]
Sorry, I'm not sure I can help with this. I don't have a BuildBarn setup and can't easily test or debug this.

It sounds like an old version of `https://golang.org/dl/?mode=json&include=all` is being cached. When `go_download_sdk` is evaluated, it fetches the list of Go downloads from that URL. The `sha256` argument is not passed to `repository_ctx.download`, so that file should not be cached at all.

As far as I know, that should not be affected by whether remote caching is enabled. Bazel evaluates repository rules on the host system, and all the files are created there.

You mentioned a remote fetcher. What is that exactly?

**Comment by uhthomas** [comment]
That's what I'm seeing too.

The correct sha256 (right now) is `ddb161cd359db9663c69ba7008223dc7589e33ed667611970496a665debb161e`, but am seeing `a6e405e31ea50626c4b0bcf821ba56fd4d7b90c0de5ec32a7c6323c73d7ba48d`.

Bazel relatively recently introduced the [remote asset protocol](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto). Usable through [--experimental_remote_downloader](https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_remote_downloader).

The cache seems to be fine, you're right, but using the remote downloader is what is causing the issue. I imagine it's probably something with our deployment, or weirdness with the remote asset server. I don't think there's anything you can do, so I'll close for now.

Thanks again for all the help 😄

**Comment by uhthomas** [comment]
It's probably worth mentioning that [go_download_sdk](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_download_sdk) should be a workaround.

It's not as "clean" though.
