### ISSUE TITLE
Cross compiled Go, fully rebuilds when unrelated skylib flags change 

### ISSUE THREAD

**Issue by mishas** [bazelbuild/rules_go#2846]
### What version of rules_go are you using?

Tried with v0.26.0, v0.25.1 and v0.24.13

### What version of gazelle are you using?

v0.22.3, but I don't think it's relevant.

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

MacOS 11.1, AMD64

### Any other potentially useful information about your toolchain?

Manually importing Skylib.
Tried with the newest (v1.0.3) and with v0.9.0

Using protobuf for the example, but the problem happens even if there's no proto at all.

### What did you do?

When adding a flag (e.g. `string_flag` rule) from skylib, and passing that flag to a build for a Go binary that has `goos` and `goarch` set for it (even if not cross-compiling) - everything fully rebuilds (including host-run tools, like protoc).
This happens even if that flag is not used anywhere (see example below).

This happens without protoc as well, but I'm using it in the example, as something that should not even be cross-compiled that recompiles.

main BUILD file:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

# Example copied from https://docs.bazel.build/versions/master/skylark/config.html#predefined-settings
# Please note that this rule is not used anywhere.
string_flag(
    name = "myflag",
    build_setting_default = "a",
    values = ["a", "b", "c"],
)

go_library(
    ...  # removing for simplicity. Generated with Gazelle
    deps = ["//pb"],  # depending on some protobuf. The BUILD file in //pb:BUILD is gazelle generated.
)

go_binary(
    ...  # removing for simplicity. Generated with Gazelle
    goarch = "amd64",
    goos = "linux",  # The problem happens even if I set this to "darwin", which should NOT cross-compile.
)
```

First run:
`bazel build //pkg/demo --//pkg/demo:myflag=a`
then run
`bazel build //pkg/demo --//pkg/demo:myflag=b`

### What did you expect to see?

I'd expect the second build to be very fast - in fact, I'd expect no build happening at all (only analysis)

### What did you see instead?

Everything is rebuilt. Including the CC code of the `protoc` compiler.

### Interesting fact

The same doesn't happen, if I use `--define myflag=<whatever>` - in the case of the (deprecated) `--define` flag, only analysis runs twice, not the build.

**Comment by jayconrod** [comment]
This sounds like a Bazel bug, especially since protoc is rebuilt. Have you asked in bazel-discuss or opened an issue in bazelbuild/bazel?

rules_go does use a transition for some things, but it explicitly declares a list of input and output build settings (as all transitions must). I wouldn't expect a setting outside of that set to invalidate analysis results, let alone build outputs.

**Comment by mishas** [comment]
I didn't ask in bazel-discuss nor did I open an issue in bazelbuild/bazel, because I thought it might be somehow related to the cross-compile toolchain defined by rules_go.

My thinking here was that `--define` is implemented in Bazel itself, and it works, while the skylib flags which are implemented outside of the core Bazel code, don't work.

I ruled out a bug in skylib, because the problem did not persist when I tried the same with C++, so - I assumed it has to be in rules_go.

@jayconrod, please let me know what you think about the above, and if you still think it's more likely a problem in Bazel itself, I'll open a ticket there.

Thanks for looking into it!

**Comment by jayconrod** [comment]
The Skylib definitions are pretty small. They're mostly there so every project doesn't need to define their own `string_flag`. All of the logic to implement those flags and configuration transitions is in Bazel, so I think it would be worth asking there.

**Comment by robfig** [comment]
Looks like this is fixed in bazel^. Please reopen if there's still a problem.
