### ISSUE TITLE
rules_go-v0.24.12 doesn't compile com_google_cloud_go_logging/apiv2

### ISSUE THREAD

**Issue by JessieQX** [bazelbuild/rules_go#2856]
### What version of rules_go are you using?
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "4d838e2d70b955ef9dd0d0648f673141df1bc1d7ecf5c2d621dcc163f47dd38a",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.12/rules_go-v0.24.12.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.12/rules_go-v0.24.12.tar.gz",
    ],
)

### What version of gazelle are you using?
http_archive(
    name = "bazel_gazelle",
    sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
    ],
)

### What version of Bazel are you using?
Bazelisk version: development
Build label: 3.4.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
maxOS Darwin 10.15.7

### What did you do?
I imported `cloud.google.com/go/logging v1.3.0` in go.mod, and make bazel update and build

### What did you expect to see?
Bazel build successfully

### What did you see instead?
/private/var/tmp/_bazel_xxx/2da79b9c9a959af4631105b8f2bd980f/external/com_google_cloud_go_logging/apiv2/BUILD.bazel:3:11: GoCompilePkg external/com_google_cloud_go_logging/apiv2/go_default_library.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_google_cloud_go_logging/apiv2/config_client.go -src ... (remaining 45 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_cloud_go_logging/apiv2/config_client.go:328:63: undefined: logging.CreateBucketRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:374:63: undefined: logging.DeleteBucketRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:388:65: undefined: logging.UndeleteBucketRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:401:60: undefined: logging.ListViewsRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:442:58: undefined: logging.GetViewRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:442:110: undefined: logging.LogView
external/com_google_cloud_go_logging/apiv2/config_client.go:460:61: undefined: logging.CreateViewRequest
external/com_google_cloud_go_logging/apiv2/config_client.go:460:116: undefined: logging.LogView
external/com_google_cloud_go_logging/apiv2/config_client.go:966:14: undefined: logging.LogView
external/com_google_cloud_go_logging/apiv2/config_client.go:981:65: undefined: logging.LogView
external/com_google_cloud_go_logging/apiv2/config_client.go:460:116: too many errors
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_amd64/compile: exit status 2

**Comment by jayconrod** [comment]
It looks like this is an issue with mismatched dependency versions.

The missing symbols are defined in `google.golang.org/genproto`, which contains some common, generated proto packages. There's a special repository for that, `go_googleapis`, that Gazelle will resolve imports to by default. So that may be out of date. Try updating to a new version of rules_go. `v0.24.12` is not the latest version. The 0.24 branch is quite old and will not receive more updates.

The repository contains `go_proto_library` targets that generate code at build time. If you don't want to use that, and you'd prefer to use your own `org_golang_google_genproto` delcaration, then you'll need to disable proto rule generation. [Avoiding conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) has more information.

If none of that works, please post a minimal repo that reproduces the issue.

**Comment by 110y** [comment]
@jayconrod 

I might be facing the same problem. I've added `# gazelle:proto disable_global` to BUILD file and  `build_file_proto_mode=disable_global` option to each `go_repository`, but it doesn't work for me.
My minimal repo is here: https://github.com/110y/bazel-go-genproto-issue/
When I execute `bazel build //:bazel-go-genproto-issue` on the repo, it causes:

```
external/com_google_cloud_go_spanner/client.go:491:11: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/client.go:516:24: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:82:20: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:91:17: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:94:49: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:126:11: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:129:42: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:259:11: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:262:43: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions_Priority
external/com_google_cloud_go_spanner/transaction.go:285:64: undefined: "google.golang.org/genproto/googleapis/spanner/v1".RequestOptions
external/com_google_cloud_go_spanner/transaction.go:285:64: too many errors
```

**Comment by robfig** [comment]
Here is a non-reproducer with a working com_google_cloud_go_logging. Please have a look at provide your own reproducer if you can't get it to work. Thanks
https://github.com/robfig/rules_go_cloud_logging
