### ISSUE TITLE
strange "undefined" error on supposedly exported function/type: <file>.go: undefined: wasmer.Instance

### ISSUE THREAD

**Issue by joehattori** [bazelbuild/rules_go#2861]
### What version of rules_go are you using?
v0.25.1

### What version of gazelle are you using?
v0.22.3

### What version of Bazel are you using?
4.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
ubuntu x64 (Virtual Box)

### What did you do?
I am trying to integrate [wasmer-go](https://github.com/wasmerio/wasmer-go) to my project with bazel.
Seemingly wasmer-go currently do not support bazel, so I forked it to [here](https://github.com/joehattori/wasmer-go) but I get this strange error on `bazel build <target>`;
```
Use --sandbox_debug to see verbose messages from the sandbox
<file>.go: undefined: wasmer.Instance
<file>.go: undefined: wasmer.NewEngine
<file>.go: undefined: wasmer.NewStore
```
I have added the following lines to my project's `WORKSPACE` file;
```
go_repository(
    name = "com_github_joehattori_wasmer_go",
    importpath = "github.com/joehattori/wasmer-go",
    commit = "1434f844b230aa26ca43e278a78deba48f520229",
)
```

I get the same error even when I treat wasmer-go as a non-Bazel repository (like [this commit of the fork](https://github.com/joehattori/wasmer-go/tree/748d49627985e5943cbac7524670db9135ad3862). I deleted `WORKSPACE` and `BUILD` file).

### What did you expect to see?
I expected my project to build successfully with `bazel build <target>`

### What did you see instead?
The error above.

### Reference
For more details, I posted a relevant issue to wasmer-go (https://github.com/wasmerio/wasmer-go/issues/259) but I have yet to solve this error.

**Comment by robfig** [comment]
In my experience, all but the simplest cgo-using projects require you to customize the BUILD files, at a minimum. `go_repository` runs Gazelle on the repository and it's likely that the resulting BUILD file does not correctly capture the C build.

To get this to work, I would recommend cloning wasmer, running Gazelle yourself, and pointing your repo to it using `local_repository`. This way you can easily iterate on the wasmer BUILD files and test that it works by running its tests using bazel and building your app that depends on it. 

Once you have a minimal patch that works, you can either fork wasmer and continue using your fork with the changes, or you can capture your changes as .patch files in your repository and apply them using the `patches` argument to `go_repository`. 

It looks like you've started on this path already. If you have a fork of wasmer that you can't get to build with Bazel, please share what you've tried and I will give it a shot. 

You can see an example where I did this for imagemagick here:
https://engblog.yext.com/post/bazel-cgo-imagemagick

And for v8go here:
https://github.com/robfig/v8go/commit/7f55e791720b8c443675ee9a28354891ed382f9d

**Comment by robfig** [comment]
Actually -- my guess, based on the error message, is that the immediate problem with your build is that CGO_ENABLED=0. That is the main thing that would cause a build to fail with "X is not defined" where X is defined in a cgo-using file.

**Comment by joehattori** [comment]
@robfig Thank you for the detailed reply!
I forked and tested on local with `local_repository` and checked whether `bazel build <target>` passes, but it kept failing.
Here's what I've done so far;
- delete `WORKSPACE` and `BUILD` file of wasmer-go to treat it as a non-bazel repository: [this commit](https://github.com/joehattori/wasmer-go/tree/748d49627985e5943cbac7524670db9135ad3862)
- run gazelle and generate missing `BUILD` files: [this commit](https://github.com/joehattori/wasmer-go/tree/1434f844b230aa26ca43e278a78deba48f520229)
- write BUILD files manually: [this commit](https://github.com/joehattori/wasmer-go/tree/f798e61cafe67f43dac11d22d88dd42ddc7c086e)

All of them leads to the same error which I mentioned above.
My project builds a standard go_binary, and I tried `export CGO_ENABLED=1` but the outcome was the same.
Would you tell me what my mistakes are?
Please tell me if I missed any information.

**Comment by robfig** [comment]
I cloned your repository and was not able to build:
```
$ bazel build //wasmer
...
wasmer/cgo.go:12:11: fatal error: 'wasmer_wasm.h' file not found
 #include <wasmer_wasm.h>
          ^~~~~~~~~~~~~~~
```

It looks like the include file path is incorrect in your packaged/include/BUILD file. To simplify, I moved the cc_library to the top level and deleted those two build files under packaged:
```
# wasmer/BUILD

cc_library(
    name = "lib",
    srcs = select({
        "@io_bazel_rules_go//go/platform:darwin": ["packaged/lib/darwin-amd64/libwasmer.dylib"],
        "@io_bazel_rules_go//go/platform:linux": ["packaged/lib/linux-amd64/libwasmer.so"],
        "//conditions:default": ["UNSUPPORTED_PLATFORM"],
    }),
    visibility = ["//visibility:public"],
    hdrs = glob(["packaged/include/**/*"]),
    strip_include_prefix = "packaged/include",
)
```

Now `bazel build //wasmer` succeeds, but tests failed, even after I changed the paths in `clinkopts` (-rpath, -L) to be relative to current directory:

```
$ bazel test --test_output=errors //wasmer:wasmer_test
...
ld: warning: directory not found for option '-Lpackaged/lib/darwin-amd64'
FAIL: //wasmer:wasmer_test (see /private/var/tmp/_bazel_robfig/c7bc02ca11ec86a0d97a85fc3b3cfb06/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/wasmer/wasmer_test/test.log)

==================== Test output for //wasmer:wasmer_test:
dyld: Library not loaded: @rpath/libwasmer.dylib
  Referenced from: /private/var/tmp/_bazel_robfig/c7bc02ca11ec86a0d97a85fc3b3cfb06/sandbox/darwin-sandbox/31/execroot/__main__/bazel-out/darwin-fastbuild/bin/wasmer/wasmer_test_/wasmer_test.runfiles/__main__/wasmer/wasmer_test_/wasmer_test
  Reason: image not found
```

I suspect there's some tweak there that could make it work. Once I get `bazel test` working, I think you should be good to go. I have to step away from the computer for the rest of the day though. Hope this helps

**Comment by joehattori** [comment]
@robfig Thanks for the fix! After change the `clinkopts` to absolute path, `bazel test` also passed for whatever reason.
With this change, I was able to build and run a small project (https://github.com/joehattori/bazel-playground).
However, I still get the `undefined: wasmer.XXX` errors when I try to integrate wasmer-go into gVisor. The cloned version of the gvisor is [here](https://github.com/joehattori/gvisor/tree/rustfer) and this is supposed to be built with `bazel build runsc`, as I have modified the `WORKSPACE` and `runsc/container/BUILD` just like [the project I mentioned above](https://github.com/joehattori/bazel-playground), but this still gives me the error. Could you tell me where I got wrong on the [gvisor fork](https://github.com/joehattori/gvisor/tree/rustfer)?
The only part I am using wasmer-go where is `runsc/container/container.go`, so I changed `WORKSPACE` file and `runsc/container/BUILD`.

**Comment by joehattori** [comment]
@robfig Thanks for the fix! `bazel test` also passed when I set `clinkopts` to abosolute path.
With this I was finally able to integrate wasmer-go with my project. Thank you so much for your help.
