### ISSUE TITLE
nogo exclude_files doesn't work properly for cgo

### ISSUE THREAD

**Issue by TimothyGu** [bazelbuild/rules_go#2862]
### What version of rules_go are you using?

v0.27.0

### What version of gazelle are you using?

v0.23.0

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

darwin/amd64

### Any other potentially useful information about your toolchain?

Nothing special. Using Command Line Tools rather than Xcode.

### What did you do?

Excluding files from nogo analysis with the `exclude_files` config key. The filename in question is something like `external/com_blah/common/abc.go` (a file in a Gazelle `go_repository`), and I added `"external/": ""` to the nogo config file.

### What did you expect to see?

Diagnostics from the specified analyzers get excluded when running through this file.

### What did you see instead?

The diagnostics still appear:

```
external/com_blah/common/abc.go:14:23: possible misuse of unsafe.Pointer (unsafeptr)
Target @com_blah//common:common failed to build
```

----

I dug around a bit, and added 

```go
fmt.Fprintf(os.Stderr, "%s(%s)\n", act.a.Name, filename);
```

to right before [line 422 of nogo\_main.go](https://github.com/bazelbuild/rules_go/blob/707c634bf8f7ca5b57c2a923bec16fa62ced1fc7/go/tools/builders/nogo_main.go#L422). Here's what I got in the output logs:

```
compilepkg: unsafeptr(/var/folders/y4/d2xhlc550nv5wxfl3w1mr47xrjmbp2/T/rules_go_work-234795290/abc.cgo1.go)
nogo: errors found by nogo during build-time code analysis:
external/com_blah/common/abc.go:14:23: possible misuse of unsafe.Pointer (unsafeptr)
Target @com_blah//common:common failed to build
```

It appears that this may be a result of using `token.FileSet.File` on [line 397](https://github.com/bazelbuild/rules_go/blob/707c634bf8f7ca5b57c2a923bec16fa62ced1fc7/go/tools/builders/nogo_main.go#L397), which doesn't respect cgo's `//line` adjustment comments, rather than `token.FileSet.Position`.

**Comment by SlyMarbo** [comment]
>I added `"external/": ""` to the nogo config file

Is there any chance this is fixed by the config `"external/.*": ""`? The config is a regex, not a prefix.

**Comment by TimothyGu** [comment]
> Is there any chance this is fixed by the config `"external/.*": ""`? The config is a regex, not a prefix.

As you can tell from the path in the debugging log, the matched path is `/var/folders/y4/d2xhlc550nv5wxfl3w1mr47xrjmbp2/T/rules_go_work-234795290/abc.cgo1.go`, so not even `.*external/.*` would work. Nevertheless, nogo [uses](https://github.com/bazelbuild/rules_go/blob/4cd45a2ac59bd00ba54d23ebbdb7e5e2aed69007/go/tools/builders/nogo_main.go#L415) [RegExp.MatchString](https://golang.org/pkg/regexp/#Regexp.MatchString), which checks for any _substring_ of the path that matches the regex. (In other words, the config is not treated as `"^external/$": ""`.)
