### ISSUE TITLE
Cgo rpath is incorrectly computed for non-generated cc_imported dynamic libraries

### ISSUE THREAD

**Issue by TimothyGu** [bazelbuild/rules_go#2867]
### What version of rules_go are you using?

0.27.0

### What version of gazelle are you using?

None

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

darwin/amd64

### Any other potentially useful information about your toolchain?

Xcode 12.4 on macOS 11.2.1 Big Sur.

### What did you do?

See https://github.com/TimothyGu/rules_go_2867.

Essentially, we have:

* `//import` with a single `cc_import` target with `shared_library = "libhello.dylib"`. libhello.dylib is a precompiled dylib with `LC_ID_DYLIB` set to `@rpath/libhello.dylib`.

* `//src` with a single `go_binary` target that uses a function in libhello.dylib.

### What did you expect to see?

`bazel run //src` should run successfully.

### What did you see instead?

`bazel run //src` prints

```
❯ bazel run //src
INFO: Analyzed target //src:src (5 packages loaded, 106 targets configured).
INFO: Found 1 target...
Target //src:src up-to-date:
  bazel-bin/src/src_/src
INFO: Elapsed time: 5.368s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
dyld: Library not loaded: @rpath/libhello.dylib
  Referenced from: /private/var/tmp/_bazel_tigu/.../execroot/__main__/bazel-out/darwin-fastbuild/bin/src/src_/src
  Reason: image not found
```

### Digging deeper

We see that when the `src` binary is getting linked, a rpath is set:

```
❯ bazel aquery 'mnemonic("GoLink", //src)'
...
  Command Line: (exec bazel-out/host/bin/external/go_sdk/builder \
    link \
    [...] \
    -- \
    -extld external/local_config_cc/cc_wrapper.sh \
    '-buildid=redacted' \
    -extldflags '-fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -mmacosx-version-min=11.1 -Wl,-rpath,@loader_path/../../import')
```

(The very last line above includes `-Wl,-rpath,@loader_path/../../import`.)

This rpath is correct if `@loader_path` is taken to be `bazel-bin/src/src_/src.runfiles/__main__/src/src_/src`. Indeed the path

```
bazel-bin/src/src_/src.runfiles/__main__/src/src_/../../import/libhello.dylib
```

reaches libhello.dylib. However, in actuality, the `src` binary in `src.runfiles` is a symbolic link:

```
❯ readlink bazel-bin/src/src_/src.runfiles/__main__/src/src_/src
/private/var/tmp/_bazel_tigu/.../execroot/__main__/bazel-out/darwin-fastbuild/bin/src/src_/src

(i.e., bazel-bin/src/src_/src)
```

and as far as I can tell, dyld sets `@loader_path` to be the "real" path of the executable, obtained after all symlinks are resolved. By this logic we see that 

```
bazel-bin/src/src_/../../import/libhello.dylib
```

is not a valid path to the libhello.dylib file.

### Potential fix

One potential fix is to add another rpath to the linked binary that accommodates for the case where the executable is outside its own .runfiles directory. In this case, if we had

```
-extldflags '-Wl,-rpath,@loader_path/../../import -Wl,-rpath,@loader_path/src.runfiles/__main__/import'
```

then everything would run correctly.

**Comment by TimothyGu** [comment]
I just noticed that there's actually a test for a very similar case as above: https://github.com/bazelbuild/rules_go/blob/707c634bf8f7ca5b57c2a923bec16fa62ced1fc7/tests/core/cgo/BUILD.bazel#L31-L36

However, a crucial difference is that in the test, the analog of "libhello.dylib" is compiled and hence exist in bazel-bin. In this case, however, libhello.dylib doesn't exist in bazel-bin outside of the runfiles hierarchy. The dylib file should always be in the runfiles hierarchy though, so I think we could just change the `-rpath` argument rather than providing another `-rpath`.

**Comment by negator** [comment]
@TimothyGu thank you for this patch, we are experiencing this issue with `rules_go` `0.27.0` as well, when building the `libvips` repo which includes prebuilt binaries .

**Comment by TimothyGu** [comment]
@jayconrod Would you be able to review #2869 when you get a chance? Thanks!

**Comment by jayconrod** [comment]
@TimothyGu It's in my review queue. I'll probably have bandwidth to look at it this week.

cc @bazelbuild/go-maintainers in case anyone has bandwidth earlier.

**Comment by TimothyGu** [comment]
I can't ping @bazelbuild/go-maintainers, but hoping someone can take a look soon.

I am ending an industry internship this week, and it'd be great not to have references to my own fork in the company's code base after I leave ;)
