### ISSUE TITLE
rules_go's more configurable visibility vs. "go build"

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2871]
There are cases when `go build` disallows one package to import another:

* Go packages with "internal" as part of the path is not allowed to be imported from outside
* Main package is not allowed to be imported

Bazel emulates these two rules by having Gazelle generating rules with limited visibilities. If people manually change the visibility, rules_go would go along with it. As the codebase evolves, people would find some packages become not buildable by `go build` anymore because of these importing rules.

@jayconrod @achew22 @steeve What do you think? Should we enforce these rules in rules_go? Does Google's internal build system allow these?

**Comment by achew22** [comment]
Definitely not authoritative, but if you want to make your repo incompatible with the `go build` tool chain I think we should let them. They've already opted out of it by using Bazel for their build. Beyond that it is kind of icky and I wouldn't want to do it myself, what is the incentive to force people to adhere to the stipulations of a build tool they've opted out of?

If this is a problem in your organization, I think the first tool I would reach for would be to replace `go_library` with a macro that validated that the `visibility` didn't break any of these rules. Is that a solution that would work for you?

**Comment by jayconrod** [comment]
I think it makes sense to rely on `visibility` attributes and allow people to manually edit them. Bazel's `visibility` is richer than what `go build`, so it can give folks some useful flexibility. Gazelle can map `go build`'s "internal" convention to Bazel `visibility` in most cases, so this should affect manual changes. If manual changes shouldn't be allowed, I think the best way to approach that is with a macro (as @achew22 suggested) or an auditing tool.

It is pretty weird that `main` packages can be imported. I don't have a problem with changing that, though I am sometimes annoyed that `go build` doesn't allow that (for the purpose of tracking tool dependencies).

**Comment by robfig** [comment]
I would echo the perspectives and think that we should default to a configuration which is compatible with `go build` but allow folks to opt out. Thanks for raising - definitely worth thinking about - but I think we're good here.
