### ISSUE TITLE
go_embed_data should support args.use_param_file

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#2880]
OS args limit may be hit when attempting to embed things like node_modules.

I have a fix, will plan to submit PR.

**Comment by robfig** [comment]
How it going?

**Comment by pcj** [comment]
Looks like I failed to strike when the iron is hot!  If others are hitting this, I can resume work on it, otherwise the issue can be closed.

**Comment by robfig** [comment]
OK, no problem! I'm not aware of any other place this has come up so far, so I'll close this for now. Thanks
