### ISSUE TITLE
No such package when requesting external dependencies.

### ISSUE THREAD

**Issue by entersb** [bazelbuild/rules_go#2883]
Rules_go version 0.27.0.

Gazelle version 0.23.0.

Bazelisk version is 4.1.0. 

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux Mint 19.2.

### Any other potentially useful information about your toolchain?

I have added simple main file with klog package. Gazelle manages to get klog package as instructed in its manual.

When running `bazelisk build //mailer:mailer`, it cannot fetch external dependencies required by klog package.

Example to reproduce is below:
In root add WORKSPACE and BUILD file as below.

WORKSPACE
```bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "69de5c704a05ff37862f7e0f5534d4f479418afc21806c887db544a316f3cb6b",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "62ca106be173579c0a167deb23358fdfe71ffa1e4cfdddf5582af26520f1c66f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_repository(
    name = "io_k8s_klog_v2",
    importpath = "k8s.io/klog/v2",
    sum = "h1:Q3gmuM9hKEjefWFFYF0Mat+YyFJvsUyYuwyNNJ5C9Ts=",
    version = "v2.8.0",
)

go_rules_dependencies()

go_register_toolchains(version = "1.16")

gazelle_dependencies()
```
and root BAZEL
```bazel
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    prefix = "basics",
)
```
In mailer folder, add BUILD and main.go as below.

BUILD
```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mailer_lib",
    srcs = [
        "main.go",
    ],
    importpath = "basics/mailer",
    visibility = ["//visibility:private"],
    deps = [
        "@io_k8s_klog_v2//:klog",
    ],
)

go_binary(
    name = "mailer",
    embed = [":mailer_lib"],
    visibility = ["//visibility:public"],
)
```

main.go
```go
package main

import (
	"flag"

	"k8s.io/klog/v2"
)

func main() {

	klog.InitFlags(nil)
	// By default klog writes to stderr. Setting logtostderr to false makes klog
	// write to a log file.
	flag.Set("logtostderr", "false")
	flag.Set("log_file", "myfile.log")
	flag.Parse()
	klog.Info("nice to meet you")
	klog.Flush()
}

```

Run `bazelisk build //mailer:mailer` to reproduce error.

### What did you expect to see?

To collect all external dependencies and build application.

### What did you see instead?

```
bazelisk build //mailer:mailer
ERROR: /home/localhost/.cache/bazel/_bazel_localhost/3d438f0584258c67b292e77bb53909f8/external/io_k8s_klog_v2/BUILD.bazel:3:11: no such package '@com_github_go_logr_logr//': The repository '@com_github_go_logr_logr' could not be resolved and referenced by '@io_k8s_klog_v2//:klog'
ERROR: Analysis of target '//mailer:mailer' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.822s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 33 targets configured)

```

**Comment by robfig** [comment]
You need to have `go_repository` declarations for all transitive dependencies. You can use [gazelle](https://github.com/bazelbuild/bazel-gazelle/) to generate those for you:

```
$ bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%go_dependencies
```

**Comment by entersb** [comment]
@robfig Thanks for answer. 

Still, your explanation is not clear, as I do not have go.mod at all. I am using gazelle directly to import dependencies.
Can you provide more information?

**Comment by robfig** [comment]
You must have `go_repository` declarations for all transitive dependencies. In your example, you have only one for `k8s.io/klog/v2`, and the build error is saying that it can not find that package's dependency, `com_github_go_logr_logr`. That's because klog depends on go-logr. 

I suggest the following:

```
$ go mod init example.org/mine
$ go get k8s.io/klog/v2
$ bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%go_dependencies
```

That should create a go.mod file with all of the dependencies of klog, and then run gazelle to convert those into Bazel repository declarations.
