### ISSUE TITLE
how to input compile flag gcflag to bazel go build 

### ISSUE THREAD

**Issue by liuxiangwoaini** [bazelbuild/rules_go#2893]
### What version of rules_go are you using?
1.16.1

### What version of gazelle are you using?
0.22

### What version of Bazel are you using?
4.1

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
linux amd64

### What did you do?
bazel test ...

### What did you expect to see?
input compile flag to rules_go
i find rules_go has some compile flag ,i want to input some within bazel test ,but i cannot find some documentation about it ,can you tell me how to input args to go compile
![image](https://user-images.githubusercontent.com/12146363/121802719-6a7e5600-cc70-11eb-92ac-20ae458fc0d5.png)

**Comment by liuxiangwoaini** [comment]
i want to input go build flag gcflag input bazel go build 
https://golang.org/cmd/go/

**Comment by achew22** [comment]
You said

> i try to use gc_goopts

Can you elaborate on how you tried that? Possibly providing a code sample of your `BUILD` file where you did this? I would expect that to work

**Comment by liuxiangwoaini** [comment]
![image](https://user-images.githubusercontent.com/12146363/121835553-2a68b300-cd04-11eb-8893-af89213cfd68.png)
this is my build file, i want to  disable inline, i also try -l flag ,but if did not work.

this is the error log 
![image](https://user-images.githubusercontent.com/12146363/121835822-c2669c80-cd04-11eb-9fe4-d2811bfb0ed6.png)

**Comment by liuxiangwoaini** [comment]
> You said
> 
> > i try to use gc_goopts
> 
> Can you elaborate on how you tried that? Possibly providing a code sample of your `BUILD` file where you did this? I would expect that to work

i supple info in a new comment

**Comment by achew22** [comment]
How did you invoke `rules_go`? your 3 line snippet isn't nearly enough information to understand what's going on. Can you put a sample repo up on github so that someone who wants to help could see the issue in its entirety?

**Comment by achew22** [comment]
Also, sharing screenshots of error messages is not a great way to do this. By sharing a screenshot you prevent people from finding the text that you're using in a search engine. Please include all future snippets as copy/pasted code in a [code block](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by liuxiangwoaini** [comment]
I am sorry I am not familiar with raising issue.
this is my build file :
`load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "merge.go",
    ],
    importpath = "app/calcm",
    visibility = ["//app/calcm:__subpackages__"],
    deps = [
        "//app/calcm/config:go_default_library",
        "//app/calcm/model:go_default_library",
        "@org_golang_google_protobuf//types/known/timestamppb:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "merge_test.go",
    ],
    gc_goopts = ["-gcflags=all=-l",],
    embed = [":go_default_library"],
    deps = [
        "//app/calcm/config:go_default_library",
        "//app/calcm/model:go_default_library",
        "@com_github_golang_mock//gomock:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
    ],
)
`

and this is the error log 
`
bazel test ...
INFO: Analyzed 205 targets (0 packages loaded, 0 targets configured).
INFO: Found 123 targets and 82 test targets...
ERROR: /root/bazel-build/workspace/src/app/calcm/BUILD.bazel:38:8: GoCompilePkg app/calcm/go_default_test.internal.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src app/calcm/config.go -src app/calcm/model.go -src ... (remaining 97 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
flag provided but not defined: -gcflags
usage: compile [options] file.go...
  -%    debug non-static initializers
  -+    compiling runtime
  -B    disable bounds checking
  -C    disable printing of columns in error messages
  -D path
        set relative path for local imports
  -E    debug symbol export
  -I directory
        add directory to import search path
  -K    debug missing line numbers
  -L    show full file names in error messages
  -N    disable optimizations
  -S    print assembly listing
  -V    print version and exit
....
`

**Comment by achew22** [comment]
Thanks for pasting as a codeblock, that makes it much easier to help.

I believe the issue is that the rule directly exposes a setting for the `gcflag`  in the target definition. Since you're not going through the `go` toolchain you don't need to indirect your flags with the `-gcflags=` prefix. You probably can do just

```
go_test(
    name = "go_default_test",
    srcs = [
        "merge_test.go",
    ],
    gc_goopts = ["-l"], # Note how I'm not passing gc_goopts multiple times
    embed = [":go_default_library"],
    deps = [
        "//app/calcm/config:go_default_library",
        "//app/calcm/model:go_default_library",
        "@com_github_golang_mock//gomock:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
    ],
)
```

Could you comment with if this was successful?

**Comment by liuxiangwoaini** [comment]
it success , thanks so much !!!!!!!
