### ISSUE TITLE
Tag a latest release - disable prerelease option

### ISSUE THREAD

**Issue by gibfahn** [bazelbuild/rules_go#2899]
Normally I (and our automation) get the latest release for a GitHub repo by querying the `/releases` endpoint. However for this repo I don't get any results:

```console
❯ curl -s https://api.github.com/repos/bazelbuild/rules_go/releases/latest

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
}
```

I believe this is because the releases are all marked as pre-release by the setting of the `This is a pre-release` tag in the Releases UI, or `prerelease: true` in the API. It would be nice to not do that so that getting latest works.

I get that this is probably still technically a pre-release, but I suspect that the stability guarantees are being fairly well upheld, and people are using it for production systems anyway.

Same thing applies to Gazelle too.

**Comment by robfig** [comment]
This seems fine to me. Any objections, @jayconrod ?

**Comment by jayconrod** [comment]
Seems fine. I've removed the prerelease bit from v0.28.0.

I think we did this with the idea that we'd some day shed our API tech debt and tag v1.0.0, but somehow we've ended up at v0.28.0. I don't think the prerelease bit communicates anything that's not also in semver, so if it's causing problems, there's no sense in leaving it on.
