### ISSUE TITLE
org_golang_google_protobuf

### ISSUE THREAD

**Issue by Aresky** [bazelbuild/rules_go#2900]
### What version of rules_go are you using?

rules_go-v0.27.0

### What version of gazelle are you using?

bazel-gazelle-v0.23.0

### What version of Bazel are you using?

Build label: 4.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jan 23 02:07:47 2021 (1611367667)
Build timestamp: 1611367667
Build timestamp as int: 1611367667

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macos-11.4

### What did you do?

bazel build //app/interface/user/cmd:cmd

error：
external/com_github_go_kratos_kratos_v2/transport/http/binding/encode.go:95:22: fd.TextName undefined (type protoreflect.FieldDescriptor has no field or method TextName)

Possible reason: protobuf version is too low

### What did you expect to see?

How can I customize the version of org_golang_google_protobuf, I need a version above 1.26.0, but now I have installed 1.25.0

**Comment by wamuir** [comment]
See [overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies).  You'll need something similar to:

```bazel
# WORKSPACE
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "69de5c704a05ff37862f7e0f5534d4f479418afc21806c887db544a316f3cb6b",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

http_archive(
    name = "org_golang_google_protobuf",
    patch_args = ["-p1"],
    patches = [
        "//:org_golang_google_protobuf-gazelle.patch",
    ],
    sha256 = "a01b25899f598fbac3c2626376b74fc15229f009904c262658f8da1c1c392386",
    strip_prefix = "protobuf-go-1.27.1",
    urls = [
        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf-go/archive/v1.27.1.zip",
        "https://github.com/protocolbuffers/protobuf-go/archive/v1.27.1.zip",
    ],
)

go_rules_dependencies()

go_register_toolchains(version = "1.16")
```

Note that this applies a patch, located in the root of the workspace.  This patch for v1.27.1 can be downloaded from https://github.com/bazelbuild/rules_go/blob/47887148c9ae5ef50c7e82b31f18bd0106ec4888/third_party/org_golang_google_protobuf-gazelle.patch

**Comment by Aresky** [comment]
> See [overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies). You'll need something similar to:
> 
> ```python
> # WORKSPACE
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> 
> http_archive(
>     name = "io_bazel_rules_go",
>     sha256 = "69de5c704a05ff37862f7e0f5534d4f479418afc21806c887db544a316f3cb6b",
>     urls = [
>         "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
>         "https://github.com/bazelbuild/rules_go/releases/download/v0.27.0/rules_go-v0.27.0.tar.gz",
>     ],
> )
> 
> load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
> 
> http_archive(
>     name = "org_golang_google_protobuf",
>     patch_args = ["-p1"],
>     patches = [
>         "//:org_golang_google_protobuf-gazelle.patch",
>     ],
>     sha256 = "a01b25899f598fbac3c2626376b74fc15229f009904c262658f8da1c1c392386",
>     strip_prefix = "protobuf-go-1.27.1",
>     urls = [
>         "https://mirror.bazel.build/github.com/protocolbuffers/protobuf-go/archive/v1.27.1.zip",
>         "https://github.com/protocolbuffers/protobuf-go/archive/v1.27.1.zip",
>     ],
> )
> 
> go_rules_dependencies()
> 
> go_register_toolchains(version = "1.16")
> ```
> 
> Note that this applies a patch, located in the root of the workspace. This patch for v1.27.1 can be downloaded from https://github.com/bazelbuild/rules_go/blob/47887148c9ae5ef50c7e82b31f18bd0106ec4888/third_party/org_golang_google_protobuf-gazelle.patch

thank you！
