### ISSUE TITLE
Support using precompiled protoc binaries

### ISSUE THREAD

**Issue by rmohr** [bazelbuild/rules_go#2902]
### What version of rules_go are you using?

v0.27

### What version of gazelle are you using?

v0.23
### What version of Bazel are you using?

3.7.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What did you do?

When switching locally branches in a project which `rules_go` we spend quite some time recompiling `protoc` over and over.

### What did you expect to see?

It would be great if `rules_go` could work with precompiled protoc versions, like described in https://github.com/bazelbuild/rules_proto/pull/36 and for example implemented at https://github.com/bazelbuild/rules_scala/pull/1142 for the scala rules.

### What did you see instead?

`protoc` gets compiled every time we switch a branch.

**Comment by achew22** [comment]
I think improving `rules_go` like this would be a great first contribution to the project! How can I help you get into a position where you can effectuate this change?

As a side note, since `WORKSPACE` files are not imported from projects, only `.bzl` files that you explicitly `load`, I don't believe there is any action her to unblock consumers. Is that correct?

**Comment by rmohr** [comment]
Thanks for your response. I can try to have a look. My fist guess would be that if we are lucky wrapping some dependencies in a bzl file with a `maybe` could already solve the issue. I tried to modify the workspace file of our Project to use the precompiled versions but it looked like rules_go is somehow pulling in the dependencies still. Would be great if you have a few pointers already.

**Comment by achew22** [comment]
I can tell you that my project already uses the precompiled `protoc` and we don't patch `rules_go` at all. Maybe you could describe what you've tried already?

**Comment by rmohr** [comment]
> I can tell you that my project already uses the precompiled protoc and we don't patch rules_go at all.

That sounds great. How exactly did you set it up?

I did a similar thing like described here: https://github.com/bazelbuild/rules_proto/pull/36#issuecomment-763807462.

I can share my exact changes tomorrow.

**Comment by rmohr** [comment]
@achew22 thanks for your responses. I tried it again. I don't know what I did wrong before, but now it is working: https://github.com/kubevirt/kubevirt/pull/5959
