### ISSUE TITLE
rules_go CI broken for Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_go#2916]
Breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2092#8b412153-3218-4bbe-9b14-99420e2561fb

Culprit: https://github.com/bazelbuild/bazel/commit/ca1d20fdfa95dad533c64aba08ba9d7d98be41b7

**Comment by c-parsons** [comment]
@oquenchil

**Comment by c-parsons** [comment]
This may have already been rolled back in https://github.com/bazelbuild/bazel/commit/aa768ada9ef6bcd8de878a5ca2dbd9932f0868fc

I'll trigger another build.

**Comment by jayconrod** [comment]
Looks like the rules_go pipelines are still passing. Let me know if we need to do anything here.
