### ISSUE TITLE
feature request: add `gen_only` or `extra_sources` to `go_proto_library`

### ISSUE THREAD

**Issue by dt** [bazelbuild/rules_go#2920]
Hello!

A common pattern in our project is to have a hand-written "foo.go" along side a "foo.pb.go" that is generated from "foo.proto", where the foo.go file may define some type aliases, like say `type FooID = uint64`, as well as additional methods on some of the types defined in foo.proto/foo.pb.go, and then foo.proto will include options like `casttype=FooID` that mean its generated foo.pb.go includes methods depends on foo.go to build. Thus foo.pb.go depends on foo.go to build and foo.go depends on foo.pb.go to build -- they expect to be built together, as one package and there is a circular dependency between them. 

Previously we've defined a `go_library` target around foo.go, and then included that target in the `embed` attribute of the `go_proto_library` rule for foo.proto, however that `go_library` is a little weird, in that it it cannot build successfully on its own, as it only includes foo.go, and not the generated foo.pb.go that foo.go needs to build.

Instead, it seems like `go_proto_library` could be provided go sources like foo.go directly, instead of via a `go_library` targets in `embed`, so that the `go_library` it yields builds the union of these and the generated sources?

### What version of rules_go are you using?

v0.26.0 (with [a couple patches](https://github.com/cockroachdb/rules_go/tree/inuse))

### What version of gazelle are you using?

https://github.com/bazelbuild/bazel-gazelle/commit/d038863ba2e096792c6bb6afca31f6514f1aeecd

### What version of Bazel are you using?

4.1.0-homebrew

### Does this issue reproduce with the latest releases of all the above?

I believe so (I haven't rebased our patches to test, but I didn't see any similar features in the subsequent releases' notes).

### What operating system and processor architecture are you using?

n/a (linux and Darwin, x64)

### Any other potentially useful information about your toolchain?

Using gogoproto

**Comment by achew22** [comment]
> Previously we've defined a go_library target around foo.go, and then included that target in the embed attribute of the go_proto_library rule for foo.proto, however that go_library is a little weird, in that it it cannot build successfully on its own, as it only includes foo.go, and not the generated foo.pb.go that foo.go needs to build.

Could you speak to when previously was and what changed? What timeline are we talking about here? O(hours), O(months), O(years)?  I'm not aware of any major changes in that system in the past 90 days that would prohibit doing something like that. Is this coming up because of an upgrade of rules_go? What versions are you running? Maybe this could be helped with a copy/pasted'd example or gist instead of a narrative description?

Our issues are prefilled with `<!-- Please answer these questions before submitting your issue. Thanks! -->`, which it appears you deleted before submitting. If you could go through and answer that section that would be greatly appreciated.

**Comment by dt** [comment]
Whoops, sorry, I've edited to include the used version information (I'd elided it thinking it wasn't as useful to a new feature suggestion).

Also, sorry for the confusion, I should have said "Currently" or something instead of "Previously", as nothing has changed upstream w.r.t this, it is just something we've been looking at. When we first started working on bazel-izeing our repo, we setup the `go_library` targets to pass to `go_proto_library`'s `embed` list, but they are causing some issues (more and that below) so we'd prefer to remove them. 

Let me see if can give a more detailed example, based on the existing [`embed_test`](https://github.com/bazelbuild/rules_go/blob/master/tests/core/go_proto_library/BUILD.bazel#L35) case.

**How foo.pb.go depends on foo.go**

A common pattern in our codebase is to use typed alias instead of a raw int64/[]byte/etc to provide improved type safety and more expressive function signatures. Looking at the the `embed_test` example, we might replace `extra.go` with a `foo.go` that looks like this:
```go
package foo

type FooValue int64
```

Now we update [foo.proto](https://github.com/bazelbuild/rules_go/blob/master/tests/core/go_proto_library/foo.proto), so that rather than reading `message Foo { int64 value = 1; }` it instead reads `message Foo {int64 value = 1 [(gogoproto.casttype) = "FooValue"]; }`. Now the generated go struct's `Value` field is of type `FooValue` instead of `int64`, just like we wanted.

Thus, the generated `foo.pb.go` now depends on `foo.go` (since it uses `FooValue`).

**How foo.go depends on foo.pb.go**

Another common thing in our codebase is to add extra methods to proto-generated types. For example, let's a getter for Value that does a little business logic, so `foo.go` which now reads:

```go
package foo

type FooValue int64

// ReducedValue returns the value reduced by x, or zero if x > value.
func (f *Foo) ReducedValue(x FooValue) FooValue {
  if f.Value > x { 
    return f.Value - x
  }
  return 0
}
```

Thus, the generated `foo.go` now depends on `foo.pb.go` (the `Foo` receiver on `ReducedValue`).

**How We Build This Today**

Today, we use the `embed` attribute of `go_proto_library` to add `foo.go` to the sources of a `go_proto_library` that owns `foo.proto`, the same way this is done in `embed_test`:

```bazel
proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)

go_library(
    name = "extra_lib",
    srcs = ["foo.go"],
)

go_proto_library(
    name = "embed_go_proto",
    proto = ":foo_proto",
    embed = [":extra_lib"],
)
```

This _mostly_ works: we can build and depend on "embed_go_proto"  in other targets. However `extra_lib` here is on its own not buildable since our "foo.go" depends on symbols from foo.pb.go, but it doesn't (and can't, right?) depend on `embed_go_proto`. This comes up when people use `:all` and accidentally end up trying to build or test `:extra_lib` accidentally.

**What I'm Proposing**
It seems like since `foo.go` depends on `foo.pb.go` and `foo.pb.go` depends on `foo.go`, what I really want is for them to both be in one, and only one, target's sources. Concretely, I'm suggesting being able to pass individual go sources directly to `go_proto_library` which are added to its `go_srcs` in addition to any generated sources and embedded target sources, so in our example we would remove `extra_lib` and just have `embed_go_proto` own `foo.go`, e.g.:

```bazel
proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)

go_proto_library(
    name = "embed_go_proto",
    proto = ":foo_proto",
    go_srcs = ["foo.go"],
)
```

**Comment by dt** [comment]
And even more concretely, the functionality addition I'm suggesting is essentially: 
```diff
diff --git a/proto/def.bzl b/proto/def.bzl
@@ -98,7 +105,7 @@ def _go_proto_library_impl(ctx):
             fail("Either proto or protos (non-empty) argument must be specified")
         proto_deps = ctx.attr.protos
 
-    go_srcs = []
+    go_srcs = [f for t in ctx.attr.go_srcs for f in as_iterable(t.files)]
     valid_archive = False
 
     for c in compilers:
@@ -146,6 +153,7 @@ go_proto_library = rule(
             providers = [GoLibrary],
             aspects = [_go_proto_aspect],
         ),
+        "go_srcs": attr.label_list(allow_files = go_exts + asm_exts + cgo_exts, default = []),
         "importpath": attr.string(),
```

**Comment by achew22** [comment]
Thanks for following up with more information. It's much appreciated.

I've never used gogoproto, so please forgive any naïveté I might have around the topic.

My brief familiorization with gogo revolved around me checking out the [Gazelle generated BUILD file](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/testdata/protos_gogo/BUILD.want) for the testcases.

https://github.com/bazelbuild/rules_go/blob/46b4330eef15da2889373329f3a8830ebe2c921f/tests/core/go_proto_library/BUILD.bazel#L35-L47

This may be a usecase where it is worth extending the API, but I generally like to try to use an existing API before I go mucking with things. What do you think about the following modification, where I invert the hierarchy:

```bzl
go_proto_library(
    name = "embed_go_proto",
    # <-- Remove the embed statement from here
    importpath = "github.com/bazelbuild/rules_go/tests/core/go_proto_library/foo",
    proto = ":foo_proto",
)

go_library(
    name = "extra_lib",
    embed = [":embed_go_proto"], # <-- This line is new
    srcs = ["extra.go"],
    importpath = "github.com/bazelbuild/rules_go/tests/core/go_proto_library/foo",
)
```

Now they should both build in the glob case (without resorting to tagging as `manual`), it keeps the separation of concerns around a `go_proto_library`. Can you help me understand where this straw man falls over in your usecase?

**Comment by dt** [comment]
I don't think just inverting the dependency edge quite solves our issue, since in our example we have a _circular_ dependency between the generated code and the "extra" code. If we remove the `embed` directive from `embed_go_proto`, then _it_ will fail to build, because its generated `foo.pb.go`, thanks to the `casttype` option, will look like `type Foo struct { Value FooValue }`but `FooValue` is defined in `extra_lib`. I think the root issue here is that we have two mutually dependent source files -- the generated foo.pb.go and extra.go (which I'd renamed `foo.go` in my example). Putting them in separate targets will always result in either one not being able to build, or a circular dependency between targets, so what we really want is for them to just be one target.

**Comment by linzhp** [comment]
It seems you are not using Gazelle. Have you tried? Your issue may get automatically resolved by Gazelle. This is what Gazelle would generate for you:

```python
proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)

go_proto_library(
    name = "foo_go_proto",
    importpath = "example.com/some/path/foo"
    proto = ":foo_proto",
)

go_library(
    name = "go_default_library",
    srcs = ["foo.go"],
    importpath = "example.com/some/path/foo"
    embed = [":foo_go_proto"],
)
```

When you import "example.com/some/path/foo", Gazelle would automatically resolve to the "go_default_library", which incudes both the generated and regular file.

**Comment by dt** [comment]
@linzhp we are using Gazelle, and that's what we get. The problem some of our developers are complaining about is that that yields a target -- `foo_go_proto` -- that will fail to build if built on its own. You don't particularly _need_ to build it -- as you say, `go_default_library` is what you'd typically depend on and expect to build instead -- but it there's still the unfortunate effect of having a target laying around that fails to build, which trips up anyone running `:all` shorthands or who otherwise wants to test/build/etc "all" the targets in some subtree. Ideally, we'd not have these broken targets laying around just to embed in another target, if we could instead just pass their src's directly.

**Comment by dt** [comment]
I found another example that might be clearer: 

Several of our proto messages include `option (gogoproto.goproto_stringer) = false;` which skips the generation of a `func (m* Foo) String() string` method, in `foo.pb.go`, to allow an alternative `String()` method to be hand-written in say `foo.go` instead. 

However, since `String()` is part of the `proto.Message` interface, this means `foo.pb.go` will no longer compile on its own, since it things `*Foo` implements that interface i.e. it now _depends_ on being compiled with `foo.go`, to add that `String()` method. But `foo.go` obviously depends on `foo.pb.go` since it has a method `func (m *Foo) String() sting {` that is mentioning the type `Foo` from `foo.pb.go.`

So hopefully this illustrates that any `go_proto_library` building a proto that uses `gogoproto.goproto_stringer=false` *must* somehow include at least one additional source file that defines the custom stringers. The remaining question is how it does that, i.e. via `embed` or something else.

It we say it does so via `embed` as is supported today, then we need to wrap that additional source file in a `go_library` -- let's call it "shim" for now -- to pass to embed. Now our go_proto_library target is satisfied. Yay. 

However, this new "shim" target is _not_ happy: it contains only our `foo.go` file that has content `func (m *Foo) String() string { return "hello" }`, but if you try to build :shim for any reason, it'll fail, because `Foo` is undefined.  And we can't make it happy, because it depends on our generated protos... which depend on it. 

The problem here is we made a separate ":shim" target for code that is not in fact separate, and never _really_ wanted to be separate -- we just put it in a separate target since that is what we had to do to pass it to `embed`. If instead we could have just passed `foo.go` to be included in our go_proto_library, it be built with, and only with, foo.pb.go, and they'd both be happy.

Does this example make any more sense than the `casttype` one?  At the root I think they're basically the same, but this one I think is a little clearer since in the `casttype` case you could, in theory, move all the type definitions to tiny, def-only root target to break the cycle and have three targets each of which is buildable (e.g. :foo->:foo_proto->:foo_types) but with the missing `String()` method I think it's more obvious that the cycle _can't_ be broken since it is foo.pb.go->foo.go->foo.pb.go, so any solution that makes a target with only foo.go or only the protos is going to make a broken target.

**Comment by dt** [comment]
@achew22 or @linzhp does the example of a custom`String()` _method_ -- where its definition both needs the generated code to compile, since its receiver type is the generated type, and is needed by the generated code to compile since it is part of the interface the generated code's type asserts it implements -- help show how it is indeed a *circular* dependency between those two files, and thus neither can be placed in a non-broken `go_library` by itself for use in the current `embed` field?

**Comment by linzhp** [comment]
yeah, the example helps a lot. An alternative solution is to add an `out` attribute to `go_proto_library`, so we can specify `out = "foo.pb.go"`. When `go_proto_library` sees that, it will not compile the generated file. So the build rules would look like this:

```python
proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)

go_proto_library(
    name = "foo_go_proto",
    proto = ":foo_proto",
    out = "foo.pb.go",
)

go_library(
    name = "go_default_library",
    srcs = [
        "foo.go",
        "foo.pb.go",
    ],
    importpath = "example.com/some/path/foo"
)
```

This is the approach [gomock](https://github.com/jmhodges/bazel_gomock/blob/master/gomock.bzl) uses

**Comment by dt** [comment]
Ah, yeah, not expecting the `go_proto_library` to synthesize a its own buildable `go_library` at all, and instead just yield a derived source that can be consumed by another rule, would work too, rather than trying to pass it raw sources that nobody else owns. Would that imply though we'd need define one `go_proto_library` _per proto_, since we only specify a single `out` value? 

I guess, alternatively, following the same approach though, couldn't we optionally just not have `go_proto_library` _not_ synthesize a `go_library` target at all, and instead only be consumed by being `embed`'ed in some other `go_library`?

**Comment by linzhp** [comment]
yeah, that's a good idea too. We can add an attribute like `gen_only`, when it's true, `go_proto_library` would instead return the list of generated Go file as `DefaultInfo`, so you can have:

```python
proto_library(
    name = "foo_proto",
    srcs = ["foo1.proto", ""foo2.proto"],
)

go_proto_library(
    name = "foo_go_proto",
    proto = ":foo_proto",
    gen_only = True,
)

go_library(
    name = "go_default_library",
    srcs = [
        "foo.go",
        ":foo_go_proto",
    ],
    importpath = "example.com/some/path/foo"
)
```

**Comment by dt** [comment]
Apologies for the extended delay in getting back to this. After digging a little more it looks like the `valid_archive` flag on the _compiler_ does basically exactly this: it returns a `GoLibrary` and `GoSource` that can be embedded but does _not_ return a GoArchive that thinks it should be able to build standalone, i.e. exactly what needed, but just at the compiler level rather than individual target granularity. I guess I can just define an extra variation of my go_proto_compiler though and use it for the targets that are split like this though, rather than adding a new per-target flag. Sorry for the noise!

**Comment by achew22** [comment]
@dt thanks for following up on this. If you do end up going this route, would you be willing to link to the PR where you do it in this issue? It'd be a great way to close the loop for future people with similar problems.

**Comment by dt** [comment]
>  If you do end up going this route, would you be willing to link to the PR where you do it

Yep, I just merged that here: https://github.com/cockroachdb/cockroach/pull/74313. I ended up just setting `valid_archive=False` on our shared `go_proto_compiler` rules, so all our `go_proto_library` targets, both those that were broken and those that weren't, stopped producing `GoArchive`s, and then I switched our gazelle configuration to mode `default`, so they all have the generated `go_library` wrappers targets to yield buildable archives.
