### ISSUE TITLE
no such attribute 'env' in 'go_transition_test' rule

### ISSUE THREAD

**Issue by v3n** [bazelbuild/rules_go#2921]
### rules_go version

`v0.27.0`

### What version of gazelle are you using?

`v0.23.0`

### What version of Bazel are you using?

`4.1.0`

### Does this issue reproduce with the latest releases of all the above?

Reproduces with `v0.28.0`

### What operating system and processor architecture are you using?

macOS, amd64.

### Any other potentially useful information about your toolchain?

Fairly standard toolchain, using a few custom protobuf compilers for proto+gRPC. This is a set of e2e (external) tests that uses the _actual_ binary as a run-time dependency.

### What did you do?
```
go_test(
    name = "go_default_test",
    srcs = ["svm_test.go"],
    args = ["$(location :svm)"], # actual binary under test
    data = [
        ":svm",
        "//thirdparty/patchcli",
    ],
    embed = [":go_default_library"],
    env = {
        "SNIPPED_TOOL_PATH": "$(location //thirdparty/snipped_tool)",
    },
    race = "off",
    rundir = ".",
    tags = [
        "functional",
    ],
    deps = ["<snip>"],
)
```
```
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "snipped_tool",
    src = select({
        "@platforms//os:windows": ":win64",
        "@platforms//os:macos": ":macos",
        "@platforms//os:linux": ":linux",
    }),
    out = "snipped_tool",
)
```

`$ bazel test //services/svm:go_default_test`

### What did you expect to see?

Per [the Bazel common attributes](https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes-tests), I would expect this to work and this environment variable be available in the test runtime.

### What did you see instead?

```
$ bazel test //services/svm:go_default_test
Another command (pid=42199) is running. Waiting for it to complete on the server (server_pid=39418)...
INFO: Invocation ID: de25d398-863c-4243-9b98-697aea4a6cc5
ERROR: /Users/jhoward/git/patcher/services/svm/BUILD.bazel:61:8: //services/svm:go_default_test: no such attribute 'env' in 'go_transition_test' rule
ERROR: error loading package 'services/svm': Package 'services/svm' contains errors
INFO: Elapsed time: 31.567s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by v3n** [comment]
Apologies, I'm dumb and missed this part of the documentation:

> This attribute only applies to native rules, like cc_test, py_test, and sh_test. It does not apply to Starlark-defined test rules.

This is no longer a bug, but instead a feature request to support this.

**Comment by depthwise** [comment]
And also `env_inherit`. If your AWS creds are in `~/.aws/credentials`, your test won't be able to find them because `HOME` is stripped from env when the binary is run, which is how I stumbled upon this.

**Comment by gabrielrussoc** [comment]
Is there a fundamental reason why `go_test` rules don't have `env`. If not, I can take a stab

**Comment by linzhp** [comment]
It has been attempted before. See #7364, #1973, and https://github.com/bazelbuild/bazel/issues/7364. Long story short, it was hoped that Bazel would add `envs` attribute to all *_binary and *_test rules. They implemented, but later disabled it for all starlark rules. I guess we will have to implement it on our own in rules_go

**Comment by wondfor** [comment]
also no such attribute 'env' in '_native_test' rule
