### ISSUE TITLE
C++ flags set through command line configuration are ignored by rules_go cgo logic 

### ISSUE THREAD

**Issue by chancila** [bazelbuild/rules_go#2923]
master @ 24c3d41068c57d1ee7bf5774391285fd4ac5d189

### What version of gazelle are you using?

v0.23.0

### What version of Bazel are you using?

4.1 

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac/Linux x86_64

### Any other potentially useful information about your toolchain?

Custom clang 12 toolchain, verified normal cc compilation works fine on all relevant platforms.

### What did you do?
I have a global `--linkopt=/usr/bin/ld` set for my build in order to override the toolchain linker and cgo is not picking it up, causing linking issues. This uncovered an issue with the go rules where they seemingly ignore configuration set via `--copt`/`--linkopt` in general.

### What did you expect to see?
A successful build

### What did you see instead?
```
 (cd /Users/chancila/<REDACTED> && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/cc_toolchain/llvm/bin:/bin:/usr/bin \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/darwin-opt-exec-2B5CBBC6/bin/<REDACTED>-0.params' -- -extld external/cc_toolchain/llvm/bin/clang '-buildid=redacted' -extldflags '--sysroot=external/cc_toolchain/sysroots/macos_12_0_1_x86_64 --target=x86_64-apple-macos10.15 -fuse-ld=lld -mlinker-version=519 -Wl,-sdk_version,10.14')
```

the above command fails (due to issues with lld) however I have --linkopt set to use the system linker, if it would be properly picked up, the following modification works if I execute it manually, note `-fuse-ld=/usr/bin/ld'` at the end:

```
 (cd /Users/chancila/<REDACTED> && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/cc_toolchain/llvm/bin:/bin:/usr/bin \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/darwin-opt-exec-2B5CBBC6/bin/<REDACTED>-0.params' -- -extld external/cc_toolchain/llvm/bin/clang '-buildid=redacted' -extldflags '--sysroot=external/cc_toolchain/sysroots/macos_12_0_1_x86_64 --target=x86_64-apple-macos10.15 -fuse-ld=lld -mlinker-version=519 -Wl,-sdk_version,10.14 -fuse-ld=/usr/bin/ld')
```
```

**Comment by rmohr** [comment]
Seeing the same. With #2926 I can set the linker like expected.
