### ISSUE TITLE
Not able to pass importpath to protoc-gen-go

### ISSUE THREAD

**Issue by gandhikrishna** [bazelbuild/rules_go#2931]
### What version of rules_go are you using?

`v0.24.13`

### What version of gazelle are you using?

`v0.23.1`

### What version of Bazel are you using?

`3.7.0`

### Does this issue reproduce with the latest releases of all the above?

Reproduces with `v0.28.0`

### What operating system and processor architecture are you using?

macOS, amd64.

### What did you do?
With golang/protobuf v1.5.2 it is mandatory to have the Go package's import path. Either import path should be present in the proto file as:
`option go_package = "github.com/project/protos/foo";`

We can also specify the Go package's import path as param in protoc while generating go code as:
`protoc --go_out=. --go_opt=paths=source_relative foo.proto`

More info on go package’s import path: https://developers.google.com/protocol-buffers/docs/reference/go-generated#package

I am trying to pass the `importpath` via rules, this will ensure mapping of all `.proto` files to their Go import paths,
```
load("@io_bazel_rules_go//proto:compiler.bzl", "go_proto_compiler")

go_proto_library(
    name = "pb_go_proto",
    compilers = ["foo"],
    importpath = "github.com/foo/baz,
    proto = ":pb_proto",
    visibility = ["//visibility:public"],
    deps = [],
)


go_proto_compiler(
    name = "foo",
    options = GOGO_WELL_KNOWN_TYPE_REMAPS,
    visibility = ["//visibility:public"],
    import_path_option = True,
)
```

I am setting import_path_option as true, this should make sure `importpath` attribute from `go_proto_library` rules should be passed to the compiler on the command line. 

### What did you expect to see?

Generation of protobuf go-code without error.

### What did you see instead?

```
panic: invalid Go import path "runtime" for "github.com/foo/baz"

The import path must contain at least one forward slash ('/') character.
```

This is happening as importpath attribute is not being passed to protoc-gen-go at the time of compiling.

**Comment by blico** [comment]
It looks like the `import_path` option passed by `go_proto_compile` into `protoc` has been deprecated, likely explaining the no-op. A potential fix could be to update `go_proto_compile` to pass in the recommended `M${PROTO_FILE}=${GO_IMPORT_PATH}` options instead when `import_path_option` is set.

**Comment by robfig** [comment]
@gandhikrishna - would that solve your problem? 

@bazelbuild/go-maintainers - if `import_path_option` is not usable any longer, should we remove it?

**Comment by gandhikrishna** [comment]
@robfig turns out _v0.28.0_ release(latest) is compatible with _golang/protobuf v1.5.x_ https://github.com/bazelbuild/rules_go/releases/tag/v0.28.0 (release notes). And this release makes sure to pass `import_path` attribute to protoc at the time of compiling and hence the issue of specifying the full import path in proto files is not needed. We can close this ticket as the functionality is provided with the latest release.
