### ISSUE TITLE
Failing to use `com_google_cloud_go_logging` without patching proto target name

### ISSUE THREAD

**Issue by freddd** [bazelbuild/rules_go#2938]
### What version of rules_go are you using?

v0.27.0

### What version of gazelle are you using?

d038863ba2e096792c6bb6afca31f6514f1aeecd

### What version of Bazel are you using?

4.1.0

### What did you do?

1) Run `go get -u cloud.google.com/go/logging`
2) Try to use `@com_google_cloud_go_logging//:logging`

Example BUILD.bazel:
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "main",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_cloud_go_logging//:logging"],
)
```
It fails with the following error message:
```
external/com_google_cloud_go_logging/BUILD.bazel:3:11: no such target ‘@go_googleapis//google/logging/type:ltype_go_proto’: target ‘ltype_go_proto’ not declared in package ‘google/logging/type’ (did you mean ‘type_go_proto’?)
```

It's also worth mentioning that we are using this version of `go_googleapis` (we've tried with the latest master as well):
```
http_archive(
    name = "go_googleapis",
    sha256 = "8a52b16b96eacc99f064fdb1518883f0ec6329c7e6c5845338d88b935a284546",
    strip_prefix = "googleapis-9a9e29627a715077cd8e33c0d2bd549437039bd0",
    # master, as of 2021-04-15
    urls = [
        "https://github.com/googleapis/googleapis/archive/9a9e29627a715077cd8e33c0d2bd549437039bd0.zip",
    ],
)
```

### What did you expect to see?

I expected the library to be built successfully when running `bazel build :main`. We fixed it internally for now by using a patch that does the following change:
```
@@ -17,7 +17,7 @@ go_library(
         "@com_google_cloud_go//compute/metadata",
         "@com_google_cloud_go//internal/version",
         "@go_googleapis//google/api:monitoredres_go_proto",
-        "@go_googleapis//google/logging/type:ltype_go_proto",
+        "@go_googleapis//google/logging/type:type_go_proto",
         "@go_googleapis//google/logging/v2:logging_go_proto",
         "@io_bazel_rules_go//proto/wkt:struct_go_proto",
         "@org_golang_google_api//option",
-- 
```

### What did you see instead?

It fails with the following error message:
```
external/com_google_cloud_go_logging/BUILD.bazel:3:11: no such target ‘@go_googleapis//google/logging/type:ltype_go_proto’: target ‘ltype_go_proto’ not declared in package ‘google/logging/type’ (did you mean ‘type_go_proto’?)
```

**Comment by robfig** [comment]
Sorry for the long delay in looking at this. 

I tried to reproduce the problem, but this library works for me:
https://github.com/robfig/rules_go_cloud_logging

I never got the same error you did, but I did find that an older version of protocolbuffers resulted in issues.
