### ISSUE TITLE
io_bazel_rules_go not working with Bazel 4.2.0. Which version to be used ?

### ISSUE THREAD

**Issue by uajith** [bazelbuild/rules_go#2945]
### What version of rules_go are you using?

v0.22.2

### What version of gazelle are you using?

0.18.2

### What version of Bazel are you using?

4.2.0

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
Ubuntu 20.04.2

### What did you do?
While building the target, we are getting this error
```

ERROR: /home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel:3:16: in go_tool_library rule @io_bazel_rules_go//go/tools/coverdata:coverdata: 
Traceback (most recent call last):
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/private/rules/library.bzl", line 42, column 25, in _go_library_impl
		archive = go.archive(go, source)
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 219, column 29, in emit_archive
		cgo_exports = sets.union(cgo_exports, *[a.cgo_exports for a in direct])
	File "/home/ajithu/.cache/bazel/_bazel_ajithu/64f281071d7b4d7bf8c57a82ac06e780/external/bazel_skylib/lib/new_sets.bzl", line 189, column 42, in _union
		return struct(_values = dicts.add(*[s._values for s in args]))
Error: 'list' value has no field or method '_values'
ERROR: Analysis of target '//tools/cedp_ci:cedp_ci' failed; build aborted: Analysis of target '@io_bazel_rules_go//go/tools/coverdata:coverdata' failed
INFO: Elapsed time: 60.147s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (73 packages loaded, 6636 targets configured)


```

### What did you expect to see?
Expecting to complete the build

### What did you see instead?
Getting this error: 
Error: 'list' value has no field or method '_values'

I am not sure which is the correct version of bazel gazelle  and io_rules_go  for bazel 4.2.0

**Comment by steeve** [comment]
Can you make a sample project or give us the bazel options? it seems you are using coverage?

**Comment by uajith** [comment]
Yes. I am using coverage.
While building the target, I am getting the error

`$ bazel build //tools/cedp_ci:cedp_ci
`

On Bazel 3.2.0 I am able to build the above target. 
There I am using version **0.19.3** of **io_bazel_rules_go**

**Comment by robfig** [comment]
It looks like the error happens in skylib. Can you try upgrading that to latest? 

I successfully used Bazel 4.2 with the latest version of rules_go (0.28), so upgrading rules_go might also be something to try.

**Comment by uajith** [comment]
ok fine it worked in 4.2
