### ISSUE TITLE
in go_context_data rule @io_bazel_rules_go//:go_context_data: cycle in dependency graph:

### ISSUE THREAD

**Issue by filmil** [bazelbuild/rules_go#2963]
### What version of rules_go are you using?

`8e968b5fcea1d2d64071872b12737bbb5514524ee5f0a4f54f5920266c261acb`

### What version of gazelle are you using?

`62ca106be173579c0a167deb23358fdfe71ffa1e4cfdddf5582af26520f1c66f`

### What version of Bazel are you using?

Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667

### What operating system and processor architecture are you using?

Linux, amd64

### Any other potentially useful information about your toolchain?

No

### What did you do?

Tried to initialize a repository with the go toolchain.

### What did you expect to see?

I expected it to work.

### What did you see instead?

Circular dependency in the tools:

```
ERROR: /home/fmil/.cache/bazel/_bazel_fmil/0da78383745ae41c0b1c7d4a32903934/external/io_bazel_rules_go/BUILD.bazel:73:16: in go_context_data rule @io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //:gazelle
    //:gazelle-runner
    @bazel_gazelle//cmd/gazelle:gazelle
    @bazel_gazelle//language/proto:go_default_library
    @bazel_gazelle//language/proto:proto
    @bazel_gazelle//pathtools:pathtools
.-> @io_bazel_rules_go//:go_context_data
|   @io_bazel_rules_nogo//:nogo
|   @io_bazel_rules_go//:default_nogo
|   @io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @org_golang_x_tools//go/analysis/internal/facts:go_tool_library
|   @org_golang_x_tools//go/analysis:go_tool_library
|   @org_golang_x_tools//internal/analysisinternal:go_tool_library
|   @org_golang_x_tools//go/ast/astutil:go_tool_library
|   @org_golang_x_tools//internal/typeparams:typeparams
`-- @io_bazel_rules_go//:go_context_data
```

**Comment by filmil** [comment]
FWIW using the commit that is at the current ToT removes the error.

```
git_repository(                                                                                                                     
    name = "io_bazel_rules_go",                                                                                                     
    remote = "https://github.com/bazelbuild/rules_go",                                                                              
    commit = "a00b47cd24b3bb855fcf8e1ac4842538f92ad450",                                                                            
    shallow_since = "1632498172 -0400",                                                                                             
)                                      
```

**Comment by robfig** [comment]
Perhaps there's an incompatibility between specific versions of gazelle & rules_go. Does this reproduce using the latest released versions, as shown in the "getting started" snippet here?
https://github.com/bazelbuild/bazel-gazelle/#running-gazelle-with-bazel

**Comment by filmil** [comment]
I took `gazelle` and`rules_go` from what's described at this page https://github.com/bazelbuild/rules_go#generating-build-files.

For reference:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "8e968b5fcea1d2d64071872b12737bbb5514524ee5f0a4f54f5920266c261acb",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.28.0/rules_go-v0.28.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.28.0/rules_go-v0.28.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "62ca106be173579c0a167deb23358fdfe71ffa1e4cfdddf5582af26520f1c66f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.23.0/bazel-gazelle-v0.23.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.17")

gazelle_dependencies()
```

**Comment by robfig** [comment]
I'm not sure what it could be, but maybe it's not important to get to the bottom of since it sounds like it's fixed at HEAD and we are intending to cut a release soon. If you'd like me to investigate, can you provide a reproducer repo along with a command to run? 

I have this repo which I made the other day using those exact versions of the tools, and it works fine for me. 
https://github.com/robfig/rules_go_cloud_logging

**Comment by filmil** [comment]
Frankly I'm happy that there is an easy workaround - as long as someone can search for the error string and hit this issue, they will see what to do. That's enough for me.

**Comment by robfig** [comment]
Sounds good, will keep an eye out to see if this error message comes up in the future. Thanks for reporting!
