### ISSUE TITLE
go tip changes signature of testing.MainStart, will fail with go1.18

### ISSUE THREAD

**Issue by HALtheWise** [bazelbuild/rules_go#2964]
I'm using rules_go with an unreleased tip version of go, because I want generics support that won't be released until `1.18`. In the process, I ran into an issue with `go_test()` with go tip, seemingly because there was a change to the `testing.MainStart` function, which is _explicitly_ [excluded](https://pkg.go.dev/testing#MainStart) from the go1 compatability garuntee.

Since `rules_go` does not promise compatability with unreleased go versions, this isn't _technically_ a bug yet, but I figured people might want to hear about it ahead of time so that `rules_go` can have a fix released before the next go version gets out.

### What version of rules_go are you using?

Tip @ commit `9f77676a87f23c7d5963bb9aef91f07398706809`

### What version of go are you using?

Tip @ commit `c894b442d1e5e150ad33fa3ce13dbfab1c037b3a` (to become `1.18`)

### What version of gazelle are you using?

`0.23.0`

### What version of Bazel are you using?

`4.0.0`

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

x86 Linux

### What did you do?

This issue reproduces with all `go_test` rules I've tried, presumably it is universal.

### What did you expect to see?

Tests succeed

### What did you see instead?

```
bazel-out/k8-fastbuild/bin/internal/task/task_test_/testmain.go:75:7: not enough arguments in call to testing.MainStart
```

**Comment by HALtheWise** [comment]
This seems to be an issue

**Comment by robfig** [comment]
I believe this is fixed by https://github.com/bazelbuild/rules_go/commit/f1019ef4c2c22d6ca78257084a9da47e15fc415d

**Comment by robfig** [comment]
Closing, since we believe this to be fixed.
