### ISSUE TITLE
CGO static library cannot find

### ISSUE THREAD

**Issue by Icemap** [bazelbuild/rules_go#2965]
### What version of rules_go are you using?
0.28.0

### What version of gazelle are you using?
0.23.0

### What version of Bazel are you using?
4.2.1

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
CentOS7 x86_64

### Any other potentially useful information about your toolchain?
C/C++ complier: GCC 4.8.5 20150623 (Red Hat 4.8.5-5) (GCC)

### What did you do?

I have written a Golang program that depends on a library.
And this library is developed using CGO and it has a static library(lib***.a).
When I use ```bazel build ...``` will get a error `/usr/bin/ld: cannot find -l***` when compiling, while using ```go build``` everything works fine.
I put the minimal recipe for reproducing the error on "https://github.com/Icemap/test_cgo_with_static_lib", you can use ```./recurrent.sh``` to get this error.

### What did you expect to see?

no errors

### What did you see instead?
```log
[qizhiwang@VM-238-235-centos test_cgo_with_static_lib]$ ./recurrent.sh 
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 47299df6f0166ee1658fcd04d7e5db43a6b537d18f7886121ad7de9598371be1
DEBUG: /data/home/qizhiwang/.cache/bazel/_bazel_qizhiwang/b29454d10666e768866d12b93fa8a857/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: CC with -fuse-ld=gold returned 0, but its -v output didn't contain 'gold', falling back to the default linker.
INFO: Analyzed 2 targets (39 packages loaded, 7809 targets configured).
INFO: Found 2 targets...
ERROR: /data/home/qizhiwang/.cache/bazel/_bazel_qizhiwang/b29454d10666e768866d12b93fa8a857/external/com_github_icemap_test_cgo_with_static_lib_gowapper/BUILD.bazel:10:11: GoCompilePkg external/com_github_icemap_test_cgo_with_static_lib_gowapper/gowapper.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_icemap_test_cgo_with_static_lib_gowapper/wapper.go -importpath ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld: cannot find -ltest_calc
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
INFO: Elapsed time: 11.454s, Critical Path: 1.54s
INFO: 7 processes: 5 internal, 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by robfig** [comment]
Thank you for the reproducer! 

This works if you delete the `clinkopts` attribute. I think the reasoning is that `cdeps` includes the static library in the resulting binary directly, but that library is not in a search path so when it's requested by `-ltest_calc`, it can't be found. Let me know if this doesn't solve your problem.
