### ISSUE TITLE
Help: how to configure WORKSPACE working like 'go mod replace' 

### ISSUE THREAD

**Issue by hitzhangjie** [bazelbuild/rules_go#2966]
Hi, I have a project managed by 'go module' before. 

I want to try 'bazel', now there's a problem to be solved, there's a 'go mod replace' directive in my go.mod:

`replace github.com/xxx => stub/github.com/xxx`,

How do I configure WORKSPACE to let it work? I am a newbie to bazel. Please Help! Thanks!

I think I should use `local_repository`, but I don't know how to write it properly.

**Comment by robfig** [comment]
Hi, welcome to bazel! 

There are two ways to do this, depending on whether you want to replace using a local path or a remote fork:

1. Local path - use `local_repository`:
 ```
 local_repository(
   name = "com_github_xxx",
   path = "/Users/hitzhangjie/path/to/github.com/xxx",
 )
 ```
2. Remote fork - use `go_repository` attribute `replace`:
 ```
 go_repository(
   name = "com_github_xxx",
   importpath = "github.com/xxx",
   replace = "github.com/fork_xxx",
   commit = "abc123",
)   
 ```

Feel free to reopen if you have further questions or if that doesn't work for you. 
Cheers,
Rob
