### ISSUE TITLE
reproducibility_test hardcodes the "host" output dir

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_go#2967]
Testing rules_go against https://github.com/bazelbuild/bazel/pull/14049 (which enables the toolchain transition globally), there is a failure in reproducibility_test (https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/ee4684ae-24f9-48bc-b094-0fa33588180e/tests/integration/reproducibility/reproducibility_test/attempt_1.log):

```
    reproducibility_test.go:226: open /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2d3ef5fd1c1b57796f35d5cea92c0a3f/bazel_testing/bazel_go_test/main0/bazel-out/host/bin/external/go_sdk/builder: no such file or directory
FAIL
```

The cause of the error seems to be the hard-coded "host" in the output path. When this change reaches Bazel head, the test will begin failing until this can be fixed.

**Comment by robfig** [comment]
Thanks for the heads up. 

It seems that output paths are no longer predictable. Is there a recommendation for how to access the build artifact?

**Comment by meteorcloudy** [comment]
Does `$workspace_root/bazel-bin/external/go_sdk/builder` work?

**Comment by katre** [comment]
You can save the build event messages and check them: https://docs.bazel.build/versions/main/build-event-protocol.html

**Comment by robfig** [comment]
Confirmed working https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2277#9ff111ee-6b1b-4494-af4e-1e7260ecbe61
