### ISSUE TITLE
Create a rules_go release removing dependency from rules_cc

### ISSUE THREAD

**Issue by limdor** [bazelbuild/rules_go#2975]
Hi,

I would like to request a new release that contains the change removing the dependency from rules_cc.
The dependency to rules_cc has been removed in https://github.com/bazelbuild/rules_go/issues/2949
However there is no release that contains that change.
We could of course use a version from master but it is hard to say what is a good commit and in general we want to avoid that.

Thanks

**Comment by robfig** [comment]
Hi, I began working on a release yesterday, but it got held up with test failures resulting from updating dependencies to latest. I will continue to work on it and would expect a release to be out by the end of the week. Thanks

**Comment by limdor** [comment]
These are great news, thanks!

**Comment by robfig** [comment]
FYI v0.29.0 is live!
https://github.com/bazelbuild/rules_go/releases/tag/v0.29.0
