### ISSUE TITLE
nogo build-time code analysis in v0.29.0 (worked in v0.28.0)

### ISSUE THREAD

**Issue by mishas** [bazelbuild/rules_go#2983]
### What version of rules_go are you using?

v0.29.0
(Problem doesn't exist in v0.28.0)

### What version of gazelle are you using?

Tried with v0.23.0 and master.

### What version of Bazel are you using?

v4.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes, but works fine in v0.28.0 of rules_go

### What operating system and processor architecture are you using?

Linux and MacOS (both amd64)

### Any other potentially useful information about your toolchain?

Nope

### What did you do?

Full demo here: https://github.com/mishas/bazel-cross-compile-rebuild/tree/example/nogo
Failed build here: https://github.com/mishas/bazel-cross-compile-rebuild/runs/3854490570?check_suite_focus=true

1. Create an empty project that depends on `golang.org/x/tools` directly or indirectly.
2. Configure gazelle to load `go_repositories` before `go_rules_dependencies` (as described [here](https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies) for example). This is important in our case, as we sometimes need newer version of libraries than the newest rules_go currently brings.
3. Setup nogo build-time code analysis (with vet in my case), as described [here](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst#running-vet).

### What did you expect to see?

Everything to work fine, just like it did with rules_go v0.28.0

### What did you see instead?

Error:
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/48e68a0f17482eeca983c1a927fd4186/external/io_bazel_rules_go/go/tools/builders/BUILD.bazel:52:10: in go_source rule @io_bazel_rules_go//go/tools/builders:nogo_srcs: alias '@org_golang_x_tools//go/analysis/internal/facts:go_default_library' referring to target '@org_golang_x_tools//go/analysis/internal/facts:facts' is not visible from target '@io_bazel_rules_go//go/tools/builders:nogo_srcs'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//pkg/demo:demo' failed; build aborted: Analysis of target '@io_bazel_rules_go//go/tools/builders:nogo_srcs' failed
```

**Comment by robfig** [comment]
I think that https://github.com/bazelbuild/bazel-gazelle/pull/1113 will fix it.
