### ISSUE TITLE
mirror.bazel.build links in go/private/repositories.bzl are not valid

### ISSUE THREAD

**Issue by bizrad** [bazelbuild/rules_go#2985]
### What version of rules_go are you using?

0.29.0

### What version of gazelle are you using?

0.24.0

### What version of Bazel are you using?

4.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS Catalina Intel i9

### What did you do?

When running bazel build or gazelle update commands it appears these mirror links are no longer working. The other links appear to be satisfying the build needs.

### What did you expect to see?

No Warnings or 404 errors fetching files

### What did you see instead?

WARNING: Download from https://mirror.bazel.build/github.com/googleapis/go-genproto/archive/c76a74d43a8eff9efc7832aa92c6a61ce42c8101.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

WARNING: Download from https://mirror.bazel.build/github.com/golang/tools/archive/v0.1.7.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

WARNING: Download from https://mirror.bazel.build/github.com/golang/sys/archive/2c5d950f24efcc95bc256be158532a2eee20542f.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

This file in repositories.bzl is also missing from the mirror
https://mirror.bazel.build/github.com/googleapis/googleapis/archive/409e134ffaacc243052b08e6fb8e2d458014ed37.zip

### Check/reproduce
Pull HEAD of main
```
$ cd rules_go/go/private 
$ for i in `grep "mirror.bazel" repositories.bzl | tr -d '"' | tr -d ','`;do wget -O /dev/null -q $i || echo "Missing: $i";done
```

**Comment by jayconrod** [comment]
All uploaded now.

**Comment by jacobbogdanov** [comment]
@jayconrod I'm seeing this same issue when using `rules_go` v0.30.0
```
...
WARNING: Download from https://mirror.bazel.build/github.com/golang/tools/archive/v0.1.8.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

...
WARNING: Download from https://mirror.bazel.build/github.com/golang/sys/archive/da31bd327af904dd4721b4eefa7c505bb3afd214.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```
Here's one of the offending mirrors; https://github.com/bazelbuild/rules_go/blob/v0.30.0/go/private/repositories.bzl#L102
