### ISSUE TITLE
Missing types when building com_github_prometheus_common

### ISSUE THREAD

**Issue by tyen-brex** [bazelbuild/rules_go#2998]
### What version of rules_go are you using?

v0.29.0

### What version of gazelle are you using?

v0.24.0

### What version of Bazel are you using?

4.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

OSX 10.5 Intel

### Any other potentially useful information about your toolchain?

go_repository contains these dependencies, and a Go program depends on them

```
    go_repository(
        name = "com_github_prometheus_client_golang",
        importpath = "github.com/prometheus/client_golang",
        sum = "h1:HNkLOAEQMIDv/K+04rukrLx6ch7msSRwf3/SASFAGtQ=",
        version = "v1.11.0",
    )
    go_repository(
        name = "com_github_prometheus_client_model",
        importpath = "github.com/prometheus/client_model",
        sum = "h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=",
        version = "v0.2.0",
    )
    go_repository(
        name = "com_github_prometheus_common",
        importpath = "github.com/prometheus/common",
        sum = "h1:iMAkS2TDoNWnKM+Kopnx/8tnEStIfpYA0ur0xQzzhMQ=",
        version = "v0.26.0",
    )

```

### What did you do?

1. Upgraded bazel_rules_go `v0.27.0` to `v0.29.0` and bazel_gazelle `v0.23.0` to `v0.24.0`. I did not change any existing `go_repository`s
2. Ran `bazel build` on a `go_binary` target

### What did you expect to see?

No build errors

### What did you see instead?

```
external/com_github_prometheus_common/expfmt/openmetrics_create.go:171:19: metric.Counter.Exemplar undefined (type *io_prometheus_client.Counter has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:239:7: b.Exemplar undefined (type *io_prometheus_client.Bucket has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:305:12: undefined: io_prometheus_client.Exemplar
external/com_github_prometheus_common/expfmt/openmetrics_create.go:448:41: undefined: io_prometheus_client.Exemplar
```

**Comment by amalucelli** [comment]
@tyen-brex I opened a similar issue here https://github.com/bazelbuild/bazel-gazelle/issues/1140, as I only got the error when I upgraded the `gazelle` to latest.

**Comment by tyen-brex** [comment]
https://github.com/bazelbuild/bazel-gazelle/issues/1140 has the solution
