### ISSUE TITLE
Can't easily configure differing host and remote execution SDKs

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_go#3007]
### What version of rules_go are you using?

0.29.0

### What version of gazelle are you using?

0.24.0

### What version of Bazel are you using?

5.0.0rc1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS 11.6.1, arm64

### What did you do?

I'm running a bazel build on an arm64 Mac, but targeting an x86 remote execution platform. I need the SDK to be the `darwin-amd64` version, but since the repository rule detects the architecture with `uname -m`,`go_download_sdk` downloads the `darwin-arm64` version. If I use `go_download_sdk` to download the `darwin-amd64` version, I also have to call it explicitly for every other platform I support (e.g. linux). In addition, because I call it multiple times, it downloads all of the SDKs, even if they aren't used.

**Comment by nacl** [comment]
Also seeing a variant of this with HEAD rules_go and Bazel 5.2.0.  When I provide an explicit URL for `go_download_sdk`, rules_go seems to ignore the URL and download the SDK for the host architecture.

The OS autodetection feature can be worked around by explicitly providing `goos` and `goarch` to `go_download_sdk`, assuming that's what you are using, of course.

And as for everything being downloaded, you're probably seeing #3196.

**Comment by nacl** [comment]
I've also seen cases where `goos` and `goarch` end up being unset or empty in the generated BUILD files for SDKs in our configuration -- it might be an issue with `native.existing_rules`, as we have our golang toolchains configured in a separate repository from the one bazel is invoked from.

**Comment by achew22** [comment]
Strongly agree. Having our toolchains defined via flags is almost certainly the correct way for us to go.
