### ISSUE TITLE
go/tools/coverdata: multiple copies of package passed to linker

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#3017]
### What version of rules_go are you using?

v0.29.0

### What version of gazelle are you using?

Not using Gazelle

### What version of Bazel are you using?

4.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS arm64 and Linux amd64

### What did you do?

1. Create a workspace like this:

```
-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "2b1641428dff9018f9e85c0384f03ec6c10660d935b750e3fa1492a281a53b0f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.17.1")
-- fx.go --
package fx

import (
	_ "uber.com/internal"
)
-- fx_test.go --
package fx
-- internal/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["lib.go"],
    importpath = "uber.com/internal",
    visibility = ["//visibility:public"],
    deps = ["@io_bazel_rules_go//go/tools/coverdata"],
)

go_test(
    name = "go_default_test",
    srcs = ["lib_test.go"],
    embed = [":go_default_library"],
)
-- internal/lib.go --
package internal

import _ "github.com/bazelbuild/rules_go/go/tools/coverdata"
-- internal/lib_test.go --
package internal
-- BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["fx.go"],
    importpath = "code.uber.internal/devexp/code-coverage/cmd/fx",
    visibility = ["//visibility:private"],
    deps = ["//internal:go_default_library"],
)

go_test(
    name = "go_default_test",
    srcs = ["fx_test.go"],
    embed = [":go_default_library"],
)
```
2. Run `bazel build --collect_code_coverage //:go_default_test` or `bazel coverage //:go_default_test`

### What did you expect to see?

Build succeeds

### What did you see instead?

```
link: package conflict error: github.com/bazelbuild/rules_go/go/tools/coverdata: multiple copies of package passed to linker:
	@io_bazel_rules_go//go/tools/coverdata:coverdata
	@io_bazel_rules_go//go/tools/coverdata:coverdata
Set "importmap" to different paths or use 'bazel cquery' to ensure only one
package with this path is linked.
Target //:go_default_test failed to build
```

Interestingly, `bazel coverage //internal:go_default_test` succeeded, even it's the package that imports "github.com/bazelbuild/rules_go/go/tools/coverdata"

**Comment by linzhp** [comment]
Running `bazel build -s --collect_code_coverage //:go_default_test`, there is indeed two copies of `coverdata`:

```
-arc '@io_bazel_rules_go//go/tools/coverdata:coverdata=github.com/bazelbuild/rules_go/go/tools/coverdata=bazel-out/darwin_arm64-fastbuild/bin/external/io_bazel_rules_go/go/tools/coverdata/coverdata.a'
-arc '@io_bazel_rules_go//go/tools/coverdata:coverdata=github.com/bazelbuild/rules_go/go/tools/coverdata=bazel-out/darwin_arm64-fastbuild-ST-8f6eb6207b9d/bin/external/io_bazel_rules_go/go/tools/coverdata/coverdata.a'
```

Where is the second copy from?

**Comment by robfig** [comment]
Any idea what the "*-ST-8f6eb6207b9d" build configuration means? I wonder if that's something to differentiate the pre/post transition of the nogo config setting. That would explain why this only showed up now.

It looks like the coverdata package is added explicitly as a dep in a few places:
go/private/actions/compilepkg.bzl
go/private/actions/link.bzl
go/private/rules/test.bzl

My guess is that it is added more times than necessary, and it was previously de-duped by the depset and didn't cause a problem.

**Comment by linzhp** [comment]
I think "*-ST-8f6eb6207b9d" build may be the one rules_go uses to build the instrumented code. The other build is to build the one imported by `internal/lib.go`.

**Comment by robfig** [comment]
I'm not too sure what the best solution is here, but please give https://github.com/bazelbuild/rules_go/commit/c7ce4fd99f8ef49cc3d170dc53e774ee3bfca64f a try in your repo. Let me know if it prints any warnings about ignoring other duplicate archives.

**Comment by linzhp** [comment]
We can also think about whether to let packages outside rules_go import `github.com/bazelbuild/rules_go/go/tools/coverdata`. In the comment, it says:

> // This package is part of the Bazel Go rules, and its interface
> // should not be considered public. It may change without notice.
