### ISSUE TITLE
Extra newline required after `# gazelle:ignore`.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_go#302]
The gazelle [documentation](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle) does not indicate that a newline is required after the directive `# gazelle:ignore`. I assumed I didn't have the right version of gazelle installed.  It's only by chance that I added an extra newline while trying to figure out what was  going wrong.

**Comment by pmbethe09** [comment]
Feel free to update the documentation where appropriate!  Send the PR to me.

**Comment by jayconrod** [comment]
@hsyed, could you post part of your BUILD file where the directive isn't working? I'm guessing it's something like this, but please confirm:

```bzl
# gazelle:ignore -- no blank line before rule
go_binary(
    name = "hello",
    srcs = ["hello.go"],
)
```

It looks like Gazelle is scanning comments *after* top level statements but not before. The buildifier parser used by Gazelle puts the block of comments at the top of the file in the *after* section of an implicit empty statement. If there's no blank line before the first statement, those comments will be parsed as before the first statement, and Gazelle won't notice them.

Agreed this is weird behavior. I'll put together a PR to fix it and update the documentation.

**Comment by hsyed** [comment]
@jayconrod it's actually the first line in [this file](https://gist.github.com/hsyed/c4736a6bebb235f7a782db153192099f). I'm sure I did try moving the comments around a bit.

Since you are going to look at the file. is this still the prescribed way to ensure things build on different platforms ? -- I am building in a docker container and on a mac.

**Comment by jayconrod** [comment]
Thanks for sharing that file. This confirms what the problem is.

`select` is definitely the right way to choose different files for different platforms. You can eliminate some redundancy by adding the result of the `select` function to a list of common files.

```bzl
go_library(
    name = "go_default_library",
    srcs = select({
        ":darwin": [
            ...
        ],
        "//conditions:default": [
            ...
        ],
    }) + [
        "alt_exit.go",
        "doc.go",
        ...
    ],
    visibility = ["//visibility:public"],
)
```
