### ISSUE TITLE
Bazel CI: //tests/integration/reproducibility:reproducibility_test broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_go#3024]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2268#cf713d45-245a-437a-bb0f-85a10498d523
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tests/integration/reproducibility:reproducibility_test
-----------------------------------------------------------------------------
--- FAIL: Test (35.40s)
    reproducibility_test.go:226: open /private/var/tmp/_bazel_buildkite/151f56892d8b39575ff82475bb0e1262/bazel_testing/bazel_go_test/main0/bazel-out/host/bin/external/go_sdk/builder: no such file or directory
FAIL
```

A bisect points to https://github.com/bazelbuild/bazel/commit/4b47d6f849bb2eca669f48cfdb5d1796100920f3, which looks like  an intentional change.

**Comment by meteorcloudy** [comment]
FYI @katre

**Comment by meteorcloudy** [comment]
@robfig Can you also take a look at this?
To reproduce
```
export USE_BAZEL_VERSION=4b47d6f849bb2eca669f48cfdb5d1796100920f3
bazelisk test //tests/integration/reproducibility:reproducibility_test
```

**Comment by katre** [comment]
See #2967, this is known and needs to be fixed in rules_go's tests.

**Comment by meteorcloudy** [comment]
@katre Thanks!

@robfig @jayconrod If this isn't going to be fixed soon, can you disable the test to make downstream green again?
