### ISSUE TITLE
Feature: go_embed_data

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#304]
rules_go needs a rule for code-generating a file contents as data inside a package, e.g.

go_embed_data(
    name = "gen_script",
    src = "//usefule:script.py",
    out = "script.py.go",
    package = "server",
    var = "ScriptData",
)

AND, gazelle should parse and respect this (means a file "script.py.go" in srcs of "go_default_library")

**Comment by jayconrod** [comment]
So would this create script.py.go with the contents of "script.py" inside a []byte var named ScriptData? Or is "script.py" executed and the output embedded?

Both interpretations seem useful, but it would be good if we could generalize. Seems like we could produce the .go file with a genrule, then reference the label in srcs of go_default_library with "# keep". Maybe Gazelle should keep labels referenced in srcs automatically. WDYT?

**Comment by jayconrod** [comment]
@alandonovan pointed out to me there is a Google-internal macro that does exactly this. So we will match compatibility with that.

**Comment by pmbethe09** [comment]
Yes, it seems fairly useful, and I had a request from an internal team for this in rules_go
