### ISSUE TITLE
Using -extldflags in gc_linkopts gets ignored by go tool link

### ISSUE THREAD

**Issue by toby-jazz** [bazelbuild/rules_go#305]
Related to #217 and #161 
When passing `-extldflags` with `gc_linkopts`:
```
go_binary(
    name = "foo",
    srcs = ["foo.go"],
    gc_linkopts = [
        "-extldflags \"-static\"",
    ],
)
```
the -extldflags gets added to `go tool link` twice due to `_emit_go_link_action` (https://github.com/bazelbuild/rules_go/blob/master/go/def.bzl#L442).
It looks like `go tool link` then only uses the second set of flags, meaning the flags passed in through `gc_linkopts` are ignored.
Ideally these flags should be merged so that only one `-extldflags` is emitted.

**Comment by sumitd2** [comment]
Hi team, I have the same issue with v0.37.0, please help:
```
go_binary(
    name = "cockroach",
    embed = [":cockroach_lib"],cgo = True,gc_linkopts = ["-extldflags=-lkeyutils"],
    visibility = ["//visibility:public"],
)

bazel-out/ppc-opt-exec-2B5CBBC6/bin/external/go_sdk/builder '-param=bazel-out/ppc-fastbuild/bin/pkg/cmd/cockroach/cockroach_/cockroach-0.params' -- -extld /usr/bin/gcc '-extldflags=-lkeyutils' '-buildid=redacted' -extldflags '-fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -lm')

```

**Comment by fmeum** [comment]
@sumitd2 Could you try `gc_linkopts = ["-extldflags", "-lkeyutils"]`?
