### ISSUE TITLE
package conflict error related to WKT ptypes/any:any

### ISSUE THREAD

**Issue by mmellin** [bazelbuild/rules_go#3052]
### What version of rules_go are you using?
v0.29.0

### What version of gazelle are you using?
v0.24.0

### What version of Bazel are you using?
4.2.2

### Does this issue reproduce with the latest releases of all the above?
n/a

### What operating system and processor architecture are you using?
Linux Ubuntu 20.04 64-bit VM

### Any other potentially useful information about your toolchain?
- I am leveraging Gazelle and `rules_go` from the `rules_proto_grpc` rule (v4.1.1) as instructed from their [docs](https://rules-proto-grpc.com/en/latest/lang/go.html).
- I am using Gazelle to create a `go_repositories.bzl` file which contain my deps from `go.mod`. I load this after `go_rules_dependencies()` and before `gazelle_dependencies()`.
- I am using `go_proto_library` rules in my BUILD files, but we do not use Gazelle to autocreate them. We set `#gazelle:ignore` on all of them and set  the main directive to `# gazelle: proto disable_global`.
- I set `build_file_proto_mode: disable_global` on nearly all rules in `go_repositories.bzl` expect for a select few which may require different settings, like `org_golang_google_grpc` set to `disable`.

### What did you do?
I am building a target of mine which contains many deps, internal and 3rd party. Some utilize `*.proto` files for protobuf and gRPC.  I receive build errors no matter what I try, so any help/guidance is appreciated. 

```
$ bazel build -k //engprod/cli:atom
Starting local Bazel server and connecting to it...
(01:52:12) INFO: Current date is 2022-01-20
```

I have looked through many issue cases and read through many docs such as:
- https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#go_rules_dependencies
- https://github.com/bazelbuild/rules_go/tree/v0.29.0#protobuf-and-grpc
- https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies
- etc

I've tried to utilize `bazel cquery` to view the chain, but I'm a bit confused at the output. Both are identical up to the last 3 lines.

```
$ bazel cquery 'somepath(//engprod/cli:atom, @com_github_golang_protobuf//ptypes/any:any)' 
(02:02:03) INFO: Current date is 2022-01-20
(02:02:03) INFO: Build options --action_env and --test_env have changed, discarding analysis cache.
(02:02:06) INFO: Analyzed 2 targets (780 packages loaded, 13589 targets configured).
(02:02:06) INFO: Found 2 targets...
//engprod/cli:atom (3560f85)
//engprod/cli:go_default_library (3560f85)
//engprod/cli/commands:go_default_library (3560f85)
//engprod/cli/commands/container:go_default_library (3560f85)
//engprod/cli/commands/container/inventory:go_default_library (3560f85)
//build/inventory/processor:go_default_library (3560f85)
//build/inventory/collectors/docker:go_default_library (3560f85)
@com_github_googlecontainertools_container_diff//util:go_default_library (3560f85)
@com_github_googlecontainertools_container_diff//util:util (3560f85)
@com_github_googlecontainertools_container_diff//pkg/util:util (3560f85)
@com_github_google_go_containerregistry//pkg/v1/daemon:daemon (3560f85)
@com_github_docker_docker//api/types:types (3560f85)
@com_github_docker_docker//api/types/network:network (3560f85)
@com_github_docker_docker//errdefs:errdefs (3560f85)
@org_golang_google_grpc//status:status (3560f85)
@org_golang_google_grpc//internal/status:status (3560f85)
@com_github_golang_protobuf//ptypes:go_default_library_gen (3560f85)
@io_bazel_rules_go//proto/wkt:any_go_proto (3560f85)
@io_bazel_rules_go//proto/wkt:any_wrapper (3560f85)
@com_github_golang_protobuf//ptypes/any:go_default_library (3560f85)
@com_github_golang_protobuf//ptypes/any:any (3560f85)
(02:02:06) INFO: Elapsed time: 3.584s
(02:02:06) INFO: 0 processes.
(02:02:06) INFO: Build completed successfully, 0 total actions
```
and 
```
$ bazel cquery 'somepath(//engprod/cli:atom, @io_bazel_rules_go//proto/wkt:any_go_proto)' 
(02:02:54) INFO: Current date is 2022-01-20
(02:02:54) INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
(02:02:54) INFO: Found 2 targets...
//engprod/cli:atom (3560f85)
//engprod/cli:go_default_library (3560f85)
//engprod/cli/commands:go_default_library (3560f85)
//engprod/cli/commands/container:go_default_library (3560f85)
//engprod/cli/commands/container/inventory:go_default_library (3560f85)
//build/inventory/processor:go_default_library (3560f85)
//build/inventory/collectors/docker:go_default_library (3560f85)
@com_github_googlecontainertools_container_diff//util:go_default_library (3560f85)
@com_github_googlecontainertools_container_diff//util:util (3560f85)
@com_github_googlecontainertools_container_diff//pkg/util:util (3560f85)
@com_github_google_go_containerregistry//pkg/v1/daemon:daemon (3560f85)
@com_github_docker_docker//api/types:types (3560f85)
@com_github_docker_docker//api/types/network:network (3560f85)
@com_github_docker_docker//errdefs:errdefs (3560f85)
@org_golang_google_grpc//status:status (3560f85)
@org_golang_google_grpc//internal/status:status (3560f85)
@com_github_golang_protobuf//ptypes:go_default_library_gen (3560f85)
@io_bazel_rules_go//proto/wkt:any_go_proto (3560f85)
(02:02:54) INFO: Elapsed time: 0.331s
(02:02:54) INFO: 0 processes.
(02:02:54) INFO: Build completed successfully, 0 total actions
```

I originally had tried using `Gazelle` and `rules_go` as individual WORKSPACE rules along with `rules_proto_grpc` but received a variety of other build errors depending on the dependency ordering and the way the wind was blowing that day (typically linker errors or missing deps errors).

### What did you expect to see?
Target successfully building.

### What did you see instead?
```
link: package conflict error: github.com/golang/protobuf/ptypes/any: multiple copies of package passed to linker:
        @io_bazel_rules_go//proto/wkt:any_go_proto
        @com_github_golang_protobuf//ptypes/any:any
Set "importmap" to different paths or use 'bazel cquery' to ensure only one
package with this path is linked.
Target //engprod/cli:atom failed to build
```

**Comment by JohnnyS318** [comment]
Seems to be a similar issue to https://github.com/bazelbuild/rules_go/issues/3028

**Comment by mmellin** [comment]
I've since solved this issue by setting `build_file_proto_mode=disable` on the `com_github_googleapis_gnostic` go_repository rule in my WORKSPACE.

```
go_repository(
    name = "com_github_googleapis_gnostic",
    build_file_proto_mode = "disable",
    importpath = "github.com/googleapis/gnostic",
    sum = "h1:9fHAtK0uDfpveeqqo1hkEZJcFvYXAiCN3UutL8F9xHw=",
    version = "v0.5.5",
)
```

I currently have this and other rules in the WORKSPACE further down than the `gazelle_dependencies()` macro, or the rule_go one.

#### How I figured it out

I used a further cquery to identify ALL the deps and found some hidden commonalities. I found our use of the library `io_k8s_client_go` was partly to blame. This, and other k8s libraries utilize a transitive dependency on `github.com/googleapis/gnostic` which uses `github.com/golang/protobuf` (protobuf API v1) instead of `google.golang.org/protobuf` (v2) and Gazelle was not changing the deps to use its own WKTs. 

The cqueries I used were:

```
$ bazel cquery 'allpaths(//sample-app/component:go_default_test, @io_bazel_rules_go//proto/wkt:any_go_proto)' --notool_deps --output=graph

$ bazel cquery 'allpaths(//sample-app/component:go_default_test, @com_github_golang_protobuf//ptypes/any:any)' --notool_deps --output=graph 
```

I took both outputs and plugged them into https://dreampuf.github.io/GraphvizOnline to visualize them. In both cases I saw the Any WKT coming from gnostic libraries. At first I tried a complicated set of maneuvers to workaround the issue but once this worked it help me understand I simply needed to set the `build_file_proto_mode=disable`.
