### ISSUE TITLE
Support for bazel's --test_runner_fail_fast in go_test

### ISSUE THREAD

**Issue by jacobbogdanov** [bazelbuild/rules_go#3055]
### What version of rules_go are you using?

0.28.1

### What version of gazelle are you using?

v0.23.0

### What version of Bazel are you using?

4.2.0

### Does this issue reproduce with the latest releases of all the above?

as far as I can tell, yes

### What operating system and processor architecture are you using?

linux x86-64

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

`bazel test --test_runner_fail_fast //path/to/my/go/test`

### What did you expect to see?

the `go_test` target to stop execution after the first failure.

I know that I can run `--test_arg=-failfast`, but if I'd like to run all my tests across multiple languages and have them all fail fast this approach doesn't work.
`--test_runner_fail_fast` is documented [here](https://docs.bazel.build/versions/main/command-line-reference.html#flag--test_runner_fail_fast), but according to [bazelbuild/bazel#11667](https://github.com/bazelbuild/bazel/issues/11667) the environment variable `TESTBRIDGE_TEST_RUNNER_FAIL_FAST`, which is set by that command line flag is not documented anywhere.

### What did you see instead?

All the tests were run and it did not stop after the first failure.

**Comment by achew22** [comment]
This seems like a really great enhancement! The entry point for the test methods are generated here

https://github.com/bazelbuild/rules_go/blob/75fdf4c365e905a905e0515993a5663b00e44752/go/tools/builders/generate_test_main.go#L161-L182

and the last 3 lines are an example of reading an environment variable and using that to set a flag. What can I do to help this contribution to the project?
