### ISSUE TITLE
Editor Setup instructions for Vim + vim-go

### ISSUE THREAD

**Issue by bcspragu** [bazelbuild/rules_go#3056]
(I removed all the template questions because this isn't a bug)

Hi there!

I recently configured my Vim setup to work with the new-ish rules_go packages driver, and I wanted to update the [Editor setup wiki page](https://github.com/bazelbuild/rules_go/wiki/Editor-setup#3-editor-setup) with instructions.

I figured I'd check in first to see 1) if that was a welcome contribution, and 2) how to go about submitting a wiki PR/contribution. I came [across these suggestions](https://stackoverflow.com/a/11481887) in searching around.

It's also worth noting that this is my first foray into Vimscript, and it's likely hideous to someone more familiar with it.

The TL;DR:

<details>
<summary>.vimrc update</summary>

```vim
function! MaybeSetGoPackagesDriver()
  " Start at the current directory and see if there's a WORKSPACE file in the
  " current directory or any parent. If we find one, check if there's a
  " gopackagesdriver.sh in a tools/ directory, and point our
  " GOPACKAGESDRIVER env var at it.
  let l:dir = getcwd()
  while l:dir != "/"
    if filereadable(simplify(join([l:dir, 'WORKSPACE'], '/')))
      let l:maybe_driver_path = simplify(join([l:dir, 'tools/gopackagesdriver.sh'], '/'))
      if filereadable(l:maybe_driver_path)
        let $GOPACKAGESDRIVER = l:maybe_driver_path
        break
      end
    end
    let l:dir = fnamemodify(l:dir, ':h')
  endwhile
endfunction

call MaybeSetGoPackagesDriver()

" See https://github.com/golang/tools/blob/master/gopls/doc/settings.md
let g:go_gopls_settings = {
  \ 'build.directoryFilters': [
    \ '-bazel-bin',
    \ '-bazel-out',
    \ '-bazel-testlogs',
    \ '-bazel-mypkg',
  \ ],
  \ 'ui.completion.usePlaceholders': v:true,
  \ 'ui.semanticTokens': v:true,
  \ 'ui.codelenses': {
    \ 'gc_details': v:false,
    \ 'regenerate_cgo': v:false,
    \ 'generate': v:false,
    \ 'test': v:false,
    \ 'tidy': v:false,
    \ 'upgrade_dependency': v:false,
    \ 'vendor': v:false,
  \ },
\ }
```

**Comment by achew22** [comment]
We do have a new `/docs` directory that I, for one, would be happy to see this added to. Of course, only if you're interested.
