### ISSUE TITLE
Build Failure with 0.30.0 on macOS with Apple Silicon

### ISSUE THREAD

**Issue by kylekurz** [bazelbuild/rules_go#3070]
### What version of rules_go are you using?

0.30.0

### What version of gazelle are you using?

0.24.0

### What version of Bazel are you using?

5.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
macOS 12.2.1, Apple Silicon M1 Pro (arm64)

### Any other potentially useful information about your toolchain?

I'm using a custom toolchain to build for x86_64 from Apple Silicon, however this error happens even if I build against my local platform, without using a cross flag.

Here's my custom platform:
```
package(default_visibility = ["//visibility:public"])

constraint_setting(name = "container_build_setting")

constraint_setting(name = "container_push_setting")

constraint_value(
    name = "build_containers",
    constraint_setting = "container_build_setting",
)

constraint_value(
    name = "push_containers",
    constraint_setting = "container_push_setting",
)

platform(
    name = "github_actions",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    parents = [
        "@io_bazel_rules_go//go/toolchain:linux_amd64",
    ],
)

platform(
    name = "github_actions_deploy",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
        ":build_containers",
        ":push_containers",
    ],
    parents = [
        "@io_bazel_rules_go//go/toolchain:linux_amd64",
    ],
)
```

### What did you do?

Upgraded from 0.29.0, 0.23.0, 4.2.1 respectively and re-ran `bazelisk build //...`. I'm now getting errors related to, I think, the autogenerated BUILD.bazel for modernc.libc.

### What did you expect to see?

Successful build, as with previous versions

### What did you see instead?

Error related to targets:
```
ERROR: .../external/io_bazel_rules_go/go/platform/BUILD.bazel: no such target '@io_bazel_rules_go//go/platform:ios_arm': target 'ios_arm' not declared in package 'go/platform' (did you mean 'ios_arm64'?) defined by ...external/io_bazel_rules_go/go/platform/BUILD.bazel
ERROR: .../external/org_modernc_libc/BUILD.bazel:3:11: errors encountered resolving select() keys for @org_modernc_libc//:libc
```

**Comment by bizrad** [comment]
I'm also seeing a similar error on an x86 mac using bazel 5.0.0 when trying to update to rules_go 0.30.0 and gazelle 0.24.0
```
ERROR: .../external/io_bazel_rules_go/go/platform/BUILD.bazel: no such target '@io_bazel_rules_go//go/platform:ios_386': target 'ios_386' not declared in package 'go/platform' defined by .../external/io_bazel_rules_go/go/platform/BUILD.bazel
ERROR: .../external/com_github_pion_webrtc_v3/BUILD.bazel:3:11: errors encountered resolving select() keys for @com_github_pion_webrtc_v3//:webrtc
```

If I explicitly bring in @platforms v.0.0.5 as and http_archive then it changes to this
```
ERROR: .../external/io_bazel_rules_go/go/platform/BUILD.bazel: no such target '@io_bazel_rules_go//go/platform:ios_arm': target 'ios_arm' not declared in package 'go/platform' (did you mean 'ios_arm64'?) defined by .../external/io_bazel_rules_go/go/platform/BUILD.bazel
ERROR: .../external/com_github_pion_webrtc_v3/BUILD.bazel:3:11: errors encountered resolving select() keys for @com_github_pion_webrtc_v3//:webrtc
```

The issue appears to have been introduced after this commit 
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "c59f5441947eb851d07da1881252f56c9f5ac04f",
    shallow_since = "1638290941 -0500",
)
```

**Comment by bizrad** [comment]
My builds are now working with bazel 5.0.0, rules_go 0.31.0 and gazelle 0.25.0.

**Comment by kylekurz** [comment]
I'll try that out, thanks @bizrad!

**Comment by kylekurz** [comment]
Confirmed working for me as well, thanks.

**Comment by sgammon** [comment]
@kylekurz would you mind posting your toolchain config for x86 cross-compilation? i'm getting 
```
No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
```

after adding
```
build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
```

**Comment by kylekurz** [comment]
@sgammon I use the platforms I posted above like this:

`bazelisk build --platforms=//tools/platforms:github_actions_deploy //...`

and I specify to only do the docker-ish things when using that platform like this:

```
container_image(
    name = "image",
    ...
    # Only build containers on GitHub
    target_compatible_with = [
        "//tools/platforms:build_containers",
    ],
)

container_push(
    name = "artifact",
    format = "Docker",
    image = ":image",
    ...
    # Only push containers on GitHub
    target_compatible_with = [
        "//tools/platforms:push_containers",
    ],
)
```

Hope that helps!

**Comment by sgammon** [comment]
@kylekurz thank you! yes, this provides some hints 😄
