### ISSUE TITLE
no matching toolchains found for types @io_bazel_rules_go//go:toolchain on DARWIN ARM64

### ISSUE THREAD

**Issue by USB-05** [bazelbuild/rules_go#3086]
### What version of rules_go are you using?

v0.30.0

### What version of gazelle are you using?

v0.22.3

### What version of Bazel are you using?

4.2.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

darwin arm64

### What did you do?

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "d6b2513456fe2229811da7eb67a444be7785f5323c6708b38d851d2b51e54d83",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.30.0/rules_go-v0.30.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies", "go_download_sdk")

go_download_sdk(
    name = "go_sdk",
    version = "1.17.7",
    goos = "darwin",
    goarch = "arm64",
)

go_rules_dependencies()
go_register_toolchains()
```

### What did you expect to see?

Successful Execution: `INFO: Build completed successfully,`

### What did you see instead?

```
ERROR: While resolving toolchains for target //980-commons/src/main/proto/io/harness/security:980_commons_security_go_proto: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//980-commons/src/main/proto/io/harness/security:980_commons_security_go_proto' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
INFO: Elapsed time: 15.284s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 217 targets configured)

```

**Comment by USB-05** [comment]
Above snippet of `io_bazel_rules_go ` is working fine for "darwin amd64" but keep on throwing error for "arm64".

**Comment by JoeDurand3** [comment]
@USB-05 have you been able to move past this issue? I've attempted with every supported combination of bazel / rules_go. Somehow it worked once, but after purging caches, I can't get it to work again.
