### ISSUE TITLE
Mirror URL for v0.31.0 release returns a 404 response

### ISSUE THREAD

**Issue by arashpayan** [bazelbuild/rules_go#3097]
### What version of rules_go are you using?
v0.31.0

### What did you do?
I attempted to download the archive of the v0.31.0 release from the mirror URL.

To reproduce:
```
# From a computer with wget:
$ wget https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.31.0/rules_go-v0.31.0.zip
--2022-03-28 21:44:02--  https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.31.0/rules_go-v0.31.0.zip
Resolving mirror.bazel.build (mirror.bazel.build)... 130.211.22.235
Connecting to mirror.bazel.build (mirror.bazel.build)|130.211.22.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-28 21:44:02 ERROR 404: Not Found.
```

### What did you expect to see?
I expected zip archive of rules_go v0.31.0 to be downloaded to my current directory.

### What did you see instead?
`wget` printed out that there was a `404` response from the server.

**Comment by meteorcloudy** [comment]
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.31.0/rules_go-v0.31.0.zip is now available.
