### ISSUE TITLE
Hosting bazel_gomock in rules_go

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#3101]
@jmhodges created [bazel_gomock](https://github.com/jmhodges/bazel_gomock), which is Bazel rules to generate mocks using [golang/mock](https://github.com/golang/mock). However, the project is inactive, with all pull requests from Uber stuck for years. We also have more internal patches for it. These pull requests and patches significantly improve the performance. We would like to contribute these improvement to the open source community.

Can rules_go host the Bazel rules for gomock?

**Comment by jmhodges** [comment]
I'm into this and happy to hand over copyright, etc! My bazel use has dropped since I've been doing 9-5 gigs again.
