### ISSUE TITLE
mirror.bazel.build 404

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_go#3104]
### What version of rules_go are you using?

`v0.31.0`

### What version of gazelle are you using?

`v0.25.0`

### What version of Bazel are you using?

`5.1.0`

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux x86_64

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

Build `rules_go`.

### What did you expect to see?

A quiet build, with available sources.

### What did you see instead?

```sh
(16:59:20) WARNING: Download from https://mirror.bazel.build/github.com/golang/sys/archive/b874c991c1a50803422b257fb721b0b2dee3cf72.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

**Comment by uhthomas** [comment]
and

```
(17:04:33) WARNING: Download from https://mirror.bazel.build/github.com/googleapis/googleapis/archive/9acf39829240ef41f5adb762a29b87bc6eeee728.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

Maybe others too?

**Comment by linzhp** [comment]
Should be fixed.
