### ISSUE TITLE
Move compile, link actions into Go

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#312]
`_emit_go_compile_action` and `_emit_go_link_action` currently generate Bash scripts that Bazel executes. These are getting pretty complicated, and I expect them to get more complicated as more features are added. With #311, this includes calling a Go binary (`filter_tags`) produced by a genrule. I'm concerned these Bash scripts will become unmaintainable and error-prone, especially when we need to support different options for commands and different shell capabilities on Linux / Darwin.

It would simplify the build to move the action logic out of Bash scripts into Go programs. These could be built using the same genrule as in #311 (`go_tool_binary`), and invoked using a simple action with arguments instead of a script.

**Comment by ianthehat** [comment]
#443 finished this for the compile part, we still have link and cgo to fix

**Comment by ianthehat** [comment]
#627 was the last one (cgo)
