### ISSUE TITLE
Please add a neovim example on wiki page (Editor setup)

### ISSUE THREAD

**Issue by jyane** [bazelbuild/rules_go#3124]
Please add an example for neovim on [wiki page](https://github.com/bazelbuild/rules_go/wiki/Editor-setup).
Neovim setup is a little bit complicated but I don't see any concrete examples on random pages as far as I searched Google.

It would be better if you can add the example like:
``` lua
nvim_lsp.gopls.setup {
  on_attach = on_attach,
  settings = {
    gopls = {
      env = {
        GOPACKAGESDRIVER = './tools/gopackagesdriver.sh'
      },
      directoryFilters = {
        "-bazel-bin",
        "-bazel-out",
        "-bazel-testlogs",
        "-bazel-mypkg",
      },
      ...
    },
  },
}
```

I'm not sure whether I can send a PR for wiki pages (guessing no) so I'm filing this.

**Comment by achew22** [comment]
Thanks for sending this in. I added a new section for [neovim](https://github.com/bazelbuild/rules_go/wiki/Editor-setup#neovim).

**Comment by kaynetik** [comment]
@jyane Could you share a bit more details on your own usage of neovim and `bazel`? 

I have been trying to set it up for the past few hours, and the only proper reference I can find is this PR.
