### ISSUE TITLE
Gazelle should support multiple package in the same directory

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#315]
This will help migrate projects that follow the Blaze style.

A rough outline of rules to be followed. This will need to be refined.

* Gazelle will read the BUILD file (if it exists) and the files in a directory.
* For files with a package name that matches the directory name:
 * If a `go_library` exists with the name `go_default_library`, it will own these files.
 * If a `go_library` exists with the name of the directory, it will own these files.
 * If neither rule exists, one of the above rules will be created. Behavior will be controlled by a flag. `go_default_library` will be the default.
 * If both rules exist, Gazelle will report an error.
* For files with other package names, add to a `go_library` rule with a matching name.
* If test files are present, add them to a `go_test` rule, following the naming convention above.

NOTE: Gazelle cannot use `go/build` to do this, since that package assumes sources follow the Go conventions instead of the Blaze conventions.
NOTE: The import path for `//foo/bar:bar` will be `go_prefix/foo/bar/bar`.

**Comment by ashi009** [comment]
s/Blaze/Bazel/ ;)

**Comment by jayconrod** [comment]
@ashi009 In this context, I actually meant Blaze :) Bazel is the open source version of Google's internal system called Blaze.

Internal Go projects follow their own set of conventions (Blaze conventions), which is different from the normal Go conventions. We want Gazelle to support both sets of conventions to make it easy to open source internal projects in the future.

**Comment by ashi009** [comment]
Make sense. I thought we always use bazel externally.
Jay Conrod <notifications@github.com>于2017年3月18日 周六上午9:25写道：

**Comment by jayconrod** [comment]
Closing old Gazelle issues. Migrated to bazelbuild/bazel-gazelle#7.
