### ISSUE TITLE
Gomock missing `go_default_library` targets

### ISSUE THREAD

**Issue by nickgooding** [bazelbuild/rules_go#3154]
### What version of rules_go are you using?

v0.32.0

### What version of gazelle are you using?
v0.25.0

### What version of Bazel are you using?

v5.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac OS 12.3, x86_64-apple-darwin21.1.0

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

Tried to build `go_*` targets that depend on `go_default_library` targets in `@com_github_golang_mock` after upgrading to rules_go v0.32.0

### What did you expect to see?

Build would work successfully

### What did you see instead?

Builds failed with this error:
```
ERROR: <snip>/BUILD.bazel:3:11: no such target '@com_github_golang_mock//gomock:go_default_library': target 'go_default_library' not declared in package 'gomock' defined by <snip>/external/com_github_golang_mock/gomock/BUILD.bazel and referenced by '<snip>:go_default_library'
```

### Workaround

Adding the following in our workspace and rerunning Gazelle resolved the issue (even though it isn't actually used in lieu of the dependency of rules_go)
```diff
     go_repository(
         name = "com_github_golang_mock",
         build_file_proto_mode = "disable",
+        # Workaround for bazelbuild/rules_go#3154
+        build_naming_convention = "import",
         importpath = "github.com/golang/mock",
         replace = "github.com/golang/mock",
         sum = "h1:ErTB+efbowRARo13NNdxyJji2egdxLGQhRaY+DUumQc=",
         version = "v1.6.0",
     )

```

**Comment by linzhp** [comment]
How can I reproduce the issue?

**Comment by nickgooding** [comment]
To reproduce the issue, have a workspace using the `go_default_library` Gazelle naming convention and a `go_library` target created by Gazelle that depends on `com_github_golang_mock`. With `rules_go` v0.31.0, this would build fine, but upgrading to v0.32.0 breaks it. The fix is very trivial, as you can see in the linked PR.

This repo contains a very minimal reproduction: https://github.com/nickgooding/rules_go-3154-repro
