### ISSUE TITLE
Deprecate the unused compiling API

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#3168]
Tracking bug for deprecating the unused compiling API that was removed when Jay switched over to having all the compilation/linking. We are going to add `print` warning statements into the `compile`, `compilePackage` et al to ask people to come check in on this bug.

@fmeum

**Comment by fmeum** [comment]
Submitted #3172 to add deprecation warnings. #3173 is a CI test run to check that removing these actions is actually safe.
