### ISSUE TITLE
protoc argument list too long

### ISSUE THREAD

**Issue by sateeshpnv** [bazelbuild/rules_go#3188]
### What version of rules_go are you using?

v0.32.0

### What version of gazelle are you using?

v0.25.0

### What version of Bazel are you using?

5.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux x86

### What did you do?

In a large project with several transitive protobuf dependencies, did a `bazel build ...:xxx_go_proto` (a go_proto_library target).

### What did you expect to see?

Since changing the OS limits is not feasible, expect protoc to be invoked with `@<filename>` option so that long argument list length is not a problem

### What did you see instead?

bazel build of a go_proto_library target fails with the below error:

```
2022/06/07 16:53:18 error running protoc: fork/exec bazel-out/k8-opt-exec-2B5CBBC6/bin/rules/proto/protoc: argument list too long
```

The length of the args is about 220kB. It fails on linux, while it works on macOS; at this size.

### Proposed fix

Use `@<filename>` option instead of passing all the args in command line, only if the length is >100k. `@<filename>` should not be used for all cases as file IO would slow down the build. Though 100k seems to work it is, kind of, arbitrary. Any better suggestion is welcome.

**Comment by fmeum** [comment]
@sateeshpnv Thanks for the report. Could you check whether https://github.com/bazelbuild/rules_go/pull/3190 fixes the issue?
