### ISSUE TITLE
Set up caching for Travis CI

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#320]
Travis CI supports a [persistent cache](https://docs.travis-ci.com/user/caching/) that can be reused between test runs. This would make tests faster, since build artifacts could be kept in the cache.

More importantly, we may be able to cache downloads of the Go toolchain with the [--experimental_repository_cache flag](https://github.com/bazelbuild/bazel/blob/fc475658721b86a81351cb8841aa8f5ad57d828f/src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java#L27). See [bazel_repository_cache_test.sh](https://github.com/bazelbuild/bazel/blob/8d8abe46bd7ab0c87beb31d97c9185760d762d79/src/test/shell/bazel/bazel_repository_cache_test.sh) for usage.

**Comment by jayconrod** [comment]
On reading [Things not to cache](https://docs.travis-ci.com/user/caching/#Things-not-to-cache), it doesn't seem like caching the Go binary would benefit us, since it's something that's quick to install but slow to download. It would take as long to fetch the cache as it would fetch the Go toolchain as we do now.

Caching Bazel intermediate files wouldn't have much benefit at this point.

**Comment by kevinburke** [comment]
I'd like to reopen this, if possible. My tests take 47 seconds with a cold cache, but only 13 seconds if the cache is enabled: https://travis-ci.org/kevinburke/hostsfile/builds/290936859. In particular it seems like it could speed things up if we didn't have to fetch dependencies before running tests.

Maybe the request should be to cache only a part of the build. Is there a way to cache everything except the large Go binary?

**Comment by jayconrod** [comment]
In terms of downloading, we could probably speed up the test by using a host SDK (something Travis already has installed on workers) and downloading a version of Bazel from GitHub that doesn't bundle Java. Saving the cache would help, but probably not as much as those two things.

I don't think this would actually help a whole lot though. We spend the vast majority of our time waiting in the Mac build queue. The Mac workers are really oversubscribed. This will just get worse over time.

I'd rather switch to another CI system than spend time optimizing the Travis CI build. I've been looking at a couple of Google CI systems, but I haven't had time to really evaluate and try switching.

**Comment by kevinburke** [comment]
I guess it's going to continue to be a problem for open source projects that use Travis - most of which that I have seen do not use the Mac builders.

I wrote a little bit about it here:

https://kev.inburke.com/kevin/bazel-tests-on-travis-ci/
