### ISSUE TITLE
Running test that requires time.LoadLocation fails under bazel (on Windows at least)

### ISSUE THREAD

**Issue by tomqwpl** [bazelbuild/rules_go#3225]
### What version of rules_go are you using?
v0.32.0

### What version of gazelle are you using?
v0.25.0

### What version of Bazel are you using?
Bazelisk version: v1.11.0
Build label: 5.2.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:03:57 2022 (1654617837)
Build timestamp: 1654617837
Build timestamp as int: 1654617837

### Does this issue reproduce with the latest releases of all the above?
I believe these are the latest versions

### What operating system and processor architecture are you using?
Windows 10 x86

### What did you do?

Here is my test case:
````
var _ = FDescribe("test tests", func() {
	Specify("xx", func() {
		goroot := os.Getenv("GOROOT")
		fmt.Println("GOROOT envar " + goroot)
		fmt.Println("GOROOT is " + runtime.GOROOT())
		_, err := time.LoadLocation("America/New York")
		Expect(err).NotTo(HaveOccurred())
	})
})
````

### What did you expect to see?

I expect LoadLocation to succeed

### What did you see instead?

LoadLocation fails

The issue is with the setting of GOROOT in the bazel environment. GOROOT is set to GOROOT, so time.LoadLocation doesn't work, since it can't find the GOROOT/lib/time/zoneinfo.zip that it relies on.

It's therefore unclear how to make this work.
I have seen various workaround that perform horrible looking bazel specific code to infer where GOROOT is and then set the GOROOT environment variable, but they look, well, horrible.

**Comment by fmeum** [comment]
Reading https://github.com/golang/go/issues/21881, to me it looks like this doesn't have much to do with Bazel: Using `time.LoadLocation` by default requires a Go SDK to be installed on Windows, which is also a problematic requirement e.g. for deploying a Go binary built with the non-Bazel Go toolchain on Windows.

Isn't the proper fix, with and without Bazel, to import [`time/tzdata`](https://pkg.go.dev/time/tzdata), as suggested in the issue?

**Comment by tomqwpl** [comment]
Yes, you're right. It's a test that works "normally", but failed under Bazel, so I blamed bazel. I hadn't imported time/tdata because I hadn't had to, the test worked just fine without.
