### ISSUE TITLE
Any objection to add a ignore_go_package option in go_proto_library rule?

### ISSUE THREAD

**Issue by rosun82** [bazelbuild/rules_go#323]
Background:

We have a bunch of protos put in a git repository, and for historical reasons they have go_package option specified. However, when switching to Bazel, the go_package option gets in the way, as the output .pb.go file is in the wrong place and wrong package hence cannot be used as "deps" for other go_proto_library rules.

Proposal, add an ignore_go_package option, when specified, simply remove "option go_package" line from the proto source code then compile.

I can handle the modification if there is no objection.

**Comment by pmbethe09** [comment]
Long-term: we should fix go_proto_library.  But that might take some effort.

So short-term I would be ok with this hack if you want to write it.

**Comment by jayconrod** [comment]
@rosun82 Would this work for you: write a genrule that removes `option go_package` with `grep -v` or something similar, then use the output as srcs for `go_proto_library` instead of the original.

**Comment by rosun82** [comment]
I have tried that. The trouble is there are proto imports. A genrule has to produce a file with different name, say we rename file a.proto to a_fix.proto through genrule. If b.proto imports a.proto, it will not build

**Comment by rosun82** [comment]
@pmbethe09 Sorry to disturb, but how to contribute to the rules_go repository exactly?

I have checked CONTRIBUTING.md, and found it extremely confusing. The link goes to contributing to bazel itself, but I could not find the repository for go rules at all.
