### ISSUE TITLE
How to set the result of `bazel run @kubebuilder_sdk//:pwd` to `go_test`'s `env`

### ISSUE THREAD

**Issue by LittleWat** [bazelbuild/rules_go#3245]
Sorry for the beginner's question.

### What version of rules_go are you using?

latest (v0.34.0)

### What version of gazelle are you using?

latest(v0.26.0)

### What version of Bazel are you using?

5.2.0

```
$ bazel version
Bazelisk version: development
Build label: 5.2.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:09 2022 (1654618269)
Build timestamp: 1654618269
Build timestamp as int: 1654618269
```

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

m1 mac (not related)

### Any other potentially useful information about your toolchain?

no

### What did you do?

I am using https://github.com/ob/rules_kubebuilder.

Now I am running like this;

```
bazel test --test_env=KUBEBUILDER_ASSETS=$(bazel info execution_root 2>/dev/null)/$(bazel run @kubebuilder_sdk//:pwd 2>/dev/null) //...
```

but I want to set the environment variable using `go_test` env attribute.

How should I set it?

```
 env = {
        "KUBEBUILDER_ASSETS": "$(location //kubebuilder_sdk//:pwd)",
 },
```

or 

```
 env = {
        "KUBEBUILDER_ASSETS": "$(location @kubebuilder_sdk//:pwd)",
 },
```

does not work....

### What did you expect to see?

I would like to use `go_test` env attribute.

### What did you see instead?

build error....

```
ERROR: /runner/_work/.../BUILD.bazel:34:8: in go_test rule //foo/controllers:controllers_test: label '@kubebuilder_sdk//:pwd' in $(location) expression is not a declared prerequisite of this rule
ERROR: /runner/_work/.../BUILD.bazel:34:8: Analysis of target '//foo/controllers:controllers_test' failed
```

**Comment by fmeum** [comment]
Could you try adding `@kubebuilder_sdk//:pwd` to the `data` of your `go_test`?

**Comment by fmeum** [comment]
`rules_kubebuilder` uses [this template](https://github.com/ob/rules_kubebuilder/blob/main/kubebuilder/BUILD.sdk.bazel) to generate a BUILD file for `@kubebuilder_sdk`. As you can see, the `pwd` target doesn't have `visibility` set, which makes it impossible to reference from outside `@kubebuilder_sdk`. You could either reference `@kubebuilder_sdk//:bin/kubebuilder` if that's what you want or else you would have to open an issue at https://github.com/ob/rules_kubebuilder to have them add `visibility = ["//visibility:public"]` to the target.
