### ISSUE TITLE
Dose Bazel analysis go test log and product xml by log line?

### ISSUE THREAD

**Issue by mtcoafun** [bazelbuild/rules_go#3252]
### Bugs: Bazel analysis go test log and product xml by log line.
> There is a fmt statement in go test case and not newlines,

![image](https://user-images.githubusercontent.com/50589627/132814138-8784d75e-2a8d-4c9a-93d1-252a12b52967.png)

> and go test log is as follows,

![image](https://user-images.githubusercontent.com/50589627/132814310-ebb9c034-4fbe-40ad-974a-d9246b29c6e0.png)

> but this will be considered as a fail case when Bazel product xml by this test log

![image](https://user-images.githubusercontent.com/50589627/132814730-2525bb16-d6b1-4be7-9931-c5d928581a88.png)

> unless add a '\n' in fmt.

**Comment by mtcoafun** [comment]
original question is [here](https://github.com/bazelbuild/bazel/issues/13970)

**Comment by fmeum** [comment]
I'm hesitant to make the test result parser more lenient as that may result in false positives, which are much worse than false negatives.

Is that `fmt.Printf` contained in test code? You could use `log.Printf` or `t.Failf` instead which AFAIK add the newline automatically.

**Comment by mtcoafun** [comment]
> I'm hesitant to make the test result parser more lenient as that may result in false positives, which are much worse than false negatives.
> 
> Is that `fmt.Printf` contained in test code? You could use `log.Printf` or `t.Failf` instead which AFAIK add the newline automatically.

yes, i uesd `fmt.Printf` in unit test code, it seems best not to use it in test code😂
