### ISSUE TITLE
go_proto_library target doesn't work with blaze modules

### ISSUE THREAD

**Issue by ntnj** [bazelbuild/rules_go#3265]
### What version of rules_go are you using?
0.33.0

### What version of Bazel are you using?
5.2.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Ubuntu 22.04, amd64

### What did you do?
in `MODULE.bazel`, added `bazel_dep(name = "rules_go", version = "0.33.0")`
then added `load("@rules_go//proto:def.bzl", "go_proto_library")` to a BUILD file.

### What did you expect to see?
go_proto_library works.

### What did you see instead?
`ERROR: error loading package '': at home/..../external/rules_go.0.33.0/proto/def.bzl:43:5: Unable to find package for @rules_proto//proto:defs.bzl: The repository '@rules_proto' could not be resolved: Repository '@rules_proto' is not visible from repository '@rules_go.0.33.0'.`

**Comment by fmeum** [comment]
Use rules_go 0.34.0 or later from the registry for `go_proto_library` support. `go_grpc_library` is a different story.
