### ISSUE TITLE
gopackagesdriver failing for go_binary

### ISSUE THREAD

**Issue by DrewMonroe** [bazelbuild/rules_go#3270]
### What version of rules_go are you using?

v0.34.0

### What version of gazelle are you using?

v0.24.0

### What version of Bazel are you using?

v 5.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Arch linux, 5.18.16 kernel, x86_64

### What did you do?

Configure `gopackagesdriver` for vim [as describe in the docs](https://github.com/bazelbuild/rules_go/blob/master/docs/go/editors/vim.md). Create a `go_library`, and a `go_binary` that depends on that library. Vim is able to autocomplete for the `go_library`, but not the `go_binary`. Specifically, the `bazel query` command run by `gopackagesdriver` is not returning the name of build target, causing an error when `bazel build` is run by the driver.

Adding `go_binary` to the return of the [`fileQuery` function for the `BazelJSONBuilder` struct](https://github.com/bazelbuild/rules_go/blob/master/go/tools/gopackagesdriver/bazel_json_builder.go#L38) solves the problem. 

### What did you expect to see?

Vim should have autocompletion options. 

### What did you see instead?

No autocompletion options.

I'm happy to submit a PR for the one line change, but wanted to create an issue to make sure this behavior wasn't intentional.

**Comment by fmeum** [comment]
I'm not too familiar with the code, but I don't see a reason why we wouldn't want to list `go_binary` there. @linzhp What do you think?

**Comment by linzhp** [comment]
yeah, that's reasonable. Can you send a pull request?

**Comment by DrewMonroe** [comment]
Yup I'd be happy to. Thanks for the sanity check
