### ISSUE TITLE
rules_go tests failing with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_go#3293]
First reported at https://github.com/bazelbuild/continuous-integration/issues/1429
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2632#01833a2a-4026-47c4-9730-89252449e823
```
    --- FAIL: TestLcovCoverage/without-race (5.06s)
        lcov_coverage_test.go:171: bazel-testlogs/src/lib_test/coverage.dat: does not contain:
            
            SF:src/other_lib.go
            FNF:0
            FNH:0
            DA:3,1
            DA:4,1
            DA:5,0
            DA:6,0
            DA:7,1
            LH:3
            LF:5
            end_of_record
            
            actual content:
            
```

`//tests/core/coverage:lcov_coverage_test` and `//tests/core/coverage:lcov_test_main_coverage_test` are broken by coverage_output_generator v2.6 introduced at https://github.com/bazelbuild/bazel/commit/a70d84b9eaae99f665ccdebd68eb3da57e07530b

(There is another test `//tests/core/cross:non_executable_test` also failing, but due a Bazel issue, we are investigating)

**Comment by fmeum** [comment]
This one is on us: We have been lazy about populating `InstrumentedFilesInfo` since it wasn't necessary until v2.6. Will fix that and look into `//tests/core/cross:non_executable_test` as well.

**Comment by meteorcloudy** [comment]
Thanks!
For `//tests/core/cross:non_executable_test`, we have figured it out, please check https://github.com/bazelbuild/continuous-integration/issues/1429#issuecomment-1246891945
