### ISSUE TITLE
test stderr is only in test.log, not test.xml

### ISSUE THREAD

**Issue by rickystewart** [bazelbuild/rules_go#3298]
I'm not sure if this is the desired behavior, but it is pretty surprising: only `stdout` output from the test binary is in the `test.xml` produced by `rules_go`. The `stderr` is ONLY in `test.log` (which also contains the `test.xml` `stdout` output). For us at `cockroach` we parse `test.xml` to get test results, and it's often the case that the `test.xml` says there's a failure but contains no relevant information because many tests/frameworks/etc. only write error output to `stderr` rather than `stdout`. This means if you want the full or relevant output you MUST look in `test.log`, which may be confusing.

I have a candidate fix at [https://github.com/rickystewart/rules_go/tree/stderrxml](this branch), and can file a PR if desired.

**Comment by fmeum** [comment]
Your reasoning and the fix seem valid.

@jayconrod @achew22 Do you remember whether there is/was a reason for this behavior?

**Comment by achew22** [comment]
I think this is a normal development oversight and would welcome the patch. Thanks @rickystewart!

**Comment by rickystewart** [comment]
I'll file the PR now, thanks everyone.

**Comment by rickystewart** [comment]
So I've found one problem with this: rarely, the `stdout` and `stderr` will get interleaved such that some `stderr` content will end up "in the middle of" a line of stdout, which can interfere with parsing and result in `No pass/skip/failed event for test`.

Consider this output from https://github.com/cockroachdb/cockroach/issues/88048:

```
            --- PASS: TeI220916 15:19:35.406930 702 3@pebble/event.go:649  [pebble,s?] 2  [JOB 1] MANIFEST created 000001
I220916 15:19:35.407183 702 3@pebble/event.go:677  [pebble,s?] 3  [JOB 1] WAL created 000002
...
I220916 15:19:35.414755 702 sql/colexec/colexectestutils/utils.go:691  [-] 22  batchSize=1/sel=false
stWindowFramer/mode=Groups/start=OffsetFollowing/end=UnboundedFollowing#01/count=17 (0.00s)
                --- PASS: TestWindowFramer/mode=Groups/start=OffsetFollowing/end=UnboundedFollowing#01/count=17/ordered/asc=true/typ=timestamptz/exclusion=NoExclusion (0.00s)
                --- PASS: TestWindowFramer/mode=Groups/start=OffsetFollowing/end=UnboundedFollowing#01/count=17/ordered/asc=false/typ=timestamptz/exclusion=NoExclusion (0.00s)
```

Notice how the content of the line `--- PASS: TestWindowFramer/mode=Groups/start=OffsetFollowing/end=UnboundedFollowing#01/count=17 (0.00s)` is "split" across several other lines of test `stderr`, meaning that `rules_go` can't parse it.

On the `cockroach` side we've applied https://github.com/cockroachdb/rules_go/pull/8 to fix this, but it's bigger than the original change due to the need for added synchronization. I can submit a PR for this one as well if desired.
