### ISSUE TITLE
Build tag filtering for `cgo` rules

### ISSUE THREAD

**Issue by nelhage-stripe** [bazelbuild/rules_go#330]
I think this is the issue I was actually seeing when I created #328. `cgo_library` rules appear to not properly filter based on build tags, and will try to run over `.go` files that shouldn't be built.

https://github.com/nelhage-stripe/bug_rules_go/tree/master/cgo_tags builds for me under `go build` and not `rules_go`, on `darwin_amd64`.

**Comment by jayconrod** [comment]
Ah, yes, the cgo tag filtering doesn't work yet. Definitely still need to fix that.

**Comment by nelhage-stripe** [comment]
Thanks for the quick turnaround!

Looks like cfdcbdc still doesn't filter `.c` files based on file suffixes, which `go build` does. Happy to open a new issue if that's easier.

**Comment by jayconrod** [comment]
@nelhage-stripe Thanks for pointing that out. I'll reopen this issue.

Filtering .c files may be trickier than .go files since we build those directly with `cc_library`. Still, I'm sure we can find a way to make that work.

**Comment by nelhage-stripe** [comment]
Thanks so much! After all these fixes, I can confirm my project finally builds on vanilla `gazelle`-generated `BUILD` files using the latest `rules_go`.

**Comment by jayconrod** [comment]
@nelhage-stripe Great! I'm really happy to hear that. I'm not 100% confident yet that this builds everything that go build does, but please let me know if you see anything else that isn't working.

Note that `gazelle` will still generate BUILD files based on your GOOS and GOARCH due to #339. I'm planning to fix that soon.
