### ISSUE TITLE
Support host SDK in toolchain:sdk_version command-line flag

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#3302]
### What version of rules_go are you using?

v0.35.0

### What version of gazelle are you using?

v0.27.0

### What version of Bazel are you using?

5.3.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS M1

### Any other potentially useful information about your toolchain?

I want to use a particular SDK version by default (it is defined first) but also be able to switch the whole build to use host SDK using a flag (or some other way?).

### What did you do?

WORKSPACE:
```
go_download_sdk(
    name = "go_sdk",
    version = "1.18.5",
)

go_host_sdk(
    name = "host_sdk",
)

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies(
    go_sdk = "go_sdk",
)
```

```
bazel build --@io_bazel_rules_go//go/toolchain:sdk_version=host_sdk //some-target
```

### What did you expect to see?

Target built with the host Go SDK.

### What did you see instead?

```
ERROR: somepath/BUILD.bazel:16:23: While resolving toolchains for target //some-target: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//some-target' failed; build aborted: 
```

**Comment by fmeum** [comment]
This could be achieved relatively easily by adding a `config_value` for `host_sdk` (or `host`, to avoid duplicating `sdk`) [here](https://github.com/bazelbuild/rules_go/blob/4d4a2454c588dab27853ccffb03fcb9205001192/go/private/BUILD.sdk.bazel#L100) conditionally if the [_sdk_build_file](https://github.com/bazelbuild/rules_go/blob/4d4a2454c588dab27853ccffb03fcb9205001192/go/private/sdk.bzl#L234) function is called from [_go_host_sdk_impl](https://github.com/bazelbuild/rules_go/blob/4d4a2454c588dab27853ccffb03fcb9205001192/go/private/sdk.bzl#L30).

@ash2k or anyone else interested in picking this up, I can help in case you get stuck.

**Comment by ash2k** [comment]
I'll open a PR. Thanks for the instructions!
