### ISSUE TITLE
Cross-compiling should use the appropriate SDK's stdlib rather than rebuilding it

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_go#3305]
Currently cross-compiles via `--platforms` or `go_cross_binary` result in rebuilding the stdlib from scratch, which is [slow and expensive](https://github.com/bazelbuild/rules_go/issues/2188).

Instead, cross compiles should use the prebuilt stdlib from the appropriate SDK. I'm not familiar with the details, but perhaps the functionality introduced in https://github.com/bazelbuild/rules_go/pull/3261 is helpful to support this.

### What version of rules_go are you using?

v0.35.0

### What version of gazelle are you using?

v0.26.0

### What version of Bazel are you using?

Bazelisk version: development
Build label: 5.3.1
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Sep 19 17:37:11 2022 (1663609031)
Build timestamp: 1663609031
Build timestamp as int: 1663609031

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS. Tested on both Intel and arm64, same result.

### What did you do?

Run `bazel aquery --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 'mnemonic("GoStdlib.*", deps(//tests/examples/executable_name:some_binary))' --output=summary`.

### What did you expect to see?

No `GoStdlib` mnemonics.

### What did you see instead?

```
Mnemonics:
  GoStdlib: 1
  GoStdlibList: 1
```

**Comment by jfirebaugh** [comment]
I tested cross-compiling via `go_cross_binary` as well. It also builds the stdlib.

**Comment by sluongng** [comment]
https://github.com/bazelbuild/rules_go/pull/3242 could give some context.

Short: we re-compile go stdlib for different combinations of config value: cgo/pure, arch, os etc...  We cannot use a Windows stdlib for a linux compilation.

**Comment by fmeum** [comment]
As @sluongng has noted, there are valid cases for rebuilding the stdlib. 

That said, there are also wasteful recompilations, for example when cross-compiling for two different platforms targets with identical constraints using `go_cross_binary`. I'm working on a more principled fix for such issues in core Bazel and will introduce experimental support in rules_go once these experiments have landed in Bazel.

**Comment by jfirebaugh** [comment]
> Short: we re-compile go stdlib for different combinations of config value: cgo/pure, arch, os etc... We cannot use a Windows stdlib for a linux compilation.

Right, but vanilla cross-compiles without pure or race, where the target platform is one of the ones with a supported SDK, could use the prebuild stdlib, right?

Also, I suspect the SDKs include prebuilt stdlib with race support, because non-Bazel race builds don't require building a stdlib (https://github.com/bazelbuild/rules_go/issues/3218#issuecomment-1225071032, https://github.com/bazelbuild/rules_go/issues/3258).

**Comment by sluongng** [comment]
> because non-Bazel race builds don't require building a stdlib 

I don't think this is true. If you use `go build -x .` vs `go build -x -race .` (on a non-cached machine), it should show recompilation of std packages. It's should be even clearer if you switch to cross-compile to a different platform (Linux -> Windows).

The different between non-Bazel builds is that stdlib are compiled per package instead as a whole. So if you only use `fmt`, here would be the 2 different command runs:

```
# bazel
go install -race std

# go tooling
go install -race fmt
```

So right now, rules_go is using a "big" action to simplify how `std` is being prepared.

---

@jfirebaugh Generally these are rarely rebuild as they are cached quite well. Are you running into issues because of a Go SDK upgrade?

**Comment by jfirebaugh** [comment]
> I don't think this is true. If you use go `build -x .` vs go `build -x -race .` (on a non-cached machine), it should show recompilation of std packages.

I'm not sure exactly what I'm looking for, but I don't think I see this. I also just downloaded the latest darwin-amd64 release off https://go.dev/dl/ and verified that it contains a `pkg/darwin_amd64_race` directory containing `.a` files for all stdlib packages.

**Comment by jfirebaugh** [comment]
I guess https://github.com/golang/go/issues/47257 will make this moot, and instead we need to focus on making stdlib rebuilds with Bazel more efficient.

> Generally these are rarely rebuild as they are cached quite well. Are you running into issues because of a Go SDK upgrade?

The issues we run into are:

* `@io_bazel_rules_go//go/config:race` invalidates the cache: https://github.com/bazelbuild/rules_go/issues/3218
* Unless you are using `--remote_download_minimal`/`toplevel`, Bazel uses an excessive amount of memory when reading from the cache. It frequently gets OOM killed on an instance with 8GB RAM. This occurs even with conservative values for `--jobs` and `--local_{ram,cpu}_resources`. [#3218 (comment)](https://github.com/bazelbuild/rules_go/issues/3218#issuecomment-1225071032)
* Unless you are using `--remote_download_minimal`/`toplevel`, reading the cache is slow. Users have reported it being 2x to 5x slower than not caching at all: https://github.com/bazelbuild/rules_go/issues/2188 / https://github.com/bazelbuild/rules_go/issues/2834.

**Comment by derekperkins** [comment]
Any progress here?

**Comment by fmeum** [comment]
I recently learned that starting with Go 1.20, the SDKs will no longer ship any precompiled stdlibs. Instead of adding more reliance on them, we should thus try to migrate away from them as soon as possible and instead improve on the current pain points.

I am trying to get some flags flipped for Bazel 6.0.0 that would allow us to drastically reduce the number of times the stdlib is rebuilt (for `bazel build //...` on the rules_go repo itself, from 19(!) times down to 2 or 3). We should then try to fix the issues with remote caching. Any contributions in this area are very welcome and I am more than happy to help them along.

**Comment by sluongng** [comment]
From the comments above, I think this issue should be closed.

The recent “reset transition” mechanism Fabian introduced should also help quite a bit with reducing the number of stdlib action needed for multi-configurations build.

We should redirect future efforts into breaking up the big stdlib action into multiple smaller actions if folks care about improving the speed there. Feel free to create a separate issue with proposal on how to achieve it.
