### ISSUE TITLE
missing strict dependencies for https://github.com/DataDog/sketches-go

### ISSUE THREAD

**Issue by pwaterz** [bazelbuild/rules_go#3308]
### What version of rules_go are you using?
v0.35.0

### What version of gazelle are you using?
v0.27.0

### What version of Bazel are you using?
5.3.1

### Does this issue reproduce with the latest releases of all the above?
Yes. I am running all the latest versions.

### What operating system and processor architecture are you using?
Ubuntu 22.04 x86 64

### What did you do?
bazel build //...:all

```
 go_repository(
        name = "com_github_datadog_sketches_go",
        importpath = "github.com/DataDog/sketches-go",
        sum = "h1:j5G6as+9FASM2qC36lvpvQAj9qsv/jUs3FtO8CwZNAY=",
        version = "v1.4.1",
    )
```

### What did you expect to see?
Successful build

### What did you see instead?
$ bazel build //...:all
INFO: Build option --platforms has changed, discarding analysis cache.
INFO: Analyzed 334 targets (753 packages loaded, 16451 targets configured).
INFO: Found 334 targets...
ERROR: /home/pwaters/.cache/bazel/_bazel_pwaters/b9add76341c27a79c7d399065a2c31b6/external/com_github_datadog_sketches_go/ddsketch/mapping/BUILD.bazel:3:11: GoCompilePkg external/com_github_datadog_sketches_go/ddsketch/mapping/mapping.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/home/pwaters/.cache/bazel/_bazel_pwaters/b9add76341c27a79c7d399065a2c31b6/sandbox/linux-sandbox/71/execroot/__main__/external/com_github_datadog_sketches_go/ddsketch/mapping/cubically_interpolated_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
	/home/pwaters/.cache/bazel/_bazel_pwaters/b9add76341c27a79c7d399065a2c31b6/sandbox/linux-sandbox/71/execroot/__main__/external/com_github_datadog_sketches_go/ddsketch/mapping/index_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
	/home/pwaters/.cache/bazel/_bazel_pwaters/b9add76341c27a79c7d399065a2c31b6/sandbox/linux-sandbox/71/execroot/__main__/external/com_github_datadog_sketches_go/ddsketch/mapping/linearly_interpolated_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
	/home/pwaters/.cache/bazel/_bazel_pwaters/b9add76341c27a79c7d399065a2c31b6/sandbox/linux-sandbox/71/execroot/__main__/external/com_github_datadog_sketches_go/ddsketch/mapping/logarithmic_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
INFO: Elapsed time: 4.098s, Critical Path: 0.69s
INFO: 43 processes: 21 internal, 22 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by knitehias** [comment]
this post saved me lots of time

**Comment by AttilaTheFun** [comment]
I had the same issue and the build directives above fixed it for me.

**Comment by fmeum** [comment]
Running `gazelle -repo_root . -go_prefix github.com/DataDog/sketches-go` on a local checkout of the repo provides the explanation for this failure:

```
gazelle: rule //ddsketch/mapping imports "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb" which matches multiple rules: //ddsketch/pb/sketchpb and //ddsketch/pb:sketchpb. # gazelle:resolve may be used to disambiguate
gazelle: rule //ddsketch/store imports "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb" which matches multiple rules: //ddsketch/pb/sketchpb and //ddsketch/pb:sketchpb. # gazelle:resolve may be used to disambiguate
gazelle: rule //ddsketch imports "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb" which matches multiple rules: //ddsketch/pb/sketchpb and //ddsketch/pb:sketchpb. # gazelle:resolve may be used to disambiguate
gazelle: rule //ddsketch:ddsketch_test imports "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb" which matches multiple rules: //ddsketch/pb/sketchpb and //ddsketch/pb:sketchpb. # gazelle:resolve may be used to disambiguate
```

The repo contains checked in Go files pregenerated from the protos. Gazelle could prefer `go_library` over `go_proto_library` targets in this case, assuming that non-Bazel-aware projects would use the pregenerated files as the source of truth anyway.

CC @linzhp
