### ISSUE TITLE
Source code for new tutorial

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_go#3316]
Hi all

We wrote a new rules_go tutorial under the purview of the Bazel Rules sig.   The tutorial is located on the bazel rules GitHub pages site.  Along with that tutorial, we have source code that needs a home.  Talking with @alexeagle, we were wondering if we could include the tutorial source code in this repo.

Here is the source code:

https://github.com/bazel-contrib/Bazel-learning-paths/pull/6

We would rather not have the source in Bazel-learning-paths.

Thanks
Chris

**Comment by chrislovecnm** [comment]
@fmeum what is the full directory path that we want?  I will need to update both the source code and the tutorial.

`rules_go/examples/tutorial` - how about that?

**Comment by fmeum** [comment]
That sounds reasonable, we might want to add other `examples` in the future that aren't linked to the tutorial.

Where is the tutorial itself hosted? Would it make sense to also host it in the `rules_go` repo so that tutorial and accompanying code are easier to keep in sync?

**Comment by chrislovecnm** [comment]
@fmeum, the tutorial is here: https://bazel-contrib.github.io/SIG-rules-authors/go-tutorial.html - and eventually, we are trying to figure out how to move it to https://bazel.build/start/.  

I wish it were easier to keep the tutorial and source code in sync, but we want the tutorial hosted on a website, and for now, the bazel-contrib gh-pages is our best option.
