### ISSUE TITLE
CI/CD setup for examples

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_go#3318]
We are missing the CD/CI setup for the examples with MacOS.  I figured out how to do it for ubuntu, but I do not know how to set this line:

https://github.com/bazelbuild/rules_go/blob/d517cd9bec43f0541b421315fe633cdd0f204270/.bazelci/presubmit.yml#L28

For MacOSX

**Comment by fmeum** [comment]
The value should be `macos`: If `platform` isn't given explicitly, it defaults to the name of the job.

**Comment by chrislovecnm** [comment]
@fmeum, can we get the first PR merged, and then I will loop back on this?

**Comment by chrislovecnm** [comment]
Closing this as I fixed it in #3317
