### ISSUE TITLE
Unrecognized build option errors when trying to use @io_bazel_rules_go//go/config:strip 

### ISSUE THREAD

**Issue by aw185176** [bazelbuild/rules_go#3325]
### What version of rules_go are you using?

0.35.0

### What version of gazelle are you using?

0.26.0

### What version of Bazel are you using?

5.3.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux x86-64

### What did you do?

```
❯ bazel build //... --@io_bazel_rules_go//go/config:strip
INFO: Invocation ID: 548294b5-5b52-465c-ad99-b6361c85c0af
INFO: Invocation ID: 548294b5-5b52-465c-ad99-b6361c85c0af
ERROR: Unrecognized option: @io_bazel_rules_go//go/config:strip=true
```

### What did you see instead?

`Unrecognized option` error. Other options appear to work that are documented

**Comment by fmeum** [comment]
It's a `bool_setting` rather than a `bool_flag`, which explains the error. As to why it is I'm not sure.

@jayconrod I think this line hasn't changed since the switch to transitions. Could you explain the choice of not exposing this setting to users?

**Comment by aw185176** [comment]
Based on the wording in the docs, I would guess that it is probably an oversight: https://github.com/bazelbuild/rules_go/blob/master/go/modes.rst#build-settings

**Comment by fmeum** [comment]
@malt3 Sorry for the delay, I haven't forgotten about the PRs and will take another look soon. What's difficult about this is considering user expectations and potential implications for backwards compatibility, including with the usual Go toolchain.
