### ISSUE TITLE
Go version not correctly recongised

### ISSUE THREAD

**Issue by zakcutner** [bazelbuild/rules_go#3331]
### What version of rules_go are you using?

997520fc8d75fddc0ee51cec62833e748bb06000

When detecting the version of Go, rules_go expects the format to be of the form `go version go1.18.3 linux/amd64` in [`sdk.bzl`](https://github.com/bazelbuild/rules_go/blob/997520fc8d75fddc0ee51cec62833e748bb06000/go/private/sdk.bzl#L320). It then checks the third word of this output to determine the version.

However, development Go versions will be of the form `go version devel go1.18.3 linux/amd64`, so the Go version is not correctly determined in this case. I would suggest potentially checking the fourth word for the version instead if the third word  is `devel`.

**Comment by fmeum** [comment]
@zakcutner Do you think we could instead always check the second-to-last field? That would simplify the logic.

**Comment by zakcutner** [comment]
@fmeum That would make sense to me 👍

**Comment by fmeum** [comment]
Do you want to contribute the small fix? The relevant line is:
https://github.com/bazelbuild/rules_go/blob/997520fc8d75fddc0ee51cec62833e748bb06000/go/private/sdk.bzl#L322

**Comment by zakcutner** [comment]
Thanks! I'll open a PR shortly

**Comment by zakcutner** [comment]
Actually, on closer inspection it seems that reading the second last argument is not necessarily safe (see https://github.com/golang/go/issues/51876 for an example output). I'll update my PR with my previous idea, but let me know if you'd prefer something else
