### ISSUE TITLE
Fails to match host Go toolchain on linux/ppc64

### ISSUE THREAD

**Issue by mahiuchun** [bazelbuild/rules_go#3335]
### What version of rules_go are you using?

Git master

### What version of gazelle are you using?

None

### What version of Bazel are you using?

5.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes?

### What operating system and processor architecture are you using?

linux/ppc64

### Any other potentially useful information about your toolchain?

Go 1.19.2 toolchain for linux/ppc64 built from source

### What did you do?

Basic usage with `go_register_toolchains(version = "host")` and `go_binary` targets.
The same WORKSPACE and BUILD files have been tested on other platforms such as darwin/arm64 and windows/amd64.
See: https://github.com/mahiuchun/adventofcode-2018

### What did you expect to see?

It works like other platforms.

### What did you see instead?

It errors with something like `While resolving toolchains for target //day01:part2: no matching toolchains found for types @io_bazel_rules_go//go:toolchain`

**Comment by fmeum** [comment]
Could you run with `'--toolchain_resolution_debug=.*'` and post the log messages here?
