### ISSUE TITLE
bazel.FindBinary fails when the working directory is the workspace root.

### ISSUE THREAD

**Issue by matts1** [bazelbuild/rules_go#3339]
### What version of rules_go are you using?
0.34.0

### What version of gazelle are you using?

0.27.0

### What version of Bazel are you using?

6.0.0-pre.20221012.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux, x86-64

### Any other potentially useful information about your toolchain?

No

### What did you do?
```
if err := os.Chdir(<workspace root>); err != nil {
   log.Fatal(err)
}
bin, ok := bazel.FindBinary("dir", "mybinary")
if !ok {
  log.Fatal("Unable to find mybinary")
}
```

dir/BUILD.bazel:
```
go_binary(
  name = "mybinary",
  ...
)
```

### What did you expect to see?

binary found

### What did you see instead?
Binary not found

### Explanation
`bazel.FindBinary()` first calls `bazel.Runfile(pkg)` to get the directory the binary is contained within in the runfiles.

However, `bazel.Runfile` special-cases that if the thing you're searching for exists in the working directory, it will return that.
In this case, while the file dir/mybinary does not exist, the directory dir does. Thus, bazel.Runfile returns <workspace_root>/dir, instead of what bazel.FindBinary expects, which is $RUNFILES_DIR/dir.

This is usually a non-issue since dir normally would not exist in the current directory, but if you happen to be cd'd to the workspace root, it almost certainly will exist.

**Comment by fmeum** [comment]
The rules_go-provided runfiles functionality is, as you noticed, semi-broken. I would recommend using https://github.com/phst/runfiles instead until we have finished upstreaming it, which is tracked by https://github.com/bazelbuild/rules_go/issues/3036.

Please reopen if you run into issues with this library in your situation.
