### ISSUE TITLE
No BUILD file generated

### ISSUE THREAD

**Issue by nlamirault** [bazelbuild/rules_go#334]
Hi,
I try to use Bazel on a golang project. I build the project like that: 

```
go build -o diabloctl gitlab.sys.op.mbs/nimbus/diablo/cli
```

I use govendor for dependencies. I try this command : 

```
gazelle -go_prefix gitlab.sys.op.mbs/nimbus/diablo/cli -external vendored -mode print
```

No BUILD file generated. Any idea ? What is my error?
Thanks

**Comment by pmbethe09** [comment]
How can we replicate this?  Since it seems that gitlab.sys.op.mbs/nimbus/diablo/cli is not a publicly available path.

**Comment by nlamirault** [comment]
Yes ;(.
How can i debug that ? 
Can i activate some traces ?

**Comment by jayconrod** [comment]
@nlamirault, if `-mode print` is passed to Gazelle on the command line, it should just print the generated file without writing it to disk. Is it not printing anything for you? Does it write the file when you don't provide that option?

If Gazelle is behaving unexpectedly, it would help if you could provide a small repo that demonstrates the issue.
