### ISSUE TITLE
Rules_docker is broken with release of 36

### ISSUE THREAD

**Issue by Cartman75** [bazelbuild/rules_go#3361]
### What version of rules_go are you using?

0.36.0

### What version of gazelle are you using?

Not Defined.

### What version of Bazel are you using?

5.3.2

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Debian bullseye

### What did you expect to see?
Rules_docker be able to compile images

### What did you see instead?
Error: 
ERROR:` Traceback (most recent call last):
        File "/home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/bazel_gazelle/internal/go_repository_tools.bzl", line 15, column 52, in <toplevel>
                load("@io_bazel_rules_go//go/private:common.bzl", "env_execute", "executable_extension")
Error: file '@io_bazel_rules_go//go/private:common.bzl' does not contain symbol 'env_execute'
ERROR: error loading package '': at /home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/io_bazel_rules_docker/repositories/deps.bzl:22:6: at /home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/io_bazel_rules_docker/repositories/go_repositories.bzl:22:6: at /home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/bazel_gazelle/deps.bzl:24:5: initialization of module 'internal/go_repository_tools.bzl' failed

It looks like env_execute was mistakenly thought of not being used: 
https://github.com/bazelbuild/rules_go/pull/3276

**Comment by fmeum** [comment]
@Cartman75 bazel-gazelle stopped using that rules_go-internal method in https://github.com/bazelbuild/bazel-gazelle/commit/3e83644bd8b1ed373d322b898cf7c05927b39201#diff-c1403c382e16f440e9d5e59ebc70a6beb7f68f5ccefbcb5dd73e5cb9352e85a0, which is contained in the last five releases. rules_docker depends on a very old version of bazel-gazelle, so adding a more recent version of bazel-gazelle to your `WORKSPACE` explicitly (close to the top) should fix this issue.

**Comment by Cartman75** [comment]
You are right, adding gazelle fixed. it. Thanks!
