### ISSUE TITLE
mirror.bazel.build link for rules_go-v0.36.0.zip is 404

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/rules_go#3364]
### What version of rules_go are you using?

v0.36.0

### What did you do?

I added the WORKSPACE snippet from https://github.com/bazelbuild/rules_go/releases/tag/v0.36.0 to my repository.

### What did you expect to see?

No warnings during the build.

### What did you see instead?

WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.36.0/rules_go-v0.36.0.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found

**Comment by fmeum** [comment]
We are waiting for https://github.com/bazelbuild/bazel/issues/16833 to be acted on. I expect that to happen early next week.

**Comment by mostynb** [comment]
Looks like this is working now.
