### ISSUE TITLE
Editor wiki page references non-existent vscode-go "references" setting

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#3365]
The [Editor wiki page](https://github.com/bazelbuild/rules_go/wiki/Editor-setup) references a "references" setting inside `go.enableCodeLens`, but that setting [only supports the `runtest` boolean inside it](https://github.com/golang/vscode-go/blob/master/docs/settings.md#goenablecodelens).

(I'd fix this myself, but, of course, I don't have write privileges to the wiki!)

**Comment by achew22** [comment]
I think I've changed the setting to allow editing of the wiki by people in the community. Fortunately it appears to be version controlled, so this might go badly, but in the meantime feel free to modify to your hearts content!

**Comment by achew22** [comment]
I'd love it if you'd try making the change in the wiki to confirm that it is possible and close this issue if it is. If not, I'll make the change on Tuesday and look at the settings agian.

Thanks @jmhodges

**Comment by jmhodges** [comment]
Works! Thank you!
