### ISSUE TITLE
runfiles: error message `path "...." is not normalized` should be instructive

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_go#3374]
### What version of rules_go are you using?

v0.36.0

### What version of gazelle are you using?

Not sure

### What version of Bazel are you using?

5.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux

### Any other potentially useful information about your toolchain?

n/a

### What did you do?

`runfiles.Rlocation("external/com_google_protobuf_javascript//generator/protoc-gen-js")` returns an error that requires reading the code to understand:

```
path "external/com_google_protobuf_javascript//generator/protoc-gen-js" is not normalized
```

### What did you expect to see?

An error message that explains what corrective action should be taken.

### What did you see instead?

See above.

Suggested fix:

```go
func (r *Runfiles) Rlocation(path string) (string, error) {
	if r.impl == nil {
		return "", errors.New("runfiles: uninitialized Runfiles object")
	}

	if path == "" {
		return "", errors.New("runfiles: path may not be empty")
	}
	if !isNormalizedPath(path) {
		return "", fmt.Errorf("runfiles: path %q is not normalized", path)
	}

	// See https://github.com/bazelbuild/bazel/commit/b961b0ad6cc2578b98d0a307581e23e73392ad02
	if strings.HasPrefix(path, `\`) {
		return "", fmt.Errorf("runfiles: path %q is absolute without a drive letter", path)
	}
	if filepath.IsAbs(path) {
		return path, nil
	}

	p, err := r.impl.path(path)
	if err != nil {
		return "", Error{path, err}
	}
	return p, nil
}

func isNormalizedPath(s string) bool {
	return !strings.HasPrefix(s, "../") && !strings.Contains(s, "/..") &&
		!strings.HasPrefix(s, "./") && !strings.HasSuffix(s, "/.") &&
		!strings.Contains(s, "/./") && !strings.Contains(s, "//")
}
```

change `isNormalizedPath() bool` to `checkNormalizedPath(s string) error` that prints something like "path should not contain multiple adjacent slashes"

**Comment by fmeum** [comment]
Very good point, I submitted https://github.com/bazelbuild/rules_go/pull/3378 to improve the error message and also fix a small bug. Please take a look!

**Comment by gonzojive** [comment]
sweet, thanks.
