### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break rules_go in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_go#3386]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_go. Please migrate to fix this and unblock the flip of this flag.

---> Note that this was not an issue until build [#1349](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1349) and has been failing from [#1351](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1351) onwards. 

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1356#0184ea22-5e2d-4875-8d65-232ad4b8a493)
- [Ubuntu 20.04, OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1356#0184ea22-5e2a-43ae-865d-0b1afb7ca794)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1356#0184ea22-5e2f-465f-8710-e2332f5ce4b3)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by fmeum** [comment]
I created https://github.com/bazelbuild/rules_go/pull/3387 to fix this.
