### ISSUE TITLE
`go_download_sdk` should use the exec OS and arch instead of the host

### ISSUE THREAD

**Issue by jpsim** [bazelbuild/rules_go#3402]
My goal is to compile something using rules_go on a macOS arm64 host, using a macOS amd64 remote executor.

From my understanding of reading the [bazel docs on platforms](https://bazel.build/extending/platforms), it seems like instead of downloading the toolchain for the host platform, it should download it for the exec platform.

https://github.com/bazelbuild/rules_go/blob/1a8fe64877c6e71dbbf51cdc8ceb2eb10c13e521/go/private/sdk.bzl#L359-L372

### What version of rules_go are you using?

https://github.com/bazelbuild/rules_go/releases/tag/v0.36.0

### What version of gazelle are you using?

https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.26.0

### What version of Bazel are you using?

`6.0.0rc4`

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Host: macOS 13 (arm64)
Exec: macOS 13 (amd64)

### Any other potentially useful information about your toolchain?

Using remote execution.

### What did you do?

```console
$ git clone https://github.com/envoyproxy/envoy.git
$ cd envoy/mobile
# ./bazelw build \
  --tls_client_certificate=<redacted> \
  --tls_client_key=<redacted> \
  --config remote-ci-macos \
  //library/common:envoy_main_interface_lib
```

### What did you expect to see?

I expected `go_download_sdk` to download the darwin/arm64 version of the SDK.

### What did you see instead?

I see a toolchain resolution error:

> ERROR: /private/var/tmp/_bazel_jsimard/e99b8d924fe95f277e909ecdb8681535/external/com_envoyproxy_protoc_gen_validate/BUILD:11:10: While resolving toolchains for target @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate: No matching toolchains found for types @io_bazel_rules_go//go:toolchain.

Here's a link to the invocation on EngFlow: https://envoy.cluster.engflow.com/invocation/7c14f5f1-1765-4589-8562-b1c5fc86318a#console

---

With https://github.com/envoyproxy/envoy/pull/24501 I can get past the toolchain resolution error when using remote exec on a macOS amd64 host and a macOS arm64 remote executor, but then the toolchain resolution fails on Linux ([CI logs](https://github.com/envoyproxy/envoy/actions/runs/3679971288/jobs/6225402653)).

**Comment by fmeum** [comment]
`rules_go` can't declare a Go SDK just for the exec platform as that platform isn't known at the time where external dependencies are declared.

Instead, we should declare Go SDKs for all platforms rather than just the host, register them all and let toolchain resolution handle the rest.

Today, https://github.com/envoyproxy/envoy/pull/24501 leads in the right direction: You should be able to have two `go_download_sdk` invocations with different names, one for Linux and one for macOS arm64. Could you give that a try?

**Comment by jpsim** [comment]
Thanks for your response!

> `rules_go` can't declare a Go SDK just for the exec platform as that platform isn't known at the time where external dependencies are declared.

That actually makes a lot of sense.

> Instead, we should declare Go SDKs for all platforms rather than just the host, register them all and let toolchain resolution handle the rest.

Ideally we'd be able to just add _additional_ platforms to declare, so that the host-determining logic is used plus the extra platforms that we know we might want to use RBE across.

For example:

```starlark
go_register_toolchains(
    go_version,
    additional_platforms = ["darwin/amd64"],
)
```

> You should be able to have two `go_download_sdk` invocations with different names, one for Linux and one for macOS arm64. Could you give that a try?

I gave that a shot just now in https://github.com/envoyproxy/envoy/pull/24501, but I'm now seeing new toolchain resolution errors on Linux: https://github.com/envoyproxy/envoy/actions/runs/3713725354/jobs/6296724743

**Comment by fmeum** [comment]
@jpsim You have to give the SDKs different names and register them via `register_toolchains("@go_sdk_toolchains//:all")` (with `go_sdk` replaced by the respective name).

**Comment by jpsim** [comment]
Giving the SDKs different names: https://github.com/envoyproxy/envoy/pull/24501/commits/148d86384818165fd15e8e633d3c493c2670136d

However, `register_toolchains("@go_sdk_toolchains//:all")` or `go_ register_toolchains("@go_sdk_toolchains//:all")` replacing `go_sdk` with all the names isn't working for me. I'm sure I'm making an obvious mistake.

First, `register_toolchains` isn't defined anywhere I can find, so if I put:

```starlark
go_download_sdk(
    name = "go_darwin_amd64",
    goos = "darwin",
    goarch = "amd64",
    version = go_version,
)
register_toolchains("@go_darwin_amd64_toolchains//:all")
```

I get an `'register_toolchains' is not defined` error. So then I try with `go_register_toolchains` which is defined:

```starlark
go_download_sdk(
    name = "go_darwin_amd64",
    goos = "darwin",
    goarch = "amd64",
    version = go_version,
)
go_register_toolchains("@go_darwin_amd64_toolchains//:all")
```

Which gives me the next error message:

```
ERROR: Traceback (most recent call last):
	File "/Users/jsimard/src/envoy/mobile/WORKSPACE", line 55, column 25, in <toplevel>
		envoy_dependency_imports()
	File "/private/var/tmp/_bazel_jsimard/e99b8d924fe95f277e909ecdb8681535/external/envoy/bazel/dependency_imports.bzl", line 33, column 27, in envoy_dependency_imports
		go_register_toolchains("@go_darwin_amd64_toolchains//:all")
	File "/private/var/tmp/_bazel_jsimard/e99b8d924fe95f277e909ecdb8681535/external/io_bazel_rules_go/go/private/sdk.bzl", line 434, column 13, in go_register_toolchains
		fail("go_register_toolchains: version set after go sdk rule declared ({})".format(", ".join([r["name"] for r in sdk_rules])))
Error in fail: go_register_toolchains: version set after go sdk rule declared (go_darwin_amd64)
ERROR: Error computing the main repository mapping: at /Users/jsimard/src/envoy/mobile/bazel/envoy_mobile_dependencies.bzl:3:6: Encountered error while reading extension file 'lib/repositories.bzl': no such package '@build_bazel_apple_support//lib': error loading package 'external': Could not load //external package
```

Seems like maybe an ordering issue, but if I try to move it up like this:

```starlark
go_register_toolchains("@go_darwin_amd64_toolchains//:all")
go_download_sdk(
    name = "go_darwin_amd64",
    goos = "darwin",
    goarch = "amd64",
    version = go_version,
)
```

I get this error:

```
ERROR: Traceback (most recent call last):
	File "/Users/jsimard/src/envoy/mobile/WORKSPACE", line 55, column 25, in <toplevel>
		envoy_dependency_imports()
	File "/private/var/tmp/_bazel_jsimard/e99b8d924fe95f277e909ecdb8681535/external/envoy/bazel/dependency_imports.bzl", line 27, column 27, in envoy_dependency_imports
		go_register_toolchains("@go_darwin_amd64_toolchains//:all")
	File "/private/var/tmp/_bazel_jsimard/e99b8d924fe95f277e909ecdb8681535/external/io_bazel_rules_go/go/private/sdk.bzl", line 443, column 21, in go_register_toolchains
		fail('go_register_toolchains: version must be a string like "1.15.5" or "host"')
Error in fail: go_register_toolchains: version must be a string like "1.15.5" or "host"
ERROR: Error computing the main repository mapping: at /Users/jsimard/src/envoy/mobile/bazel/envoy_mobile_dependencies.bzl:3:6: Encountered error while reading extension file 'lib/repositories.bzl': no such package '@build_bazel_apple_support//lib': error loading package 'external': Could not load //external package
```

However, my PR seems fine so far without that, only adding the `go_download_sdk` declarations per platform.

**Comment by fmeum** [comment]
@jpsim Sorry, since you are in the context of a macro, you need to use `native.register_toolchains` instead of just `register_toolchains`.
