### ISSUE TITLE
support go:embed of generated files failing

### ISSUE THREAD

**Issue by bakjos** [bazelbuild/rules_go#3405]
### What version of rules_go are you using?
0.37.0

### What version of gazelle are you using?
0.28.0

### What version of Bazel are you using?
5.4.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
OSX x64 

### What did you do?

When I tried to run the compilation process with the latest release, the embedsrc was failing when using go_path, due a relativize issue

### What did you expect to see?
Compiling correctly

### What did you see instead?
```
 File "/external/io_bazel_rules_go/go/private/tools/path.bzl", line 89, column 51, in _go_path_impl
                dst = pkg.dir + "/" + paths.relativize(embedpath, src_dir)
        File "external/bazel_skylib/lib/paths.bzl", line 182, column 13, in _relativize
                fail("Path '%s' is not beneath '%s'" % (path, start))
Error in fail: Path 'services/test/graphql/schema.graphql' is not beneath 'bazel-out/darwin-fastbuild/bin/services/test/graphql'
```

**Comment by mrkkrp** [comment]
Should this be closed? Seemingly resolved by #3407.
