### ISSUE TITLE
tag new version of rules_go

### ISSUE THREAD

**Issue by rsc** [bazelbuild/rules_go#3417]
We would like to be able to point people at the updated rules_go that can handle Go 1.20's missing .a files. The changes have landed but rules_go has not been tagged since early December. Can a new version be tagged? Thanks!

**Comment by fmeum** [comment]
While we can release a new version that will work with Go 1.20, it will be noticeably slower with the new version unless users also specify certain experimental Bazel flags that I'm still working on getting enabled by default. I can add a section to the README documenting these flags and their impact.

**Comment by fmeum** [comment]
https://github.com/bazelbuild/rules_go/releases/tag/v0.38.0 is available now.
