### ISSUE TITLE
default build_file_proto_mode to disable for org_golang_google_grpc

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_go#3421]
I wasted some time yesterday with a MODULE.bazel file containing
```
go_deps.module(
    path = "google.golang.org/grpc",
    version = "v1.50.1",
    sum = "h1:DS/BukOZWp8s6p4Dt/tOaJaTQyPyOoCcrjroHuCeLzY=",
)
```
because it needs `build_file_proto_mode`:
https://github.com/bazelbuild/rules_go/blob/5d306c433cebb1ae8a7b72df2a055be2bacbb12b/go/dependencies.rst#grpc-dependencies
> Make sure you set build_file_proto_mode = "disable" on the [go_repository](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) rule for org_golang_google_grpc

Is there some reason we don't just special-case the default value for that attribute for this particular dependency, so users don't have to discover that documentation?

**Comment by fmeum** [comment]
I am open to having a list of default options for common repos, but I first want to understand why that option even exists and isn't determined automatically.

@linzhp @jayconrod Do you know why setting `build_file_proto_mode` is required for `grpc-go` and whether Gazelle could figure out the correct value automatically?

**Comment by jayconrod** [comment]
I think it would be reasonable for either Gazelle or `go_repository` (which invokes Gazelle) to have modified defaults for specific repositories. There's some precedence for that already: there's a huge hard-coded table for resolving imports of  Well Known Types and Google APIs. Kind of a mess, but it's there.

Some background: I didn't have a deep enough understanding of the workflow around protos at the time I worked on `go_proto_library` and the Gazelle support for it, and there's a lot of stuff that's not ideal. A lot's changed with Go modules and the way Google publishes its APIs. There's a fair amount of stuff in there that could be rebuilt or is unintentionally difficult to use.

**Comment by fmeum** [comment]
A registry for Gazelle defaults has been added in https://github.com/bazelbuild/bazel-gazelle/commit/9c4a8d444274b09d67e583cdb80186296d73c54d#diff-f1d8b5185fca685701a36cbb85f15ea03899288c1a7f8bbe9a9acb356a530ee0 at `internal/bzlmod/directives.bzl` by @seh. It will become available with the next release.

**Comment by alexeagle** [comment]
I think this was fixed in bazel-gazelle, based on that last comment. Thanks!
