### ISSUE TITLE
Allow overriding the Go SDK version more succinctly in MODULE.bazel

### ISSUE THREAD

**Issue by seh** [bazelbuild/rules_go#3436]
### What version of rules_go are you using?

0.38.1

### What version of gazelle are you using?

0.27.0

### What version of Bazel are you using?

6.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS, x86_64

### What did you do?

Consume _rules_go_ in my Bazel project as a module, overriding the default Go SDK version:
```starlark
bazel_dep(name = "rules_go", version = "0.38.1")

# Tailor the Go SDK that we use here.
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(
    name = "go_custom_sdk",
    version = "1.19.5",
)
use_repo(go_sdk, "go_custom_sdk_toolchains")

register_toolchains("@go_custom_sdk_toolchains//:all")
```

### What did you expect to see?

Per [discussion in the "go" channel of the "Bazel" Slack workspace](https://bazelbuild.slack.com/archives/CDBP88Z0D/p1675106805343659), while the above code works as intended, it's rather verbose.

Based on discussion with @fmeum, I tried reducing it further to the following:
```starlark
bazel_dep(name = "rules_go", version = "0.38.1")

# Tailor the Go SDK that we use here.
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(
    name = "go_custom_sdk", # Should this be required?
    version = "1.19.5",
)
```
While Bazel evaluates this code without complaint, the "name" field required by `go_sdk`'s "download" tag doesn't appear to be used for anything there.

However, this turns out not to work correctly: the Go toolchain isn't registered, and Bazel falls back to using the default Go toolchain at version 1.18.3.

### What did you see instead?

It would be helpful if callers didn't need to define the alternate repository name for the toolchain and register it explicitly. In other words, if there was some way for _rules_go_ to allow just changing the SDK version more succinctly and safely, it would be better than the explicit but verbose technique required today.

**Comment by fmeum** [comment]
@Wyverald and I came up with a plan to get rid of all toolchain repo names, which prevents name collisions between Bazel modules and also gets rid of the `use_repo` and `register_toolchains` ceremony. Instead, one would simply do:

```
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.19.5")
```

The toolchains would be registered automatically in the same order as with regular `bazel_dep`s. Direct access to SDK repos is no longer possible, but in the presence of multi-platform and remote builds hasn't really been correct anyways. Instead, users would rely on https://github.com/bazelbuild/rules_go/pull/3429 to get access to the correct SDK.

**Comment by mkmik** [comment]
> @Wyverald and I came up with a plan to get rid of all toolchain repo names, which prevents name collisions between Bazel modules and also gets rid of the `use_repo` and `register_toolchains` ceremony. Instead, one would simply do:
> 
> ```
> go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
> go_sdk.download(version = "1.19.5")
> # or even
> use_extension("@rules_go//go:extensions.bzl", "go_sdk").download(version = "1.19.5")
> ```
 

I tried that with bazel version `7.0.2` and rules_go version `0.46.0` and it seems to have worked just fine with:

```bazel
go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.22.0")
```

I uploaded a reproducer repo in https://github.com/mkmik/sdkversionrepro

Does it mean this issue has been fixed or am I misunderstanding something subtle here? Perhaps now I have two toolchains and some tools are using the default one while my builds are using my custom one?

**Comment by fmeum** [comment]
@mkmik That's correct, it's been fixed and your approach is exactly right.

**Comment by mkmik** [comment]
@fmeum d
What happens if I give an explicit name parameter to the download function?

I noticed that the external produced by download has some nondescript name that shows up in the externals directory (and in the logs etc). I'm tempted to give it a nice name like "my_go_sdk". Would that get in the way of something?
