### ISSUE TITLE
Bazel 6 break rules_go?

### ISSUE THREAD

**Issue by Cartman75** [bazelbuild/rules_go#3442]
### What version of rules_go are you using?
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "19ef30b21eae581177e0028f6f4b1f54c66467017be33d211ab6fc81da01ea4d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.38.0/rules_go-v0.38.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.38.0/rules_go-v0.38.0.zip",
    ],
)

### What version of gazelle are you using?
http_archive(
    name = "bazel_gazelle",
    sha256 = "ecba0f04f96b4960a5b250c8e8eeec42281035970aa8852dda73098274d14a1d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
    ],
)

### What version of Bazel are you using?

Trying to upgrade to bazel 6

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### What did you expect to see?
When I upgrade from the latest 5.x version to 6, no other changes, it looks like rules_go breaks. 

INFO: Build option --toolchain_resolution_debug has changed, discarding analysis cache.
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_aix_ppc64-impl; mismatching values: aix, ppc
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_android_386-impl; mismatching values: android, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_android_amd64-impl; mismatching values: android, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_android_arm-impl; mismatching values: android, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_android_arm64-impl; mismatching values: android, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_darwin_386-impl; mismatching values: osx, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_darwin_amd64-impl; mismatching values: osx, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_darwin_arm-impl; mismatching values: osx, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_darwin_arm64-impl; mismatching values: osx, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_dragonfly_amd64-impl; mismatching values: dragonfly, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_freebsd_386-impl; mismatching values: freebsd, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_freebsd_amd64-impl; mismatching values: freebsd, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_freebsd_arm-impl; mismatching values: freebsd, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_freebsd_arm64-impl; mismatching values: freebsd, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_illumos_amd64-impl; mismatching values: illumos, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_ios_amd64-impl; mismatching values: ios, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_ios_arm64-impl; mismatching values: ios, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_js_wasm-impl; mismatching values: js, wasm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_386-impl; mismatching values: linux, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_amd64-impl; mismatching values: linux, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_arm-impl; mismatching values: linux, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_arm64-impl; mismatching values: linux, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_mips-impl; mismatching values: linux, mips
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_mips64-impl; mismatching values: linux, mips64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_mips64le-impl; mismatching values: linux, mips64le
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_mipsle-impl; mismatching values: linux, mipsle
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_ppc64-impl; mismatching values: linux, ppc
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_ppc64le-impl; mismatching values: linux, ppc
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_riscv64-impl; mismatching values: linux, riscv64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_linux_s390x-impl; mismatching values: linux, s390x
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_nacl_386-impl; mismatching values: nacl, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_nacl_amd64p32-impl; mismatching values: nacl, amd64p32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_nacl_arm-impl; mismatching values: nacl, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_netbsd_386-impl; mismatching values: netbsd, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_netbsd_amd64-impl; mismatching values: netbsd, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_netbsd_arm-impl; mismatching values: netbsd, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_netbsd_arm64-impl; mismatching values: netbsd, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_openbsd_386-impl; mismatching values: openbsd, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_openbsd_amd64-impl; mismatching values: openbsd, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_openbsd_arm-impl; mismatching values: openbsd, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_openbsd_arm64-impl; mismatching values: openbsd, arm64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_plan9_386-impl; mismatching values: plan9, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_plan9_amd64-impl; mismatching values: plan9, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_plan9_arm-impl; mismatching values: plan9, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_solaris_amd64-impl; mismatching values: solaris, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_windows_386-impl; mismatching values: windows, x86_32
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_windows_amd64-impl; mismatching values: windows, x86_64
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_windows_arm-impl; mismatching values: windows, arm
INFO: ToolchainResolution:     Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: Rejected toolchain @go_sdk//:go_windows_arm64-impl; mismatching values: windows, arm64
INFO: ToolchainResolution:   Type @io_bazel_rules_go//go:toolchain: target platform @local_config_platform//:host: No toolchains found.
INFO: Repository go_puller_darwin instantiated at:
  /home/tradergt/modules/dba-utilities/WORKSPACE:83:23: in <toplevel>
  /home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/io_bazel_rules_docker/repositories/repositories.bzl:60:18: in repositories
Repository rule http_file defined at:
  /home/tradergt/.cache/bazel/_bazel_tradergt/5ec41db2c4e272bc949a06a673e6483b/external/bazel_tools/tools/build_defs/repo/http.bzl:466:28: in <toplevel>
ERROR: /home/tradergt/modules/dba-utilities/common/golib/BUILD:1:11: While resolving toolchains for target //common/golib:VirtualTable: No matching toolchains found for types @io_bazel_rules_go//go:toolchain.
To debug, rerun with --toolchain_resolution_debug='@io_bazel_rules_go//go:toolchain'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//common/golib:VirtualTable' failed; build aborted:
INFO: Elapsed time: 16.871s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 739 targets configured)
    currently loading: @lazy_deps_absl_py// ... (28 packages)
    Fetching repository @lazy_deps_switch; starting
    Fetching repository @lazy_deps_urllib3; starting
ERROR: Couldn't start the build. Unable to run tests

### What did you see instead?
It compiles and run unit tests.

**Comment by Clement-Jean** [comment]
I have a similar issue (toolchain error) with Bazel 6 with the following error:

```
@remote_coverage_tools//:Main: No matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
```

But I simply ran: `bazel test //...`. I did not ask for coverage.

**Comment by fmeum** [comment]
@Clement-Jean Which version of Bazel are you on? https://github.com/bazelbuild/bazel/commit/1a438b41b74d94fd8b6ff4dcf20b4526530e3c6e is in 6.1.0 and should fix this.

**Comment by Clement-Jean** [comment]
I'm on NixOS and the bazel_6 package is version 6.0.0, I'll try to update that. Thank you

**Comment by Cartman75** [comment]
@Clement-Jean Your issue is different than mine...
@fmeum IS there anything I can do about the issue I am seeing? I can't upgrade to 6 at all with this issue.

**Comment by fmeum** [comment]
@Cartman75 Do you have a reproducer you can share? Just from the toolchain resolution debug output I can't tell what's wrong in your situation. Are you trying to cross-compile Go?

**Comment by Cartman75** [comment]
Its very simple code. We are a major python shop, and I created some code mostly because I was figuring it out. In 5x, this is fine:

```load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "VirtualTable",
    srcs = ["VirtualTable.go"],
    importpath = "dbautils/common/golib/VirtualTable",
    visibility = ["//visibility:public"],
)

go_test(
    name = "VirtualTable_test",
    size = "small",
    srcs = ["VirtualTable_test.go"],
    embed = [":VirtualTable"],
)```

I am NOT trying to cross-compile. But it feels like it's trying to? 
Also, if I remove all 2 pieces of code we have for go, all goes well until it gets to building docker, then this error returns.

WORKSPACE and go: 

```# See https://github.com/bazelbuild/rules_go for the up to date setup instructions.
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "6b65cb7917b4d1709f9410ffe00ecf3e160edf674b78c54a894471320862184f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "ecba0f04f96b4960a5b250c8e8eeec42281035970aa8852dda73098274d14a1d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.2")

gazelle_dependencies()```

It feels like a default was removed or something, and its not configuring my environment right, go wise. Our entire python stack works fine.

**Comment by Cartman75** [comment]
Let me see if I can come up with something today,

**Comment by Cartman75** [comment]
Ugh, I figured it out. I had this in my .bazelrc file
```
common --experimental_enable_bzlmod
```
Removing that and it's all working on 6.1.1 now. Thanks and sorry for the noise..

**Comment by mrmeku** [comment]
I believe this is just the rules_go caveat of this bazel build: https://github.com/bazelbuild/bazel/issues/17289
