### ISSUE TITLE
Select deps / cdeps based on gotags

### ISSUE THREAD

**Issue by malt3** [bazelbuild/rules_go#3444]
### What version of rules_go are you using?

v0.37.0

### What version of gazelle are you using?

bazel-gazelle-af021617bef884e1e40afb01b692092a471d9a48 (latest commit)

### What version of Bazel are you using?

6.0.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

- 5.15.0-58-generic Ubuntu SMP x86_64 GNU/Linux
- Ubuntu 22.04.1

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

I'm trying to conditionally depend on a `cdep` based on a go build tag.
Consider the following (imaginary) example:

BUILD.bazel
```bazel
load("@io_bazel_rules_go//go:def.bzl",  "go_binary", "go_library")

go_library(
    name = "simulator",
    srcs = [
        "simulator.go",
        "simulator_disabled.go",
    ],
    importpath = "github.com/malt3/example/simulator",
    visibility = ["//:__subpackages__"],
    deps = select({
        "@io_bazel_rules_go//go/gotags:enable_simulator": [
            "@com_github_google_go_tpm_tools//simulator",
        ],
        "//conditions:default": [],
    }),
)

go_binary(
    name = "foo_no_simulator",
    srcs = ["foo.go"],
    importpath = "github.com/malt3/example/simulator",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "foo_simulator",
    srcs = ["foo.go"],
    gotags = ["enable_simulator"],
    importpath = "github.com/malt3/example/simulator",
    visibility = ["//visibility:public"],
)
```

simulator.go
```go
//go:build enable_simulator

package simulator

import "github.com/google/go-tpm-tools/simulator"

func UseSimulator() {
    // Uses dependency ....
    // ... 
}
```

simulator_disabled.go
```go
//go:build !enable_simulator

package simulator

func UseSimulator() { /* does nothing */ }
```

foo.go
```go
package simulator

func main() {
    UseSimulator()
}
```

### What did you expect to see?

I would expect to have a method to `select` dependencies (`deps` or `cdeps`) based on `gotags` of the go_binary rules.
This example works when using `go build` by either setting `go build -tags enable_simulator` or not setting the tag.

### What did you see instead?

I cannot find a method to select deps based on tags. The code either has to include the dep or not. I can select deps on other constraints (os, architecture..) but not on tags.

**Comment by fmeum** [comment]
There is currently no way in Bazel to select on a particular value being present in a list-valued settings, so I fear this can't be supported by rules_go directly. Maybe there is something else we can do, but I don't see a good solution yet

**Comment by fmeum** [comment]
Just note that the Bazel way to do this, which is working today, would be to introduce a custom build setting and then select both go build tags and cdeps based on that.

**Comment by malt3** [comment]
Thanks. For reference, I think you mean the feature used [in this example code](https://github.com/bazelbuild/examples/tree/b88cad9825e80b73894154c8b73aefe8d5791bd4/configurations/basic_build_setting). 
Can I define two `go_binary` rules in the same build that use different values for a build setting?
I want to `bazel build ...` and get both binaries as a result and not build twice with different settings.

**Comment by fmeum** [comment]
[`go_cross_binary`](https://github.com/bazelbuild/rules_go/blob/13e02a919127bc5826006dff9dc1446ffb3e848d/go/private/rules/cross.bzl#L128) could also serve as inspiration.

I will close this issue since Bazel offers all the tools to achieve this goal today, even if they aren't optimized for usability yet. Feel free to reopen if you think something is missing.
