### ISSUE TITLE
Transitive dependencies on go_proto_library cause unexpected proto to import path mapping

### ISSUE THREAD

**Issue by sessfeld** [bazelbuild/rules_go#3445]
### What version of rules_go are you using?

v0.38.1

### What version of gazelle are you using?

v0.29.0

### What version of Bazel are you using?

v6.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS aarch64

### Any other potentially useful information about your toolchain?

No

### What did you do?

When depending on code in go_proto_library, it is possible that transitive dependencies introduce unexpected `.proto` to import path mapping. [See this repo that reproduces the issue](https://github.com/sessfeld/rules-go-ptypes-repro).

The `go_proto_library` depends on `@org_golang_google_genproto//googleapis/longrunning`, and that includes `@ io_bazel_rules_go//proto/wkt:timestamp_go_proto`. When the rules runs, an aspect traverses all `go_proto_libraries` in the transitive dependencies and collects a mapping of Proto file to import path. The wkt rule adds the mapping `google/protobuf/timestamp.proto` to `github.com/golang/protobuf/ptypes/timestamp`.

The compiler rule includes all well-known types from their location in `google.golang.org`. That means it's then missing the strict dependency and fails the build.

### What did you expect to see?

The generated Go file to import `Timestamp` from `google.golang.org/protobuf/types/known/timestamppb`.

### What did you see instead?

The generated Go file imports `Timestamp` from `github.com/golang/protobuf/ptypes/timestamp`.

I would suggest that we remove the special handling for those well-known types altogether. If I understand it correctly, when using the rules as is, the WKTs always come precompiled from `google.golang.org/protobuf/types/known/...`. I believe the special handling for the old WKTs is probably there for historical reasons, but I believe they aren't really required anymore.

**Comment by kyle-hiller-nh** [comment]
The patch file in your repro fixed this issue for me. Thank you!

**Comment by sessfeld** [comment]
This is resolved by #3595
