### ISSUE TITLE
Jenkins builds are failing with Bazel at HEAD

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#349]
http://ci.bazel.io/job/rules_go/754/

**Comment by pmbethe09** [comment]
/home/ci/workspace/rules_go/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/.bin/bazel: line 3: /home/ci/.bazel/HEAD/bin/bazel: No such file or directory

Seems like a bazel issue

**Comment by jayconrod** [comment]
Yeah, I think so, too. I've emailed bazel-discuss.

We're also seeing instability in Darwin builds. I haven't been able to reproduce that locally, and we're not seeing it in Travis CI. The last successful "HEAD" build that Travis downloads is a couple days old (March 29). Jenkins may be testing a newer, broken version.

**Comment by jayconrod** [comment]
The failures in Darwin builds are happening in cgo targets, both with Bazel HEAD and 0.4.5. The processes are getting killed with signal 9.

I think the underlying issue is https://github.com/golang/go/issues/19734. Upgrading Xcode to 8.3 exposes a DWARF alignment bug. I can't confirm whether Jenkins is running Xcode 8.3, but this does explain why I'm not seeing the issue on my laptop running 8.2.

**Comment by jayconrod** [comment]
I reproduced the Darwin issue on my laptop after upgrading to Xcode 8.3. Also confirmed it's possible to work around by passing the `-s` flag to the Go linker (symbol table can't be misaligned if you don't emit it at all).

The fix for this issue should be ported to Go 1.8.1, which isn't too far away. My inclination is to wait until that's released, then fix this just by upgrading the default in `go_repositories`. We could try to workaround this by adding `-s` depending on Xcode version and Go version, but that seems too magical. There are already some [problems and workarounds](https://github.com/bazelbuild/rules_go/blob/e319b92040ea11df99e7efbf4ff39eacf5a5c686/go/def.bzl#L505) related to `-s`.

**Comment by jayconrod** [comment]
Jenkins builds are passing since we added support for Go 1.8.1.
