### ISSUE TITLE
cgo_library() cannot find source files when used with new_git_repository()

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_go#35]
@yugui This is a followup to https://github.com/bazelbuild/rules_go/commit/bb7e87b63d33c24770cb21974bcc8ae00f8f9d07.

When using `cgo_library()` with `new_git_repository()` bazel is unable to find source files. For example, consider https://golang.org/x/sys/unix.

```bzl
...

SYS_UNIX_BUILD = """
load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_library", "cgo_library")
go_prefix("golang.org/x/sys/unix")
go_library(
    name = "go_default_library",
    srcs = glob([
        "unix/*_linux_amd64.s",
        "unix/*_linux.go",
        "unix/*_linux_amd64.go",
        "unix/*_unix.go",
        "unix/syscall.go",
        "unix/race0.go",
        "unix/str.go",
      ],
      exclude = ["unix/types_linux.go", "unix/gccgo_*"],
    ),
    deps = [
        ":types_linux",
    ],
    visibility = ["//visibility:public"],
)

cgo_library(
    name = "types_linux",
    srcs = ["unix/types_linux.go"],
)
"""
new_git_repository(
    name = "org_golang_x_sys_unix",
    remote = "https://go.googlesource.com/sys",
    commit = "076b546753157f758b316e59bcb51e6807c04057",
    build_file_content = SYS_UNIX_BUILD,
)
```

When building, I receive the following error:

```
ahochhaus@debian:~/ll$ b build ...
INFO: Found 51 targets...
ERROR: /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/org_golang_x_sys_unix/BUILD:23:1: error executing shell command: 'export GOROOT=$(pwd)/external/golang_linux_amd64/go/bin/.. && export CC=$(cd $(dirname /usr/bin/gcc); pwd)/$(basename /usr/bin/gcc) && export CXX=$CC && objdir=$(pwd)/bazel-out/local-fastbuild/genf...' failed: namespace-sandbox failed: error executing command /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/ll/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
open unix/types_linux.go: no such file or directory
INFO: Elapsed time: 21.208s, Critical Path: 20.88s
```

Is `cgo_library()` expected to work with `new_git_repository()`?

**Comment by hochhaus** [comment]
@yugui Thanks. I can confirm that your fix resolves my issue. Could this change be moved to the master branch?

**Comment by hochhaus** [comment]
@yugui This fix works to allow use of files in a `cgo_library()` from `new_git_repository()` in bazel 0.2.3. However, with bazel 0.3.0, it fails with the file not found error. Can we reopen this issue for bazel 0.3.0?

**Comment by yugui** [comment]
@hochhaus 
Sure.  Sorry for your inconvenience.

**Comment by hochhaus** [comment]
No problem! Thanks for taking a look.

**Comment by yugui** [comment]
Note for investigation:

`short_path` of the file "@org_golang_x_sys//:unix/types_linux.go" used to be `external/org_golang_x_sys/unix/types_linux.go` but not it is `../org_golang_x_sys/unix/types_linux.go`

I am wondering if this is an issue of Bazel because `"/".join([f.root.path, f.short_path])` is different from `f.path`.

**Comment by yugui** [comment]
Looks to be a side-effect of the runfiles structure change in Bazel 0.3.0.
