### ISSUE TITLE
SDK registration no longer detecting go_download_sdk

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/rules_go#3510]
[This PR ](https://github.com/bazelbuild/rules_go/pull/3443) broke [buildbuddy](https://github.com/buildbuddy-io/buildbuddy) repo when upgrading from v0.38.1 to v0.39.1.

```
ERROR: Traceback (most recent call last):
        File "/Users/sluongng/work/buildbuddy/buildbuddy/WORKSPACE", line 81, column 23, in <toplevel>
                go_register_toolchains(
        File "/private/var/tmp/_bazel_sluongng/06e573a93bc2d6a9cad4ad41f00b4310/external/io_bazel_rules_go/go/private/sdk.bzl", line 641, column 17, in go_register_toolchains
                fail('go_register_toolchains: version must be a string like "1.15.5" or "host"')
Error in fail: go_register_toolchains: version must be a string like "1.15.5" or "host"
```

Here is the bisect that I used 

```
> cat test-build.sh
#!/bin/bash

(
  cd /Users/sluongng/work/buildbuddy/buildbuddy
  bazel build cli --override_repository=io_bazel_rules_go=/Users/sluongng/work/bazelbuild/rules_go
)
```

Bisect run
```
  cd /Users/sluongng/work/bazelbuild/rules_go
  git bisect start --first-parent
  git bisect bad HEAD # this is latest master (e558f56df9995f571e49de336c3831d407d9ff70)
  git bisect good v0.38.1
  git bisect run ./test-build.sh
```

Most likely this has something to do with how our repo is registering separate Go SDK using `go_download_sdk` calls to avoid some `transition` cross-compilation we found in the past. https://github.com/buildbuddy-io/buildbuddy/blob/ede1e1d07122a3bdd22a61b31dd7c6a8d8bd458d/WORKSPACE#L53-L83

cc: @fmeum @tyler-french

**Comment by fmeum** [comment]
I suspect that this line is now out-of-date: https://github.com/bazelbuild/rules_go/blob/e558f56df9995f571e49de336c3831d407d9ff70/go/private/sdk.bzl#L642

@sluongng Could you check whether that's all that broke and potentially submit a PR?

**Comment by sluongng** [comment]
thanks for the hint, PR submitted 🤗
