### ISSUE TITLE
`gopackagesdriver` doesn't work with golangci-lint

### ISSUE THREAD

**Issue by grampelberg** [bazelbuild/rules_go#3523]
### What version of rules_go are you using?

v0.39.0

### What version of gazelle are you using?

v0.30.0

### What version of Bazel are you using?

6.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

linux-amd64

### What did you do?

Exported `GOPACKAGESDRIVER` and `GOPACKAGESDRIVER_BAZEL_QUERY_SCOPE`, ran `golangci-lint`.

### What did you expect to see?

A successful run of `golangci-lint` with no `typecheck` errors.

### What did you see instead?

Silent failures because `golangci-lint` wasn't able to load the types from source and gave up on non-local libraries.

**Comment by grampelberg** [comment]
There are a couple issues here:

- `golangci-lint` supports `go list` query syntax which is less explicit that the current `file=` support required by `gopls`.
- Because imports are resolved by path in `gopackagesdriver`, if you have the same import path for multiple IDs it is possible for the wrong source to be referenced.
- `stdlib` does not include any generated files, namely the CGO files for packages such as `net`.
- WKT for protobufs are skipped because they use a `library` attribute instead of the current ones.

**Comment by grampelberg** [comment]
I've got this working now in [my branch](https://github.com/grampelberg/rules_go/tree/thomas/packages-driver).

**Comment by dbernadett** [comment]
@grampelberg I am trying to get golangci-lint working with bazel. Could you help me get on the right path? I have some example code here:
https://github.com/dbernadett/golanglint-x-bazel
