### ISSUE TITLE
Gazelle in external mode is slow for repositories with lots of dependencies

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#353]
In [resolve_external.go](https://github.com/bazelbuild/rules_go/blob/cfdcbdc1d17e6dc3c48bbda4fce760949e58e381/go/tools/gazelle/rules/resolve_external.go#L54), Gazelle calls [`vcs.RepoRootForImportPath`](https://godoc.org/golang.org/x/tools/go/vcs#RepoRootForImportPath), which can be very slow (it may fetch information about repositories over the network). This gets called for every external import in every .go file.

One solution would be to call [`vcs.RepoRootForImportPathStatic`](https://godoc.org/golang.org/x/tools/go/vcs#RepoRootForImportPathStatic) instead, which does not do a network fetch. This will work fine for well-known sites like GitHub, but it won't be able to identify the repository root for other sites, unless it's qualified in the import path.

Another solution would be to read the repositories in the WORKSPACE file, which have full URLs, and attempt to resolve using those *before* calling `RepoRootForImportPath`.

**Comment by jayconrod** [comment]
This is the performance issue mentioned in #335.

**Comment by pmbethe09** [comment]
Yeah, I added the 'specialCases' that we were seeing a lot of but obviously there are things lot listed there.
