### ISSUE TITLE
bazel.RunfilesPath fails for Go binary invoked via Bazel ctx.actions.run

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/rules_go#3544]
### What version of rules_go are you using?

v0.39.1 (latest tag as of 2023-04-24)

### What version of gazelle are you using?

v0.30.0 (latest tag as of 2023-04-24

### What version of Bazel are you using?

Build label: 6.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS arm64

### Any other potentially useful information about your toolchain?

N/A.

### What did you do?

Invoked a Go binary that used `bazel.RunfilesPath` in an indirect dependency in a Bazel rule using `ctx.actions.run`.

### What did you expect to see?

Successful execution.

### What did you see instead?

https://github.com/bazelbuild/rules_go/blob/2a7131169cceb41f787caf9a39d251cff948fa8d/go/tools/bazel/runfiles.go#L424

```
could not locate runfiles directory
```

### Debugging

I worked around the issue by adding another resolution strategy by appending `/.runfiles/<workspace_name>` to the invoked binary name. I can provide a minimal example if more detail is helpful.

```go
func RunfilesPath() (string, error) {
	rfPath, err := bazel.RunfilesPath()
	if err != nil {
		// When running a binary via ctx.actions.run, the runfiles path is not
		// found using bazel.RunfilesPath.
		if siblingRfPath := findNestedRunfileDirectory(); siblingRfPath != "" {
			return siblingRfPath, nil
		}
		return "", fmt.Errorf("get runfiles path: %w", err)
	}
	return rfPath, nil
}

func findNestedRunfileDirectory() string {
	wd, err := os.Getwd()
	if err != nil {
		return ""
	}
	execPath := os.Args[0]
	if !filepath.IsAbs(execPath) {
		execPath = filepath.Join(wd, execPath)
	}

	workspaceName := "simc"
	siblingRunfiles := execPath + ".runfiles/" + workspaceName
	if _, err := os.Stat(siblingRunfiles); err == nil {
		return siblingRunfiles
	}
	return ""
}
```

**Comment by fmeum** [comment]
While we haven't formally deprecated everything in that package, I would strongly recommend using https://pkg.go.dev/github.com/bazelbuild/rules_go@v0.39.1/go/runfiles instead.

**Comment by jschaf** [comment]
Gotcha. I missed that because `bazel.Runfile` is deprecated, but `bazel.RunfilesPath` is not (yet) deprecated. I'll try switching to the new runfiles library.

I've tried a replacement of `bazel.Runfile` with `runfiles.Rlocation`, but it doesn't find runfiles that previously worked. `simc` is the workspace name.

```
/private/var/tmp/_bazel_joe/a23dc33a1da1c4843c603ab7998b3c25/execroot/simc/bazel-out/darwin_arm64-fastbuild/bin/build/build_test_/build_test.runfiles/build/version.bzl 
no such file or directory
```

Looking at the bazel out directory structure, the problem appears to be that the runfiles tree includes my bazel workspace name.

```
# resolved by runfiles.Rlocation
.../build_test_/build_test.runfiles/build/version.bzl 

# actual disk layout
.../build_test_/build_test.runfiles/simc/build/version.bzl
```

**Comment by jschaf** [comment]
I worked around the missing workspace name by wrapping the rules_go implementation. Curious to know if I've misconfigured something to cause the rules_go implementation not to resolve.

```go
// Rlocation returns the runfile location of the given path.
// Necessary until https://github.com/bazelbuild/rules_go/issues/3544 is fixed.
func Rlocation(path string) (string, error) {
	rf, err := runfiles.RlocationFrom(path, "")
	if err != nil {
		return rf, err
	}
	return strings.Replace(rf, ".runfiles/", ".runfiles/simc/", 1), nil
}
```

I also discovered one incompatibility, `bazel.Runfile` worked for relative testdata directories. Using `runfiles.Rlocation` requires the full repo path.

```go
// Before
bazel.Runfile("testdata/foo.txt")

// After
runfiles.Rlocation("full/repo/path/testdata/foo.txt")
```

**Comment by fmeum** [comment]
`Rlocation` is not meant to be a drop-in replacement as `bazel.Runfile` had semantics that are inherently problematic. All arguments to `Rlocation` must be of the form `repo_name/full/pkg/path/file`. If you intend to use it only to fetch files from your own repository, you could add a wrapper around it that prepends the workspace name and/or the current working directory.

**Comment by jschaf** [comment]
Good news: using Rlocation fixed the reported bug.

Bad news: converting all usages to runfiles.Rlocation was much more tedious than I expected.

- easy: fixing relative paths like `testdata/foo.txt`

- easy: prefix the workspace name. Side note: the repo name defaults to `__main__` if the workspace name is unset.

- hard: I couldn't use Rlocation to get a path to a directory because the manifest strategy doesn't work for directories. I worked around the issue by using Rlocation on a known file and calling filepath.Dir repeatedly. The manifest strategy was picked when using bazel run or with bazel rules.
