### ISSUE TITLE
Repeated issues with unable to create directory for _empty.go on Windows

### ISSUE THREAD

**Issue by tomqwpl** [bazelbuild/rules_go#3558]
### What version of rules_go are you using?
v0.39.0

### What version of gazelle are you using?
v0.29.0

### What version of Bazel are you using?
bazel 6.1.0

### Does this issue reproduce with the latest releases of all the above?
Yes. tried 0.39.1 of rules, bazel 6.2.0, 0.30.0 of gazelle.

### What operating system and processor architecture are you using?
Windows x64

### What did you do?
Just trying to build golang

### What did you expect to see?
That it works

### What did you see instead?
Many golang targets (almost always tests, don't know whether that is significant) fail with errors like:
```
compilepkg: could not create directory for _empty.go: mkdir C:\users\me\_bazel_me\dotzqxa5\execroot\altr_sw_hub\bazel-out\x64_windows-fastbuild\bin\golang\pkg\auth\auth\go_altair_com_slchub_pkg_auth_auth: Cannot create a file when that file already exists.
```

There is an issue elsewhere that reports that this only happens when there are multiple `go_test` targets in the BUILD.bazel file. That isn't the case here, or at least not in all cases (it is in a couple).

It also happens when running with `--jobs=1`, though I haven't run a completely clean build like that. I ran bazel with `--keep_going` to try and run all targets that would succeed and then tried running with `--jobs=1` to see whether the rest would succeed. 
I could get it to run using `--jobs=1` and then each time it failed, deleting the directory it was trying to create. After a few rounds of that the build succeeded.

I have repeated the test by first manually deleting the "execroot" output directory to force a completely clean build and I get the same thing.

The curious thing is that looking at the source code for the rules, I don't really understand why it's even trying to make an `_empty.go` file. The appears to be that it is only created if `len(srcs.goSrcs) == 0`. But all of my rules have lists of go files, and none of the files have golang build conditions in them, so it ought to have real code to build.

**Comment by tomqwpl** [comment]
I have just done a complete clean build with "--jobs=1" and it ran through successfully without intervention, so this would appear to be a concurrency issue of some kind. Note that I'm not using the experimental "sandboxing" feature on Windows.

As I say, the curiosity I have is why it's even attempting to create an "_empty.go" file.

**Comment by fmeum** [comment]
cc @sluongng as you worked on this in the past

I could see this happening if a build action is interrupted before performing the cleanup that deletes the directory, but that should be rare. 

@tomqwpl Does the directory exist after every build? Are there two targets with importpaths that become identical after being converted to directory names (e.g. slashes replaced with underscores)?

**Comment by tomqwpl** [comment]
@fmeum In response to "Does the directory exist after every build?".
Not totally sure what you mean. Perhaps this helps.
I just tried running a build. Failed in the above described way. 
I then deleted the directory it said it was trying to create and reran the build. It failed on another instance of the same thing. However, the directory I had deleted, then exists, and is empty.
The directory that it says it's trying to create for the second failure isn't empty, it contains "_empty.go".

So I believe that when it fails with the "can't create directory for "_empty.go", the directory it's trying to create exists, and already contains _empty.go. If I delete that directory and rerun, then the directory is created, and at the end of the build is actually empty.

Hopefully that makes sense

**Comment by tomqwpl** [comment]
@sluongng Here is an example that's just failed:
```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rbac",
    srcs = ["migrations.go"],
    embedsrcs = glob(["migrations/*.sql"]),
    importpath = "go.altair.com/slchub/pkg/migrations/rbac",
    visibility = ["//visibility:public"],
)

go_test(
    name = "rbac_test",
    srcs = ["migrations_test.go"],
    embed = [":rbac"],
    deps = [
        "@com_github_onsi_ginkgo//:ginkgo",
        "@com_github_onsi_ginkgo//reporters",
        "@com_github_onsi_gomega//:gomega",
    ],
)

```
None of the source files have any build conditions in them.

**Comment by sluongng** [comment]
Rewrite the error above a bit for easier reading.

```
compilepkg: 
  could not create directory for _empty.go: 
    mkdir C:\users\me\_bazel_me\dotzqxa5\execroot\altr_sw_hub\bazel-out\x64_windows-fastbuild\bin\golang\pkg\auth\auth\go_altair_com_slchub_pkg_auth_auth: 
      Cannot create a file when that file already exists.
```

This is happening on https://github.com/bazelbuild/rules_go/blob/4660427960cde81412031f93a2c2fb9fc6fcffa2/go/tools/builders/compilepkg.go#L223-L227

It seems like the directory `C:\users\me\_bazel_me\dotzqxa5\execroot\altr_sw_hub\bazel-out\x64_windows-fastbuild\bin\golang\pkg\auth\auth\go_altair_com_slchub_pkg_auth_auth` is being re-created 🤔, which suggests that there is another `go_test` in the same package that may have created the directory and enter the same race condition.

In https://github.com/bazelbuild/rules_go/pull/3145/files#diff-f5ba5554688cd727c306fb33aa10f80e92fd27201da575159972b133f7c6916cR105, when there is no implicit `importpath` attribute set on the go_test target, we use the label name( things like `name = "auth"`) as importpath instead.

Since I don't have a way to reproduce this on my end, @tomqwpl is it possible for you to setup a small example git repo that we could use to reproduce and fix the problem?

**Comment by sluongng** [comment]
> The bit I'm suspicious about is the "if len(srcs.goSrcs) == 0 {" line. Given the BUILD.bazel file above, why is that condition true? Or am I misunderstanding something?

You would need to understand how Go (and rules_go) compiles tests in a package. I would recommend reading https://github.com/bazelbuild/rules_go/pull/3145 as I tried explaining it there in detail.

But when there is a go_test target being compiled, rules_go will actually split that into 2 libraries underneath, 1 internal and 1 external. https://github.com/bazelbuild/rules_go/blob/c403db655ff4db63101ea8f4e7f1aa7b46dd73ee/go/private/rules/test.bzl#L64-L84

It's possible that you use external tests or internal tests exclusively in that package though. In that case, one of the 2 packages will be empty without any source files to compile. And because Bazel expects deterministic outputs, we would still need to provide it with _something_... which is why we would create `_empty.go` there and compile it to create a dummy result.

**Comment by tomqwpl** [comment]
It feels to me like there are two complete copies of bazel running at the same time both trying to do the same build, thus conflicting with each other. The things it is complaining about aren't duplicated as far as I can see. There is only one "go_test" in each BUILD.bazel file that it complaint at.

At the beginning of the build log I get:
```
DEBUG: C:/work/slc-hub/main/packaging/naming.bzl:12:10: {"version": "0.0.0.0", "branch": "master", "name_suffix": "DEV", "noinfo": "passed"}
DEBUG: C:/work/slc-hub/main/packaging/naming.bzl:12:10: {"version": "0.0.0.0", "branch": "master", "name_suffix": "DEV", "noinfo": "passed"}

```
I can only see one place in the BUILB.bazel files where the code to generate that is being referenced, yet it's being output twice.

I have only one java.exe process running. If I `bazel shutdown` it goes away. Symptoms persist when I try again after that.

I will try rebooting and see whether that makes any difference.

**Comment by tomqwpl** [comment]
Rebooting makes no difference. 
It runs reliably with --jobs=1. 
I only get errors when there are tests being built. If I'm building just the "build the distribution zip or distribution MSI" target I don't have a problem. But with any time I do "build //..." it fails on this kind of error, unless "--jobs=1". That takes a while though (albeit less time than manually restarting it having deleted the directories it complains about each time).

**Comment by tomqwpl** [comment]
> It runs reliably with --jobs=1.

Possibly spoke too soon on that front.
Paraphrased output:
```
bazel build --jobs=1 //...

...

compilepkg: could not create directory for _empty.go: mkdir C:\users\tquarendon\_bazel_tquarendon\dotzqxa5\execroot\altr_sw_hub\bazel-out\x64_windows-fastbuild\bin\golang\pkg\auth\usergroup\store\go_altair_com_slchub_pkg_auth_usergroup_store: Cannot create a file when that file already exists

erase /q <that directory>

bazel build --jobs=1 //...

same complaint.
```

That is, it complained twice on subsequent runs about the same directory, despite the fact that I erased it in between (and I have checked the directories against each other, they are the same and I deleted the same one). So second time the directory didn't exist before bazel started, it must have been created by bazel.
In fact I appear to be able to do that over and over.

**Comment by sluongng** [comment]
Yeah that's because you have multiple actions under `//...` that are creating a similar path.
It might help narrow things down if you were to do

```
bazel clean --expunge
bazel build --jobs=1 //golang/pkg/auth/usergroup/store/:all
```

That would let you build all targets under the same package and check if there is any duplication within that package.

**Comment by tomqwpl** [comment]
```
>bazel clean --expunge
INFO: Starting clean.

>bazel build --jobs=1 //golang/pkg/auth/usergroup/store:all
INFO: Analyzed 2 targets (178 packages loaded, 10293 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 208.235s, Critical Path: 57.10s
INFO: 137 processes: 9 internal, 128 local.
INFO: Build completed successfully, 137 total actions
```

**Comment by fmeum** [comment]
Different configurations should result in different output paths and the directory we create `_empty.go` in is relative to the output path.

@tomqwpl I have access to Windows - it would be very helpful if you could provide me with a reproducer.

**Comment by tomqwpl** [comment]
So far I'm been unable to reproduce on a small example. If I just take the one BUILD.bazel file that fails for example and try and put that in a separate directory, it then succeeds. But equally, it seems that just running the one single build target seems to work. The BUILD.bazel files are nothing complicated though, see example above.

Now, the interesting thing is that I don't seem to be able to reproduce this any more. I've just done a "clean --expunge" and then a "build //..." and it worked without issue. Previously this would have given me an issue. I'm fairly sure nothing in the code has changed, and that I'm using the same directory as I was before.
I will try again, but I may have to just close this as now unreproducible.

**Comment by fmeum** [comment]
This is happening in Bazel CI (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3035#0188343c-c91d-4305-866f-aabf6f5e5a9d):

```
(13:48:16) ERROR: C:/b/bk-windows-v72b/bazel-downstream-projects/bazelisk/platforms/BUILD:14:8: GoCompilePkg platforms/platforms_test_test.external.a failed: (Exit 1): builder.exe failed: error executing GoCompilePkg command (from target //platforms:platforms_test)
--
  | cd /d C:/b/txumw2c7/execroot/__main__
  | SET CGO_ENABLED=1
  | SET GOARCH=amd64
  | SET GOOS=windows
  | SET GOPATH=
  | SET GOROOT=external/go_sdk
  | SET GOROOT_FINAL=GOROOT
  | SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt
  | SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\um\x64
  | SET PATH=;C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\system32
  | SET TEMP=C:\temp
  | SET TMP=C:\temp
  | bazel-out\x64_windows-opt-exec-ST-f007e4e0eadc\bin\external\go_sdk\builder.exe compilepkg -sdk external/go_sdk -installsuffix windows_amd64 -src platforms/platforms.go -src platforms/platforms_test.go -embedroot  -embedroot bazel-out/x64_windows-fastbuild/bin -embedlookupdir platforms -arc github.com/bazelbuild/bazelisk/versions=github.com/bazelbuild/bazelisk/versions=bazel-out/x64_windows-fastbuild/bin/versions/go_default_library.x -arc github.com/hashicorp/go-version=github.com/hashicorp/go-version=bazel-out/x64_windows-fastbuild/bin/external/com_github_hashicorp_go_version/go-version.x -arc github.com/bazelbuild/bazelisk/platforms=github.com/bazelbuild/bazelisk/platforms=bazel-out/x64_windows-fastbuild/bin/platforms/platforms_test.internal.x -importpath github.com/bazelbuild/bazelisk/platforms -p github.com/bazelbuild/bazelisk/platforms_test -package_list bazel-out/x64_windows-opt-exec-ST-f007e4e0eadc/bin/external/go_sdk/packages.txt -o bazel-out/x64_windows-fastbuild/bin/platforms/platforms_test_test.external.a -x bazel-out/x64_windows-fastbuild/bin/platforms/platforms_test_test.external.x -testfilter only -gcflags  -asmflags
  | # Configuration: 2a3cf7208bd3ae1853df083f9823da61b7246f31df8a4ec512381271fcad013d
  | # Execution platform: @local_config_platform//:host
  | compilepkg: could not create directory for _empty.go: mkdir C:\b\txumw2c7\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\platforms\github_com_bazelbuild_bazelisk_platforms: Cannot create a file when that file already exists.
```

It's possible that file deletion sometimes just fails and that leaves behind `_empty.go` files from previous invocations. Although in this case there really should be sources...

**Comment by fmeum** [comment]
Turns out that *every* test triggers this logic since there is a separate compile action for the external test package `<name>_test`, which is often empty.
