### ISSUE TITLE
Proposal: consolidate cgo_library with other rules

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#359]
## Goal

Allow `go_binary`, `go_test`, and `go_library` to contain cgo code without explicitly using `cgo_library`. Ideally, `cgo_library` would eventually become private.

## Background

This repository provides `go_library`, `go_binary`, and `go_test` rules that only accept pure Go source files (no cgo, no .c files). In order to use cgo, developers must declare a separate `cgo_library` target that includes .go files with cgo code. Other rules may incorporate cgo code by depending on a `cgo_library` through the `library` attribute.

### Example:

```bzl
go_binary(
    name = "cmd",
    srcs = ["foo.go", "bar.go"],  # pure Go source files
    library = ":cgo_lib",
)

cgo_library(
    name = "cgo_lib",
    srcs = ["baz.go", "quux.c"],  # cgo and C source files
)
```

## Proposed change

Developers should be able to mix pure Go and cgo sources in `go_library`, `go_binary`, and `go_test` without explicitly declaring cgo targets. They should still state that cgo code is present:

```bzl
go_binary(
    name = "cmd",
    cgo = 1,
    srcs = ["foo.go", "bar.go", "baz.go", "quux.c"],
)
```

## Implementation

We can accomplish this by adding a layer of macros in front of the real rules, which would ideally become private. For example:

```bzl
def go_binary(name, srcs = [], deps = [], data = [], cgo = None, **kwargs):
  if cgo:
    _cgo_library(
        name = name + "_cgo",
        srcs = srcs,
        deps = deps,
        data = data,
        **kwargs
    )
    _go_binary_rule(
        name = name,
        library = name + "_cgo",
    )
  else:
    _go_binary_rule(
        name = name,
        srcs = srcs,
        deps = deps,
        data = data,
        **kwargs,
    )
```

The `cgo_library` macro and other associated rules and macros will continue to be necessary to generate files and actions that build cgo code. Ideally, we could eventually make `cgo_library` private though. If Gazelle no longer generates `cgo_library` calls, usage would become rare after some time.
### Caution:

When a rule is defined, Bazel attaches attaches the name on the left side of the assignment statement to the internal rule metadata.

```bzl
go_library = rule(...)
```

For example, `go_library` appears in error messages and is recognized by `bazel query`. We should make sure the rules keep their original names in order to preserve this behavior, even though developers will not be calling them directly.

**Comment by jayconrod** [comment]
cc @pmbethe09 @ianthehat 

WDYT? This would also simplify Gazelle, since we wouldn't need to check for cgo and define separate rules anymore.

**Comment by dslomov** [comment]
FWIW, I do recommend not relying on macros for this.
1. Macros are not visible to aspects, so it will complicate any IDE support story
2. Macros are transparent to `blaze query` as you discovered and papering over this will be a rat hole.

**Comment by jayconrod** [comment]
@dslomov Could you suggest a better approach for this? The macros would basically be reproducing what we do now; they would just simplify usage for developers.

**Comment by dslomov** [comment]
I'd leave go and cgo rules separate. I do not see much benefit in moving the distinction to the attribute. Why `go_library(.., cgo = 1, ...) is better than `cgo_library(...)` if both can interop?

**Comment by jayconrod** [comment]
With `cgo = 1` we only need one declaration for a single logical package instead of two. That seems like a non-trivial benefit to me.

**Comment by pmbethe09** [comment]
What about doing this at the rule-level instead of macro -- creating extra actions when cgo=1 ?

**Comment by dslomov** [comment]
why not just add support for cgo into go rule implementation then?

**Comment by dslomov** [comment]
(what @pmbethe09  says)

**Comment by jayconrod** [comment]
If that's possible, I'd love to do that. `cgo_library` creates a `cc_library` and `cc_binary` internally though. AFAIK it's not possible to instantiate those within a rule. Is there another way we can create compile/link actions for C?

**Comment by jayconrod** [comment]
(We already access the external linker through `ctx.fragments.cpp.compiler_executable` when when linking a `go_binary` or `go_test` with cgo dependencies. Not sure whether that will break though if the linker changes.)

**Comment by pmbethe09** [comment]
Ah yes, the need for cc_library does complicate things.

**Comment by dslomov** [comment]
Ah I see, that is of course Bazel sandwich: https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html. wdyt @mhlopko ?

**Comment by ianthehat** [comment]
The biggest problem with the existing solution is that it *cannot* compile valid cgo files, because it attempts to build the go files itself, which means that it breaks if those go files refer to symbols from the rest of the package, so we need to fix it somehow.

I think a nicer way to go would be to break the rule up rather than unify it.
Have the cgo_library rule not do compilation, but just take go files with cgo markers, and generate the separated c and go files, and provide them as outputs.
Those outputs would then be used directly in cc_library and go_library rules.
So long as gazelle is doing all the heavy lifting of generating and maintaining these rules, I don't really see the multiple rules being an impediment, and splitting it means you keep all the controls of the individual library rules without having to have a single rule that knows all the options for both.

go_binary( # standard go binary 
    name = "cmd",
    srcs = ["foo.go", "bar.go", ":cgo"], # needs to only pick the go files from the :cgo outputs 
    deps = ":cgo_lib",
)

cc_library(  # standard cc rule, so we can generate deps, compile and link options
  name = "cgo_lib",
  srcs = ["quux.c", ":cgo"], # needs to only pick the c files from the :cgo outputs
)

cgo_source(  # takes baz.go and generates the split go and c files
    name = "cgo",
    srcs = ["baz.go"],
)

**Comment by mhlopko** [comment]
Yup, Go team does suffer for missing C++ sandwich, and C++ sandwich is needed if you want to register C++ actions from Skylark. The problem is that C++ actions have huge surface and we need to polish them first. I really hope to start working on C++ sandwich in Q2, but I'm cannot promise you that it will be finished by EOQ2.

**Comment by jayconrod** [comment]
@ianthehat I think there's more complication in cgo than splitting up the source files. Below is a diagram I made (sorry for the handwriting and the low-quality scan; hopefully still legible). Boxes are rules, circles are files, sources are at the bottom.

`_cgo_codegn_rule` is basically what you're describing. It produces .go and .c files from cgo sources. The Go files are compiled in a `go_library` (actually, they're usually pulled into another target with the `library` attribute). The C files are compiled through `cc_library` and `cc_binary`, then post-processed through `_cgo_import` and `_cgo_object` rules.

@mhlopko The C++ sandwich sounds like what we need. If we can invoke the C++ compiler and linker in a compatible way (without adding toolchain-specific flags ourselves), then all this complexity could be expressed inside one big rule as files and actions.

So I think the question becomes do we wait for C++ sandwich before doing anything here? I don't think any other work is blocked by this, and this is maybe P2, so it's okay to wait. On the other hand, I think we would have the same external interface with C++ sandwich as proposed here (just with rules instead of macros), so we could still get some benefit now.

![cgo dependencies](https://raw.githubusercontent.com/jayconrod/misc/bb48f7ecae01aba71fd6e76cf2bca196988cf7ef/images/cgo-dependencies.png)

**Comment by bcmills** [comment]
`cgo_library` currently has the nice property of separating `deps` from `cdeps`, which seems like it makes Gazelle's job a bit easier (it can know to leave cdeps intact, using only local information).  Would you preserve the distinction between `cdeps` and `deps` in the combined `go_library` rule?

**Comment by jayconrod** [comment]
@bcmills I hadn't thought about, but I think it makes sense to keep `deps` and `cdeps` separate, given that they're handled so differently internally.

**Comment by alandonovan** [comment]
On 26 April 2017 at 16:54, Jay Conrod <notifications@github.com> wrote:

> @bcmills <https://github.com/bcmills> I hadn't thought about, but I think
> it makes sense to keep deps and cdeps separate, given that they're
> handled so differently internally.
>

I'd prefer to keep them in a single list.  From the user's perspective,
there may be two kinds of dependencies today, but they're both just
dependencies; it should be the tools' job to treat them differently.  And
tomorrow there might be a third kind, but we wouldn't want another
attribute for it.

**Comment by bcmills** [comment]
@alandonovan The difference between `cdeps` and `deps` is that the `deps` can be more-or-less strictly inferred from the source code.  Separating "automated" and "manual" dependencies seems useful in a way that other fine-grained distinctions may not be.

**Comment by ianthehat** [comment]
Done in #633
