### ISSUE TITLE
ERROR FAILED: //tests/core/transition:hermeticity_test  with Bazel@HEAD in Downstream CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_go#3597]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3109#0188d690-a57f-42b0-891f-8b2986d9db52

Platform: Windows, MacOs, Ububtu

Logs : 
```
FAIL: //tests/core/transition:hermeticity_test 
```

Steps: 
```
git clone https://github.com/bazelbuild/rules_go.git 
git reset 9d5416bcc9d48da3735b73fb5540b1cdbd470b85 --hard
export USE_BAZEL_VERSION=211fd6c14bef2f656265b3d3eb98a476f02ebf88
bazel build //...
```

Reference issue, which is causing error : https://github.com/bazelbuild/bazel/commit/cb558978820b1fb9b579d8e9578cbb9ca590fe60

CC Green Team @ fweikert

**Comment by fmeum** [comment]
@sgowroji How certain are you that the given commit is the culprit? Was there some kind of bisection that I could look into the results of?

**Comment by meteorcloudy** [comment]
It got the result from https://buildkite.com/bazel/culprit-finder/builds/5736#0188d70d-c9dc-438e-8119-76650a30b54c, which seems to be the same issue reported in https://github.com/bazelbuild/bazel/issues/18666

**Comment by fmeum** [comment]
@meteorcloudy I think that there may be two different issues at play that confused the culprit finder. The log linked in the issue has a different kind of error: It looks like the output of `cquery --output=jsonproto` changed to new-line delimited JSON.

**Comment by fmeum** [comment]
Maybe this is caused by https://github.com/bazelbuild/bazel/commit/607d0f7335f95aa0ee236ba3c18ce2a232370cdb?

**Comment by meteorcloudy** [comment]
Oh, you are probably right, I forgot to check the actual error in the downstream pipeline.

**Comment by zhengwei143** [comment]
Sorry I just saw this, let me take a quick look.

**Comment by zhengwei143** [comment]
I've just rolled back the change in https://github.com/bazelbuild/bazel/commit/dba9e43a26d41c2559568e4abfdece57e79de37d which should fix this.

**Comment by sgowroji** [comment]
We are also seeing this test failiure in the latest CI https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#01894849-482e-4d46-9522-beab4a40754e

```
//tests/core/output_groups:compilation_outputs_test                      FAILED 
```

**Comment by zhengwei143** [comment]
That looks like a separate issue - this test failure has been failing even after the rollback in https://github.com/bazelbuild/bazel/commit/dba9e43a26d41c2559568e4abfdece57e79de37d (see for example https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3149#01892e86-2c8f-4b6b-ad39-fb36384d135d)

Btw, I've reimplemented this in https://github.com/bazelbuild/bazel/commit/aa8835753cbbed5a837fc10a37464ee4a84941ba, and the previous failures seem to be fixed. So this issue should be closed.

**Comment by fmeum** [comment]
I submitted https://github.com/bazelbuild/rules_go/pull/3623 to fix this separate issue - it is trivial and unrelated.

**Comment by sgowroji** [comment]
Hi @fmeum, I see rules\_go is again failing with hermeticity\_test failure in downstream [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3202#0189a9b6-589a-41d7-9870-a7a09b3436d7.](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3202#0189a9b6-589a-41d7-9870-a7a09b3436d7.) Should we reopen this present issue or raise a new one. Could you please have a look. Thanks! 

```
//tests/core/transition:hermeticity_test                                
```

**Comment by zhengwei143** [comment]
Looking at the error logs, this should be due to https://github.com/bazelbuild/bazel/commit/c061e57a7004a88eeb2f84d094d9a88b56c146b6
 which should also be fixed by the rollback in https://github.com/bazelbuild/bazel/commit/0c917255ca95b5c25ae6cf61ebe7a63c1061f73f.

**Comment by fmeum** [comment]
Since this change may be rolled forward as an incompatible change in the future, I went ahead and updated the usage: https://github.com/bazelbuild/rules_go/pull/3638

**Comment by sgowroji** [comment]
Hi @fmeum, We found rules_go [Downstream CI](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-a7fd-4435-a687-c3d25c266b7a) is failing with hermeticity_test.

**Comment by fmeum** [comment]
Looks like an instance of https://github.com/bazelbuild/bazel/issues/19823. I will disable Bzlmod for it.

**Comment by sgowroji** [comment]
Another test is failing in rules\_go \`\`\`//tests/integration/gopackagesdriver:gopackagesdriver\_test               FAILED \`\`\` https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3519#018c569e-024d-4130-84d6-95989988cd21

**Comment by fmeum** [comment]
rules_go is passing in the latest downstream pipeline: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3526
