### ISSUE TITLE
Allow extra_outputs on go_proto_compile

### ISSUE THREAD

**Issue by tingilee** [bazelbuild/rules_go#3630]
### What version of rules_go are you using?

0.40.0

### What version of gazelle are you using?

0.28.0

### What version of Bazel are you using?

 6.3.0rc1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?
MacOS M1 Ventura and Linux AMD

### What did you do?

See below. 

### What did you expect to see?

We have a custom plugin to generate enums .pb.go files from .proto files. For `example.proto`, we expect both
`example_dbenum.pb.go` and `example.pb.go` to be generated as Bazel provider outputs. Currently, only files with the same name and `.pb.go` file extensions are allowed. I'd like to propose adding attributes to allow outputting more w/ custom proto plugins.

**Comment by fmeum** [comment]
This sounds useful. Since you have a concrete application in mind, would you be interested in contributing this improvement (with some support from maintainers)?

**Comment by tingilee** [comment]
@fmeum I'd love to. Here's a patch that has worked for our monorepo: https://github.com/bazelbuild/rules_go/pull/3631  Could you take a look? Happy to add tests and address comments.
