### ISSUE TITLE
Use rules_go to run `go mod` and `go get`

### ISSUE THREAD

**Issue by kellyma2** [bazelbuild/rules_go#3635]
### What did you do?

Attempting to run a genrule to update go.mod (ie: run `go get -u ./...` and `go mod tidy`)

```
genrule(
    name = "go-mod-update",
    srcs = [
        "@io_bazel_rules_go//go",
    ],
    tools = ["@io_bazel_rules_go//go"],
    outs = [ "foo" ],
    cmd = "$(location @io_bazel_rules_go//go) get -u ./...",
)
```

### What did you see instead?

```
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_mkelly/d20eafd4e13be53578028ce5d4211ed8/external/io_bazel_rules_go/go/private/rules/go_bin_for_host.bzl", line 31, column 23, in _go_bin_for_host_impl
		_ensure_target_cfg(ctx)
	File "/private/var/tmp/_bazel_mkelly/d20eafd4e13be53578028ce5d4211ed8/external/io_bazel_rules_go/go/private/rules/go_bin_for_host.bzl", line 23, column 13, in _ensure_target_cfg
		fail("//go is only meant to be used with 'bazel run', not as a tool. " +
Error in fail: //go is only meant to be used with 'bazel run', not as a tool. If you need to use it as a tool (e.g. in a genrule), please open an issue at https://github.com/bazelbuild/rules_go/issues/new explaining your use case.
```

**Comment by fmeum** [comment]
A `genrule` is a build action and as such shouldn't have side effects. 

Instead of wrapping this in a `genrule`, you could just `bazel run @io_bazel_rules_go//go -- get ...` directly or, if that command line gets more complicated, create an `sh_binary` that wraps it. 

Let me know if that doesn't address your use case.

**Comment by kellyma2** [comment]
My hope was that I could automate the update process similarly to what gazelle-update-repos does.  Obviously, it's possible to just write a shell snippet for this, but repeating it across many repos is quite tedious.  Instead, what I'd like to do is something like:

```
> bazel run update-deps 
```

which would internally translate to something like:

```
> go get -u ./...
> go mod tidy
> bazel run gazelle-update-repos
```
and have this run with the embedded go in my bazel environment (instead of relying on my outer environment to have golang installed)

**Comment by fmeum** [comment]
That is possible, but fundamentally problematic in a `genrule`: Bazel rules must not have observable side effects besides creating their declared outputs.

`bazel run` is the right place for such actions. The sequence of `go get`, `go mod tidy`, `bazel run` you gave above essentially already is a shell script, so you could move that into an `.sh` file and wrap it into an `sh_binary` that can then be run with `bazel run`.

If you want to use the Bazel-provided Go SDK, you need to:
1. Add `data` dependencies on `@io_bazel_rules_go//go` and `@bazel_tools//tools/bash/runfiles`.
2. Pass `$(rlocationpath @io_bazel_rules_go//go)` into the `sh_binary` via `env` or `args`.
3. Use the `rlocation` function provided by `@bazel_tools//tools/bash/runfiles` to get the runtime path of the embedded Go binary.
