### ISSUE TITLE
Profile-guided optimization in Go 1.20+

### ISSUE THREAD

**Issue by LINKIWI** [bazelbuild/rules_go#3637]
### What version of rules_go are you using?

0.41.0

### What version of gazelle are you using?

0.32.0

### What version of Bazel are you using?

6.3.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

Hi, is there a plan to support a rules_go interface to supply a profile to enable [PGO](https://go.dev/doc/pgo) via the `-pgo` build flag?

**Comment by fmeum** [comment]
I don't think anybody has a concrete plan to work on this yet, but contributions in this area would definitely be welcome.

**Comment by adam-azarchs** [comment]
I think the tricky part of this is that you want to provide a profile for each `go_binary` target, and use the right one for the build of each `go_library` that it depends on.  You can do that with config transitions but that massively multiplies the build graph, and you have to be careful to avoid letting that multiplication propagate outward to non-go dependencies, e.g. `cc_library` targets you depend on for cgo linkage.
