### ISSUE TITLE
nogo_main fail to build when to upgrade golang.org/x/tools

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#3640]
### What version of Bazel are you using?

Build label: 6.3.1-homebrew

### Does this issue reproduce with the latest releases of all the above?

if you update the tools like this

```
    go_repository(
        name = "org_golang_x_tools",
        build_file_proto_mode = "disable_global",
        importpath = "golang.org/x/tools",
        sum = "h1:ojD5zOW8+7dOGzdnNgersm8aPfcDjhMp12UfG93NIMc=",
        version = "v0.11.1",
    )
```

you will get the error

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/io_bazel_rules_go/go/tools/builders/nogo_main.go:237:11: not enough arguments in call to pkg.facts.Encode
        have ()
        want (bool)
external/io_bazel_rules_go/go/tools/builders/nogo_main.go:399:54: not enough arguments in call to facts.NewDecoder(pkg.types).Decode
        have (func(pkg *types.Package) ([]byte, error))
        want (bool, func(pkgPath string) ([]byte, error))

```

**Comment by fmeum** [comment]
@sluongng Do you happen to have a recommendation here? Should we just update the version used by rules_go and force users to update with us?

**Comment by sluongng** [comment]
I think we also ran into a separate issue with `x/tools@v0.11` over on Gazelle side https://github.com/bazelbuild/bazel-gazelle/issues/1579. It seems like the upstream library is introducing quite a few breaking changes in this release (cc: @adonovan)

> Should we just update the version used by rules_go and force users to update with us?

Yeah, there is no way we could accommodate a matrix of 3rd party deps version ranges.
At most, we could provide a release note suggesting how to patch rules_go if you want to keep on using older versions of x/tools.

I think we need to bump x/tools version in both rules_go and gazelle to the latest and do new releases.
