### ISSUE TITLE
Unable to download golang 1.21 toolchain

### ISSUE THREAD

**Issue by baizhenyu** [bazelbuild/rules_go#3644]
### What version of rules_go are you using?
0.39.0

### What version of gazelle are you using?
0.26.0

### What version of Bazel are you using?
5.4.0

### Does this issue reproduce with the latest releases of all the above?
Unsure

### What operating system and processor architecture are you using?
x86_64 Linux

### What did you do?
Download golang toolchain with

```
go_download_sdk(
     name = "go_sdk",
     goarch = "amd64",
     goos = "linux",
 )
```
Please note no version is specified and should use latest version.

### What did you expect to see?
Download success

### What did you see instead?
```
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/usr/local/google/home/timbai/.cache/bazel/_bazel_timbai/390359d02f81fc440c9ec00323252b81/external/io_bazel_rules_go/go/private/sdk.bzl", line 112, column 17, in _go_download_sdk_impl
                fail("did not find version {} in https://go.dev/dl/?mode=json".format(version))
Error in fail: did not find version 1.21 in https://go.dev/dl/?mode=json
```

**Comment by teran** [comment]
> Thanks @jamie-digital . Using version `1.21.0` I see a different failure using `go_register_toolchains(version = "1.21.0")`
> 
> ```
> 	File "io_bazel_rules_go/go/private/sdk.bzl", line 116, column 43, in _go_download_sdk_impl
> 		detected_version = _detect_sdk_version(ctx, ".")
> 	File "io_bazel_rules_go/go/private/sdk.bzl", line 519, column 17, in _detect_sdk_version
> 		fail("SDK is version %s, but version %s was expected" % (version, ctx.attr.version))
> Error in fail: SDK is version 1.21.0
> time 2023-08-04T20:14:06Z
> , but version 1.21.0 was expected
> ```
> 
> Looks like something is piping through a full version struct instead of a string. That's using version 41.0

just troubleshooted it a bit: that happened because VERSION file in the downloaded Go archive contains additional string:

```
go1.21.0
time 2023-08-04T20:14:06Z
```

While 1.20.7 has just:
```
go1.20.7
```

So I've patched it locally the following way while waiting for the fix in rules (not quite sure if that fix is OK for the upstream so...) :

```
diff --git a/WORKSPACE b/WORKSPACE
index de6cd10..d248760 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -29,6 +29,8 @@ versions.check(

 http_archive(
     name = "io_bazel_rules_go",
+    patch_args = ["-p1"],
+    patches = ["//common/bazel/rules/rules_go/patches:0001-fix-go-1.21.0-version-check.patch"],
     sha256 = "6dc2da7ab4cf5d7bfc7c949776b1b7c733f05e56edc4bcd9022bb249d2e2a996",
     urls = [
         "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.39.1/rules_go-v0.39.1.zip",
diff --git a/common/bazel/rules/rules_go/patches/0001-fix-go-1.21.0-version-check.patch b/common/bazel/rules/rules_go/patches/0001-fix-go-1.21.0-version-check.patch
new file mode 100644
index 0000000..79062bf
--- /dev/null
+++ b/common/bazel/rules/rules_go/patches/0001-fix-go-1.21.0-version-check.patch
@@ -0,0 +1,13 @@
+diff --git a/go/private/sdk.bzl b/go/private/sdk.bzl
+index 5a3ef422..bbbcc052 100644
+--- a/go/private/sdk.bzl
++++ b/go/private/sdk.bzl
+@@ -514,7 +514,7 @@ def _detect_sdk_version(ctx, goroot):
+     version_file_path = goroot + "/VERSION"
+     if ctx.path(version_file_path).exists:
+         # VERSION file has version prefixed by go, eg. go1.18.3
+-        version = ctx.read(version_file_path)[2:]
++        version = ctx.read(version_file_path)[2:].split("\n")[0]
+         if ctx.attr.version and ctx.attr.version != version:
+             fail("SDK is version %s, but version %s was expected" % (version, ctx.attr.version))
+         return version
diff --git a/common/bazel/rules/rules_go/patches/BUILD.bazel b/common/bazel/rules/rules_go/patches/BUILD.bazel
new file mode 100644
index 0000000..e69de29
```

This worked for me on 1.20.7 and 1.21.0 which I've tested on macOS.

**Comment by fmeum** [comment]
@teran That fix looks good, do you want to send a PR?

**Comment by teran** [comment]
> @teran That fix looks good, do you want to send a PR?

AFAICS it's already fixed in master with:
```
version_line = ctx.read(version_file_path).splitlines()[0]
```

So it's probably up to cherry-pick to 0.39 branch and create a new 0.39.x release (if applicable)

**Comment by sfc-gh-kleonhard** [comment]
Sounds great to me. I'll anxiously await the new version!

**Comment by sfc-gh-kleonhard** [comment]
Any chance the fixes for 1.21 will be released soon? @fmeum

**Comment by fmeum** [comment]
We are working on it. In the meantime, you can always depend on a commit on master, which has all the fixes. Our release archives aren't really any different from what's in the repo.

**Comment by jingxu97** [comment]
What is the current status of this issue? Thanks!

**Comment by fmeum** [comment]
1.21 should be fully supported now and is tested in CI.
