### ISSUE TITLE
shipping the new version detection and go_googleapis change together causing confusion

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#3645]
I'm not sure how else to provide this feedback. Sorry if there's a better venue. This is written as a debugging session, but it's not really meant to be a bug report (I may write a separate one). This is me trying to give a concrete example of how difficult the release process has made some things

The rules_go 0.41.0 and gazelle 0.32.0 releases have been very frustrating and have done so in a pattern that seems common to rules_go and gazelle releases. I love the work that y'all have done and have used it for years. But this has been a struggle.

Those two releases a) are coupled together without them checking if the other was updated; b) break third party code in ways that are hard-to-impossible to figure out how to fix; and c) added the breaking `go_googleapis` change while also being required if folks want to support Go 1.21.

First, if folks simply try to upgrade to rules_go 0.41.0 (maybe in order to support Go 1.21), their build can break with:

```
$  bazel query 'deps(//go/svc/fe)'
ERROR: Evaluation of query "deps(//go/svc/fe)" failed: preloading transitive closure failed: no such package '@go_googleapis//google/rpc': The repository '@go_googleapis' could not be resolved: Repository '@go_googleapis' is not defined
... elided ...
```

So, you follow the instructions in the rules_go 0.41.0 release to add the `googleapis` repo to your WORKSPACE. But that just gets you to 

```
$  bazel query 'deps(//go/svc/fe)'
ERROR: Evaluation of query "deps(//go/svc/fe)" failed: preloading transitive closure failed: no such package '@go_googleapis//google/rpc': The repository '@go_googleapis' could not be resolved: Repository '@go_googleapis' is not defined
```

Okay, well, we guess what was meant by "Together with Gazelle v0.32.0" was that you also had to simultaneously update gazelle not just if you upgraded gazelle, too, you'd need this change.

This is our first frustration. The coupling of the gazelle and rules_go dependencies means that anyone trying to automate their dependency maintenance will hit a full block of that system and have to manually unbreak their builds by fixing up the deps. It also means very careful attention has to be paid to every release note. To be honest, folks can't and don't want to be in the business of being full experts in their build tools.

So, update gazelle (oh, yeah, and go work out [the new http_archive yourself](https://github.com/bazelbuild/bazel-gazelle/issues/1601)) and, whoops, you get:

```
$  bazel query 'deps(//go/svc/fe)'         
ERROR: Evaluation of query "deps(//go/svc/fe)" failed: preloading transitive closure failed: no such package '@com_google_cloud_go_monitoring//apiv3/v2/monitoringpb': The repository '@com_google_cloud_go_monitoring' could not be resolved: Repository '@com_google_cloud_go_monitoring' is not defined
```

Uhhhhh, okay. You do have an old `go_repository` for `com_google_cloud_go` that's not been updated to `sum`-y versions of things. Let's try updating that.

```
$  bazel run //:gazelle -- update-repos cloud.google.com/go
INFO: Running command line: bazel-bin/gazelle update-repos cloud.google.com/go
```

That updated com_google_cloud_go to `v0.110.7` with sum `h1:rJyC7nWRg2jWGZ4wSJ5nY65GTdYJkg0cd/uXb+ACI6o=`

Okay, now let's see:

```
$  bazel query 'deps(//go/svc/fe)'
ERROR: Evaluation of query "deps(//go/svc/fe)" failed: preloading transitive closure failed: no such package '@com_google_cloud_go_trace//apiv2/tracepb': The repository '@com_google_cloud_go_trace' could not be resolved: Repository '@com_google_cloud_go_trace' is not defined
```

What? I've got no `com_google_cloud_go_trace` in my WORKSPACE or elsewhere. Okay, let's undo all of these changes and list the deps of `//go/svc/fe` when we were on rules_go 0.40.1 and gazelle 0.39.1. ([gist](https://gist.github.com/jmhodges/5bfa80de2a9e11e861279d7096c53998))

Uhhh, there's no `com_google_cloud_go_trace` in that list of deps. That means there's something new in how rules_go 0.41 or gazelle 0.32 creates repositories for com_google_cloud? No clue. (And, while I have some protos in that dep list, but there's no `import` of `google/rpc/status.proto` or `google/longrunning/operations.proto` in them. The only one is `import "proto/time/time.proto";` which is baked in?)

Okay, let's double check the `build`. 

```
$  bazel build //go/svc/fe   
ERROR: /Users/jmhodges/founding/src/founding/go/pkg/tracehelp/BUILD.bazel:3:11: no such package '@com_google_cloud_go//compute/metadata': BUILD file not found in directory 'compute/metadata' of external repository @com_google_cloud_go. Add a BUILD file to a directory to mark it as a package. and referenced by '//go/pkg/tracehelp:tracehelp'
```

What? The [compute/metadata](https://pkg.go.dev/cloud.google.com/go/compute/metadata) directory totally exists and  `com_google_cloud_go` repo doesn't have an extra BUILD setting . It's only:

```
go_repository(
    name = "com_google_cloud_go",
    importpath = "cloud.google.com/go",
    sum = "h1:rJyC7nWRg2jWGZ4wSJ5nY65GTdYJkg0cd/uXb+ACI6o=",
    version = "v0.110.7",
)
```

Okay, fine, let's see what the error is in `tracehelp`, I guess? Not sure what could be different.

```
$  bazel build //go/pkg/tracehelp:tracehelp        
ERROR: /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/org_golang_google_genproto/googleapis/devtools/cloudtrace/v2/BUILD.bazel:3:11: no such package '@com_google_cloud_go_trace//apiv2/tracepb': The repository '@com_google_cloud_go_trace' could not be resolved: Repository '@com_google_cloud_go_trace' is not defined and referenced by '@org_golang_google_genproto//googleapis/devtools/cloudtrace/v2:cloudtrace'
```

Uhhhh, okay, so the `org_golang_google_genproto` repo rule that rules_go told me to add is busted? I ALSO need to add new repo for  `com_google_cloud_go_trace`? But that's already covered by the `go_repository` for `com_google_cloud_go` I added later, isn't?

```
$  bazel query 'deps(@org_golang_google_genproto//googleapis/devtools/cloudtrace/v2:cloudtrace)'
ERROR: Evaluation of query "deps(@org_golang_google_genproto//googleapis/devtools/cloudtrace/v2:cloudtrace)" failed: preloading transitive closure failed: no such package '@com_google_cloud_go_trace//apiv2/tracepb': The repository '@com_google_cloud_go_trace' could not be resolved: Repository '@com_google_cloud_go_trace' is not defined
Loading: 0 packages loaded
```

Wait, do I have to add the `com_google_cloud_go` go_repository BEFORE the `switched_rules_by_language` from `googleapis` or its load?

Nope, that wasn't it.

I still am not sure what's wrong in my non-trivial build. (Trying this on both bazel 6.2.1 and 6.3.1 changed nothing).

I've been a years long user of rules_go and I love the work that y'all have done. But this pattern of coupling releases of different tools with no means of backwards compatibility between the tools and not considering how incredibly unclear the failure modes are even when folks _do_ upgrade both is a real bummer.

Please, please reconsider the tendency to make changes without backwards compatibility, and the tendency to make changes across multiple tools at once and the tendency to make those changes required in order to simply use a new version of Go.

I did all this because I was originally just trying to help the homebrew project [bump the version of Go to 1.21](https://github.com/bazelbuild/bazel-watcher/issues/617#issuecomment-1670228126) and hit problems with their `ibazel` tests being migrated to rules_go 0.41.0 that I wanted to see reproduced in my own private build. Like, straight up, the problems in rules_go and gazelle are now affecting my ability to help upgrade folks to Go 1.21 outside of bazel.

**Comment by linzhp** [comment]
Sorry for the frustrations. I tried to make this process less painful to users, but there are difficult choices that I had to make:

1. all maintainers are full time employees for some companies other than Google. We use rules_go and Gazelle for work, but to keep them alive requires much more than that, and I find it hard to justify my working hours on releasing these two projects. I personally have to work at nights and weekends for such work. With limited time, we won't be able to make any progress if we try to make them backward compatible between releases. That's why we never made them 1.0.
2. rules_go 0.41 and Gazelle 0.32 are very rare cases where people have to upgrade both together. They are to remove a coupling between the two with regards to googleapis. There may be a way to make the upgrade smoother, but with my limited time, it means it would take longer, and people will be stuck with old googleapis for longer.


In addition, big changes like this won't work with automatic upgrades. That's an expectation for any dependency upgrader.
