### ISSUE TITLE
Build failures when using a local go 1.21.0 SDK

### ISSUE THREAD

**Issue by adam-azarchs** [bazelbuild/rules_go#3665]
### What version of rules_go are you using?

v0.41.0

### What version of gazelle are you using?

v0.32.0

### What version of Bazel are you using?

6.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux/amd64

### Any other potentially useful information about your toolchain?

Using `go_host_sdk`, with go 1.21.0.

### What did you do?

Attempt to build with external repository dependencies (not bzlmod, though I doubt that matters here)

### What did you expect to see?

Working build.

### What did you see instead?

```
ERROR: An error occurred during the fetch of repository 'org_golang_google_grpc_cmd_protoc_gen_go_grpc':
   Traceback (most recent call last):
        File "/.../external/bazel_gazelle/internal/go_repository.bzl", line 256, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch org_golang_google_grpc_cmd_protoc_gen_go_grpc: fetch_repo: google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0: GOPROXY list is not the empty string, but contains no entries
```
Building with `go build` works fine.

A little bit of Googling around turned up https://github.com/golang/go/issues/61928.  I suspect the issue is that
https://github.com/bazelbuild/rules_go/blob/139ec3c5ebf86682527aa1decc09b01d17235b97/go/private/BUILD.sdk.bazel#L77-L84
is not pulling in the new `go.env` file from the root of the SDK directory.

Honestly I'm not sure whether I'd count this as a bug in `rules_go` (for not including the file) or `go` itself (for failing this way if the file is missing, rather than just falling back on sensible defaults like it would if the file was present but empty).

**Comment by fmeum** [comment]
Sounds good!
