### ISSUE TITLE
Remove -pie from LDFLAGS if buildmode is not pie

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#3691]
### What version of rules_go are you using?

0.41.0

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

6.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Debian 12

### Any other potentially useful information about your toolchain?

LLVM 15 with LLD. On Debian like systems, can be set up with:
```sh
sudo apt-get install clang-15 lld-15
```

### What did you do?

CASE 1: Tried to build and run a cgo test target within this project with the `--force_pic` flag.
```sh
CC=clang-15 bazel run --force_pic //tests/core/cgo:c_srcs
```

CASE 2: Instead of one of the tests from this repo, a simpler Go program can also be:
```go
// File main.go
package main

// #cgo LDFLAGS: -lm
// #include <math.h>
import "C"
import "fmt"

func main() {
	fmt.Println(int(C.sqrt(100.0)))
}
```

with a build target that is simply:
```starlark
go_binary(
  name = "main",
  srcs = ["main.go"],
  cgo = True,
)
```

### What did you expect to see?

The test target run completing successfully, and/or the simpler Go program run completing successfully.

### What did you see instead?

```txt
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x9dc40 text= 0x5611882ecc40 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x561188274f78?, 0x0?})
	GOROOT/src/runtime/panic.go:1047 +0x5d fp=0x7ffd1e384c80 sp=0x7ffd1e384c50 pc=0x56118831cefd
runtime.moduledataverify1(0x7ffd1e384dac?)
	GOROOT/src/runtime/symtab.go:627 +0x806 fp=0x7ffd1e384d80 sp=0x7ffd1e384c80 pc=0x5611883384e6
runtime.moduledataverify(...)
	GOROOT/src/runtime/symtab.go:613
runtime.schedinit()
	GOROOT/src/runtime/proc.go:710 +0x3a fp=0x7ffd1e384de0 sp=0x7ffd1e384d80 pc=0x5611883209da
runtime.rt0_go()
	src/runtime/asm_amd64.s:349 +0x11c fp=0x7ffd1e384de8 sp=0x7ffd1e384de0 pc=0x561188347ddc
```

### Notes

This crash is happening because `force_pic` is sending the `-pie` flag to the linker, which gets passed along as part of CGO_LDFLAGS. But because the buildmode is not set to "pie" in the go_binary target, I think the stdlib is mismatched.

This is not a problem with the standard Go toolchain because it filters out the "-pie" flag from CGO_LDFLAGS.

Building under normal buildmode, will filter out "-pie" from the linker command. Notice that there were no -extldflags set for the link step.
```sh
CC=clang-15 CGO_LDFLAGS='-v -fuse-ld=lld -pie' go build -x main.go
```

To force sending "-pie" to the linker,  you will have to explicitly set -extldflags.
```sh
CC=clang-15 CGO_LDFLAGS='-v -fuse-ld=lld' go build -ldflags -extldflags='-pie' -x main.go
```

**Comment by fmeum** [comment]
The analysis looks just right, thanks! 

Would you be interested in sending a fix? https://github.com/bazelbuild/rules_go/blob/ba4668684b2eb7dbe7f197dc9435a780fecbfbf8/go/private/rules/cgo.bzl#L71-L74 seems like a good spot to place this in.

**Comment by siddharthab** [comment]
Thanks. I sent a PR that works for this specific example. But I am not sure if I am matching all the conditions right. Will you be able to take a look at the TODO I have in my change?

**Comment by mmellin** [comment]
I see the same error when trying to build a `go_proto_library` target on my Ubuntu 22.04 using LLVM @v16.0.4. If I remove LLVM, it seems to work fine.

```
 fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x564b54c01542?, 0x0?})
        GOROOT/src/runtime/panic.go:1047 +0x5d fp=0x7ffd201b67e0 sp=0x7ffd201b67b0 pc=0x564b54f26f5d
runtime.moduledataverify1(0x564b552c47a0?)
        GOROOT/src/runtime/symtab.go:627 +0x806 fp=0x7ffd201b68e0 sp=0x7ffd201b67e0 pc=0x564b54f44866
runtime.moduledataverify(...)
        GOROOT/src/runtime/symtab.go:613
runtime.schedinit()
        GOROOT/src/runtime/proc.go:710 +0x3a fp=0x7ffd201b6940 sp=0x7ffd201b68e0 pc=0x564b54f2aa3a
runtime.rt0_go()
        src/runtime/asm_amd64.s:349 +0x11c fp=0x7ffd201b6948 sp=0x7ffd201b6940 pc=0x564b54f5619c
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 2.
```

Rule:
``` 
go_proto_library(
    name = "v1_go_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_grpc",
        "@com_github_grpc_ecosystem_grpc_gateway_v2//protoc-gen-grpc-gateway:go_gen_grpc_gateway",
    ],
    importpath = "mydomain.com/mysrvc/proto/mysrvc/v1",
    proto = ":v1_proto",
    visibility = ["//visibility:public"],
    deps = ["@googleapis//google/api:annotations_go_proto"],
)
```

Bazel 6.3.2
Rules_go 0.44.0
rules_proto_grpc 4.5.0
toolchains_llvm 0.10.3
Go 1.20.7
grpc-ecosystem/grpc-gateway/v2 @v2.16.2


I seemed to solve it by upgrading the grpc-gateway compiler lib `github.com/grpc-ecosystem/grpc-gateway/v2` pkg to v2.19.1.

**Comment by aran** [comment]
We hit a similar-looking panic, with up-to-date toolchains_llvm and rules_go,  also with a protoc plugin (`protoc-gen-go-json`), not with `force_pic`, but I think it's a separate issue. We're using Chromium project sysroots, but with these same sysroots, I think our Ubuntu dev machines are not compatible so the tool breaks.

**Comment by sfc-gh-mhazy** [comment]
@aran I have very similar setup as you (toolchains_llvm, rules_go, chromium sysroot and without force_pic) and I made some progress in debugging:

1. Clang started using https://github.com/llvm/llvm-project/commit/ca68038d12a23fa7ebb2b1ccbda93c321635e6bf which enabled `pie` by default. 
2. Apparently with `linkmode=normal` for go target, there is some incompatibility.

I was able to fix it in 3 ways:
1. Add `-no-pie` to link_flags of llvm toolchain.
2. Build my own clang with `-DCLANG_DEFAULT_PIE_ON_LINUX=OFF`
3. set `linkmode=pie` in go target. 

@fmeum  There is an open question why rules_go are failing to compile correctly. Perhaps linkmode should default to pie if using clang as cc compiler. 

We should probably open a separate issue as it's different from the original topic.

**Comment by fmeum** [comment]
Maybe rules_go should pass `-no-pie` in `normal` mode? And then we make an effort to make `pie` the new default link mode.

**Comment by mering** [comment]
This is blocking our update to LLVM 15+ now as well. Thanks for your work and looking forward to see this fixed!

**Comment by fmeum** [comment]
PRs are welcome!

**Comment by mering** [comment]
@fmeum There is already #3693.

**Comment by fmeum** [comment]
> @fmeum There is already #3693.

Right. @siddharthab Do you have time to look into it again after my latest comment?

**Comment by mering** [comment]
> I was able to fix it in 3 ways:
> 
> 1. Add `-no-pie` to link_flags of llvm toolchain.
> 2. Build my own clang with `-DCLANG_DEFAULT_PIE_ON_LINUX=OFF`
> 3. set `linkmode=pie` in go target.

@sfc-gh-mhazy thanks for your analysis!

We added `build --@io_bazel_rules_go//go/config:linkmode=pie` to our `.bazelrc` as a mitigation for now.

> Maybe rules_go should pass `-no-pie` in `normal` mode? And then we make an effort to make `pie` the new default link mode.

@fmeum I think making `pie` the new default link mode would be desired. Of course it makes sense to also fix `normal` mode.

While I couldn't reproduce this issue, my colleagues told me that #3693 (used via `git_override`) did not fix the issue for them. Might be that there were old cache files but even in this case the caches should be correctly invalidated by changes to the action graph.

**Comment by siddharthab** [comment]
> > > @fmeum There is already #3693.
> >
> > Right. @siddharthab Do you have time to look into it again after my latest comment?
> 
> Yes. Sorry, I have been on and off looking into it but have not had the time to finish the change. As I understand it, your last comment says I should filter out the -pie flag from the cc_toolchain features. I have found that there is a place where we are filtering flags from the cc_toolchain, so maybe I just need to add this flag there.

@fmeum Can you take another look at the PR?

**Comment by mering** [comment]
> And then we make an effort to make `pie` the new default link mode.

@fmeum What would be needed to make `pie` the new default link mode?

**Comment by aran** [comment]
Making pie the default link mode maybe should become a separate issue/discussion?

Call this an amicus brief: It may be a little strange for rules_go to diverge unnecessarily from what Go tooling does out of the box. This might be relevant to the go implementation: https://github.com/golang/go/blob/master/src/internal/platform/supported.go#L238
