### ISSUE TITLE
Testcase cgo:opts_test is getting failed at BAZEL@HEAD                                        

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_go#3704]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3321#018ab594-7208-4a0c-b795-c503d46be980

Platform : rules_go (:debian: 11 Bullseye (OpenJDK 17, gcc 10.2.1))

Logs:
```
//tests/core/cgo:opts_test   FAILED 
//tests/core/transition:hermeticity_test    FAILED
```

Steps:
```
git clone -v https://github.com/bazelbuild/rules_go.git
git reset 7309aba88014f97d6a3c2916a5ed4e2ca2017d83 --hard
export USE_BAZEL_VERSION=6446607f6eb2ce2b1ff5e5d8d429456dcdfec01f
bazel test //...

```
Culprit Found: [5100d8716f4b9ce25db40c131a94f346055ca9cb](https://github.com/bazelbuild/bazel/commit/5100d8716f4b9ce25db40c131a94f346055ca9cb)

CC Greenteam @comius

**Comment by comius** [comment]
cc @tjgq the culprit seems likely cause

**Comment by fmeum** [comment]
I can't reproduce the failure locally, neither before nor after the culprit. My suspicion is that this isn't related to @tjgq's changes.

@meteorcloudy Did anything change about the CI setup recently, e.g. updates to compilers or machine images?

**Comment by meteorcloudy** [comment]
There is no CI changes recently.

**Comment by meteorcloudy** [comment]
I suspect you need remote execution to reproduce the problem.

**Comment by fmeum** [comment]
@tjgq Sorry, I was looking at the wrong test. The failing one is more complex than what I first thought and it is possible that your commit affects it.

**Comment by sgowroji** [comment]
CI looks green for rules_go now https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3353. Closing this issue now.

**Comment by sgowroji** [comment]
Rules\_go CI looks green now. We can close this issue now.
