### ISSUE TITLE
Clarification needed re: handing of external workspaces

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#373]
I am working through an issue that I feel may be related to changes in how rules_go detects whether a repository is considered `external`.  I am looking at:

https://github.com/bazelbuild/rules_go/blame/master/go/def.bzl#L89-L95

With rules_go at 2d9f328a9723baf2d037ba9db28d9d0e30683938:

```python
local_repository(
    name = "io_bazel_rules_go",
    path = "/Users/pcj/github/rules_go",
)

# git_repository(
#     name = "io_bazel_rules_go",
#     commit = "2d9f328a9723baf2d037ba9db28d9d0e30683938",
#     remote = "https://github.com/bazelbuild/rules_go.git",
# )
```

And the following WORKSPACE definition:

```python
new_http_archive(
    name = "com_github_googleapis_googleapis",
    sha256 = "63555639d21dd0041a2e7e02d0af57b60da0b8dfccbf638fba8a930ceb555176",
    url = "https://github.com/googleapis/googleapis/archive/6277786c1352a6d7be1e5a5d697394e1802f6608.zip",
    strip_prefix = "googleapis-6277786c1352a6d7be1e5a5d697394e1802f6608",
    build_file_content = GOOGLEAPIS_BUILD_FILE,
)

```

Having BUILD file content:

```python
# GOOGLEAPIS_BUILD_FILE
package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
go_prefix("google.golang.org/genproto/googleapis/api/label")

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_library")

go_proto_library(
    name = "go_label_proto",
    protos = [
        "google/api/label.proto",
    ],
    go_package = "google.golang.org/genproto/googleapis/api/label",
    verbose = 0,
)
```

Generates the corresponding protobuf file:

```
$ bazel build @com_github_googleapis_googleapis//:go_label_proto
  bazel-bin/external/com_github_googleapis_googleapis/go_label_proto.a
```

And the files generated by rules_go:

```sh
$ tree bazel-out/local-fastbuild/bin/external/com_github_googleapis_googleapis
bazel-out/local-fastbuild/bin/external/com_github_googleapis_googleapis
├── bazel-out
│   └── local-fastbuild
│       └── bin
│           └── external
│               └── com_github_googleapis_googleapis
│                   └── go_label_proto.a.GoCompileFile.params
├── go_label_proto.a
└── go_label_proto.a.dir
    ├── github.com
    │   └── golang
    │       ├── glog.a -> ../../../../../../../../bazel-out/local-fastbuild/bin/external/com_github_golang_glog/go_default_library.a
    │       └── protobuf
    │           └── proto.a -> ../../../../../../../../../bazel-out/local-fastbuild/bin/external/com_github_golang_protobuf/proto/go_default_library.a
    ├── golang.org
    │   └── x
    │       └── net
    │           └── context.a -> ../../../../../../../../../bazel-out/local-fastbuild/bin/external/org_golang_x_net/context/go_default_library.a
    └── google.golang.org
        ├── genproto
        │   └── googleapis
        │       └── bazel-out
        │           └── local-fastbuild
        │               └── genfiles
        │                   └── external
        │                       └── com_github_googleapis_googleapis
        │                           └── google.golang.org
        │                               └── genproto
        │                                   └── googleapis
        │                                       └── api
        │                                           └── label
        │                                               └── label.pb.go -> ../../../../../../../../../../../../../../../../../../../bazel-out/local-fastbuild/genfiles/external/com_github_googleapis_googleapis/google.golang.org/genproto/googleapis/api/label/label.pb.go
        └── grpc.a -> ../../../../../../../bazel-out/local-fastbuild/bin/external/org_golang_google_grpc/go_default_library.a
```

The end-problem I'm having is a missing import when trying to compile a target that depends on the `label.pb.go` file.  This is a `go_library` rule called internally by the `go_proto_library` macro definition.  In other words, the protobuf source file is generated, but I can't get it to compile because of the missing import problem.

```
github.com/pubref/rules_protobuf/tests/external_proto_library/bazel-out/local-fastbuild/genfiles/message.pb.go:19: can't find import: "google.golang.org/genproto/googleapis/api/label"
```

When rules_go sets up the `a.dir`, in [symlink_tree_commands](https://github.com/bazelbuild/rules_go/blame/master/go/def.bzl#L89), the line `is_external("bazel-out/local-fastbuild/bin/external/com_github_googleapis_googleapis/go_label_proto.a.dir")` reports `False` for that particular string (since it does not start with "`../`").

Anyhow, this seems like the wrong conclusion... am I in error to believe the string `"bazel-out/local-fastbuild/bin/external/com_github_googleapis_googleapis/go_label_proto.a.dir"` *is* an external directory?  Also, it seems wrong to see "bazel-out/local-fastbuild/genfiles/external/com_github_googleapis_googleapis/google.golang.org/genproto" portion of the path (the deepest leaf in the graphic above) should be repeated within the symlinked target with the `a.dir`.

I'm confused by the code comment...

> "In old versions of Bazel, external execroot paths were of the form bazel-out/host/bin/external/repo/path/to/target, so counting up the /s worked fine. In bazel 5.0+, execution roots began to look like ../repo/bazel-out/host/bin/path/to/target.  The ../repo basically ends up resolving to 0 path elements, so 2 segments should be removed from the count.* 

...because AFAIK nobody is on bazel 5.0+ yet.

However, clearly rules_go is dealing with most external repositories correctly, so I'm probably doing something wrong.  

@kchodorow @jayconrod (help anybody!) any thoughts?
 
```sh
$ bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:50:12 2017 (1489668612)
Build timestamp: 1489668612
Build timestamp as int: 1489668612
```

**Comment by jayconrod** [comment]
Thanks for reporting this. I'll look into this today.

Regarding the `is_external` function, I believe it returns False for every path that Bazel provides, external or not. I guess there was some change in behavior a while ago. #360 will remove that function and will simplify symlink handling in general. I'll make sure it works for this case before merging though.

**Comment by kchodorow** [comment]
Please do not remove id_external!!!!

It is needed for an upcoming change to Bazel.

**Comment by jayconrod** [comment]
@kchodorow Ah, I thought this was supporting old behavior, not new behavior that hadn't been merged yet. I'll rewrite #360 to take this into account and add you as a reviewer when it's ready.

**Comment by kchodorow** [comment]
Thank you!

**Comment by jayconrod** [comment]
I tried building this with the BUILD and WORKSPACE files you provided, but I ran into some issues. First, it looks like `go_package` is not recognized by `go_proto_library`; it gets passed on to `go_library`, which does not have an attribute of that name. I commented that out, but then I got an error that label.pb.go was not created. I didn't dig further into `go_proto_library` to see what's going on; maybe I have it set up wrong.

Here's the complete WORKSPACE file I'm using.

```bzl
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go",
    tag = "0.4.2",
)
load("@io_bazel_rules_go//go:def.bzl", "go_repositories")

go_repositories()

git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.7.1",
)
load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_repositories")
go_proto_repositories()

GOOGLEAPIS_BUILD_FILE = """
# GOOGLEAPIS_BUILD_FILE
package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
go_prefix("google.golang.org/genproto/googleapis/api/label")

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_library")

go_proto_library(
    name = "go_label_proto",
    protos = [
        "google/api/label.proto",
    ],
    #go_package = "google.golang.org/genproto/googleapis/api/label",
    verbose = 0,
)
"""

new_http_archive(
    name = "com_github_googleapis_googleapis",
    sha256 = "63555639d21dd0041a2e7e02d0af57b60da0b8dfccbf638fba8a930ceb555176",
    url = "https://github.com/googleapis/googleapis/archive/6277786c1352a6d7be1e5a5d697394e1802f6608.zip",
    strip_prefix = "googleapis-6277786c1352a6d7be1e5a5d697394e1802f6608",
    build_file_content = GOOGLEAPIS_BUILD_FILE,
)
```

**Comment by pcj** [comment]
Sorry @jayconrod the `go_package` option is a new option I was working on, so it's not on a published branch at the moment.  I'll update and push that branch later today.

**Comment by jayconrod** [comment]
So as I understand the problem, the generated file `external/com_github_googleapis_googleapis/google/api/label.pb.go`, contains an import for `google.golang.org/genproto/googleapis/api/label`, but there's no package that matches that import listed in the deps of `go_label_proto`.

The logic to translate between labels and import paths is in [`_go_importpath` at go/def.bzl:178](external/com_github_googleapis_googleapis/google/api/label.pb.go). Based on that name, there would need to be a library with the label `@com_github_googleapis_googleapis//:go_default_library`.

**Comment by pcj** [comment]
This turned out to be an error on my end.  Thanks for helping with it!  Hopefully it had the side-effect of clarification for #360.
