### ISSUE TITLE
Bazel 7.0.0rc2 fails to build `gomock` rules

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/rules_go#3742]
### What version of rules_go are you using?

0.42.0

### What version of gazelle are you using?

0.33.0

### What version of Bazel are you using?

7.0.0rc2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux x86 64

### What did you do?

```
tfrench@tfrench-go ~/go-code % bazel build src/code.uber.internal/...
INFO: Writing tracer profile to '/tmp/bazel_20231031161831_yk31a'
INFO: Invocation ID: 82d08ebe-d86a-4400-bef0-52d222f9e014
ERROR: /home/user/go-code/src/.../BUILD.bazel:28:7: //src/.../arcanist:arcanist_gomock: no such attribute 'copyright_file' in 'gomock' rule
```

**Comment by fmeum** [comment]
In Bazel 7 it is an error to pass `None` values to non-existing attributes. This was silently ignored by earlier Bazel versions. I'm pretty sure that's the cause here.

**Comment by tyler-french** [comment]
Interesting. It does seem like the attributes exist here: https://github.com/bazelbuild/rules_go/blob/master/extras/gomock.bzl
So would need to probably do some further debugging.
