### ISSUE TITLE
rules_go-v0.44.0.zip and rules_go-v0.44.1.zip missing from mirror.bazel.build

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/rules_go#3807]
I noticed warnigs when trying the v0.44.0 and v0.44.1 releases, because the WORKSPACE snippets for those releases mention two URLs which return 404 errors:
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.0/rules_go-v0.44.0.zip
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.44.1/rules_go-v0.44.1.zip

This is not super urgent, the builds still work because the other github.com URL works, but FYI in case mirror.bazel.build needs manual updating.

**Comment by fmeum** [comment]
I filed  https://github.com/bazelbuild/bazel/issues/20701.

**Comment by mostynb** [comment]
Added https://mirror.bazel.build/github.com/golang/sys/archive/refs/tags/v0.15.0.zip to the upload request.

**Comment by alexeagle** [comment]
Looks like this can be closed.

(@fmeum is it time to take over the mirror from Google? I haven't even bothered trying to mirror anything because the process is manual.)
