### ISSUE TITLE
Nogo stuck in dependency cycle when using bzlmod

### ISSUE THREAD

**Issue by alirankine-dojo** [bazelbuild/rules_go#3809]
### What version of rules_go are you using?

0.44.0 (via bzlmod)

### What version of gazelle are you using?

0.35.0 (via bzlmod)

### What version of Bazel are you using?

7.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS 14.1.2

### Any other potentially useful information about your toolchain?

go 1.21.5

### What did you do?

Adding nogo via bzlmod results in a dependency cycle identical to that described in #2479.
When building an application, the following error appears:
```shell
ERROR: /private/var/tmp/_bazel_user/60a93a897b2d535ad5c3d919eaa075c2/external/rules_go~0.44.0~go_sdk~io_bazel_rules_nogo/BUILD.bazel:3:6: in alias rule @@rules_go~0.44.0~go_sdk~io_bazel_rules_nogo//:nogo: cycle in dependency graph:
    //:backend (7a4f3b2564699f7b8bd4cc135c50d0547ebe04e011e302478e62038755eda25c)
    //:backend (7baf2462b8dc082d7868aad895e80c01f6d9dba247a3296e4fd6dd318f4433c1)
    @@rules_go~0.44.0//:go_context_data (7baf2462b8dc082d7868aad895e80c01f6d9dba247a3296e4fd6dd318f4433c1)
    @@rules_go~0.44.0//:go_context_data (1f5a65a4bcb5e21d7d3a749e4180da9c5c4c3dd7093afe41092695dc92f86a5f)
.-> @@rules_go~0.44.0~go_sdk~io_bazel_rules_nogo//:nogo (2ebdd81607ac0a6115aa3bd8dc8f6d2f7beaef81234bfa9a4aff5033b6eec69c)
|   //:backend (2ebdd81607ac0a6115aa3bd8dc8f6d2f7beaef81234bfa9a4aff5033b6eec69c)
|   @@rules_go~0.44.0//:go_context_data (2ebdd81607ac0a6115aa3bd8dc8f6d2f7beaef81234bfa9a4aff5033b6eec69c)
`-- @@rules_go~0.44.0~go_sdk~io_bazel_rules_nogo//:nogo (2ebdd81607ac0a6115aa3bd8dc8f6d2f7beaef81234bfa9a4aff5033b6eec69c)
ERROR: Analysis of target '//:backend' failed; build aborted
INFO: Elapsed time: 2.452s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

from the `MODULE.bazel`:
```starlark

bazel_dep(name = "gazelle", version = "0.35.0")
bazel_dep(name = "rules_go", version = "0.44.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.21.5")
go_sdk.host()
nogo = go_sdk.nogo(
    nogo="//:backend",
)
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
    go_deps,
# dependencies snipped
)
```

### What did you expect to see?

A completed build OR a list of lint issues

### What did you see instead?

Dependency Cycle error.

**Comment by fmeum** [comment]
Do you have a reproducer you can share? I didn't manage to reproduce this in the "obvious" way, trying to `bazel build` a registered `nogo` target.

If you can't isolate the failure, could you run `bazel config ID1 ID2` on the configuration IDs right next to the targets in the cycle? The config differences should help us track this down.

**Comment by alirankine-dojo** [comment]
I'm almost certain that this is something stupid that i've done 😄. I can reproduce the error in this silly toy repo: [https://github.com/alirankine-dojo/bazeltest](https://github.com/alirankine-dojo/bazeltest)

**Comment by fmeum** [comment]
@alirankine-dojo You need to point the `go_sdk.nogo` tag to a target of the `nogo` rule, not a `go_binary`. See https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst for how to define such a target.
