### ISSUE TITLE
@go_sdk//:bin/gofmt is failed to run

### ISSUE THREAD

**Issue by azakharchenko-msol** [bazelbuild/rules_go#3871]
### What version of rules_go are you using?
bazel_dep(name = "rules_go", version = "0.45.1", repo_name = "io_bazel_rules_go")

### What version of gazelle are you using?
bazel_dep(name = "gazelle", version = "0.35.0", repo_name = "bazel_gazelle")

### What version of Bazel are you using?
bazel 7.0.2

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
ubuntu 22.04 x86_64

### What did you do?
```
bazel run @go_sdk//:bin/gofmt
WARNING: Target pattern parsing failed.
ERROR: Skipping '@go_sdk//:bin/gofmt': No repository visible as '@go_sdk' from main repository
ERROR: No repository visible as '@go_sdk' from main repository
```
cat MODULE.bazel
...
bazel_dep(name = "rules_go", version = "0.45.1", repo_name = "io_bazel_rules_go")
go_sdk = use_extension("@io_bazel_rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(name = "go_sdk", version = "1.21.6")

### What did you expect to see?
gofmt runs

### What did you see instead?
```
ERROR: Skipping '@go_sdk//:bin/gofmt': No repository visible as '@go_sdk' from main repository
ERROR: No repository visible as '@go_sdk' from main repository
```

**Comment by fmeum** [comment]
We recommend using `bazel run @io_bazel_rules_go//go -- fmt` instead since that indirection handles a few things directly invoking an SDK binary doesn't. This has different syntax than `gofmt` though.

Alternatively, bring the `go_sdk` repo in scope via `use_repo(go_sdk, "go_sdk")`.

**Comment by azakharchenko-msol** [comment]
@fmeum Thank you!
