### ISSUE TITLE
Test binaries swallow SIGTERM; printed stack traces misleading

### ISSUE THREAD

**Issue by rickystewart** [bazelbuild/rules_go#3875]
### What version of rules_go are you using?

v0.46.0

### What version of gazelle are you using?

v0.35.0

### What version of Bazel are you using?

6.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS/arm64

### Any other potentially useful information about your toolchain?

None

### What did you do?

Run a test with `--test_timeout=5`

### What did you expect to see?

The test will time out after 5 seconds

### What did you see instead?

The test times out after 20 seconds. I tried a few different values and saw that the test will time out 15 seconds after I request it to, for example, if I set the timeout to 10 seconds, it will time out in fact after 25 seconds, etc. It seems like whatever the timeout "should" be, `rules_go` is adding 15 seconds to it. This behavior wasn't there in `rules_go` v0.43.

**Comment by fmeum** [comment]
This happens because we are catching the SIGTERM sent by Bazel when reaching the timeout, which makes it so that Bazel sends a SIGKILL after the grace period of 15 seconds.

**Comment by fmeum** [comment]
We could reraise the SIGTERM here:
https://github.com/bazelbuild/rules_go/blob/145b042e21a073fa3637c096bf9779cdbcac6f75/go/tools/bzltestutil/timeout.go#L37

However, that would also result in any other SIGTERM handlers being called again.

@linzhp @illicitonion Do you see this causing problems?

**Comment by rickystewart** [comment]
The comment says the following:

```
We do not panic (like native go test does) because
users may legitimately want to use SIGTERM in tests and prints are less disruptive than
panics in that case.
```

I would push back against this and say that to whatever extent possible, it is advantageous for users if `rules_go`'s behavior matches the native `go test`'s.

Additionally:
1) it's not desirable for a test binary to unconditionally "ignore" `SIGTERM` and refuse to clean up or die
2) due to this behavior, the printed stack trace is misleading -- it shows the stack traces 15 seconds before the test timed out, not the traces when the timeout actually occurred

**Comment by fmeum** [comment]
The reason we can't just do what `go test` does without breaking some use cases is that we don't manage the timeout ourselves, but just react to Bazel sending a SIGTERM. Since we already have a test wrapper, maybe we could translate the SIGTERM to something else? We would need to dig into how exactly Bazel sends the signal.

**Comment by linzhp** [comment]
I am worried that the 3-second reduction of timeout could be too much for small tests. For example, if the timeout set by user is only 3 seconds, then the test will always timeout.

How about a mix of two approaches? We set the `-test.timeout` according to the value of `TEST_TIMEOUT`, but at the same time swallow Bazel's SIGTERM. The 15 second delay between SIGTERM and SIGKILL will be the time for tests to clean up.

This fixes the first regression described in #3746, but I am not sure if fixes the second one.

**Comment by fmeum** [comment]
I'm thinking that we should fix this at the root and make it so that Bazel (optionally) sends a SIGQUIT rather than a SIGTERM on timeout. The former is pretty much a standard for printing debug information at this point. What do you think about this?

**Comment by linzhp** [comment]
I am fine with SIGQUIT, but I think we still need to set `-test.timeout`, because it allows the test binary to produce proper test.xml, which shows which test case caused the timeout. This is needed for systems to monitor the healthiness of test cases.
