### ISSUE TITLE
[Bazel CI] Test failure gopackagesdriver_test with Bazel@HEAD in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_go#3889]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3720#018e4049-fb9b-4c0e-8f91-652ef7e9416f

Platform: MacOS, Windows, Ubuntu

Logs:

```
FAIL: [0m//go/tools/gopackagesdriver:gopackagesdriver_test (Exit 1) (see /private/var/tmp/_bazel_buildkite/3e69e71b71ef10f5180eefcc51399150/execroot/io_bazel_rules_go/bazel-out/darwin_x86_64-fastbuild/testlogs/go/tools/gopackagesdriver/gopackagesdriver_test/test_attempts/attempt_1.log)
```

Culprit:

Steps:

```
 git clone https://github.com/bazelbuild/rules_go
git reset 7538c5438308e86ab6ece6692847226cd8c9fda6  --hard
export USE_BAZEL_VERSION=6f254ce0f95d70e744b513a94d577036712befac
bazel test //... 
```

CC Greenteam @Wyverald

**Comment by fmeum** [comment]
@jayconrod It seems more likely that this is caused by https://github.com/bazelbuild/rules_go/commit/7538c5438308e86ab6ece6692847226cd8c9fda6 then by a Bazel commit (I checked the history and nothing stood out). I can also look into it though.

**Comment by jayconrod** [comment]
I'll try to reproduce the issue today and figure out what's going on.

**Comment by fmeum** [comment]
> I'll try to reproduce the issue today and figure out what's going on.

Wild guess: Bazel@HEAD returns a fixed non-semver version string, which may throw off the feature detection.

**Comment by jayconrod** [comment]
@fmeum You were exactly right. It returns `development version`. The surprising thing was that we assume that means `6.0.0`. #3893 should fix it.
