### ISSUE TITLE
Building for a different GOARM version (passing an environment variable to Go compiler)?

### ISSUE THREAD

**Issue by popovicu** [bazelbuild/rules_go#3992]
### What version of rules_go are you using?

0.46.0

### What version of gazelle are you using?

0.35.0

### What version of Bazel are you using?

Bazelisk version: v1.19.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux, x86_64

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

I'm building a `go_cross_binary` for Raspberry Pi Zero. When I build without Bazel, I can just do the following:

```
env GOOS=linux GOARCH=arm GOARM=5 go build
```

The binary then runs correctly. I should emphasize there is **no cgo involved**. I build my binary this way:

```python
go_cross_binary(
    name = "my_binary_arm",
    platform = "@rules_go//go/toolchain:linux_arm",
    target = ":my_binary",
)
```

When I debug my subcommands, I see this correctly:

```
CGO_ENABLED=0 \
    GOARCH=arm \
    GOEXPERIMENT=nocoverageredesign \
    GOOS=linux \
```

Would it be possible to 'sneak in' another environment variable for this build step?

### What did you expect to see?

I expected the binary to run on my device.

### What did you see instead?

The binary immediately crashes with an 'illegal instruction'.

**Comment by fmeum** [comment]
You can define your own platform with one of the `constraint_value`s from https://github.com/bazelbuild/rules_go/blob/master/go/constraints/arm/BUILD.bazel and specify that on `go_cross_binary` to build for a specific ARM version.

**Comment by popovicu** [comment]
Awesome, yes, that worked out:

```python
platform(
    name = "arm_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:armv7",
        "@rules_go//go/toolchain:cgo_off",
        "@rules_go//go/constraints/arm:5",
    ],
)
```

That said, I had to use `@platforms//cpu:armv7` with constraint `arm:5`, which seems a bit counterintuitive... If I just try `@platforms//cpu:arm`, then it says the toolchain is not registered. It's a minor inconvenience, but may be worth addressing at some point.

**Comment by fmeum** [comment]
I don't know enough about ARM versioning to assess what's wrong here, but if you search for usages of both constraints in the rules_go codebase and figure it out, I'm happy to review PRs.
