### ISSUE TITLE
Is `nogo` still experimental?

### ISSUE THREAD

**Issue by albertocavalcante** [bazelbuild/rules_go#3996]
I intend to use `nogo` for a production project, but the [documentation](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) still states:

> WARNING: This functionality is experimental, so its API might change. Please do not rely on it for production use, but feel free to use it and file issues.

The first commit seems to be from 6 years ago - https://github.com/bazelbuild/rules_go/commit/a3c4fd9a29d7459015509965816934ffa46e6e60. Since `rules_go` itself has no `v1.0`, I don't know how to infer when the API has stabilized. Could you please confirm if this warning is still current?

Thanks!

**Comment by fmeum** [comment]
We haven't made any breaking changes to the nogo API in at least three years. I would consider it pretty stable, especially with the Bzlmod way of configuring it. I am actively working on making it more cache-friendly, but that change will be backwards compatible.

**Comment by albertocavalcante** [comment]
Thanks, @fmeum! I appreciate your quick response; that's what I wanted to confirm. Just before I close this, would it be OK to raise a PR to change the wording a little bit so someone would feel more comfortable adopting it? (If not, that's also fine.)

**Comment by fmeum** [comment]
Yes, such a change would be very welcome!
