### ISSUE TITLE
`bazel mod tidy` does not generate `github.com/bazelbuild/bazel-gazelle` repo

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_go#4018]
`rules_go` version 0.49.0
`gazelle` version 0.37.0
Bazel 7.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS on Apple silicon

### What did you do?

When using [this go.mod file](https://github.com/shs96c/target-determinator/blob/bazel7/go.mod), and [this MODULE.bazel file](https://github.com/shs96c/target-determinator/blob/bazel7/MODULE.bazel), running `bazel mod tidy` doesn't make any changes to [the `use_repo` block](https://github.com/shs96c/target-determinator/blob/bazel7/MODULE.bazel#L22-L33).

### What did you expect to see?

I would expect a reference to `com_github_bazelbuild_bazel_gazelle` to be added to the `use_repo` block because of [this entry in `tools.go`](https://github.com/shs96c/target-determinator/blob/bazel7/tools/tools.go#L7), and because the repo is listed as a [required dependency](https://github.com/shs96c/target-determinator/blob/bazel7/go.mod#L9) of the project.

### What did you see instead?

No entry for `com_github_bazelbuild_bazel_gazelle` is generated.

**Comment by fmeum** [comment]
This is working as intended: If we were to add a `go_repository` for Gazelle, we would have two repos providing Go targets for it: that `go_repository` and the Bazel module `gazelle`.

The Go language extension for Gazelle should automatically generate references to the `gazelle` `bazel_dep`. Does that work for you?

**Comment by shs96c** [comment]
`bazel run gazelle` adds a reference to the `@com_github_bazelbuild_bazel_gazelle` repo.

**Comment by fmeum** [comment]
Caused by a directive: https://github.com/shs96c/target-determinator/blob/ab318eacd32725b0ff5ada51817818630f78273e/BUILD.bazel#L3
