### ISSUE TITLE
correctly handle go_package option in go_proto_library 

### ISSUE THREAD

**Issue by ghasemloo** [bazelbuild/rules_go#403]
https://github.com/bazelbuild/rules_go/blob/master/proto/go_proto_library.bzl#L20
says:
> Gets confused if local protos use 'option go_package'

I am running into this issue. I am trying to use grpc.Status.Proto()
https://github.com/grpc/grpc-go/blob/master/status/status.go
which returns a proto with correct go package name which is based on the go_package option
"google.golang.org/genproto/googleapis/rpc/status;status"
according to:
https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
but when I try to use it in a status proto that is embedded in my proto message I get a type mismatch error.

**Comment by pmbethe09** [comment]
workaround: ignore_go_package_option = 1
will strip the 'option go_package' from the proto before running protoc.

**Comment by pmbethe09** [comment]
but I agree, this should be fixed for real.

**Comment by ghasemloo** [comment]
I am not sure the workaround will handle the case. The ones for gRPC are generated correctly with the right package name and are part of go genproto repo, I am not generating them. I am only generating my own ones which bazel proto rules for go do not handle go_package option so we get mismatch. 

For now we are manually converting between them everywhere we get a type mismatch.
