### ISSUE TITLE
Gazelle should default to vendoring if the vendor directory exists

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#404]
Gazelle currently requires `-external vendored` to be passed explicitly on the command line when vendoring is desired. Instead, we should default to vendored mode if the vendor directory exists in the local repository.

This should not affect Gazelle's behavior for external repositories when run through `new_go_repository`. Gazelle should always run in external mode for these, i.e., we should not depend on packages in an external repository's vendor directory.

**Comment by pmbethe09** [comment]
I see, so v1, if //vendor exists, assume everything is vendored -- no mixing and matching of vendored and WORKSPACE deps?

**Comment by jayconrod** [comment]
I should have thought about this idea more carefully yesterday. It doesn't make sense in the context of #388 and #399. If an import path can be resolved in the vendor directory *or* in WORKSPACE, Gazelle should use that. If an import path can't be resolved, the BUILD files emitted by Gazelle will be invalid whether we're in external mode or vendored mode. Maybe there's no need to change the current behavior, other than fixing those issues. WDYT?

About mixing and matching vendored and WORKSPACE deps, I think it should be slightly discouraged, but it's probably necessary sometimes. For example, if you generally want to use WORKSPACE, but you need to make some changes to one dependency, there's a good use case to vendor that one dep.

**Comment by jayconrod** [comment]
Closing old Gazelle issues.

Gazelle will now use vendored libraries if they are present, but for libraries that it can't resolve, it will use whichever -external mode was given.
