### ISSUE TITLE
nogo is very noisy in 0.50.0

### ISSUE THREAD

**Issue by TvdW** [bazelbuild/rules_go#4080]
### What version of rules_go/gazelle/Bazel are you using?

rules_go 0.50.0, gazelle 0.38.0, Bazel 7.3.1, Go 1.23.0

### What did you do?

I wrote some Go code that doesn't compile, and then I tried to build it with `bazel build //...`

### What did you expect to see?

An error message

### What did you see instead?

28 error messages.

Each nogo analyzer is individually reporting on the compilation failure. For example:

    analyzer "asmdecl" failed: analysis skipped due to type-checking error: path/to/file.go:142:71: cannot use b.awsConfig (variable of type *aws.Config) as aws.Config value in argument to s3.NewFromConfig

... repeated for every nogo analyzer.

I can't seem to reproduce this with _every_ compilation failure, which is interesting. The line that manages to trigger this is `s3.NewFromConfig(b.awsConfig)` from `github.com/aws/aws-sdk-go-v2/service/s3`, where `b.awsConfig` is a pointer instead of a struct.

**Comment by fmeum** [comment]
I didn't intentionally change anything non-trivial about what the actual nogo binary does, so I'm a bit surprised to see this. Are you that it didn't happen with 0.49.0? Could you perhaps run a bisect?

**Comment by TvdW** [comment]
Right, yes, I should have done that 😄 bisect points at c5299a8c248453fc3ffab0430c21a616bbdab74f

**Comment by fmeum** [comment]
The nogo action depends on the compilation action if and only if the compile action isn't pure, so that's probably why you are seeing this issue in some cases but not others. 

I think that we should just skip all analyzers if type-checking fails.

**Comment by fmeum** [comment]
@TvdW Could you test https://github.com/bazelbuild/rules_go/pull/4083?

**Comment by TvdW** [comment]
@fmeum Looks good!

    28 analyzers skipped due to type-checking error: [...]
