### ISSUE TITLE
the download mirror url of v0.50 is 404

### ISSUE THREAD

**Issue by hawkingrei** [bazelbuild/rules_go#4085]
https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.50.0/rules_go-v0.50.0.zip 

<img width="868" alt="image" src="https://github.com/user-attachments/assets/4b947e49-eb93-4541-9e24-d8e9a933f360">

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/issues/23496
