### ISSUE TITLE
Can you do hot reloading when running golang program?

### ISSUE THREAD

**Issue by liushuai05** [bazelbuild/rules_go#4090]
### What version of rules_go are you using?
0.48.0
### What version of gazelle are you using?
0.37.0

### What version of Bazel are you using?

7.3.0

### What operating system and processor architecture are you using?
manjaro x86-64

### What did you expect to see?
I ran golang's bazel project normally and found that there was no automatic hot reload after modifying the file. What I want is a project development environment, which can automatically build my project and run it when I modify the archive, like go-air or gowatch. I don't know if it can be realized.

### What did you see instead?
There is no hot reload after modifying the code.

**Comment by dzbarsky** [comment]
Perhaps you are looking for https://github.com/bazelbuild/bazel-watcher ?

**Comment by liushuai05** [comment]
> Perhaps you are looking for https://github.com/bazelbuild/bazel-watcher ?

This is great, yes, it solves my problem, thank you very much.
