### ISSUE TITLE
go_test should combine internal and external test sources

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#413]
When "go test" is run on a package, up to three libraries may be built for the Go sources in the package's directory.

* The package under test. This includes sources with a `package p` declaration (for some name `p`), *without* a `_test.go` filename suffix.
* The internal tests. This includes the sources from the package under test and sources with a `package p` declaration *with* a `_test.go` filename suffix. Internal tests may reference unexported symbols in the package under test.
* The external tests, This includes sources with a `package p_test` declaration with a `_test.go` filename suffix. External tests may reference external symbols in the internal tests (including symbols defined in the package under test).

These libraries are linked (along with dependencies and a generated main package) into a single test executable.

This can be expressed awkwardly in the Go rules with two separate `go_library` and `go_test` rules.

```bzl
go_library(
    name = "p",
    srcs = ["p.go"],
)

go_library(
    name = "p_test_lib",
    srcs = ["p_internal_test.go"],
    library = ":p",
)

go_test(
    name = "p_internal_test",
    library = ":p_test_lib",
)

go_test(
    name = "p_external_test",
    srcs = ["p_external_test.go"],
    deps = [":p_test_lib"],
)
```

Gazelle does not generate these rules. Gazelle links external tests directly against the library under test, which means external tests can't reference symbols exported by internal tests. This breaks `golang.org/x/tools/container/intsets`, which does exactly this (#390).

Instead of modifying Gazelle to generate more complicated rules, we should allow `go_test` to contain both internal and external sources and build them the same way "go test" does. This will reduce impedance mismatch with "go test" and will simplify BUILD files. We can easily determine which sources are internal and which are external by parsing the package declaration before passing them to the compiler.

We could rewrite the example above as:

```bzl
go_library(
    name = "p",
    srcs = ["p.go"],
)

go_test(
    name = "p_test",
    srcs = [
        "p_internal_test.go",
        "p_external_test.go",
    ],
    library = ":p",
)
```

**Comment by pmbethe09** [comment]
One comment about all of this compression of rules...  by doing all of this work under the hood, 
bazel query is less useful, as is incremental compilation.

**Comment by jayconrod** [comment]
It will still be possible to have split internal / external `go_test` rules if desired. This should be backward compatible with previous BUILD files. Gazelle will generate fewer `go_test` rules though.

Fair point about incremental compilation. The same .a files will be produced, but fewer test binaries would be linked.

**Comment by apesternikov** [comment]
looks like golang.org/x/sys/unix is also affected by this problem
https://github.com/apesternikov/bazel_go_repr/blob/master/vendor/golang.org/x/sys/unix/BUILD.bazel
