### ISSUE TITLE
Nogo validations should not run for external packages

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/rules_go#4137]
Right now external dependencies would still generate additional nogo actions, which should be no-ops, but still add an overhead for the action scheduler + sandbox.

We should find a way to skip nogo validation actions for external packages by default on the starlark-level, so that folks who build locally don't have to schedule those actions to begin with.

**Comment by fmeum** [comment]
```starlark
go_register_nogo(
  nogo = "@//:my_nogo"  # my_nogo is in the top-level BUILD file of this workspace
  includes = ["@//:__subpackages__"],  # Labels to lint. By default only lints code in workspace.
  excludes = ["@//generated:__subpackages__"],  # Labels to exclude.
)
```
and its Bzlmod equivalent are supposed to be handled in Starlark. Have you tried that?

**Comment by sluongng** [comment]
ah yeah. I think this is the main diff between using WORKSPACE setup and bzlmod setup 🤕 

Closing this.

**Comment by fmeum** [comment]
It has been backported to WORKSPACE (the snippet above is from WORKSPACE).

**Comment by sluongng** [comment]
ohh... Hmm let me see how we should do it for our repo.

**Comment by sluongng** [comment]
The problem was the `includes` and `excludes` would only be applied via the `go_register_nogo_wrapper` macro. Most WORKSPACE setups define nogo via `go_register_toolchain`, which does not use the macro. BuildBuddy repo was the same deal.

So applying something like this would fix the issue

```
diff --git a/WORKSPACE b/WORKSPACE
index a28e6a46ef..627d2e737b 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -83,7 +83,7 @@ install_static_dependencies()
 install_go_mod_dependencies()

 load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
-load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_register_toolchains", "go_rules_dependencies")
+load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_register_nogo", "go_register_toolchains", "go_rules_dependencies")

 go_rules_dependencies()

@@ -135,10 +135,12 @@ go_download_sdk(
     version = GO_SDK_VERSION,
 )

-go_register_toolchains(
+go_register_nogo(
     nogo = "@//:vet",
 )

+go_register_toolchains()
+
 gazelle_dependencies(
     go_env = {
         "GOPROXY": "https://proxy.golang.org|direct",
```

so the question is: should `go_register_toolchains` use the wrapper macro by default? 🤔

**Comment by fmeum** [comment]
I would personally want to leave any WORKSPACE-specific logic as is. It's hard to update without the potential for breakages and it's going away anyway.

**Comment by annapst** [comment]
In our repository using WORKSPACE no nogo actions got run with this setup, I ended up patching context.bzl like this:
`if _matches_scopes(label, NOGO_INCLUDES + [Label("@@//:__subpackages__")]) and not _matches_scopes(label, NOGO_EXCLUDES)`
Seems like the default has resolved to running nogo on io_bazel_rules_nogo instead of our workspace.

**Comment by fmeum** [comment]
@annapst Could you send a PR?

**Comment by annapst** [comment]
I'll try to look into generalizing this better and share then! In this form we'd force include all subpackages of the main workspace, which is what we need, but might not be what everyone wants.
