### ISSUE TITLE
/bin/bash: Argument list too long

### ISSUE THREAD

**Issue by stephanheinze** [bazelbuild/rules_go#42]
Trying to compile a library with several thousand (generated) go-files will cause failure because of a too long argument list passed to bash.

**Comment by yugui** [comment]
Is it possible to build the go package with "go build"?
If it is possible, I'll treat this issue as a bug.

**Comment by damienmg** [comment]
For most of the rule we use a param files that we generate to avoid hiting
the bash command line limit.

**Comment by stephanheinze** [comment]
I've published the repository: github.com/fgrid/iso20022
The master branch ist go-getable.
I've setup a ```bazel-build``` branch that's NOT buildable by bazel with rules_go 0.0.3.

Hope that helps.

Warning: loads of files :-)
Compiling takes some CPU time.
