### ISSUE TITLE
support stamping multiple packages in one binary

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#432]
We seemingly need to stamp multiple packages now (https://github.com/kubernetes/kubernetes/issues/45298), but the `go_binary` `linkstamp` option only supports a single package.

Any ideas besides adding a new attribute to allow specifying multiple packages? (`linkstamp_pkgs`?)

cc @mikedanese

**Comment by jayconrod** [comment]
We could add another attribute for link stamping multiple packages. It wouldn't be hard to implement, but it would add API complexity.

Do you need different stamps in different packages? Or would it be the same information in both places? I'm not sure the former is possible, because Bazel just gets that information once from the status script.

Is it possible to store the information in one packages and access it from both places?

**Comment by ixdy** [comment]
I agree it wouldn't be hard, and I agree that it'd make things more complex.

It is the same values in both places. We're replacing literally the same variables in both packages.

I'm still trying to figure out if we can avoid this in https://github.com/kubernetes/kubernetes/issues/45298, but our weird dependency tree is making this difficult.

**Comment by mikedanese** [comment]
Can we do something like what the docker rules do and just use link options?

https://github.com/kubernetes/kubernetes/blob/master/build/BUILD#L88

I really wish there was a consistent solution for this across all bazel rules. We have need for this building debs/rpms, docker images, go binaries... and all the APIs are different right now.

ref bazelbuild/bazel#1054

**Comment by jayconrod** [comment]
@ianthehat mentioned this morning that link stamping should be an attribute of `go_library`, not `go_binary` or `go_test`. This would allow multiple libraries to request link stamping in a decentralized way.
This would just be a Boolean `linkstamp` attribute on `go_library`. WDYT?

**Comment by ixdy** [comment]
That would probably solve the issue for us, yes.

**Comment by mikedanese** [comment]
@jayconrod would that trigger rebuilds of the targets that depend on a library when the stamp changes? That sounds pretty painful.

**Comment by mikedanese** [comment]
This would be ideal:
```python
go_binary(
    name = "foo",
    x_defs = {
         "k8s.io/version1": "{FOO_VERSION}",
         "k8s.io/version2": "{FOO_VERSION}",
    },
)
```

Where FOO vars are sourced from the workspace status. This is the API exposed by bazelbuild/rules_docker.

**Comment by jayconrod** [comment]
@mikedanese It would trigger relink of targets that depend on the library, but not a recompile. But yeah, would be painful if you depend on a package where you don't care about the version.

The rules_docker format mentioned above seems pretty good. We could implement that without adding a new attribute. @ianthehat WDYT?

**Comment by ixdy** [comment]
The rules_docker change (https://github.com/bazelbuild/rules_docker/pull/17) was pretty easy since we were already doing the tagging in a Python script, so I could just reuse Python's formatting. It might be a little trickier here, but probably still doable.

(I'm not sure if there's any consensus yet across the various rules around how stamping should work. The implementations are also a little messy since the stamp info files aren't visible to skylark yet.)

**Comment by ixdy** [comment]
Any more thoughts on this? I'm thinking of trying to tackle it.

My current proposal is to extend `gc_linkopts` and/or `_extract_extldflags` (in `go/private/binary.bzl`) to extract out the flags that need stamping (i.e. have a value like `{FOO}`, though I'm open to other suggestions).

We'd then pass these flags, along with the existing `linkstamp` attribute, to a new go program under `go/tools` (maybe `go/tools/stamp_x_defs`?) which would return the list of link flags, having read the workspace status files. Said program would replace [this bit of shell](https://github.com/bazelbuild/rules_go/blob/9e5e4fce5745c7806f6e5af7737b503b47f082e3/go/private/binary.bzl#L176-L182).

(Alternately, I guess we could do the format substitution solely in shell, maybe using `sed`? probably less maintainable, though.)

**Comment by ixdy** [comment]
Pulling `x_defs` out of [`gc_linkopts()`](https://github.com/bazelbuild/rules_go/blob/9e5e4fce5745c7806f6e5af7737b503b47f082e3/go/private/binary.bzl#L102-L103) will probably make the logic simpler, actually.
