### ISSUE TITLE
build tag support?

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#45]
The README says that build tags aren't supported. I see that there's a filter_tags tool in the codebase.

What's there to do to hook these bits up? Or are they already hooked up and just need docs?

**Comment by yugui** [comment]
No. There's no available implementation of build tag support.
`filter_tags` were added to show how to deal with build tags but it is not used.

I am thinking of supporting build tags in BUILD file generator #15. And now @pmbethe09 is checking if it is feasible to opensource Google's internal implementation of the generator.
