### ISSUE TITLE
go_proto_library does not find relative proto

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/rules_go#457]
I have the following `BUILD` content:

    load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

    go_proto_library(
        name = "go_default_library",
        srcs = [
            "digest.proto",
            "directory.proto",
            "nodes.proto",
        ],
    )

which gives me the error:

    Process exited with status 1 [sandboxed].
    nodes.proto: File not found.
    base_proto/directory.proto: Import "nodes.proto" was not found or had errors.

Which is strange, since all of the files exist.

**Comment by abergmeier-dsfishlabs** [comment]
It does work however, if I prefix all imports with: `base_proto/`.

**Comment by rosun82** [comment]
All files should be referred to from repository base directory, which
avoids a lot of confusion down the road.

On Tue, May 16, 2017 at 6:48 PM, Andreas Bergmeier <notifications@github.com

**Comment by pmbethe09** [comment]
This follows the google-style which requires repository root-relative imports for all things to avoid ambiguity.

**Comment by abergmeier-dsfishlabs** [comment]
> This follows the google-style which requires repository root-relative imports for all things to avoid ambiguity.

Is this mentioned somewhere?

**Comment by pmbethe09** [comment]
Internally it is enforced, I guess externally it is hidden in the language guide:
https://developers.google.com/protocol-buffers/docs/proto#importing-definitions
"In general you should set the --proto_path flag to the root of your project and use fully qualified names for all imports."

And without the reasoning -- which is the same from C++ (where we also do fully qualified imports).  If you add an 

import "type.proto"

and there are multiple type.proto in your repo, which one should be selected?  It is purely up to the command-line ordering of your import-path '-I' flags, which is a sad state.
