### ISSUE TITLE
not a root of a repository

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#463]
Hello,

I'm trying to import a subdirectory of a github repository <https://github.com/coreos/etcd/tree/master/clientv3> using importpath, but I got
`failed to fetch com_github_coreos_etcd: 2017/05/19 10:29:29 not a root of a repository: github.com/coreos/etcd/clientv3`

I can import the whole repository, but it requires too many unnecessary dependencies.
Is there any way to import a subdirectory of a repository?

My current rule is

```
new_go_repository(
    name = "com_github_coreos_etcd",
    importpath = "github.com/coreos/etcd/clientv3",
    tag = "v3.1.7",
)
```

Thanks,

**Comment by jayconrod** [comment]
Bazel keeps a close correspondence between repositories and dependencies. There isn't a way to check out a subdirectory of a repository with `git_repository`.. `go_repository` is a custom rule that we built, but we've followed the Bazel conventions with it.

Pulling in some additional dependencies should not hurt your build time. Bazel will not download them if they are not depended on by a build target. I'm not sure whether that will change when Bazel adds nested workspaces, but it's the case now. They do add some boilerplate to your WORKSPACE file though.

One possible fix would be to support the `strip_prefix` attribute in `go_repository` for git and other vcs. Currently this attribute is only supported for HTTP archives.
