### ISSUE TITLE
gazelle does not support "// +build ignore"

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_go#477]
This creates issues for golang.org/x/sys/unix/linux:

https://github.com/golang/sys/blob/master/unix/linux/types.go#L5

ERROR: /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/com_github_oschwald_maxminddb_golang/BUILD.bazel:5:1: no such package '@org_golang_x_sys//windows': failed to generate BUILD files for golang.org/x/sys: 2017/05/25 14:07:05 found packages main (mkall.go) and unix (types.go) in /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/external/org_golang_x_sys/unix/linux

**Comment by jayconrod** [comment]
I'm working on a fix for this as part of #409.

**Comment by hochhaus** [comment]
Thanks. Closing in favor of #409 as that clearly documents this deficiency.
