### ISSUE TITLE
Support vendor dirs not in root of the repo

### ISSUE THREAD

**Issue by tomwilkie** [bazelbuild/rules_go#486]
Gazelle expects the vendor directory to be in the root of the repo.  This isn't always the case.  Would it be possible to pass the vendor directory location?

**Comment by jayconrod** [comment]
Seems like something we should support.

I'm currently wrapping up some improvements for handling build constraints in Gazelle. Once that work is done, I'll be focusing on improving Gazelle's management of dependencies. This will fit into that project.

**Comment by pwittrock** [comment]
Any update on this?  I need to run carefully crafted `sed` scripts after running gazelle.

the equivalent of `go list -f '{{ join .Deps  "\n"}}' | grep` might be able to provide this

**Comment by jayconrod** [comment]
#859 will solve this.

At the moment, Gazelle converts import paths to Bazel deps just by transforming the string without checking whether something is there or not. That prevents us from using vendor directories that aren't at the root of the repository.

#859 is a proposal to index all of the packages in a repository by import path, then choose something appropriate. I'm planning to work on that as soon as we ship support for proto rules (#868). It should be in the major release after the current one we're about to tag, hopefully in a month or so.

**Comment by jayconrod** [comment]
This should be working now.
