### ISSUE TITLE
Trouble using rules_go

### ISSUE THREAD

**Issue by Limdi** [bazelbuild/rules_go#5]
https://github.com/Limdi/testing_go

bazel build //lib:go_default_library
bazel test //lib:lib_test

These give me errors, my workaround is to add @io_bazel_rules_go  to the Labels so the thing uses the @io_bazel_rules_go//go/toolchain  stuff instead of trying to find //go/toolchain in my current WORKSPACE.

I guess the @// syntax was once supposed to mean "stay in this repo to resolve this dependency" or something, but I didnt get it to work that way and I read it only worked while some tools-folder was available as a symlink or something, nevermind about that I suppose.

edit: Maybe that doesnt work either, so how to do this?

**Comment by kchodorow** [comment]
I have a patch to fix this (Bazel should resolve //foo relative to the repository), but it hasn't been committed yet.  Once the patch is in, these rules should work with Bazel HEAD.  Before then, recommended workaround is to either put this who repository in your workspace or use @bazel_tools//tools/build_rules/go.

**Comment by raliste** [comment]
Same here

**Comment by Limdi** [comment]
Works for me, thanks!

**Comment by kchodorow** [comment]
FWIW, using Bazel with this change: https://github.com/bazelbuild/bazel/commit/6f15335deac0c04cfae11623efbe745f11e177ff and the go rules with this change: https://github.com/bazelbuild/rules_go/commit/3dc43724d4d914294d9021a6a809fe74410d28e8 should work now.
