### ISSUE TITLE
gazelle: in test only file package, gazelle generates spurious and bogus go_binary

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#516]
In a directory with only a `foo_test.go` file, gazelle with rules_go f014fed68b1b7b414265e014ce0af276b3c017dc (current HEAD) and buildtools 1f7f3f55d2a8ab8e926fab4811dd866c05f02864 (also current HEAD), generates a spurious and bogus go_binary target.

Run on the directory `testonly` with the file `foo_test.go`, you'll get something like:

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "testonly",
    library = ":",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["foo_test.go"],
)
```

The go_binary doesn't need to exist at all and the library setting for it is, of course, busted, too.

**Comment by jayconrod** [comment]
Reproduced. #509 rewrites most of the rule generating logic in Gazelle. I've checked that it fixes this. You'll need to clear the `go_binary` rule manually though. Sorry about that.

I'll keep this issue open and add a test case to prevent it from happening again.

**Comment by jmhodges** [comment]
Thank you!
