### ISSUE TITLE
gomobile Support

### ISSUE THREAD

**Issue by lingz** [bazelbuild/rules_go#52]
It would be great to have a gomobile_sdk(), target like here:
https://godoc.org/golang.org/x/mobile/cmd/gomobile

Which calls `gomobile bind`, and then we could build go sdks targetting android and iOS directly.

**Comment by robfig** [comment]
I agree with you. I'm afraid we don't have the bandwidth or expertise for this, but we'd be happy to review a PR adding it, assuming it comes with a comprehensive set of automated tests. Since this is such an old issue, I'm going to close, but feel free to reopen if you'd like to take it on. Thanks

**Comment by luangong** [comment]
This issue should be reopened. One of the major selling-points of Bazel is its support for multi-language projects and cross-language dependencies, and the support for gomobile is one such important feature to fulfill Bazel’s promises.

**Comment by luangong** [comment]
FYI: I found a repository at https://github.com/gfanton/rules_gomobile but it was abandoned five years ago.

**Comment by fmeum** [comment]
While `gomobile` support for Bazel sounds very useful, it's not something that would fit into rules_go, neither in terms of scope nor maintainer workload. But I don't see any reason why fully featured `gomobile` rules couldn't be developed as a separate ruleset that interoperates with rules_go via its providers and action API. Maybe start with a fork of that repo and find out what it would take to make it work end to end?
