### ISSUE TITLE
github.com/mattn/go-sqlite3 can't be built as an external dependency

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#526]
go-sqlite3 contains a header file, `sqlite3-binding.h`, which can be included when go-sqlite3 is built as the local repository, but not when it's built as an external dependency.

```
ERROR: /usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/558e6c6fca1bec20ec6f31ee3f9f34ec/external/com_github_mattn_go_sqlite3/BUILD.bazel:5:1: error executing shell command: 'bazel-out/local-fastbuild/bin/external/com_github_mattn_go_sqlite3/bazel-out/local-fastbuild/genfiles/external/com_github_mattn_go_sqlite3/cgo_default_library.cgo_codegen.dir/CGoCodeGenFile.params' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/558e6c6fca1bec20ec6f31ee3f9f34ec/execroot/popular_repos/bazel-out/local-fastbuild/genfiles/external/com_github_mattn_go_sqlite3/cgo_default_library.cgo_codegen.dir/external/com_github_mattn_go_sqlite3/backup.go:10:29: fatal error: sqlite3-binding.h: No such file or directory
 #include <sqlite3-binding.h>
                             ^
compilation terminated.
blaze: Leaving directory `/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/558e6c6fca1bec20ec6f31ee3f9f34ec/execroot/popular_repos/'
Target @com_github_mattn_go_sqlite3//:go_default_library failed to build
```

Note that cgo itself is failing, not the compiler used by `cc_library`. We may need to change the directory where cgo runs or adjust the include paths. This adjustment may also be needed for `cc_library`.

**Comment by jayconrod** [comment]
Spent some time looking into this today. When `go build` invokes cgo, it adds a `-I` argument with the work directory. Adding a similar flag also fixes the cgo action in Go rules.

However, there is another problem after this: the `cc_library` ends up including a copy of the .h file rather than the original. We don't strictly need to make the copy. @ianthehat is working on a simplification for cgo that will eliminate unnecessary copies. I'll look at this again once that simplification has landed.

**Comment by ianthehat** [comment]
Stage one of simplification is in #541, which should be enough for this.

**Comment by cquinn** [comment]
This is exactly the fix I am looking for. When do you think this fix will land in a release?

**Comment by jayconrod** [comment]
@cquinn We don't have concrete release dates, but I expect we'll tag a release next week or the week after when some improvements to generated code handling land in Gazelle.
