### ISSUE TITLE
go_test disallows running tests that run other target's binaries

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#528]
There's [a bazel-discuss thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/axSee5OzX9g/FDDdlmyOCgAJ) about this.

It's not currently possible to write a `go_test` for integration tests that runs binaries from other targets because the way rules_go sets up the directories makes bazel's sandbox kill off those child processes. I think!

In that thread, the `sh_test` runs the sandbox and sets the working directory to `${BLAH}/${test_target_name}.runfiles/${workspace_name}/` while go_test sets it to `${BLAH}/${test_target_name}.runfiles/${workspace_name}/path/to/fancyclient`. The `sh_test` can then can run anything in any of its subdirectories, but, in the `go_test` version, any binaries that are started (by changing or even just `..`'ing the binary's path) are immediately killed.

I'm pretty sure that's because bazel has been told by rules_go that only that fancyclient directory is allowed to run things. I think rules_go does the current thing in order to allow open source (and similar) Go projects to use a local `testdata` directory.

Not sure how the bazel API works well enough to fix this.

**Comment by jayconrod** [comment]
I don't know that much about Bazel sandboxing, but it should be possible to create new processes and run them in different directories within the sandbox. `go_test` doesn't do anything special here. We do change directories at the start of the test for compatibility with `go test`. Our test generator is in `go/tools/generate_test_main.go` if you want to see how it works.

The main purpose of the sandbox is just to make sure tests don't access any files they haven't explicitly declared a `data` dependency on. So as long as the other targets appear in `data`, it should work in theory. That said, I don't think we have enough test coverage of this, and it's quite possible something is broken. Do you have a small repository where we can reproduce and debug this?

An idea to help with debugging: try printing the results of `filepath.Walk` to make sure other files are where you expect they will be. Bazel moves some files (shared libraries at least) to special directories.

**Comment by jmhodges** [comment]
This was PEBCAK. I was canceling a context in the wrong place.
