### ISSUE TITLE
Package io_bazel_rules_go_repository_tools missing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/rules_go#530]
I get the error:

    no such package '@org_golang_x_crypto//ssh': no such package '@io_bazel_rules_go_repository_tools//'

Is it possible, that there is either a, not sufficient error handling or b, a missing dependency between a `new_go_repository` and `io_bazel_rules_go_repository_tools`?

In my WORKSPACE I have:

    git_repository(
        name = "io_bazel_rules_go",
        remote = "https://github.com/bazelbuild/rules_go.git",
        tag = "0.4.4",
    )

    load("@io_bazel_rules_go//go:def.bzl", "go_repositories", "new_go_repository")

    go_repositories()

    new_go_repository(
        name = "org_golang_x_crypto",
        importpath = "golang.org/x/crypto",
        commit = "080743b21912ae11ad9222778a048b795a5aae00",
    )

I have seen multiple errors like this while developing. They appear and disappear. Sadly now this happens on our production server.

**Comment by jayconrod** [comment]
It looks like you're missing the `load` statement from the WORKSPACE file you posted.

```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_repositories", "new_go_repository")
```

You should have gotten a different error because that, so maybe it's a copy-paste mistake. Could you post minimal WORKSPACE and BUILD files that reproduce the problem?
