### ISSUE TITLE
buildmode shared

### ISSUE THREAD

**Issue by lingz** [bazelbuild/rules_go#54]
I saw that using -buildmode=c-shared is currently unsupported here:
https://github.com/bazelbuild/rules_go/pull/10

Any plans to add this or ideas of how difficult it would be to add?

**Comment by yugui** [comment]
It was discussed at https://groups.google.com/d/msg/bazel-dev/N_cS_OJocZI/-6vvvLUkAwAJ
But currently we don't have a good generic solution.

It turned out that my original proposal did not generally work fine because it instantiates go runtime for each `c-shared` library.  So if you link hundred number of such `c-shared` libraries into your binary, the binary will have hundred number of garbage collectors and their corresponding threads.
To avoid this issue, we need a way to provide `CcLinkParamProvider` from Skylark to native `CCLibrary`.

I plan to revisit this feature once we get a good support by Bazel.

**Comment by lingz** [comment]
Ok I look forward to seeing how it goes. Are you requesting new features from Bazel before this can be implemented well?

**Comment by ajbouh** [comment]
Any progress on support for -buildmode=c-shared?

**Comment by ianthehat** [comment]
I was planning to add support for all the buildmode options following either the "static" or "race" patterns depending on if they are main or package level choices.
This means c-shared would become an outputgroup choice on go_binary.
All the supporting work was done and proven implementing those two modes, it's really easy to add the others, the only thing stopping me is I have no use case, no examples, and no way to test, and other things seemed more urgent.
If you need this, and are willing to test it for me or give me a github repo to work on, I can add it very quickly.

**Comment by ajbouh** [comment]
I have hacked something together with a shell script to unblock myself, but I'd really like to get it working the "right" way.

I can certainly help you test this, though I should point out that I also need to use a shell script for swig support. So there's a chance that this is a larger bit of work than just -buildmode=shared support... Thoughts?

**Comment by ajbouh** [comment]
@ianthehat Dug into it more and turns out only two things need to be done for c-shared outputs. A main.go file and gc_linkopts. :)

```
go_binary(
    name="example.so",
    deps=[
      ":example", # a go_library
    ],
    srcs=[
      "main.go",
    ],
    gc_linkopts=["-buildmode=c-shared"],
    visibility = ["//visibility:public"],
)
```

**Comment by ajbouh** [comment]
Seems like there's more sorcery required to get this working linux. The above code works on Darwin, but on Linux I'm seeing:

```
/usr/bin/ld: /tmp/go-link-222028116/go.o: relocation R_X86_64_TPOFF32 against `runtime.tlsg' can not be used when making a shared object; recompile with -fPIC
/tmp/go-link-222028116/go.o: error adding symbols: Bad value
```

I'm having trouble deciphering _what_ needs to be compiled with -fPIC. @ianthehat can you help me interpret this?

**Comment by ajbouh** [comment]
Some additional research pulled up https://github.com/golang/go/issues/9652, where the fix, https://github.com/golang/go/commit/09d9520be931a32a8ab18990a5684550e3f4b6cb added support for the -shared flag to the 6l asm tool. This makes me wonder if it's the stdlib that needs to be compiled with the -shared option... does that sound right?

**Comment by ianthehat** [comment]
It could be, I know next to nothing about shared mode. You could test your theory by looking at where we cross compile the standard library and trying to build it in shared mode there.
If that is the problem, it's probably going to have to wait for the work I am doing to compile the standard library on demand for a real solution though.

**Comment by ajbouh** [comment]
@ianthehat I've been keeping an eye on your standard library cross compilation work, it seems like things are getting increasingly well organized and generally more understandable. 👍 

Can you point me at where the ahead of time standard library compilation is happening? I'd be happy to work from (and maintain) a fork of rules_go until the on demand work is live.

**Comment by ianthehat** [comment]
You want
https://github.com/bazelbuild/rules_go/blob/master/go/private/toolchain.bzl#L54

**Comment by jayconrod** [comment]
Closing old issues. This is supported now with `linkmode = "c-shared"` in `go_binary`.

**Comment by SvenKratzKodiak** [comment]
does linkmode="c-shared" also generate a header file? I'm not seeing a header corresponding to the library output in the bazel-bin.
