### ISSUE TITLE
Possible build reproducibility error

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#543]
This looks like a possible build reproducibility error. Sorry I don't have time to do a full investigation, but here's what happened:

Medium size Go project, using Bazel 0.5.1 on macOS Sierra 10.12.5.
Before: rules_go version 0.4.4, Go version 1.8.1
Changed rules_go version to 0.5.0 and Go to version 1.8.3 simultaneously.
Ran `bazel build` and got a panic in the Go linker:

```
ERROR: foor/bar/baz/sync/BUILD.bazel:10:1: null failed: link failed: error executing command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/link external/go1_8_3_darwin_amd64/bin/go -- -L . -L bazel-out/darwin_x86_64-fastbuild/bin/apps/api-api/beta/ -L ... (remaining 99 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/darwin_x86_64-fastbuild/bin/foo/bar/baz/sync/sync.a(_go_.o): object is [darwin amd64 go1.8.1 X:framepointer] expected [darwin amd64 go1.8.3 ]
sync.(*Mutex).Lock: call to external function
sync.(*Cond).Signal: call to external function
sync.init: call to external function
sync.(*Once).Do: call to external function
sync.(*Mutex).Unlock: call to external function
sync.(*Pool).Put: call to external function
sync.(*WaitGroup).Wait: call to external function
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
cmd/link/internal/ld.decodetypePtrdata(0x12fbc60, 0xc420d4ca18, 0xc42093c87f)
    /usr/local/go/src/cmd/link/internal/ld/decodesym.go:83 +0x9e
cmd/link/internal/ld.(*GCProg).AddSym(0xc428947790, 0xc42198b1c8)
    /usr/local/go/src/cmd/link/internal/ld/data.go:1229 +0x76
cmd/link/internal/ld.(*Link).dodata(0xc420088340)
    /usr/local/go/src/cmd/link/internal/ld/data.go:1522 +0x108d
cmd/link/internal/ld.Main()
    /usr/local/go/src/cmd/link/internal/ld/main.go:205 +0x927
main.main()
    /usr/local/go/src/cmd/link/main.go:58 +0xdb
2017/06/15 11:13:59 error running linker: exit status 1
INFO: Elapsed time: 156.437s, Critical Path: 23.66s
make: *** [build] Error 1
```

The "object is [darwin amd64 go1.8.1 X:framepointer] expected [darwin amd64 go1.8.3 ]" message implies that a library wasn't recompiled when it should have been, maybe there's a missing dependency on the Go toolchain somewhere.

After a `bazel clean --expunge`, a rebuild completes successfully (as expected).

**Comment by ianthehat** [comment]
Yes, that is exactly the error I would expect if you tried to consume a .a built with one version of the compiler with a different version. This may be a temporary condition as the platform stuff is using some fairly odd and temporary hacks at the bottom level while we wait for the final version of platform support to ship in bazel, I am still surprised it happens though.

**Comment by jayconrod** [comment]
This is troubling. Hopefully this is a temporary condition that will get resolved soon as @ianthehat said. If not, we'll follow up with the core Bazel team and figure out what's going on.

**Comment by ianthehat** [comment]
We have not seen this again, so i am going to close this.
