### ISSUE TITLE
Gazelle generates incorrect rules for platform-specific packages

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#544]
The package `github.com/hpcloud/tail/winfile` is sadly rather pathological. It contains a single source file with the build tag `// build +windows`: https://github.com/hpcloud/tail/blob/master/winfile/winfile.go.

Gazelle generates the following `BUILD.bazel` file:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:windows_amd64": [
            "winfile.go",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)
```

On all platforms except Windows, `srcs` is empty and Bazel complains about this, for example:

```
$ bazel build //vendor/github.com/hpcloud/tail/winfile:go_default_library
ERROR: /Users/username/src/foo/vendor/github.com/hpcloud/tail/winfile/BUILD.bazel:3:1: in go_library rule //vendor/github.com/hpcloud/tail/winfile:go_default_library:
Traceback (most recent call last):
	File "/Users/username/src/foo/vendor/github.com/hpcloud/tail/winfile/BUILD.bazel", line 3
		go_library(name = 'go_default_library')
	File "/private/var/tmp/_bazel_tom.payne/426382695a0eb57a7825dd83e14df9cd/external/io_bazel_rules_go/go/private/library.bzl", line 100, in _go_library_impl
		emit_library_actions(ctx, sources = depset(ctx.files.sr...), <3 more arguments>)
	File "/private/var/tmp/_bazel_tom.payne/426382695a0eb57a7825dd83e14df9cd/external/io_bazel_rules_go/go/private/library.bzl", line 39, in emit_library_actions
		fail("may not be empty", "srcs")
attribute srcs: may not be empty.
ERROR: Analysis of target '//vendor/github.com/hpcloud/tail/winfile:go_default_library' failed; build aborted.
```

I'm not sure what rules_go can reasonably do about libraries that have no sources on some platforms. Feel free to close this issue as WONTFIX.

**Comment by ianthehat** [comment]
I think gazelle is doing exactly the right thing, and what we need is a way to allow empty source lists in the go_library rule. It's not even that difficult, we could just manufacture a fake empty.go when we see it happen to keep the rest of the system happy, all we need is a way to generate an acceptable package line.

**Comment by jayconrod** [comment]
Thanks for reporting, but this is working as intended. `go build` will refuse to build a package where all sources are filtered out, and Go+Bazel will do the same.

There are a couple ways to work around this. If you have a platform-agnostic package that depends on this package (maybe through an import in a platform-specific source file), make sure the dependency is also inside a `select` expression with the same condition. Gazelle should do this for you automatically.

If you're building or testing everything in a repository, (e.g., `bazel test //...`), you can exclude platform-specific targets by prefixing them with `-`. You'll have to add a `--` argument earlier so Bazel doesn't interpret these arguments as options.

```
bazel build -- @com_github_hpcloud_tail//... -@com_github_hpcloud_tail//winfile:go_default_library```
```

[popular_repos.bash](https://github.com/bazelbuild/rules_go/blob/master/tests/popular_repos/popular_repos.bash) has a larger example of this if you're curious. There are several tests in the `golang.org/x` libraries that we need to exclude.

Another mechanism is to add `tags = ["manual"]` to the rules. Bazel will not build targets with the `manual` tag if they would be selected with wildcards like `//...`.

**Comment by twpayne** [comment]
Thanks for the explanation, that all makes sense. For info I'm using `bazel build -- //... -//vendor/...` so Bazel doesn't build anything in `vendor` that is not explicitly needed. This is a rather large sledgehammer to work around all the problems with vendor'ed `golang.org/x` packages.
