### ISSUE TITLE
Allow cc_binary to depend on cgo_library

### ISSUE THREAD

**Issue by lingz** [bazelbuild/rules_go#55]
Go allows the export of symbols, so it would be interesting to see its symbols exported and used inside a C binary, built all in bazel. Currently if I depend on a cgo_library() with a cc_binary, I just get the following:

```
in deps attribute of cc_binary rule //lib/go:testmain: go_library rule '//lib/go:test' is misplaced here (expected cc_inc_library, cc_library or objc_library)
```

**Comment by yugui** [comment]
#54 is the reason why it fails.
Can I close this issue as a duplicate?

**Comment by lingz** [comment]
Yeah okay.
