### ISSUE TITLE
Gazelle should ignore cgo_library if platform doesn't require cgo

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_go#551]
Gazelle generate build files for cgo fail when a platform doesn't require cgo. The generate build file effectively creates `cgo_library(srcs=[])` for the platform that doesn't have any c. Example is the build file generated for https://github.com/google/certificate-transparency-go/tree/master/x509 which fails on linux with:

```.../vendor/github.com/google/certificate-transparency/go/x509/BUILD.bazel:3:1: in srcs attribute of _cgo_codegen_rule rule //vendor/github.com/google/certificate-transparency/go/x509:cgo_default_library.cgo_codegen: '//vendor/github.com/google/certificate-transparency/go/x509:cgo_default_library.cgo_select_go_srcs' does not produce any _cgo_codegen_rule srcs files (expected .go, .s, .S or .h). Since this rule was created by the macro 'cgo_library', the error might have been caused by the macro implementation in /root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/io_bazel_rules_go/go/private/cgo.bzl:599:14.```

**Comment by jayconrod** [comment]
Thanks for reporting! Unfortunately, this is a known problem (though I couldn't find another open issue tracking it). @ianthehat is working on a fix that will consolidate cgo functionality into `go_library`. See #359 for the high-level proposal.

**Comment by ains** [comment]
Hey @ianthehat @jayconrod is there a workaround for this issue or ETA on #359 - issue also affects https://github.com/vishvananda/netlink so we can't use the latest rules_go in our builds.

**Comment by ains** [comment]
well, in terms of workarounds this worked https://github.com/improbable-io/netlink/commit/e3ff332ef8f88c9cbcc17985b7510ee8cd5dc88e

but it'll be nice to get this working for the upstream

**Comment by jayconrod** [comment]
@ianthehat Is the `cgo_library` unification work blocked on anything in Bazel? I know it needs some support from the Gazelle side. I can add that behind an experimental flag until the rules work is done.

**Comment by ianthehat** [comment]
Because it's a major breaking change to the api of the rules_go, I was trying to make sure we do all the breaking changes in a single version switch to minimise the pain. I am not sure that is going to be viable though (proto has issues with the well known repositories, gazelle flat mode may change the api and is not going to be ready any time soon, and the race/asan etc modes are not going to be done straight away either)
Also the new API depends on the full providers system, which only works in the very latest bazel.

**Comment by ianthehat** [comment]
The new cgo handling is in place, and should work.
Gazelle is being updated now to generate the new form, and then this problem should be solved.

**Comment by ianthehat** [comment]
This should all be fixed now, please re-open if there are still any issues.
