### ISSUE TITLE
gazelle drops explicitly added genrules from srcs

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#555]
I have a genrule target `:some_generated_go` that creates a .go file for use in a test that I explicitly added to a `go_test`'s `srcs`. Gazelle, when run on that Go package, removes that `:some_generate_go` from its `srcs` and has to be manually added back afterwards.

This is likely to be a general target look up thing to be fixed, not just genrules alone.

**Comment by pmbethe09** [comment]
What if you put '# keep' after the genrule in srcs?

**Comment by jmhodges** [comment]
Ah, I hadn't known about that feature. Yep, that works.

**Comment by pmbethe09** [comment]
yeah, I added that and then @jayconrod recently made it better.

What I would really like is a rule-level 'ignore' for packages like 
https://github.com/bazelbuild/buildtools/blob/master/build/BUILD.bazel#L21
where we have checked in generated files to satisfy the 'go build' community, but at gazelle time it would be nice to tell gazelle to '# keep' the generated file and '# ignore parse.y.go'

**Comment by jmhodges** [comment]
Ooo.

Also, thanks for the help!

**Comment by jayconrod** [comment]
These are both great ideas. I'm starting to work on a design to improve Gazelle's handling of generated code, and I'll make sure to incorporate these.
