### ISSUE TITLE
Gazelle: incorporate generated .go sources into rules

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#557]
A key strength of Bazel is its ability to handle generated code. Gazelle should make it easy to take advantage of this. If Gazelle can determine that an existing rule generates .go files, it should incorporate those files into `go_library` and `go_test` rules in the same package.

```bzl
genrule(
    name = "gen_parser",
    srcs = ["gopher.y"],
    outs = ["gopher.go"],
    cmd = ["go tool yacc -o gopher.go -p parser gopher.y"],
)

# gazelle could generate this rule
go_library(
    name = "go_default_library",
    srcs = ["gopher.go"],
)
```

### Detecting generated code

Gazelle generates rules by scanning source files in a directory. Gazelle could use existing BUILD files as another source of information. It should look for files with .go suffixes in `out` and `outs` attributes of top-level rules. This would cover `genrule` and `go_embed_data` when it's supported (#304). It would also cover `_go_proto_library_gen` if we ever made that a standalone public rule.

There are some limitations to this approach. We won't be able to detect .go files created implicitly by rules or inside macros unless we run `bazel query`, which would be very slow, especially if it needs to download additional dependencies. We won't be able to detect sources created with `go generate`, since generate comments don't list any inputs, outputs, or dependencies.

### Incorporating generated code

Gazelle uses `packages.Package` to represent the sources and dependencies for a package. Gazelle should add detected files to `Package` before rules are generated from it. Generated files should be treated as if they have no imports or build tags, since we cannot infer those without actually generating them. We should respect filename suffixes though: `foo_linux_test.go` should be treated as a Linux-specific test file.

### Excluding existing files

Because `go generate` is not part of `go build`, it's common for people to check in generated files so that `go get` Just Works. This is not necessary with Bazel, but we need to avoid any problems caused by this.

If a rule generates a file with the same name as an existing file, Bazel will use the generated file at build time as if the existing file didn't exist. Gazelle should probably incorporate imports and build tags from the existing file. This is unclear, since the file won't be seen at build time, but the programmer's intent is most likely for the generated and existing files to be equivalent.

If an existing file should not be included in the build because a rule produces a substitute file with a different name, it should be possible to prevent Gazelle from adding it. See [this comment by @pmbethe09](https://github.com/bazelbuild/rules_go/issues/555#issuecomment-309231103) for why this is needed. This could be accomplished by supporting rule-level `# keep` comments or `# gazelle:exclude <file>` comments in `srcs` lists. When a file is excluded, Gazelle should not add any dependencies for imports from that file.

**Comment by jayconrod** [comment]
cc @jmhodges @pmbethe09 @ianthehat

**Comment by pmbethe09** [comment]
Overall, I really like the plan for gazelle to be aware of generated files

"unless we run bazel query, which would be very slow" - yes for the first time for a given repo, but not any additional times.  I would suggest using bazel query as clean and simple.
"it's common for people to check in generated files" - this is IMHO the worst feature of the `go build` environment and a place where bazel really gets it right.
"but the programmer's intent is most likely for the generated and existing files to be equivalent." - I would agree, maybe gazelle can auto-generate a genfile_check_test see https://github.com/bazelbuild/buildtools/blob/master/build/BUILD.bazel#L12

**Comment by jayconrod** [comment]
@pmbethe09 `bazel query` can be slow because it's not aware of configuration. We're not sure how this will interact with toolchains. I'm concerned there are situations where it will download every possible SDK because of this. @ianthehat has been working on converting our Bash tests into regular Bazel tests, and he's seeing this happen on Jenkins builds because the Jenkins setup uses `bazel query` to find tests instead of just running `bazel test //...`. This  only seems to happen in rules_go for now since the toolchains are declared there, but we're not sure how toolchains will change this when the feature lands.

Automating or simplifying `genfile_check_test` is not a bad idea. I think people will still have to manually write `genrule`s to replace `go generate`. Maybe we could just provide a replacement for `genrule` that compares the outputs to existing files in a single rule. Or perhaps Bazel could add that functionality to `genrule` itself, since it seems pretty general.
