### ISSUE TITLE
Protocol Buffer Generation

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#56]
I've been working on rules for protobuf generation.  The go support is largely based on @yugui   https://github.com/grpc-ecosystem/grpc-gateway/blob/e958c5db30f7b99e1870db42dd5624322f112d0c/grpc-gateway.bzl and rules_go.

Could someone (@yugui?) review this and offer suggestions or contributions to get the hello world example to run? I have the protobuf generation working but I'm stuck on either a missing / import or incorrect package mapping to get it to compile.  Changes are on the "go" branch.

Disclaimer: I'm primarily a java and js dev, golang is relatively new for me.

```
$ git clone https://github.com/pubref/rules_protobuf
$ cd rules_protobuf
$ git checkout go
$ bazel build examples/helloworld/go/client
```

@see [rules_protobuf go branch](https://github.com/pubref/rules_protobuf/tree/go)
@see [//bzl:go.bzl](https://github.com/pubref/rules_protobuf/blob/go/bzl/go.bzl)
@see [//bzl:protoc.bzl](https://github.com/pubref/rules_protobuf/blob/go/bzl/protoc.bzl)

Thanks!
Paul

**Comment by pcj** [comment]
Continued on https://github.com/pubref/rules_protobuf/issues/1

**Comment by pcj** [comment]
go_proto_library is now supported by rules_protobuf with the help of rules_go, but there are some limitations, see https://github.com/pubref/rules_protobuf/issues/4

**Comment by yugui** [comment]
@pcj I'm sorry for being late to review the go branch.  In general, it looks good to me.
Thank you for your great work!
