### ISSUE TITLE
Gazelle doesn't use workspace Go version for build tags

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#563]
Gazelle seems to use the local-installed Go version, not the version of Go specified in the project's `WORKSPACE` file, when determining which source files to include in the generated `BUILD` file. This causes the generated`BUILD` files to have the wrong `srcs`.

We saw:
- A developer has Go 1.7.4 installed on his machine. Gazelle is built and installed with this version.
- The `WORKSPACE` file specifies `go_repositories(go_version="1.8.3")`.
- A package (e.g. https://github.com/gorilla/websocket) has different code for build tags `go1.8` and `!go1.8` ([`client_clone.go`](https://github.com/gorilla/websocket/blob/master/client_clone.go#L5) and [`client_clone_legacy.go`](https://github.com/gorilla/websocket/blob/master/client_clone_legacy.go#L5)).
- Gazelle generates a `BUILD.bazel` file for Go 1.7.4, not Go 1.8, i.e. it includes `client_clone_legacy.go` in the list of `srcs`.
- Since `client_clone_legacy.go` contains `// +build !go1.8` the Go 1.8 compiler, when invoked by Bazel, ignores the file and the build breaks (neither `client_clone.go` nor `client_clone_legacy.go` get included).

Ideally Gazelle would somehow extract the Go version from `WORKSPACE` but this might be difficult: if no explicit version is specified, the Go version will come from whatever the default version happens to be for the tag/commit of `rules_go` that the `WORKSPACE` imports.

This case - developer's locally-installed Go being out-of-sync with the Go version in `WORKSPACE` - is a fairly strange one so feel free to close this as "WONTFIX".

**Comment by jayconrod** [comment]
Thanks for reporting this. It's a subtle issue, and it's one we'd like to address.

I've filed issue #564 to make it easier to run a Gazelle binary build by Bazel from the local workspace. That would reduce the risk of running a different version of Gazelle.

In any case, it doesn't seem like Gazelle's behavior is what's desired: it shouldn't matter what version of Go you built Gazelle with. There are a couple alternatives. 

The short term option is for Gazelle to ignore release tags and the let Bazel sort them out at compile time. This means you'd have a `go_library` rule that includes both client_clone.go and client_clone_legacy.go in `srcs` (and their imports in `deps`), but only one would really get built.

The long term option is to include the Go version in the platform labels used by `select` and include those sources conditionally. There are a couple things blocking this, but we'll probably go this route once platform support in Bazel is more mature.

I'll implement the short term option for now.
