### ISSUE TITLE
document go_proto_library's load statement

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#574]
Folks (like me) always try to load go_proto_library from the usual `@io_bazel_rules_go//go:def.bzl` instead of the correct `@io_bazel_rules_go//proto:go_proto_library.bzl`. The README doesn't mention that correct location of go_proto_library except in a small parenthetical.

**Comment by ianthehat** [comment]
We need complete proto documentation now the rules are mostly clean and working.

**Comment by jayconrod** [comment]
Closing this. `go_proto_library` is documented at https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst, with a couple short examples. Need more examples and tests though.
