### ISSUE TITLE
feature request: when test sharing will be done?

### ISSUE THREAD

**Issue by zhexuany** [bazelbuild/rules_go#575]
We plan use `bazel` as our automate building tool. But there is one problem: 
we use `init` to solve circular dependency in our project. But `test sharing` is not implemented yet, we have to do a workaround about this. I am wondering when will `test sharing` be added into codebase?

**Comment by jayconrod** [comment]
I'm not sure what you mean by test sharing. Could you elaborate? If you have a small example or a pointer to a github repo, that would be helpful.
