### ISSUE TITLE
Failure building github.com/mattn/go-sqlite3

### ISSUE THREAD

**Issue by cquinn** [bazelbuild/rules_go#578]
Compilation fails while building this SQLite library for Go, which is transitively needed by Gorma and Goa. This is using rules_go@dd999cefc15bbfd4f74ade6efb45bc6118309bf4 , and a gazelle I built from the same pull.

```
go_repository(
    name = "com_github_mattn_go_sqlite3",
    importpath = "github.com/mattn/go-sqlite3",
    commit = "afe454f6220b3972691678af2c5579781563183f",
)
```
The error that I see is in the cgo_library build:
```
ERROR: <...>/external/com_github_mattn_go_sqlite3/BUILD.bazel:5:1: C++ compilation of rule '@com_github_mattn_go_sqlite3//:cgo_default_library.cgo_c_lib' failed: gcc failed: error executing command tools/cpp/gcc-4.8/bin/gcc -nostdinc -isystem external/gcc_4_8/usr/include -isystem external/gcc_4_8/usr/include/x86_64-linux-gnu -isystem external/gcc_4_8/usr/lib/gcc/x86_64-linux-gnu/4.8/include ... (remaining 56 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
<...>/execroot/driving/external/com_github_mattn_go_sqlite3/sqlite3.go:62:1: error: '_sqlite3_exec' defined but not used [-Werror=unused-function]
 _sqlite3_exec(sqlite3* db, const char* pcmd, long long* rowid, long long* changes)
 ^
cc1: all warnings being treated as errors
```
Is there a possible workaround?

**Comment by jayconrod** [comment]
I've seen that warning come up before, but I haven't seen it treated as an error. Could you tell us a bit more about your build environment, especially your C compiler? Do you have `-Werror` set anywhere in your environment that your C compiler might pick it up by default?

As a workaround, you can generate a BUILD.bazel file for that repository ahead of time and customize it.

* git clone the go-sqlite3 repository and cd into it. If it's already in your `GOPATH`, you can just use that.
* Create an empty WORKSPACE file. Gazelle expects this.
* Run `gazelle -go_prefix=github.com/mattn/go-sqlite3`. It should produce a BUILD.bazel file.
* Copy the file into your own repo with a different name (`go-sqlite3.bazel` perhaps).
* Add `-Wno-error` to the `copts` attribute of the `cgo_library`. Delete the `go_test` rule at the bottom.
* In your WORKSPACE file, replace the rule for `com_github_mattn_gosqlite3` with one that looks like this:

```
new_git_repository(
    name = "com_github_mattn_go_sqlite3",
    remote = "https://github.com/mattn/go-sqlite3",
    commit = "afe454f6220b3972691678af2c5579781563183f",
    build_file = "sqlite3.bazel",
)
```

**Comment by cquinn** [comment]
Ah, yes, our gcc environment has some particular settings, including -Werror. 

I will follow your suggestion and create a custom BUILD file for it. I think I'll need that to work around some other oddities I am seeing after hacking out the -Werror for testing.

Thanks a ton, and sorry to assume this was a Bazel/rules_go problem.

**Comment by jayconrod** [comment]
No problem, thanks for reporting.

In the future, this workaround should be simpler and more standard. We're considering deprecating `go_repository` and adding a "flat mode" to Gazelle so it will generate a single BUILD.bazel file for rules in the entire repository. We'll need to figure out how to make that convenient and usable, but it will be easier to customize BUILD.bazel files for external repositories.
