### ISSUE TITLE
Gazelle and visibility

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#583]
Gazelle needs to attempt to match user intent when merging build files with respect to visibility attributes.
Running it on kubernetes currently adds public visibility to almost all the rules.

**Comment by jayconrod** [comment]
For clarification, kubernetes has `package(default_visibility = ["//visibility:public"])` in most (all?) of its BUILD files. Gazelle should not add visibility attributes to new or existing rules when a default visibility declaration is present. We shouldn't remove visibility attributes in this case either.
