### ISSUE TITLE
Gazelle monorepo support (importpath)

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#597]
As mentioned in https://github.com/bazelbuild/rules_go/issues/459 at Improbable we have a monorepo such that the import path "improbable.io/server/foo" in go code would live under the workspace at directory "go/src/improbable.io/server/foo".

Now that https://github.com/bazelbuild/rules_go/pull/458 has landed we're almost ready to rebase our branch of rules_go and use the monorepo work from upstream, but we need to update Gazelle to support generating build files for our repository (it still currently ignores the importpath attribute and incorrectly generates deps w/o our code for the prefix_root attribute https://github.com/improbable-io/rules_go/commit/6fd942ade995888d18c85ca6836d577327d3590f#diff-f39898632343c613a749bbca1d278bb1R42

I propose adding a feature to Gazelle similar to the importmap used by the protoc compiler, where the user can pass a flag specifying tuples of (go_import_path_prefix, workspace_relative_path).

We could specify, ("improbable.io", "go/src/improbable.io")  causing gazelle to generate deps with the workspace prefix e.g "improbable.io/server/foo" -> "//go/src/improbable.io/server/foo" and the go_library rule would have the importpath of "improbable.io/server/foo" (package_path - go_import_path_prefix).

If you guys agree this would be a feature worth having upstream or if you have any alternative suggestions let me know and I can get a patch prepared.

**Comment by ianthehat** [comment]
One thing we have discussed is making gazelle add the importpath declaration automatically if the canonical import path is set in the go files.
This would allow you to not have to maintain the importpath->dir mapping from outside the source files, which I think would be much easier and cleaner. I am undecided about what gazelle would/should do if you specify the canonical import path in a root package but not in children though, should it infer the importpath from the root, that would work for things laid out how go normally expects, but it's extra magic. The downside of not doing that is that you have to specify the canonical import path in every package, which might be a good thing to do anyway.
The other open problem is then that we generate correct library rules, but we still need to know how to convert from import path to label when generating the deps. To do this right we need to change to a two pass system where we collect up all the libraries first, and then go back through setting deps once we have a full mapping of importpath->label. We need to do this anyway for all sorts of reasons, but it's another thing that is a pre-requisite for this approach to work.

**Comment by jayconrod** [comment]
@ains I like this idea, but I'd like to avoid having to pass too many arguments to Gazelle. What if instead, Gazelle recognized a directive at the root of each subtree? For example, in `go/src/improbable.io/BUILD.bazel`, you could write:

```bzl
# gazelle:prefix improbable.io
```

Then Gazelle would generate `importpath` attributes for rules in that subtree. Would that work? Might be easier to maintain.

As @ianthehat pointed out, there are some challenges in resolving import paths to labels, but it's work that's planned already.

**Comment by ains** [comment]
@jayconrod that does seem cleaner, i'll try out an implementation of it this week and see how it works for us in practice

**Comment by jayconrod** [comment]
Closing old Gazelle issues. Gazelle resolves dependencies using `importpath` now, but we don't support prefixes yet that aren't at the repository root. This should be covered in bazelbuild/bazel-gazelle#6.

**Comment by skyl** [comment]
For anyone finding this on Google, the solution seems to be to use a comment in the root BUILD file and a comment in the BUILD file at `$GOPATH/src`. So, for instance, I have a BUILD file in the root that looks like:

```
# gazelle:prefix

load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
)
```

And then at `go/src/BUILD` I have simply:

```
# gazelle:prefix
```
