### ISSUE TITLE
go_test subst wrong location

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/rules_go#605]
I have a `go_test`:

    def create_test():
        native.genrule(
            outs = ["%s.param" % name],
            ...

        go_test(
            name = name,
            srcs = [
                "@my_repo//test/:test.go",
            ],
            args = [
                "$(location %s.param)".format(name),
            ],
            data = [
                "%s.param" % name,
            ],

The test itself *never* can open the param file:

    open gof3m_assets/source/texture_test_in_assets/asteroids/plain/textures_dir.params: no such file or directory

So I added a `local` tag and wrote cwd:

    /user/.cache/bazel/_bazel_user/384827ac61ea21f490af9da32681de43/execroot/tools/bazel-out/local-py3-fastbuild/bin/gof3m_assets/source/texture_test_in_assets/asteroids/plain/textures_dir.runfiles/com_dsfishlabs_tools/gof3m_assets/source

in contrast to the arg:

    gof3m_assets/source/texture_test_in_assets/asteroids/plain/textures_dir.params

So one of these is wrong. Since `//gof3m_assets/source` is the current package, I would say the latter. Seems like location is not substituted according to the current package.

**Comment by jayconrod** [comment]
`go_test` binaries will change to their package directory before calling `TestMain` or running test cases. This is intended to be consistent with "go test".

The path substituted for `$(location)` is relative to the test's runfiles directory. Maybe one of the functions in `github.com/bazelbuild/rules_go/blob/master/go/tools/bazel` would help locate the file? In this example though, it seems like you could just omit the pass `["%s.param" % name]` as `args`.

**Comment by abergmeier-dsfishlabs** [comment]
>  In this example though, it seems like you could just omit the pass ["%s.param" % name] as args.

Thanks, that indeed made it work.
