### ISSUE TITLE
gazelle infers wrong external from import path 

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#606]
I depend on the go code in rules_webtesting to do some testing. It's import path in Go is `	"github.com/bazelbuild/rules_webtesting/go/webtest"`.

However, it's bazel external name that rules_webtesting sets as its workspace (and so the repository is named in my WORKSPACE) is `io_bazel_rules_webtesting`.

Gazelle, when run on this code, will add or change the go_test's `deps` to depend on `"@com_github_bazelbuild_rules_webtesting//go/webtest:go_default_library"` instead of the correct `@io_bazel_rules_webtesting//go/webtest:go_default_library`. If the correct dep was already present, it will be rewritten to the incorrect one.

**Comment by jmhodges** [comment]
(I tested this with the new `bazel run :gazelle` trick using the new gazelle skylark function)

**Comment by jmhodges** [comment]
Is there an import to label map now? Saw some changes that seem to be related

**Comment by jayconrod** [comment]
Not yet, but soon. #859 is a proposal for this.

**Comment by jayconrod** [comment]
Closing old Gazelle issues. I've migrated this to bazelbuild/bazel-gazelle#12 and bazelbuild/bazel-gazelle#13. Let me know if I've left anything out.
