### ISSUE TITLE
Relationship between this and 'official' go implementation in bazel?

### ISSUE THREAD

**Issue by lingz** [bazelbuild/rules_go#61]
Could you clarify what the difference between using your package remotely, vs. using the built in go_rules from bazel like:

```
load("@bazel_tools//tools/build_rules/go:def.bzl", "go_binary", "cgo_library", "go_library")
```

**Comment by pmbethe09** [comment]
The built_in go_rules were forked into this repo.  If you look in
https://github.com/bazelbuild/bazel/tree/master/tools/build_rules

you will see that there is not longer a 'go' directory.
