### ISSUE TITLE
Gazelle should add load statement at the top of a file

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#611]
When Gazelle merges a `load` statement in an existing file, it checks for another `load` statement from the same file and attempts to merge with it. If no compatible `load` statement is found, Gazelle will append the the `load` to the end of the file. For example, say we have this existing file:

```
go_library(
    name = "go_default_library",
    srcs = ["lib.go"],
)
```

Gazelle will add the `load` statement after existing rules.

```
go_library(
    name = "go_default_library",
    srcs = ["foo.go"],
    visibility = ["//visibility:public"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_prefix")

go_prefix("github.com/jr_hacker/example")
```

This seems wrong. `load` statements should be at the top of a file.

**Comment by ianthehat** [comment]
Yes. There was even a discussion about whether the BUILD language should be changed to require load statements being at the top of BUILD files in the skylark discussions. It's clearly intended, even if not enforced right now.
