### ISSUE TITLE
gazelle incorrectly (?) includes generated files in srcs

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#618]
This change of behaviour may or may not be a bug. I'm not sure. `git bisect` reveals that the changed was introduced in commit d463fe26ef1da1e82389e82b474f5890d543c8f5.

Consider the following `BUILD.bazel` file, which includes a source file `auto.go` generated with a `genrule`:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_prefix")

go_prefix("github.com/twpayne/gazelle-test")

go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
        ":gen-auto.go",  # keep
    ],
    visibility = ["//visibility:private"],
)

go_binary(
    name = "gazelle-test",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

genrule(
    name = "gen-auto.go",
    outs = ["auto.go"],
    cmd = "echo package main > $@",
)
```

Gazelle prior to commit d463fe26ef1da1e82389e82b474f5890d543c8f5 re-generates this file as-is. Gazelle is run with:

```sh
$ gazelle -build_file_name=BUILD.bazel -go_prefix=github.com/twpayne/gazelle-test -mode=fix .
```

Running the same command with Gazelle at commit d463fe26ef1da1e82389e82b474f5890d543c8f5 and later adds `auto.go` to the `go_library`'s `srcs` attribute. The resulting diff is:

```patch
diff --git a/BUILD.bazel b/BUILD.bazel
index 4098238..c2549fe 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -5,6 +5,7 @@ go_prefix("github.com/twpayne/gazelle-test")
 go_library(
     name = "go_default_library",
     srcs = [
+        "auto.go",
         "main.go",
         ":gen-auto.go",  # keep
     ],
```

The full files need to reproduce this are in https://gist.github.com/twpayne/1d1ce73bdedd9b6fad8e9dc41c7dc6da. This files should be copied into `$GOPATH/src/github.com/twpayne/gazelle-test` for the paths to work.

I'm not sure if this is a bug. Initially I thought there would be a conflict between the `auto.go` and `:gen-auto.go` elements in `srcs`, but Bazel does not complain. Secondly, changing the output filename in the `genrule`'s `outs` attribute and re-running Gazelle causes Gazelle to correctly update the filename in the 'go_library`'s `srcs`. So, it initially looks like a violation of the Don't Repeat Yourself (DRY) principle, but in fact works in practice.

Feel free to close this as "not a bug". The behaviour surprised me, which led to the investigation.

**Comment by jayconrod** [comment]
It's a feature, not a bug. :)

Gazelle now includes generated files mentioned in `out` or `outs` attributes of other rules in `srcs`. It will not remove lines with `# keep` declarations though. Bazel knows these files are generated by another rule, so it will figure out the dependency on the `genrule` automatically; no need to reference it explicitly.

**Comment by twpayne** [comment]
Ah, that's great. I've removed the `# keep` declarations referencing the `genrule`-generated files in my `BUILD.bazel` files and everything continues to work.

Thanks for the swift response and useful extra info!
