### ISSUE TITLE
Using vendored libraries that depend on other libraries

### ISSUE THREAD

**Issue by lingz** [bazelbuild/rules_go#62]
So as with your approach to vendoring, I manually created a BUILD file at my //goroot/src/github.com/etc location and include all the *.go files in the dependency. However, as the dependency imports other packages (also in the form of github.com), it will throw an "can't find import:" during compilation.

Is there any way to use vendored packages like this, which might have a long chain of dependencies?

**Comment by pmbethe09** [comment]
Due to the diamond-dependency problem, bazel has chosen not to load
dependencies of dependencies.  Instead, in your WORKSPACE file, you will
need to flatten and provide all of the transitive dependencies.

**Comment by lingz** [comment]
Are there any tools that can partially or fully automate this? I read about
glaze in some of these issues but it seems like there's no timeline on
releasing that.

**Comment by jayconrod** [comment]
Closing as (mostly) obsolete. [gazelle](https://github.com/bazelbuild/bazel-gazelle) can resolve dependencies, both vendoring an external. It can also import external repositories from dep.
