### ISSUE TITLE
setup: not clear that I'm not supposed to change values

### ISSUE THREAD

**Issue by kevinburke** [bazelbuild/rules_go#624]
I failed at this step:

```
Add the following to your WORKSPACE file:

git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.5.1",
)
load("@io_bazel_rules_go//go:def.bzl", "go_repositories")

go_repositories()
```

I tried to change the values there to the values for my own project but it seems like I'm supposed to use the ones you provided.

**Comment by ianthehat** [comment]
rules_go is not shipped with bazel, the purpose of those lines is to tell bazel where to find the rules for building go code, and what version of them to use.
This means you should use the values exactly as we specified them without any modifications (unless you want to switch to a different version, in which case you would change the tag= line only, or if you need to fork the rules, in which case you would change the remote= line to point to your forked repository)

**Comment by jayconrod** [comment]
I have a PR out to clarify the wording. I'll close this issue when that lands.

We definitely need more starting documentation though, and Gazelle needs a LOT more documentation (though I am planning to revamp its CLI, so I'm not going to write it yet).
