### ISSUE TITLE
cover before cgo

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#641]
Currently, we create a `go_library` with cgo by splitting .go files into pure Go and C, then compiling the pure .go files as a normal `go_library`. This means coverage instrumentation is added after cgo runs.

Unfortunately, this is the only way coverage will work at the moment. The cover tool in the SDK deletes cgo comments (as of Go 1.9). "go build" also runs cgo, then coverage. I hope to get this switched upstream at some point (issue to be filed), but we'll need to be aware of the Go version when ordering these.

**Comment by ianthehat** [comment]
+jayconrod I believe this is now how we want it to be?

**Comment by jayconrod** [comment]
Yes, this is fixed now.
