### ISSUE TITLE
Travis CI fails to download HEAD

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/rules_go#649]
In `rules_scala` we took your `.travis.yml` code for downloading bazel binaries.
Recently ci.bazel.io was changed and the old script stopped working.

I updated the script in `rules_scala` (https://github.com/bazelbuild/rules_scala/commit/6edec0d0c095807140f23920f08882a0142d8a48) but   @damienmg suggested waiting for that issue to resolve:
https://github.com/bazelbuild/continuous-integration/issues/95

**Comment by jayconrod** [comment]
@or-shachar Thanks for reporting. I think we'll stop testing at Bazel HEAD on Travis CI until bazelbuild/continuous-integration#95 is resolved.

Both rules_go and rules_scala are tested at HEAD on Jenkins, so Travis is somewhat redundant. We have seen failures on one and not the other in the past though, so it's nice to have them both.

**Comment by damienmg** [comment]
The Bazel team consider it a problem of Bazel if a build is failing @ HEAD and not with the release, it means that either we need to send PR to the various project to update to the new world or revert a change on Bazel. We ignore target already failing with Bazel release.
