### ISSUE TITLE
Is it possible to get rid of the "go_default_library" name?

### ISSUE THREAD

**Issue by adrianludwin** [bazelbuild/rules_go#66]
Hi all (but especially @yugui), 

I've been wondering about the magic go_default_library name, which seems to have been a part of the Go+Bazel support since the beginning. However, since (virtually?) every Go directory (and hence virtually every BUILD file) will have exactly one Go library in it, why do we need to _explicitly_ add the "go_default_library" text to everything? 

I would have thought that it would make the BUILD files much cleaner if we simply assume that every go_library defines a library with the same name as the package, so instead of referring to //path/to/lib:go_default_library, we could simply refer to //path/to/lib (or //path/to/lib:lib). However, it's not clear to me whether this is technically possible or if there would be other ill effects.

Thanks, A

**Comment by yugui** [comment]
First of all, sometimes there are several Go packages in a directory, which have different set of build tags. Although it is not related to the question very well.

Second, `go_default_library` makes the mapping between Bazel package and Go package path simple. We can always assume that `//path/to/lib:something` is under the go package `$go_prefix/path/to/lib/...`.

Technically it was not impossible to choose the design of `//path/to/lib:lib` but it adds another special case into the mapping and makes the implementation more complex. So I have no plan to change the design.

**Comment by pmbethe09** [comment]
I think once we have a working 'gazelle' BUILD file generator, this issue
will be less important

On Tue, Aug 16, 2016 at 9:46 AM, Yuki Yugui Sonoda <notifications@github.com

**Comment by adrianludwin** [comment]
Agreed, I think this is fine to leave for now. Thanks.
