### ISSUE TITLE
Go binary is downloaded twice

### ISSUE THREAD

**Issue by kevinburke** [bazelbuild/rules_go#671]
On my Mac, I observe the download count get to about 89MB, and then reset to 0 and start downloading again. Project is: https://github.com/kevinburke/rest, running the "make test" target.

I'm not sure the best way to reproduce and not sure I'll have time to do it.

**Comment by jayconrod** [comment]
Reproduced, even with a minimal example. This might have been introduced during some recent toolchain work. I'll look into this.

**Comment by jayconrod** [comment]
Well this is embarrassing. This bug has been here all along. Not sure why I didn't see it and fix it earlier.

There's some [fine print](https://docs.bazel.build/versions/master/skylark/repository_rules.html#when-is-the-implementation-function-executed) in the Bazel documentation that states the repository rules implemented in Skylark may be restarted if they declare a dependency on something that isn't available yet through a `Label`. In the implementation of `go_sdk_repository`, we call `ctx.download_and_extract`, *then* we get a template for the `BUILD.bazel` file from `@io_bazel_rules_go` using a label. That's causing a restart. We can fix this by doing the download *after* labels are resolved in these kinds of rules.

I'll send out a PR in a minute.

**Comment by ivyxyz** [comment]
Testing commit abfa5e953f870fd45618bc1d30ae971f37f5a34d with the default go version, I think go 1.9 is downloaded twice again.
