### ISSUE TITLE
Gazelle: incorrect definition for platform-dependent go/cgo package

### ISSUE THREAD

**Issue by sigma** [bazelbuild/rules_go#678]
`github.com/appc/spec/pkg/device` (https://github.com/appc/spec/tree/master/pkg/device) is an interesting corner case of a package that's purely go on Linux, and purely cgo on other Posix platforms.

Gazelle generates the following code for it:

```
load("@io_bazel_rules_go//go:def.bzl", "cgo_library", "go_library")

cgo_library(
    name = "cgo_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["device_posix.go"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:private"],
)

go_library(
    name = "go_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:linux_amd64": ["device_linux.go"],
        "//conditions:default": [],
    }),
    library = ":cgo_default_library",
    visibility = ["//visibility:public"],
)
```

The problems are:
- on both Linux and Darwin, exactly one of the `srcs` will be empty, leading to a failure to build the corresponding target
- on Darwin, the final library should just be the cgo library

It's not clear to me what code *should* be generated instead.
I'm currently working around the problem by adding platform-agnostic dummy go and cgo files, but that's quite ugly :)

**Comment by jayconrod** [comment]
`go_library` now supports combined pure-Go and cgo sources, as long as you add `cgo = True`. Gazelle doesn't generate these rules for this yet. I don't think there's an issue open -- this is as good as any. I'm working on a strategy for squashing `cgo_library` and `go_library` in existing BUILD files.

Ideally, this should work:

```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["device_posix.go"],
        "@io_bazel_rules_go//go/platform:linux_amd64": ["device_linux.go"],
        "//conditions:default": [],
    }),
    cgo = True,
    visibility = ["//visibility:public"],
)
```

**Comment by sigma** [comment]
so, just to be sure we're on the same page: that BUILD definition currently doesn't work as the underlying `cgo` is still invoked with an empty list of files on Linux, leading to the same error:

```
 CGoCodeGen //vendor/github.com/appc/spec/pkg/device:go_default_library.cgo_codegen failed (Exit 1).
usage: cgo -- [compiler options] file.go ...
  -debug-define
    	print relevant #defines
  -debug-gcc
    	print gcc invocations
  -dynimport string
    	if non-empty, print dynamic import data for that file
  -dynlinker
    	record dynamic linker information in -dynimport mode
  -dynout string
    	write -dynimport output to this file
  -dynpackage string
    	set Go package for -dynimport output (default "main")
  -exportheader string
    	where to write export header if any exported functions
  -gccgo
    	generate files for use with gccgo
  -gccgopkgpath string
    	-fgo-pkgpath option used with gccgo
  -gccgoprefix string
    	-fgo-prefix option used with gccgo
  -godefs
    	for bootstrap: write Go definitions for C file to standard output
  -import_runtime_cgo
    	import runtime/cgo in generated code (default true)
  -import_syscall
    	import syscall in generated code (default true)
  -importpath string
    	import path of package being built (for comments in generated files)
  -objdir string
    	object directory
  -srcdir string
    	source directory
2017/08/01 09:48:24 error running cgo: exit status 1
```

**Comment by jayconrod** [comment]
We should be able to fix that internally. At minimum, we can introduce dummy files when all sources are filtered out.

I thought we were already doing that, but I guess not yet.
