### ISSUE TITLE
Use Gazelle to update files in rules_go

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#698]
All of our BUILD files are written by hand. Many of them track somewhat specialized cases that Gazelle doesn't handle. But many of them (especially Gazelle itself) do follow normal conventions.

We should add `# gazelle:ignore` or `# keep` directives in files that Gazelle shouldn't mess with, then let Gazelle update the rest.

We should probably rename everything to BUILD.bazel while we're at i.

**Comment by ianthehat** [comment]
Renaming is covered by #576, I am just waiting to merge toolchains (#683) before I do it.
