### ISSUE TITLE
Gazelle expands ${SRCDIR} to an absolute path

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#704]
Suppose we have a `#cgo` directive in the file //tensorflow/tensorflow/go/lib.go like this:

```
// #cgo CFLAGS: -I${SRCDIR}/../../
```

Gazelle expands this to:

```bzl
go_library(
    ...
    cgo = True,
    copts = ["-I/usr/local/google/home/jayconrod/.go/src/github.com/tensorflow/tensorflow/tensorflow/go/../../"],
)
```

This path doesn't make sense for other users, and we can't check in the resulting BUILD file. We should expand `${SRCDIR}` into a path to the current package from the repository root.

**Comment by anurag-harness** [comment]
Is there any alternative provided to get the actual absolute path?
