### ISSUE TITLE
Update go_proto_library to use aspects referencing proto_library

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#707]
bazel now has java_proto_library and cc_proto_library which do exactly that.  
go_proto_library should do the same, and in the case of gazelle finding .proto, it should generate both a proto_library for the srcs and a go_proto_library which references that.

**Comment by kyessenov** [comment]
It would simplify our use case: we have a repository https://github.com/istio/api that contains only protos. I would like to import it with go_repository and have pb.go files auto-generated.
Is that possible nowadays?

**Comment by ianthehat** [comment]
I have been looking in to this a lot, and at this point I am not convinced that the aspect version will work.
There are just too many edge cases where the aspect just does not have enough information to get it right, and there is no way to supply additional per target information to an aspect.

What I am trying instead at the moment is adding a go_proto_source rule that takes a proto_library input and produces the .pb.go files as output, that you can then use directly in the srcs of a go_library rule. This gives full freedom and flexibility, while still relying on the core proto_library system (it consumes the descriptor output), at the cost of you having to have a go_proto_source and go_library rule for every proto package.

**Comment by balasanjay** [comment]
I was under the impression that the advantage of the new proto library approach means that if you add dependencies on N protos, you may have to add N go_proto_library rules, but you don't have to modify M rules in the transitive closure of the N protos (and add a go_api_version attribute).

Admittedly, this is less of a problem outside of google3 where I imagine people don't have humongous trees of protos with disparate OWNERs files and so forth. But still, ideally, blaze and bazel would spell the same thing the same way (I imagine that'd also make it slightly easier for those projects that are built both internally and externally like k8s (probably)).

What additional per-target information do you need?

**Comment by ianthehat** [comment]
That is the advantage, and it mostly works in a constrained environment with a trivial mapping of label to go import path.

Unfortunately go programmers in the wild have not had to live with these restrictions and have developed patterns that do not match, we have to support a lot more.

In theory the go package can (and should) be specified inside the proto file, but that information is not available to the aspect, so you can't use it to set the import path, and the import path has to be known at the go_library level.

If you build .pb.go files with a go generate rule (which is what most people have been doing) there are consequences. The most important is that you put that generate rule in the top of a go file, which in almost all cases will be compiled in to the package. This has naturally led developers to add extra types and methods to the generated, proto library package. To match that functionality we need to add those sources to the library as well, which means additional file lists and dependencies that are also not visible to the aspect.

**Comment by balasanjay** [comment]
I see. The import path issue is rather unfortunate, as you say.

(warning: I am a complete novice wrt to Skylark)

Is the crux of the issue that the Skylark implementation needs the package path to build the command-line for calling gc and can't read files to get it?

If so, would a slightly hacky workaround would be to substitute the compiler for a program that reads the files, extracts the information, builds command-line args for gc and then invokes gc via exec.Command? Basically, each compile would emit its desired package as a secondary output, and downstream rules would read those files to build the importpath flag.



Also, re the "add extra types to the generated package" point: it seems to me that there should be a genrule-esque (go_gen_proto_library?) solution to replace the go generate use cases, and the "more correct" go_proto_library approach, that folks can migrate to over time.

**Comment by balasanjay** [comment]
Actually, I just had a completely different idea:

Can we have the go_proto_library specify the importpath for the immediate package, and then any proto that doesn't have it specified (and has it purely set by aspect propagation) would just have a horribly mangled import path.

That is to say, as long as I only use the protos that I import directly, I can use their import paths as normal. If I access subfields of those protos, those subfields will have a mangled package name, but the key thing is that I can't name those types (I think) unless I depend on it directly (at which point, I would presumably add a go_proto_library and assign a better package name).

**Comment by prattmic** [comment]
I'm not sure I see how that would work. Presumably, you'd have something like:

```
proto_library(
     name = "foo",
     srcs = ["foo.proto"],
     deps = [":bar"],
)

go_proto_library(
     name = "foo_go_proto",
     deps = [":foo"],
     package = "package1",
)

proto_library(
     name = "bar",
     srcs = ["bar.proto"],
)

go_proto_library(
     name = "bar_go_proto",
     deps = [":bar"],
     package = "package2",
)
```

Suppose foo contains a message Foo with a field of type Bar. The `go_proto_library` for foo would generate a mangled package for Bar, something like `package1_import_bar.Bar`. When I depend on bar_go_proto directly, I get another type `package2.Bar`. I can't assign `Foo.Bar` with a `package2.Bar` because the type doesn't match.

AIUI, the issue is that the `proto_library` aspects don't provide the package. Perhaps Bazel can add that? (I'm not very familiar with aspects)
