### ISSUE TITLE
gazelle not deleting defunct `go_library` rule

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#731]
https://github.com/kubernetes/kubernetes/commit/e590ec705840226159e3d26f224890029cac912f removed `pkg/watch/doc.go` from our repo, leaving no Go files in the [directory](https://github.com/kubernetes/kubernetes/tree/e590ec705840226159e3d26f224890029cac912f/pkg/watch).

However, `gazelle` doesn't seem to be removing the now-defunct `go_library` from the [`BUILD`](https://github.com/kubernetes/kubernetes/blob/master/pkg/watch/BUILD) file there:
```
go_library(
    name = "go_default_library",
    srcs = ["doc.go"],
)
```

We're currently using gazelle @ 82483596ec203eb9c1849937636f4cbed83733eb.

cc @mikedanese

**Comment by jayconrod** [comment]
I'll dup this against #332, which has unfortunately been open for a while. I've added the `bug` label to make sure it gets attention soon.
