### ISSUE TITLE
support optimized vs debug builds

### ISSUE THREAD

**Issue by ldemailly** [bazelbuild/rules_go#741]
Could we make it so
bazel build -c opt
uses the optimizations for go compiler (basically today the default empty gcflags but maybe future go releases would have extra optimizations from the default)

While debug builds would have
-gcflags="-N -l"

(like c++ rules automatically tweak cc flags) 
does that make sense ?

**Comment by ianthehat** [comment]
I put up a pull request with this feature over the weekend, if you want to try it you can get #743, and let me know if it does what you need.

**Comment by ldemailly** [comment]
thanks a lot !!
