### ISSUE TITLE
Gazelle: should preserve "library" param for go_library

### ISSUE THREAD

**Issue by jmuk** [bazelbuild/rules_go#744]
The `go_library` rule has `library` param, like
```
go_library(
  name = "go_default_library",
  srcs = [...],
  library = ":foo_library",
  ...
)
```

This `library =` line is dropped after Gazelle processes this BUILD file.

Right now `# keep` marker can keep it, but I think this should be preserved by default.

**Comment by ianthehat** [comment]
the library line on a go_library is not a supported attribute, it's not in the documented interface, and it will cease to exist in the not too distant future...
The only use of a library attribute that is will be allowed is on go_test where it provides the link to the package under test for internal tests.
Can I ask what you are using it for so I can make sure that your use case is supported?

**Comment by jmuk** [comment]
Thanks, I wasn't aware of the status of library line.

I think it's a transient solution to merge new codegen-based library (`:foo_library` in this case) and old normal go_library. After the transition is done, I think this will be removed.

See https://github.com/istio/mixer/blob/88973cde1ffec6c25ae287ddd8013f959549289b/adapter/BUILD for the actual usage, if you're interested in.
