### ISSUE TITLE
Detect and update rules in non standard layouts

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#746]
We have examples in this repository that are in non standard directory layouts (see examples/cgo/sub).
It would be good if gazelle automatically spotted these and knew what to do, at the moment you have to add ignore directives, and gazelle will not update the rule for you.

**Comment by jayconrod** [comment]
What should Gazelle do in this situation? I'm sure we can detect non-standard rules (`sub` and `cgo_lib_test` in that example), but I don't think we can reliably update them in place. We could delete non-standard rules (replacing them with standard rules) or print a warning that we couldn't handle them.

**Comment by ianthehat** [comment]
This is a more general form of flat file processing, we should be able to work out that a given go_library rule represents a given directory and package, and update it as such, allowing both multiple packages in one directory, and multiple directories in one build file.

**Comment by jayconrod** [comment]
Migrated to bazelbuild/bazel-gazelle#17
