### ISSUE TITLE
request for 1.9 repositories

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#747]
Go 1.9 is out, so getting rules_go to support it natively would be nice. Not sure if there's a script for adding new Go versions here. Have the start of patch for this, but imagined someone might have some automation that would moot my work.

**Comment by ianthehat** [comment]
I was really hoping that bazel 0.5.4 would ship before go1.9, adding go1.9 is going to be annoying both in adding it and then in merging the toolchain work if we do it first, whereas adding it in the new toolchains is fairly trivial.

**Comment by ianthehat** [comment]
Bazel shipped 0.5.4 today, so we will tag a release on monday, and then get the toolchain changes submitted, and then add to1.9 on top of that.
I have already done most of the changes (in my [go1.9](/ianthehat/rules_go/tree/go1.9) branch, it's missing the verification sha because https://storage.googleapis.com/golang/ has not been updated with the 1.9 versions yet, but it works in it's current state, you can see the commit here: 0884b1535fea105049198ba8478842bc37852e95

**Comment by junghoahnsc** [comment]
When is this going to be released?

**Comment by ianthehat** [comment]
It is checked in to the main line, and everything is working. You can just update your rules to a recent commit if you want and it should be fine.
If you are asking when we are planning to tag a new release, we are trying to get a whole host of new features in, and then add lots of documentation before we tag a new version, so it may be a while.
In general we follow the go way where we try to keep the tip of master fully working and assume that people will be following that, version tagging is more about bug reporting and markers for when new features are released than anything else.

**Comment by junghoahnsc** [comment]
yI was asking an ETA for a new release. If it will take a while, yes we can use with a recent commit.
Thanks!

**Comment by hochhaus** [comment]
Now that bazel 0.6.0 is out any chance we could have a new rules_go release which includes 1.9?

**Comment by ianthehat** [comment]
We will be adding a new tag in the next couple of weeks

We are making sure the toolchain api is fully stable, adding full documentation for everything and trying to get the new proto handling into gazelle, but you really don't need to wait for a tag, we don't generally recommend you use tags to fetch anyway.
