### ISSUE TITLE
Run benchmarks

### ISSUE THREAD

**Issue by nelhage** [bazelbuild/rules_go#75]
Does a `go_test` support running benchmarks? I tried running the resulting binary with `-test.bench=.`, but it doesn't seem to do anything, and I don't see any reference to benchmark handling in `geneate_test_main.go`

**Comment by yugui** [comment]
Right. It is not supported right now.

**Comment by ghasemloo** [comment]
This is fixed in https://github.com/bazelbuild/rules_go/pull/230. The benchmark is working now.

**Comment by bjryan2** [comment]
@ghasemloo how do you force `bazel test` to run benchmarks? I cannot find any documentation or a hook in bazel

**Comment by hntd187** [comment]
@ghasemloo could you give an example of how to run this? I'm not sure how this works?

**Comment by bjryan2** [comment]
@hntd187 You need to directly run the test binary (found in `bazel-bin`) yourself. Running `go test -test.bench=. <binary>` should do the trick :)

**Comment by ghasemloo** [comment]
This should work:
bazel run //project:go_default_test -- -test.bench=.

**Comment by ianthehat** [comment]
We should document this

**Comment by JensRantil** [comment]
> We should document this

Was it ever documented?

**Comment by JensRantil** [comment]
Meh, never mind. Just saw the linked issue.
