### ISSUE TITLE
Gazelle generates duplicate `go_binary`s on directory renames

### ISSUE THREAD

**Issue by twpayne** [bazelbuild/rules_go#761]
Renaming a directory containing a `go_binary` and then running Gazelle leads to duplicate `go_binary` rules in the generated `BUILD.bazel`.

Example:

Consider a directory `foo` containing the following `BUILD.bazel` file generated by Gazelle:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    visibility = ["//visibility:private"],
)

go_binary(
    name = "foo",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```

If you rename the directory from `foo` to `bar` and re-run Gazelle in `-fix` mode, Gazelle adds a new `go_binary` target but does not remove the old one. The resulting `BUILD.bazel` file is:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    visibility = ["//visibility:private"],
)

go_binary(
    name = "foo",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "bar",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```

Although the resulting `BUILD.bazel` file is valid and builds both binaries, this is unlikely to be what the programmer intended. Running `go build` on the package would produce a single binary.

Maybe a special case is required here: if `BUILD.bazel` contains multiple `go_binaries` and they all have the same dependencies then discard all but the one whose name is equal to basename of the directory. In all other cases, maintain the existing `go_binary` rules.

**Comment by ianthehat** [comment]
And then you have people that make a single code base that varies it's behavior depending on the name of the binary (or arg[0] rather), and they want two go_binaries that have identical source lists...

I think there are always going to be extreme edge cases that gazelle cannot get right, what we should aim for is that gazelle is as helpful as it can be without ever being a hindrance. The worst thing it could do is repeatedly make a change the programmer has to undo each time they run it, and that always has to be uppermost in our minds when deciding what changes it should make for you.
In this case you have very rare situation where gazelle still makes a working build file and the programmer just has to delete a spare rule, where doing so automatically has the potential to delete something the programmer really wanted, so I would err on the side of leaving it alone.

**Comment by twpayne** [comment]
Good point about `argv[0]`. Caveats there are:

* Duplicating the binaries results in a slower build (the linker is invoked multiple times), `cp` would be quicker.
* Duplicating the binaries results in more disk usage (multiple copies of the same file exist simultaneously), using hard or symbolic links would be more efficient. `busybox` uses this approach, for example.

As an alternative, automation can catch the duplicate binary problem. I'm sure a crafted `bazel query` will catch duplicate binaries and can be added as a check in a CI step.

Thanks for the discussion. Feel free to close this as `WONTFIX`.

**Comment by ianthehat** [comment]
I totally agree with you that nobody should ever write a BUILD file like that, for all sorts of reasons. I am aware however that users have a habit of not agreeing with me, and we have to allow for patterns of use that to us seem a little odd sometimes :)

**Comment by jayconrod** [comment]
In general, I want Gazelle to delete rules that aren't needed anymore, primarily if there are no sources left. This binary renaming is a tricky situation because Gazelle won't know whether the `go_binary` rule was written manually or if was generated when the directory had a different name. This will also affect `go_library` rules in flat mode, which are named based on the directory.

Maybe this is a good use for our new `fix` command. `fix` could delete all Go rules that would not be generated by Gazelle, based on name. `# keep` comments could be used to preserve rules that were written manually.

**Comment by twpayne** [comment]
+1 on using `# keep` comments to preserve handwritten rules.

This seems like a very good compromise: doing the expected thing by default, while still allowing non-standard uses.

**Comment by jayconrod** [comment]
Closing old Gazelle issues.

I retract what I said in my earlier comment: Gazelle should not delete rules unless we can be reasonably sure that Gazelle created them. Users shouldn't need to opt out of deletion.

bazelbuild/bazel-gazelle#17 is a proposal to detect and update rules in non-standard layouts (which is what a renamed directory with a `go_binary` would be). We might rename rules when the `fix` command is given.
