### ISSUE TITLE
way to tell gazelle to not generate a test target

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#788]
I have a package that has only an integration test using rules_webtesting's `go_web_test_suite` in it.  Running `bazel run :gazelle` causes another test target that is always busted (because it doesn't use `go_web_test_suite`) even when the name the `go_web_test_suite` target is `go_default_test`.

Is there a way to get gazelle to not create this target with a comment in my BUILD file or similar?

**Comment by jmhodges** [comment]
(I also get told to run `gazelle fix` when I just did run `bazel run :gazelle -- -mode fix` over that BUILD file.

The exact output is "BUILD: warning: file contains rules whose structure is out of date. Consider running 'gazelle fix'.". Not sure what is busted about it. Maybe something in rules_webtesting? It would be nice to be told why gazelle fix asks for gazelle fix to be run!

**Comment by ianthehat** [comment]
possibly related to #748

**Comment by jayconrod** [comment]
There's no way to do this right now, but this is functionality I would like to have.

It will probably take the form of a directive in BUILD file. Something like:

```
# gazelle:skiptarget go_default_test
# gazelle:skiptarget go_default_xtest
```

Does that work for you?

**Comment by jayconrod** [comment]
I've filed #792 to track the vague warning message separately.

**Comment by jmhodges** [comment]
That would work for me!

**Comment by jmhodges** [comment]
And thank you for the separate ticket!

**Comment by jayconrod** [comment]
Migrated to bazelbuild/bazel-gazelle#57
