### ISSUE TITLE
go_path - contains generated cgo code

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#789]
I'm trying to use the `go_path` rule as a basis for IDE support for our rules_go based workspace (and also to make our cross compile less hacky for now, until official support lands).

One issue i've come across is if a library uses `cgo=True` the sources in the generated gopath are generated cgo files not the original go code.

Seems to stem from us replacing the srcs in the`go_library_macro` with those from the `setup_cgo_library` call (https://github.com/bazelbuild/rules_go/blob/master/go/private/rules/wrappers.bzl#L22)

I've got a patch I can PR which threads through the original go sources into a separate field of go_library, inaddition to `srcs` which may or may not contain generated code. With this change the generated gopath can be used for building / autocompletion.

I know the rule is in flux atm however so if there are better ideas for resolving this let me know.

**Comment by ianthehat** [comment]
Yeah, that's an oversight that falls out of the fact that we are forced to use cc_library and thus split what ought to be a single rule. 
The go_path stuff is in flux, but the library rule is reasonably stable now (I hope) and this is mostly about making the information available on the library, so I would love to see the PR.

**Comment by ains** [comment]
https://github.com/bazelbuild/rules_go/pull/793

**Comment by ianthehat** [comment]
I believe this was fixed with the submission of your patch, please reopen if there are still issues.
