### ISSUE TITLE
go_path should only return absolute directories

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#797]
The `go` tool and others require GOPATH to have only absolute directories in it[1]. When used, at least, in another repo, `go_path` will return a relative directory which collides with this. 

`go_vet` currently works around this by prepending `$(pwd)/` to its entries. Other tools built in other repos seem to need `"$(pwd)/"+ctx.var["BINDIR"]` to work correctly.

It would be easier for everyone if it was an absolute directory.

[1] with the error "GOPATH entry is relative; must be absolute path:"

**Comment by ianthehat** [comment]
I remember now why I did this. There are some use cases for the go_path stuff where it would be nice to be able to keep supporting remote execution, which means the resolve to a full path needs to happen at execution time of the specific rule in question, the absolute path of the go_path rule is no use if the results have been symlinked in to the working area of the current rule along with other stuff.
This is important if people want to do thinks like have vet run in a ci system.

**Comment by jmhodges** [comment]
Got a recommendation them for how to do this, then?  because having to remember BINDIR (and the examples here not having it included) and pwd seems easy to screw up

**Comment by ianthehat** [comment]
We could write a small go program that abs'd the GOPATH and GOROOT environment variables before running a sub command, would be generally useful.
I am really not sure why you needed the BIN_DIR stuff, so long as you got the inputs correct that should never be needed.
It's basically the approach we took with all the `go tool` invocations within the rules, we have a small helper that does stuff you have to do at run time (abs paths, inspect files) that runs as a wrapper over the real tool.

**Comment by jmhodges** [comment]
This is still required and now seems to have gotten weirder. I've got a go_path command working locally on macOS but not in linux on HEAD.

I think the BIN_DIR stuff is because I'm building rules_go as an external.

**Comment by jmhodges** [comment]
Discussion has moved to #1318
