### ISSUE TITLE
How can I specify dependent versions to go_rules_dependencies()

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#807]
Hello,

I'm trying to use `rules_go` from HEAD to use Go 1.9, but it failed due to version conflicts that `go_rules_dependencies()` loads like `org_golang_google_grpc`.
Is there any way to specify a version of dependency?

Thanks,

**Comment by ianthehat** [comment]
The dependencies at head were recently rewritten so they are all easy to override.
If you have already specified a repository with a matching name in your WORKSPACE **before** you call `go_rules_dependancies()` then your version will be honored and the go_rules will skip that one.

**Comment by junghoahnsc** [comment]
I thought I had to put `go_rules_dependancies()` before using any other rules like `go_repository()`.
I moved it to the end of WORKSPACE.
Thanks!

**Comment by ianthehat** [comment]
Glad it worked for you. Let us know if you need anything else.

**Comment by junghoahnsc** [comment]
It would be helpful if this is documented. And also it might be useful if we can pass versions to `go_rules_dependancies()`.

Thanks!
