### ISSUE TITLE
checksum changed on google protobuf v3.4.0

### ISSUE THREAD

**Issue by toffaletti** [bazelbuild/rules_go#830]
> no such package '@com_github_google_protobuf//': Error downloading [https://github.com/google/protobuf/archive/v3.4.0.tar.gz] to /private/var/tmp/_bazel_jason/f9068d4bee2f42e347047a166adc4943/external/com_github_google_protobuf/v3.4.0.tar.gz: Checksum was f6600abeee3babfa18591961a0ff21e7db6a6d9ef82418a261ec4fee44ee6d44 but wanted cd55ee08e64a86cf12aaadd4672961813f592c194ed0c9ad94da0ec75acf219f and referenced by '//proto:go_default_library_protos'.

**Comment by ianthehat** [comment]
This was reported in #820 and fixed in #824
The 0.5.5 release from this morning should have the fix. Please let us know if it is still a problem.
