### ISSUE TITLE
Is there a way to pass a target cpu to go_binary

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#832]
Hello,

I'd like to force a target cpu to some `go_binary` rule.
Is this possible? If not, is there a way to fail if `--cpu` is not set to a specific target?

Thanks,

**Comment by jayconrod** [comment]
So you have a `go_binary` that should only be built on a specific platform (or set of platforms), right?

There's no way to skip declaring a target on other platforms or to build a target on a specific platform without specifying it on the command line.

You can use `config_setting` and `select` to have platform-specific attributes like `srcs` or `gc_goopts`  though. We have a few of these predefined. Something like this?

```
go_binary(
    name = "bin",
    srcs = [
        "normal.go",
    ] + select({
        "@io_bazel_rules_go//go/platform:linux_amd64": [],
        "//conditions:default": ["error_on_unsupported_platforms.go"],
    }),
)
```

Keep in mind that although there are some predefined cpu values, in general it's user-defined. Users can set up their own crosstool and add cpu values with arbitrary names.

Does that help?

**Comment by junghoahnsc** [comment]
Yes. This works for our case.
Thanks!

**Comment by jayconrod** [comment]
Glad to help!
