### ISSUE TITLE
Question: Deterministic Builds

### ISSUE THREAD

**Issue by rlguarino** [bazelbuild/rules_go#863]
Are the builds produced by these rules supposed to be deterministic? Should the output hash to the same if you run `bazel build //...` then `bazel clean` and then `bazel build //...` without changing any file?

**Comment by ianthehat** [comment]
In theory, yes it should.

In practice there are ways to break this (things like build stamping that includes a timestamp, or custom build actions that write source files of random numbers) but anybody doing so is bad and should feel bad.
There may be bugs, if there are, please let us know and we will fix them, deterministic builds are very important to us.

**Comment by rlguarino** [comment]
@ianthehat  thanks for the quick response. I did a few more google searches and found: https://github.com/bazelbuild/rules_go/issues/198 

Seems that's still an Issue. I've build the same program with bazel 0.6.0 and go rules 0.5.4 and I see a lot of strings in the output that contain my username and the sandbox path.

**Comment by ianthehat** [comment]
Yes, that issue is not fixed, but it also should not affect whether the build is deterministic.

**Comment by rlguarino** [comment]
Maybe I'm using the wrong term. The way I'm testing this is by running `sha256sum` on the resulting binary in `bazel-bin`. I build the program, check the hash, run `bazel clean` and then build the program once more and compare the hash to the previous hash. I haven't been able to reproduce a build of my own this way.

**Comment by ianthehat** [comment]
If the sha is changing, then yes, you have a non deterministic build, but the username and sandbox path should be stable, so they would not be causing it.
Can you see what is different between the two, or share more information about what you are building, or a link to you project (or a cut down example that also exhibits the problem)

**Comment by rlguarino** [comment]
This is what I'm using to test:
```
ross@siberia ~/s/rlg.io (master)> head -n 12 WORKSPACE 
workspace(name = "io_rlg")

git_repository(
    name = "io_bazel_rules_go",
    commit = "2ffc49e4b9a3fb71fef5e94fa2da5bc1eca4f44d",
    remote = "https://github.com/bazelbuild/rules_go.git",
    #    tag = "0.5.5",
)

load("@io_bazel_rules_go//go:def.bzl", "go_repositories", "go_repository")

go_repositories()
ross@siberia ~/s/rlg.io (master)> tail -n +1 test/*
==> test/BUILD.bazel <==
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    visibility = ["//visibility:private"],
)

go_binary(
    name = "test",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

==> test/main.go <==
package main

func main() {
	panic("")
}
ross@siberia ~/s/rlg.io (master)> bazel clean 
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ross@siberia ~/s/rlg.io (master)> bazel build //test:test
INFO: Analysed target //test:test (15 packages loaded).
INFO: Found 1 target...
Target //test:test up-to-date:
  bazel-bin/test/test
INFO: Elapsed time: 1.973s, Critical Path: 0.92s
INFO: Build completed successfully, 8 total actions
ross@siberia ~/s/rlg.io (master)> sha256sum bazel-bin/test/test
312e96d41ad379971bee70836d8712d2c21a4cf5e2283b43b66d9086ecdc9d66  bazel-bin/test/test
ross@siberia ~/s/rlg.io (master)> bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ross@siberia ~/s/rlg.io (master)> bazel build //test:test
INFO: Analysed target //test:test (15 packages loaded).
INFO: Found 1 target...
Target //test:test up-to-date:
  bazel-bin/test/test
INFO: Elapsed time: 1.820s, Critical Path: 0.92s
INFO: Build completed successfully, 8 total actions
ross@siberia ~/s/rlg.io (master)> sha256sum bazel-bin/test/test
cfb9c0eaf0ad9b070f098bfadec1bd294c13ecc861424fa44a5e636de930412d  bazel-bin/test/test
```

Let me know how I can help debug this.

**Comment by ianthehat** [comment]
I have been looking in to this today, the problem is in the dwarf information.
The go linker adds a "DW_AT_comp_dir" entry to the dwarf section, and there is no way currently to suppress it short of stripping the dwarf section (which is something we need to offer a way of doing).
This did not used to matter, because the current directory was stable, but it's not if you are running under the current sandbox implementation, where the temporary directory created for each action execution is essentially random.

**Comment by rlguarino** [comment]
Thanks @ianthehat  I've re-tested this and it works for me :+1:

**Comment by ianthehat** [comment]
Note that if you specify either `-c dbg` or `--strip=never` it will still not be deterministic, as it will add the dwarf info back which will still contain the compilation directory, but the default is `-c fastbuid` `--strip=sometimes` which should always drop it, and I would expect build machines to be using `-c opt` `--strip=always` which will also drop it, so those cases will be fine.

I am going to discuss a way of making the dwarf not contain that path in the future (it's not useful anyway once the sandbox is torn down) but that will involve changes to the go linker, so it will require a new version of go if it happens at all.
