### ISSUE TITLE
Build Tags for `go_test`

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_go#867]
Support behaviour like `go test -tags=integration .` for different types of testing. Maybe this is already possible?

**Comment by jayconrod** [comment]
This is not possible at the moment, but it would be easy to add. The main issue is that we haven't decided on a good way to set the flags on the Bazel command line.

Maybe something like `bazel build --define='go_build_tags=foo,bar'`?

**Comment by ianthehat** [comment]
You can add tags to any rule, and use --test_tag_filters to filter which tests get run.
You can easily have multiple go_test targets with different test sources in them (no need for any single test to be in more than one go_test rule, better not to in fact).
The only thing that is not supported is a way of gazelle automatically generating or maintaining the split go_test rules.

**Comment by ianthehat** [comment]
I am going to close this issue as I don't think there is any work to do here, please let me know if this was not the case.
