### ISSUE TITLE
go_library: cgo and objc is not supported

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#878]
The `go build` recognises and accept `.m` files.
The `go_library` rules do not yet.

I am investigating into how complex it would be to add it, but I wanted to open this issue so that there is a place for the work.

**Comment by jayconrod** [comment]
Shouldn't be terribly complicated. We use the `cc_library` rule to compile C code from cgo. We would need to use an `objc_library` instead if .m files are present.

I have no idea how complicated linking would be. I'm guessing we would need to pull in a bunch of objc runtime stuff.

Gazelle support should be straightforward.

**Comment by ianthehat** [comment]
Last time I tried to use Bazel for objective C it turned out that it only had support for compiling it to iOS, not OSX. Not sure if it has changed in the mean time.

**Comment by steeve** [comment]
@ianthehat @jayconrod 

I went ahead and managed to make it work, although I'm having issues propagating the link options to go without an `objc` fragment in macro land.

This means I'm forced to provide frameworks as `clinkopts` instead of them being inferred automatically:
```python
go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
        "print.h",
        "print.m",
    ],
    cgo = True,
    clinkopts = [
        "-framework Foundation",
        "-framework CoreLocation",
    ],
    importpath = "github.com/steeve/cmd",
    visibility = ["//visibility:private"],
)
```

I also need to find a way to propagate the options from `objc_library` to that we can leverage the full potential.

I'm eager for feedback on my commit here, I'll open a PR later on: https://github.com/znly/rules_go/commit/2049b845b139c4287e9d3de488661ba3f525b568

**Comment by jayconrod** [comment]
Closing old issues. This works now (thanks @steeve !).

**Comment by steeve** [comment]
\o/ what a journey!
