### ISSUE TITLE
Can Gazelle Support Empty Go Prefixes?

### ISSUE THREAD

**Issue by nathantchan** [bazelbuild/rules_go#88]
Is it possible for the gazelle binary to support passing in empty go prefixes? This is especially helpful if our project has dependencies that pull in from different domains like gopkg.in, github.com, and/or golang.org.

**Comment by yugui** [comment]
Could you explain more about the directory structure in your project?
Are you talking about `vendor` directory?

**Comment by nathantchan** [comment]
Mostly an issue with vendor. Something like this:
vendor/gopkg.in
vendor/github.com
vendor/golang.org
If we want to build a package in github.com that imports a library in golang.org, it will either say that the golang.org package has the wrong prefix, or it assumes it is an external repo.

**Comment by jayconrod** [comment]
Closing old Gazelle issues. Please reopen an issue at https://github.com/bazelbuild/bazel-gazelle if Gazelle isn't doing something you want.

We do now have some support for empty prefixes now, but you do have to specify `-go_prefix ""` explicitly on the command line. This may not work for rules in the repository root directory, which would end up with an empty import path.
