### ISSUE TITLE
No way to pass gazelle directives to go_repository

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/rules_go#882]
The latest work on supporting compilation of .proto files with gazelle breaks existing go_repository logic. If a project's protos cannot be built (but they have committed .pb.go files), there is no option that can be passed to go_repository to set proto-related behavior of gazelle. I couldn't find any reference to this functionality in existing branches, so I'm assuming this is worth filing an issue for.

On a related note, modifying gazelle sources does not regenerate BUILD.bazel files during the next `bazel build`. Is that intended behavior?

**Comment by jayconrod** [comment]
Sorry for not responding this sooner. This was fixed directly in #894.

Modifying Gazelle sources won't change BUILD.bazel files already generated in `go_repository`. This is an unfortunate consequence of how repository rules work in Bazel -- they are only re-evaluated when their attributes (e.g., the commit id) or their implementation changes. We are planning to remove `go_repository` eventually (#460). In the future, you'll generate a build files for external repositories ahead of time and then use `new_http_archive` or `new_git_repository`. This will also give you greater control over dependencies (in case the files require some modification beyond what Gazelle does).
