### ISSUE TITLE
--features=static doesn't produce static binary

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_go#883]
Cloning github.com/kubernetes/test-infra as head (831d39df911d18a06116f437162b32ff53f1ae7f) and running the following produces a binary with a dependency on glibc:
```shell
$ bazel build --features=static prow/cmd/hook
INFO: Analysed target //prow/cmd/hook:hook (1 packages loaded).
INFO: Found 1 target...
Target //prow/cmd/hook:hook up-to-date:
  bazel-bin/prow/cmd/hook/hook
INFO: Elapsed time: 0.407s, Critical Path: 0.08s
INFO: Build completed successfully, 1 total action

$ ldd bazel-bin/prow/cmd/hook/hook
        linux-vdso.so.1 =>  (0x00007ffe7c10c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8806a39000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8806670000)
        /lib64/ld-linux-x86-64.so.2 (0x00005580a91fc000)
```

Perhaps I'm holding it wrong?

**Comment by mattmoor** [comment]
This is where they currently build the binary that's included in their image: https://github.com/kubernetes/test-infra/blob/master/prow/Makefile#L71

**Comment by ianthehat** [comment]
Which version of the rules are you up to?
Until very late last week `--features=static` only affected tests, not binaries.

It's also not the best way even with the new stuff, you really want to use the output_groups form.

```
bazel build --output_groups=static //prow/cmd/hook
```

will build you `bazel-bin/prow/cmd/hook/hook.static`

**Comment by damienmg** [comment]
Why not have hook.static be an optional output so you don't have to specify
all those command line arguments? You would then just ask to build
//prow/cmd/hook:hook.static.

**Comment by mattmoor** [comment]
@ianthehat I either want something I can put in `.bazelrc` to get static binaries without anything, or (my preference) that is activated by a side-output like what @damienmg indicates.

I will experiment with updating the version of `rules_go` the repo uses, and see if that fixes things.

**Comment by mattmoor** [comment]
@ianthehat It works at head.  Do you have an ETA for darwin support?

**Comment by ianthehat** [comment]
There is no plans to ever support static builds on darwin, I am under the impression that it is not even possible, although I have spent very little time looking into it myself, I just trusted the comments of others.
