### ISSUE TITLE
Gazelle uses @com_google_protobuf and @com_github_golang_protobuf when `vendored = "external"` is set

### ISSUE THREAD

**Issue by jkinkead** [bazelbuild/rules_go#888]
When running a `gazelle` target with `external = "vendored"`, some targets are being generated which reference nonexistent `@com_google_protobuf` and `@com_github_golang_protobuf` repositories.

Specifically, I'm seeing this for the generated BUILD files for `github.com/jhump/protoreflect/desc/protoparse`.

These should be `//vendor` paths.

**Comment by tomwilkie** [comment]
I too am seeing this, I'm getting output like this:
```
vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go:8:2: inconsistent definition for type grpc.callInfo during import
	struct { grpc.failFast bool; grpc.headerMD metadata.MD; grpc.trailerMD metadata.MD; grpc.peer *peer.Peer; grpc.traceInfo grpc.traceInfo; grpc.maxReceiveMessageSize *int; grpc.maxSendMessageSize *int; grpc.creds credentials.PerRPCCredentials } (in "google.golang.org/grpc")
	struct { grpc.failFast bool; grpc.headerMD metadata.MD; grpc.trailerMD metadata.MD; grpc.traceInfo grpc.traceInfo } (in "github.com/weaveworks/common/httpgrpc")
```

I think this is because I have a vendored grpc library and gazelle is adding `//vendor/google.golang.org/grpc` to my dependancies, but the go_grpc_library is depending on `@org_golang_google_grpc`.  We used to be able to override the `@org_golang_google_grpc` dependancy with the old proto rules: https://github.com/bazelbuild/rules_go/issues/442  Can we do this again?

**Comment by tomwilkie** [comment]
I eventually got it to compile by adding:

```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://codeload.github.com/bazelbuild/rules_go/zip/ad076c97335c03319280fa438c9f958e7c81597a",
    strip_prefix = "rules_go-ad076c97335c03319280fa438c9f958e7c81597a",
    type = "zip",
)

# Ensure @org_golang_google_grpc matches my vendored copy
load("@io_bazel_rules_go//go:def.bzl", "go_repository")
go_repository(
    name = "org_golang_google_grpc",
    importpath = "google.golang.org/grpc",
    urls = ["https://codeload.github.com/tomwilkie/grpc-go/zip/ab0c33d016c88f45fe3b7ecc5a256eb1a07c297a"],
    strip_prefix = "grpc-go-ab0c33d016c88f45fe3b7ecc5a256eb1a07c297a",
    type = "zip",
    build_file_proto_mode = "disable"
)
```

to my WORKSPACE

**Comment by jayconrod** [comment]
#945 should fix the the dependencies in vendor. Let me know if it doesn't do what you want.

@tomwilkie With this change, `go_grpc_library` should depend on `//vendor` targets in vendored mode.

In general, that is the correct way to override a repository. You can declare a replacement `go_repository` before or after the call to `go_rules_dependencies()`. That function won't override a repository that's already been declared.
