### ISSUE TITLE
ERROR: 'alias' is not defined

### ISSUE THREAD

**Issue by lucas-sonnabend** [bazelbuild/rules_go#89]
I followed the instruction to build a go repo with bazel but I got the following error:
ERROR: /home/lucas/.cache/bazel/_bazel_lucas/193cc5f26c6c8c0e09cc62d097bb638a/external/io_bazel_rules_go/go/toolchain/BUILD:5:1: name 'alias' is not defined.
ERROR: /home/lucas/.cache/bazel/_bazel_lucas/193cc5f26c6c8c0e09cc62d097bb638a/external/io_bazel_rules_go/go/toolchain/BUILD:10:1: name 'alias' is not defined.
ERROR: /home/lucas/.cache/bazel/_bazel_lucas/193cc5f26c6c8c0e09cc62d097bb638a/external/io_bazel_rules_go/go/toolchain/BUILD:15:1: name 'alias' is not defined.
ERROR: /home/lucas/Documents/bazel_playaround/go_example/go/src/improbable.io/dictdash/BUILD:3:1: every rule of type go_library implicitly depends upon the target '@io_bazel_rules_go//go/toolchain:go_include', but this target could not be found because of: no such target '@io_bazel_rules_go//go/toolchain:go_include': target 'go_include' not declared in package 'go/toolchain' defined by /home/lucas/.cache/bazel/_bazel_lucas/193cc5f26c6c8c0e09cc62d097bb638a/external/io_bazel_rules_go/go/toolchain/BUILD.
ERROR: Loading failed; build aborted.

This is related to version 0.1.0, when I used version 0.0.4 it worked fine

**Comment by lucas-sonnabend** [comment]
The following is the commit that breaks it:
4c2efe6cca58555e0cf333224c02298a08274bbb

**Comment by pcj** [comment]
Does the problem persist on the latest master commit?

```
git_repository(
     name = "io_bazel_rules_go",
     remote = "https://github.com/bazelbuild/rules_go.git",
     commit = "6f9dff563e4946bf92ec33eae9397a2d9db93a11",
 )
```

**Comment by yugui** [comment]
@lucas-sonnabend What version of Bazel are you using?
`alias` is a 0.3.0 feature.  So I suspect if you are using 0.2.x.

**Comment by lucas-sonnabend** [comment]
okay, I'm using 0.2.2b, which is the latest version you can get via apt-get
So the solution is to install it from the github repo, right?

**Comment by yugui** [comment]
Does the installer or a their apt repository work on debian?
https://www.bazel.io/versions/master/docs/install.html

**Comment by yugui** [comment]
Can I close this issue?
