### ISSUE TITLE
gRPC version is old

### ISSUE THREAD

**Issue by jmuk** [bazelbuild/rules_go#892]
Upgrading our code base with the latest rules_go revision, I've noticed that some of our code base doesn't compile, and noticed that because rules_go fetches gRPC v1.0.4, which is older than the expectation of our code base (https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl#L164).

Is it possible to upgrade it to the latest release track, or to provide a way to customize the version through some parameter of `go_repositories`?

**Comment by jayconrod** [comment]
You can load your own version of gRPC (or any other dependency) by explicitly adding it to your WORKSPACE file. I think it needs to be above the first load statement. Make sure the name is still `org_golang_google_grpc`.

We should update it on our side though.

**Comment by jayconrod** [comment]
I've started working on this. The newest version of gRPC has a new dependency and requires new versions of some existing dependencies. Gazelle may need some tweaking to generate correct protos in here, too.
