### ISSUE TITLE
Unable to depend on cgo library in c

### ISSUE THREAD

**Issue by ivyxyz** [bazelbuild/rules_go#901]
Continuing from the cgo example here (https://github.com/bazelbuild/rules_go/tree/master/examples/cgo),

BUILD.bazel
```
cc_binary(
    name = "main",
    srcs = [
        "main.c",
    ],
    deps = [
        ":go_default_library",
    ],
)
```
main.c
```
#include "use_exported.h"

int main() {
  PrintGoVersion();
}
```
This will result in error of `in deps attribute of cc_binary rule :main: go_library rule ':go_default_library' is misplaced here (expected cc_inc_library, cc_library, objc_library or cc_proto_library).`

**Comment by jayconrod** [comment]
This is not expected to work now, but we'd like to add a rule to make it work in the future.

A big concern here is that all the Go code that ends up in a binary needs to be linked by the Go linker, but there's no way to make that happen if a `cc_binary` depends on multiple `go_libraries`. We'll work with the core Bazel folks to find a design that makes sense.

**Comment by ajbouh** [comment]
I've had some success with buildmode c-shared and using a go library as a dependency for a c++ program, though this approach only works on macOS and not on Linux due to different defaults in how the go std library is compiled. Some relevant discussion here: https://github.com/bazelbuild/rules_go/issues/54

**Comment by jayconrod** [comment]
I discussed this offline with @ianthehat, who has looked more deeply into the C++ rules. They actually check the rule type of their dependencies, not just providers. There is no way to implement Skylark rules that are compatible with them.

That might change some time in the distant future, but for now, I'm closing this as infeasible. @ajbouh's solution seems like the only thing that will work for now, but I would expect to see lots of platform-specific linking problems with that.

**Comment by ajbouh** [comment]
I concur with the platform-specific linking issues comment. They are not
fun. It would probably be simpler to just use the go toolchain directly to
generate the files you need and make a cc_library out of those.
