### ISSUE TITLE
rules_go downloads whole toolchain

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#915]
Even with a `WORKSPACE` that looks like this 
```
local_repository(
        name = "io_bazel_rules_go",
        path = "/home/barriosj/rules_go",
)



load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains","go_sdk")
go_sdk(name="go1_9_1_linux_amd64", path="/home/barriosj/go") #can't stop download until u run go install -v std as root

go_rules_dependencies()
go_register_toolchains()
```
The rules still believe it is necessary to download the whole tool chain. I also have installed to my local go distribution `go install -v std` . One of the requirements I have is that code can be built with no internet connection.

**Comment by ianthehat** [comment]
If you just want to use the installed toolchain, you can just use "host" as the version, see [here](/bazelbuild/rules_go/blob/master/go/toolchains.rst#using-the-installed-go-sdk) for full documentation on selecting toolchains.

If you just want to avoid downloads, you can use `--experimental_repository_cache`
It is easier to force local repositories using `--override_repository` so you don't have to modify the WORKSPACE file.

**Comment by jeb2239** [comment]
For this build to be truly reproducible without an internet connection it seems like you need to specify every repository used in the WORKSPACE

**Comment by ianthehat** [comment]
You can specify repository overrides using the bazel.rc, or you could use an HTTP proxy, or you could vendor, or write custom repository rules.
I am going to close this issue because I don't think there is anything rules_go can or needs to do for this issue, please let me know if this was not the case.
