### ISSUE TITLE
use local repository with git_repository?

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#916]
Is there away to use the local git repository with hashes to control version used? It seems this functionality also requires you to download the from a remote git repository.

**Comment by ianthehat** [comment]
Not sure what you are asking here.
Local repository knows nothing about git or hashes, the rules that use git always start with a clone and can work from any valid git url.

**Comment by jeb2239** [comment]
I am saying that a git repository is a git repository wether it comes from a url or not and that i would have expected that its revision could checked before it is used by the git repository rule but it seems like you absolutely must download it to get this functionality even though all this information is available in a local git initialized repository.

**Comment by ianthehat** [comment]
The git repository rules clone the repository and the modify the working directory to the requested revision. They don't modify the source they are fetching from, I really don't think you want a build to cause a force checkout to a specific revision of a git clone it was not in full control of.
The source can be local (use a file url) it just won't use that copy, it will clone it to it's scratch area so it has something safe to work on.

**Comment by jeb2239** [comment]
git_repository(
    name = "io_bazel_rules_go",
    remote = "file://localhost/home/barriosj/rules_go/BUILD.bazel",
    commit = "a390e7f7eac912f6e67dc54acf67aa974d05f9c3",
)

is this what you mean?

**Comment by jeb2239** [comment]
or this
```

git_repository(
    name = "io_bazel_rules_go",
    remote = "/home/barriosj/rules_go",
    commit = "a390e7f7eac912f6e67dc54acf67aa974d05f9c3",
)



load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_repository","go_register_toolchains")




go_repository(
     name = "com_github_sirupsen_logrus",
    commit = "89742aefa4b206dcf400792f3bd35b542998eb3b",
    remote = "/home/barriosj/logrus",
    importpath = "github.com/sirupsen/logrus",
    vcs="git"
)



go_register_toolchains() 
go_rules_dependencies()

``
neither are working for me but I don't which is correct.

**Comment by jeb2239** [comment]
Also this seems to be downloading even more things than I thought...........

/home/barriosj/go_practice_code/src/BUILD.bazel:3:1: no such package '@com_github_sirupsen_logrus//': no such package '@io_bazel_rules_go_repository_tools//': java.io.IOException: Error downloading [https://codeload.github.com/golang/tools/zip/3d92dd60033c312e3ae7cac319c792271cf67e37] to /home/barriosj/.cache/bazel/_bazel_barriosj/75347ef6914677177b441e22d1f94b55/external/io_bazel_rules_go_repository_tools/3d92dd60033c312e3ae7cac319c792271cf67e37.zip: Unknown host: codeload.github.com and referenced by '//src:go_default_library'

**Comment by jayconrod** [comment]
It doesn't seem like this will work. See [documentation for the `remote` attribute](https://docs.bazel.build/versions/master/be/workspace.html#git_repository.remote). It must be an HTTP URL.

You may need to implement a repository rule to accomplish this. See [Repository Rules](https://docs.bazel.build/versions/master/skylark/repository_rules.html) and [`repository_ctx`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html).
