### ISSUE TITLE
Allow use of vendor/ to satisfy go_rules_dependencies()

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#918]
Right now, I might have (and in fact do in the repo I'm using `rules_go` with) grpc and proto in my vendor/ directory. Unfortunately, any rule in `rules_go` that needs those libraries pulls an independent version in from the web. Can we make it easy to fetch these deps from the local repository instead of having to use some external source?

**Comment by ianthehat** [comment]
The rules need to know the label of those dependancies up front, it's referenced from inside rules_go and it cannot change or be controlled without modifying the source of the rules.
You can control what those labels point to easily though by replacing the repository they reference.
If you want it to point to the one in the vendor folder you would need a workspace rule that declared a repository pointing at your local folder and you would need to pre-generate and check in the workspace and build files for that folder.

It would be better though to use normal workspace methods to set the version you want, and soon gazelle will know how to prefer the workspace declared versions to ones found in the vendor folder.

**Comment by swsnider** [comment]
Our goal is to be able to avoid calls to the network in general during builds (or failing that, definitely not calls to the internet).

I'm trying to also avoid a situation where a reference to the public internet sneaks in because I didn't override the rules soon enough, or because a dependency got added in a new rules_go release, etc., so I'd really like an explicit 'always use //vendor/...' mode, so that the build fails if a new dependency is required instead of falling back to the undesirable behavior of connecting to the internet.

**Comment by jeb2239** [comment]
Has there been any progress on this? I have looked through the source of the rules and have even attempted to write them in such away that they don't download anything. It is ashame there is no way to freeze the downloaded artifacts such that they can be checked in or saved.

**Comment by ianthehat** [comment]
The rules themselves refer to the workspace repository labels, there is no way to tell them to always use vendor. What you can do is map those workspace repositories to folders in your vendor area using local_repository, and then it will all just work. There is no need for any changes to rules_go for this.
Please let me know if you have attempted this and not got it to work.
