### ISSUE TITLE
gazelle ignores "vendor/" inside vendored dependency

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_go#946]
Please take a look to repository for problem reproduce / problem description
https://github.com/excavador/bazel_vendor_inside_vendor

**Comment by jayconrod** [comment]
This is a known issue unfortunately. #859 will solve this.

**Comment by excavador** [comment]
@jacobvoytko thank you!

Please guide me - should I keep this ticket, or attach my bug-repo to some another ticket and close this?

**Comment by jayconrod** [comment]
No need to do anything now. I'll keep this issue open and verify that it's fixed when #859 is fixed.

Thanks for putting this together by the way. Always nice to have reproducible examples like this.

**Comment by excavador** [comment]
My pleasure!
Will wait fix

**Comment by jayconrod** [comment]
Closing old Gazelle issues. Index-based library resolution landed a few weeks ago, so this should be working now. If not, please file a new issue in bazelbuild/bazel-gazelle.
