### ISSUE TITLE
Creating a thrift library with rules_go

### ISSUE THREAD

**Issue by RBlafford** [bazelbuild/rules_go#948]
Hi all. I would like to create a go_library from a list of go files which have previously been genn'ed from a genrule. Apparently I cannot just generate the files and attempt to compile them using go_library, because go_library will complain:

`bazel-out/local-fastbuild/genfiles/concord/thrift/gen_concord/gen-go/concord/mutable_ephemeral_state_service-remote/mutable_ephemeral_state_service-remote.go: import of concord/thrift/gen_concord/gen-go/cluster_management, which is not a direct dependency
...
`
All of my imports between generated files cannot be included. Looking at the docs it appears as though I want to do something with GoEmbed. The docs say:

`Providing the dependencies for generated code. If you wanted to use flatbuffers in your code, and you had a custom rule that ran the flatbuffers compiler to generate the serialization functions, you might hit the issue that the only thing that knows you depend on github.com/google/flatbuffers/go is the generated code. You can instead have the generator return a GoEmbed provider instead of just the generated files, allowing you to tie the generated files to the additional dependencies they add to any package trying to compile them.
`

This is exactly what i'm trying to do, however there is no documentation on GoEmbed or how to use it. I then attempted to emmulate how go_proto* works but failed due to my lack of complete understanding of this project in its entiety. 

My question is, how should I attempt to solve this issue? Am I going down the right path attempting to do this in the same vein as the go_proto* providers or is this easier then it seems?

**Comment by ianthehat** [comment]
This stuff is all now working and mostly documented, see go_source for an example of how to return source and deps pairs.
Happy to help make this work if you want to send me a link to your rules, feel free to re-open this if you still need/want anything.
