### ISSUE TITLE
How to specify output dir in project bazelrc?

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#954]
I tried
`startup --batch --host_jvm_args=-XX:-UseParallelGC --output_base=/dev/shm/$$USER`
and 
`bazel --output_base=/dev/shm/$$USER`

as lines in my .bazelrc file

**Comment by jayconrod** [comment]
`--output_base` can go in `startup` (as you wrote on the first line), but Bazel won't expand variables.

```
startup --output_base=/home/jay/bazel_out_dir`
```

You can put this in ~/.bazelrc for user-specific settings or tools/bazel.rc for project-specific settings.
