### ISSUE TITLE
0.6.0 Error: BUILD file not found on package path

### ISSUE THREAD

**Issue by font** [bazelbuild/rules_go#964]
When upgrading from rules_go 0.5.5 to 0.6.0 I encounter the following error when attempting to `bazel fetch //:genfiles_deps` in this repo https://github.com/kubernetes/cluster-registry:

```
→ bazel fetch //:genfiles_deps
.........
ERROR: /home/user/.cache/bazel/_bazel_user/3d01b22cc801f0c39fe4276b1a6f4f8d/external/io_k8s_apimachinery/pkg/runtime/BUILD.bazel:11:1: no such package '@io_k8s_apimachinery//k8s.io/apimachinery/pkg/util/intstr': BUILD file not found on package path and referenced by '@io_k8s_apimachinery//pkg/runtime:runtime_go_proto'.
ERROR: /home/user/go/src/k8s.io/cluster-registry/BUILD.bazel:8:1: no such package '@io_k8s_kubernetes//hack/boilerplate': failed to fetch io_k8s_kubernetes: 2017/10/26 19:38:00 get "k8s.io/kubernetes": found meta tag vcs.metaImport{Prefix:"k8s.io/kubernetes", VCS:"git", RepoRoot:"https://github.com/kubernetes/kubernetes"} at https://k8s.io/kubernetes?go-get=1
# cd .; git clone https://github.com/kubernetes/kubernetes /home/user/.cache/bazel/_bazel_user/3d01b22cc801f0c39fe4276b1a6f4f8d/external/io_k8s_kubernetes
Cloning into '/home/user/.cache/bazel/_bazel_user/3d01b22cc801f0c39fe4276b1a6f4f8d/external/io_k8s_kubernetes'...
fatal: Unable to read current working directory: No such file or directory
fatal: index-pack failed
2017/10/26 19:38:03 exit status 128
 and referenced by '//:genfiles_deps'.
 ERROR: Evaluation of query "deps(//:genfiles_deps)" failed: errors were encountered while computing transitive closure.
```
Not sure why the `git clone` fails but that's clearly why no such file or directory exists and may be related to the first error. The `git clone` error only happens the first time and goes away after a subsequent execution leaving only multiple instances of the first error: `BUILD file not found on package path` (the reason for this issue).

After inspecting the repo, it's clear that there exists a `BUILD` and `BUILD.bazel` file in `/home/user/.cache/bazel/_bazel_user/3d01b22cc801f0c39fe4276b1a6f4f8d/external/io_k8s_apimachinery/pkg/util/intstr`. Both build files contain the dep target `go_default_library`.

Why is the error reporting that the BUILD file is `not found on package path and referenced by @io_k8s_apimachinery//pkg/runtime:runtime_go_proto`?

**Comment by jayconrod** [comment]
It sounds like fetch_repo might be silently failing here. I'll look into that.

In the mean time, you should be able to work around this by running `bazel clean --expunge` and then fetching or building again.

**Comment by font** [comment]
Unfortunately, these errors are from a clean state such that fetching/building after running `bazel clean --expunge` results in the same issue over and over again.

**Comment by jayconrod** [comment]
I looked into this more closely. You're seeing this problem after upgrading because of the new proto rule generation in Gazelle. These rules are being generated:

```
proto_library(
    name = "runtime_proto",
    srcs = ["generated.proto"],
    visibility = ["//visibility:public"],
    deps = ["//k8s.io/apimachinery/pkg/util/intstr:intstr_proto"],
)

go_proto_library(
    name = "runtime_go_proto",
    importpath = "k8s.io/apimachinery/pkg/runtime",
    proto = ":runtime_proto",
    visibility = ["//visibility:public"],
    deps = ["//k8s.io/apimachinery/pkg/util/intstr:go_default_library"],
)
```

The label in `deps` doesn't exist. It comes from this import:

```
import "k8s.io/apimachinery/pkg/util/intstr/generated.proto";
```

Gazelle and Bazel expect proto import paths to be relative to the root of the repository. So they will both have trouble with this. Outside of Bazel, you have a lot of flexibility for setting search paths in protoc, so reality doesn't always match expectations.

I'd suggest adding `build_file_proto_mode = "disable"` to `go_repository` rules for repositories that don't follow the Bazel convention. This will cause Gazelle to ignore .proto files. Gazelle will still incorporate existing .pb.go files into `go_library` targets.
