### ISSUE TITLE
Add additional files into the go_library for a go_proto_library

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#973]
From looking at the [examples](https://github.com/bazelbuild/rules_go/tree/master/examples/proto) (thanks for doing that!), it seems that there isn't a way to generate a go_library that has both the proto and additional source files to be included in the package.

Is there a way I can work around that? I would like to add additional things to that package but can't figure out how.

**Comment by ianthehat** [comment]
The way to do this is to not add them to the go_proto_library, but instead add the go_proto_library to the embed inputs of a normal go_library. This uses the go_proto_library as a source and dep generator, rather than an actual go library.

```
proto_library(
    name = "my_proto",
    srcs = ["my.proto"],
)

go_proto_library(
    name = "my_go_proto",
    proto = ":my_proto",
    importpath = "github.com/user/project/thing/my_proto",
)


go_library(
    name = "my_go_lib",
    srcs = ["extra_source.go"],
    embed = [":my_go_proto"],
    importpath = "github.com/user/project/thing/my_proto",
)
```

**Comment by achew22** [comment]
Thanks! I put together a simple example of this and sent PR979 to document and test the functionality.
