### ISSUE TITLE
Can't go_repository for cloud.google.com/go

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#974]
When I add this go_repository rule (and associated repository rules)

```
go_repository(
    name = "com_google_cloud_go",
    commit = "c070977cc61d0a6d9bf31484517ed2c164544cc0",
    importpath = "github.com/GoogleCloudPlatform/google-cloud-go",
)
```

then build my target I get the error:

```
achew22@lappy:/tmp/rules_go_demo (master)$ bazel build //...
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
ERROR: /home/achew22/.cache/bazel/_bazel_achew22/d7ae88e473a0392c8ef67f0296c8cdf9/external/org_golang_x_oauth2/google/BUILD.bazel:3:1: GoCompile external/org_golang_x_oauth2/google/~normal~go_default_library~/golang.org/x/oauth2/google.a failed (Exit 1)
2017/11/01 00:45:02 missing strict dependencies:
        external/org_golang_x_oauth2/google/default.go: import of cloud.google.com/go/compute/metadata, which is not a direct dependency
        external/org_golang_x_oauth2/google/google.go: import of cloud.google.com/go/compute/metadata, which is not a direct dependency
INFO: Elapsed time: 0.508s, Critical Path: 0.10s
FAILED: Build did NOT complete successfully
```

I have uploaded a failing sample as a gist at https://gist.github.com/achew22/2680239539887d8d8661a9ab136b9b2d and would be happy to submit a PR to a repo with a failing integration test.

**Comment by jayconrod** [comment]
Try changing `importpath` for that repository to `cloud.google.com/go` instead. `go_repository` will do the import path redirection automatically. If you need to use a different repository with the same import path (e.g., a fork), you can set it with the `remote` attribute.

I tried building your gist with that change, and it resolved the error, but there were some other undefined symbols. Maybe a versioning issue?

**Comment by achew22** [comment]
That fixed it. Thanks for pointing out my problem! I also documented the gist which should get picked up by the googlebot eventually and make some nice results for someone with the exact same problem as me.
