### ISSUE TITLE
Not able to use @org_golang_google_grpc//status:go_default_library in 0.6.0

### ISSUE THREAD

**Issue by crazytan** [bazelbuild/rules_go#977]
I'm using v0.6.0 rules with bazel 0.7.0. Bazel build fails for the following BUILD file (`foo.go` is an empty file in package `hello`):
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "hello",
    srcs = [ "foo.go" ],
    deps = [
         "@org_golang_google_grpc//status:go_default_library",
    ],
    importpath = "hello",
)
```
The error message is 
```
no such package '@org_golang_google_grpc//status': BUILD file not found on package path
```
However, if I change `@org_golang_google_grpc//status` to `@org_golang_google_grpc//codes`, the build succeeds. The build also succeeds if I use the latest commit of `rules_go`.

My concern is that since `go_rules_dependencies()` automatically includes `google.golang.org/grpc`, there should be some testing done for each release, as we no longer have control of the specific commit of the rpc library anymore.

**Comment by promiseofcake** [comment]
What was the resolution on this?

**Comment by jayconrod** [comment]
@promiseofcake I don't think we investigated this issue before it was closed, but we updated to the latest version of google.golang.org/grpc in October. The issue may have been resolved by updating to a newer version of rules_go.

Are you still seeing this issue? Please reopen with more information if so.

**Comment by crazytan** [comment]
Yes it was resolved by using HEAD of rules_go. My original concern was that testing should have been done to prevent this from happening again, and I'll re-open this if I see this again. Thanks!
