### ISSUE TITLE
cpp fragment options don't seem to be used during stdlib compilation

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/rules_go#985]
https://github.com/bazelbuild/rules_go/blob/f08376e2826201ad8dfe664b07b564262f79ecf4/go/private/rules/stdlib.bzl#L103

But they're exported on the line linked to above. Is this intended?

If these options are accidentally not wired to CGO_CXXFLAGS, etc. then I believe that using them *and* ensuring they include -fPIC is needed to make it possible to use go's c-shared buildmode. I say this because I reimplemented most of this logic by hand before realizing that this may be the problematic line.

**Comment by nathantchan** [comment]
This same issue is creating problems for us when we try to use our own cc_toolchain_suite. We had to modify stdlib.bzl to extract the appropriate compiler and linker flags and pass them in to CGO_CPPFLAGS and CGO_LDFLAGS.
