### ISSUE TITLE
Extending Bazel Rules to execute other go tools

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#989]
Is there a good way to do this? For example I would like to run go generate which uses swagger to generate a swagger spec for a rest api. This tool uses godoc which must know about all dependencies. How can I run swagger from inside the go rules.

**Comment by bweston92** [comment]
Looking for something similar to generate go docs.

**Comment by jayconrod** [comment]
Sorry for not responding to this much, much earlier.

[`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) is a rule which can be used to gather all of the sources (generated and static) used to build a set of targets. It's a useful input for tools which expect a directory structure that looks like `GOPATH`. It returns a [`GoPath`](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst#gopath) provider which contains lot of useful metadata for rules. If you don't need something that looks like `GOPATH`, all of the Go rules return [`GoArchive`](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst#goarchive) which `go_path` is based on.

You may also find Kubernetes' [`go_genrule`](https://github.com/kubernetes/repo-infra/blob/master/defs/go.bzl) interesting.
