### ISSUE TITLE
What is the correct way to build a mac binary from linux

### ISSUE THREAD

**Issue by rlguarino** [bazelbuild/rules_go#994]
I can find a bunch of issues trying to build a linux binary on a mac, what about the other way around?

The documentation says --cpu controls the GOOS and GOARCH variables but I can't seem to make that work.

**Comment by rlguarino** [comment]
Thanks, That got me most of the way there but I still seem to be having an issue using grpc. First it wouldn't build without adding the `--features=pure` flag, I'm not really sure why its needed though. Now I'm getting this error: Seems that the external dependence wasn't build for darwin is that expected? I'm not including `com_github_golang_protobuf` myself, I'm using the one included to go rules by default.

```
platform/pyli/pkg/encoding/token/token.pb.go:16:8: import /home/ross/.cache/bazel/_bazel_ross/1d52a67fa668e48a23e5a2542f04d188/bazel-sandbox/341612419194706520/execroot/workspace/bazel-out/host/bin/external/com_github_golang_protobuf/proto/~pure_stripped~go_default_library~/github.com/golang/protobuf/proto.a: object is [linux amd64 go1.9.2 X:framepointer] expected [darwin amd64 go1.9.2 X:framepointer]
```

**Comment by rlguarino** [comment]
The first issue I had might be related to: https://github.com/bazelbuild/rules_go/issues/990

**Comment by ianthehat** [comment]
This should all be working now.
